### ISSUE TITLE
There’s no support for RISC-V assembler

### ISSUE THREAD

**Issue by afiskon** [radareorg/radare2#10001]
Hello,

I noticed that rasm2 disassembles RISC-V instructions successfully but can't assemble same instructions:

```
$ rasm2 -a riscv -d b70701001307a00ab7366e01
lui a5, 0x10
li a4, 170
lui a3, 0x16e3

$ rasm2 -a riscv 'lui a5, 0x10'
Cannot assemble 'lui a5, 0x10' at line 3
invalid
```

I'm using Arch Linux x64, radare2 was compiled from source using radare2-cutter-git AUR package ( https://aur.archlinux.org/packages/radare2-cutter-git/ ):

```
$ uname -a
Linux e733 4.16.5-1-ARCH #1 SMP PREEMPT Thu Apr 26 16:53:40 UTC 2018 x86_64 GNU/Linux
$ rasm2 -v
rasm2 2.6.0-git 18014 @ linux-x86-64 git.2.5.0-142-g1d4cd29ec
commit: 1d4cd29ec77cc3523f00572109fdf086b62b320a build: 2018-04-26__15:49:27
$ r2 -v
radare2 2.6.0-git 18014 @ linux-x86-64 git.2.5.0-142-g1d4cd29ec
commit: 1d4cd29ec77cc3523f00572109fdf086b62b320a build: 2018-04-26__15:49:27
$ gcc --version
gcc (GCC) 7.3.1 20180406
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Is it a bug or this feature is just not implemented yet?

**Comment by radare** [comment]
there’s no support for riscv assembler at all

$ rasm2 -L | grep risc
_dA_  32 64      riscv       GPL     RISC-V


there’a no ‘a’ in the first column

**Comment by afiskon** [comment]
Oh, OK. Is there anyone working on it currently? If not I could try to implement it.

**Comment by radare** [comment]
nobody afaik, all yours :)

**Comment by afiskon** [comment]
I explored the code a little bit and I got an impression that I'm not going to reuse current disassembly implementation. I would like to implement risc-v assembly/disassembly engine from scratch (fortunately this ISA is well documented and structured) and cover it with property-based tests.

Does this course of action sound OK? If the answer is yes, will it be OK to replace current risc-v disassembler to keep things consistent?

**Comment by Maijin** [comment]
What's the reason of not improving the current risc-v disassembler over reimplementing a new one?
Same question, why not using the binutils riscV then instead of reimplementing a new one?

**Comment by radare** [comment]
current riscv disassembler is ripped from GNU, and yes, gnu code is awful. dont even try to reuse the assembler implementation of gas, its even worst than trying to adjust the disassembler. ideally it should be theorically easy to adjunst the llvm-riscv code to work within capstone and then make r2 use capstone for disasm and analysis, but assembling will be lacking too because the llvm assembler is in c++ and we dont want that in r2land

**Comment by afiskon** [comment]
@Maijin I completely understand the desire to reuse existing code. But as always there are pros and cons.

Pros:
* The code _suppose to be_ working, well-tested, etc
* Time is saved

Cons:
* There is no fun in that :) And people write OSS for free in their spare time because it's fun.
* License issues. For libraries (not end products) I prefer MIT/BSD-style licenses so anyone could reuse it, including Radare2 project.
* Legacy code. You will be surprised what you can find in 10/20/... years old project - K&R C, 1500 lines long procedures, homebrewed atomics implementations, support of weird platforms like AIX, HP-UX, tests suites in Perl 5.8, Perl scripts that make MSVC project from Autotools project, etc. Sometimes it's simpler and faster just to throw the code away and rewrite it.
* If you want to change something in the side project you depend on the maintainers of this project, it's release cycle, has to deal with it's code style (which naturally uses tabs, limits line width to 80 characters, etc).
* Existing code can be written with different use cases in mind. It's not necessary good for Radare2.

**Comment by Maijin** [comment]
And there is no modern, maintained disassembler library in the MIT/BSD license available already?

If you want to reimplement the wheel go ahead, but please prioritize the assembler first so we don't end up with 2 not working disassembler and still no assembler. 

Make also sure that this current tests 
* https://github.com/radare/radare2-regressions/blob/master/new/db/asm/riscv_32 and
* https://github.com/radare/radare2-regressions/blob/master/t.formats/elf/elf-riscv64
will be passing in your new disassembler.

**Comment by radare** [comment]
im totally for doing things from scratch, but reusing helps avoiding dupped work.

lemme answer your dots

> On 4 May 2018, at 11:47, Aleksander Alekseev <notifications@github.com> wrote:
> 
> @Maijin <https://github.com/Maijin> I completely understand the desire to reuse existing code. But as always there are pros and cons.
> 
> Pros:
> 
> The code suppose to be working, well-tested, etc
> Time is saved
> Cons:
> 
> There is no fun in that :) And people write OSS for free in their spare time because it's fun.
+1
> License issues. For libraries (not end products) I prefer MIT/BSD-style licenses so anyone could reuse it, including Radare2 project.
+1, thats why we have —without-gpl configure flag, and thats why i said to do that in capstone
> Legacy code. You will be surprised what you can find in 10/20/... years old project - K&R C, 1500 lines long procedures, homebrewed atomics implementations, support of weird platforms like AIX, HP-UX, tests suites in Perl 5.8, Perl scripts that make MSVC project from Autotools project, etc. Sometimes it's simpler and faster just to throw the code away and rewrite it.
thats why we do continuous refactoring , break apis, rewrite things from scratch all the time, etc. r2 doesnt have “legacy” code. or at least we try to make all code “alive"
> If you want to change something in the side project you depend on the maintainers of this project, it's release cycle, has to deal with it's code style (which naturally uses tabs, limits line width to 80 characters, etc).

well, capstone is imho dead. after 3 years waiting for a release i lost all possible hope. But we use their repo and we apply a bunch of patches over it because tired of waiting., but yeah i understand this worrying

> Existing code can be written with different use cases in mind. It's not necessary good for Radare2.

**Comment by Maijin** [comment]
Yeah as said it's fine, but please prioritize assembler to avoid 2 broken disassembler and no assembler in the end.

**Comment by xermicus** [comment]
I'm interested in implementing the asm but I won't be able to do it (properly at least) before r2con

**Comment by radare** [comment]
👍
