### ISSUE TITLE
acr should autogenerate MAJOR/MINOR/MICRO variables from VERSION

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#10035]
We should expose those variables in a .h file from ACR. it's is funny how some other projects handle that:

```
shlr/lz4/lz4.h:#define LZ4_VERSION_NUMBER (LZ4_VERSION_MAJOR *100*100 + LZ4_VERSION_MINOR *100 + LZ4_VERSION_RELEASE)

#define LIBZIP_VERSION "0.11.1"
#define LIBZIP_VERSION_MAJOR 0
#define LIBZIP_VERSION_MINOR 11
#define LIBZIP_VERSION_MICRO 0
```

acr must define that variable prefix from the PKGNAME directive and split out the version string by chopping stuff after dash:

```
2.6.0-git -> MAJOR 2, MINOR 6, MICRO 0
```

**Comment by radare** [comment]
Dunno if meson is able to do that

**Comment by radare** [comment]
Related to https://github.com/frida/frida-core/issues/188

**Comment by ret2libc** [comment]
@trufae shouldn't this go to acr repository? I'm closing this for r2.

**Comment by trufae** [comment]
Its already implemented anyway
