### ISSUE TITLE
Invalid base address when connect to gdbserver

### ISSUE THREAD

**Issue by xOmenus** [radareorg/radare2#10052]
I emul mips system on qemu `sudo qemu-system-mips -kernel 'vmlinux-3.2.0-4-4kc-malta' -nographic -hda dlink.img -append "root=/dev/sda rw init=/init" -net nic -net tap`
And start my gdbserver listen on port. Then i opened another terminal and put command `r2 -AAA -B 0x00400000 -a mips -e bin.baddr=0x00400000 -e cfg.bigendian=true -e dbg.exe.path=/home/omenus/firmware/_20160114_1621_DIR_632_2.6.1_sdk-master.bin.extracted/squashfs-root/bin/resident -e asm.bits=32 -D gdb gdb://10.0.2.2:666/473`
The the base address of the binary given as wrong. This does not seem to be correct. The address of the first loadable segment in the binary is 0x00400000, and the entry point address (in other words, the address of _start) is 0x405090.

![r2_register](https://user-images.githubusercontent.com/24994261/39768159-33e2eb84-52f1-11e8-9c1e-46f87470c956.png)
![readelf](https://user-images.githubusercontent.com/24994261/39768411-e578f78a-52f1-11e8-9aed-574fd3080621.png)

 Radare2 output:
`read_packet: unpack failed
unpack: Invalid repeat`

OS `Linux 4.13.0-39-generic #44-Ubuntu SMP Thu Apr 5 14:25:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
r2 -v `radare2 2.6.0-git 18087 @ linux-x86-64 git.2.5.0-176-gcbe9a12be
commit: cbe9a12be2d1d8cc39b757b9034cb29ce097e768 build: 2018-05-04__22:24:54`
File rabin2 out: 
`arch     mips`
`binsz    102496`
`bintype  elf`
`bits     32`
`canary   false`
`class    ELF32`
`crypto   false`
`endian   big`
`havecode true`
`intrp    /lib/ld-uClibc.so.0`
`lang     c`
`linenum  false`
`lsyms    false`
`machine  MIPS R3000`
`maxopsz  16`
`minopsz  1`
`nx       false`
`os       linux`
`pcalign  0`
`pic      false`
`relocs   false`
`relro    no`
`rpath    NONE`
`static   false`
`stripped true`
`subsys   linux`
`va       true`

This stream file wireshark, when it connect to gdbserver [r2_stream.log](https://github.com/radare/radare2/files/1984309/r2_stream.log)
Valgrind log [trace.log](https://github.com/radare/radare2/files/1984720/trace.log)
This file : [resident.tar.gz](https://github.com/radare/radare2/files/1984328/resident.tar.gz)
gdbserver file [gdbserver.tar.gz](https://github.com/radare/radare2/files/1984733/gdbserver.tar.gz)

**Comment by XVilka** [comment]
@SrimantaBarua may help with this I think

**Comment by XVilka** [comment]
@xOmenus no need, he wrote/refactored this code, so if he has time - he will respond here.
