### ISSUE TITLE
r2 http server not shutting down gracefully

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#10381]
When using the http server, back-grounded, it does not shut down gracefully.

```
r2 ./test
 -- Have you seen the latest radare2 TV spot?
[0x00400470]> =h& 12345
Background http server started.
[0x00400470]> Starting http server...
open http://localhost:12345/
r2 -C http://localhost:12345/cmd/
[0x00400470]>
[0x00400470]> q
r_sys_mkdirp: fail '/home' of '/home/r2/.cache/radare2'
```

Basically, just turned on the http server in the background and quit. However, that last `q` simply hangs and i have to force kill r2 every time. The web server should gracefully shutdown when quitting radare.

**Comment by radare** [comment]
thestranger is fixing this now

**Comment by trufae** [comment]
it's another bug in tasks. and i dont expect anyone to fix that, so closing, as i plan to rewrite all this soon or late
