### ISSUE TITLE
Bytes field in disas json when opcode invalid

### ISSUE THREAD

**Issue by Usibre** [radareorg/radare2#10389]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Currently when an opcode is seen as invalid (in pdj), the json returned has no useful information apart from the size and the offset. However, I'd like to argue that the raw byte(s) are very useful as you can overcome some parts manually when this error occurs. Hence, it would be nice to have the 'bytes' section in the pdj command, so I can manually handle the bytes when radare2 fails to disassemble this instruction. 

Thanks!

**Comment by radare** [comment]
you can just send a PR fixing this, its only 1 line of code
