### ISSUE TITLE
FreeBSD buildfixes

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#10440]
Taken from https://svnweb.freebsd.org/ports/head/devel/radare2/Makefile?revision=463925&view=markup
1. Documentation building patch:
```
post-patch-DOCS-off:
--
34 | @${REINPLACE_CMD} -e 's\| install-doc \|\|g' \
35 | ${WRKSRC}/Makefile
```
2. SDB HOST_CC is not autodetected properly
```
MAKE_ENV+= HOST_CC=${CC}
```
Without it it tries to use GCC.

**Comment by radare** [comment]
Can we have the freebsd maintainer to send a pullreq for this? Killing install-doc is a bad idea

And the sdhostcc problem should be affecting other platforms if changed. So better have a pr

**Comment by MaskRay** [comment]
Alternatively, you can advocate meson and ask them to switch from configure to meson.

```
meson . release --buildtype=release --prefix=~/.config/radare2/prefix -Db_lundef=false
# b_lundef=false because `environ` is not in libc.so but in crt1.o, r_util .so will have an undefined reference
```

**Comment by unixfreaxjp** [comment]
> ask them to switch from configure to meson.

That will never gonna happen.

**Comment by Maijin** [comment]
https://www.freebsd.org/doc/en/books/porters-handbook/uses-meson.html

**Comment by unixfreaxjp** [comment]
@Maijin you haven't ever done build world yourself don't you? Copy pasta URL doesn't make you BSD men in a snap. I am telling you `configure` is in our heartbeat. I am twice your age and my first OS is BSD.

**Comment by unixfreaxjp** [comment]
I guess I am starting to script my own `stages build` scheme on r2 compilation for BSD, just in case some future problem. Just in case.

**Comment by XVilka** [comment]
Met this problem during setting up the autobuilds for FreeBSD here: https://builds.sr.ht/~xvilka/radare2

**Comment by Maijin** [comment]
Oh nice! Great finding @XVilka

**Comment by XVilka** [comment]
TODO: also run regression tests with these

**Comment by radare** [comment]
release is tonight, i though 1 year and a half was enough time to fix this

**Comment by unixfreaxjp** [comment]
can't compile. see: https://twitter.com/malwaremustd1e/status/1174702479432474625
please use the version check for older freebsd. Again, P L E A S E.
@radare @xvilka

**Comment by unixfreaxjp** [comment]
log:
```
CC PIC ht_pp.c
CC PIC ht_up.c
CC PIC set.c
LIB libsdb.so.1.4.1
CC binheap.c
CC mem.c
CC unum.c
CC str.c
CC hex.c
CC file.c
CC range.c
CC tinyrange.c
CC prof.c
CC cache.c
CC sys.c
CC buf.c
CC w32-sys.c
sys.c:314:2: warning: #warning TODO: r_sys_bt : unimplemented
sys.c: In function 'r_sys_perror_str':
sys.c:877: warning: ignoring #pragma push_macro
sys.c:880: warning: ignoring #pragma pop_macro
sys.c: In function 'r_sys_run_rop':
sys.c:1042: error: expected string literal before ')' token
CC ubase64.c
gmake[2]: *** [/usr/home/TEST/radare/radare2-TEST/libr/../global.mk:36: sys.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [../rules.mk:62: all] Error 2
gmake: *** [Makefile:58: all] Error 2
```
Reason: 
No legacies has that `r_sys_bt` on kernel, why not checking the version as previously done?

**Comment by unixfreaxjp** [comment]
example to code with checking versions: (libr/util/sys.c)
```asm
if defined(__FreeBSD__)
# include <sys/param.h>
# include <sys/sysctl.h>
# if __FreeBSD_version >= 1000000
#  define FREEBSD_WITH_BACKTRACE
# endif
#endif
```
ping @devnexen
cc: @radare @xvilka @unixfreaxjp
cc: @sonodam @tessyjp

**Comment by unixfreaxjp** [comment]
@devnexen yes, I also realized that now, below is the investigation result of the bug:


## I checked all source code:

git-5bb241711983c5d8b548c7980058f1dda67fb5d6 3.9.0 --> sys.c: In function 'r_sys_run_rop': sys.c:1042: error: expected string literal before ')' token
3.9.0  --> sys.c: In function 'r_sys_run_rop': sys.c:1042: error: expected string literal before ')' toke
3.8.0  --> sys.c: In function 'r_sys_run_rop': sys.c:1042: error: expected string literal before ')' toke
3.7.1  --> ctype.c:14: error: redefinition of typedef 'RParseCType'
           radare2-3.7.1/libr/include/r_parse.h:79: error: previous declaration of 'RParseCType' was here
3.7.0  --> no build error, the "r2" command line is inaccessible (install script problem)
3.6.0  --> perfect!

## The investigation result:

0. source code: radare2/libr/util/sys.c
1. function "r_sys_run_rop"
2. Start from mid August 2019
3. After 3.7.0 released.

## The problem source:

Ragg rop chain #13609 https://github.com/radareorg/radare2/pull/13609
by @scrapbird

## The solution proposed:

I think we need to add __FREEBSD_ check to exclude it from R_SYS_ASM_START_ROP code below:

```asm
  :
#ifdef __x86_64__
# ifdef _MSC_VER

#  define R_SYS_ASM_START_ROP() \
	 eprintf ("r_sys_run_rop: Unsupported arch\n");
# else
  :
```

cc: @radare @xvilka

**Comment by unixfreaxjp** [comment]
Checked. My box & legacies doesn't support `r_sys_run_rop` and somehow it was undetected, or to be precised, the FreeBSD detection for this feature is none. Below `ifdef` may help to exclude it. And only put supported version under `FREEBSD_SUPPORTED_ROP` to do those new ROP code stuff..
````
# if __FreeBSD_version >= 1000000
# define FREEBSD_SUPPORTED_ROP
````
@radare @XVilka @devnexen @scrapbird @unixfreaxjp
cc: @tessyjp @sonodam

**Comment by devnexen** [comment]
I may have a "slightly" better idea, I m building under FreeBSD 9.2 and realised it does not support this form of inline assembly.

**Comment by unixfreaxjp** [comment]
@devnexen 
Thank you for the reply.
Go for it, what’s good for 9.2 is good for mine too, got 9.3 custom here and above example works.

**Comment by devnexen** [comment]
Ok so I ll try 9.2 i386 (did tested only amd64) just saw the details of your ticket.

**Comment by unixfreaxjp** [comment]
for freebsd 9.3 and 10.4 is needed for many software dev have both arch each, others are 11 and 12 on each arch, the rest are the "others" bsd's.

**Comment by radare** [comment]
still not closeable?

**Comment by unixfreaxjp** [comment]
I put crond watch for FreeBSD 9.3,10, 11,12. Should I proceed tests down to r2dec and/or r2ghidra plugin for this compatibility or just core codes? I am aiming for build error. Please advise. Thank you
@radare @XVilka

**Comment by radare** [comment]
@unixfreaxjp you may open issues in the r2dec and r2ghidra repos with a build error message. the plan is to switch to the new testsuite after 4.2, and then we will be able to enable the BSD testsuite and eventually automatically build r2dec and r2ghidra too

**Comment by radare** [comment]
i think we can close this now that we are building r2 in freebsd in CI

**Comment by unixfreaxjp** [comment]
I can not upgrade BSD servers to fir to my criteria of tests due to COVID19 emergency situation. Sorry for delay. Basically as workaround I slowly test all one by one booting systems locally under VM and it is super slow. I will post issue if significant bug is spotted. So far none of those level.
See: https://github.com/radareorg/radare2/issues/11558#issuecomment-634276433
