### ISSUE TITLE
Add more magic signatures in libr/magic/d

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#10554]
Here's a nice list of them, media types like mp3/ogg are important too

* [ ] https://en.wikipedia.org/wiki/List_of_file_signatures
* [ ] https://blog.netspi.com/magic-bytes-identifying-common-file-formats-at-a-glance/

**Comment by unixfreaxjp** [comment]
I see several magics are doubled in `libr/magic/d`, I will make PR in stages (since there are so many to confirm) on new file database for unrecorded magic in forensics, with OpenBSD rules. @radare
