### ISSUE TITLE
Core Plugin to interdict command

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#10570]
It would be helpful for registered core plugins to have the ability to interdict a command.

For example, the core plugin could be an updated handler for comments. In this case, when it see's "CC " command come through, it may want to handle the command update and tell the radare core to mark this as completed. This way, you wouldn't be getting excess updates. This is the same method that Google's Android provides for intents and how you can use a different messaging application instead of the default one.

In my case, I'm trying to handle things like comments and flags, but at best i end up with duplicates because i handle it, then the core actually handles it as well.

This would likely require a special return type (like `EventHandled` or something), and also prioritization of who gets to see the command first.

**Comment by radare** [comment]
So when you say interdict you are refering to signal or event handlers?

**Comment by radare** [comment]
This is half planned to be implemented to do the undo/redo magic as well as the collaborative platform
