### ISSUE TITLE
ARM Thumb Emulation Fails to set Carry Bit

### ISSUE THREAD

**Issue by SpenserStyles** [radareorg/radare2#10577]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.13.5 64-bit
| File format of the file you reverse (mandatory)      | BIN
| Architecture/bits of the file (mandatory)            | ARM Cortex 16-bits
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.9 18640 @ darwin-x86-64 git.2.6.9 commit: 159d16b34550f4a83ee496839981c8316339ac4d build: 2018-07-02__11:32:1

### Expected behavior
Set carry flag when r2 is less then r3 in cmp r2, r3 instruction

### Actual behavior
Carry flag is not set correctly.

### Steps to reproduce the behavior 
[example.bin.zip](https://github.com/radare/radare2/files/2155968/example.bin.zip)
```
r2 -a arm -b 16 example.bin
omb 1 0x8000000
omr 1 0x80000
o malloc://0x20000 0x20000000
s 0x8001970
ahb 16
aaa
aei
aeip
```
Perform emulation and the comparison at 0x8001986 never sets the carry flag.

### Additional Logs, screenshots, source-code,  configuration dump, ...
![image](https://user-images.githubusercontent.com/31034116/42175211-c81a22a0-7df2-11e8-8632-87fecd92bcfc.png)

**Comment by radare** [comment]
Can you show the esil expression of those instructions? You can probably fix that yourself just changing that string in a pullreq

**Comment by SpenserStyles** [comment]
I made a change to the code to fix this issue

```
case ARM_INS_CMP:
		// r_strbuf_appendf (&op->esil, "%s,%s,==,$z,zf,=", ARG(1), ARG(0));
		r_strbuf_appendf (&op->esil, "%s,%s,==,$z,zf,=,$c31,cf,=", ARG(1), ARG(0));  // FIX TO CORRECTLY SET CARRY
		break;
```
It produces the modified esil @ 0x8001986 by including $c31,cf,= 
![image](https://user-images.githubusercontent.com/31034116/42325551-8fd93536-8034-11e8-8580-7ea312c735ca.png)
