### ISSUE TITLE
more unit tests in main repo

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#10636]
Probably it was discussed over IRC multiple times, but let's be clear about this and write things "on paper".

What do you think about including *unit tests* in the main repository? As usual, tests should be as close as possible to the tested code (thus in the main radare2 repository and not in r2r). They can be used to test whether the installation process was successful (e.g. in a RPM/DEB packaging you can run them to see if pkg-config files and libraries were installed correctly, without the need to download a separate repository). They should be written together with new code and or adapted when existing code is changed.

More unit tests, more stability, more examples of how to use APIs (which are many times *obscure*) and a lot of other benefits. Regressions tests are good to test the overall behaviour, but they do not help to keep the code base clean and good. Unit tests force you to think a bit more about *where* you need to change code.

Comments, thoughts, etc. are welcome!

**Comment by xarkes** [comment]
I agree with that, but only *unit tests* (not regressions one).
I think the ones [here](https://github.com/radare/radare2-regressions/tree/master/unit) are a very good start, and I also think it's a good idea to move them in the main repository.

Then I think one should be able to run the tests without *installing* radare2, but only by compiling and running them (and having no installation of r2 nowhere).

And as @ret2libc said, I think it will help improve the codebase over time. Although the regressions tests are necessary, I think unit tests are a requirement too for the good health of any project.

I think that's how most projects work and I agree with that.

**Comment by Maijin** [comment]
They used to be in radare2 repository scattered everywhere and that was a huge mess.

In any case they need to be rewritten in the new format https://github.com/radare/radare2-regressions/tree/master/unit/legacy_unit

**Comment by ret2libc** [comment]
@Maijin what was the mess coming from? What was the problem exactly?

**Comment by xarkes** [comment]
If the only mess was that they were scattered, there no reason to scatter them, we can just move the unit folder from r2r in r2 repo I think.

**Comment by Maijin** [comment]
@ret2libc @xarkes I'm just stating what was there before, it's not problem anymore but if we do switch back to r2, better not do scattering again 👍

**Comment by radare** [comment]
The new/ thing should run the unit tests otherwise we will have a bottleneck because they run in serial

**Comment by ret2libc** [comment]
The main request is to add those unit tests to the r2 repo. Being *unit* tests, they are very focused on one piece and very light. Indeed if you run:

```
time for i in $(find . -perm 775 -name 'test_*'); do ./${i} ; done
```

They are not even noticeable. They shouldn't take much since we shouldn't use them to load libraries or do any complicated analysis. I think before saying they are a bottleneck we should try.

**Comment by radare** [comment]
can we close this?

**Comment by ret2libc** [comment]
I would still love to have unit tests in the main repo... :(

**Comment by xarkes** [comment]
Me too :)
Just mv ./radare2-regression/unit ./radare2/

**Comment by radare** [comment]
can we close this?

**Comment by ret2libc** [comment]
Nothing has changed and nothing has been discussed, so no.

**Comment by Maijin** [comment]
Yes, this needs to be discussed.

**Comment by radare** [comment]
i think everybody have its own position on this. im against that :P

**Comment by xarkes** [comment]
Maybe we should vote?

**Comment by ret2libc** [comment]
Yeah, this can be closed as we agreed to move them in the repo :) good choice :P
