### ISSUE TITLE
Load `t` types in `-nn` mode

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#10637]
For now they are not loaded, which is not very useful when you inspect some unknown data format with `tp` commands.

**Comment by radare** [comment]
I think we should have a it or iT command to show the types info associated with the curtent binobj. Then use .it* to load them into the current session. And kill the -nn behaviour at some point which was a hack

**Comment by radare** [comment]
-nn must die, we have `pfo` and `iH*` and segments are used properly for most file formats and we should improve in that direction to kill -nn

**Comment by owenniles** [comment]
I noticed what I think is a similar issue. It seems like the `tk` command does not work when `.radare2rc` is loaded automatically at startup.

Steps to reproduce:

```
$ r2 -v
radare2 4.5.0-git 24495 @ linux-x86-64 git.4.4.0-82-gf1e113ca8
commit: f1e113ca8feee3e7caae85f535ab8ca1ef86dd6a build: 2020-04-24__15:04:20
$ cat ~/.radare2rc
# Change one of the configuration variables so that we can verify that the
# configuration file is actually loaded when we run r2
e asm.syntax=att

# It doesn't seem like any of the following commands get executed
tk char **=type
tk type.char **=p
tk type.char **.size=64
tk type.char **.pointto=char *
$ # We can manually load the configuration script with the -i flag
$ r2 -i ~/.radare2rc -
[0x00000000]> t~char **
char **
[0x00000000]> q
$ # But otherwise, the `tk` commands don't seem to be loaded properly
$ r2 -
[0x00000000]> e asm.syntax
att
[0x00000000]> t~char **
[0x00000000]> q
$
```

Am I missing something here? If not, does this deserve its own issue or can it live here?

**Comment by trufae** [comment]
bin types/structs are loaded as `pf` expressions, not struct defined types (yet) and c structs arent generated properly from the pf formats either:

```
[0x100001060]> pfc.mach0_header
struct mach0_header {
    int32_t magic; // 0xe5894855
    int32_t cputype; // 0x56415741
    int32_t cpusubtype; // 0x54415541
    enum filetype; //
    int32_t ncmds; // 1560
    int32_t sizeofcmds; // 1106741577
    struct flags {
}
[0x100001060]> td `pfc.mach0_header `
<string>:1: error: bracket expected
<string>:1: error: '}' expected (got "�")
No previous search done
No previous search done
No previous search done
No previous search done
No previous search done
No previous search done
[0x100001060]>
```

**Comment by trufae** [comment]
Fixed already
