### ISSUE TITLE
meson-ify radare2 build

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#10643]
meson is currently mainly used for the Windows build, but acr + make is still the preferred method on Linux. This meta-task groups all missing "features" in the meson build:

- [x] install headers
- [ ] install r2 link
- [x] install r2pm
- [x] allow user to use system zip library
- [x] allow user to use system capstone library
- [x] allow user to use system magic library
- [x] allow user to use system lz4 library
- [ ] integrate some of the special-handling done in sys/meson.py
- [ ] sdb should be declared as dependency only in shlr/sdb/meson.build and not twice (shlr/meson.build)
- [x] capstone should be downloaded and patched in the build dir, not in the source dir
- [ ] sdb_version.h should be created in the build dir, not in the source dir
- [ ] spp/config.h should be created in the build dir, not in the source dir 
- [x] when a system dependency is used, the internal dependency should not be specified in the Require of another pkgconfig file
- [ ] sign binaries/libraries when on OS X

**Comment by pelijah** [comment]
Is it not "install headers"? https://github.com/radare/radare2/blob/master/libr/meson.build#L311

**Comment by XVilka** [comment]
@ret2libc I think this can be closed, no?

**Comment by ret2libc** [comment]
Not yet. Tere are some points that still are not done (e.g. build SDK, sign binaries for OSX, use of subprojects, etc.)

**Comment by ret2libc** [comment]
Closing this. Let's open specific issues if/when needed.
