### ISSUE TITLE
Implement more RCons.Dietline M-* actions

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#10656]
Some from the [bash manual](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html)

8.4.4 Killing And Yanking

* [x] kill-line (C-k) Kill the text from point to the end of the line.
* [x] backward-kill-line (C-x Rubout) - Kill backward from the cursor to the beginning of the current line.
* [x] kill-whole-line (C-u) Kill all characters on the current line, no matter where point is. By default, this is unbound.
* [x] kill-word (C-t) - Kill from point to the end of the current word, or if between words, to the end of the next word. Word boundaries are the same as forward-word.
* [x] backward-kill-word (M-DEL)Kill the word behind point. Word boundaries are the same as backward-word.
* [x] shell-backward-kill-word (C-o) Kill the word behind point. Word boundaries are the same as shell-backward-word.
* [x] unix-word-rubout (C-w)Kill the word behind point, using white space as a word boundary. The killed text is saved on the kill-ring.
* [x] yank (C-y) Yank the top of the kill ring into the buffer at point.
* [x] yank-pop (C-]) Rotate the kill-ring, and yank the new top. You can only do this if the prior command is yank or yank-pop.

# Optional

* [ ] unix-filename-rubout ()Kill the word behind point, using white space and the slash character as the word boundaries. The killed text is saved on the kill-ring.
* [ ] shell-kill-word () Kill from point to the end of the current word, or if between words, to the end of the next word. Word boundaries are the same as shell-forward-word.
* [ ] delete-horizontal-space () Delete all spaces and tabs around point. By default, this is unbound.
* [ ] kill-region () Kill the text in the current region. By default, this command is unbound.
* [ ] copy-region-as-kill () Copy the text in the region to the kill buffer, so it can be yanked right away. By default, this command is unbound.
* [ ] copy-backward-word () Copy the word before point to the kill buffer. The word boundaries are the same as backward-word. By default, this command is unbound.
* [ ] copy-forward-word () Copy the word following point to the kill buffer. The word boundaries are the same as forward-word. By default, this command is unbound.

**Comment by TsarFox** [comment]
I believe that the following are already implemented:
- kill-line (C-k)
- unix-line-discard (C-u)
- kill-word (M-d)
- backward-kill-word (M-DEL)
- yank (C-y)

But implementing the rest of the actions you listed would be very useful.

Now that I see that Dietline supports yanking, though, I realize that my `kill-word` implementation isn't fully compliant -- it should also move the killed word into the clipboard, even though that isn't explicitly mentioned in the manual. A patch for tomorrow, I guess. I'm sleepy

**Comment by XVilka** [comment]
@TsarFox how was your sleep?

**Comment by TsarFox** [comment]
> @TsarFox how was your sleep?

If I remember correctly, I slept very well the night of July 8th, 2018 :)  Why do you ask? Is there renewed interest in addressing this issue? I thought #10677 addressed my implementation of `kill-word`, but it's been nearly a year and I sort of forget now.

**Comment by XVilka** [comment]
@TsarFox there is **always** an interest in fixing any issue in radare2.

**Comment by deepakchethan** [comment]
I will start working on this now. Dietline issues would be complete after this :)

**Comment by XVilka** [comment]
@deepakchethan don't forget to add them, once implemented in https://github.com/radare/radare2book/blob/master/basic_commands/dietline.md book chapter.

**Comment by XVilka** [comment]
All the most important were added and documented in the book.
