### ISSUE TITLE
Function line interrupts on some instructions

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#10700]
While it is being known to interrupt on "nop" instructions, here you can see the second interrupt on moves too, which is obviously wrong:

![screenshot_20180711_114358](https://user-images.githubusercontent.com/203261/42549649-d8839c2a-84ff-11e8-91c3-10e203636625.png)

[fedora28_ls_sample.zip](https://github.com/radare/radare2/files/2183435/fedora28_ls_sample.zip)

**Comment by radare** [comment]
Theres an xref rhere. In fact 57 of them. Provide the sample

**Comment by XVilka** [comment]
Added sample

**Comment by XVilka** [comment]
I think this is probably `sym.imp.abort()` marked as noreturn function.

**Comment by radare** [comment]
i see no abort

**Comment by XVilka** [comment]
@radare at 0x4151 offset

**Comment by cyanpencil** [comment]
I'm not exactly sure that the interruption of the function line is wrong...
As you said, the abort () function never returns; so the two movs and the jmp after the call to abort() are effectively unreachable?
