### ISSUE TITLE
arm disassembly for local vars not using sp

### ISSUE THREAD

**Issue by SpenserStyles** [radareorg/radare2#10729]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac 10.13.5 64-bit
| File format of the file you reverse (mandatory)      | BIN
| Architecture/bits of the file (mandatory)            | arm 32-bit cortex
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.9 18640 @ darwin-x86-64 git.2.6.9 commit: 159d16b34550f4a83ee496839981c8316339ac4d build: 2018-07-03__09:48:34

I'm disassembling a binary for a ARM cortex-m and it has functions that are using r7 as the sp.  Is there a way to make Radare rename the offsets as local_vars?

Below is an example of the prologue for a function where space is made on the stack and then r7 is used as the base address to access local vars.
```
push [r7]
sub sp, 8
mov r7, sp .  // R7 is now used to reference local vars
str r0, [r7] . // can I insert a local_var name here
str r1 [r7, 4] . // Can I replace 4 with local_var?
```

If not can this be done through a script?  Or does the code base need to be modified for a special extract_vars() function for arm?

**Comment by sivaramaaa** [comment]
> If not can this be done through a script? Or does the code base need to be modified for a special extract_vars() function for arm?

Afaik it's not possible yet , it needs change in code base

But i wanted to know how often this kind of scenario happens or is it just specific only to this binary ?

**Comment by SpenserStyles** [comment]
I believe this to be fairly common at least for cortex-m series.  I compiled the source using arm-none-eabi-gcc.  Also Ida handles this case.

**Comment by sivaramaaa** [comment]
Sure i will look into it !

**Comment by sivaramaaa** [comment]
Hey @SpenserStyles , can u provide this bin or even few bytes dump , so that i could repro this issue and try to work on a fix !

**Comment by sivaramaaa** [comment]
Ping2 @SpenserStyles , binary or reproducer pls !

**Comment by SpenserStyles** [comment]
Sorry for the delay.  Here is an example binary.
This is for an STM32F4 
Loading address: 0x8000000

Below is a snapshot of IDA disassembly at 0x80005f4.  You can see it loads SP into R7 then uses R7 at the reference for local vars.

![image](https://user-images.githubusercontent.com/31034116/44093324-3572df48-9fa1-11e8-8f4c-a0f6c25aaa3a.png)

[example.zip](https://github.com/radare/radare2/files/2286975/example.zip)
