### ISSUE TITLE
Simatic S7 (S7-200, S7-300, S7-400) instruction set support

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#10738]
[s7300_parameter_manual_en-US_en-US.pdf](https://github.com/radare/radare2/files/2197426/s7300_parameter_manual_en-US_en-US.pdf)
[STL-cheat-sheet-by-category.pdf](https://github.com/radare/radare2/files/2197430/STL-cheat-sheet-by-category.pdf)
[STL-cheat-sheet-by-alphabet.pdf](https://github.com/radare/radare2/files/2197431/STL-cheat-sheet-by-alphabet.pdf)
[S7-SW2.pdf](https://github.com/radare/radare2/files/2197432/S7-SW2.pdf)
[lv2017.pdf](https://github.com/radare/radare2/files/2811269/lv2017.pdf)

See also http://www.plcdev.com/statement_list_stl_cheat_sheets

**Comment by XVilka** [comment]
@montekki so, what do you think?

**Comment by XVilka** [comment]
Se also:
- https://www.pnfsoftware.com/jeb/plc
- https://arxiv.org/pdf/1812.03478.pdf
- https://github.com/momalab/ICSREF

**Comment by XVilka** [comment]
@wargio could you please transfer your https://github.com/wargio/libmc7 repo to "radareorg/? Then we can close this issue

**Comment by ret2libc** [comment]
Also, if you don't intend the to close this in a short time, please move it to radareorg/ideas.

**Comment by wargio** [comment]
> @wargio could you please transfer your https://github.com/wargio/libmc7 repo to "radareorg/? Then we can close this issue
done: https://github.com/radareorg/libmc7
Probably broken stuff: r2pm and Circle CI used in the repo
