### ISSUE TITLE
r2 scripts path are wrong

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#10759]
Scripts:
         system       ${R2_PREFIX}/share/radare2/radare2rc
         user         ~/.radare2rc ~/.config/radare2/radare2rc (and ~/.config/radare2/radare2rc.d/)
         file         ${filename}.r2

* .config? didnt we use .local now?
* system in share/ ?? shouldnt this be in etc/?

**Comment by radare** [comment]
what about ~/.local/etc

**Comment by ret2libc** [comment]
just created two new labels `meson` and `acr`, so we can tag issues with the build system used in the reported issue.

**Comment by pelijah** [comment]
`.local`? Since when? Nobody was against `.config` for storing r2 scripts in #9959.

**Comment by radare** [comment]
What do the standard say about .local/etc ?

Also for the global maybe /etc/radare2rc too?

**Comment by XVilka** [comment]
++ for "~/.local"

**Comment by radare** [comment]
Isnt this fixed already?

**Comment by MaskRay** [comment]
radare2-extras is still advertising ~/.config

**Comment by radare** [comment]
In the readme or where?

**Comment by radare** [comment]
isnt this fixed yet?

**Comment by ret2libc** [comment]
I don't even understand what's the problem here... can it be described better?
On my system I have everything under `~/.config/radare2`. Is this a problem? What would be the expected directory?

Also, what would be the right place for radare2rc?

**Comment by ret2libc** [comment]
No more acitvity here, problem is not clear either. Closing, but please re-open if necessary with more details.
