### ISSUE TITLE
[Feature request] `aesu` sub command to automatically skip JMP and CALLs

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#10784]
Currently, `aesu` hangs whenever it steps over a CALL to library functions like print, etc, so we use workarounds to skip these instructions.
It would be great to make a subcommand  to `aesu` in order to overcome this issue and make emulation smoother in these cases

**Comment by XVilka** [comment]
There was a workaround already, it is just disabled in the code
