### ISSUE TITLE
Understand shell octal strings format

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#10780]
In rax2, not only hexadecimal string, but also octal string, like
"\008\037\174\000"

**Comment by radare** [comment]
btw we should proabbly show some errors when the conversion is not valid:

rax 0888 -> 0x0

**Comment by XVilka** [comment]
I guess it works now? So we can close.

**Comment by radare** [comment]
Add a test begore closint

**Comment by ret2libc** [comment]
There is already in `test/db/tools/rax2`. Closing.
