### ISSUE TITLE
Function scope determined improperly

### ISSUE THREAD

**Issue by elicn** [radareorg/radare2#10824]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 19015 @ linux-x86-64 git.2.7.0-155-g4ac487310 commit: 4ac48731001400e290c124f2f2fdbd1d96bbf5a2 build: 2018-07-27__02:43:17

### Expected behavior
Function scope is expected to be identified correctly, that is, including all function's instructions.
### Actual behavior
In a case where a function uses multiple exit points (i.e. more than one `ret` instruction), the instructions past the first `ret` instruction are not considered part of the function, even though the function xrefs them.

Consider the following C snippet:
![snippet](https://user-images.githubusercontent.com/10291650/43295219-36e54c3e-914c-11e8-9da0-83e4af888668.png)

Disassembling the function yields only part of it: while the `else` clause is shown, the `if` clause is missing:
![bug](https://user-images.githubusercontent.com/10291650/43295288-a13d3efc-914c-11e8-905d-583f0b6906c0.png)

Disassembling a fixed amount of instructions showing the rest:
 ![expected](https://user-images.githubusercontent.com/10291650/43295313-d6745e52-914c-11e8-82b1-67b888aae8c1.png)

Although the wide `nop` instruction at 0x6e3 "breaks" the function, it seems that the function size should have been 62 instead of 35.

### Steps to reproduce the behavior 
- Attached an archive with source code and binary, reduced to relevant code only: 
[trunc.tar.gz](https://github.com/radare/radare2/files/2234009/trunc.tar.gz)
Binary compiled using gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

**Comment by radare** [comment]
Which command did you used to analyze this function? Also try swapping the value of the anal.endsize variable

**Comment by elicn** [comment]
I used the following command line to load the file: `r2 -A trunc`.
However, loading it with `r2 -e anal.endsize=false -A trunc` as suggested, seems to solve the problem.

**Comment by radare** [comment]
Feel free to add a testcase for this situation. We cant enable this option by default because it breaks other analysis situations so we must find the right way before removing this option

Thanks for testing

**Comment by elicn** [comment]
For what it's worth the problem no longer exists, regardless of the `anal.endsize` setting.

Version details:
radare2 4.5.0-git 25104 @ linux-x86-64 git.4.4.0-326-g7575d0525 commit: 7575d05252d051adbb0a62134ad7c21bbb9311ef build: 2020-06-23__15:25:50
