### ISSUE TITLE
remove libr/include/sdb/* header files

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#10867]
Given that we are including the sdb project in `shlr/sdb`, we don't need to copy all sdb files in `libr/include`. sdb should install its headers in `{prefix}/include/sdb` and radare2 should take them from there. r2 libraries that need sdb headers, should just reference the headers in their `shlr/sdb` location, not in `libr/include`, to avoid duplication.

**Comment by radare** [comment]
Sgtm but this implies many changes in makefiles, pkgconfig files and also in meson. The idea for embedding sdb was because the api/abi was not stable at the time so we didnt wanted to have more moving pieces.

**Comment by ret2libc** [comment]
Yes it would require some changes in makefiles, but in meson I’m already taking care of it with the active prs I have in sdb and in radare. They are not a lot of changes there fortunately

**Comment by ret2libc** [comment]
No need to track this..
