### ISSUE TITLE
is root needed to install radare2?

### ISSUE THREAD

**Issue by diehard88** [radareorg/radare2#10861]
this is my first installation.
I couldn't find any reference in r2's online documentation.
My specs:
- samsung tab 3 (sm-820)
- oreo
- termux
- no root

```
CC rax2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD rax2
CC rasm2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD rasm2
CC rabin2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD rabin2
CC rahash2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD rahash2
CC radiff2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD radiff2
CC radare2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD radare2
CC rafind2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD rafind2
CC rarun2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD rarun2
CC ragg2.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD ragg2
CC r2agent.c
clang-6.0: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
LD r2agent
NOTE: sudo not found. Please run as root: make symstall
```

thanks!

**Comment by radare** [comment]
termux already have r2 packaged. no need to build it by yourself. but if you want to install it you can use the NOSUDO=1 to skip that requirement and install in the given prefix with the current user

**Comment by diehard88** [comment]
perfect!

**Comment by Rexier-alt20** [comment]
Can u drop install command of radare2 witouth that root access
My device is not rooted

**Comment by trufae** [comment]
You dont need root to install r2 in termux. Maybe sys/termux.sh should be executed from sys/install.sh when running there

**Comment by trufae** [comment]
@apkunpacker can u confirm and submit fix?

**Comment by Rexier-alt20** [comment]
> You dont need root to install r2 in termux. Maybe sys/termux.sh should be executed from sys/install.sh when running there

![Screenshot_20231031-133855](https://github.com/radareorg/radare2/assets/148649383/f45c6e59-9d1b-4ee4-b436-602d7ecc2b0a)

How to fix this?  [This program is required.]
Nag ka error e

**Comment by apkunpacker** [comment]
> Can u drop install command of radare2 witouth that root access My device is not rooted

Hy installation of radare2 not require root.
There are 2 way to install r2 on termux -
1. Using default package manager to install r2 ( which is little bit older than master branch)
```sh
pkg update
pkg upgrade
pkg install radare2
```
after this r2 commands will be available in the commandline
2. If you want to build from master branch which is always latest
```sh
pkg update
pkg upgrade
pkg install build-essential git wget binutils
cd
git clone https://github.com/radareorg/radare2 --depth 1
cd radare2
sh sys/termux.sh
```
wait for 5-6 minutes to let it complete and r2 commands will be available in command line (Don't put termux in background during installation as newer android version give least priority to background task which slow download the installation)

**Comment by apkunpacker** [comment]
> > You dont need root to install r2 in termux. Maybe sys/termux.sh should be executed from sys/install.sh when running there
> 
> ![Screenshot_20231031-133855](https://user-images.githubusercontent.com/148649383/279269285-f45c6e59-9d1b-4ee4-b436-602d7ecc2b0a.jpg)
> 
> How to fix this? [This program is required.] Nag ka error e

```sh
pkg install binutils
```

**Comment by Rexier-alt20** [comment]
> > > You dont need root to install r2 in termux. Maybe sys/termux.sh should be executed from sys/install.sh when running there
> > 
> > 
> > ![Screenshot_20231031-133855](https://user-images.githubusercontent.com/148649383/279269285-f45c6e59-9d1b-4ee4-b436-602d7ecc2b0a.jpg)
> > How to fix this? [This program is required.] Nag ka error e
> 
> ```shell
> pkg install binutils
> ```

It work thankyou 🔥😊
Your an expert🔥
