### ISSUE TITLE
Long string not truncated in visual graph mode

### ISSUE THREAD

**Issue by d4em0n** [radareorg/radare2#10911]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | KDE Neon
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18892 @ linux-x86-64 git.2.7.0-193-g3524f8b commit: 3524f8b8cad210b7803d9807767be1103ccbea49 build: 2018-07-31__16:01:20

### Expected behavior
long string should be truncated

### Actual behavior
![screenshot_20180803_214102](https://user-images.githubusercontent.com/29397847/43649064-5784191e-9766-11e8-9fb1-0e2af0d818f1.png)

### Steps to reproduce the behavior 
enter to visual graph mode
### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
its not about long string, its about missing newlines in here. which may be shown as a multiline comment

**Comment by ret2libc** [comment]
I'm going to work on this for next release (4.6.0)

**Comment by trufae** [comment]
Reproducer:

```
$ r2 -
[0x00000000]> wx 90c3
[0x00000000]> af
[0x00000000]> CC very long comment nobody will care about reading it because its boooooooooring
[0x00000000]> af
[0x00000000]> agf
[0x00000000]>  # fcn.00000000 ();
 ─────────────────────────────────────────────────────────────────────────────────────────┐
│  0x0                                                                                    │
│ 1: fcn.00000000 ();                                                                     │
│    nop ; very long comment nobody will care about reading it because its boooooooooring │
└─────────────────────────────────────────────────────────────────────────────────────────┘
[0x00000000]>
```

**Comment by john-peterson** [comment]
I have symbol names from a c++ program

The class names are long and many symbols are long

The graph is several thousand pixels wide all the time

I'm looking in vain for a word wrap for graph

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/radare2/pull/22256
