### ISSUE TITLE
Radare2 Windows Debugging Invalid Output

### ISSUE THREAD

**Issue by visce** [radareorg/radare2#10913]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | 4.17.9-1-ARCH arm 64
| File format of the file you reverse (mandatory)      | sudo r2 -a x86 -b 32 -d  windbg:///tmp/win10.pipe
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 -v radare2 2.8.0-git 18851 @ linux-x86-64 git.2.7.0-164-g79bfcd8f6 commit: 79bfcd8 build: 2018-07-27__11:23:10
--

### Expected behavior
I have run radare2 with the sudo r2 -a x86 -b 32 -d  windbg:///tmp/win10.pipe command, and gotten a shell. I want to see assembly output where it says invalid.
### Actual behavior
I then type pd but the assembly output is invalid, I'd expect there to be output here. This even happens when I dpa to a process then pd, or even visual mode. 
### Steps to reproduce the behavior 
sudo r2 -a x86 -b 32 -d  windbg:///tmp/win10.pipe
> pd 20

### Additional Logs, screenshots, source-code,  configuration dump, ...

![radare2pd](https://user-images.githubusercontent.com/38126953/43653619-19b9ab0e-9738-11e8-959e-02b5d2c01b40.png)

**Comment by radare** [comment]
obviously at offset 0 there’s no memory allocated, see the maps. or the registers and seek there

**Comment by visce** [comment]
I've found registers with dr but I don't understand how I can the running assembly output. I've never used the maps. Are you talking about using o then the memory address?

**Comment by Maijin** [comment]
@radare his eip is on this offset too that's the problem

**Comment by radare** [comment]
is the register profile for windbg properly defined?

**Comment by visce** [comment]
I haven't found any documentation on the register profile. How would I go about setting this up?

**Comment by GustavoLCR** [comment]
I think this will also get fixed with #14666.
@visce can you please test after its merged?

**Comment by XVilka** [comment]
@visce ping?

**Comment by XVilka** [comment]
@GustavoLCR if you think this can be closed - please close. No response from the issue author.
