### ISSUE TITLE
Radare2 unexpectedly terminates when HTTP server recieves high-volume of traffic

### ISSUE THREAD

**Issue by JeremyWildsmith** [radareorg/radare2#10986]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 / x64 / 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0 0 @windows-x86-32 git Commit: unknown build 2018-08-07__12:27:49.79 (the latest download source from git, built by myself.)

### Expected behavior
- Radare2 continues to accept HTTP commands instead of terminating

### Actual behavior
- After many commands sent over HTTP, Radare2 terminates with an assertion fail error

### Steps to reproduce the behavior 
- Open radare and make accessible via HTTP by using command "=h5555"
- Connect to HTTP server hosted by radare on port 5555 and send high volume of commands
- Radare terminates after several commands due to assertion failure

### Additional source-code

Node JS Script I am running to reproduce the crash (in my actual nodejs app, it is stepping, not grabbing registers, but this is the easiest way to reproduce it)

```
'use strict';
const { promisify } = require('util');
var r2pipe = require('r2pipe');
 
var r2cmd = null;
var r2cmdj = null;

async function main() {
   
    var r2 = await promisify(r2pipe.connect)("http://localhost:5555/cmd/");
    r2cmd = promisify(r2.cmd);
    r2cmdj = promisify(r2.cmdj);
    while (true) {
        await r2cmdj("drj");
    }
}
 
main();
```

**Comment by radare** [comment]
assertion? can you provide a backtrace?

**Comment by JeremyWildsmith** [comment]
Assertion error appears to occur inside of C Runtime on call to dup2
```
 	ucrtbased.dll!028776f3()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for ucrtbased.dll]	
>	r_cons.dll!r_cons_pipe_close(int fd) Line 60	C
 	r_core.dll!r_core_cmd_str_pipe(r_core_t * core, const char * cmd) Line 3816	C
 	r_core.dll!r_core_rtr_http_run(r_core_t * core, int launch, int browse, const char * path) Line 686	C
 	r_core.dll!r_core_rtr_http(r_core_t * core, int launch, int browse, const char * path) Line 912	C
 	r_core.dll!cmd_rap(void * data, const char * input) Line 582	C
 	r_core.dll!r_cmd_call(r_cmd_t * cmd, const char * input) Line 237	C
 	r_core.dll!r_core_cmd_subst_i(r_core_t * core, char * cmd, char * colon, bool * tmpseek) Line 2899	C
 	r_core.dll!r_core_cmd_subst(r_core_t * core, char * cmd) Line 1928	C
 	r_core.dll!r_core_cmd(r_core_t * core, const char * cstr, int log) Line 3603	C
 	r_core.dll!r_core_prompt_exec(r_core_t * r) Line 2464	C
 	radare2.exe!main(int argc, char * * argv, char * * envp) Line 1378	C
 	[External Code]	
```

**Comment by JeremyWildsmith** [comment]
I looked at my temp directory and this definitely seems to have something to do with radare2 trashing my %temp% directory with CMDxxxx.tmp files. There are like 2000 CMDxxxx.tmp files in there.

I cleared my temp directory and I cannot seem to reproduce it so far. I'll let you know if I get it to occur again...

**Comment by JeremyWildsmith** [comment]
Yeah, after I let it run long enough, its failing now again at the same point. If I clear my temp directory it lasts longer.

**Comment by radare** [comment]
aah thats a bug in the way the output of commands is captured in some systems. i think i know where’s the problem and we can probably switch back to rcons instead of tmpfiles

**Comment by JeremyWildsmith** [comment]
Okay awesome, thanks. If theres anything else I can do to help, let me know.

**Comment by radare** [comment]
Can you check again? we have now a new implementation using libev. maybe you can check if this issue is gone when building r2 against this lib
