### ISSUE TITLE
Commit guidelines for the contributors

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#10991]
Is it possible to show those also before sending a PR?

**Comment by Maijin** [comment]
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by NishantPuri99** [comment]
Can I work on this? Thanks

**Comment by trufae** [comment]
Not sure if this is the pr template or some basic git usage already explained in the book. Seems like it can be closed to me

**Comment by NishantPuri99** [comment]
All right. Thank you
