### ISSUE TITLE
eprintf doesnt' goes through RCons

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11002]
One of the problems is that some eprintfs use ansi escape codes, so they dont work on windows.

imho one solution would be to avoid using ansi escape codes in stderr. 

![image 2018-08-09 13 11 57](https://user-images.githubusercontent.com/917142/43895487-cc37d7c8-9bd5-11e8-82c9-f72827f3e7a2.jpg)

**Comment by radare** [comment]
Another solution is to make eprintf go thru the unexistent RLog API and filter them out or use the w32 api/html etc when needed. but eprintf is for errors and status updates.. so i wouldnt use ansi escapes in there

**Comment by BackTrackCRoot** [comment]
The use of ConEmu is a temporary alternative.

**Comment by ret2libc** [comment]
And... why do we use eprintf in the first place?

I think something like https://github.com/radare/radare2/pull/11786 should solve this.
