### ISSUE TITLE
Binary reassembly

### ISSUE THREAD

**Issue by stevenagy** [radareorg/radare2#11155]
Hello,

I'm wanting to disassemble a binary, add in some new functionality, and reassemble it to a working binary. Does radare2 support this? 

Thanks,
-Steve

**Comment by radare** [comment]
U want to patch fee instructions or replace the whole thing? Because the r2 can do both but obviously both require manual interaction and review because there are zillions of ways to make this process fail

**Comment by stevenagy** [comment]
I'm wanting to insert some new instructions (ideally at the end of `.text`) and then insert a callback to these instructions right after `<main>`. Here's an example of what I'm trying to accomplish: https://github.com/shellphish/patcherex/issues/15#issue-350201936

**Comment by radare** [comment]
that doesnt requires reassembling the whole binary, just use rabin2 -O to resize the section. then put the code in there with r2. and depending on the order of the sections after resizing you will probablby need to rebase the binary which requires manual work to review all the memory accessses in the program code to be shifted

**Comment by stevenagy** [comment]
`and depending on the order of the sections after resizing you will probablby need to rebase the binary which requires manual work to review all the memory accessses in the program code to be shifted`
Could you explain this process some more? I'm not sure I totally understand. Based on the wiki I think I'd have to use `r2 -B <new_base_addr>`. How would I find the new base addr?

The binaries I'm looking to patch are fairly large. Would it be more practical to just accomplish this via reassembly?

**Comment by radare** [comment]
if they are large, just find a place where the code is not used or can be removed /moved reasily (unrolled loops, etc) and put the code in there

**Comment by stevenagy** [comment]
I specifically need it to be placed at the end of `.text`, and executed by `<main>`. If there's a way to disassemble and reassemble I think that would be easiest. Does r2 support this?

**Comment by MaskRay** [comment]
There are not many gaps (-falign-functions=n). .text may be followed by .init .fini .data (lld) .fini .rodata ...(ld.bfd,gold) If you cannot find space, hack .eh_frame .eh_frame_hdr if you don't use C++ exceptions.

Much human interaction is involved. I don't think r2 should and can support the feature out-of-the-box.

**Comment by stevenagy** [comment]
I guess what I'm asking is - can r2 disassemble a binary, and the resulting assembly code be used to re-assemble the same functional binary?

**Comment by radare** [comment]
No. The process is not as simple as you describe

**Comment by stevenagy** [comment]
> The process is not as simple as you describe
For assembly-level patching or for reassembly? 

Sorry for all the questions - I'm a noob trying to learn! :)

**Comment by counter-reverse** [comment]
If you expand the .text section and you do not take care of anything else you will most likely overwrite another section. I can only agree with radare on the fact it is a high level of difficulty. 

If you are interested in learn more about file modification I suggest you to take a look into the book "learning Linux binary analysis" by Ryan O'Neill. Please note that the book dry only with the Linux file formats.

**Comment by stevenagy** [comment]
Here is what I don't understand: I'm basically trying to replicate a well-established [static assembly-time patching approach](https://github.com/FoRTE-Research/afl/blob/master/afl-as.c). This technique just injects the patch's code in the compiler-generated assembly for the binary, and then uses the resulting new assembly to compile the patched binary. 

Assuming r2 supports disassembly, why is it impossible to adopt the same approach (e.g., injecting the patch's assembly into the disassembled binary's assembly) for reassembly?

**Comment by XVilka** [comment]
@stevenagy one of the biggest problems - distinct between constants and addresses. So to insert code you have to relocate some parts of the existing code, some of it will contain constants, which is impossible to decide with 100% certainty (especially automatically) if they should be changed according to the relocation, or not.

**Comment by counter-reverse** [comment]
If you absolutely want to do everything yourself, I can suggest you to code your own tool. Code from the book I suggested you could be a great approach to get basis for program such tool.

**Comment by stevenagy** [comment]
Got it. Thank you all for your help!
