### ISSUE TITLE
Unexpected behavior on hex search for big files (>2G)

### ISSUE THREAD

**Issue by arnaugamez** [radareorg/radare2#11162]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Xubuntu 18.04 x64
| File format of the file you reverse (mandatory)      | VDI (VirtualBox Disk Image)
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19223 @ linux-x86-64 git.2.8.0-144-g620affc89 commit: 620affc89e221951af71d07ca928c38a1010f59b build: 2018-08-20__11:22:27

I was dealing with analyzing some vbox disk images searching patterns and so but hex search was not working as expected so after many tests I think I have found why it was not working.

### Problem
Files with filesize greater that 2GB (2147483647 bytes) have weird behavior related to searches (I only tested with hex searches but I think problem may apply to other types as well)

For testing purposes and to illustrate the problem, I made two truncated files from the original VDI file, one of 2147483647 bytes size and the other of just one byte more, 2147483648 bytes size. The differences arise as following.

> Note that:
> 	- the file has '841e' hex pair of bytes at address 0x190
> 	- block size is 0x100 by default

### Expected behavior
With 2147483647 bytes file I have normal behavior as expected:

```
[0x00000000]> r
2147483647
[0x00000000]> b
0x100
[0x00000000]> s/x 841e
Searching 2 bytes in [0x1-0x7fffffff]
0x00000190 hit0_0 841e
```

Same applies if i make simple hex search with '/x 841e' it just finds lots of entries that actually have the correct value '841e' at the address found.

### Actual behavior
Now with 2147483648 bytes file things just don't work as expected/desired:

```
[0x00000000]> r
2147483648
[0x00000000]> b
0x100
[0x00000000]> s/x 841e
Searching 2 bytes in [0x1-0x80000000]
[# ]^C0x1348ff01 < 0x80000000  hits = 0   

hits: 0
Cannot seek to unknown address 'hit0_0'
[0x00000000]> b 0x190
[0x00000000]> s/x 841e
Searching 2 bytes in [0x1-0x80000000]
[# ]^C0x062f3271 < 0x80000000  hits = 0   

hits: 0
Cannot seek to unknown address 'hit1_0'
[0x00000000]> b 0x191
[0x00000000]> s/x 841e
Searching 2 bytes in [0x1-0x80000000]
0x00000190 hit2_0 3c3c
```

As you can see it does not find the value (neither the closest nor any other one) unless you make block size > (strictly greater than) the distance from the seek address you are to the first occurrence of the hex value you are looking for. Have to stop the search as it continues going without any hit.

Also you can see that it is weird that when it founds the value what is shown next to the hit flag (hit2_0 in this case) is the first N bytes (where N is the same number of bytes you were looking for) from the seek address you are, and not the actual value you were looking for and that was shown in files with <=2G size as expected.

### Additional comments
I guess it has something to do with the way r2 deals with huge files, were size becomes negative beyond 2G size. You can see that if you "ls -l" from r2 shell, the filesize reported for such big files is negative, as opposed to what is reported by system's ls and so.

Maybe is just a matter of environment configuration, but I did not find the way to make it working.

I guess this behavior will probably happen if searching for other stuff like magic /m or so, but did not have time to test exhaustively.

**Comment by radare** [comment]
$ r2 -e io.va <http://io.va/>=0 -n /dev/disk0
[0x00000000]> s/x 90
Searching 1 byte in [0x1-0xffffffffffffffff]
hits: 0
Cannot seek to unknown address 'hit0_0'
[0x00000000]>

the range (1-fff) is clearly wrong. but it also not working , seems to ignore search.in

there are a bunch of problems in here, and i guess all recents refactors are involved in this problem
