### ISSUE TITLE
Function not recognized after jump instruction

### ISSUE THREAD

**Issue by nsajko** [radareorg/radare2#11268]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux amd64 Intel x86-64
| File format of the file you reverse (mandatory)      | memory dump
| Architecture/bits of the file (mandatory)            | MSP430, 16 bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19222 @ linux-x86-64 git.2.8.0-221-g97e680833 commit: 97e6808335f5f7bbb79097e64b1aee0bbf17b3d7 build: 2018-08-26__17:27:48

### Expected behavior
Recognize whole function, including the part after the jump instruction.

### Actual behavior
The function parts starting with the address jumped to (jmp $+0x00e8) are not recognized as part of the function, instead they are just autonamed loc.0000xxxx. Note that this is worse than it sounds because you get nothing after 'jmp $+0x00e8' in the graph view, so the graph view is useless.

### Steps to reproduce the behavior 
https://asciinema.org/a/PuRZC0EaeyzaCcq7Jk3cgR9TJ

**Comment by nsajko** [comment]
I can try to fix this if I get some hints ...

I suspect this has something to do with some limit on (noncontiguous) function length.

**Comment by nsajko** [comment]
Can somebody shed some light on this issue? Is it just a misconfiguration or a bug? What is up with the loc.0000xxxx parts?

**Comment by radare** [comment]
If u enable anal.hasnext the analysis will go beyond the end of functions to find more. Didnt tried to reproduce your issue but maybe that helps

**Comment by nsajko** [comment]
Thanks, but that did not help. Just marked a bunch of functions immediately after the 'jmp $+0x00e8', with each function ending at a jump.

**Comment by XVilka** [comment]
Can you craft a testcase for radare2-regressions?

**Comment by nsajko** [comment]
I extracted the relevant part of the binary so there would be a convenient way to reproduce:

```
r2 -
e asm.arch=msp430
e asm.bits=16
wx 324000a0b01210000c4f3cf0fe0f3c5000e00a4b3f4a0012733c8c4f00003f4a00126e3c8c4f02003f4a0012693c8c4f04007ff01f003f53fe233f4a0012603c8c4f06003f4a00125b3c8c4f08003f4a0012563c8c4f0a003f4a0012513c8c4f0c000e4c013c9f4f0e4c0d403d500c00013c9d4e3241004c02123e801541013c12b08e4315418e4317418e4319418e431b418e431d418e431f418e4321410b4c3b8094313c4028463c505000324000a0b01210000f530d4f3df0f01f3d5000503090008002343d5000303c80be440e400d123e80c8000e120f4e0c12bd4e00002d532c830c93fa233c413e413c40dc008e4300002e532c830c93fa233d41004d013c9f4f0e4a8e10013c95803e80d204013c91a10e520e10013cfb900eaa013cd1a10e11013cc1d00e102ea0013cd1a10e520e10013cfb902e500e10013cd1a10e10013cd1a10fee013cd0c13e412e53013c9f4f004e013cd1a13e41013cd1a1
af
```
