### ISSUE TITLE
Add ! suffix as an alias for blocksize/space

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11318]
right now we can do
```
x@10!2
```
but some people expect this to be valid too:
```
x!2@10
```
when it should be like this:
```
x 2@10
```

if we use ! as an explicit suffix that specifies blocksize we can write commands without spaces and also be more consistent with that bang syntax.

What do you think?

**Comment by MaskRay** [comment]
Isn't this too wasteful to use a precious metacharacter ! for this minor feature (blocksize)? What if you later come out a better use for `!`?

**Comment by radare** [comment]
all the feedback i got was negative, will wait to see more comments before taking a decision

**Comment by ret2libc** [comment]
I guess it can be closed given the negative feedback received 2 years ago and given nobody else replied.
