### ISSUE TITLE
Clean or remove some sys/* installation helper scripts

### ISSUE THREAD

**Issue by MaskRay** [radareorg/radare2#11350]
Most users will not notice them.

Even if they do, some are outdated or do things users might not like (e.g. installing to a specific path).

Most are underspecified and provide values no higher than a wiki page or well-organized documentation. For some toolchains or bizarre setup, the installation steps are destined to not be as easy as a onekey install. Interactions are involved but many of these scripts cannot help.

A wiki page (which also eases user contribution) may do a better job

Again, in case r2con users can't find a good topic for small talk :)

**Comment by radare** [comment]
Can you be more specific on which files to remove or change?

wiki pages has been removed in order to focus on the book.

Yes, i guess this seems like a good topic to discuss or attendees to check

**Comment by MaskRay** [comment]
@kij Yes, that is the purpose of this issue.

**Comment by radare** [comment]
I have removed sys/gtk*, @Maijin was testing an n900 yesterday, maybe he can share his experience with sys/maemo.sh, it is used to create the deb package. imho will be good to keep it up, but i dont have my n900 anymore :(

About menu.sh will be good to add some love in there, and make it support meson too. i did it ala-linux style, and i though people would like it, but doesnt seems to get much acceptance or at least most people seems to ignore its existence.

**Comment by radare** [comment]
install-su.sh should be deleted, but i have implemented it inside install.sh. so i killed it

**Comment by radare** [comment]
moar comments pls (:
