### ISSUE TITLE
Bad ESIL with vectorial instructions in x86

### ISSUE THREAD

**Issue by quim0** [radareorg/radare2#11421]
```
radare2 3.0.0-git 19475 @ darwin-x86-64 git.2.9.0-16-g09e8ccead
commit: 09e8ccead33cb28f6d1aff1db05a9205148081b5 build: 2018-09-06__16:18:45
```

### Expected behavior

Vectorial instructions perform the operation on each element of the vector. One example from the intel documentation:

Instruction: `addpd xmm, xmm`
Correct behavior:
```
FOR j := 0 to 1
	i := j*64
	dst[i+63:i] := a[i+63:i] + b[i+63:i]
ENDFOR
```

More: https://www.felixcloutier.com/x86/ADDPS.html

### Actual behavior

ESIL expression is wrong:

```
addpd xmm0, xmmword [local_30h]
0x30,rbp,-,[16],xmm0,+=
```

And the same with most of the vectorial instructions that are not load and store (when they're implemented).

### Steps to reproduce the behavior 

```
#include <emmintrin.h>

int main(void) {
    __m128d test = _mm_setzero_pd();
    __m128d test1 = _mm_setzero_pd();
    test = _mm_add_pd (test, test1);
}
```

Compile without optimization `clang test.c -o test`, and look at the ESIL output of the vectorial instructions.

**Comment by radare** [comment]
packed registers are operated as packs, no need to do loops here

**Comment by radare** [comment]
but yes, there are a bunch of missing mmx/sse instructions to be supported

**Comment by quim0** [comment]
But ESIL code is just making one "+" operation, and it must do two in this case. With just the ESIL there's no way to know if `xmm0` is a packed, and how it's packed (4 simple precision floats, 2 double precision floats...).

**Comment by radare** [comment]
Fair enough

**Comment by XVilka** [comment]
This is why I suggested to implement bignums instead. In my opinion ESIL shouldn't care about packed/not packed things: https://github.com/radare/radare2/issues/6093
