### ISSUE TITLE
AVR arguments are not captured by af/ aftm

### ISSUE THREAD

**Issue by oddcoder** [radareorg/radare2#11468]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | gentoo x86
| File format of the file you reverse (mandatory)      | AVR ROM.
| Architecture/bits of the file (mandatory)            | AVR 8Bits
| r2 -v full output, **not truncated** (mandatory)     |radare2 3.0.0-git 19416 @ linux-x86-64 git.2.9.0-44-g1e429810e commit: 1e429810eb233e38c2462db7be3fd95f6f8d6d07 build: 2018-09-08__19:22:21

### Expected behavior
Register based arguments gets caught by auto-analysis
### Actual behavior
They are never caught.
### Steps to reproduce the behavior 
This is the used binary: [flash_blc.bin.zip](https://github.com/radare/radare2/files/2364141/flash_blc.bin.zip)

```
➜  Telegram Desktop r2 flash_blc.bin
[0x00000026]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[Value from 0x00000000 to 0x00001f42
aav: 0x00000000-0x00001f42 in 0x0-0x1f42
[SPM: I dont know what to do with SPMCSR 1f26.
SPM: I dont know what to do with SPMCSR 1ef8.
SPM: I dont know what to do with SPMCSR 1f26.
[x] Analyze function calls (aac)
[SPM: I dont know what to do with SPMCSR 1ef8.rences (aar)
SPM: I dont know what to do with SPMCSR 1f26.
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
SPM: I dont know what to do with SPMCSR 1f26.
[SPM: I dont know what to do with SPMCSR 00. (afta)
[x] Type matching analysis for all functions (afta)
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x00000026]>  s fcn.00001ac8 
[0x00001ac8]> pdf
╭ (fcn) fcn.00001ac8 10
│   fcn.00001ac8 ();
│           ; CALL XREF from fcn.00000162 (0x19e)
│           0x00001ac8      dc01           movw r26, r24
│           0x00001aca      cb01           movw r24, r22
╰           0x00001acc      fc01           movw r30, r24
│           ; CODE XREF from fcn.00001ac8 (0x1ad0)
│       ╭─> 0x00001ace      e199           sbic 0x1c, 1
│       ╰─< 0x00001ad0      fecf           rjmp 0x1ace
[0x00001ac8]>
```
r24 and r22 are supposed to be register arguments (and r26 should be too according to the calling convention `avr` but it is ignored here)

**Comment by oddcoder** [comment]
CC @brainstorm, @sivaramaaa

**Comment by brainstorm** [comment]
For context, `radare2/libr/anal/d/cc-avr-8.sdb.txt` was modified to accomodate those variations in the sdb config files:

```
avr_mem=cc
cc.avr_mem.name=avr_mem
cc.avr_mem.argn=stack
cc.avr_mem.ret=r24
```

But there was no effect... according to [the radare avr workshop](https://radare.org/get/avrworkshops2016.pdf) by @dukebarman et al, those conventions mentioned are compiler-dependent, so I'm not entirely sure if the expected behavior is really expected (since the binary is almost for sure not compiled with GCC).

**Comment by dukebarman** [comment]
Better to ask @Darkkey I'm not sure too.

**Comment by XVilka** [comment]
@oddcoder can you please craft a testcase for radare2-regressions?

**Comment by oddcoder** [comment]
I am not sure how the exact behavior would look like, perhaps someone more antiquated with AVR should do it. I just opened the issue because I was referred to this bug

**Comment by brainstorm** [comment]
I bet @killabytenow is quite versed on most typical calling conventions for AVR and (non-)GCC compilers? I'm unsure on which registers and calling conventions are actually used for that firmware after reading through https://radare.org/get/avrworkshops2016.pdf and looking at the actual assembly of that .bin attached above :/
