### ISSUE TITLE
Problems resolving imported functions in PowerPC

### ISSUE THREAD

**Issue by jstucke** [radareorg/radare2#11495]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Mint 19, x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | PowerPC (32)
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19519 @ linux-x86-64 git.2.9.0-61-g7f816f53d commit: 7f816f53dbd37a500d922a562c3aa285932ae3fa build: 2018-09-12__10:49:23

### Actual behavior
The imports do not get resolved correctly.

I'm not really an expert regarding powerpc but the PLT entries of this binary [dropbear_powerpc.zip](https://github.com/radare/radare2/files/2374339/dropbear_powerpc.zip) look different from older versions of the same program and it seems radare is not able to resolve the import calls correctly:
```
# PLT stub
/ (fcn) fcn.0002dca0 12                                                                                             
|   fcn.0002dca0 ();                                                                                                
|           ; XREFS: CALL 0x00015ff0  CALL 0x00015ffc  CALL 0x00016008  CALL 0x0001615c  CALL 0x00016168            
|           ; XREFS: CALL 0x00016304  CALL 0x00016310                                                               
|           0x0002dca0      r11 = word[r30 - 0x7938]                                                                
|           0x0002dca4      ctr = r11                                                                               
\           0x0002dca8      goto ctr                                                                                
            0x0002dcac      .dword 0x60000000
```

The same import in an older version:
```
/ (fcn) sym.imp.free 16                                                                                             
|   sym.imp.free ();                                                                                                
|           ; XREFS(185)                                                                                            
|           0x1002c820      3d601005       r11 = (0x1005 << 16)                                                     
|           0x1002c824      816b003c       r11 = word[r11 + 0x3c]                                                   
|           0x1002c828      7d6903a6       ctr = r11                                                                
\           0x1002c82c      4e800420       goto ctr
```

Some functions get (correcly?) resolved as something like `loc.00008000.got2.plt_pic32.fsync__GLIBC_2.0`, others get wrongly resolved as other imports (when compared to the same binary compiled as x64 where everything seems to work without problems) and others don't get resolved at all (`fcn.XXXXXXXX`).

If anyone knows what is going wrong here or even how to fix it, I would be glad. I can provide the x64 binary and the older version if anyone is interested.

### Steps to reproduce the behavior 
- Analyzing [dropbear_powerpc.zip](https://github.com/radare/radare2/files/2374339/dropbear_powerpc.zip) with radare2 (aaa)

**Comment by XVilka** [comment]
Seems https://github.com/radare/radare2/pull/10526 and https://github.com/radare/radare2/issues/9825 are related

**Comment by XVilka** [comment]
@radare one more testcase

**Comment by trufae** [comment]
No need for tests. this works well
