### ISSUE TITLE
*BSD autobuilds in CI

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#11558]
https://www.freebsdnews.com/2016/10/07/running-freebsd-travis-ci/
or setup in ci.rada.re

**Comment by Maijin** [comment]
Qemu based sounds like it'll be very slow in travis definitely bad idea as it will slow down all the commits/PR tests.

In Ci.rada.re however would be adapted 👍

**Comment by XVilka** [comment]
Also Cirrus CI supports FreeBSD VMs https://cirrus-ci.org/guide/FreeBSD/

**Comment by XVilka** [comment]
Created feature request in Travis CI forum as well https://travis-ci.community/t/freebsd-vms-support/2125

**Comment by XVilka** [comment]
Created feature request in Azure Pipelines https://developercommunity.visualstudio.com/idea/449932/support-freebsd-andor-other-bsd-systems-vms.html

Now we only can wait.

**Comment by XVilka** [comment]
SourceHut already supports FreeBSD and OpenBSD, so we can try to setup it https://builds.sr.ht/

**Comment by XVilka** [comment]
I pushed the basic builds support in the master, and you can track the status of the builds here: https://builds.sr.ht/~xvilka/radare2

Once we figure how to integrate properly (there is some problem with @radare being personal account), we will enable autobuilds for master and pull requests.

**Comment by XVilka** [comment]
@krytarowski by the way, you might want to check out NetBSD support for SourceHut - it seems already in work-in-progress.

**Comment by krytarowski** [comment]
My role is to feedback patches for NetBSD. Please setup CI yourself.

**Comment by XVilka** [comment]
@krytarowski I didn't suggest you to setup CI or something, sorry if it sounded like that. I just though you might be interested that sr.ht will add NetBSD builds soon too.

**Comment by XVilka** [comment]
GitHub integration depends on this issue: https://github.com/radare/radare2/issues/13263
Otherwise GitHub API doesn't allow to integrate it with my SourceHut account due to a limitations.

**Comment by XVilka** [comment]
Ok, everything is done, the missing things are:
- NetBSD build (waiting for the SourceHut for that)
- Running regression tests for FreeBSD and OpenBSD jobs

**Comment by XVilka** [comment]
@devnexen can you please add the regression tests in these builds? Since you have local BSD installation it might be easier for you to setup.

**Comment by unixfreaxjp** [comment]
> the missing things are:

Please support FreeBSD 9,10,11,12 or r2 must make public announcement saying that ONLY released FreeBSD versions that are supported.

Each has different kernels, you know we dealt a lot with those compats in C syntax or with kernel libraries a lot.

Many bsd coders and control systems are on freebsd9 FYI.

**Comment by devnexen** [comment]
@unixfreaxjp what is your lowest version ? FreeBSD 9.0 or upper ?

**Comment by XVilka** [comment]
@unixfreaxjp sadly it's a third-party service, so we don't have control over the used versions. From https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd you can see this CI supports only 11.x, 12.x and CURRENT FreeBSD versions, and OpenBSD 6.5 only.

**Comment by devnexen** [comment]
Ah yes that makes sense, supports non EOL versions.

**Comment by devnexen** [comment]
Started for FreeBSD here https://github.com/radareorg/radare2/pull/15089 will start OpenBSD soon-ish.

**Comment by unixfreaxjp** [comment]
> will start OpenBSD soon-ish.

I have OpenBSD 6.3 running, but don't use it for r2 tests yet. Some more embedded ones with NetBSD too.. My hands is full (actually is lagging) with FreeBSD tests (x86 or x64) & linux (multi cpu arch) at the moment 

> CI supports only 11.x, 12.x

Will do the focus on 9 and 10, already run the cron+mail but seems has not enough time to check them too.. will do it better. You dev guys coded so much, we test folks is dying.. :)

**Comment by unixfreaxjp** [comment]
Just a memo, this is the stuff that I planned to test for year 2020, made this in Dec 2019.
## radare2 for servers - test result
```
FreeBSD 9 :  unsupported, see: https://twitter.com/malwaremustd1e/status/1211930394628509697
FreeBSD 10 : unsupported , see: https://twitter.com/malwaremustd1e/status/1211930394628509697
FreeBSD 12 : core : ok , r2ghidra: NG, r2dec NG 
FreeBSD 11 : core : ok , r2ghidra: NG, r2dec NG 
Debian Wheezy: unsupported, see: https://twitter.com/malwaremustd1e/status/1215954152137740288
Debian Jessie: core : ok , r2ghidra: NG, r2dec OK 
Debian Stretch core : ok , r2ghidra: NG, r2dec OK 
Debian Buster: core: ok, r2ghidra: PENDING, r2dec PENDING 

Note:
- All above tests are for x64. x32 tests is on uncommitted status.
- r2ghidra failed on debian compilation is on usage of "isnan","isinf" < amiguous,
- r2 ghidra failed on BSD platform in cpp libs compatibility
- r2dec problem is on the "duktape" for overall BSD Tests 
- for FreeBSDx32 is now unsupported, see: https://twitter.com/malwaremustd1e/status/1211930394628509697
- Tests for Debian Stretch x32 is uncommitted anymore., but below is result: 
  Debian Stretch x86 core : ok , r2ghidra: NG, r2dec OK
- The OpenBSD is under test after upgrade, now it is still unset for tests.. 
- NetBSD is still untouched. 
- version tested:
~/radare2-STABLE]$ r2 -v
radare2 4.2.0-git 23842 @ freebsd-x86-64 git.4.1.1-128-g3c788a496
commit: 3c788a49674d2e1c0e8ddbe6cce52ab4a9bcf818 build: 2020-01-16__14:06:39
````
Thu Jan 16 14:30:32 JST 2020 @unxifreaxjp
