### ISSUE TITLE
Fix all the GNU-based RAsm plugins to use RStrBuf properly

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11605]
Like i did for arc, arm.gnu...

See those as inspiration:

* d86ddacca97eb9151a8242feb4348d685a9ec97e
* c8fbb88e01e8500e40b67ff162536c92c32c00fe
* ...

**Comment by pelijah** [comment]
Isn't it better to use `r_strbuf_appendf()` instead of explicit `sprintf()` to temp buf?
Example: https://github.com/radare/radare2/blob/master/libr/asm/p/asm_arm_gnu.c#L99

**Comment by radare** [comment]
Yep
