### ISSUE TITLE
RMemPool

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11616]
Ive been testing it and found a bunch of issues and only used in 1 place. SO i would go for killing it.

* Allocated blocks are not aligned in memory
* Overflow may happen because nodesize is not used to ensure poolsize is in sync
* No unallocation method

Originally the idea of RMemPool was based on GLib's Slices:
*  https://developer.gnome.org/glib/stable/glib-Memory-Slices.html

But instead of having a global pool, just one controlled by the user. But our implementation doesnt uses memalign and fails with ubsan in different ways.

I vote for removing it, or not use it until we get it properly implemented. Also, my benchmarks seems to not be much different compared to malloc/free. at least in macOS, seems like the heap implementation is fast enough to perform as well as mempools. so its probably not necessary to go that finegrained when we can rely on libc.

**Comment by radare** [comment]
random hacky fix
```
diff --git a/libr/util/pool.c b/libr/util/pool.c
index c622be4ba..37216b1cb 100644
--- a/libr/util/pool.c
+++ b/libr/util/pool.c
@@ -54,7 +54,7 @@ R_API void *r_mem_pool_alloc(RMemoryPool *pool) {
        if (!pool) {
                return NULL;
        }
-       if (pool->ncount >= pool->poolsize) {
+       if (((pool->ncount+1) * pool->nodesize) >= pool->poolsize) {
                if (++pool->npool >= pool->poolcount) {
                        eprintf ("FAIL: Cannot allocate more memory in the pool\n");
                        return NULL;
@@ -66,7 +66,9 @@ R_API void *r_mem_pool_alloc(RMemoryPool *pool) {
                pool->ncount = 0;
        }
        // TODO: fix warning
-       return (void *) (&(pool->nodes[pool->npool][pool->ncount++]));
+       ut8 *p = (ut8*)&(pool->nodes[pool->npool]);
+       return p + (pool->nodesize * pool->ncount++);
+       // return (void *) (&(pool->nodes[pool->npool][pool->ncount++]));
 }

```

**Comment by radare** [comment]
the PR  was basically removing the use of rmempool. but rmempool is buggy and its still there. so we must decide in killing it or fixing it

**Comment by radare** [comment]
and maybe we can have this inside Sdb, for perfomrance reasons

**Comment by trufae** [comment]
This issue was fixed already. Pool.c no longer exists in util
