### ISSUE TITLE
Support --without-gpl in meson

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11666]

**Comment by ret2libc** [comment]
A random question: isn't the code already GPL ? Why do we need a flag to exclude GPL code? (apart from that, the change is very very easy, i'm just curious)

**Comment by radare** [comment]
> On 26 Sep 2018, at 13:12, Riccardo Schirone <notifications@github.com> wrote:
> 
> A random question: isn't the code already GPL ?
> 

No. R2 is LGPL

> Why do we need a flag to exclude GPL code? (apart from that, the change is very very easy, i'm just curious)
> 

Because gpl is incompatible with lgpl. And companies who build products with statically linked r2 cant ship gpl code or they will be forced to opensource the whole solution

**Comment by pelijah** [comment]
I found some LGPL plugins that are not included to `plugins.nogpl.cfg`.
About GPL: r2 includes some code marked as GPL even with `--without-gpl` option (e.g. https://github.com/radare/radare2/blob/master/libr/hash/hamdist.c). Is it legal? I am just wondering. I'm not good at it.

**Comment by radare** [comment]
If its just hamdist im the owner and ill relicense to mit after lunch

**Comment by pelijah** [comment]
And what about https://github.com/radare/radare2/blob/master/libr/hash/md4.c?

**Comment by radare** [comment]
What about making a list instead of randomly pasting filenames?

**Comment by radare** [comment]
i fixed those you mentioned

**Comment by pelijah** [comment]
List of plugins marked as LGPL but not included to `plugins.nogpl.cfg` (need validation):
```
anal.6502
anal.arm_gnu
anal.avr
anal.chip8
anal.cris
anal.i4004
anal.mcore
anal.mips_gnu
anal.nios2
anal.pic
anal.ppc_gnu
anal.propeller
anal.rsp
anal.sh
anal.snes
anal.sparc_gnu
anal.v810
anal.vax
anal.wasm
anal.xtensa
asm.arm_as
asm.chip8
asm.gas
asm.lh5801
asm.mcore
asm.mcs96
asm.pic
asm.propeller
asm.rsp
asm.v810
asm.x86_as
asm.x86_nasm
bin.art
bin.avr
bin.bflt
bin.bootimg
bin.cgc
bin.dyldcache
bin.mbn
bin.mdmp
bin.menuet
bin.nes
bin.omf
bin.psexe
bin.sfc
bin.smd
bin.spc700
bin.vsf
bin.zimg
crypto.blowfish
debug.bochs
debug.qnx
io.ar
io.gprobe
io.null
io.qnx
io.r2k
io.r2web
io.rbuf
io.sparse
io.tcp
```

**Comment by radare** [comment]
GPL != LGPL

**Comment by pelijah** [comment]
What is wrong? LGPL allows dynamic linking. So it's possible to add them to `plugins.nogpl.cfg`, isn't it? I think they should be included as `SHARED` but `plugins.nogpl.cfg` already contains LGPL plugins in `STATIC` list (`anal.8051`, `anal.arc`, `anal.xap`, `anal.dalvik`, ...).

**Comment by pelijah** [comment]
Whoops I didn't notice new file `plugins.static.nogpl.cfg`.

**Comment by ret2libc** [comment]
This is a bit trickier than what I thought because the meson build right now does not support different plugins settings (they are hardcoded in the meson.build files)

**Comment by ret2libc** [comment]
I'm going to move this to next release. I think first we should support plugins selection. Then this will be easy, as it will just involve disabling a bunch of fs plugins. If we implement this right now, it will be a mess soon.

**Comment by radare** [comment]
sgtm, but having the ability to choose which plugins to build will be good to have in meson too

**Comment by ret2libc** [comment]
Indeed. That's what I'm saying. Let's first implement the ability to choose plugins in meson, than on top of that we can more easily implement this feature.

**Comment by ret2libc** [comment]
Probably not going to focus on this for few releases. I guess it will raise in prio as soon as someone who needs --without-gpl will use meson.

**Comment by radare** [comment]
can you just split up the list of plugins built by meson like its done in acr? so plugins.cfg is honored? this way we can just use the plugins.cfg of desire. the only extra thing would be to pass the WITOHUT_GPL cflag

**Comment by trufae** [comment]
Already did this
