### ISSUE TITLE
Connection to remote gdbserver hangs/does not succeed

### ISSUE THREAD

**Issue by reijin90** [radareorg/radare2#11722]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64_86 (remote host) and Windows 10 Pro 64 (local)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 1 @ windows-x86-32 git. commit: 653064d30ac2a3035c26cc0cbd394b1b7a9b5d65 build: Sat 07/14/2018__ 8:12:38.88

### Expected behavior
Connecting to remote gdbserver via its domainname and debugging the file on the remote machine using the radare2 webui or cli. 

### Actual behavior
radare establishes connection (gdbserver recognizes connection) but then nothing happens (seems like a hang). There is just a new line after my executed command and no interface starts (cli/web)

### Steps to reproduce the behavior 
Started gdbserver on remote Ubuntu machine 
`gdbserver host:8585 /my/file`
Try to connect on my local Windows machine via:
```
radare2.exe -D gdb -d gdb://my.remote.ubuntu:8585
radare2.exe -d gdb://my.remote.ubuntu:8585
radare2.exe -c=H -D gdb gdb://my.remote.ubuntu:8585
radare2.exe -c=H -D gdb -d /my/file gdb://my.remote.ubuntu:8585
```
All of the above commands lead to a connection attempt at my gdbserver, but no UI is spawned and no interaction is possible. 

Note: the file to be debugged is not located on my local Windows machine, it is only stored at /my/file on the remote Ubuntu machine.

**Comment by abcSup** [comment]
Tested radare2.exe on Microsoft Windows 10 Home Version 10.0.18363 Build 18363 while connecting to a remote gdbserver on Ubuntu 18.04 LTS

```
$ gdbserver host:4444 /bin/ls
```
```
C:\Users\abcSup>radare2 -v
radare2 4.5.0-git 24612 @ windows-x86-64 git.4.4.0-155-g0b231619a
commit: 0b231619abedfec08f3bfb86fea259536877ab9a build: Sun 05/10/2020__15:15:45.34
C:\Users\abcSup>radare2 -d gdb://192.168.112.137:4444
= attach 4135 0
 -- Use +,-,*,/ to change the size of the block
[0x7ffff7dd6090]> pd 5
            ;-- rip:
            0x7ffff7dd6090      4889e7         mov rdi, rsp
            0x7ffff7dd6093      e8080e0000     call 0x7ffff7dd6ea0
            0x7ffff7dd6098      4989c4         mov r12, rax
            0x7ffff7dd609b      8b0597662200   mov eax, dword [0x7ffff7ffc738] ; [0x7ffff7ffc738:4]=0
            0x7ffff7dd60a1      5a             pop rdx
[0x7ffff7dd6090]> fs
   20 * regs
[0x7ffff7dd6090]> is
[0x7ffff7dd6090]>
```

It works for me. However, I realized that radare2.exe on Windows does not generate most of the symbols. Meanwhile, r2 on my Ubuntu shows the symbols while connecting to the same gdbserver.

```
$ r2 -d gdb://localhost:4444
[0x7ffff7dd6090]> fs
    0 * classes
  118 * imports
   20 * regs
  124 * relocs
   28 * sections
   10 * segments
  420 * strings
   34 * symbols
[0x7ffff7dd6090]>
```

I suggest @reijin90 try again with the latest r2.

**Comment by trufae** [comment]
Closing as no feedback and gdb is known to work
