### ISSUE TITLE
Simplify graph edges

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11728]
After enabling jump tables our graphs have become much bigger, so we need better strategies to simplify them. My proposal here is to add a config option for the graphs to avoid overheating the edge overlapping edges and such by just merging them if they have a common source or destination. We can just add a (number) label next to the edge to show how many lines are there.

The merge of the edges should be just to reduce clutter, and only in the common paths of the lines that have same destination.

**Comment by cyanpencil** [comment]
Do you mean something like it is done in the callgraphs?
For example here:
![image](https://user-images.githubusercontent.com/3428362/46607108-02ab0100-cb00-11e8-9345-debd85e6cbab.png)

**Comment by radare** [comment]
Imho vertical lines should have only one edge at the bottom to distribute to the exit nodes but yeah more or less
