### ISSUE TITLE
Wrong segment value conversion

### ISSUE THREAD

**Issue by BlaCoiso** [radareorg/radare2#11735]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu/x86/32
| File format of the file you reverse (mandatory)      | none
| Architecture/bits of the file (mandatory)            | none
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19613 @ linux-x86-32 git.2.9.0-278-g831c236 commit: 831c23641672ab767f6da2ac578e76a735a9028c build: 2018-10-04__19:46:57

### Expected behavior
segment conversion for 0xfffff gives f000:ffff
### Actual behavior
segment conversion for 0xfffff gives f000:0fff
### Steps to reproduce the behavior 
`rax2 -r 0xfffff` or `r2 -c "? 0xfffff" -q -`
### Additional Logs, screenshots, source-code,  configuration dump, ...
https://github.com/radare/radare2/blob/master/libr/core/cmd_help.c#L504
https://github.com/radare/radare2/blob/master/binr/rax2/rax2.c#L421

**Comment by XVilka** [comment]
Capstone strikes again.

**Comment by ret2libc** [comment]
> Capstone strikes again.

Are you sure it's capstone? I think the conversion to segment:offset is only done by radare2 itself.
