### ISSUE TITLE
Use git subtree for dependencies

### ISSUE THREAD

**Issue by xarkes** [radareorg/radare2#11730]
Hello,

I think it would be easier to handle the dependencies in radare2 (mostly `shlr/` folder) if we were using git submodules.
I think copy pasting is a bad practice and that we should use better development practices.

[EDIT] Actually I believe using `git subtree` is much better for our needs.

**Comment by radare** [comment]
how many times we had this discussion? are you sure there's no other issue to track this? anyone tried to ask github to support submodules in the release tarballs? i dont want to push my own tarballs. also managing submodules will be a pain for many users, even if its good practices will introduce many new issues for many users. So until github doesnt supports it i dont have any plan in switching to submodules

**Comment by xarkes** [comment]
> I don't want to push my own tarballs.

Fortunately in 2018 there are tools such as Travis which can do that for you. Not an issue from my PoV.

**Comment by radare** [comment]
Travis fails pretty frequently, and delegating the responsability to create tarballs to a third party implies a security issue in the distribution stage. also extra work to maintain/setup.

why not just mail github and ask for this feature

**Comment by xarkes** [comment]
@Maijin asked and there is no answer for now.
I think he should ping them again.

**Comment by radare** [comment]
sgtm

**Comment by xarkes** [comment]
A friend of mine just learned me too alternatives:
- [git sub-tree](https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree)
- [git-subrepo](https://github.com/ingydotnet/git-subrepo)

Those are worth checking out.

**Comment by Maijin** [comment]
wait, maybe sub-tree can fix the issue though because as @xarkes explain, it's a copy just like we have now.

**Comment by Maijin** [comment]
I created a test-case for subtree here:

* https://github.com/Maijin/testsubtree
And published a release here:
* https://github.com/Maijin/testsubtree/releases/tag/1.0

The release contains the subtree in Github:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1408600/46600109-71309480-cae9-11e8-8fb0-c9266f29c190.png">

**Comment by radare** [comment]
Another reason for not using submodules is because we will miss all the static source code analysis reports from Coverity. That's how i found many vulns in capstone, grub, gnu binutils, zip, .... we can't register more projects there

**Comment by Maijin** [comment]
@radare have you read the proposed solution with subtree?

**Comment by radare** [comment]
nope, im just focusing on the release. and this is not going to be in this release

**Comment by Maijin** [comment]
So when you have time, read my message then comment because this "we will miss all the static source code analysis " is not a problem with git subtree.

**Comment by Maijin** [comment]
Seems like we're moving towards submodules see #15497

**Comment by radare** [comment]
any volunteer?
