### ISSUE TITLE
Incorrect VV Graph rendering

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#11760]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 1 @ linux-x86-64 git.3.0.0-git commit: a873a4d942f491d28c6a17a62ca1a434e58d3eb1 build: 2018-09-27__07:36:41

### Expected behavior
A conditional jump should have two branches out in the graph.

### Actual behavior
The conditional jump is displayed as a non-conditional jump

### Steps to reproduce the behavior 
- `r2 -A ./ls`
- `s main`
- `VV`
- Check out `je` at `0x00003c6a`

### Additional Logs, screenshots, source-code,  configuration dump, ...
![radare_bad_v_graph](https://user-images.githubusercontent.com/7632864/46586111-c1571a80-ca47-11e8-9c39-8c53e7338e81.png)
[ls.zip](https://github.com/radare/radare2/files/2454255/ls.zip)

**Comment by radare** [comment]
known bug

use this to “workaround"

[0x00005430]> e anal.endsize =false
