### ISSUE TITLE
Different behaviour for `-0` between Windows and macOS/Ubuntu

### ISSUE THREAD

**Issue by pawlos** [radareorg/radare2#11808]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Win10 x64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     |  radare2 2.8.0-git @ windows-x86-32 git., commit: 653064d30ac2a3035c26cc0cbd394b1b7a9b5d65 build: Sat 07/14/2018__ 8:12:38.88

### Expected behavior
- when sending commands to radare2 in -0 mode it should print the results to console under Windows as it does under macOS or Ubuntu

### Actual behavior
- no output is visible and radare2 exits after the first command sent

### Steps to reproduce the behavior 
- start `radare2.exe -0 -` in the console under Windows
- type `?V`
- hit 2x return
- no output & radare2 exits

On Ubuntu or macOS, r2 operates continuously in this mode and prints the results of the commands being sent.

### Additional Logs, screenshots, source-code,  configuration dump, ...
I've discovered that when playing with [r2pipe for .net](https://github.com/radare/radare2-r2pipe/tree/master/dotnet). Examples provided did not work for me and I've noticed that radare2 was exiting after the command was sent.

**Comment by radare** [comment]
The -0 flag expectd commands separated by 0. So it is expected not to work that way but the behaviour should be consistent
