### ISSUE TITLE
Wrong disassembly of x86 shared library built with Android Studio

### ISSUE THREAD

**Issue by fabianMendez** [radareorg/radare2#11847]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0 19776 @ linux-x86-64 git.2.9.0-391-g2d9d4e73e commit: 2d9d4e73e3ca76185e171247e3eb1bbc66eea622 build: 2018-10-17__19:38:09

### Expected behavior
`objdump -M intel --start-address=0x5c0 --stop-address=0x66b -d libnative-lib.so`
```asm
 5cc:	e8 00 00 00 00       	call   5d1 <JNI_OnLoad+0x11>
 5d1:	58                   	pop    eax
 5d2:	81 c0 0b 1a 00 00    	add    eax,0x1a0b
 5d8:	8b 4d 0c             	mov    ecx,DWORD PTR [ebp+0xc]
 5db:	8b 55 08             	mov    edx,DWORD PTR [ebp+0x8]
 5de:	89 44 24 28          	mov    DWORD PTR [esp+0x28],eax
 5e2:	89 4c 24 24          	mov    DWORD PTR [esp+0x24],ecx
 5e6:	89 54 24 20          	mov    DWORD PTR [esp+0x20],edx
 5ea:	8b 44 24 28          	mov    eax,DWORD PTR [esp+0x28]
 5ee:	8b 88 fc ff ff ff    	mov    ecx,DWORD PTR [eax-0x4]
 5f4:	8b 09                	mov    ecx,DWORD PTR [ecx]
```
### Actual behavior
```asm
│           0x000005cc  ~   e800000000     call 0x5d1
│           ;-- loc._92:
│           0x000005cf      0000           add byte [eax], al
│           0x000005d1      58             pop eax
│           0x000005d2      81c00b1a0000   add eax, 0x1a0b
│           0x000005d8  ~   8b4d0c         mov ecx, dword [arg_ch]
│           ;-- loc._93:
│           0x000005d9      4d             dec ebp                     ; /jni.h:1
│           0x000005da      0c8b           or al, 0x8b
│           0x000005dc      55             push ebp
│           0x000005dd  ~   088944242889   or byte [ecx - 0x76d7dbbc], cl
│           ;-- loc._94:
│           0x000005e1      28894c242489   sub byte [ecx - 0x76dbdbb4], cl
│           ;-- loc._95:
│           0x000005e7      54             push esp
│           0x000005e8  ~   2420           and al, 0x20
│           ;-- loc._96:
│           0x000005e9      208b4424288b   and byte [ebx - 0x74d7dbbc], cl
│       ╎   ;-- loc._97:
│       ╎   0x000005ef      88fc           mov ah, bh
│       ╎   0x000005f1      ff             invalid
│       ╎   0x000005f2      ff             invalid
│       ╎   0x000005f3  ~   ff8b0983f900   dec dword [ebx + 0xf98309]
```
### Steps to reproduce the behavior 
```shell
$ r2 -A libnative-lib.so 
[0x000004c0]> s 0x000005c0
[0x000005c0]> pdf
```
### Additional Logs, screenshots, source-code,  configuration dump, ...
[libnative.zip](https://github.com/radare/radare2/files/2489942/libnative.zip)

**Comment by sudhackar** [comment]
This is happening because of the `loc._$i` flags. Running `f-loc._*` before disassembling should do the trick for now.

**Comment by radare** [comment]
f-loc*

**Comment by ret2libc** [comment]
This seems to work now. Closing. Please re-open if you think otherwise.
![image](https://user-images.githubusercontent.com/562321/93616704-5ce3ba80-f9d5-11ea-8620-4359b2772c86.png)
