### ISSUE TITLE
Global Variables

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#11871]
RIght now the only concept of varaibels iwe have in r2land is the local ones, bound to a function. There's a discussion going on about the merge of local and global xrefs, which imho is confusing, but we need to take decissions on that. in fact we dont know what a global variable is... but we may assume that a global variable can be constant or not, but must be a data reference to a data location , this is a non-executable page.. but this is not always true. because we can have global variables in firmwares and the page is rwx... so suggestions are welcome

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/8565

**Comment by XVilka** [comment]
And  https://github.com/radare/radare2/issues/6754 for constants

**Comment by jinnies47** [comment]
Hi, I would like to work on the issues and help  in any way possible in the growth and development of this organization.

**Comment by trufae** [comment]
I already implemented that
