### ISSUE TITLE
add tricore arch analysis support

### ISSUE THREAD

**Issue by yfuchs-c2a** [radareorg/radare2#11900]
It seems that tricore arch only support disassembler?
I would like to add support for tricore analysis.

Maybe someone can help get started?

Thanks!

**Comment by XVilka** [comment]
See https://radare.gitbooks.io/radare2book/content/plugins/dev-anal.html

**Comment by c-urly** [comment]
I am doing this.
Will update after doing one of the opcode type.

**Comment by c-urly** [comment]
Currently facing this error while building 
```
LD libr_anal.dylib
Undefined symbols for architecture x86_64:
  "_r_anal_plugin_mips_gnu", referenced from:
      _anal_static_plugins in anal.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libr_anal.dylib] Error 1
make[2]: *** [anal] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```
Below is that he current implementation i am trying to compile. IS it something wrong with it? thats why this error is coming?

[tricore_analysis_code](https://gist.github.com/c-urly/7db28e9892fb4f8a6b90c51eef2d3a72)

**Comment by radare** [comment]
a very basic anal plug for tricore should be added before 4.4 release. the plugin should be just doing nothing but returning a reg profile to save an assert
