### ISSUE TITLE
Potential analysis regression bug for arm v7

### ISSUE THREAD

**Issue by bitwave** [radareorg/radare2#11908]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | raw bootloader
| Architecture/bits of the file (mandatory)            | 32 bit ARM v7
| r2 -v full output, **not truncated** (mandatory)     |radare2 3.1.0-git 19764 @ linux-x86-64 git.3.0.1-8-g4c6aca5cd
commit: 4c6aca5cd7c0c1d100d95c9be63e8a4d7adced78 build: 2018-10-22__08:45:24

### Expected behavior
As in radare2 from around November 2017, after loading with
`r2 -a arm -b32 boot.img` and running `aaa`, functions showing up with `afl`

### Actual behavior
only one function is detected and no strings or anything useful
### Steps to reproduce the behavior 
load image with `r2 -a arm -b32 boot.img` and run `aaa` and `afl`
### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.
[boot.zip](https://github.com/radare/radare2/files/2506106/boot.zip)

**Comment by radare** [comment]
This binary lengtsh 328 bytes, and there’s only 1 function and 1 string, you can get it with `izz` because as long as its a raw binary `iz` shows nothing. Also about the code analysis when things like this happen because you are analyzing a binary without headers you can use the anal.hasnext=true option and sometimes the anal.endsize=false helps too. but that’s not the case.

**Comment by bitwave** [comment]
Sorry it was the wrong one. This is the real one.

[boot.zip](https://github.com/radare/radare2/files/2506800/boot.zip)

**Comment by bitwave** [comment]
In Hopper there are 23 Functions plus entrypoint.

**Comment by bitwave** [comment]
It disassembles also mostly as thumb code, which is odd.

**Comment by bitwave** [comment]
> can we distribuet it in the testsuite?
yeah, sure.
As I told, I re-did some analysis on this code from a year ago and was a bit surprised by analysis behaviour. Anyway, learned something new :D 

Thanks for the fast answer

**Comment by Maijin** [comment]
This is a regression because in November 2017, Sf was executed at the opening of raw file. 

Not sure who introduced this regression though @radare @ret2libc any idea?

**Comment by Maijin** [comment]
`Sf` doesn't work anymore too 👎

**Comment by radare** [comment]
the S command should die, but i d ont have time to kill all the things that must die in r2land

**Comment by Maijin** [comment]
Ok after checking on master and the good binary, it seems that aap doesn't require Sf anymore so it's all good. 

I will put `aap ; aav ; aac ; aar ; aan ; afta` in `aaa` only when opening a raw bin.

**Comment by radare** [comment]
Only? Do you think this is not a lot? :p

**Comment by Maijin** [comment]
They look relevant to me
