### ISSUE TITLE
Defining breakpoint relative to module name offset (only) is broken

### ISSUE THREAD

**Issue by fbellet** [radareorg/radare2#11902]
Hi!
When saving the project, breakpoints are saved as offset relative to the module name they belong to witth "dbm modulename offset", instead of their absolute address. This is problematic in linux, because the same module name may correspond to several mapped areas, with different permissions. And there is not warranty that the suitable mapping (hopefully the one with the execution bit set) will be the one that will be retained from the r_debug_native_modules_get() function, currently the first from the map list with a unique name.
I think r_debug_bp_add() should iterate on the maps list, and not on the modules list when m_delta is non null.

**Comment by radare** [comment]
Can you try to provide a pr fixing this?

Thanks!
