### ISSUE TITLE
Make radare2 Machine Learning/Deep Learning friendly

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#12040]
- [ ] Harmonize the commands output (mainly JSON ones)
 - [ ] Document on how to perform simple tasks
 - [ ] Small scripts as an examples
 - [ ] Integrate with signature search
 - [ ] Integrate with collaboration

**Comment by radare** [comment]
Wat

**Comment by gnarf-xx** [comment]
a hadoop radare2 database makes sense?  :heart_decoration:
