### ISSUE TITLE
Support for attaching to an already traced process

### ISSUE THREAD

**Issue by matrix1001** [radareorg/radare2#12076]
**Where do I get this idea**
I'm a user of `pwndbg`, as many other ctf players. Although gdb is a good debugger, it is definitely not a good disassembly code browser. That why I use `r2`.

The problem initially bumped out  when I use `pwndbg` command `r2`. (It has a weak support for r2, just uses `r2 filename -s addr`) The command does not resolve `PIE`. And I fixed it by a PR.

After that, I was thinking about if `r2` can attach to an already traced process. Not using `ptrace` to do real attach, but just read enough information from `/proc/pid/`. 

**Describe the solution you'd like**
Just a fake attach. Getting information from `/proc/pid/` is not a big problem. Some information like registers can be ignored.

**Describe alternatives you've considered**
NO

**Additional context**
This idea may sounds weird. And only benefits a few people like me who use gdb for debugging and r2 for disassembly.

By the way, is my problem already fixed ? I'm not very familiar to r2.

**Comment by radare** [comment]
That works with macOS and iOS already. On linux you can use r2 mmap://proc/pid/maps

**Comment by ret2libc** [comment]
If, according to https://github.com/radareorg/radare2/issues/12076#issuecomment-436561782, it already works, let's close this.
