### ISSUE TITLE
Strings not working in fat binaries

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#12089]
testcase:

```
r2 radare2-regressions/bins/mach0/hellocxx-osx-fat-intel
iz
```

* should display 1 string (str.Hello_World)
* if you rabin2 -x and open any of the bins below the strings are found properly.
* also check with izz, because pa = va and it shouldnt (hint)

**Comment by XVilka** [comment]
Moving to 3.5.0, since it not easy to fix.

**Comment by radare** [comment]
I think its easy if we fix the rbuf and force rbin to use only rbuf

**Comment by radare** [comment]
depends on the rbuf refactoring from  @ret2libc , so moving to 3.6

**Comment by radare** [comment]
Most of the refactorings required to fix this are done. we shouhld be able to find some time to fix this now

**Comment by trufae** [comment]
From my tests it seems to work fine now, will reopen with a reproducer in any case
