### ISSUE TITLE
TBH/TBB support for ARM analysis 

### ISSUE THREAD

**Issue by alvarofe** [radareorg/radare2#12098]
This is one way to implement switch cases in ARM (http://www.keil.com/support/man/docs/armasm/armasm_dom1361289912399.htm)

I had enabled the option `e anal.jmptbl` so I assume this is not handled yet.

![latest](https://user-images.githubusercontent.com/3474042/48209578-d50edd00-e375-11e8-873c-38933318f424.png)

You can assign to me, I will do it eventually - I lost my power to do so.

**Comment by 0x8008135** [comment]
@alvarofe should be fixed now with https://github.com/radareorg/radare2/pull/17347

**Comment by ret2libc** [comment]
Closing this because of what said in https://github.com/radareorg/radare2/issues/12098#issuecomment-667716678 . If the issue is still not solved for you, please re-open it with more details and a binary to reproduce. Thanks!
