### ISSUE TITLE
Base address of ARM object file is not being set correctly

### ISSUE THREAD

**Issue by asutoshpalai** [radareorg/radare2#12117]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | arm/32
| r2 -v full output, **not truncated** (mandatory)     | rradare2 3.1.0-git 20001 @ linux-x86-64 git.3.0.1-181-g59d7a92 commit: 59d7a92f8c09231c73a197d824d7f001a47c401d build: 2018-11-10__22:14:13

### Expected behavior
Addresses of functions in an ELF *object file* in r2 should match with the addresses output by `objdump`.

### Actual behavior
The addresses produced by r2 are with respect to a base address of `0x08000000`.

### Steps to reproduce the behavior

Please find the test object file attached

```bash
$ cat test2.c 
int add(int a, int b) {
        return a + b;
}

$ arm-linux-gnueabi-gcc -c test2.c -o test.o

$ r2 -AA -q -c 'afl' ./test.o
Warning: Cannot initialize program headers
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Invalid range to find strings 0x64 .. 0x64
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
0x08000034    1 48           entry0

$ r2 -AA -q -c 'pdf @ entry0' ./test.o -e io.cache=true
Warning: Cannot initialize program headers
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Invalid range to find strings 0x64 .. 0x64
            ;-- section..text:
            ;-- $a:
            ;-- pc:
            ;-- r15:
/ (fcn) entry0 48
|   entry0 ();
|           ; var int local_ch @ fp-0xc
|           ; var int local_8h @ fp-0x8
|           0x08000034      04b02de5       str fp, [sp, -4]!           ; [01] -r-x section size 48 named .text
|           0x08000038      00b08de2       add fp, sp, 0
|           0x0800003c      0cd04de2       sub sp, sp, 0xc
|           0x08000040      08000be5       str r0, [local_8h]          ; 8
|           0x08000044      0c100be5       str r1, [local_ch]          ; 0xc ; 12
|           0x08000048      08201be5       ldr r2, [local_8h]          ; 8
|           0x0800004c      0c301be5       ldr r3, [local_ch]          ; 0xc ; 12
|           0x08000050      033082e0       add r3, r2, r3
|           0x08000054      0300a0e1       mov r0, r3
|           0x08000058      00d04be2       sub sp, fp, 0
|           0x0800005c      04b09de4       pop {fp}
\           0x08000060      1eff2fe1       bx lr

$ arm-linux-gnueabi-objdump -d test.o

test.o:     file format elf32-littlearm


Disassembly of section .text:

00000000 <add>:
   0:   e52db004        push    {fp}            ; (str fp, [sp, #-4]!)
   4:   e28db000        add     fp, sp, #0
   8:   e24dd00c        sub     sp, sp, #12
   c:   e50b0008        str     r0, [fp, #-8]
  10:   e50b100c        str     r1, [fp, #-12]
  14:   e51b2008        ldr     r2, [fp, #-8]
  18:   e51b300c        ldr     r3, [fp, #-12]
  1c:   e0823003        add     r3, r2, r3
  20:   e1a00003        mov     r0, r3
  24:   e24bd000        sub     sp, fp, #0
  28:   e49db004        pop     {fp}            ; (ldr fp, [sp], #4)
  2c:   e12fff1e        bx      lr
```
[test.o.zip](https://github.com/radare/radare2/files/2569123/test.o.zip)

**Comment by alvarofe** [comment]
This iirc is due to objects file have a default address assigned The rationale behind was (if I am not wrong) to avoid overlaps with pa and handle better relocatable files. After all an object file can be mapped anywhere

The commit which introduced this was - b0c6ae4409c5cca4837bc75faa7fcdf5b785daa2

**Comment by asutoshpalai** [comment]
Thanks for the reply! I was just concerned with this behaviour not being what is followed by `objdump`, `gdb` or any other disassembly tool.

If you believe that this is the intended behaviour, feel free to close this issue.

**Comment by trufae** [comment]
Closing this ticket as it's up to the user to pick whatever base address they want
