### ISSUE TITLE
Allow to make partial builds

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#12162]
For some projects it is interesting to just use RAsm, or RBin, RHash, etc.. 

We should modify the build system to allow to specify which libs we want to build and don't build the other ones. This will save compilation times.

One first step would be to move the LIBS* into a separate file outside libr/Makefile

But the problem is not solved with this, so we will need to compute the dependencies of the libs specified and adjust build and installation scripts, same goes for meson.

Feedback on meson?

**Comment by oddcoder** [comment]
I have  no experience with meson, but why wouldn't kconfig be used for that. I have seen couple of projects building their modular parts on top of kconfig, and it is amazingly easy to deal with once the build system is in place.

**Comment by radare** [comment]
i dont think kconfig plays well with visual studio and other stuff we need to build r2 on other platforms than Linux.

**Comment by radare** [comment]
pls @oddcoder confirm the change i did is enough for you to do this

**Comment by ret2libc** [comment]
For meson this is already very simple. Each lib has the dependencies very well defined in the related meson.build file, so it's just a matter of adding an option in `meson.options` and add some `if` here and there I think.

**Comment by oddcoder** [comment]
yes it is more than enough, I was trying to figure out what did we do wrong.. and it was that we used make :), thanks a lot

**Comment by radare** [comment]
Cool!

**Comment by radare** [comment]
Oh wait. We probably want to keep this issue open because this is not working in meson yet and it will be good to document it in the book

**Comment by ret2libc** [comment]
Could you tell me how you do this in makefile? What's the command to only get RBin, for example?

**Comment by radare** [comment]
just create the libr.custom.mk with the l ist of libs you want to build and run configure+make like always

**Comment by radare** [comment]
One solution would be to create new libr_XXX_s.a with all the dependencies embedded in it, so r_bin wil have util io socket magic hash and syscall insside. this way you can disstribute only one .lib/.a to link to other projects without having to mess with multiple libs. i think this will simplify the integration at api level with other projects on windows mainly, linux distros will prefer the multilib i think

**Comment by ret2libc** [comment]
As this was opened years ago and there wasn't any real request from people using meson, I'm closing this. If we will get any complaint about this, we can rethink our priorities. Also, maybe just splitting the libs would be better.

**Comment by trufae** [comment]
Agree
