### ISSUE TITLE
Improve display  of many flags in a single offset

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#12202]
* [x] e asm.maxflags=0 # current behaviour
* [ ] support line by line scrolling
* [ ] show flags in columns like its done for xrefs

<img width="267" alt="screenshot 2018-11-17 at 22 48 58" src="https://user-images.githubusercontent.com/917142/48666091-1a8c8200-eabb-11e8-961d-9d2151254e68.png">

**Comment by ret2libc** [comment]
3.2 for this one too. Just 2 days and it has been like this for a long time. No need to hurry a fix.

**Comment by radare** [comment]
Done with asm.flags.inline
