### ISSUE TITLE
IDA .sig files with version 5 compression not supported

### ISSUE THREAD

**Issue by lambofsenpai** [radareorg/radare2#12420]
The comments in this similar issue seem to imply this was fixed: https://github.com/radare/radare2/issues/3665 but I'm still getting the same error:

```
[0x00000000]> zfs **.sig
Sorry we do not support the signatures version 5 compression.
We encountered an error while parsing the file ./pc/bcb5rt.sig. Sorry.
```

The PR that fixed the compression issue was apparently in zip.c, but it doesn't look like any change was made to flirt.c which throws this error whenever a flirt sig with version 5 compression is detected.

**Comment by XVilka** [comment]
Can we add such a signature in radare2-regression tests? Is it redistributable?

**Comment by lambofsenpai** [comment]
I could generate a very simple .sig file just for testing. However, I discovered that in the FLAIR utilities available from hex-rays, there is a tool called "zipsig", which can add or remove this compression scheme from existing .sig files, making them compatible with r2. This isn't really clear from IDA's own documentation (because most IDA users will never need it), but if people have IDA Pro they should have access to this. So the fix might just be to add a note about this to r2's documentation regarding FLIRT signature support.

**Comment by XVilka** [comment]
It is better to support them both. Can you please generate compressed and
uncompressed files and send a PR to radare2-regressions (better with a
testcase)?

**Comment by lambofsenpai** [comment]
After some experimenting, I've found that creating a compressed .sig file from scratch using IDA Pro's latest FLAIR tools creates a compressed .sig file that _IS_ compatible with r2. It's only the compressed signatures supplied with IDA that have an issue—and not all of them, some work fine. I imagine that there was some change in their compression scheme or file structure at some point, and all .sigs they produced in a certain period have this issue.

So it seems like kind of a corner case not worth dealing with, and I'm not sure we'll find any redistributable file that has this problem. But any users coming from IDA to r2 will no doubt want to open/convert the .sigs they've been using, so including a note about this in the documentation seems prudent.

**Comment by Maijin** [comment]
ping 1

**Comment by Maijin** [comment]
I can reproduce on bcb5rt.sig mentionned.

**Comment by XVilka** [comment]
@swoops maybe you can take a look at this one?

**Comment by swoops** [comment]
I don't think I will be of much help with this one. I really don't know anything about FLIRT database files. Sorry.

**Comment by schrodyn** [comment]
Just ran into this issue for the first time and I was wondering if there is any status update on this bug? Can provide the sig file outside of the issue.
