### ISSUE TITLE
rasm2/mips: cannot assemble `jalr` instruction

### ISSUE THREAD

**Issue by hummelchen** [radareorg/radare2#12544]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | mips
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20484 @ linux-x86-64 git.3.1.3-130-g249899eec commit: 249899eec854696b63627e51aac8fc3f9e8f9d59 build: 2018-12-22__18:09:49

### Expected behavior
`% rasm2 -a mips "jalr t9"`
09f82003
### Actual behavior
`% rasm2 -a mips "jalr t9"`
Missing argument
Missing argument
Missing argument
Cannot assemble 'jalr t9' at line 3
invalid

**Comment by radare** [comment]
Feel free to send a pr implementing support for it. Shouldnt take more than 3 lines or code

**Comment by GustavoLCR** [comment]
It works if you specify the return register like this:
`$ rasm2 -a mips "jalr ra t9"` 
09f82003
