### ISSUE TITLE
Using 'dc' in debugging mode causes every instruction to turn to 'invalid'

### ISSUE THREAD

**Issue by dafta** [radareorg/radare2#12565]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.3 0 @ linux-x86-64 git.3.1.3
commit: HEAD build: 2018-12-18__20:01:57

### Expected behavior
I'm expecting to use the debugger and step instruction by instruction using 's' and 'S' or using 'dc' to continue execution. I'm in 'V!' visual debugging mode, and using '?' to check the keybindings shows that 's/S' is used for stepping into/over.

### Actual behavior
Using 's' or 'S' toggles locations between 0x00000000 and my current location, being sym.main.

Using 'dc' seeks to 0x00000000, and when I go back to sym.main, I see that every opcode is 'ff' and everything is 'invalid'.

### Steps to reproduce the behavior 
Asciinema link, because it happens with more than one binary.

https://asciinema.org/a/S9ZgNreN2VlrhVSBTrjOXqFr9

I've also included the .zip file containing some binaries. I tried it with the first 4 challenges.

### Additional Logs, screenshots, source-code,  configuration dump, ...
[challenges.zip](https://github.com/radare/radare2/files/2710788/challenges.zip)

**Comment by radare** [comment]
Thats because its dead

**Comment by davidpolverari** [comment]
Seems related to https://github.com/radare/radare2/issues/12437

**Comment by dafta** [comment]
Why would it be dead, though? It's a program that waits for input, running it normally waits for input, so why wouldn't it in radare?
