### ISSUE TITLE
Memleak in RBinObject

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#12607]
https://oss-fuzz.com/testcase-detail/5693031810859008

Clusterfuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11911&q=radare2&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary

**Comment by trufae** [comment]
RBin changed a lot since 2019, and there have been several memleak fixing patches on top of it. Assuming this is fixed as long as the issue is not very specific
