### ISSUE TITLE
Kill fastcall.h and use Calling convention SDB files

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#12700]
Right now there are 2 places where calling conventions need to be defined:

* https://github.com/radare/radare2/blob/master/libr/syscall/fastcall.h 
and
* https://github.com/radare/radare2/blob/master/libr/anal/d/cc-x86-64.sdb.txt

`fastcall.h` must be killed and code refactored to use the SDB files instead

**Comment by 08A** [comment]
Is this issue solved? Because the only reference to 'RSyscallRegs *regs;' is in one legacy test?

**Comment by Maijin** [comment]
Not fixed

**Comment by Maijin** [comment]
If you want to work on CPU/Platform profiles project that’s definitely an important one!
