### ISSUE TITLE
win7 32bit no entrypoint in debug mode

### ISSUE THREAD

**Issue by bamboospirit** [radareorg/radare2#12755]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 7 x86 32
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.3 6 @ windows-x86-32 git.3.1.3-5-gdf4c9f0
commit: df4c9f09ba6fe07a30b55a5c40c5bbdb7bddf087 build: Tue 12/04/2018__21:40:59.09

### Expected behavior

```
r2 -d c:\sshd\BssCtrl.exe
ie
```

I expect to see the entrypoint... 
### Actual behavior

```
r2 -d c:\sshd\BssCtrl.exe
ie
[Entrypoints]
0 entrypoints
```
[avg_remover_slt.zip](https://github.com/radare/radare2/files/2752112/avg_remover_slt.zip)

After opening it in debugging mode ie and iM don't show any entrypoint or Main function.
Opening it without -d works though...(ie will show the entrypoint)

**Comment by GustavoLCR** [comment]
I think this was fixed.

Windows 10 x64

![fixed](https://user-images.githubusercontent.com/23562137/51371845-13451d00-1ada-11e9-937c-1606f06ee2e3.jpg)

**Comment by XVilka** [comment]
@bamboospirit can you please confirm it was fixed?

**Comment by XVilka** [comment]
Ideally, it should be minimized and added as a test case. And closed, since there is no response from the author.

**Comment by radare** [comment]
Skuater should have a look at it. Or maybe gustavo

**Comment by GustavoLCR** [comment]
I can't reproduce it even using the same version of r2 as him. Maybe he uploaded the wrong bin?

![image](https://user-images.githubusercontent.com/23562137/80654593-03451880-8a53-11ea-988f-bc9c07e508ae.png)

**Comment by XVilka** [comment]
Lets close then. We will reopen if it will be confirmed.
