### ISSUE TITLE
Hex editor improvements

### ISSUE THREAD

**Issue by MorteNoir1** [radareorg/radare2#12919]
**Is your feature request related to a problem? Please describe.**
radare2 will be more usable as a hex editor if the following issues will be fixed. Behavior of some commands is unexpected and differs very much from other hex editors.

**Describe the solution you'd like**
In visual mode (```VV```) with cursor enabled (```C```):

- Expected: Page Up / Page Down keys should scroll bytes upwards and downwards. 
Observation: they select 16 bytes up and down.
- Expected: Pressing ↓ key when the cursor is at the last visible row of bytes, you expect to see next 16 bytes.
Observation: "random" number of bytes appeared, the cursor is positioned at a random byte at the next row as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by radare** [comment]
Wtf?  What i expect is the actual behaviour and it has been always like this, please provide version information as well as system information, terminal etc

**Comment by Maijin** [comment]
Thanks for your suggestion @MorteNoir1 :
Can you please provide:
- the version of your radare2 (output of `r2 -v`)
- https://asciinema.org/ with the current output that you think need to be changed and/or some screenshots.

**Comment by XVilka** [comment]
Seems to work fine on all terminals I tested. We need information about
- radare2 version
- used OS and terminal emulator
- contents of `TERM` variable.

**Comment by ret2libc** [comment]
Closing. The current behaviour is the expected one. Thanks for creating this issue!
