### ISSUE TITLE
Show border of Hexagon instruction

### ISSUE THREAD

**Issue by RusEm** [radareorg/radare2#12937]
As we know Hexagon  using  VLIW, so 1 instruction can contain few commnds. Now r2 doesnt show  which commands jointed into one instruction. Thats why its very hard to understand code.
For example, r2 show this code:

0x43167220      allocframe (0x238)
0x43167224      R1   = 0x0
0x43167228      call 0x43167434
0x4316722c      R2   = 0x10
0x43167230      R3   = memw (gp + 0x158)
0x43167234      R16  = R0
0x43167238      call 0x4316743C

Here is very hard to understand which registers using fo 1st call.
Its must be like this:

0x43167220     { allocframe (0x238) }
0x43167224     { R1   = 0x0
0x43167228      call 0x43167434
0x4316722c      R2   = 0x10
0x43167230      R3   = memw (gp + 0x158) }
0x43167234     { R16  = R0
0x43167238      call 0x4316743C }

**Comment by radare** [comment]
ping @XVilka

**Comment by XVilka** [comment]
Oh, will check asap, forgot about this one.

**Comment by uis246** [comment]
@XVilka

**Comment by XVilka** [comment]
@uis246 I left the project. See https://github.com/rizinorg/rz-hexagon/ if you want better support.

**Comment by trufae** [comment]
Slacking for 3 years without solving this issue and now spamming your thing in here.

Hats off.

@uis246 @RusEm feel free to contribute back to r2, I never touched this architecture, so i'll need context and samples to understand the issue and fix it, and im currently busy in other fronts. I'll keep this issue open in case someone wants to improve the hexagon support.

Thanks

**Comment by uis246** [comment]
Well, I'm interested in braces not only for Hexagon, but for another VLIW arch.

**Comment by trufae** [comment]
It should be working as expected now in master, i just did a blind implementation of vliw after reading some documentation. Thanks for pointing it out!
