### ISSUE TITLE
Center or be able to choose the position of the active line in visual mode

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#1302]
Center or be able to choose the position of the active line in visual mode

**Comment by trufae** [comment]
@Maijin can we close this issue? i think it is possible to follow any other flag on panels or visual splits and nobody had issues about this on the last 6 years. feel free to close it unless you have more suggestions/ideas

**Comment by Maijin** [comment]
I think follow should be default to negative number but ok to close this.
