### ISSUE TITLE
Functions referenced from UJMP should be named "sub." instead of "fcn."

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13095]
<img width="753" alt="screenshot 2019-02-14 at 03 28 55" src="https://user-images.githubusercontent.com/917142/52758507-cf760280-3008-11e9-87bc-1bc274c574ff.png">

**Comment by SohailAlvi** [comment]
I am interested, can i take up this issue?

**Comment by radare** [comment]
Yup

**Comment by radare** [comment]
See https://github.com/radare/radare2/pull/13152 as inspiration

**Comment by radare** [comment]
Seems like @SohailAlvi have no time to chk this issue before the next release. so it's open again for anyone who wants to contribute.

**Comment by c-urly** [comment]
How do i generate this? i am unable to get fcn.* after jump. Can you show me the series of commands to generate this?

**Comment by radare** [comment]
Just aa on random binaries, im busy now and i have no handy bin to specify now

**Comment by c-urly** [comment]
<img width="1170" alt="screenshot 2019-03-07 at 12 55 38 pm" src="https://user-images.githubusercontent.com/14140421/53939260-8cbfbb80-40d8-11e9-94db-163e3a3b5bbc.png">
 I am getting this output after aa.

**Comment by deepakchethan** [comment]
I can start working on this.
But even I'm not able to reproduce this.

**Comment by radare** [comment]
any comment here @ITAYC0HEN ?

**Comment by radare** [comment]
I think we can close this after the bb approach it makes no sense to try to obey ida style fcn names
