### ISSUE TITLE
Setting xmm registers fail

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#13090]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 81 @ linux-x86-64 git.3.3.0-git commit: 69ed84834c040a160fdff7546432a975550456f9 build: 2019-02-13__23:04:54

### Expected behavior
Running `dr xmm0l=0x10` will set `xmm0l` to be `0x10`.

### Actual behavior
`xmm0l` is unchanged. 

### Steps to reproduce the behavior 
 - r2 -d /bin/ls
 - drt all # Just to see what the current value is
 - dr xmm0l=0x10 # Try to set it
 - drt all # verify it didn't set

**Comment by koyaan** [comment]
This appears to have been fixed by correcting the register profile.
```
[0x004000b0]> dr xmm0l=0xAABBCCDD
[0x004000b0]> dr xmm0h=0x31337
[0x004000b0]> dr xmm0
0x00000000aabbccdd0000000000031337
```
