### ISSUE TITLE
Rafind -m not detecting end of zip archive

### ISSUE THREAD

**Issue by a-meth** [radareorg/radare2#13168]

**Comment by XVilka** [comment]
Please clarify.

**Comment by a-meth** [comment]
Binwalk detects the end of zip archive when we use binwalk -e but Rafind -m only detects the magic of the files in the .zip file and doesn't detect the magic of the end of the zip archive, which could be helpful for implementing rafind -Me.

**Comment by radare** [comment]
thats expected. but can be improved indeed

**Comment by a-meth** [comment]
Fixed in commit #14027

**Comment by Maijin** [comment]
Hi @a-meth cool PR, check https://github.com/radareorg/radare2/issues/11163 :)
