### ISSUE TITLE
Automate merging easy and test-passing pull requests

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#13172]
For example if all tests are passing, coverage is not decreased, amount of changes is not big, PR was reviewed, it can merge automatically.

There is a bot for that:

https://mergify.io/

https://github.com/apps/mergify

**Comment by radare** [comment]
im the only one doing that and i dont think we need this

**Comment by ret2libc** [comment]
@XVilka can we work on this? I think it would be useful for all those cases where we set the "merge-when-green" label or things like that.

**Comment by trufae** [comment]
no. thats a bad idea. even more when there are bots pushing fake pull requests here and there
