### ISSUE TITLE
asm.meta=false improvements

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13200]
* [x] The ahi 10 (or vdi 10) results in invalid .hex xx, (its signed!) works fine in asm.meta=true
* [x] If the thing has been marked as data, it should be all of the same color and not analize the instruction there
* [x] indentation issues

<img width="684" alt="screenshot 2019-02-27 at 00 02 17" src="https://user-images.githubusercontent.com/917142/53452930-0396ed80-3a23-11e9-80b0-ea5bb02a02c0.png">

<img width="644" alt="screenshot 2019-02-26 at 23 35 46" src="https://user-images.githubusercontent.com/917142/53452945-0bef2880-3a23-11e9-9424-5eb4034c6897.png">

**Comment by oxcabe** [comment]
Now it displays data segments without colors

![asm_meta](https://user-images.githubusercontent.com/25517190/53708445-7a6d2580-3e2b-11e9-905d-2a584bfa34bb.png)

The thing is, now comments before data are also non-colored. Working on it, but feeling a bit stuck on this at this point.

**Comment by radare** [comment]
Thats neither a data segment or a comment

**Comment by radare** [comment]
ping @deepakchethan if you are blocked on something you can chk this issue too

**Comment by radare** [comment]
check this issue @deepakchethan its easy

**Comment by deepakchethan** [comment]
Okay, I will work on this today.

**Comment by deepakchethan** [comment]
Could you share the binary or tell me how to reproduce this on my local ?

**Comment by radare** [comment]
```
r2 /bin/ls
e asm.meta=false
v
pdwdi10
```

pdwdi10 is:

* p ->switch to disasm mode
* dw -> define dword
* di10 -> hint that dword as base 10 (show in decimal instead of hex)

**Comment by radare** [comment]
works with asm.meta=true
