### ISSUE TITLE
io_plugin: how to open multiple fds?

### ISSUE THREAD

**Issue by Cloudef** [radareorg/radare2#13215]
I made a io plugin (1) for opening running process's regions from `/proc/$$/maps` using uio (so it doesn't actually stop the process, like with ptrace). However, I'm running into a problem where I want the protocol to basically be `mem://pid` and have the io plugin to create fd for each region. I see there's open_many, but I'm not sure how it actually gets called.

1: https://ptpb.pw/WmLS.c/c

**Comment by Cloudef** [comment]
with `file.openmany=100`
```
 └╼ git:master ] r2 -e file.openmany=100 mem://$$
0 mem://30191
1 mem://30191
1 mem://30191
r_core_bin_load: no file specified
[r] Cannot open 'mem://30191'
```

**Comment by Cloudef** [comment]
As a "workaround" I made version that works with single descriptor https://ptpb.pw/Zn99.c/c
It has its pros and cons, but technically there could be different kind of binaries mapped

**Comment by condret** [comment]
Why do you want to use a filedescriptor for each region, why not a RIOMap?

**Comment by Cloudef** [comment]
Is there examples of that? I was looking at the io plug api and wondered why there are so many similar abstractions. (map, desc, fd)

**Comment by condret** [comment]
fds are a references to desc, so that we don't to use rawpointers to desc outside of RIO. descs represent connection to the io-plugin. Maps are for remapping things that exist in the desc (the file). I think you may want to use r_io_map_add, but it probably won't work from inside the open callback in the io-plugin. ... alternativly, you could create an rbin-plugin, which parses the map-files, and creates rbin-sections, which later get translated to riomaps

**Comment by Cloudef** [comment]
>alternativly, you could create an rbin-plugin, which parses the map-files, and creates rbin-sections, which later get translated to riomaps

I'll look into this. Can I also make it this way open `/proc/PID/self` (with supporting bin plugin, such as elf) and then use maps to map the regions? Maybe this should be a debugger plugin instead...? Though I have no plans to add any debugging facilities on top of this.

**Comment by condret** [comment]
oh, this is going to be tough

**Comment by ret2libc** [comment]
Hi @Cloudef , was your question answered? Are you still working on this?

**Comment by Cloudef** [comment]
Sorry, havent worked on this. For now this can be closed.
