### ISSUE TITLE
Github Transfer ownership of radare/radare2 to radareorg/radare2

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#13263]
For better better team management, roles assignment, CI tools usages. And also to stop using radare account for answering people as the account does not represent the team nor the org.

https://help.github.com/en/articles/transferring-a-repository#repository-transfers-and-organizations

- [x] radare2
- [x] sdb
- [x] radare2-r2pipe ( I suggest to rename also into just r2pipe)
- [x] r2book
- [x] radare2-extras (I suggest to rename also into just r2extras)
- [ ] radare2ida (I suggest to rename also into just r2ida)
- [x] radare2-regressions (I suggest also to rename into r2tests)
- [x] radare2-release (I suggest also to rename into r2release)
- [x] radare2-pm (I suggest also to rename into r2pm-db)
- [x] radare2-webui (I suggest also to rename into r2webui)
- [x] radare2-bindings
- [x] radare2-win-installer
- [ ] radare2-translations

**Comment by thestr4ng3r** [comment]
And if you do it, please DO NOT fork and unfork, just transfer the ownership.

**Comment by XVilka** [comment]
In fact it can be applied with a few related repositories as well:
- sdb
- r2pipe
- r2bindings
- etc

**Comment by XVilka** [comment]
Only a few left: sdb, r2book, radare2ida, and radare2-webui

**Comment by XVilka** [comment]
@radare can you please transfer the rest before 4.0 release? So we'll fix all URLs before, and such things?

**Comment by radare** [comment]
moved r2book and r2webui have been moved

not sure about r2ida mainlny because its dead

will think about sdb because despite being used by r2 its mainly a personal project

**Comment by Maijin** [comment]
Radare2ida is not dead

**Comment by radare** [comment]
thats true, last commit was 1 year ago and the contents are full of useless scripts

**Comment by Maijin** [comment]
It's not dead - @ITAYC0HEN

**Comment by thestr4ng3r** [comment]
+1 for transferring sdb next

**Comment by radare** [comment]
Done

**Comment by XVilka** [comment]
https://github.com/radare/radare2-win-installer and  https://github.com/radare/radare2ida - only two still relevant issue left. And we can close this issue for good.
No need for `radare2-capstone`, `radare2-translations`, etc since these are abandoned.

**Comment by radare** [comment]
i think we can close this issue. i dont consider radare2ida and radare2-transaltions useful projects at all, in fact, r2ida can be moved into extras prefectly , and translations is a hack that shouldnt be ever used.

**Comment by radare** [comment]
R2ida is now in extras. The other two are not needed. The old r2ida repo is innreadonly mode. We shiuld update the r2pm pkgs before deleting it
