### ISSUE TITLE
Reuse the XML library everywhere

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#13312]
Like it was done for JSON parsing and generation.

Currently XML is being parsed in:

- XNU kernelcache https://github.com/radare/radare2/blob/master/libr/bin/format/xnu/yxml.c
- GDB remote protocol https://github.com/radare/radare2/blob/master/shlr/gdb/src/gdbclient/xml.c

We can reduce the amount of code and bugs by using the same library everywhere.

Thus we can also add:
- [x] [Get symbols from AndroidManifest for APK files](https://github.com/radare/radare2/issues/5863)

**Comment by Maijin** [comment]
ping @mrmacete

**Comment by ninostephen** [comment]
seems like something i could help with. so what all should i find after parsing the manifest file? xml files can be parsed using the libxml2 library. could someone elaborate what is to be done?

**Comment by Maijin** [comment]
First step is to move yxml in shlr/ymxl can you do that @ninostephen?

**Comment by ninostephen** [comment]
I'm not quite sure what you mean by that. I'm much more of python dev than
a c guy. Could you elaborate?

**Comment by Maijin** [comment]
The library https://github.com/radare/radare2/blob/master/libr/bin/format/xnu/yxml.c must be moved to the location https://github.com/radare/radare2/tree/master/shlr in a new folder called `yxml`

**Comment by MMagdys** [comment]
I may work on this.
what other steps after moving yxml in shlr/ymxl ?
i think i should remove xml

**Comment by XVilka** [comment]
@MMagdys then the next step will be to rewrite other places that has XML parsing to reuse the yxml everywhere.

**Comment by ret2libc** [comment]
What are the exact steps missing here?

**Comment by Maijin** [comment]
Use `ymxl` library everywhere and remove `xml` from shlr

**Comment by ret2libc** [comment]
@Maijin please specify *everywhere*. Is it only used in `gdbclient`?

**Comment by Maijin** [comment]
The idea of the issue was to search too but I can't find it used at all.

**Comment by trufae** [comment]
The actual idea was from me to be able to process stream based xml or other structured data in raw data. This is on corrupted files or memory dumps so you can find the offset for the given xml path (or json). As well as print indented region or seek to the next open/close tag/element/attribute..

**Comment by Maijin** [comment]
That's a separate issue, here the idea was cleanup only.
