### ISSUE TITLE
available calling conventions do not properly synchronize with file bitness

### ISSUE THREAD

**Issue by fritzr** [radareorg/radare2#13329]
## Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux 2.6.32-696.23.1.el6.centos.plus.x86_64 x86_64
| File format of the file you reverse (mandatory)      | Raw binary
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.1 427 @ linux-x86-64 git.20170407-144-g09163a169  commit: 09163a169a960b5873d69cbeb8113ba628195a90 build: 2019-03-05__20:28:14

Here are the default arch/bits settings for my system:
```
$ r2 --
[0x00000000]> e asm.arch
x86
[0x00000000]> e asm.bits
64
```

## Expected behavior

*Case 1*. I expect to be able to use the 32-bit calling conventions after I set `e arch.bits = 32`.

For x86 I expect:
```
$ r2 --
[0x00000000]> e asm.bits
64
[0x00000000]> e asm.arch = x86
[0x00000000]> e asm.bits = 32
[0x00000000]> afcl
pascal
optlink
stdcall
cdecl
fastcall
borland
watcom
```

For ARM I expect:
```
$ r2 --
[0x00000000]> e asm.bits
64
[0x00000000]> e asm.arch = arm
[0x00000000]> e asm.bits = 32
[0x00000000]> afcl
arm32
```

*Case 2*: For a real raw binary I would expect to be able to set the architecture/bits on the command-line and achieve the same behavior as above.

For any raw binary I expect:
```
$ file /usr/share/radare2/3.2.1/opcodes/mips.sdb
/usr/share/radare2/3.2.1/opcodes/mips.sdb: data
$ r2 -a arm -b 32 /usr/share/radare2/3.2.1/opcodes/mips.sdb
[0x00000000]> e asm.bits
32
[0x00000000]> e asm.arch
arm
[0x00000000]> afcl
arm32
```

*Case 3*: I would expect the available calling conventions to honor overriding the architecture/bits on the command-line for a file of a known type (such as ELF).

x86 32b override expected output:
```
$ file /lib/ld-2.12.so
/lib/ld-2.12.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not stripped
$ r2 -a x86 -b 64 /lib/ld-2.12.so
[0x003b9860]> e asm.bits
64
[0x003b9860]> e asm.arch
x86
[0x003b9860]> afcl
amd64
ms
```

x86 64b override expected output:
```
$ file /lib64/ld-2.12.so 
/lib64/ld-2.12.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
[0x37cde00b30]> e asm.bits
32
[0x37cde00b30]> e asm.arch
x86
[0x37cde00b30]> afcl
pascal
optlink
stdcall
cdecl
fastcall
borland
watcom
```

## Actual behavior

*Case 1*: If I set bits after setting arch, the calling conventions are only available from the previous value of bits:

For x86 I see:
```
$ r2 --
[0x00000000]> e asm.bits
64
[0x00000000]> e asm.arch = x86
[0x00000000]> e asm.bits = 32
[0x00000000]> afcl
amd64
ms
```

For ARM I see:
```
$ r2 --
[0x00000000]> e asm.bits
64
[0x00000000]> e asm.arch = arm
[0x00000000]> e asm.bits = 32
[0x00000000]> afcl
arm64
```

*Case 2*: If I use the command-line to set the architecture/bits for an arbitrary raw binary, I see the same issue as case 1:

Random raw binary actual output:
```
$ file /usr/share/radare2/3.2.1/opcodes/mips.sdb
/usr/share/radare2/3.2.1/opcodes/mips.sdb: data
$ r2 -a arm -b 32 /usr/share/radare2/3.2.1/opcodes/mips.sdb
[0x00000000]> e asm.bits
32
[0x00000000]> e asm.arch
arm
[0x00000000]> afcl
arm64
```

Furthermore the command-line values for bitness appear to be overridden by the actual type of the file if it is known (such as an ELF):

x86 32b override actual output:
```
$ file /lib/ld-2.12.so
/lib/ld-2.12.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not stripped
$ r2 -a x86 -b 64 /lib/ld-2.12.so
[0x003b9860]> e asm.bits
64
[0x003b9860]> e asm.arch
x86
[0x003b9860]> afcl
pascal
optlink
stdcall
cdecl
fastcall
borland
watcom
```

x86 64b override actual output:
```
$ file /lib64/ld-2.12.so 
/lib64/ld-2.12.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
[0x37cde00b30]> e asm.bits
32
[0x37cde00b30]> e asm.arch
x86
[0x37cde00b30]> afcl
amd64
ms
```

### Workarounds

*Case 1*: For the first issue, I can set bits first and then arch to get what I expect:

For x86 I see:
```
$ r2 --
[0x00000000]> e asm.bits = 32
[0x00000000]> e asm.arch = x86
[0x00000000]> afcl
pascal
optlink
stdcall
cdecl
fastcall
borland
watcom
```

For ARM I see:
```
$ r2 --
[0x00000000]> e asm.bits = 32
[0x00000000]> e asm.arch = arm
[0x00000000]> afcl
arm32
```

*Case 2/3*: For the command-line cases I just have to reset the arch to flush the CC to use the correct bits, apparently:
```
$ r2 -a arm -b 32 *
[0x00000000]> e asm.bits
32
[0x00000000]> e asm.arch
arm
[0x00000000]> afcl
arm64
[0x00000000]> e asm.arch = arm
[0x00000000]> afcl
arm32
```

## Steps to reproduce the behavior 
- Run `r2 --`
- Set `e asm.bits = 64`
- Set `e asm.arch = x86`
- Set `e asm.bits = 32`
- Run `afcl` to view calling conventions -- only the 64-bit CCs appear

Similar for command-line; described above.

**Comment by radare** [comment]
cc @sivaramaa

would be good to have a test (or a bunch of them) as a pr in r2r

**Comment by fritzr** [comment]
I've submitted PR [radare2-regressions#1740](https://github.com/radare/radare2-regressions/pull/1740) for these tests.

**Comment by trufae** [comment]
Can you try again? i think we have some tests for this in `test/db/cmd/cmd_afcl`. Can you confirm if it's fixed in master?

**Comment by radare** [comment]
It's fixed. just confirmed it again
