### ISSUE TITLE
Types inference and analysis for 64 bit registers is wrong

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#13433]
If you try to use `aft` on any binary from 64bit platform, e.g. x86_64, it will mark register arguments as `int32_t`, e.g. `rax` becomes `arg int32_t ...`. Before my changes it was `arg int ...`, but remember that `int` type is 4 bytes at most, thus even initially it was wrong. In this cases it should propagate register arguments to `int64_t` (and further).

**Comment by radare** [comment]
ping @sivaramaaa @oxcabe

**Comment by radare** [comment]
i think this was fixed by @kazarmy this week

**Comment by kazarmy** [comment]
i did? ... anyway this needs a test

**Comment by radare** [comment]
Uhm u did the rax=64bit type, eax=32bit one. Right?

**Comment by kazarmy** [comment]
i think you have confused me with @sivaramaaa ... it appears interesting but currently there are no resources that can be allocated towards it

**Comment by XVilka** [comment]
I think he meant @GustavoLCR and this commit https://github.com/radareorg/radare2/commit/281c4df09d6a51405b1157868f6301424ec3b95a

**Comment by kazarmy** [comment]
Yeah that seems to be it ... i suppose `bits` can sometimes not mean what it's supposed to mean
