### ISSUE TITLE
Problematic analysis options

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13482]
```
[0x00005310]> e anal.jmp.after =0
```

setting this results in pretty fuckedup analysis, we may probably want to remove some of those options or remove the code paths that cause this

**Comment by radare** [comment]
i think anal.jmp.eob can be removed, but i need to read some more code to get a decision on this, feedback is welcome

**Comment by XVilka** [comment]
Maybe postpone this for 3.5.0 instead?

**Comment by Maijin** [comment]
Can you please provide details on what is "fucked-up" and reproducers files and commands?

**Comment by radare** [comment]
lots of broken edges and invalid bb boundaries basically

<img width="1680" alt="Screenshot 2019-03-31 at 13 58 26" src="https://user-images.githubusercontent.com/917142/55288796-0fc4f080-53bd-11e9-8c15-e5eb56db88b8.png">

**Comment by Maijin** [comment]
When you have time can you provide files and commands for this?

**Comment by radare** [comment]
/bin/ls from mojave, set those options, aaa and open graph in visual

**Comment by Maijin** [comment]
Here is the binary - 
[ls.zip](https://github.com/radare/radare2/files/3089270/ls.zip)

**Comment by Maijin** [comment]
For eob the only issue that needed it was this one maybe now it's working by default and therefore the eval can be removed - https://github.com/radare/radare2/issues/4258#issuecomment-193562720 to be tested

**Comment by radare** [comment]
https://github.com/radareorg/radare2/pull/15340

**Comment by radare** [comment]
cc @thestr4ng3r

**Comment by trufae** [comment]
I removed those variables, so this is no longer an issue
