### ISSUE TITLE
radiff2 -g dumps raw disassembly in graph output

### ISSUE THREAD

**Issue by Siguza** [radareorg/radare2#13540]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.12, x86_64h
| File format of the file you reverse (mandatory)      | Mach-O
| Architecture/bits of the file (mandatory)            | arm64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21471 @ darwin-x86-64 git.3.3.0-289-g110b5fb15 commit: 110b5fb15c00602550e5a38ee4896246daac0203 build: 2019-03-28__17:27:26

### Steps to reproduce the behavior 

These are my test files: [kernels.zip](https://github.com/radare/radare2/files/3019365/kernels.zip)  
This is the command I'm running:

```
radiff2 -g 0xfffffff007558ca8,0xfffffff007554ff4 kernel_120 kernel_122 2>/dev/null
```

And these are the first 30 lines of output I get:

```
;-- OSUnserializeXML(charconst*,OSString**):
; CODE XREF from sym.OSUnserializeXML_charconst__unsignedlong_OSString (0xfffffff007558d44)
0xfffffff007557250      stp x28, x27, [sp, -0x60]!
0xfffffff007557254      stp x26, x25, [sp + var_10h]
0xfffffff007557258      stp x24, x23, [sp + var_20h]
0xfffffff00755725c      stp x22, x21, [sp + var_30h]
0xfffffff007557260      stp x20, x19, [sp + var_40h]
0xfffffff007557264      stp x29, x30, [sp + var_50h]
0xfffffff007557268      add x29, sp, 0x50
0xfffffff00755726c      sub sp, sp, 0xb20
0xfffffff007557270      mov x20, x1
0xfffffff007557274      mov x21, x0
0xfffffff007557278      add x22, sp, 0x2f8
0xfffffff00755727c      nop
0xfffffff007557280      nop
0xfffffff007557284      ldr x8, sym.___stack_chk_guard
0xfffffff007557288      str x8, [x22, 0x820]
0xfffffff00755728c      cbz x21, 0xfffffff007557364
     ldxr w8, [x26]
     add w8, w8, w1
     stxr w9, w8, [x26]
     cbnz w9, 0xfffffff00755364c
digraph code {
	graph [bgcolor=azure fontsize=8 fontname="Courier" splines="ortho"];
	node [fillcolor=gray style=filled shape=box];
	edge [arrowhead="normal"];
	"0xfffffff007557250" -> "0xfffffff007557364" [color="green"];
	"0xfffffff007557250" -> "0xfffffff007557290" [color="red"];
 "0xfffffff007557250" [fillcolor="orange",color="black", fontname="Courier", label="", URL="sym.OSUnserializeXML_charconst__unsignedlong_OSString/0xfffffff007557250"]
	"0xfffffff007557290" -> "0xfffffff007557364" [color="green"];
```

From line 23 onward, the output is valid DOT, but not only is there a big chunk of stray disassembly before it, but when I remove that part and look at the resulting graph, that same disassembled block is also missing.

**Comment by XVilka** [comment]
@deepakchethan can you please take a look at this one?

**Comment by deepakchethan** [comment]
Currently working on this :)

**Comment by deepakchethan** [comment]
This is runPendingAnal issue. For the first time, during the first run it prints the disassembly

**Comment by radare** [comment]
@deepakchethan any updates on this?

**Comment by radare** [comment]
ping @deepakchethan

**Comment by kuqadk3** [comment]
Hi, I am looking into this problem as suggested by @XVilka . It would be great if someone could give me some insights. What's the problem? what's the expected behavior?

**Comment by Siguza** [comment]
The expected output is a a graph file in the [DOT language](https://en.wikipedia.org/wiki/DOT_(graph_description_language)), highlighting the differences between the two input files/specified addresses.  
The actual output with current radare (`radare2 4.3.0-git 24615 @ darwin-x86-64 git.4.2.1-194-gf74dd3144, commit: f74dd31440fe90491c51420abc22edfb4d079958 build: 2020-03-03__04:51:32`) and the provided files & command, is some disassembly followed by a monster ASCII graph.

**Comment by kuqadk3** [comment]
So basically it's something wrong that make the code output a DOT graph at the middle of the function?

**Comment by radare** [comment]
its just calling the right apis i think, everything needed is implemented

**Comment by deepakchethan** [comment]
The method name has been changed. it's `run_pending_anal` now :)

> Hi, I am looking into this problem as suggested by @XVilka . It would be great if someone could give me some insights. What's the problem? what's the expected behavior?
> 
> Btw, I couldn't find runPendingAnal function, is it a typo mistake @deepakchethan ?
> (okay, runPendingAnal is now run_pending_anal)
> Thanks you guys ;)
> ![image](https://user-images.githubusercontent.com/12135974/75741264-aec83a00-5d3c-11ea-8ffd-5cf454a37e53.png)

**Comment by kuqadk3** [comment]
Seems like it was solved in recent PR (!?) since I could not find ```run_pending_anal``` anymore and could not reproduce the error. If so, I would love to know which PR, thanks! 
![image](https://user-images.githubusercontent.com/12135974/76232147-dd707400-6258-11ea-90b8-c4cbdb919fb3.png)

**Comment by Siguza** [comment]
Yep, with `-m d` I get the expected output now.  
I'll close this then. I don't know which commit solved it, but thanks a lot either way. :)
