### ISSUE TITLE
Add types information in function zignatures too

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13661]
types: `txf.`

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/6947

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/13677

**Comment by XVilka** [comment]
@oxcabe in fact, you might be interested in this too - from the implementation size r2 zignatures are just SDB databases, so it will be easy to add, once you determine how to store the function type, argument types, local variable types too.

**Comment by XVilka** [comment]
I am afraid it can't be done without proper testing and tests in 3 days.

**Comment by radare** [comment]
we can probably add some metrics from afis and afisf

**Comment by radare** [comment]
done
