### ISSUE TITLE
r_bp_restore - boolean argument

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#1375]
Recently the meaning of the argument was swapped and in fact it is still confusing, I would like to ask for feedback to determine a new function name for that:

```
r_bp_restore (TRUE)  -> restore breakpoints
r_bp_restore (FALSE)  -> restore original data from breakpoints

vs

r_bp_restore (TRUE)  -> restore original data from breakpoints
r_bp_restore (FALSE)  -> restore breakpoints
```

**Comment by jduck** [comment]
This ticket overlaps with work I'm doing in the debugger. In the upcoming PR, restoring breakpoints is part of the "recoil" and disabling them is part of the "bp_hit". I vote for something even more clear like ```r_bp_enable``` and ```r_bp_disable``` ...

**Comment by Maijin** [comment]
@jduck status on this ? Is it closable ?

**Comment by jduck** [comment]
After my recent changes, there are the "r_bp_enable" and "r_bp_enable_all" function, which simply set the enabled flag on the breakpoint(s). They do not (de-)activate ((un-)"restore") breakpoints at all. "r_bp_restore" (and _one and _except versions) live in IO and actually handle putting software breakpoints in place. Finally, these functions are called by the "bp_hit" and "recoil" functionality to automatically remove the breakpoints at debugger stop and re-enable them at debugger continue/step/etc.

This ticket stands as nothing has been done to clarify the naming thus far.
