### ISSUE TITLE
Support CSV

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13763]
CSV is a pretty nice format for those who like to use SQL or Excel to process the data. Those tools dont support JSON, so having CSV will give us the ability to extend the table widget.

* Import a CSV to render a table (adjust column sizes)
* Export any relevant info from r2 into CSV
* Create a CSV api like the pj_ one we have (maybe reuse the future table api) and create and exporter
* We need to define which char to use to print in that format, imho it should be a comma :D
* Columnize as a RCons filter (using the table api (_from_csv_string()))

For example:

```
afl, > functions.csv # print function list in csv format
```

Stuff that may be interesting as CSV:

* Function list
* Function Instructions
* Symbols
* Sections
* Imports
* Diffing results
* Zignatures
* ..

**Comment by XVilka** [comment]
Will overlap with `CC,` for linking the text file as a comment.

**Comment by radare** [comment]
This is supported by the RTable api, so we just need to make more use of it and improve the support for creating custom tables, joining them, filter, etc

**Comment by radare** [comment]
we can also use aflt, but this should be supported in other commands like `i` ones

**Comment by trufae** [comment]
Done via tables in 7df28e1fb253fa18d4ae9a544a1ddf65123d4c5f
