### ISSUE TITLE
Implement "hex.address" config variable to hide address column from hexdump

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#13849]
**Is your feature request related to a problem? Please describe.**
Currently we have options to hide the Address\Offset column in Disassembly and Graph using `asm.offset` and `graph.offset`. There is no such opition for `hex.*` variables though `asm.offset` also removes the Address column from hexdump (`px`). 

**Describe the solution you'd like**
I think we should separate the two  and create another config variable named "hex.address".

**Additional context**
As for @trufae request, it'd be best to change `asm.offset` and `graph.offset` to `asm.address` and `graph.address`

**Comment by trufae** [comment]
or asm.addr

address is unnecessary long
