### ISSUE TITLE
Type, recursive noreturn anal issue, fcnsignature and varnames issues

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#13861]
Two issues here:

* [ ] the function called is noreturn, so the bb shouldnt have any out edge
* [ ] if the function signature is changed (afs!) the varnames doesnt get updated

<img width="910" alt="Screenshot 2019-04-22 at 01 52 13" src="https://user-images.githubusercontent.com/917142/56477051-562fdb80-64a1-11e9-85d5-48851df0af57.png">
<img width="1040" alt="Screenshot 2019-04-22 at 01 52 34" src="https://user-images.githubusercontent.com/917142/56477052-562fdb80-64a1-11e9-94e4-1e8bcba07910.png">

**Comment by XVilka** [comment]
Please upload the file to test

**Comment by radare** [comment]
this is /bin/ls for mac as always

[ls.zip](https://github.com/radare/radare2/files/3453097/ls.zip)

**Comment by radare** [comment]
will be good to test it again @thestr4ng3r

**Comment by trufae** [comment]
my fix attempt

![Screenshot 2020-09-24 at 18 03 20](https://user-images.githubusercontent.com/6431515/94170343-3e2b6b00-fe90-11ea-9965-d94df856591f.png)

**Comment by trufae** [comment]
i fixed this in master
