### ISSUE TITLE
Nonstandard integer types used

### ISSUE THREAD

**Issue by mrnuke** [radareorg/radare2#139]
I see the use of <code>ut16</code> and other types of non-standard integer types used. Reinventing int types is ugly. The standard 'C' types are <code>uint16_t</code> and friends.

**Comment by fenugrec** [comment]
I would like to re-open this. We're in 2016, <stdint.h> is pretty standard (it's been *17 years* !). Plus, the way the types are defined in r_types_base.h is just wrong - you can't hope short int, int, etc. will always be 16/32bits. I think portability is very good for r2, and this here can become a huge problem.
I would suggest this : 
- in r_types_base.h , add #include <stdint.h> (ok, maybe have a plan B fallback for those assbackwards, retarded, mongoloid compilers that STILL don't have C99 support )
- keep the ut32 etc names, that's fine - just change the typedefs
- profit !

**Comment by fenugrec** [comment]
Plus, we're already including `<stdbool.h>`, and that's also from C99, so why stop there ! C99 all the code

**Comment by radare** [comment]
I know, im slowly c99-izing r2 mainly because all compilers that tsrget all platforms supported by r2 do support it. But this was not the case when i started the project.

Also, ut* names are shorter than the boring uint*_t and i found some compilers produced some type conflicts thats why i choosed to use define.

**Comment by mrnuke** [comment]
As I've stated many years ago, the problem with nonstandard types is that it raises the entry barrier for new contributors. This and a few other reasons, such as the nonstandard buildsystem, made me decide to not invest time into contributing, despite being very enthusiastic of the process.

I'm glad to hear that this is now being worked on.

P.S. the "_t" in stdint types still drives me nuts today.
