### ISSUE TITLE
aoj missing x86/x64 semantic information of instructions

### ISSUE THREAD

**Issue by MapleLeaf-X** [radareorg/radare2#13908]
It affects any instruction that has side effects such `push` because opex only shows the visible operands and anything hidden is ignored.
I'm not entirely sure if this is a bug or not so please forgive me if this the intended behaviour.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Win7 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21238 @ windows-x86-64 git.3.5.0-git commit: 1c279c6081bc1877fabd533a8314eb527e32c66c build: Wed 04/10/2019__10:52:39.32

### Expected behavior
aoj (opex) should provide information about modified/accessed registers and cpu flags that are hidden.

### Actual behavior
![img](https://user-images.githubusercontent.com/28764234/56830199-3f98d400-6855-11e9-8bdf-9aeade0ac5ed.PNG)

### Additional Logs, screenshots, source-code,  configuration dump, ...
The responsible function seem to be opex from `libr/anal/p/anal_x86_cs.c`

**Comment by radare** [comment]
agree, seems like a good idea, you can get this by evaluating the esil expression too. but i agree that this sinfo should be exposed directly from static.

Its an easy fix, do you want to send a PR for it?

**Comment by MapleLeaf-X** [comment]
I'm not familiar enough with the code or the 'style' of how things are done with radare so it might have to wait unless if someone else has an idea how it should be represented.

**Comment by radare** [comment]
I dont expect anyone  to do that before r2con
