### ISSUE TITLE
No zignspace context in applied flags or function naming

### ISSUE THREAD

**Issue by AlexKornitzer** [radareorg/radare2#13934]
**Is your feature request related to a problem? Please describe.**
This could well be a design decision and not an oversight hence the raise as a feature request over bug report. The issue here is that any zignspace context for a set of zignatures is not applied to the flags or function names when command such as `z/` are run. As a result when looking at function names or flags for this data you lose this additional context. This means that if you have two signatures with the same name in different namespaces you will not be able to tell which was matched.

**Describe the solution you'd like**
My current though is that the namespace should be applied to flags and function names, the issues arise from as to how best to approach this. For flags I am thinking that the following would fit in well and be sufficient: `sign.MATCH_TYPE.ZIGNSPACE.FUNCTION_NAME` For function names this becomes a little bit more complicated, I am currently thinking that we could us a delimiter approach which would then allow automatic namespace application but this could conflict with how people name their functions. For example if we used `:` as the delimiter, once functions had been named, when we run `zg` it would split on `:` to get the namespace if any and apply the function name (this delimiter could be a setting in the r2 config): `ZIGNSPACE:FUNCTION_NAME`

Additionally I think we should replace the `count` with the matching address, the current count values are confusing and inaccurate (as noted in the source). 

**Describe alternatives you've considered**
1. Only apply zignspace context to flags, the latest match will apply to the function name.

**Additional context**
Current State of Play:
![image](https://user-images.githubusercontent.com/2750747/56952224-bb36a180-6b31-11e9-9792-db3b4afd6f11.png)

**Comment by AlexKornitzer** [comment]
If we take this forward I am happy to implement it.

**Comment by radare** [comment]
can you share the binary? all those Warning messages are not good

**Comment by AlexKornitzer** [comment]
Yeah can do, it is nothing sensitive just `ls` from Arch Linux: https://www.archlinux.org/packages/core/x86_64/coreutils If you would rather I just upload the binary let me know where to put it.

Any thoughts on the actual issue?

**Comment by radare** [comment]
@AlexanderYukhanov are you still happy to implement it?

**Comment by AlexKornitzer** [comment]
@radare if that was intended for me, I am happy to implement this was just holding off until you gave feedback on the approach above as to not waste time implementing something that was not wanted or sufficient. If you are happy with the solution above, I will try and get it done over the next couple of weeks.

**Comment by radare** [comment]
Sgtm. Maybe others have comments here @ret2libc @xvilka ?

**Comment by AlexKornitzer** [comment]
Okay, I will crack on then!

**Comment by AlexKornitzer** [comment]
Right lets close this as the main PR is in, the only things left to do are cosmetic.
