### ISSUE TITLE
Command parser only escapes up to one pipe character

### ISSUE THREAD

**Issue by tilman2** [radareorg/radare2#13939]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21666 @ linux-x86-64 git.3.4.1-277-gcdff7bf53 commit: cdff7bf53a9433be69788c8cb024b883ec9fc721 build: 2019-04-28__08:15:04

### Expected behavior
The command parser allows for escaping any number of pipe characters:

\> CC x \| y \| z
\> pd 1
    0x00000000      0000           add byte [rax], al          ; x | y | z
\>

### Actual behavior
The command parser allows for escaping a single pipe character only:

\> CC x \| y \| z
'\x' expected.
\>

**Comment by XVilka** [comment]
It is related to the improving radare2 commands syntax parsing:
- https://www.radare.org/rsoc/2019/ideas.html#title_1
- https://github.com/radare/radare2/issues/7967

**Comment by ret2libc** [comment]
@tilman2 could you provide better test case? I don't understand the example you provided.

**Comment by ret2libc** [comment]
I think we can close this. 
This is now possible with `cfg.newshell`, thanks to proper parsing.

```
$ radare2 -ecfg.newshell=true -qc "CC x \| y \| z; pd 1" -
            0x00000000      0000           add byte [rax], al          ; x | y | z
```

Of course you have to escape the `|` character, because otherwise it would be interpreted as the pipe operator `|`.
