### ISSUE TITLE
How to access the internal grep help?

### ISSUE THREAD

**Issue by DaniloNC** [radareorg/radare2#13991]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | kali linux docker - Linux 6aab7b5494fc 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF (Does not matter)
| Architecture/bits of the file (mandatory)            | x86/64 (Does not matter)
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21648 @ linux-x86-64 git.3.4.1-366-g428e62340 commit: 428e623406fbed4284acd62fa1c8bd01432ef995 build: 2019-05-07__16:02:
### Expected behavior

Access the internal grep help

### Actual behavior

Internel Grep not accessible from the command line using the recommended syntax `~??`

```
[0x00006130]> ?@?

[.... TRUNCATE ....]
| .!rabin2 -re $FILE  run command output as r2 script
| *                   output of command in r2 script format (CC*)
| j                   output of command in JSON format (pdj)
| ~?                  count number of lines (like wc -l)
| ~??                 show internal grep help
| ~..                 internal less
| ~{}                 json indent
| ~{}..               json indent and less
| ~word               grep for lines matching word
| ~!word              grep for lines NOT matching word
[.... TRUNCATE .... ]
[0x00006130]> ?~??
[0x00006130]> ?@~??
[0x00006130]> ~??
[0x00006130]> 
```

**Comment by karliss** [comment]
Both `~?` and `~??` currently print the help. The double question mark in `?` and `~?` could be replaced with single question mark version.
