### ISSUE TITLE
Implement pipe+xargs support syntax sugar

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14004]
The idea is to be able to write something like this:

```
pz~[0] || axt
```

the idea is that we want to be able to use pipes ini r2 commands, but r2 commands dont get anything from stdin, so instead of using babckticks and @@ iterators we need a way to express it in a pipe-form, similiar to how `xargs` work in unix

In that case that would work the same way as this:

```
axt @@=`pz~[0]`
```

But as long as || acts as `stdin` we may probably want to handle stdin pipes in more commands like `w ` for writing strings passed as stdin, those expressions could be groupped inside iterators @@.

```
izqq || w+
```

Maybe this ticket should be moved into the discussions tab

**Comment by radare** [comment]
feedback on this @ret2libc

**Comment by ret2libc** [comment]
i'm not sure... it's just so much complicated even to think about how the commands should interact, I'm not sure I'm ok with complicating the command syntax even more :(

I really think that for these "complicated" things you should just write a small script in r2pipe instead of making the syntax harder and harder.

**Comment by ret2libc** [comment]
I don't think this feature should be in 4.5.0 and not even in a close release. It's really just a "ok-to-have" but I think anything this complicated is better done with a r2pipe script. Please move this issue to 9999999999999999 milestone.

**Comment by trufae** [comment]
It's now a discussion https://github.com/radareorg/radare2/discussions/19969
