### ISSUE TITLE
Identify slow panels

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14107]
Some panels like decompiler can take a lot of time to render, will be good to compute the time they took. or execute them in background in a task, and collect the contents when finished, showing (working...) somewhere in the frame.

By checking the time of executing the frames we can suggest the user to enable cache for them automatically. Because for example, the decompiler output will not change if you just select a different frame or resize it, will be good to avoid refreshing panels if the offset didn't changed. and add a way to invalidate them when specific commands are executed...

I have the idea to provide a hash representing a watermark of the state of r2, and be able to use that to check if we need to invalidate some regions of the disasm, etc.

**Comment by trufae** [comment]
closing, everything seems fast to me, and there's  no need to have a non-specific issue
