### ISSUE TITLE
Length Argument of aha is ignored

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/radare2#14139]
Help:
```
| aha ppc 51         set arch for a range of N bytes
```
Giving it a length or not doesn't have any effect on the saved hint:
![Bildschirmfoto vom 2019-05-22 22-58-20](https://user-images.githubusercontent.com/1460997/58208510-29135a80-7ce5-11e9-9459-51e763115371.png)

**Comment by lowlyw** [comment]
yes, this is because we call thru to this

```c
   97 R_API void r_anal_hint_set_arch(RAnal *a, ut64 addr, const char *arch) {
⇒  98     setHint (a, "arch:", addr, r_str_trim_ro (arch), 0);
   99 }
```

and the `r_anal_hit_set_arch` has no concept of length. looking now

**Comment by lowlyw** [comment]
yeah, hints don't even support size at all, this is more a TODO and a poorly written help.

chk `r_anal_hint_del`

```c
✖  12 R_API void r_anal_hint_del(RAnal *a, ut64 addr, int size) {
   13     char key[128];
   14     if (size > 1) {
   15         eprintf ("TODO: r_anal_hint_del: in range\n");
   16     } else {
   17         setf (key, "hint.0x%08"PFMT64x, addr);
   18         sdb_unset (a->sdb_hints, key, 0);
   19     }
   20 }
```

**Comment by radare** [comment]
i think the help msg is wrong, anal hints take all over the place until another hint is found
