### ISSUE TITLE
meson install is not working

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14248]
![IMAGE 2019-06-07 19:41:12](https://user-images.githubusercontent.com/917142/59122891-34f55280-895c-11e9-9e23-f1f20eac6e2b.jpg)
![IMAGE 2019-06-07 19:41:16](https://user-images.githubusercontent.com/917142/59122895-3757ac80-895c-11e9-9a55-15a26c25ba8e.jpg)

**Comment by ret2libc** [comment]
Can this still be reproduced? I build/install with meson daily and I have no problem at all. The sys/meson.py script should probably be deprecated though. Please re-open if you are able to reproduce.
