### ISSUE TITLE
"dte" output dont sorted by numeric

### ISSUE THREAD

**Issue by s0i37** [radareorg/radare2#14240]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali Rolling x64
| File format of the file you reverse (mandatory)      | PE/ELF (doesn't matter)
| Architecture/bits of the file (mandatory)            | x86/32, x86/64 (doesn't matter)
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22141 @ linux-x86-64 git.2.9.0-2532-gbb6f18b79
commit: bb6f18b79a4aa6a29950792b8fb8b06aaf40d09c build: 2019-06-07__10:55:43

"dte" don't sorted output (sorted by ascii, but not numeric).

### Expected behavior
For example, if I have more that 10 steps in trace the "dte" output will contains instructions in order like with:
0.addr=0x15b4
...
1.addr=0x15b5
...
10.addr=0x106b
...

### Actual behavior
Of course it must be in numeral ordering:
0
1
2

### Steps to reproduce the behavior 
e dbg.trace=1aei;aeim;aeip;aets+; 11 aes; dte

**Comment by radare** [comment]
Its sorted by time

**Comment by radare** [comment]
Theres a grep filter to sort if u want to see it like this. Otherwise it can be a subcommand but a trace shoukdnt be sorted by addr

**Comment by s0i37** [comment]
May be I said a bit wrong, ordering is like:
0,1,10,11,12,13,14,15,2,3,4,5,6,7,8,9

**Comment by radare** [comment]
Oh that sounds wrong then

**Comment by s0i37** [comment]
Take a look on issue #14243. There are shows more long "dte" output.

**Comment by radare** [comment]
Ok ive checked this. When i rewrote the old rlist into sdb the sdb was dumped in a sorted way. The sdb lib changed after that to get proper hashtables which are unsorted and require an extra sort step before listing now. Also i have observed the ~$ sorting only works alphabetically, not numericaly, i will have a look at those issues when i get some time. But the current iutput is a raw sdb dump which is not as readable as it should be

**Comment by XVilka** [comment]
@yossizap since you are checking the debugger - could you please take a look at this one?

**Comment by yossizap** [comment]
Sure

**Comment by abcSup** [comment]
This seems to be already fixed in `esil_trace.c:r_anal_esil_trace_list`. 

```
ls_sort (list, (SdbListComparator) cmp_strings_by_leading_number);
```
Outputs

```
[0x10000102c]> dte
0.addr=0x10000102c
0.mem.write=0x177ff8
0.mem.write.data.0x177ff8=0080170000000000
0.reg.read=rsp,rbp
0.reg.read.rbp=0x178000
0.reg.read.rsp=0x178000
0.reg.write=rsp
0.reg.write.rsp=0x177ff8
1.addr=0x10000102d
1.reg.read=rsp
1.reg.read.rsp=0x177ff8
1.reg.write=rbp
1.reg.write.rbp=0x177ff8
2.addr=0x10000102c
2.mem.write=0x177ff8
2.mem.write.data.0x177ff8=0080170000000000
2.reg.read=rsp,rbp
2.reg.read.rbp=0x178000
2.reg.read.rsp=0x178000
2.reg.write=rsp
2.reg.write.rsp=0x177ff8
3.addr=0x10000102d
3.reg.read=rsp
3.reg.read.rsp=0x177ff8
3.reg.write=rbp
3.reg.write.rbp=0x177ff8
4.addr=0x10000102c
4.mem.write=0x177ff8
4.mem.write.data.0x177ff8=0080170000000000
4.reg.read=rsp,rbp
4.reg.read.rbp=0x178000
4.reg.read.rsp=0x178000
4.reg.write=rsp
4.reg.write.rsp=0x177ff8
idx=4
```

**Comment by s0i37** [comment]
Will it work after 10th instructions?

**Comment by abcSup** [comment]
> Will it work after 10th instructions?

You are right, it won't work. I understand the problem now.

**Comment by radare** [comment]
This output is the raw hashtable contents. Hashtables are not sorted

**Comment by s0i37** [comment]
Good. It works finally!
Grepping works too.

**Comment by abcSup** [comment]
> Good. It works finally!
> Grepping works too.

Wait, I do not think my latest PR have solved this problem yet. There is a planned refactor to fix this.

**Comment by s0i37** [comment]
Really? I've tested and it works fine.Shoud I reopen the issue?03.09.2020, 16:31, "Zi Fan" <notifications@github.com>:

Good. It works finally!
Grepping works too.

Wait, I do not think my latest PR have solved this problem yet. There is a planned refactor to fix this.

**Comment by abcSup** [comment]
Sorry for the deleted message. I have to check it first and it might be fixed by other PR.

**Comment by abcSup** [comment]
I can confirm that it is working somehow, so it can be closed for now.

**Comment by s0i37** [comment]
Cool!
