### ISSUE TITLE
Radare2 falsely detects an Entry Point in an ELF object file

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#14279]
Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
|File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22334 @ linux-x86-64 git.3.5.1-210-g759ebd5   commit: 759ebd5bfd2f8572d6866fffa7e26b7c739329f4 build: 2019-06-10__18:43:5

### Expected behavior
Radare2 should no detect an entry point in the binary and should not rename it to "entry0" instead of using the symbol provided

![image](https://user-images.githubusercontent.com/20182642/59210925-5605af80-8bb7-11e9-8130-cc0949529e3b.png)

### Actual behavior

```
$ r2 pngrutil.o
[0x08000034]> afl
0x08000034    3 54           entry0
0x0800006a    1 76           sym.png_get_uint_32
0x080000b6    1 76           sym.png_get_int_32
...
...
...

````

The function detected as "entry0" should be called `sym.png_get_uint_31`. 

As you can see, radare2 correctly set a flag "sym.png_get_uint_31":

```
[0x08000034]> fd.
entry0
section..text
sym..text
sym.png_get_uint_31
eip
```

And shows it also here:

```
[0x08000034]> pd 4
            ;-- section..text:
            ;-- .text:
            ;-- png_get_uint_31:
            ;-- eip:
╭ (fcn) entry0 54
│   entry0 (int32_t arg_8h, int32_t arg_ch);
│ bp: 3 (vars 1, args 2)
│ sp: 0 (vars 0, args 0)
│ rg: 0 (vars 0, args 0)
│           0x08000034      55             push ebp                    ; [01] -r-x section size 21908 named .text
│           0x08000035      89e5           mov ebp, esp
│           0x08000037      83ec18         sub esp, 0x18
````

It has an entry point detected:
```
[0x08000034]> ie
[Entrypoints]
vaddr=0x08000034 paddr=0x00000034 haddr=0x00000018 hvaddr=0x08000018 type=program

1 entrypoints
```

### Steps to reproduce the behavior 

1. Open pngrutil.o in radare2
2. analyze the binary
3. List the functions using "afl"

**Binary:**
[pngrutil.zip](https://github.com/radare/radare2/files/3272930/pngrutil.zip)

**Comment by lowlyw** [comment]
it's an unlinked object file. there should /not/ be any entrypoint to this imo

```
0x00000000]> pf.elf_header
     ident :
                struct<elf_ident>
           magic : 0x00000000 = "\x7fELF"
           class : 0x00000004 = class (enum elf_class) = 0x1 ; ELFCLASS32
            data : 0x00000005 = data (enum elf_data) = 0x1 ; ELFDATA2LSB
         version : 0x00000006 = version (enum elf_hdr_version) = 0x1 ; EV_CURRENT
      type : 0x00000010 = type (enum elf_type) = 0x1 ; ET_REL
   machine : 0x00000012 = machine (enum elf_machine) = 0x3 ; EM_386
   version : 0x00000014 = version (enum elf_obj_version) = 0x1 ; EV_CURRENT
     entry : 0x00000018 = 0x00000000
     phoff : 0x0000001c = 0x00000000
     shoff : 0x00000020 = 0x00008704
     flags : 0x00000024 = 0x00000000
    ehsize : 0x00000028 = 0x0034
 phentsize : 0x0000002a = 0x0000
     phnum : 0x0000002c = 0x0000
 shentsize : 0x0000002e = 0x0028
     shnum : 0x00000030 = 0x000e
  shstrndx : 0x00000032 = 0x000b
```

note 

```
     entry : 0x00000018 = 0x00000000
```

which has just been taking as the begin of the `.text` segment

```
[0x08000034]> iS~.text
01 0x00000034 21908 0x08000034 21908 -r-x .text
```

**Comment by lowlyw** [comment]
the code for `elf.c` to find entry is just wrong

```
  ut64 Elf_(r_bin_elf_get_entry_offset)(ELFOBJ *bin) {
      r_return_val_if_fail (bin, UT64_MAX);
      ut64 entry = bin->ehdr.e_entry;
      if (!entry) {
          entry = Elf_(r_bin_elf_get_section_offset)(bin, ".init.text");
          if (entry != UT64_MAX) {
              return entry;
          }
          entry = Elf_(r_bin_elf_get_section_offset)(bin, ".text");
          if (entry != UT64_MAX) {
              return entry;
          }
          return Elf_(r_bin_elf_get_section_offset)(bin, ".init");
      }
      return Elf_(r_bin_elf_v2p) (bin, entry);
  }
```

**Comment by lowlyw** [comment]
related https://github.com/Luis-Hebendanz/0pack/issues/1
