### ISSUE TITLE
Switch to garbage collection.

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14270]
Radare2 currently calls a lot of pairs malloc/free, causing switching the context ETOOOFTEN. What about considering to use garbage collection instead?

Something like https://github.com/orangeduck/tgc

**Comment by condret** [comment]
![doom_slayer_no](https://user-images.githubusercontent.com/5904302/136669430-f63a0465-cb30-47b5-9654-87060a70c101.jpeg)
