### ISSUE TITLE
Honor segments in DEX files

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14325]
This will make IO 2.5x faster:

```
$ r2 /tmp/classes.dex
[0x001b5b60]> iSS
[Segments]
Nm Paddr       Size Vaddr      Memsz Perms Name

[0x001b5b60]> iS
[Sections]
Nm Paddr       Size Vaddr      Memsz Perms Name
00 0x00000000   112 0x00000000   112 -r-- header
01 0x00000070 1554396 0x00000070 1554396 -r-- constpool
02 0x0017b84c 3928152 0x0017b84c 3928152 -r-x code
03 0x0053a8a4 3145488 0x0053a8a4 3145488 -r-- data
04 0x00000000 8628148 0x00000000 8628148 -r-- file
```

baiscally create 2-3 segments (overlap or not) with read-only and read-exec perms and drop the map bit of the current sections

**Comment by abcSup** [comment]
Hello,

I am looking forward to working on this issue. I have looked at the codebase and kinda know where I should begin with the fix. Before getting started, I would like to know how creating segments could make IO 2.5x faster for DEX files. And is creating three segments, such as header, code and data with the right read-only and read-exec permissions good enough?

**Comment by radare** [comment]
> On 1 Feb 2020, at 04:15, Zi Fan <notifications@github.com> wrote:
> 
> ﻿
> Hello,
> 
> I am looking forward to working on this issue. I have looked at the codebase and kinda know where I should begin with the fix.
> 

Cool!
> Before getting started, I would like to know how creating segments could make IO 2.5x faster for DEX files.
> 

Its because how rio works that its slower when there are many maps. Because it iterates them all every time. This must be optimized in r_io but we shouldnt abuse them and the sections info is already there
> And is creating three segments, such as header, code and data with the right read-only and read-exec permissions good enough?
> 
Yes, that should be enough

**Comment by abcSup** [comment]
> Its because how rio works that its slower when there are many maps. Because it iterates them all every time. This must be optimized in r_io but we shouldnt abuse them and the sections info is already there

What I understand here is that every function that makes use of the `r_io` API will perform 2.5x because `r_io` iterates through 2-3 segments instead of the 5 sections, so the 2.5x less maps. But, can you roughly point it out which part of the `r_io` API makes use of the segment information because I could not find that yet?

```
$ r2 /tmp/classes.dex
[0x0034b3c8]> iSS
[Segments]

nth paddr           size vaddr          vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000000      0x70 0x00000000      0x70 -r-- header
1   0x00344188  0x676c70 0x00344188  0x676c70 -r-x code
2   0x00aac3f1   0x29007 0x00aac3f1   0x29007 -r-- data


[0x0034b3c8]> iS
[Sections]

nth paddr           size vaddr          vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000000      0x70 0x00000000      0x70 -r-- header
1   0x00000070  0x344118 0x00000070  0x344118 -r-- constpool
2   0x00344188  0x676c70 0x00344188  0x676c70 -r-x code
3   0x00aac3f1   0x29007 0x00aac3f1   0x29007 -r-- data
4   0x00000000  0xad53f8 0x00000000  0xad53f8 -r-- file
```
This is what I have came up with by modifying the dex plugin in `r_bin`.

**Comment by radare** [comment]
Lgtm
