### ISSUE TITLE
How to select the PE-parser in radare2 ?

### ISSUE THREAD

**Issue by lamin3** [radareorg/radare2#14382]
Hi,
 
 I want to use lief-pe in radare2 for parsing.
 Should I first download it as a plugin ?
Then, after downloading it, please how to select a PE-pasrer in radare2 ? What are the commands to select the chosen parser ? I know for example that for changing debugger, I use:
 dL <debugger>
 but for PE-parser, I don't know how ?

Thanks in advance,

**Comment by radare** [comment]
rabin2 -F and r2 -F

**Comment by lamin3** [comment]
OK, thanks a lot ! But there is a problem of compilation with the plugin lief-pe, I can't install it by the way of **r2pm** , so please, is there another good PE-parser plugin I can install ?

Thanks

**Comment by radare** [comment]
Some things have changed in the rbin api, so the plugins must be updated. Should t take more than 10 minutes to fix that build

**Comment by radare** [comment]
If the default pe parser have an issue please report it

**Comment by lamin3** [comment]
Thanks for your replies. Here is the error I got when I try to install **lief** by the way of r2pm:
**/LIEF/api/c/include/LIEF/types.h:21:13: error: two or more data types in declaration specifiers typedef int bool;**

And about the default pe-parser, as I reported before, when debugging with some binaries, it goes to ff sections just after the first JMP.

[MEW_aitagent.exe.zip](https://github.com/radare/radare2/files/3317273/MEW_aitagent.exe.zip)
Please find enclosed the binary for which the default pe-parser fails: it goes to ff places just after the first jump. This binary is a PE binary packed with MEW packer. Please, just unzip it before.

**Comment by radare** [comment]
the bin parser is not used at all for debugging, so i guess you are refering to emulation, and yes, im aware that there are some issues in PE segments, but last windows i used was the 98 and i care -1 about it, so im not in charge of that. but i ugess that at some point i will have to care because seems like there's still people using this crappy OS

**Comment by radare** [comment]
omg lief is redefining basic c99 types with typedefs?!?! then thats not an issue in our side

**Comment by lamin3** [comment]
Yes, I was refering to emulation. For Windows, I try just to analyse some Windows binaries.

Thanks for your replies.

**Comment by XVilka** [comment]
Is this still a problem? Can it be closed?

**Comment by lamin3** [comment]
No longer. So yes, it can be closed. Thanks
