### ISSUE TITLE
Add asm.hint.imm

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14386]
To handle those push and mov refs
![IMAGE 2019-06-21 12:56:32](https://user-images.githubusercontent.com/917142/59918087-febbd680-9423-11e9-9f33-3bbc7be6d482.jpg)

**Comment by XVilka** [comment]
How it would look? Will it be tied to the address? Or is it something like defining a constant/enum with types? Related: https://github.com/radare/radare2/issues/8565 and https://github.com/radare/radare2/issues/4508

**Comment by radare** [comment]
like all the other asm.hint.* work, pressing 'r' in visual/graph to rotate their toggles

**Comment by trufae** [comment]
Done already a month ago or so
