### ISSUE TITLE
Disabling asm.filter does not affect display of function calls

### ISSUE THREAD

**Issue by Gordin508** [radareorg/radare2#14449]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64 rolling
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86-64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22257 @ linux-x86-64 git.3.6.0-23-gef1b1f5dd commit: ef1b1f5dd65b94fc4fad45a8ab2523f8e6ab686b build: 2019-06-28__21:49:30

### Expected behavior
Since the description of **asm.filter** reads "Replace numeric values by flags (e.g. 0x4003e0 -> sym.imp.printf)", one would expect turning it off would result in functions calls to also show the actual address instead of the flag.

So **call sym.imp.printf** becomes **call 0x1030** with asm.filter disabled.

On my debian notebook with its ancient **2.7.0 build** the output is as one would expect (notice the change at **0x1166**):

```
[0x00001148]> r2 -v
radare2 2.7.0 0 @ linux-x86-64 git.2.7.0
commit: HEAD build: 2018-11-06__16:40:40
[0x00001148]> e?asm.filter
          asm.filter: Replace numeric values by flags (e.g. 0x4003e0 -> sym.imp.printf)
[0x00001148]> e asm.filter = 1
[0x00001148]> pd 7
|           0x00001148      488d05b50e00.  lea rax, str.world     ; 0x2004 ; "world"
|           0x0000114f      488945f8       mov qword [local_8h], rax
|           0x00001153      488b45f8       mov rax, qword [local_8h]
|           0x00001157      4889c6         mov rsi, rax
|           0x0000115a      488d3da90e00.  lea rdi, str.Hello__s       ; 0x200a ; "Hello %s\n"
|           0x00001161      b800000000     mov eax, 0
|           0x00001166      e8c5feffff     call sym.imp.printf         ; int printf(const char *format)
[0x00001148]> e asm.filter = 0
[0x00001148]> pd 7
|           0x00001148      488d05b50e00.  lea rax, [0x00002004]  ; str.world ; "world"
|           0x0000114f      488945f8       mov qword [local_8h], rax
|           0x00001153      488b45f8       mov rax, qword [local_8h]
|           0x00001157      4889c6         mov rsi, rax
|           0x0000115a      488d3da90e00.  lea rdi, [0x0000200a]       ; str.Hello__s ; "Hello %s\n"
|           0x00001161      b800000000     mov eax, 0
|           0x00001166      e8c5feffff     call 0x1030                 ; sym.imp.printf ; int printf(const char *format)
[0x00001148]> 
```

### Actual behavior
While turning asm.filter off results in variables like string locations to be shown as actual address, functions calls are still listed by their flag.

See this example (same binary as above). Notice that **0x115a** changes at expected while **0x1166** does not:
```
[0x00001148]> r2 -v
radare2 3.7.0-git 22257 @ linux-x86-64 git.3.6.0-23-gef1b1f5dd
commit: ef1b1f5dd65b94fc4fad45a8ab2523f8e6ab686b build: 2019-06-28__21:49:30
[0x00001148]> e?asm.filter
          asm.filter: Replace numeric values by flags (e.g. 0x4003e0 -> sym.imp.printf)
[0x00001148]> e asm.filter = 1
[0x00001148]> pd 7
|           0x00001148      488d05b50e00.  lea rax, str.world          ; 0x2004 ; "world"
|           0x0000114f      488945f8       mov qword [var_8h], rax
|           0x00001153      488b45f8       mov rax, qword [var_8h]
|           0x00001157      4889c6         mov rsi, rax
|           0x0000115a      488d3da90e00.  lea rdi, str.Hello__s       ; 0x200a ; "Hello %s\n" ; const char *format
|           0x00001161      b800000000     mov eax, 0
|           0x00001166      e8c5feffff     call sym.imp.printf         ; int printf(const char *format)
[0x00001148]> e asm.filter = 0
[0x00001148]> pd 7
|           0x00001148      488d05b50e00.  lea rax, [0x00002004]       ; str.world ; "world"
|           0x0000114f      488945f8       mov qword [var_8h], rax
|           0x00001153      488b45f8       mov rax, qword [var_8h]
|           0x00001157      4889c6         mov rsi, rax
|           0x0000115a      488d3da90e00.  lea rdi, [0x0000200a]       ; str.Hello__s ; "Hello %s\n" ; const char *format
|           0x00001161      b800000000     mov eax, 0
|           0x00001166      e8c5feffff     call sym.imp.printf         ; int printf(const char *format)
[0x00001148]> 
```
I tested it earlier on a 3.5.x version and had the same faulty behavior (cannot recall which version exactly it was).

### Steps to reproduce the behavior 

1. Open x86-64 binary without any additional parameters
2. Disable asm.filter with `e asm.filter=0`
3. Print disassembly of code containing a function call, e. g. `pdf @ sym.main`

**Comment by Gordin508** [comment]
In the meantime `asm.filter` has been superseded by `asm.sub.jmp`, which appears to work as expected (tested in Version 5.7.8).

**Comment by trufae** [comment]
Thanks for testing and confirming it works as expected. I couldnt catch up with all the tickets sorry for that
