### ISSUE TITLE
Auto-Rename variables based on usage in function

### ISSUE THREAD

**Issue by trib0r3** [radareorg/radare2#14475]
**Is your feature request related to a problem? Please describe.**
I really like to quickly know the role of variable in disassembled code (is this some string, handle, ...). Very often we can  guess the type and role of the variable by checking how is used by some known functions (i.e printf).

**Describe the solution you'd like**
Behaviour should be similar to this known from IDA: if some variable is used in context of some known function, then corespoding arg should be renamed (and retyped) to this one known from function signature. 

**Example**

```asm
|           0x100000eeb      e860000000     call sym.imp.gets          ; char *gets(char *s)
│           0x100000ef0      488d7dd0       lea rdi, [s]               ; const char *s
│           0x100000ef4      488945b0       mov qword [var_50h], rax
│           0x100000ef8      e85f000000     call sym.imp.strlen        ; size_t strlen(const char *s)
│           0x100000efd      89c2           mov edx, eax
│           0x100000eff      8955bc         mov dword [var_44h], edx
```
 In the example above we have variable `var_50h` which is used in context of `strlen(const char *s)`, so we know that this is some string! We can rename it: `var50h => s`.

For more use-cases / scenarios you can go to IDA and play with this feature.

**Comment by Maijin** [comment]
That's already working like that in some use-cases just with `aaa`:

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/1408600/60586931-7f1ef780-9d93-11e9-81d8-28ea918efd87.png">

**Comment by Maijin** [comment]
Can you provide the binary?

**Comment by sheadovas** [comment]
Yeah, but you have (in your example / snippet) static string compiled into binary. And based on this the name of variable is changed (in my opinion).

I'm talking about the situation where you can have any type of variable, name should be generated by looking on calle argument name, so changing a little my above example to get rid of strings:

```asm
│           0x100000ef4      488945b0       mov qword [var_50h], rax
│           0x100000ef8      e85f000000     call sym.sethostid       ; void sethostid(long hostid)
```

The `var_50h` should be renamed to `hostid`.

---

My example:

```c
// gcc -o foo foo.c
#include <string.h>
#include <stdio.h>

int main() {
  char buffer[32];
  gets(buffer);

  int len = strlen(buffer);
  if (len == 6) {
    printf("%s = %d", buffer, len);
  }
  return 0;
}
```

**Comment by radare** [comment]
this one is important and also related to r2ghidra

**Comment by sivaramaaa** [comment]
Hey hi  @trib0r3 , 

The variables are renamed already based on usage in function (done during type propgation analysis aaft)

i couldn't repro the bug u are mentioning, i have compiled the example provided by u 

![r2_2020](https://user-images.githubusercontent.com/18589720/72896784-806f3c00-3d46-11ea-82c9-d7822d670bf6.png)

**Comment by trib0r3** [comment]
Nevermind, I had to use some weird r2 version
