### ISSUE TITLE
Do not print newline after `k` sdb query is finished

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14489]
`k anal/cc/**` or `k anal/cc/amd64` will both return results, and *also* an empty line after them, before showing prompt again. It should not.

**Comment by radare** [comment]
this comes from SDB and it was defined like this to use newline as separator when you do multiple queries in one line. but i agree its ugly and we may kill it

**Comment by radare** [comment]
and this issue should be solved in the sdb repo. not here
