### ISSUE TITLE
radare2 : debug error

### ISSUE THREAD

**Issue by bugshere** [radareorg/radare2#14506]
OS : Kali Linux
whoami : root
radare2 info ( radare2 3.7.0-git 22212 @ linux-x86-64 git.3.6.0-98-g681e8c1a8
commit: 681e8c1a89d6e979a1c5701c7fb1d117106d536c build: 2019-07-07__11:04:49 )
ptrace : ptrace (PT_ATTACH): Operation not permitted

ERROR

[0x00001165]> ood AAAAA-BBBB-CCCCC
Process with PID 27857 started...
File dbg:///root/binary/0x05/license_2  AAAAA-BBBB-CCCCC reopened in read-write mode
= attach 27857 27857
ptrace (PT_ATTACH): Operation not permitted
27857
[0x7f31d587c090]> 

ptrace more info : {
cat /proc/sys/kernel/yama/ptrace_scope 
0
}

here is the example 

``#include <string.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
if(argc==2) {
printf("Checking : %s\n", argv[1]);
int sum=0;
for(int i=0; i<strlen(argv[1]); i++){
sum += (int)argv[1][i];

	}
	if(sum==916) {
		printf("Access Granted!\n");
	} else {
		printf("WRONG!\n");
	}
} else {
	printf("Usage: <key>\n");
}
return 0;

}
`

**Comment by radare** [comment]
But despite rhe message, everything works. Right?

**Comment by bugshere** [comment]
Yes

**Comment by bugshere** [comment]
Well I did some research on.. and I found this...

`[0x00001155]> ood AAA-AAAAA
Process with PID 30498 started...
File dbg:///root/binary/0x07/license_3  AAA-AAAAA reopened in read-write mode
= attach 30498 30498
ptrace (PT_ATTACH): Operation not permitted
30498
`

`gdb -p 30497

Attaching to process 30497
**Reading symbols from /usr/bin/radare2...done.**
Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug/.build-id/e9/1114987a0147bd050addbd591eb8994b29f4b3.debug...done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Reading symbols from /usr/lib/libr_util.so...done.
Reading symbols from /usr/lib/libr_main.so...done.
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/18/b9a9a8c523e5cfe5b5d946d605d09242f09798.debug...done.
done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/.build-id/f2/5dfd7b95be4ba386fd71080accae8c0732b711.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libm.so.6...Reading symbols from /usr/lib/debug/.build-id/88/5dda4b4a5cea600e7b5b98c1ad86996c8d2299.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...Reading symbols from /usr/lib/debug/.build-id/d3/583c742dd47aaa860c5ae0c0c5bdbcd2d54f61.debug...done.
done.
Reading symbols from /usr/lib/libr_config.so...done.
Reading symbols from /usr/lib/libr_cons.so...done.
Reading symbols from /usr/lib/libr_io.so...done.
Reading symbols from /usr/lib/libr_flag.so...done.
Reading symbols from /usr/lib/libr_asm.so...done.
Reading symbols from /usr/lib/libr_core.so...done.
Reading symbols from /usr/lib/libr_debug.so...done.
Reading symbols from /usr/lib/libr_hash.so...done.
Reading symbols from /usr/lib/libr_bin.so...done.
Reading symbols from /usr/lib/libr_anal.so...done.
Reading symbols from /usr/lib/libr_parse.so...done.
Reading symbols from /usr/lib/libr_bp.so...done.
Reading symbols from /usr/lib/libr_egg.so...done.
Reading symbols from /usr/lib/libr_reg.so...done.
Reading symbols from /usr/lib/libr_search.so...done.
Reading symbols from /usr/lib/libr_syscall.so...done.
Reading symbols from /usr/lib/libr_socket.so...done.
Reading symbols from /usr/lib/libr_fs.so...done.
Reading symbols from /usr/lib/libr_magic.so...done.
Reading symbols from /usr/lib/libr_crypto.so...done.
Reading symbols from /usr/lib/libr_lang.so...done.
Reading symbols from /lib/x86_64-linux-gnu/libuv.so.1...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libutil.so.1...Reading symbols from /usr/lib/debug/.build-id/f4/4b754dcf4119e5743708fed89461489880474d.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/librt.so.1...Reading symbols from /usr/lib/debug/.build-id/5d/cf98ad684962be494af28a1051793fd39e4ebc.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/libnsl.so.1...Reading symbols from /usr/lib/debug/.build-id/53/2f3d2053a6b311dd5c43019780fe1ce5503a9a.debug...done.
done.
**futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x560199aa92d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.**
(gdb) 
`
I think bcoz of **futex_abstimed_wait_cancelable** , i got error : **../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.**

I also read this issue : https://github.com/ivmai/bdwgc/issues/250

**Comment by yossizap** [comment]
This issue is a result of running PT_ATTACH in 3 different places(only one checks for errors and prints the error in OP's log) for a forked PID when you're only supposed to PT_ATTACH remote processes(since the child sets himself up to be traced for you when use fork_and_ptraceme_for_linux).

I am currently looking into fixing this issue and cleaning up the code around it a bit.

**Comment by radare** [comment]
cool, thanks!
