### ISSUE TITLE
For stack in panels better show pxw or pxq depending on 32 or 64 bit

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14586]
<img width="496" alt="Screenshot 2019-07-18 at 00 57 22" src="https://user-images.githubusercontent.com/917142/61417324-15f0c580-a8f7-11e9-9a10-197f447ff3db.png">

**Comment by radare** [comment]
will be good to have `pxr@r:SP too`

**Comment by ret2libc** [comment]
This seems already fixed to me. Please re-open if you think otherwise.
