### ISSUE TITLE
htmlized json

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14616]
json shouldnt be filtered by the html thing. and this doesnt seems to work either:

`> afij@e:scr.html=0`

![Screenshot 2019-07-22 at 20 53 43](https://user-images.githubusercontent.com/917142/61657271-d80eeb00-acc2-11e9-8e19-4f1fee41ef73.png)

**Comment by radare** [comment]
i think the solution to this implies disabling scr.html temporarily everytime we print the output of a json command. but as long as this is done at flush level its a bit complicated to handle this in a single generic place

**Comment by trufae** [comment]
This was fixed in 4249c71e82af1e4cd2f81e4b53d663fec90a951b
