### ISSUE TITLE
Add higher order functions in radare2 shell

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14625]
As an extension of the classical iterators (see https://radare.gitbooks.io/radare2book/content/scripting/loops.html) it might be interesting to add these higher kinded constructs in radare2 scripting language:

- map
- fold
- filter

Since radare2 is quite close to the shell, see the [example of them in ZSH](http://yannesposito.com/Scratch/en/blog/Higher-order-function-in-zsh/):
```sh
$ filterl 'echo $1|grep a >/dev/null' ab cd ef ada
ab
ada

$ folda '$1+$2' {1..5}
15

$ folda '$1*$2' {1..20}
2432902008176640000

$ mapl 'echo X $1:t Y' ~/.zsh/functional/src/*
X each Y
X filter Y
X fold Y
X map Y

$ mapa '$1*2' {1..3}
2
4
6

$ mapl 'echo result $1' $(mapa '$1+5' $(mapa '$1*2' {1..3}))
result 7
result 9
result 11
```

We can introduce even JSON-focused `mapj`, `foldj`, `filterj`, that operate on the JSON output instead

cc @thestr4ng3r

**Comment by ret2libc** [comment]
Cool idea, but I think it's just a nice-to-have thing, I'm not going to invest time on this any time soon as newshell just landed and there are many other things to fix. It is anyway easy to use r2pipe to accomplish whatever you want.

**Comment by trufae** [comment]
That's implemented in the RTable API, so no need to keep this ticket open. If any command with useful data doesn't provides a table subcommand just open a ticket for it
