### ISSUE TITLE
Add Swift calling convention

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14657]
https://github.com/trufae/swift-frida/blob/master/calling-convention.js

**Comment by F3real** [comment]
I'll look into this.

**Comment by abcSup** [comment]
The Swift calling convention involves two additional parameters, namely `SwiftSelf` and `SwiftError`, which are not directly related to the attributes:`argi`, `argn`, `ret` in the [calling conventions profile](https://github.com/radareorg/radare2/blob/master/doc/calling-conventions.md)

In the case of x86-64, when calling an object method, the caller assigns the object address `SwiftSelf` to the register `r13`. Therefore, we can either make `SwiftSelf` as the first argument `arg0` similar to `cdecl-thiscall-ms` or introduce a new attribute `self`. 

If the function throws an error, the callee assigns the error code `SwiftError` to an additional register `r12` which is then passed back together with the return value `rax` to the caller. For the additional return value `SwiftError`, I guess we have to make some changes to the `r_anal` to take account of calling conventions that have more than one return value. Any other tips on how to proceed this?

**Comment by radare** [comment]
Hello Zi

We may want to add the concepts of 'self/this' and 'error' in the calling conventions definitions in r2.

those concepts will be also useful for other languages.

Looking forward your PR!

thanks

**Comment by abcSup** [comment]
After looking into the source, this is the plan I came up with.

1. During analysis, demangle function name to determine if function is an instance method and/or if it throws an error.
2. Add a new property in `RAnalFunction` to store the information `isInstanceMethod` (?)
3. In `r_anal_extract_rarg`, add `this` and/or `error` arguments if the function is an instance method and/or throws an error
4. Add `swift` calling conventions to `anal/p/cc-*.sdb.txt`
