### ISSUE TITLE
Add UTF-16 BE, `r_str_isutf*()` validate functions support

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14682]
https://github.com/radare/radare2/blob/master/libr/util/utf16.c has only little endian UTF-16 support.

Also we need autodetection of the endianess based on BOM for UTF-16.
I think also it makes sense to add functions
- `r_str_isutf8()`
- `r_str_isutf16le()`
- `r_str_isutf16be()`
- `r_str_isutf32()`

And reuse them for strings search in https://github.com/radare/radare2/blob/master/libr/search/strings.c

**Comment by XVilka** [comment]
@kazarmy you might be interested in those.

**Comment by kazarmy** [comment]
They do make sense -- feel free to add according to your requirements.

**Comment by XVilka** [comment]
Fixed.

**Comment by kazarmy** [comment]
Haven't done the r_str_isutf*() functions yet ... haven't yet pinned down the most suitable definition for a valid utf8/16/32 string
