### ISSUE TITLE
Forbid backticks in flagnames

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14701]
as stated by the is* issue

**Comment by radare** [comment]
they are forbidden already..
```
$ r2 -
[0x00000000]> "f je`bar=123"
[0x00000000]> f
0x0000007b 1 je_bar
[0x00000000]> f*
fs *
f je_bar 1 0x0000007b
[0x00000000]> q
$
```
i think the problem iss when accessing the struct fields properly

**Comment by thestr4ng3r** [comment]
@radare is this about `is*` only or also anywhere else?

**Comment by thestr4ng3r** [comment]
So can this be closed?

**Comment by thestr4ng3r** [comment]
see https://github.com/radare/radare2/pull/14797#issuecomment-520813533

**Comment by radare** [comment]
Why you didnt fixed r_name_filter?

**Comment by thestr4ng3r** [comment]
Because it already handles ` correctly, as wrote.

**Comment by radare** [comment]
this is fixed now
