### ISSUE TITLE
Missing /Ej

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#14744]
**Is your feature request related to a problem? Please describe.**

`/E esil-expr                 offset matching given esil expressions %%= here`

Is missing its json counterpart /Ej

**Describe the solution you'd like**
Implement /Ej using pj

https://github.com/radare/radare2/blob/master/libr/core/cmd_search.c#L1596

**Comment by radare** [comment]
Imho /E must die and renamed to /ae

**Comment by radare** [comment]
Nvm /E have nothing to do with the actual assembly esil.
