### ISSUE TITLE
r2 shm:// little bug

### ISSUE THREAD

**Issue by s0i37** [radareorg/radare2#14741]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali rolling x64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22725 @ linux-x86-64 git.3.6.0-265-g9677804b8
commit: 9677804b8e4f187656279a109d937c583ca0fb0a build: 2019-07-29__12:31:46

### Actual behavior
r2 show shared memory content by 32 bytes (2 lines in hex view):
![temp](https://user-images.githubusercontent.com/22872513/62363951-c7b80500-b539-11e9-9ffb-60e80f50d21a.png)

### Expected behavior
Normal view. In full console height.

### Steps to reproduce the behavior 
```
ipcs -m
r2 -zz shm://12345
V
```

**Comment by XVilka** [comment]
Please add the expected behaviour

**Comment by s0i37** [comment]
I've added

**Comment by radare** [comment]
Type om and see the map created its probably related to the siol change 2 years ago. Will be good to have tests

**Comment by s0i37** [comment]
```
[0x00000000]> om
 1 fd: 3 +0x00000000 0x00000000 - 0xfffffffe r-x
```
What does `siol` means?

**Comment by radare** [comment]
siol is the codename of the rewriting of the IO library from scratch that condret did 2 years ago.

**Comment by radare** [comment]
@condret can you have a look at this?

**Comment by s0i37** [comment]
It seems work
