### ISSUE TITLE
Support `@a:arch:bits` modifiers for `pa` instructions

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14775]
So the command like
```
[0x00000000]> "pa mov eax, 1; nop" @a:x86:16 @ 0x500
```
would work

**Comment by radare** [comment]
Use @b: for bits and it will work

**Comment by XVilka** [comment]
@radare still a bug, since `@a:arch[:bits]` still is how it is supposed to work.

**Comment by radare** [comment]
Works with pd?

**Comment by XVilka** [comment]
@radare yes, it is.

**Comment by radare** [comment]
the problem is the quotes. we can only fix this with an improved command parser

**Comment by ret2libc** [comment]
```
[0x00000000]> "pa mov ax, 1" @a:x86:16 @0x500
b80100
[0x00000000]> "pa mov ax, 1" @a:x86:32 @0@0x500
66b80100
```

This works with `cfg.newshell=1` (aka the new parser). I think we can close this.
