### ISSUE TITLE
Handle 'O' in  panels/panels-zoom

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14857]
To toggle asm.bytes and asm.esil. or maybe just asm.esil

**Comment by radare** [comment]
i use this frequently in trainings to show how  esil looks compared to disasm

**Comment by Vane11ope** [comment]
isnt what "i" does?

**Comment by radare** [comment]
i is to insert bytes or assembly depending if hex or dis

**Comment by Vane11ope** [comment]
yeah of course, thats I, capital. sorry

**Comment by radare** [comment]
i have the feeling that asm.bytes shouhld be disabled by default  in panels :?

**Comment by Vane11ope** [comment]
is it now? or probably depending on user default settings now so you want me to turn it on by default in panels? tbh ive got no idea which way is better but if you say that'd make things more useful then i'd implement that :)

**Comment by radare** [comment]
its not like this now. but this is just a suggestion because in visual we see the disasm in fullscreen and its fine on 80x24, but on panels there's not enough room for that and will be good to discuss about ideas to improve this

**Comment by radare** [comment]
this key should be affecting hexdump and disasm panels imho.

some more comments related to user interactions in panels:

* Handle < and > keys like its done in visual
* Visual marks 'M' maybe? and add a command to list them may be handy to add bookmarks and be able to list them
* O key should affect panels and hexdump
* Scrolling one byte left/right in disasm is possible in disasm, but not in panels (ideas to do that that doesnt involve ':s...')
* as well as we have "Cache" imho we should have an option to toggle if the panel is in sync with the current core->offset or have its own seek. also will be good to have an option to specify which panels will be following scr.interactive words if the rnum.get() is not 0.
