### ISSUE TITLE
Use alternative char instead of \

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#14910]
`\` is a kind of pain to type in many keyboards and its at the end an alias for `=!` which is also a pain ( 2chars as confusing with `!=`). I would suggest to switch to one of the followings:

* `:` (colon)
* `,` (comma)

**Comment by enovella** [comment]
Regrettably, i do like `\` but if you want to change it, please choose one character that uses only 1 keystroke (`,` in this case)

**Comment by radare** [comment]
The comma is used in macros to separate commands..  the colon requires 2 keys.. the parser command for macros can handle ,, in a special way to not break the current behaviour.. i like comma too. But lets wait for more feedback to decide

**Comment by XVilka** [comment]
I suggest `-` character. It is more obvious and unused. If you mean the horizontal split in the visual mode.

**Comment by radare** [comment]
What. We are talking about io.system here

**Comment by radare** [comment]
I added the "'" key in 3.9, and i got some good feedback about it during the r2con. so lets close this and wait if anyone complains/suggest a change
