### ISSUE TITLE
dynstr parsing

### ISSUE THREAD

**Issue by cloudtoad** [radareorg/radare2#14967]
**Is your feature request related to a problem? Please describe.**

r2 never parses dynstr for me.  It always treats the section like code.

**Describe the solution you'd like**

I'd like to see the actual strings.  Or at least an option that says "hey interpret this section like null terminated strings and not a blob of code."

**Describe alternatives you've considered**

Another option is to mask out dynstr and put it in a separate ASCII window (which we can tab too) that has a list of of said strings.

**Additional context**

https://imgur.com/a/QqbuQG9

**Comment by cloudtoad** [comment]
This might be related to the "Unknown DW_FORM 0x06" where it appears DW_FORM_data4 is being used as a section offset, rather than a constant?

**Comment by radare** [comment]
Can you provide a binary and few commands to reproduce the issue? The solution is as easy as filling yhe format field of the section struct in the bin plugin

Do you want to try to submit a pr?

**Comment by cloudtoad** [comment]
The radare2 binary itself.  Load it, hit 'v', then go to the dynstr section.  

Now, if you hit 'g' you can iteratively go to the offset of the beginning of each string and then hit 'd' and then 's' and one-by-one you can get the disassembly panel to show the strings in this section.

PS:  Yes, I'm a noob.

**Comment by radare** [comment]
In commands not keystrokes. And share the binary please

**Comment by Maijin** [comment]
Yeah sharing a binary would really help, you can drag and drop zip archive here 😄

**Comment by cloudtoad** [comment]
Ok.  "commands not keystrokes."

(1) Go into visual mode with the 'v command.'  (The radare2 book calls it the 'v command).
(2) Navigate to the dynstr section of the attached binary.  It is the radare2 binary.
(3) Issue the "go seek" command to go to the beginning of the dynstr section.
(4) Issue the "define string" command for the current block.
(5) Issue the "go seek" command to move to the next string, then go to step 4.  Repeat until all strings are displayed.

Is that what you mean?

[radare2.zip](https://github.com/radare/radare2/files/3586733/radare2.zip)

**Comment by cloudtoad** [comment]
i will make a youtube video later this evening, if that helps.

**Comment by radare** [comment]
what i  was asking for is  just `r2 -qqc'pd 4@section..dynstr' radare2` and  the  output

**Comment by radare** [comment]
as a "workaround" just select with cursor mode the  section and press 'd' and then 'S'  to convert the whole selection  into strings

**Comment by radare** [comment]
the fix must go in here

<img width="715" alt="Screenshot 2019-09-09 at 18 48 46" src="https://user-images.githubusercontent.com/917142/64550158-8da90280-d332-11e9-99d0-04004d2afbd6.png">

**Comment by radare** [comment]
np i just had some time after r2con to try the bin and see the issue you are refering to..

i will try  to do the fix before the next rls

**Comment by radare** [comment]
can you confirm if the bug is fixed?

**Comment by radare** [comment]
we are not adding hints in the dinsym section either, which are a table of relative pointers to the dynsym section. i dont think we can express that with `pf` yet

<img width="1285" alt="Screenshot 2019-10-26 at 07 24 36" src="https://user-images.githubusercontent.com/917142/67614689-acb80280-f7c1-11e9-9351-f8ccc6b4c32b.png">

**Comment by trufae** [comment]
Fixed in master
