### ISSUE TITLE
Remove a2f

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#14964]
`a2f` is largely untested, crashes radare2 very often, and rarely used by anyone. So it should be either removed or moved to radare2-extras

**Comment by radare** [comment]
It save my ass in many situations and i showed it during the training. It works bettwr and faster than af in many situations. For example in sh4. So nope

**Comment by brainstorm** [comment]
Lighten up, @XVilka, it seems to be getting better:

```
$ r2 /bin/ls
 -- Of course r2 runs FreeBSD
[0x1000011e8]> a2f
a2f: Cannot analyze opcode at 0x100001a0c
a2f: Cannot analyze opcode at 0x100001a0c
[0x1000011e8]>
```

It was 6 "Cannot analyze opcode" less than ~10 commits ago, now only 2 ;)
