### ISSUE TITLE
panels: main panel dont resizes after being wider than the terminal width

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15061]
* open panels mode
* make font size big or terminal small
* go back to normal size
* this happens

<img width="582" alt="Screenshot 2019-09-17 at 12 15 10" src="https://user-images.githubusercontent.com/917142/65033178-cd7c7500-d944-11e9-9d4b-b3a663d1c750.png">

**Comment by radare** [comment]
the situation hvae improved but the bug is still there cc @Vane11ope

**Comment by Vane11ope** [comment]
okay on it :)

**Comment by radare** [comment]
Looks fixed to me!
