### ISSUE TITLE
/acj returns invalid JSON

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#15074]
the `/acj <instruction>` command of radare2 returns invalid JSON.

### Expected behavior
The output should be a valid JSON. It needs to begin with `[` and end with `]` to fix this issue.

### Actual behavior
The returned JSON does not start with `[` and does not end with `]`

### Steps to reproduce the behavior 
```
$ r2 /bin/true
[0x000017b0]> /acj pop rax
{"offset":2125184,"len":1,"code":"pop rax"},{"offset":2125384,"len":1,"code":"pop rax"},{"offset":304,"len":1,"code":"pop rax"},{"offset":312,"len":1,"code":"pop rax"},{"offset":15555,"len":1,"code":"pop rax"},{"offset":23508,"len":1,"code":"pop rax"},{"offset":24040,"len":1,"code":"pop rax"},{"offset":24904,"len":1,"code":"pop rax"},{"offset":25066,"len":1,"code":"pop rax"}

```
As you can see, the JSON is not inside `[` and `]`

**Comment by radare** [comment]
This is valid json. Its called: json stream, and its supported by nodejs, jq as well as all the browsers out there. Its just not a single object

**Comment by thestr4ng3r** [comment]
I can't find any standard for this.
I think it would be great to support streaming multiple json objects from a command, especially for tasks. But if this is not specifically standardized without `[]`, I think it would make more sense to just keep them and emit the objects one after another somehow.

**Comment by radare** [comment]
https://en.wikipedia.org/wiki/JSON_streaming

This doesnt mean we shouldnt change that behaviour. I was just explaining what yhe current output is.

**Comment by thestr4ng3r** [comment]
Yes, judging by the code, the behavior is clearly a regression.
