### ISSUE TITLE
/bin/ls cannot analyze at (aac)

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#15091]
Per user, since 3.7.1, aac is producing cannot analyze at warnings

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | x64 
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23127 @ darwin-x86-64 git.3.9.0-13-g5a37bddba commit: 5a37bddbab37545bfafb5fc4858636f607f55ec9 build: 2019-09-20__11:46:08

### Expected behavior

No warnings

### Actual behavior

Full anal.verbose log of aac https://pastebin.com/tTi6KKNC

### Steps to reproduce the behavior 

[ls.zip](https://github.com/radareorg/radare2/files/3635329/ls.zip)

**Comment by radare** [comment]
we can hide those warnings behind anal.verbose but they are helpful to improve the analysis, im totally aware of this

**Comment by radare** [comment]
pls confirm @thestr4ng3r

**Comment by radare** [comment]
still not fixed @thestr4ng3r 
```
[0x10000102c]> aac
Failed to analyze basic block at 0x1000041b2
Failed to analyze basic block at 0x100004440
Failed to analyze basic block at 0x100004434
Failed to analyze basic block at 0x100004506
Failed to analyze basic block at 0x1000044ac
Failed to analyze basic block at 0x10000447c
Failed to analyze basic block at 0x10000441c
Failed to analyze basic block at 0x1000044a6
Failed to analyze basic block at 0x10000448e
Failed to analyze basic block at 0x100004482
Failed to analyze basic block at 0x100004428
Failed to analyze basic block at 0x100004500
Failed to analyze basic block at 0x100004548
Failed to analyze basic block at 0x10000454e
Failed to analyze basic block at 0x10000450c
Overlapped at 0x1000038b4
r_anal_fcn_bb() fails at 0x1000038fb.
r_anal_fcn_bb() fails at 0x10000395d.
r_anal_fcn_bb() fails at 0x10000395d.
r_anal_fcn_bb() fails at 0x100003851.
RET 0x10000398c. overlap=false 21 377
Overlapped at 0x100003952
r_anal_fcn_bb() fails at 0x1000038ac.
r_anal_fcn_bb() fails at 0x100003967.
r_anal_fcn_bb() fails at 0x10000395a.
r_anal_fcn_bb() fails at 0x10000395a.
r_anal_fcn_bb() fails at 0x1000038c4.
Failed to analyze basic block at 0x100003814
Failed to analyze basic block at 0x100004476
Failed to analyze basic block at 0x100004542
Failed to analyze basic block at 0x1000041d8
Failed to analyze basic block at 0x10000442e
Invalid instruction at 0x100001c1a with 64 bits
r_anal_fcn_bb() fails at 0x100001c12.
RET 0x100001c0c. overlap=false 15 566
r_anal_fcn_bb() fails at 0x100001aa7.
r_anal_fcn_bb() fails at 0x100001bdc.
r_anal_fcn_bb() fails at 0x100001bc8.
r_anal_fcn_bb() fails at 0x100001bc8.
r_anal_fcn_bb() fails at 0x100001bc8.
```

**Comment by thestr4ng3r** [comment]
That it prints stuff for `anal.verbose=1` is fine imo.
The `Cannot analyze at 0x000046d8` was because this addr is marked as data and thus the analyzed function has a 0 size. I don't think this makes much sense to report to the user in non-verbose mode (see PR).
