### ISSUE TITLE
Support "uname" and "hostname"

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15114]
To identify target operating system without relaying on system executables

**Comment by v45k0** [comment]
How do you image this? 2 `R_API` functions, one of which returns the `uname` 5-tuple of strings, and a second one which returns only the nodename?

**Comment by radare** [comment]
Use an struct containing the fields that are common in most operating systems, return it in the heap (and add a free method) this rapi function should be in libr/util/sys.c and implemented for windows and unix.

**Comment by radare** [comment]
Also this must be accessible from the “uname” command in the r2 shell. Additional flags can be added like -j for json output

**Comment by aniketnk** [comment]
Can I work on this? 
I need some help. Can you give me an example of another command, so I can figure out how the interface works? For example, how it is invoked, and how it returns the output.

**Comment by radare** [comment]
Yes you can make it. Shouldnt be difficult or long to be implemented and i expect it to be ready before the next release. So in case you cant make it please say it.

See how “ls” is implemented for example. Look at util/sys.c and core/cmd.c then grep for ‘“ls”’ and you may be able to see evrything u need

**Comment by aniketnk** [comment]
Alright! Thanks for the reference, I'll look into it. 
Also, how long do I have until the next release?

**Comment by radare** [comment]
Chrck the milestones github page. Aka by the end of this month

**Comment by radare** [comment]
tired of waiting. im on it

**Comment by radare** [comment]
Anyone for this? https://github.com/radareorg/radare2/issues/15335
