### ISSUE TITLE
Null pointer dereference in r_bin_ne_get_entrypoints()

### ISSUE THREAD

**Issue by fumfel** [radareorg/radare2#15125]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.3 x64 + Clang 9
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 22859 @ linux-x86-64 git.3.9.0-46-g9d7a72f9c commit: 9d7a72f9c68b554bcdc102daf666db5f4f47cce6 build: 2019-09-24__15:46:49

### Expected behavior

No crash in ASAN compiled project.

### Actual behavior

Null pointer dereference in ASAN and SIGSEGV.

### Steps to reproduce the behavior 
- Download `r2_nullptr_r_bin_ne_get_entrypoints` from https://github.com/radareorg/radare2-regressions/pull/1957
- Run radare2 (compiled with ASAN): `r2 -A -qq r2_nullptr_r_bin_ne_get_entrypoints`

### Additional Logs, screenshots, source-code,  configuration dump, ...

ASAN report:

```
==7250==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x7fd8568e7368 bp 0x7fff0f978820 sp 0x7fff0f9787a0 T0)
==7250==The signal is caused by a READ memory access.
==7250==Hint: address points to the zero page.
    #0 0x7fd8568e7367 in r_bin_ne_get_entrypoints radare2/libr/..//libr/bin/p/../format/ne/ne.c:361:47
    #1 0x7fd8568e5a36 in entries radare2/libr/..//libr/bin/p/bin_ne.c:90:9
    #2 0x7fd8567e7059 in r_bin_object_set_items radare2/libr/bin/bobj.c:290:16
    #3 0x7fd8567e6914 in r_bin_object_new radare2/libr/bin/bobj.c:172:2
    #4 0x7fd8567ded0c in r_bin_file_new_from_buffer radare2/libr/bin/bfile.c:481:19
    #5 0x7fd8567c5e61 in r_bin_open_io radare2/libr/bin/bin.c:387:8
    #6 0x7fd857292c9d in r_core_file_do_load_for_io_plugin radare2/libr/core/cfile.c:399:7
    #7 0x7fd85728fc77 in r_core_bin_load radare2/libr/core/cfile.c:610:4
    #8 0x7fd853f103ae in r_main_radare2 radare2/libr/main/radare2.c:1115:15
    #9 0x7fd8536f4b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #10 0x562e5a86b589 in _start (/home/kamil/Desktop/radare2/binr/radare2/radare2+0x1c589)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV radare2/libr/..//libr/bin/p/../format/ne/ne.c:361:47 in r_bin_ne_get_entrypoints
==7250==ABORTING
```

**Comment by radare** [comment]
Can you make a PR adding that if? Thanks!
