### ISSUE TITLE
NES bank mirroring not working

### ISSUE THREAD

**Issue by Masrepus** [radareorg/radare2#15122]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86-64
| File format of the file you reverse (mandatory)      | NES ROM
| Architecture/bits of the file (mandatory)            | 6052 16bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 22866 @ linux-x86-64 git.3.9.0-52-gaa6e232a3 commit: aa6e232a3f6508632b2b6aad36204b52eaba1af7 build: 2019-09-26__09:27:19

### Expected behavior
ROM uses mapper 0 (https://wiki.nesdev.com/w/index.php/NROM), thus having its code located at 0x8000-0xBFFF, with a mirrored version at 0xC000-0xFFFF

### Actual behavior
Primary code at 0x8000 is present, but the mirrored version is not there. This breaks a lot of jumps that target addresses in the mirrored region, thus making control flow analysis hard. But I think r2 somehow knows that it should have something at 0xC000, as this region is filled with zero-bytes instead of 0xFF like the surroundings.

### Steps to reproduce the behavior 
The binary causing this issue is this year's FlareOn "snake" challenge (not sure if sharing it is appreciated while the competition is still ongoing)

**Comment by radare** [comment]
Just add another line in the bin.nes plugin returning a duplicated RIO.map reusing the same ranges. do you want to try to fix this issue? it's just one line. thanks!

**Comment by Masrepus** [comment]
I have looked into this and I think it should be fixed now. It wasn't one line, but on the other hand I probably missed a smarter and quicker way of doing it haha.
