### ISSUE TITLE
'tricore' arch disassembler outputs `mfcr d15, $pc` instead of `mfcr       d15,#0xfe08`

### ISSUE THREAD

**Issue by brandonros** [radareorg/radare2#15150]
From ghidra:

![image](https://user-images.githubusercontent.com/8949910/65835692-5ab1b900-e2b7-11e9-9418-75f9d995a5f4.png)

From rasm2:

```
$ rasm2 -a tricore -o 0x80000000 -D '4d80e0ff'
0x80000000   4                 4d80e0ff  mfcr d15, $pc
```

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/65835724-a8c6bc80-e2b7-11e9-9104-98d8874a28a3.png)

**Comment by brandonros** [comment]
mtcr is wrong too

![image](https://user-images.githubusercontent.com/8949910/65835931-84b8aa80-e2ba-11e9-8d22-5332bdb8094e.png)

```
$ rasm2 -a tricore -o 0x80000000 -D 'cd 00 e0 0f '
0x80000000   4                 cd00e00f  mtcr $pcxi, d0
```

**Comment by stefansiegfried** [comment]
I've started taking a look at this, but it is not obvious to me that the current output is wrong.  Is there a way to pass an option to the disassembler to choose whether it resolves the address to its Special Function Register name?

**Comment by radare** [comment]
The disassembler doesnt do that. Its the rparse plugin who changes numbers for names found in flags or function names. Maybe just removing the # will be enough to make it work without any specific tricore parse plugin

**Comment by c-urly** [comment]
This is done right i am getting the right output in latest master. 
<img width="601" alt="Screenshot 2020-03-08 at 11 58 57 PM" src="https://user-images.githubusercontent.com/14140421/76168805-e732a280-6198-11ea-95df-281823df5c63.png">
