### ISSUE TITLE
Wrappers for setting and getting registers in esil_dfg

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#15153]
add wrapper functions for sdb_set_ptr and sdb_get_ptr in libr/anal/esil_dfg.c

usage of sdb is blocking subregister resolving here, and doing these wrappers would speed up my efforts to fix this

**Comment by radare** [comment]
Just speedup rreg but dont wrap reg access with hashtables

**Comment by condret** [comment]
thx @vifino for doing this
