### ISSUE TITLE
underline memory pointers in "V" mode

### ISSUE THREAD

**Issue by s0i37** [radareorg/radare2#15179]
Hi
Please add the new simple feature - underlining a memory pointers of memory (px) like this:

![temp](https://user-images.githubusercontent.com/22872513/66142507-f2e4d080-e61e-11e9-84fe-5449067751a9.png)
with various colors:
```
red: rw
green:  r-x
cyan: rwx
blue: r--
```

I know about pxr/pxw/pxq but it require alignement and a bit uncomfortable for example during  browsing heap area.

**Comment by radare** [comment]
pxw does that already

**Comment by radare** [comment]
I dont see how would u colorize this without specifying pointer size and alignment...

**Comment by s0i37** [comment]
I presume that pointer size could be obtained from `asm.bits`.
But it seems that even pointers in heap have alignment.
So may be `pxw` will be enought.
