### ISSUE TITLE
<Tab> changing visual mode from Graph mode (VV) to V

### ISSUE THREAD

**Issue by alex-bender** [radareorg/radare2#15181]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64 18.04
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23164 @ linux-x86-64 git.3.9.0-102-gc06cdc465 commit: c06cdc4657c6730561a617f25925a6c635d21c63 build: 2019-10-03__20:41:46

### Expected behavior
Pressing <Tab> key selects next node in graph mode (VV)

### Actual behavior
After <Tab> key being pressed visual mode changes from VV to V, then rotates over modes [switch to the next print mode (or element in cursor mode)]

### Steps to reproduce the behavior 
r2 ./bin
s main
aa
#(in VV mode press `<Tab>`)

**Comment by swoops** [comment]
I have the same trouble. I played with a bit

#### Case: `r2 /bin/ls -c 'aa;s main;VV'`
Works as expected. `agraph_print` calls `r_cons_visual_flush` and the graph is displayed.

#### Case: `r2 /bin/ls -c 'aa;s main+1;VV'` 
Does not show graph view, instead shows `V`. Same results if I hit TAB while in graph view, or use the Fast goto for a basic block.

 The `agraph_print` is called in this case but it exits [here](https://github.com/radareorg/radare2/blob/master/libr/core/agraph.c#L3408) without calling `r_cons_visual_flush`.

I will play with it in my free time, but if someone else thinks they can fix it, please go ahead.

**Comment by swoops** [comment]
I figured out the problem. 

The current seek is being passed to `r_anal_get_bbaddr` so the correct basic block can be found. This uses `r_anal_get_fcn_at` to get the correct function. `r_anal_get_fcn_at` will return NULL unless you pass it the address of the first instruction in the function ([see](https://github.com/radareorg/radare2/blob/master/libr/anal/fcn.c#L2057)). 

Not sure how to fix it. Should `r_anal_get_fcn_at` return the function containing the provided address? Is there another API that does that?

**Comment by radare** [comment]
FIxed in https://github.com/radareorg/radare2/pull/15195
