### ISSUE TITLE
Aarch64: esil incorrectly emulates STP pre-index variant

### ISSUE THREAD

**Issue by ghost** [radareorg/radare2#15184]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux 5.3.1-arch1-1-ARCH x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | Aarch64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23142 @ linux-x86-64 git.3.9.0-102-gc06cdc465, commit: c06cdc4657c6730561a617f25925a6c635d21c63 build: 2019-10-03__21:40:52

### Expected behavior
When esil emulates the 64 bits pre-index variant of `STP` instruction, the `sp` register should be updated (`sp = sp + #<imm>`).

```bash
$ r2 malloc://8
[0x00000000]> e asm.arch=arm
[0x00000000]> e asm.bits=64
[0x00000000]> "wa STP x29, x30, [sp, #0x80]"
Written 4 byte(s) (STP x29, x30, [sp, 0x80]) = wx fd7b08a9
[0x00000000]> pd 1
            0x00000000      fd7b08a9       stp x29, x30, [sp, 0x80]
[0x00000000]> aei
[0x00000000]> aeim
[0x00000000]> aeip
[0x00000000]> ar sp
0x00178000
[0x00000000]> aes
[0x00000000]> ar pc
0x00000004
[0x00000000]> ar sp
0x00178080
```

### Actual behavior
When esil emulates the 64 bits pre-index variant of `STP` instruction, the `sp` register **is not updated**.

```bash
$ r2 malloc://8
[0x00000000]> e asm.arch=arm
[0x00000000]> e asm.bits=64
[0x00000000]> "wa STP x29, x30, [sp, #0x80]"
Written 4 byte(s) (STP x29, x30, [sp, 0x80]) = wx fd7b08a9
[0x00000000]> pd 1
            0x00000000      fd7b08a9       stp x29, x30, [sp, 0x80]
[0x00000000]> aei
[0x00000000]> aeim
[0x00000000]> aeip
[0x00000000]> ar sp
0x00178000
[0x00000000]> aes
[0x00000000]> ar pc
0x00000004
[0x00000000]> ar sp
0x00178000 <--- SP is not set to the new address !!
```
### Steps to reproduce the behavior 
Emulate the above `STP` instruction

### Additional Logs, screenshots, source-code,  configuration dump, ...

https://static.docs.arm.com/ddi0487/ea/DDI0487E_a_armv8_arm.pdf  - page 1236

**Comment by condret** [comment]
are you sure that this is assembled correctly?

**Comment by zadlg** [comment]
> are you sure that this is assembled correctly?

https://asciinema.org/a/MKkxtJVHmmiLobpeXQ8i0aoCO

```
$ echo 'STP x29, x30, [sp, #0x80]' > test.s
$ clang --target=aarch64-arm-none-eabi -c test.s
$ r2 -q -c 'pd 1' test.o 2>&/dev/null
            ;-- entry0:
            ;-- section..text:
            ;-- $x.0:
            0x08000040      fd7b08a9       stp x29, x30, [sp, 0x80]    ; [02] -r
```
This is correctly assembled, according to clang.

```
$ kstool arm64 'STP x29, x30, [sp, #0x80]'
STP x29, x30, [sp, #0x80] = [ fd 7b 08 a9 ]
```
This is correctly assembled, according to keystone.

**Comment by radare** [comment]
@mrmacete can you have a look at this issue?

**Comment by mrmacete** [comment]
`fd7b08a9       stp x29, x30, [sp, 0x80]` is correctly disassembled, but that's actually not pre-index: it's signed-offset instead (which is like pre-index but doesn't write back the base register), so the above instruction not updating `sp` is technically correct.

for future reference:

pre-index: `fd7bb8a9    stp x29, x30, [sp, -0x80]!` (writes back)
post-index: `fd7b88a8    stp x29, x30, [sp], 0x80` (writes back)
signed-offset: `fd7b08a9    stp x29, x30, [sp, 0x80]` (doesn't write back)

The very same goes for the corresponding load instructions.

The current test suite covers these cases and they seem correct. closing.
