### ISSUE TITLE
Support bytes printing in yara format ("pcy" command)

### ISSUE THREAD

**Issue by dmknght** [radareorg/radare2#15216]
**Edited and moved by @ITAYC0HEN from Cutter to radare2.**
---

**Is your feature request related to a problem? Please describe.**

By now radare2 is having multiple formats for parsing hex like C (`pc` command`), Json (`pcj`), Python (`pcp`), Javascript (`pcJ`) so i think it would be useful if radare2 had a similar feature to print yara hex string format so users don't have to replace characters every time. I am well aware to the Yara plugins in r2, but these are not the same as my intention.

**Describe the solution you'd like**

Generate yara format of opcode like `$hex_string = { 0A 0B 0C 1D }`

In such format:
`$hex_startAddr_endAddr = { content }` or `$hex_startAddr_length = { content }`

```
[0x00005850]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00005850  31ed 4989 d15e 4889 e248                 1.I..^H..H

[0x00005850]> pcy 10
$hex_0x5850_10 = { 31 ed 49 89 d1 5e 48 89 e2 48 }
```

**Comment by ITAYC0HEN** [comment]
Transferred this issue and edited the content and the tile of the original one.
