### ISSUE TITLE
pvzj does not work

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#15237]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | 

### Expected behavior

```
[0x00258f9c]> pvz @0x00258F9C
_$_21NDDSServerImportEntry
[0x00258f9c]> pvzj
[{"value":6855709201944953924,"string":"_$_21NDDSServerImportEntry"}]
```

### Actual behavior

```
[0x00258f9c]> pvz @0x00258F9C
_$_21NDDSServerImportEntry
[0x00258f9c]> pvzj
[{"value":6855709201944953924,"string":""}]
```

Via @dark-lpb

**Comment by radare** [comment]
bug confirmed

**Comment by radare** [comment]
use psj meanwhile
