### ISSUE TITLE
/r does not find pushed dereferences of the searched address

### ISSUE THREAD

**Issue by m42a** [radareorg/radare2#15235]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux 64-bit
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 22990 @ linux-x86-64 git.3.9.0-156-g37abed265
| | commit: 37abed265df92fa5ab13fd20c8f8106e78a5d65b build: 2019-10-08__15:06:13

### Expected behavior

`/r 0x69682004` finds the instruction `push dword [0x69682004]`

### Actual behavior

`/r 0x69682004` does not find the instruction `push dword [0x69682004]`

### Steps to reproduce the behavior 
- Run r2 on [the attached binary](https://github.com/radareorg/radare2/files/3704161/x.dll.zip)
- Run `/r 0x69682004`
- Notice the instruction at `0x69681000` does not appear, even though it references the address `0x69682004`

### Additional Logs, screenshots, source-code,  configuration dump, ...

[Dll and assembly](https://github.com/radareorg/radare2/files/3704161/x.dll.zip)

**Comment by radare** [comment]
works fine for me


![Screenshot 2019-10-10 at 12 38 26](https://user-images.githubusercontent.com/917142/66561968-dc78d080-eb5a-11e9-9307-ac80921a80cf.png)

**Comment by radare** [comment]
ah ok the issue is taht the first instruction is not found. i see 1m
