### ISSUE TITLE
Support ThinLTO builds for sys/static

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15243]
<img width="863" alt="Screenshot 2019-10-10 at 11 25 44" src="https://user-images.githubusercontent.com/917142/66556574-c82fd600-eb50-11e9-8d37-49c376311c8f.png">
<img width="1094" alt="Screenshot 2019-10-10 at 11 26 29" src="https://user-images.githubusercontent.com/917142/66556588-cf56e400-eb50-11e9-953a-f9acd32aed94.png">

https://clang.llvm.org/docs/ThinLTO.html

**Comment by XVilka** [comment]
Probably should be supported by Meson first.
