### ISSUE TITLE
Some functions not labeled properly in Android shared libraries

### ISSUE THREAD

**Issue by numin0us** [radareorg/radare2#15260]
**Environment information**
* Operating System: Kali 
* Cutter version: 1.8.3 
* File format: Shared Library (.so) 

**Describe the bug**

I've been using Cutter to solve some Crackmes, I ran into this issue with [this one](https://github.com/OWASP/owasp-mstg/blob/master/Crackmes/Android/Level_03/UnCrackable-Level3.apk) specifically. If you unpack or unzip the APK you will find a library in the lib folder called libfoo.so, which has some dynamically linked Java methods. Java methods in native libraries called by Android apps need to be named as such `Java_com_android_interesting_Stuff_doThingsInNativeLibrary`. In libfoo.so, Cutter detects two of the native methods properly but does not detect `Java_sg_vantagepoint_uncrackable3_MainActivity_init`. If I search for the function I can find it, but on the function bar on the left, it is named entry.init0.

**Expected behavior**

Other disassemblers (like Ghidra) preserve the original name of the function when listing functions, I think that Cutter should follow this behavior as well.

**Comment by ITAYC0HEN** [comment]
transferred this issue from Cutter
