### ISSUE TITLE
Aarch64 - r2 is not able to assemble BIC instructions

### ISSUE THREAD

**Issue by elp0t0r1c0** [radareorg/radare2#15264]
## Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArchLinux X86 64 bits
| File format of the file you reverse (mandatory)      | 
| Architecture/bits of the file (mandatory)            | Aarch64 (arm64)
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23176 @ linux-x86-64 git.3.9.0-196-g76e825ad0 - commit: 76e825ad078930af41969ebb57d669ea6df5cc65 build: 2019-10-13__12:57:54

### Expected behavior
r2 assembles BIC instructions, like `BIC x12, x12, #0x3FF`

### Actual behavior
```bash
rasm2 -aarm -b64 "BIC, x12, x12, #0xf"
  Cannot assemble 'BIC, x12, x12, #0xf' at line 3
  invalid
```

### Steps to reproduce the behavior 
Use r2 or rasm2 for assembling.

### Additional Logs, screenshots, source-code,  configuration dump, ...

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/BIC_log_shift.html

https://static.docs.arm.com/100898/0100/the_a64_Instruction_set_100898_0100.pdf (page 8)

**Comment by x0urc3** [comment]
According to [this](https://developer.arm.com/docs/dui0801/f/a32-and-t32-instructions/bic) assembler can substitube bic for and. Keystone did so

```
$> rasm2 -a arm.ks -b 64 "bic x1, x2, 0xff"
41dc7892
$> rasm2 -a arm -b 64 -d 41dc7892
and x1, x2, 0xffffffffffffff00
```

Should I implement and or bic?

**Comment by radare** [comment]
Seems like both are the same but negating the immediate?

**Comment by x0urc3** [comment]
> Seems like both are the same but negating the immediate?

Yes. Implementation using 'and' requires negating the immediate. However the actual arm opcode for 'and' and 'bic' is different

The question is do you generate actual 'bic' or representative of 'bic' similar to Keystone?

**Comment by radare** [comment]
any plans to solve this issue @x0urc3 ?

**Comment by x0urc3** [comment]
Not in the immediate future
