### ISSUE TITLE
Cannot analyze the IOKit function under Mac OS X

### ISSUE THREAD

**Issue by IceAmber** [radareorg/radare2#15279]
When I analyze a Mac kernel extention by radare2, the IOKit function cannot analyze correctly
0x000008d4      488d3dee0600.  lea rdi, str.IOMedia
0x000008db      31f6           xor esi, esi
0x000008dd      e800000000     call 0x8e2
0x000008e2      4889c7         mov rdi, rax
0x000008e5      e800000000     call 0x8ea
0x000008ea      4989c5         mov r13, rax
0x000008ed      4d85ed         test r13, r13

and the result of ida is

00000000000008D4 48 8D 3D EE 06 00 00                                            lea     rdi, aIomedia 
00000000000008DB 31 F6                                                           xor     esi, esi
00000000000008DD E8 CE 21 00 00                                                  call    __ZN9IOService15serviceMatchingEPKcP12OSDictionary ; IOService::serviceMatching(char const*,OSDictionary *)
00000000000008E2 48 89 C7                                                        mov     rdi, rax
00000000000008E5 E8 C6 22 00 00                                                  call    __ZN9IOService19getMatchingServicesEP12OSDictionary ; IOService::getMatchingServices(OSDictionary *)
00000000000008EA 49 89 C5                                                        mov     r13, rax
00000000000008ED 4D 85 ED                                                        test    r13, r13

**Comment by radare** [comment]
I see the same instructions and offsets so i dont see any issue related to analysis

What i see is some missing symbol names that dont appear in the calls. Without the bin its hard to say why they dont appear, maybe a bug in the bin parser or maybe ida have some flirt signatures that are magically applied under the hood.

But definitely this have nothing to do with analysis

**Comment by IceAmber** [comment]
just as the code shows, the opcode of call in radare2 without address, just E8 00 00 00 00, while it is E8 CE 21 00 00 in ida

I can provide the bin if you need.

**Comment by radare** [comment]
Thats because of the relocs and have nothing to do with analysis. The relocs are set by the bin parser. Yeah if you can share the bin i can take a look

**Comment by IceAmber** [comment]
I had sent the bin to your email several days ago, had you got it?

**Comment by radare** [comment]
uhm where did you send the file? can you send it again?

**Comment by IceAmber** [comment]
I sent the bin to pancake@nopcode.org

**Comment by radare** [comment]
Can you send it again? Because i remembwr seeing it but i cant find the mail or the file now :??

**Comment by IceAmber** [comment]
well, I already send it again

**Comment by radare** [comment]
Yeah, those symbols come from the external relocations which are not parsed by r2 right now, shouldnt be hard to add. btw from my tests, otool fails at this, but dyldinfo, ghidra and hopper work

**Comment by IceAmber** [comment]
OK, it is up to you whether add it or not

**Comment by radare** [comment]
@mrmacete is already working on this. Its obvious that i want and we need to have this in r2.

**Comment by radare** [comment]
enotime for today to get this ready and tested moving for the next release

**Comment by IceAmber** [comment]
ok, thank you
