### ISSUE TITLE
Comment of "Define function here" doesn't be removed after Undefine function

### ISSUE THREAD

**Issue by dmknght** [radareorg/radare2#15325]
**Environment information**
* Operating System: Parrot OS 4.7
* Cutter version: 1.9.0 pulled Oct 20, 0219
* File format: ELF

**Describe the bug**

When I defined a function and then I undefined it, the comment "fcn.<address>" and function name that i defined is still there

**To Reproduce**
Steps to reproduce the behavior in radare2:
1. Go to an address that has no function
2. Analyze the function and give it a name `af myfunction`
3. Delete the function `af- @ myfunction`
4. When doing `pd 10` the flag `myfunction` is still present.

Steps to reproduce the behavior in Cutter:
1. Open binary file, go to address that has no function
2. Right click and select Define function as normal
3. Now right click on function header and select Undefine function
4. The comment of function name is still here (it is added an  unremoved)

**Expected behavior**

The comment of function name / info will be removed

**Screenshots**
Define a function
![Screenshot at 2019-10-21 22-12-08](https://user-images.githubusercontent.com/29118926/67217988-d5ea3300-f44f-11e9-858e-ab23160cc4a2.png)

![Screenshot at 2019-10-21 22-12-29](https://user-images.githubusercontent.com/29118926/67218030-e39fb880-f44f-11e9-9807-a3bbcd10c2f9.png)
Remove this new function (Undefine)

**Additional context**

**Comment by xarkes** [comment]
Done. I'm editing the main post.

**Comment by dmknght** [comment]
Thanks :D
