### ISSUE TITLE
Too many false positives in "xrefs" identification

### ISSUE THREAD

**Issue by bin2415** [radareorg/radare2#15353]
Hi, I want to get all `xrefs` of `ld` by using radare2. However, I got a lot of false positives. I checked the result, and found that radare2 finds `xrefs` even in non-existing instructions. 

I got all the `xrefs` by:

```
> aaaa
> axq > /tmp/radare_xrefs.log
```

Below is the one of the example that I found:
```
0x00407e7f -> 0x0041bff6  CALL
0x00407e80 -> 0x00407ec3  CODE
```
radare2 identifies those two `xrefs` shown as above. However, `0x407e80` is not the start address of an instruction.

I analyzed the instruction in `0x407e7f`:

``` asm
# instruction
407e7f:       e8 72 41 01 00          callq  41bff6 <lang_new_vers_pattern>
``` 

`0x407e7f` is the address of an instruction. When I seek at `0x407e7f` and got the `xrefs` from current address, it can get correct xrefs:
```
[0x00407e7f]> axf
C 0x41bff6 fcn.0041bff6
```
However, When I seek at `0x407e80` which is in the internal of instruction `0x407e7f` and got the `xrefs` from current address, it got "wrong" xref:
```
[0x00407e80]> axf
c 0x407ec3 movabs al, byte [0x8b48a0458b480beb]
```
I checked the instruction in `0x407e80`, and got the below result:
```
[0x00407e80]> pd1
 ┌─< 0x00407e80      7241           jb 0x407ec3
```
It seems that `radare2` deems that `0x407e80` is also the start address of an instruction. I am confused on this result. Here are some questions that I want to consult:

- Is this the right way to extract all the xrefs by using `axj`?
- Does radare2 use `recursive descent` method to disassemble? And why radare2 identifies the address in the internal of an instruction as the start of a new instruction?

## Environment and reproduction 

I am using ubuntu18.04, the radare2 is the latest version from github, which is `radare2 4.0.0-git 23214 @ linux-x86-64 git.3.9.0-263-gdd3ad6d66`. 

And this is the `ld` binary I tested. I tested radare2 by using striped `ld.strip`, and I also upload the `ld` with debug information.
[test.zip](https://github.com/radareorg/radare2/files/3768989/test.zip)

**Comment by bin2415** [comment]
I read the related source code [here](https://github.com/radareorg/radare2/blob/master/libr/core/canal.c#L3888), and found that it linearly scans the `loadable` segments to disassemble the instructions.

**Comment by radare** [comment]
e anal.in=?

**Comment by bin2415** [comment]
```
> e anal.in
io.maps.x
```

**Comment by radare** [comment]
Set it to something else that makes it behave as u expect and share the results. And yep, on linux some regions get exec permissions when they dont contain code which may leas to that issue. The problem is picking the right sections and have a generic option for all fileformats

**Comment by bin2415** [comment]
Thank you! One more question.

Why `radare2` linearly scans all the `executable` regions to disassemble the instructions and find all `xrefs` based on these instructions? As I know, `radare2` already `recursively` disassemble the instructions after `aa` analysis. So why not based on the `recursively` disassembled instructions to find `xrefs`?

**Comment by radare** [comment]
there are sevral different commands to analyze, some of them are linear, some are not

if you have the entrypoint of all the functions and you manage to cover all the control flows recursive is fine, but using linear will discover morereferences and calls that are useful in many sitautions. also, doing aaaa is not recommended unless you dont know what you are doing,

im working on a new branch which is reimplementing the whole analyzsis backend, making it faster and more correct. but if you do 'af' for example, this is recursive analysis and this will spot all the references too, commands like aar or aac are linear. thats up to the user

**Comment by bin2415** [comment]
I see. Thank you for your help!

**Comment by radare** [comment]
So which anal.in is better for your case?

**Comment by bin2415** [comment]
Actually, the references of recursively disassembled instructions are more better for my project. Thank you anyway! I'll close this issue if you don't mind.
