### ISSUE TITLE
Create and apply types from zignatures

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15372]
For example if you have a zignature with [embedded type information](https://github.com/radareorg/radare2/issues/13661) when there is a match it should create a function with a proper arguments names, types and return type.

**Comment by radare** [comment]
This may be easy to do and very useful. As long as signatures hold the types info we can just reapply it when the sign matches. Not just adding a flag like we do now

**Comment by XVilka** [comment]
@oxcabe any updates on this one?
