### ISSUE TITLE
Generate HTML dissasembly output

### ISSUE THREAD

**Issue by oliv3r** [radareorg/radare2#15385]
When publishing information gathered from binaries, It is nice to be able to publish disassembly as HTML code. Just simple things, color coding for example, a-refs for links. Just the basics; but it would allow for example to integrate html generation to a CI pipeline, where any new annotation commit would generate a new HTML output and host it right away. :)

Not sure if this is more related to the front-end (cutter) but since this should be scriptable, I guess having it as a core feature makes more sense.

**Comment by radare** [comment]
pd H> foo.html

or

e scr.html=true
pd > foo.html

**Comment by mmuman** [comment]
Hmm, while it does emit HTML tags, the result looks quite bare, no color, and it doesn't even include the `<pre>` required to have fixed-width font…

**Comment by XVilka** [comment]
Can you please create a test cases for this? I think it should be better
tested. Will help to avoid problems in the future.
