### ISSUE TITLE
Problem connecting to gdbserver using commands

### ISSUE THREAD

**Issue by yossizap** [radareorg/radare2#15399]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior
```
radare2 -A ~/workspace/tests/main
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
 -- git checkout hamster
[0x00400a40]> o gdb://127.0.0.1:1234
= attach 50119 0
[0x00400af0]>
[0x00400af0]> dc
[0x7ffff7bbed2d]>
```

### Actual behavior
```
radare2 -A ~/workspace/tests/main
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
 -- The unix-like reverse engineering framework.
[0x00400a40]> o gdb://127.0.0.1:1234
= attach 50119 0
ptrace (PT_ATTACH): No such process
[0x00400af0]> dc
Cannot continue, run ood?
[0x00000000]>
```

#### Bypass

```
radare2 -A ~/workspace/tests/main
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
-- It's the year of desktop on radare2
[0x00400a40]> o gdb://127.0.0.1:1234
= attach 50119 0
ptrace (PT_ATTACH): No such process
[0x00400af0]> dL gdb
[0x00400af0]> o gdb://127.0.0.1:1234
= attach 50119 0
[0x00400af0]> dc
[0x7ffff7bbed2d]>
```

### Steps to reproduce the behavior 
- Run gdbserver on any binary `gdbserver :1234 /bin/ls`
- Connect in r2 with `o gdb://127.0.0.1:1234`
- Run `dc`
- It's possible to bypass this behavior using:
    -  `o gdb://127.0.0.1:1234`
    - `dL gdb`
    -  `o gdb://127.0.0.1:1234`

Notes: 
- Setting `dL gdb` before `o gdb://...` and/or running `o gdb://..` twice in a row doesn't help.
- Gdbserver sees the connection in the first try, it's just that the debugger isn't configured.

Didn't try reproducing on windows but it might be the same with windbg.

**Comment by yossizap** [comment]
I have managed to "solve" this problem by adding `r_debug_use (core->dbg, "gdb")` after r_core_file_open @ https://github.com/radareorg/radare2/blob/master/libr/core/cmd_open.c#L1308.

The code in radare2.c that handles -D and -d isn't very clear so I am not sure if the debugger should be set and detected when running `o` or in `r_core_file_open`\`r_io_open_nmap`\`r_io_plugin_resolve`\etc.

**Comment by radare** [comment]
U mssed e cfg.debug=true and dL gdb

**Comment by yossizap** [comment]
Thanks! 

Is there a reason not to automatically detect and set it when `o` is ran with `gdb/windbg://*`?

**Comment by yossizap** [comment]
Seems that `dL gdb` before executing `o gdb..` doesn't help since `attach`(which created desc, required by check_connection) only works if the `gdb` plugin is already set. That's why it works after running `o..` -> `dL gdb` -> `o...`
