### ISSUE TITLE
Typing characters like «» insert weird characters

### ISSUE THREAD

**Issue by BlaCoiso** [radareorg/radare2#15407]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows/x86/64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 23200 @ windows-x86-64 git.4.0.0-29-g31d6b5764 commit: 31d6b5764aabc6cf3c254c48c61b1f640032c8f8 build: 03/11/2019__16:00:10,56

### Expected behavior
Typing works properly and shows the correct characters

### Actual behavior
Weird characters are displayed

### Steps to reproduce the behavior 
Try inputting characters like « or »

### Additional Logs, screenshots, source-code,  configuration dump, ...
![image](https://user-images.githubusercontent.com/13855359/68091811-68d99300-fe7c-11e9-8b8d-77cd9a4e3843.png)

**Comment by GustavoLCR** [comment]
e scr.utf8=1

**Comment by BlaCoiso** [comment]
> e scr.utf8=1
Shouldn't that be set by default?

**Comment by GustavoLCR** [comment]
it does if the console codepage is set to utf8 (65001) when r2 starts

**Comment by BlaCoiso** [comment]
This seems to be happening even with scr.utf8 = true (prints Â on key down then « on key up)
![image](https://user-images.githubusercontent.com/13855359/68093881-84e82f00-fe92-11e9-9bbd-8c8e3f7b3c2f.png)

**Comment by BlaCoiso** [comment]
Resetting the config (setting to 0 then back to 1) makes it stop happening
![image](https://user-images.githubusercontent.com/13855359/68093909-d55f8c80-fe92-11e9-85db-512e900131fa.png)
