### ISSUE TITLE
Consistency of hex/dec format representation in output of rax2

### ISSUE THREAD

**Issue by b10s** [radareorg/radare2#15439]
Currently:
```
$ rax2 -S A
41

$ rax2 41
0x29
```

Expected:
```
$ rax2 -S A
0x41

$ rax2 0x41
65
```

**Comment by radare** [comment]
Its an hexpair string. Hex numbers are tied to endianness and packsize issues

**Comment by b10s** [comment]
@radare , sorry, can't get the answer.

`rax2 15` returns `0xf`
but
`rax2 -S A` returns hex without `0x` prefix => `41` which is confusing.

**Comment by radare** [comment]
A string is linearly represented as an hexpairstring this is without 0x prefix. Because its basically one byte after another one.

Numbers are usually handled as basic entities by processors, they are not linear memory, they are stored differently depending on the endianness of the architecture.

If we add a dword/qword representation of strings this will imply being able to specify the endianness and strings will need to have some padding to adjust to the word size

**Comment by b10s** [comment]
@radare thank you for the explanation.

`0x` prefix is just to show it is a hex representation, isn't it ?

E.g. `$ rax2 -S ZZZ` gives us `5a5a5a` but what if it simply give us `0x5a0x5a0x5a` ?

I'm not sure I can understand the reason which brings us to dword/qword representation level and stops to add `0x` to each byte in case of `rax2 -S` out.

I would appreciate if you could explain more, why by adding `0x` we have to split string into dword/qword ?

**Comment by radare** [comment]
no. 0x means its an hexadecial number

0x712782378784787847834783479347834783478347834139808901387 is also a valid hex number, but i have several questions about how this number will look in memory for the reasons explained above. main reason is word size and endiannness which may lead to different confusing representations

**Comment by b10s** [comment]
If there is no difference between `0x5a0x5a` and `0x5a5a` then we can choose latest one as less wordy.

Now we can move forward to solve two questions: endianness and word size.

The out of `$ rax2 -S ABC` is  `414243`.
Would you keep the same logic in terms of endianess and word size ?

**Comment by ret2libc** [comment]
I think there is no bug/incosistency here.

The help says:
```
  -S      raw -> hexstr        ;  rax2 -S < /bin/ls > ls.hex
```

"hex strings" are  a common thing. For example:
```
$ python2 -c 'print "hello".encode("hex")'
68656c6c6f
```
but if you ask python to give you the hex value of a number:
```
$ python2 -c 'print hex(42)'
0x2a
```

The same thing applies here with rax2. Also online you can find many references/tools that use the "hex bytes"/"hex strings" and they don't prefix them with `0x`.

Hope that helps.
