### ISSUE TITLE
Radare2 VS2017 installer offline

### ISSUE THREAD

**Issue by bartblaze** [radareorg/radare2#15443]
Seems like the VS2017 build/installer from https://radare.mikelloc.com/list is offline - https://radare.mikelloc.com/get/4.0.0/radare2_installer-vs2017_64.exe currently returns a 404.

I'm using msvc installer, but thought I'd let you know.

**Comment by XVilka** [comment]
Try the "nightly" build:
- VS 2019 - https://ci.appveyor.com/project/radareorg/radare2/builds/28757933/job/g1tlusabeq9ihl1x/artifacts 
- VS 2017 - https://ci.appveyor.com/project/radareorg/radare2/builds/28757933/job/1rox8sre9uftaq96/artifacts
