### ISSUE TITLE
Assembly of a qword register other than rax is incorrect when moving from pointer with offset

### ISSUE THREAD

**Issue by MartinJM** [radareorg/radare2#15459]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian Stretch (9), 64-bit
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 23261 @ linux-x86-64 git.4.0.0-90-g279f53122 commit: 279f53122f75835a54c6dd89ba8c776f7f0e7e70 build: 2019-11-14__12:51:17

### Expected behavior
When using the "wa" command to change a mov instruction to have the rbx register as a destination, it should assemble the instruction such that the destination really becomes rbx.

### Actual behavior
The destination register will become rax:
```
[0x00000819]> pd 1
            0x00000819      488b5df8       mov rbx, qword [rbp - 8]
[0x00000819]> "wa mov rax, qword [rbp-8]"
Written 4 byte(s) (mov rax, qword [rbp-8]) = wx 488b45f8
[0x00000819]> pd 1
            0x00000819      488b45f8       mov rax, qword [rbp - 8]
[0x00000819]> "wa mov rbx, qword [rbp-8]"
Written 4 byte(s) (mov rbx, qword [rbp-8]) = wx 488b45f8
[0x00000819]> pd 1
            0x00000819      488b45f8       mov rax, qword [rbp - 8]
```

### Steps to reproduce the behavior 
Shortest steps to reproduce the problem:
```
$ r2 -w -
 -- You crackme up!
[0x00000000]> "wa mov rbx, qword [rbp-8]"
Written 4 byte(s) (mov rbx, qword [rbp-8]) = wx 488b45f8
[0x00000000]> pd1
            0x00000000      488b45f8       mov rax, qword [rbp - 8]
[0x00000000]>
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
I don't think there is any relevant additional files, but if I'm wrong, tell me and I'll supply them.

Using a compiled object file (opened in gdb), the two different instructions are:
```
   0x0000000000000001 <+0>:	48 8b 45 f8	mov    rax,QWORD PTR [rbp-0x8]
   0x0000000000000005 <+4>:	48 8b 5d f8	mov    rbx,QWORD PTR [rbp-0x8]
```

**Comment by MartinJM** [comment]
I tested a few other scenarios and only when moving from a pointer with offset is the destination wrongly assembled:
```
[0x00000000]> "wa mov rbx, 5"
Written 7 byte(s) (mov rbx, 5) = wx 48c7c305000000
[0x00000000]> pd1
            0x00000000      48c7c3050000.  mov rbx, 5
[0x00000000]> "wa mov rbx, rax"
Written 3 byte(s) (mov rbx, rax) = wx 4889c3
[0x00000000]> pd1
            0x00000000      4889c3         mov rbx, rax
[0x00000000]> "wa mov rbx, [rax]"
Written 3 byte(s) (mov rbx, [rax]) = wx 488b18
[0x00000000]> pd1
            0x00000000      488b18         mov rbx, qword [rax]
[0x00000000]> "wa mov rbx, [rax-8]"
Written 4 byte(s) (mov rbx, [rax-8]) = wx 488b40f8
[0x00000000]> pd1
            0x00000000      488b40f8       mov rax, qword [rax - 8]
[0x00000000]> "wa mov rbx, [rbx-8]"
Written 4 byte(s) (mov rbx, [rbx-8]) = wx 488b43f8
[0x00000000]> pd1
            0x00000000      488b43f8       mov rax, qword [rbx - 8]
```

**Comment by MartinJM** [comment]
It seems to be true for at least rcx as well:
```
[0x00000000]> "wa mov rcx, rbx"
Written 3 byte(s) (mov rcx, rbx) = wx 4889d9
[0x00000000]> pd 1
            0x00000000      4889d9         mov rcx, rbx
[0x00000000]> "wa mov rcx, [rbx]"
Written 3 byte(s) (mov rcx, [rbx]) = wx 488b0b
[0x00000000]> pd 1
            0x00000000      488b0b         mov rcx, qword [rbx]
[0x00000000]> "wa mov rcx, [rbx - 8]"
Written 4 byte(s) (mov rcx, [rbx - 8]) = wx 488b43f8
[0x00000000]> pd 1
            0x00000000      488b43f8       mov rax, qword [rbx - 8]
```

**Comment by MartinJM** [comment]
I can confirm that it's still present after the latest commit:
```
$ r2 -v
radare2 4.1.0-git 23265 @ linux-x86-64 git.4.0.0-92-ga598e640d
commit: a598e640df4e7fe0f316bfe622ba421de7f26f62 build: 2019-11-14__18:10:48
$ rasm2 -b 64 "mov rbx, qword [rbp-8]" | rasm2 -Db 64 -
0x00000000   4                 488b45f8  mov rax, qword [rbp - 8]
```

I can also confirm that this [patch.txt](https://github.com/radareorg/radare2/files/3847734/patch.txt) works:
```
$ git apply ../patch.txt
$ rasm2 -b 64 "mov rbx, qword [rbp-8]" | rasm2 -Db 64 -
0x00000000   4                 488b5df8  mov rbx, qword [rbp - 8]
```

I have also tested all the unit tests from the regressions repo, which all pass. I cannot test the regressions tests, as NodeJS doesn't want to work on my current install.

**Comment by radare** [comment]
Can you submit a PR instead?

**Comment by MartinJM** [comment]
I didn't want to do that yet as I've only confirmed this patch working on this specific problem. It's not written from the specification, but rather from the point of solving a specific problem. Which is why I'd rather have someone else - who knows a bit more about the code - to take a look at it first.

And on top of that, I haven't been able to run all (regression) tests yet, so maybe it'll even fail those.

If you'd like a PR despite these concerns of mine, I'll make one.

**Comment by radare** [comment]
We have a test suite to test contributions

I won’t review the code in a txt, github prs are great for that

**Comment by MartinJM** [comment]
Ok, I'll make a PR in a minute then.

If you don't want patches, I suggest removing the Contributing with patches from DEVElOPERS.md: https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#contributing-with-patches

**Comment by radare** [comment]
removed. thank you

**Comment by MartinJM** [comment]
No problem, glad I could help :)
