### ISSUE TITLE
Data Metadata incorrectly interpreted when previous instruction ends in the middle

### ISSUE THREAD

**Issue by Cooler1989** [radareorg/radare2#15473]
### Work environment
Ubuntu x86 64bit
Binary file
arch m68k 16b(not fixed)
radare2 4.1.0-git 23191 @ linux-x86-64 git.4.0.0-29-g31d6b5764
commit: 31d6b5764aabc6cf3c254c48c61b1f640032c8f8 build: 2019-11-03__21:04:33

### Expected behavior
Marking 4 bytes using 'dw' in visual mode should yield visible word interpretation in all previous offset position same as for relative offset 0x0 (abs 0x64)

0x00000064      .dword 0x0000a3da ; fcn.0000a3da   
0x00000068      .dword 0x0000a496 ; fcn.0000a496   
0x0000006c      .dword 0x00000192                  
0x00000070      .dword 0x00000192                  

### Actual behavior
Moving just one line above gives:

0x00000060      00c00432                          
0x00000061      c004           and.b d4, d0       
0x00000063      3200           move.w d0, d1      
0x00000065      .dword 0x00a3da00                 
0x00000068      .dword 0x0000a496 ; fcn.0000a496  
0x0000006c      .dword 0x00000192                 
0x00000070      .dword 0x00000192                 

which makes crippled word from 3 bytes losing refernced function name.

**Comment by radare** [comment]
can you provide a reproducer with comamnds?

**Comment by XVilka** [comment]
@Cooler1989 ping?

**Comment by Cooler1989** [comment]
Hi, sorry for leaving it unresolved but I managed to do my job with this inconvienience. I am still not sure if it is bug or just some fuzzy mechanism for determining assembler insructions. By "fuzzy" I mostly mean I do not fully understand it and I my doubts were based on my internal presumptions which was: "if I mark 4 bytes as data it should never be interpreted as part of some instruction". To resolve it I would have to find some doc with explanation or decode it from sources. Unfortunetally I do not have the time right now for neither.

**Comment by ret2libc** [comment]
I have renamed the issue, because this is not just about one architecture. It's an issue with how the metadata are handled.

This is a reproducer:
```
$ radare2 ./test/bins/elf/ls
[0x00005ae0]> s 0x5b00
[0x00005b00]> pd 10
[0x00005b00]> Cd 4 4
[0x00005b00]> pd 4
            0x00005b00      .dword 0x3d8d4800
            0x00005b04      .dword 0xffffe568
            0x00005b08      .dword 0xc30a15ff
            0x00005b0c      .dword 0x90f40001
```
At this point, as you can see the first data is defined at `0x00005b00` and it shows the value `0x3d8d4800`.
Now, let's move back one byte
```
[0x00005b00]> s -1
[0x00005aff]> pd 5
            0x00005aff      0100           add dword [rax], eax
            0x00005b01      .dword 0x683d8d48
            0x00005b04      .dword 0xffffe568
            0x00005b08      .dword 0xc30a15ff
            0x00005b0c      .dword 0x90f40001
```
As you can see, now the first data is defined at `0x00005b01` and it contains the value `0x683d8d48`.

This is wrong. While it is "ok" to have `0x00005aff` showing the full instruction, the data should still start at `0x00005b00` and it should still contain the original value, which was `0x3d8d4800`. Probably we can use a similar behaviour to midflags, with `~` meaning that some instructions overlap.

**Expected output**
```
[0x00005b00]> s -1
[0x00005aff]> pd 5
            0x00005aff  ~   0100           add dword [rax], eax
            0x00005b00      .dword 0x3d8d4800
            0x00005b04      .dword 0xffffe568
            0x00005b08      .dword 0xc30a15ff
            0x00005b0c      .dword 0x90f40001
```
