### ISSUE TITLE
Add R2_PKGCONFIG or something like that in `r2 -H`

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15478]
For example, by default `PKG_CONFIG_PATH` is not set for `/usr/local/lib/pkg_config`, but r2 installs there by default. We return all paths required for the r2 plugins, what do you think about returning also this one, for setting it up before calling `pkg-config --cflags r_core` for example?

**Comment by radare** [comment]
Thats what r2pm do

**Comment by radare** [comment]
Use R2_LIBDIR=/usr/local/lib + "/pkgconfig"
