### ISSUE TITLE
Win32 over ssh

### ISSUE THREAD

**Issue by jorgeventura** [radareorg/radare2#15475]
I am running:
radare2 4.1.0-git 23431 @ windows-x86-32 git.4.0.0-87-gc2ad608ee                                                                
commit: c2ad608ee9e79616383ddee4cd016afc449ee2cd build: Wed 11/13/2019__11:58:13.06
over ssh from a linux workstation.

When I use radare2 and go to visual mode, I have a blank line inserted in that panel. I would like to know if someone can give me a direction of some spots in the code that I can try to solve this issue by myself. Of course if some one have any other suggestion will be welcome.

Sincerely,
Jorge Ventura

**Comment by radare** [comment]
Can you add a screenshot? I guess this is a bug in windows, not in r2. But r2 provides some scr. eval vars to force a specific terminal size or add a delta to the one reported by the operating system

**Comment by jorgeventura** [comment]
Yes. The problem is Windows.

Thank you

**Comment by XVilka** [comment]
@jorgeventura I recommend you to open the bug in Microsoft Terminal repository, assuming you used this: https://github.com/microsoft/terminal
