### ISSUE TITLE
Build options no effect

### ISSUE THREAD

**Issue by unclenull** [radareorg/radare2#15485]
Options passed to `sys/install.sh` has no effect. 
Take for example, `sys/install.sh  --with-syscapstone`.
The problem is that `--with-syscapstone` is passed to `configure` incorrectly in `sys/build.sh`:
```sh
142: ./configure ${CFGARG} --prefix="${PREFIX}" || exit 1
```
`--with-syscapstone` is passed as a value of `--prefix`, instead it should keep alone.

**Comment by radare** [comment]
please test this https://github.com/radareorg/radare2/pull/15486
