### ISSUE TITLE
SVD file parser-mapper into r2 - Memory layout/map configuration database

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15484]
This issue is a sub-task of #8467

like this: but shipped with r2 to make it easy to use
https://github.com/haystack-ia/radare-funhouse/blob/master/STM32F103XX.r2
https://blogs.coreboot.org/blog/2019/08/22/gsoc-ghidra-firmware-utilities-wrap-up/
https://awesomeopensource.com/project/al3xtjames/ghidra-firmware-utils
https://github.com/posborne/cmsis-svd
https://github.com/posborne/cmsis-svd/pull/86/files

**Comment by brainstorm** [comment]
https://github.com/leveldown-security/SVD-Loader-Ghidra

**Comment by XVilka** [comment]
Related to https://github.com/radareorg/radare2/issues/8467

**Comment by Maijin** [comment]
Yes this is #8467 so closing here and moving the URL there.

**Comment by Maijin** [comment]
Duplicate of #8467

**Comment by radare** [comment]
that's not a duplicate and i was actually not finding this issue because it was closed :<<<<<<<<<

**Comment by radare** [comment]
here's an svd parser in Rust, maybe we can use it in r2-extras to parse the svd files and map the devies in r2 from here https://github.com/rust-embedded/svd

**Comment by radare** [comment]
maybe this should be moved to r2-extras

**Comment by XVilka** [comment]
Not really, it's a core feature for the embedded.

**Comment by radare** [comment]
Then we need a parser in c. Any link to chk those svd files handy?

**Comment by Maijin** [comment]
it is a duplicate, the issue 8647 is about adding CPU information including ability to parse SVD... It is in the list.

**Comment by Maijin** [comment]
Just read the comments - there are even been discussion over the different format - what should be parsed made by @queenp 3 years ago.

**Comment by Maijin** [comment]
Ok I've added references on both. Now this one is a "sub-task" of the old one - problem solved.

**Comment by radare** [comment]
done in https://github.com/radareorg/radare2-extras/tree/master/r2svd
