### ISSUE TITLE
Seek history should provide indicator about the current position in history

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#15495]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | Recent from master

This problem originally raised by @karliss on https://github.com/radareorg/cutter/issues/1617#issuecomment-507417573

### Expected behavior

`sj` should provide information\indicator about the current location inside the seek history.

### Actual behavior

sj currently looks unusable. It includes undo and redo history  without any indicator of current location inside history.
```
[0x0002bad0]> s*
f undo_5 @ 0xb120
f undo_4 @ 0xb080
f undo_3 @ 0x2bad0
f undo_2 @ 0x27db0
f undo_1 @ 0x2bad0
f undo_0 @ 0x27db0
# Current undo/redo position.
f redo_0 @ 0x27db0
f redo_1 @ 0x27d10
f redo_2 @ 0x2bad0 
```

```
[0x0002bad0]> sj~{}
[
  {
    "offset": 45344,
    "symbol": "entry.fini0"
  },
  {
    "offset": 45184,
    "symbol": "entry0"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  },
  {
    "offset": 163248,
    "symbol": "sym.strcache_add"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  },
  {
    "offset": 163248,
    "symbol": "sym.strcache_add"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  },
  {
    "offset": 163248,
    "symbol": "sym.strcache_add"
  },
  {
    "offset": 163088,
    "symbol": "sym.strcache_iscached"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  }
] 
```

**Comment by radare** [comment]
done
