### ISSUE TITLE
escr.utf8=0 gets ignored breaking radare2-regressions

### ISSUE THREAD

**Issue by karliss** [radareorg/radare2#15512]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArchLinux x86-64
| File format of the file you reverse (mandatory)      | radare2-regressions
| Architecture/bits of the file (mandatory)            | radare2-regressions
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 23444 @ linux-x86-64 git.4.0.0-138-g521ac7c28 commit: 521ac7c28f42a24586bc0b02f10feb75900a066c build: 2019-11-27__15:10:12

### Expected behavior
Running `make -k js-tests` reports no test failures.

### Actual behavior
Some of the tests with tables fail due to difference in utf8 symbol usage even though test command line specifies `escr.utf8=0`

### Steps to reproduce the behavior 
* checkout r2 version specified above
* `sys/user.sh`
* checkout radare2-regresions 83cb8e658496ea4854fa3fc74870500987670e0d
* `make -k js-tests` observe errors in tests with tables

### Additional Logs, screenshots, source-code,  configuration dump, ...

```
[XX] db/tools/rabin2 rabin2 -K md5 -S file  290
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i /tmp/tmp-176405A85gETSX88YX ../bins/pe/a.exe
!rabin2 -K md5 -S ${R2_FILE}

 [Sections]
 
 nth paddr        size vaddr        vsize perm name
---------------------------------------------------
+――――――――――――――――――――――――――――――――――――――――――――――――――
 0   0x00000400  0xa00 0x00401000  0x1000 -r-x .text
 1   0x00000e00  0x200 0x00402000  0x1000 -rw- .data
 2   0x00001000  0x200 0x00403000  0x1000 -r-- .rdata
 3   0x00000000    0x0 0x00404000  0x1000 -rw- .bss
 4   0x00001200  0x400 0x00405000  0x1000 -rw- .idata

EXPECT=<<RUN
[Sections]

nth paddr        size vaddr        vsize perm name
――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000400  0xa00 0x00401000  0x1000 -r-x .text
1   0x00000e00  0x200 0x00402000  0x1000 -rw- .data
2   0x00001000  0x200 0x00403000  0x1000 -r-- .rdata
3   0x00000000    0x0 0x00404000  0x1000 -rw- .bss
4   0x00001200  0x400 0x00405000  0x1000 -rw- .idata
```

**Comment by radare** [comment]
we use an env var to override the settings at startup. im not happy about this change but other ppl wanted it. so we can open the discussion or make the js suite use the env var

**Comment by karliss** [comment]
As long as test suite works consistently and doesn't require manually preparing environment I don't care if it is an environment variable or commandline flag.

**Comment by karliss** [comment]
So what's the environment variable that I need to set for disabling utf8 or did I misunderstood something?

**Comment by karliss** [comment]
I assume you meant locale environment variables although I expected them to be used only as default values and escr.utf8 having higher priority.

**Comment by radare** [comment]
Yes i was expecting the same behaviour but everyone in r2land complained. We can diacuss this again because imho thats the way to go

**Comment by karliss** [comment]
Any links to the previous discussions?
What's the use case? Are people  accidentally writing escr.utf8 in their configuration?

**Comment by ret2libc** [comment]
I agree it is misleading seeing tests working differently from what expected.

**Comment by kazarmy** [comment]
> Some of the tests with tables fail due to difference in utf8 symbol usage even though test command line specifies `escr.utf8=0`

This is because the `-escr.utf8=0` isn't passed to rabin2.

> So what's the environment variable that I need to set for disabling utf8 or did I misunderstood something?

https://github.com/radareorg/radare2/blob/e0b197766811db0952d243b2df36969d34cee36e/.travis.yml#L32 ugly but it works
