### ISSUE TITLE
6502 BIT instruction

### ISSUE THREAD

**Issue by csBlueChip** [radareorg/radare2#15547]
Hi,
I authored the 6502 "datasheet" referenced here https://github.com/radareorg/radare2/blob/master/libr/anal/p/anal_6502.c#L6

Last week I noticed there was a critical error in that document for the BIT instruction. The correct logic is:
``` 
 t = A & M
  P.N = M.7  // *NOT* P.N = t.7
  P.V = M.6  // *NOT* P.V = t.6
  P.Z = (t==0) ? 1:0
 ```
I've looked at https://github.com/radareorg/radare2/blob/master/libr/anal/p/anal_6502.c#L463 but I have no idea what it means - so I can't tell if you've implemented my error

...so this is a heads up, that you MAY have a bug in your 6502 implementation :/

BC

**Comment by xarkes** [comment]
cc @condret

**Comment by thestr4ng3r** [comment]
Indeed, we have this bug implemented. Thanks for reporting!
