### ISSUE TITLE
Using '$' variables in '@@' cycles

### ISSUE THREAD

**Issue by s0i37** [radareorg/radare2#15550]
I am trying to create flags for every offsets from file:
```
fs taint

f $$ @@.taint.log
```
or
`f '?v $$' @@.taint.log`

**Describe the solution you'd like**
I want to create unique flags for every address from file using '$' variables. Where address is flag name.

**Describe alternatives you've considered**
Of course I can use python script but I want to make this with r2 command because it is faster and
more convenient in my opinion.

**Comment by radare** [comment]
Use a quoted macro to do that

**Comment by s0i37** [comment]
Nothing:
```
(a ,  s)
f `.(a)` @@.taint.txt
f
> 0x00033af4 1 0x2e38
```

```
(f addr, f $0)
.(f $$) @@.taint.txt
f
> 0x00033af4 1 __
```

**Comment by radare** [comment]
i dont see any quoted macro in your snippet

**Comment by radare** [comment]
also flag names cant start with numbers, so u need to set a prefix. here's an example:

```
$ r2 -
[0x00000000]> "(setflag,f foo_`?v $$`)"
[0x00000000]> .(setflag) @@.offsets.txt
0x0000000a: .(setflag)
0x00000014: .(setflag)
0x0000001e: .(setflag)
[0x00000000]> f
0x0000000a 1 foo_0xa
0x00000014 1 foo_0x14
0x0000001e 1 foo_0x1e
[0x00000000]>

```
