### ISSUE TITLE
Use tmp/ as the directory for temporary files

### ISSUE THREAD

**Issue by neuschaefer** [radareorg/radare2#15565]
Currently /tmp/ and the r2r source directory are used for temporary files needed while testing. This is a bit ugly IMHO, because you can't easily remove these files (without actually looking where they are).
The makefile already has a `clean` target that removes tmp/, so I suggest putting everythin in there.

Comments are welcome.

**Comment by radare** [comment]
Why? We should create real temporary files. This is a wrong approach. Close the issue pls
