### ISSUE TITLE
R2R.js improvement - integrate with GitHub

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15578]
In theory it's possible to
 - [ ] Get the ID and status of the current Travis job for the Pull Request
 - [ ] Run the script and add a comment to PR if there are new breakages or fixed tests

Would improve the ability to quickly see the correctness of the every PR

See https://developer.github.com/v3/pulls/ for GitHub API for PRs and https://developer.github.com/v3/issues/comments/ for GitHub API for adding a comment (or updating it)

See how to access the status of the commit/PR https://developer.github.com/v3/repos/statuses/

**Comment by radare** [comment]
Wrong repo move to node-r2r

**Comment by MaskRay** [comment]
> regression testsuite was rewritten into the plain C, we dropped JavaScript out

Close?
