### ISSUE TITLE
Re-enable debug tests

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#15587]
Right now the debug tests are stalling when launched in r2r (locally and on travis) and have been disabled - https://github.com/radare/radare2-regressions/tree/master/new/notworking_db

It's important we try to understand what's going and fix that problem so we can have the debug tests back in the CI to avoid regressions.

**Comment by XVilka** [comment]
Can we try to do that for SourceHut and GitHub Actions? They should work on both.

**Comment by radare** [comment]
What about 4.5? So we can focus on the release

**Comment by XVilka** [comment]
@radare plan is to try - if they work without any problem - enable them, if not - postpone fixes to the later release.

**Comment by radare** [comment]
Plans end tomorrow

**Comment by thestr4ng3r** [comment]
wdym? the debug tests are already enabled:
![Screenshot from 2020-04-11 11-07-05](https://user-images.githubusercontent.com/1460997/79039875-9cb3a400-7be4-11ea-9fb4-a10a7826c0f2.png)
