### ISSUE TITLE
Unit tests support for timing out

### ISSUE THREAD

**Issue by roboman2444** [radareorg/radare2#15584]
One of my (new) unit tests results in an infinite loop (see https://github.com/radare/radare2-regressions/pull/1397 and https://github.com/radare/radare2/issues/10689).

Supporting a timeout on these would be useful. Might also be useful to grab timing information to see if there are performance regressions.

**Comment by radare** [comment]
This is planned in the new testsuite but the issue should be in the node-r2r repo not here

**Comment by trufae** [comment]
this is implemented in `r2r -t`
