### ISSUE TITLE
Make more intuitive how to select test with r2r.js

### ISSUE THREAD

**Issue by giuscri** [radareorg/radare2#15582]
Right now 791e30e482c773f3c930450069dcdf128876adb9, selecting a test or a family of tests with r2r.js is confusing as test names look like paths (this is a feature imho) and user might try to pass a path instead of a name. That won't work though, as path are _longer_ than test names.
```
    // Load tests
    const walker = walk('db', {followLinks: false});
    const filter = argv._[0] || ''; 
    walker.on('file', (root, stat, next) => {
      const testFile = path.join(root, stat.name);
      if (testFile.indexOf(filter) === -1) {
        return next();
      }   
```
Example:
```
$ ./bin/r2r.js ./db/cmd/cmd_fs 
Done
$ ./bin/r2r.js db/cmd/cmd_fs 
[**]                  db/cmd/cmd_fs   OK   14 BR    0 XX    0 FX    0
Done
```

**Comment by radare** [comment]
Im redoing the whole testsuite al this stuff is in my mind already so we can close this

**Comment by thestr4ng3r** [comment]
New r2r uses paths.
