### ISSUE TITLE
Merge all the *.sh in the root directory into one

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15598]
* r2r is the name of the r2r.js (npm i -g node-r2r)
* cherrypull.sh must die
* overlay.sh i guess its used by travis, so may be worth
* r2-v is useful, but 
* we can probably replace those with just makefiles

comments, feedback, ideas?

**Comment by XVilka** [comment]
Was largely fixed with the new r2r I think.

**Comment by thestr4ng3r** [comment]
The only remaining is `cherrypull.sh` which I have no idea what it even does.

**Comment by radare** [comment]
We csn delete cherrypull it was helpful for me to clone and meege remote branches easily but nowadays im used to use the raw git commanss by hand so im not using it anymore
