### ISSUE TITLE
make tests fails

### ISSUE THREAD

**Issue by Tatsujinichi** [radareorg/radare2#15601]
Skipping db/archos/darwin-x64/cmd_i because platform differs.
[**]                   db/anal/6502   OK 11967 BR  977 XX    1 FX   33
[**]                   db/anal/8051   OK 11991 BR  977 XX    1 FX   33
[**]                    db/anal/arc   OK 12049 BR  983 XX    1 FX   33
[**]                    db/anal/arm   OK 12097 BR  988 XX    1 FX   33
[**]             db/anal/arm.gnu_16   OK 12116 BR  988 XX    1 FX   33
[**]                    db/anal/avr   OK 12145 BR  989 XX    1 FX   33
[**]                  db/anal/chip8   OK 12154 BR  989 XX    1 FX   33
[**]                db/anal/classes   OK 12155 BR  989 XX    1 FX   33
[**]                 db/anal/dalvik   OK 12158 BR  989 XX    1 FX   33
[**]                   db/anal/java   OK 12173 BR  990 XX    1 FX   33
[**]                   db/anal/m68k   OK 12173 BR  990 XX    1 FX   34
[**]                  db/anal/mach0   OK 12174 BR  990 XX    1 FX   34
[**]                   db/anal/mips   OK 12196 BR  991 XX    1 FX   34
[**]                 db/anal/msp430   OK 12197 BR  992 XX    1 FX   34
[**]                    db/anal/ppc   OK 12201 BR  992 XX    1 FX   34
[**]                     db/anal/sh   OK 12203 BR  992 XX    1 FX   34
[**]                  db/anal/thumb   OK 12204 BR  992 XX    1 FX   34
[**]         db/anal/tms320.c64x_32   OK 12205 BR  992 XX    1 FX   34
[**]                db/anal/tricore   OK 12210 BR  992 XX    1 FX   34
[**]                 db/anal/x86_16   OK 12213 BR  992 XX    1 FX   34
TypeError: Cannot read property 'on' of undefined
    at /home/myuser/dev/radare2/radare2-regressions/new/node_modules/node-r2r/index.js:248:24
    at Generator.next (<anonymous>)
    at onFulfilled (/home/myuser/dev/radare2/radare2-regressions/new/node_modules/co/index.js:65:19)
TypeError: Cannot read property 'on' of undefined
    at /home/myuser/dev/radare2/radare2-regressions/new/node_modules/node-r2r/index.js:248:24
    at Generator.next (<anonymous>)
    at onFulfilled (/home/myuser/dev/radare2/radare2-regressions/new/node_modules/co/index.js:65:19)
[XX] WAT DO db/anal/x86_32
Cannot read property 'on' of undefined
events.js:173
      throw er; // Unhandled 'error' event

**Comment by Maijin** [comment]
Obsolete
