### ISSUE TITLE
C testsuite - add the option to save the log

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15607]
To produce the text output without color codes/etc and save it into the log. Maybe do a separate errors-only log too.

**Comment by radare** [comment]
Ill honor an env var to do colors or not instead of saving a log. We can run travis with thisnoption to ease readability

**Comment by thestr4ng3r** [comment]
See also the `-L` option.

**Comment by trufae** [comment]
There's `-o` for json logging. as well as the already menteioned `-L` flag. there's no need to have this, and if any change is needed will be done at the time. closing
