### ISSUE TITLE
Add global path for plugins

### ISSUE THREAD

**Issue by dmknght** [radareorg/radare2#15620]
**Is your feature request related to a problem? Please describe.**
By now radare2 only has 1 plugin path at `$HOME/.local/share/radare2/plugins/` on Linux so it is 
impossible for me to create pre-compiled plugin on repository (Debian based distro). And for me it will be pretty cool if i can ship r2ghidra-decompiler with radare2 and radare2-cutter with radare2 package (and more as more plugins as possible).
Goals:
- Plugins can be installed using `apt` (for Debian based distros)
- Users don't need to wait plugins be compiled
- Get rid of version conflict (plugins should be upgraded with radare2 by apt)
- All users can use plugins (if the system has multiple users)
- For r2ghidra-dec, the plugin works for both radare2 and radare2-cutter. By now install r2ghidra-dec using r2pm can't be used for radare2-cutter. It will be the same for any plugin like this.

**Describe the solution you'd like**
Radare2 add 1 more plugin path (for example `/usr/share/radare2/plugins/`) and read plugins from this path and keep the `.local` path.

**Describe alternatives you've considered**

**Additional context**

**Comment by radare** [comment]
Its in local/lib/radare. See r2 -H
