### ISSUE TITLE
tests: make tests reproducible

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#15625]
Some tests modify existing files, which make tests hardly reproducible. Tests should not modify files in place, but copy them somewhere else if necessary.

**Comment by radare** [comment]
only the ones related to fatmach0-true iirc

**Comment by ret2libc** [comment]
Yes, that's the one I'm aware of at least.

**Comment by radare** [comment]
should be easy to fix now that we have the cp command in r2 :P

**Comment by radare** [comment]
this is done already
