### ISSUE TITLE
rasm2 cannot assemble `neg eax`

### ISSUE THREAD

**Issue by jstaursky** [radareorg/radare2#15633]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 23299 @ linux-x86-64 git.4.0.0-217-g1d3698bc9 commit: 1d3698bc96a09e45c4fff4c090278623f146929c build: 2019-12-14__20:42:14

### Expected behavior
`rasm2 -a x86 -b 32 'neg eax'` should output `F7D8`
### Actual behavior
![image](https://user-images.githubusercontent.com/25406664/70856938-3a0aff80-1eb3-11ea-9c45-238e52a67457.png)

### Steps to reproduce the behavior 
See screenshot.

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/tree/master/new/db/asm** (See https://github.com/radare/radare2-regressions/blob/master/new/README.md) You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```

**Comment by x0urc3** [comment]
Already exist in latest git

"""
$> r2 -v
radare2 4.2.0-git 23640 @ linux-x86-64 git.4.1.1-155-gdd95ed40a
commit: f09468c87989f7ace5e541975fbeeb19e128dfe1 build: 2020-01-21__18:48:37
$> rasm2 -a x86 -b 32 'neg eax'
f7d8
"""

**Comment by Maijin** [comment]
Then closing thanks @x0urc3

**Comment by radare** [comment]
may be good to have a test for asm/disasm this neg instruction

can you add it @maijin?

**Comment by Maijin** [comment]
Actually - it's not fixed in x86.nz. It only works with keystone.

**Comment by x0urc3** [comment]
> Actually - it's not fixed in x86.nz. It only works with keystone - #15897

My bad. So keystone is default for x86 when available?
