### ISSUE TITLE
Graph flow doesn't change when modifying instructions

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#15644]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 24001 @ linux-x86-64 git.4.0.0-226-g89a5320e5 commit: 89a5320e5f918327f6f528fa325eeef6567932a8 build: 2019-12-16__08:20:38

### Expected behavior

Graph flow should change after editing bytes or instructions according to the new value

### Actual behavior

The flow stays the same even when it doesn't makes sense according to the new disassembly

Before the change:
![image](https://user-images.githubusercontent.com/20182642/70893948-c113c100-1ff4-11ea-8d4a-409dc32feec1.png)

I will `nop`  0x00400609 and the flow will wrongly stay the same

![image](https://user-images.githubusercontent.com/20182642/70894033-e56f9d80-1ff4-11ea-8189-83610fc5a4d8.png)

### Steps to reproduce the behavior 
- Open a binary with radare2 in write mode
- Perform analysis
- Open graph view and spot a conditional jump you want to modify or nop
- Modify it (e.j `je` -> `jne` or `nop`)
- Refresh graph and see that it stays the same

### Additional Logs, screenshots, source-code,  configuration dump, ...

Binary: https://github.com/LiveOverflow/liveoverflow_youtube/raw/master/0x05_simple_crackme_intro_assembler/license_1

**Comment by radare** [comment]
Known behaviour and there are other issues related to this. I actually filled one explaining different proposals to solve the problem

**Comment by radare** [comment]
Spoiler: analblocks branch required

**Comment by ITAYC0HEN** [comment]
@thestr4ng3r @radare now that the work you guys did with Analysis Blocks merged, this issue can be solved?
