### ISSUE TITLE
Can't debug files that were opened in write-mode

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#15650]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | recent from git

### Expected behavior

There shouldn't be a problem to debug file that is opened in write mode. Even if the file was opened in write mode and modified, running `ood` should success in debugging the file

### Actual behavior

Debugging files that are currently opened in write mode is not possible. Probably r2 kept the fd open and blocks the execution.

```
$ r2 -w /tmp/readln 
Module version mismatch /home/beet/.local/share/radare2/plugins/core_pdd.so (3.7.0) vs (4.1.0-git)
 -- Quantum dissasemble: it's there as long as you don't observe it
[0x000010d0]> doo
Could not execvp: Text file busy
Could not execvp: Text file busy
ptrace (PT_ATTACH): No such process
r_core_file_reopen: Cannot reopen file: dbg:///tmp/readln  with perms 0x7, attempting to open read-only.
[0x00000000]> 

```

### Steps to reproduce the behavior 
- Open file in write mode `r2 -w <file>`
- Try to re-open in deubg mode using `ood`
- Fail

**Comment by yossizap** [comment]
Reproduced in windows as well:

```
fork_and_ptraceme/CreateProcess: The process cannot access the file because it is being used by another process.

fork_and_ptraceme/CreateProcess: The process cannot access the file because it is being used by another process.

r_core_file_reopen: Cannot reopen file: dbg://C:\\workspace\\cutter\\radare2\\dest\\bin\\ConsoleApplication1.exe  with perms 0x7, attempting to open read-only.
```
