### ISSUE TITLE
Win32 function parameters autocomment error

### ISSUE THREAD

**Issue by skif2008** [radareorg/radare2#15680]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0 0 @ linux-x86-64 git.4.0.0
commit: unknown build: 2019-10-31__10:47:02

### Expected behavior
push 0x104                  ; 260 ; DWORD nSize
lea eax, [lpPathName]
push eax                    ; LPSTR lpFilename
mov ecx, dword [nSize]
push ecx                    ; HMODULE hModule
call dword [sym.imp.KERNEL32.dll_GetModuleFileNameA] ; 0x401090 ; DWORD GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize)

### Actual behavior
push 0x104                  ; 260 ; HMODULE hModule
lea eax, [lpPathName]
push eax                    ; LPSTR lpFilename
mov ecx, dword [nSize]
push ecx                    ; DWORD nSize
call dword [sym.imp.KERNEL32.dll_GetModuleFileNameA] ; 0x401090 ; DWORD GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize)

### Steps to reproduce the behavior 
Win32 app

**Comment by GustavoLCR** [comment]
This was fixed already, update radare2

**Comment by XVilka** [comment]
Open a new issue if it wasn't fixed.
