### ISSUE TITLE
4.1.0 Debian package build errors

### ISSUE THREAD

**Issue by gordboy** [radareorg/radare2#15686]
This is not a bug report about the operation of the program or libraries, it is a bug report about producing Debian packages.

The commit 

https://github.com/radareorg/radare2/commit/74fb0efbe3c590020514aaa79c9932c5671ea022#diff-bed8dbe5e661af85729745e34ade5671

which changes 

sys/debian/deb_hand.mak

is erroneous on my system, and in my view needs to be reverted.

The stripping of libs and executables already takes place elsewhere (actually in sys/debian.sh) and the commit is both unwanted and irksome.

`./configure --prefix=/usr`
`make -j4`
`./sys/debian.sh`

produces an error message and breaks, due to the erroneous and untested

`find .. | xargs strip`

introduced in the commit.

**Comment by radare** [comment]
Reverted.  thanks
