### ISSUE TITLE
Several instructions not being displayed in sym.__libc_csu_init

### ISSUE THREAD

**Issue by amlamarra** [radareorg/radare2#15682]
I'm working on a ROP Emporium challenge (https://ropemporium.com/challenge/ret2csu.html) and when I disassembled the __libc_csu_init function, it skips a few instructions that can be seen with GDB or objdump.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0 0 @ linux-x86-64 git.4.0.0 commit: unknown build: 2019-10-31__10:47:02

### Expected behavior
Radare2 shows the full disassembly of a function with the "pdf" command. 

### Actual behavior
Radare2 skips a few instructions, as can be seen by the two dots in the margin (see screenshot below).

### Steps to reproduce the behavior 
- Download the binary from here: https://ropemporium.com/binary/ret2csu.zip
- Disassemble the __libc_csu_init function as shown:
![image](https://user-images.githubusercontent.com/14570369/71200556-405bfb80-2266-11ea-9c0a-0767c105ae29.png)
- Same thing with "pdr":
![image](https://user-images.githubusercontent.com/14570369/71200975-1951f980-2267-11ea-8864-c240497137ec.png)
- Disassembling the same function in GDB:
![image](https://user-images.githubusercontent.com/14570369/71200827-c415e800-2266-11ea-8ddf-ad7493ee57c3.png)

**Comment by GustavoLCR** [comment]
Works for me with radare2 4.1.0

**Comment by amlamarra** [comment]
Really? I just installed the 4.1.1 prerelease and I'm having the same issue.
![image](https://user-images.githubusercontent.com/14570369/71255792-efe3ad00-22fc-11ea-9e06-b986cbb05679.png)


I also tried setting all of the jmp table analysis settings to true in my .radare2rc file:
```
[0x004005f0]> e anal.jmp.
anal.jmp.above = true
anal.jmp.after = true
anal.jmp.cref = true
anal.jmp.indir = true
anal.jmp.mid = true
anal.jmp.ref = true
anal.jmp.tailcall = 0
anal.jmp.tbl = true
```

**Comment by GustavoLCR** [comment]
Oops, sorry, opened the wrong bin

**Comment by amlamarra** [comment]
I just uninstalled, made that fix, reinstalled, and tested it again. Now it seems to work :)

**Comment by radare** [comment]
Thats how pdf works. Its a linear disasm that skips instructions not covered by the function. Use pd, pdr or report the analysis bug
