### ISSUE TITLE
radare-4.1.0 fails to build from tarball without network access: fatal: unable to access 'https://github.com/tree-sitter/tree-sitter.git/': Couldn't resolve host 'github.com'

### ISSUE THREAD

**Issue by trofi** [radareorg/radare2#15685]
Attempted to package `radare-4.1.0` in Gentoo today. Build fails in a sandbox cut out from network as:
```
"/bin/sh" clone_3rd_repo.sh tree-sitter "https://github.com/tree-sitter/tree-sitter.git" "master" "9f77afcd1ff050855259f83fcf50056ad842a790"
[tree-sitter] Cloning tree-sitter from git...
fatal: unable to access 'https://github.com/tree-sitter/tree-sitter.git/': Couldn't resolve host 'github.com'
[tree-sitter] Cannot clone tree-sitter from git
make[1]: *** [Makefile:342: tree-sitter-sync] Error 1
make[1]: Leaving directory '/tmp/portage-tmpdir/portage/dev-util/radare2-4.1.0/work/radare2-4.1.0/shlr'
make: *** [Makefile:59: all] Error 2
```

One of the solutions would be to provide that tree already present in a release tarball.

**Comment by radare** [comment]
yeah, 4.1 release requires network access, we should make the build of treesitter optional via a configure flag imho, its an experimental feature and we probably dont want everyone to try it yet

**Comment by ret2libc** [comment]
> yeah, 4.1 release requires network access, we should make the build of treesitter optional via a configure flag imho, its an experimental feature and we probably dont want everyone to try it yet

I'm ok to make this a build-time config option for now, as a short term solution, since the feature it's still very experimental. However, in the future we should probably switch to submodules/gittrees or whatever.
