### ISSUE TITLE
Infinite loop in panels

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15703]
How to reproduce:

press the following keys:

```
v<enter> # enter into panels mode
tt             # create a new tab
q             # try to quit, (causes 100% cpu usage)
```

to workaround this DoS this patch worked, but its obv useless and wrong

<img width="860" alt="Screenshot 2019-12-24 at 19 57 29" src="https://user-images.githubusercontent.com/917142/71423189-cffb1300-2687-11ea-91d5-4444d39ca58b.png">

**Comment by Vane11ope** [comment]
cool ok im on it

**Comment by Vane11ope** [comment]
#15729
