### ISSUE TITLE
Windows: The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by xobs** [radareorg/radare2#15700]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 x64
| r2 -v full output, **not truncated** (mandatory)     | Program 'radare2.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
||+ radare2 -v
||+ ~~~~~~~~~~.
||At line:1 char:1
||+ radare2 -v
||+ ~~~~~~~~~~
||   + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
||   + FullyQualifiedErrorId : NativeCommandFailed

### Expected behavior

radare2 should run

### Actual behavior

Radare2 gives the following output:

```powershell
> radare2 -v
Program 'radare2.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ radare2 -v
+ ~~~~~~~~~~.
At line:1 char:1
+ radare2 -v
+ ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
>
```

### Steps to reproduce the behavior 
- Download radare2 from the file linked on https://www.radare.org/r/ -- http://radare.mikelloc.com/get/4.0.0/radare2-msvc_64-4.0.0.zip
- Extract it somewhere
- Run `radare2.exe`

**Comment by radare** [comment]
Try the vs2017 https://radare.mikelloc.com/get/4.0.0/radare2-vs2017_64-4.0.0.zip

**Comment by xobs** [comment]
That works much better.  So the link on the front page should be changed from http://radare.mikelloc.com/get/4.0.0/radare2-msvc_64-4.0.0.zip to https://radare.mikelloc.com/get/4.0.0/radare2-vs2017_64-4.0.0.zip

**Comment by XVilka** [comment]
I think you just miss the VS2019 runtime, which you need to install.

**Comment by xobs** [comment]
I did a search on DuckDuckGo for "radare2", and went to the first link.  This brought me to this page:

![image](https://user-images.githubusercontent.com/238325/71404911-cb763080-266e-11ea-88e0-00c96c956ba4.png)

If I click the big `Download 4.0.0 for Windows` link, it goes directly to http://radare.mikelloc.com/get/4.0.0/radare2-msvc_64-4.0.0.zip.  There is no option to download VS2019 Runtime.

**Comment by pelijah** [comment]
Btw there are no sdb and header files in the archive.

**Comment by radare** [comment]
This website is the old one. So sad that ddg is still indexing it

**Comment by radare** [comment]
Which archive?

**Comment by pelijah** [comment]
> 
> Which archive?

I mean this one https://www.radare.org/r/ -- http://radare.mikelloc.com/get/4.0.0/radare2-msvc_64-4.0.0.zip

**Comment by radare** [comment]
Its a binary build its not suposed to contain developer files. But we can add them

**Comment by pelijah** [comment]
Without type and cc `*.sdb` files it is almost useless.

**Comment by xobs** [comment]
If the old website is deprecated and no longer maintained, and the "new beta" website is the canonical one, then maybe the old website should be turned into a 302 redirect.

**Comment by radare** [comment]
i keep all the old websites in there, the 302 is in /

**Comment by rohan2734** [comment]
same error still exists.
