### ISSUE TITLE
Radare not scanning all strings um izz

### ISSUE THREAD

**Issue by racerxdl** [radareorg/radare2#15719]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | Sega Genesis ROM
| Architecture/bits of the file (mandatory)            | m68k 16 BE
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.1.0-git 23287 @ linux-x86-64 git.4.0.0-138-g521ac7c28 commit: 521ac7c28f42a24586bc0b02f10feb75900a066c build: 2019-12-05__18:01:09

### Expected behavior
When running `izz` command, I expect the string table to have all strings.
```
[Strings]
nth paddr      vaddr      len size section type    string
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
8   0x00007ae9 0x00007ae9 13  14   text    ascii   SEM PORTADORA
9   0x00007af7  0x00007af7  27  28   text    ascii   INICIANDO TESTE AGUARDE !!!
10  0x00007b13 0x00007b13 13  14   text    ascii   LINHA OCUPADA
```

### Actual behavior
```
[Strings]
nth paddr      vaddr      len size section type    string
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
8   0x00007ae9 0x00007ae9 13  14   text    ascii   SEM PORTADORA
10  0x00007b13 0x00007b13 13  14   text    ascii   LINHA OCUPADA
```

Where the string table (I manually set the addresses as string):
```
0x00007ae9         .string "SEM PORTADORA" ; len=14
0x00007af7          .string "INICIANDO TESTE AGUARDE !!!" ; len=28
0x00007b13         .string "LINHA OCUPADA" ; len=14
```

### Steps to reproduce the behavior 
The ROM is already Public Domain in Brazil (its a Brazilian ROM) but I'm not sure about US Regulations. It is called "Meganet" from TecToy

### Additional Logs, screenshots, source-code,  configuration dump, ...

As a quick check, I noticed all strings that has some type of ponctuation ( e.g. `? , . !`) does not show in `izz` but show in `izzz`

```
008 0x00007ae9 0x00007ae9  13  14 (text) ascii SEM PORTADORA
010 0x00007b13 0x00007b13  13  14 (text) ascii LINHA OCUPADA
```

They're all null terminated strings:
![image](https://user-images.githubusercontent.com/578310/71548384-05577780-298c-11ea-86e2-b5c2c3b3a184.png)

The ROM
[meganet.zip](https://github.com/radareorg/radare2/files/4007349/meganet.zip)

Arch:  `m68k-16-BE`

**Comment by radare** [comment]
iz != izz

**Comment by Maijin** [comment]
The problem isn't in `iz` or `izz` difference.

**Comment by kazarmy** [comment]
This is because the default string filter for smd binaries is really darn aggressive.

I have an improved filter in the works (non-AI-based sadly), but for now, a workaround is to do:

```
e bin.str.filter=
```
