### ISSUE TITLE
Win32 not scrolling to track eip in visual mode

### ISSUE THREAD

**Issue by jorgeventura** [radareorg/radare2#15717]
I have the last version 4.2.0 (clone at 12/28/2019) compiled using VS 2019 for Win32.

When using radare2 on visual mode, working in single step (F7) if the eip address is out of the range of current panel, there is no scroll adjust for the new address what means the debug still OK but the disassembly screen doesn't present the current instruction on screen.
The problem is the same if using the regular cmd.exe or powershell. I don't know if it's a bug or something that has to be configured in radare2.

**Comment by radare** [comment]
thats expected. use 'e dbg.follow=1' to follow every single change of eip in the scrolled pane when stepping

**Comment by GustavoLCR** [comment]
> thats expected. use 'e dbg.follow=1' to follow every single change of eip in the scrolled pane when stepping

no, thats a bug with panels. following works with `s`, but doesn't with `F7`

**Comment by jorgeventura** [comment]
Thank you!

**Comment by radare** [comment]
Then the title of the issue is completely meaningless
