### ISSUE TITLE
Windows PDB server not available anymore. Any other option?

### ISSUE THREAD

**Issue by jorgeventura** [radareorg/radare2#15734]
I am trying to debug Win32 program but the PDB server from Microsoft is not available anymore.
What other option do I have to get Windows symbols. The first PDB that radare2 is complaining is ntdll.pdb.

Be dependent on MS was always a headache.

**Comment by GustavoLCR** [comment]
What do you mean with Microsoft's pdb server not being available? They are working just fine for me.

Also, you can change the default server with `e pdb.server`

**Comment by jorgeventura** [comment]
Hi Gustavo.
I have radare2 4.2.0 pointing to https://msdl.microsoft.com/download/symbols
but it's not loading any PDB file.

Here is my configuration:
pdb.autoload = 1 ; Automatically load the required pdb files for loaded
DLLs
pdb.extract = 1 ; Avoid extract of the pdb file, just download

pdb.server = https://msdl.microsoft.com/download/symbols ; Base URL for
Microsoft symbol server
pdb.symstore = O:\radare2\share\pdb ; Path to downstream symbol store

pdb.useragent = Microsoft-Symbol-Server/6.11.0001.402 ; User agent for
Microsoft symbol server

In the very first load of ntdll.dll the system complains that there is no
ntdll.pdb and the pdb.sysmstore is empty.

I was reading that it's not available:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-symbols#symbol-package-deprecation

**Comment by jorgeventura** [comment]
I was reading that cabextract and get or curl must be installed on Windows,
what means radare2 relay on those tools to get pdb files download and
extract.

**Comment by XVilka** [comment]
Afaik it's supposed to print the warning if they are not installed.
