### ISSUE TITLE
pmj ##json

### ISSUE THREAD

**Issue by brainstorm** [radareorg/radare2#15764]
The JSON command for `pm` does not seem to be implemented?:

```
[0x00426870]> pm
0x00426870 1 Microsoft Cabinet archive data, 20011963 bytes, 7 files
[0x00426870]> pmj
failed r_magic_load ("j") no magic files loaded! could not find any magic files!
```

I would have expected an output such as:

```json
{"filetype": "Microsoft Cabinet archive data", "size": 20011963, "files": 7}
```

**Comment by Maijin** [comment]
pmj should first contain the offset, 1 and the message. Parsing the full output will require much more work.

**Comment by radare** [comment]
Should be very easy to fix. Assigned to 4.2. Pls send fix asap

**Comment by deepakchethan** [comment]
Working on this right now

**Comment by radare** [comment]
Thanks!!

**Comment by radare** [comment]
fixed
