### ISSUE TITLE
reads to malloc:// buffer does not increment position

### ISSUE THREAD

**Issue by pr0cf5** [radareorg/radare2#15789]
Hello, I set the issue type to blank because I wasn't sure if what i'm experiencing is a feature or a bug.

Buffers allocated by malloc:// have a different reading mechanism from other kinds of buffers. Other buffers increment the current position by the read length but malloc://'ed buffers do not. This can be easily noticed in the [source code](https://github.com/radareorg/radare2/blob/0ac5ba9c75843f469a2b18bd6f3b31bb128c285c/libr/io/p/io_malloc.c#L107).

Also, for writes the position is incremented but reads leave the current position unchanged. 

Is this intended or is it a bug? I found this behavior while writing a bin plugin and noticed that code loaded in malloc:// is not parsed correctly.

**Comment by radare** [comment]
We may have a consistent behaviour. So i would consider this as a bug

**Comment by pr0cf5** [comment]
will there be a fix for it? I think it can be easily patched by applying the same logic used in `__write` function.

**Comment by radare** [comment]
Please send a pr
