### ISSUE TITLE
[regression] mov dword [XXX], XXX undefined type

### ISSUE THREAD

**Issue by SylvainCecchetto** [radareorg/radare2#15799]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS x86-32
| File format of the file you reverse (mandatory)      | NO FILE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.2.0-git 23544 @ darwin-x86-64 git.4.1.1-108-g2a2068996 commit: 2a206899693604283d650b0bb6d59b100a726de4 build: 2020-01-13__12:28:48

### Expected behavior
The type of `mov dword [rbp - 0xc], 0` should not be `undefined` but `mov`

This is what I get with Radare2 3.8.0:

```
[0x00000000]> a8 c745f400000000
address: 0x0
opcode: mov dword [rbp - 0xc], 0
disasm: mov dword [rbp - 0xc], 0
pseudo: dword [rbp - 0xc] = 0
mnemonic: mov
mask: ffffffffffffff
prefix: 0
id: 449
bytes: c745f400000000
val: 0x00000000
refptr: 4
size: 7
sign: false
type: mov  <-------------
cycles: 1
esil: 0,0xc,rbp,-,=[4]
direction: write
family: cpu
stackop: set
stackptr: 8
```

### Actual behavior
Type of instruction `mov dword [rbp - 0xc], 0` is `undefined`, that was not the case before.

This is what I get now:

```
[0x00000000]> a8 c745f400000000
address: 0x0
opcode: mov dword [rbp - 0xc], 0
disasm: mov dword [rbp - 0xc], 0
pseudo: dword [rbp - 0xc] = 0
mnemonic: mov
description: moves data from src to dst
mask: ffffffffffffff
prefix: 0
id: 449
bytes: c745f400000000
val: 0x00000000
disp: 0xfffffffffffffff4
refptr: 4
size: 7
sign: false
type: undefined  <-------------
cycles: 1
esil: 0,0xc,rbp,-,=[4]
direction: write
family: cpu
stackop: set
stackptr: 8
```

### Steps to reproduce the behavior 

* Open r2 with `r2 --`
* Then disassemble `c745f400000000` opcode with `a8 c745f400000000`
* Notice the line `type: undefined` instead of `type: mov`

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
FIxed in https://github.com/radareorg/radare2/pull/15805
