### ISSUE TITLE
Run V suite without radare2 installation

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15797]
Currently it expects the radare2 to be installed, so just simple `make src/r2r` fails with the following error. It would be nice to be able to just ran these tests without prior installation, exactly like current NodeJS one:
```
warning: r2r.v:34:17: reference field `R2R.r2` must be initialized
Package r_core was not found in the pkg-config search path.
Perhaps you should add the directory containing `r_core.pc'
to the PKG_CONFIG_PATH environment variable
No package 'r_core' found
/home/runner/.cache/v/r2r.tmp.c:251:10: fatal error: r_core.h: No such file or directory
 #include <r_core.h>
          ^~~~~~~~~~
compilation terminated.
V error: C error. This should never happen. 
```

See https://github.com/radareorg/radare2/pull/15796

**Comment by radare** [comment]
thats a matter of setting up the PKG_CONFIG_PATH, LDFLAGS, etc. to use the src paths. a bit anoying and actually the unit tests should be building in the same way, but its hardcoding intertnal src paths

**Comment by XVilka** [comment]
Now it works, but can't find `pkgconfig` on the OS X worker. Any ideas?
