### ISSUE TITLE
ARM disassembly incorrect

### ISSUE THREAD

**Issue by williamleecn** [radareorg/radare2#15808]
```
$ rasm2 -a arm -D "03C68FE2"
0x00000000   4                 03c68fe2  add ip, pc, 0x300000
```
correct should be
```
00002DDC   03c68fe2   adr     r12, 0x302de4
```

**Comment by radare** [comment]
If thats an issue for you u may open the issue in gnu, llvm and capstone (report the same output as r2). Are you comparing it with an invented instruction from IDA.

Also u r missing the -b32 flag

Btw ip = r12

And adr is relative add. R2 replaces those relative references with absolute ones . But thats a layer on top of the disassembling api which is the kne used in rasm2

**Comment by williamleecn** [comment]
```
00002DDC   03c68fe2   adr     r12, 0x302de4

should  equal to =>  add  r12, pc, 0x30008


```

**Comment by williamleecn** [comment]
the program is correct, my calculation is wrong, it should be added 8 to the pc
