### ISSUE TITLE
Minimal slice for reproducible af test on anal-block branch

### ISSUE THREAD

**Issue by brainstorm** [radareorg/radare2#15842]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX Catalina 10.15.2
| File format of the file you reverse (mandatory)      | VxWorks blob
| Architecture/bits of the file (mandatory)            | SuperH4 32bits
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.2.0-git 23744 @ darwin-x86-64 git.4.1.1-122-g0350db90d commit: 0350db90d3d7aa32fff4f7b10b0668e1f3df2da1 build: 2020-01-18__22:12:21

### Actual behavior

When running vxHunter+r2 as described in this issue comment:

https://github.com/PAGalaxyLab/vxhunter/issues/9#issuecomment-570551314

I'm getting a bunch of warnings, as described on the issue above... the issue was closed because the initial bug/issue was solved (`of*` not working properly on OSX Catalina). This issue relates to this:

```
(...)
###### Start analyzing functions######
af: Cannot find function at 0x0c40e662
af: Cannot find function at 0x0c40d906
af: Cannot find function at 0x0c4016a0
af: Cannot find function at 0x0c40a320
af: Cannot find function at 0x0c40a2a0
af: Cannot find function at 0x0c40a084
(...)
```

The `VxWorks.bin` binary is available under r2bins telegram but it also can be fetched publicly with some extraction steps.

I also tried to slice that `12MB` binary into smaller bits around the offsets shown above in increasing surrounding offsets (i.e `0x0c40e662±600 bytes`, using r2's `wtf` command), to craft a reproducer, but `af` does not complain anymore with those smaller chunks. Help! ;)

### Expected behavior

I would expect that the `anal-block` PR solves those warnings since it's a good refactor that is due to be released in ~3 days. It would be great to find out the root cause of those `af: Cannot find function at` and fix it for good :)

### Steps to reproduce the behavior 
1. Get `VxWorks` from `#r2-bins` TG channel.
2. `git clone https://github.com/PAGalaxyLab/vxhunter`
3. `r2 -a sh -b 32 ~/dev/anritsu/firmware/fresh/OS/VxWorks.bin`
4. `#!pipe python3 vxhunter/firmware_tools/vxhunter_r2_py3.py`

/cc @radare, @trufae, @thestr4ng3r, @dark-lbp

**Comment by thestr4ng3r** [comment]
Small reproducer:
```
r2 -a sh -c "wx 01e005400a25862f962fa62fb62fc62f; af@0; af fuck@0x6" -
```

**Comment by radare** [comment]
is this fixed?

**Comment by radare** [comment]
can we have this test commited instead of gh?

**Comment by radare** [comment]
ping

**Comment by brainstorm** [comment]
Pong, looking at how the "new" r2 regressions testsuite work right now ;)

**Comment by trufae** [comment]
The V and Nodejs suites use the same db/ directory so its compatible

**Comment by brainstorm** [comment]
@thestr4ng3r I'm not entirely sure that this small snippet reproduces the original issue:

```
(lldb) b cmd_anal.c:3884
(lldb) process launch
Process 58325 launched: '/usr/local/bin/r2' (x86_64)
Process 58325 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x0000000100da7485 libr_core.dylib`cmd_anal_fcn(core=0x0000000103000000, input="f") at cmd_anal.c:3884:7
   3881					}
   3882				}
   3883			}
-> 3884			if (name) {
   3885				if (*name && !__setFunctionName (core, addr, name, true)) {
   3886					eprintf ("af: Cannot find function at 0x%08" PFMT64x "\n", addr);
   3887				}
Target 0: (r2) stopped.
(lldb) print name
(char *) $0 = 0x0000000000000000
```

**Comment by radare** [comment]
this is not a crash, whats the actual issue?

**Comment by brainstorm** [comment]
The actual issue is a long list of warnings for functions that exist (see above in "Actual behavior"). There should not be warnings for those, they are SuperH4 optimizations (we guess), but they are valid, no warnings should be shown, see this function body:

https://github.com/PAGalaxyLab/vxhunter/issues/9#issuecomment-570555168
