### ISSUE TITLE
Base64 disable option for IZJ command 

### ISSUE THREAD

**Issue by alienzoX** [radareorg/radare2#15840]
Hi hope you guys doing well,

As documented it seems **izj** command return strings in base64 encoded format, How can I disable this feature? I want the string in whatever format it is. 
The reason is I pipe the result into the other scripts and it makes the processing slower since other scripts should decode every single of these strings.

Thanks

**Comment by radare** [comment]
you are using an old version of r2 if you are having this behaviour

**Comment by alienzoX** [comment]
Got it. Thank you so much for your fast reply. Will update it.
Cheers !!
