### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by AntyMew** [radareorg/radare2#15856]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian bullseye - Linux 5.4.0-2-amd64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | segfault (current master, commit hash f715f01f)

### Expected behavior
No crash

### Actual behavior
Passing any option or argument to r2 (as far as I've tested) results in a segfault. This is a regression from 4.1.1, which is working on my machine.

### Additional Logs, screenshots, source-code,  configuration dump, ...
Backtrace:
```
#0  __GI___libc_free (mem=0x100000000) at malloc.c:3111
#1  0x00007ffff6ce489e in cb_strpurge (user=0x7ffff7e05060 <r>, 
    data=0x55555559a290) at cconfig.c:976
#2  0x00007ffff7ac7823 in r_config_set_cb (cfg=0x555555611110, 
    name=0x7ffff6defb1e "bin.str.purge", value=0x7ffff6deb458 "", 
    cb=0x7ffff6ce4841 <cb_strpurge>) at config.c:360
#3  0x00007ffff6cebd59 in r_core_config_init (core=0x7ffff7e05060 <r>)
    at cconfig.c:3145
#4  0x00007ffff6c2b34f in r_core_init (core=0x7ffff7e05060 <r>) at core.c:2714
#5  0x00007ffff7df30c2 in r_main_radare2 (argc=2, argv=0x7fffffffe158)
    at radare2.c:401
#6  0x0000555555555422 in main (argc=2, argv=0x7fffffffe158) at radare2.c:96
```

**Comment by radare** [comment]
You probably have mixed versions of libs or old plugins around. R2 works and starts perfectly fine

**Comment by AntyMew** [comment]
Resolved. I think apt was holding onto an old lib which I hadn't auto-removed yet
