### ISSUE TITLE
Concatenated grep does not show first hit in output

### ISSUE THREAD

**Issue by JavierYuste** [radareorg/radare2#15870]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.2.0 23782 @ linux-x86-64 git.4.2.0
commit: 57a60ba8c5e782ca0807e3c7b1d26a8b3923073d build: 2020-01-21__12:53:33

### Expected behavior

Double grep should behave as expected, applying grep over the results of the first grep. For example:

```
[0x00403920]> pd 10
│           0x00403920     0-     81ec7c010000   sub esp, 0x17c 
│           0x00403926   380+     a1e4c04000     mov eax, dword [0x40c0e4] 
│           0x0040392b   380      33c4           xor eax, esp         
│           0x0040392d   380      898424780100.  mov dword [var_4h], eax 
│           0x00403934   380      53             push ebx             
│           0x00403935   384+     55             push ebp              
│           0x00403936   388+     56             push esi              
│           0x00403937   392+     57             push edi              
│           0x00403938   396>     e884480000     call fcn.004081c1    
│           0x0040393d   396      6801800000     push 0x8001           
[0x00403920]> pd 10 ~ 380
│           0x00403926   380+     a1e4c04000     mov eax, dword [0x40c0e4] 
│           0x0040392b   380      33c4           xor eax, esp          
│           0x0040392d   380      898424780100.  mov dword [var_4h], eax 
│           0x00403934   380      53             push ebx              
[0x00403920]> pd 10 ~ 380 ~ eax
**|           0x00403926   380+     a1e4c04000     mov eax, dword [0x40c0e4]** 
│           0x0040392b   380      33c4           xor eax, esp          
│           0x0040392d   380      898424780100.  mov dword [var_4h], eax 
```

### Actual behavior

Grep after grep does not show the first line. The bold text in the previous example does not show up. Real output is:

```
[0x00403920]> pd 10 ~ 380 ~ eax
│           0x0040392b   380      33c4           xor eax, esp          
│           0x0040392d   380      898424780100.  mov dword [var_4h], eax 
```

Note that the first line is missing, the one between asterisks in the previous code example.

### Steps to reproduce the behavior 

Grep disassembled lines twice. When only one line should be shown at the end, it behaves correctly. When more than one line should be shown, first line is not included.

### Additional Logs, screenshots, source-code,  configuration dump, ...

Password: infected

[a02ede958b9574429239f58b3cebd3531032bfebd0a9d3e4417c3f0bbe68d9fd.zip](https://github.com/radareorg/radare2/files/4090947/a02ede958b9574429239f58b3cebd3531032bfebd0a9d3e4417c3f0bbe68d9fd.zip)

**Comment by radare** [comment]
Use ~&foo,bar

What you report is a regression

**Comment by JavierYuste** [comment]
Thanks a lot, that works fine!

**Comment by JavierYuste** [comment]
Actually, that was in help, under `~?`. My bad, I did not see it
