### ISSUE TITLE
Clarify Semantics of Bits/Arch Anal Hints

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/radare2#15877]
The situation currently is as follows:
* Most anal hints (immbase, jump/fail, ...) only apply for a single address, not a range.
* bits is assigned to a single address too without a size, but an rbtree is build to top of it and when querying for the bits at an address x, the hint with the highest addr less or equals to x is used. This essentially means all bits hints reach until the end of the address space or until the next hint.
* arch has the following syntax: `aha ppc 51        // set arch for a range of N bytes`, but the range size arg is completely ignored and the hint will only apply for a single address, so it's basically useless.

For these ranged hints, we have a few different options:
1. Make all have a size that must explicitly be specified and store in an augmented rbtree - This would not work with a lot of the analysis that sets the bits value since the size of the code that uses the bits value is generally not known.
2. Same data structure as above but add helper functions that create ranged hints at an address and automatically calculate the size to extend until the maximum addr. This would fix the analysis.
3. Make both arch and bits work like bits currently do (implicitly extend) and use one non-augmented tree for each of them for querying.

I started to do something like 1/2 here: https://github.com/radareorg/radare2/pull/15876

It would be good to get some feedback on what behavior is expected/most useful @radare @ret2libc @XVilka

**Comment by thestr4ng3r** [comment]
Thinking about it a bit, I think solution 3 might be the best. It would still be possible to have a bits range with a specified length if you set two hints (at start and at end). The end one can have bits of 0 to indicate that the global asm.bits should be used.

**Comment by ret2libc** [comment]
What are the advantages of having a full augmented rbtree? I'm not sure I see any particular one in this case, since (I think) ranges cannot overlap. Having a simple tree and querying for the highest addr less or equals to x, as it currently does, is probably the easiest solution for what we need.

I'd vote for 3 as well.

**Comment by thestr4ng3r** [comment]
Exactly, an augmented tree would only be necessary if both bits and arch should be in the same tree, in which case a bits range can overlap an arch range. If they are split, it's not necessary.

**Comment by thestr4ng3r** [comment]
Good, unless there are any further objections, we can settle for 3.

Another question: For the rest of the hints that do not need ranges, should we use a hashtable or tree? Hashtable may be faster for many entries, but we can't query for all hints in a given interval and the hints will be unordered.
I personally would go for a ht, but maybe someone knows an application for ordering or interval query.

**Comment by ret2libc** [comment]
I'm not sure what is the most common operation there, but if the sorting is needed only for printing, then I would go for a ht and just do a sort before printing stuff. WDYT?

**Comment by thestr4ng3r** [comment]
Yep, me too. The one most important operation is querying all hints at an address before disassembling, so this should be optimized for.

**Comment by XVilka** [comment]
While 3 is not the cleanest solution, it might be the easier to implement and maintain. For setting the range-level arch/bitness we just can create a higher-level command to do so, while the hints themselves just store the address-level hints.

For the querying - it's probably to make sense to build a bitmap to store these ranges, you might use the probabilistic data structure to such a map, so in average it will be faster to deal with.

**Comment by thestr4ng3r** [comment]
How exactly does a bitmap help me to store bits/arch ranges?

**Comment by XVilka** [comment]
Assuming there are not much architecture changes, but mostly bitness - it can provide the easy way to select 16bit among 32 bit binaries and so on.

**Comment by ret2libc** [comment]
I do not think a bitmap is right. A bitmap is essentially a hashtable, so you can only answer queries like "is there something at X?" and for our case that would work only if you put a value for each possible value in the address space. A tree is much better in this case IMO as you can answer questions like "what is the closest thing that you have stored near address X?" and with this you can just store where a change in bitness/architecture is happening and not the value for each address.

**Comment by thestr4ng3r** [comment]
That's what I thought too. The bitmap can be a way to optimize if we later detect that bitness selection is a bottleneck, but a tree is what we should use as the base.
