### ISSUE TITLE
radare2-shell-parser: command substitution

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#15886]
A feature that still makes me think a lot is how we want to handle command substitution. I would like to have some feedback and thoughts about it, so that I can implement it in radare2-shell-parser, as the way we implement it will change a lot how the parser works.

1) Commands substitutions can appear anywhere, they are just string-replaced.
Example: `p$(?e "d 10~xor")` becomes => `pd 10~xor`
2) Commands substitutions can only be in arguments and they can generate new arguments
Example: `o $(?e "myfile 0x4000 rwx")` is interpreted as `o myfile 0x4000 rwx`.
3) Commands substitutions can only be in arguments and they can't generate new arguments
Example: `o $(?e "myfile 0x4000 rwx")` is interpreted as `o "myfile 0x4000 rwx"` (which would not work because `o` expects 3 arguments.
4) Commands substitutions can only be in arguments and they can generate new tokens or new commands as well.
Example: `f $(?e "ciao @ 0xdeadbeef; f-") ciao` is interpreted as `f ciao @ 0xdeadbeef; f- ciao`

Other ideas? Suggestions? What do you think is the clearest/best thing? Bash seems to use a sort of 1/2.

**Comment by ret2libc** [comment]
I'm going to try 2.

The reason I don't like 3 is because I think it makes sense for a cmd_substitution to generate more than one argument token.
The reason I don't like 4 is because if you allow the cmd_substitution to generate any kind of new token, you can hardly parse the input because until you execute each substitution you don't know the structure of the final input.

**Comment by XVilka** [comment]
I think restricting them to just arguments->arguments substitution is good enough. I don't remember any case when I needed something more advanced.

**Comment by radare** [comment]
Are you suggesting to add/replace current backticks with $() ?

Also those examples are using quotes to separate arguments instead of the whole command like its in the current parser. it is indended?

i think all your suggestions look good to me, but my question here is... do we want to substitute the internal grep after substituting the command? i mean:

```
> pd~20
```
will be the same as:
```
> `?e "pd~20"`
```

and

```
> $(?e pd) $(?e "~20")
```

**Comment by ret2libc** [comment]
> Are you suggesting to add/replace current backticks with $() ?

Current implementation already supports both `$()` and backticks, so I'm supporting both of them as well. The only difference is that `$()` can be nested, backticks cannot. 

> Also those examples are using quotes to separate arguments instead of the whole command like its in the current parser. it is indended?

Yes, it is intended. I think everybody finds it very confusing having to wrap the entire command in `"` when, instead, you would only want to wrap specific arguments. In bash, for example, you do `echo "hello;world"` and not `"echo hello;world"`.

> 
> i think all your suggestions look good to me, but my question here is... do we want to substitute the internal grep after substituting the command? i mean:
> 
> ```
> > pd~20
> ```
> 
> will be the same as:
> 
> ```
> > `?e "pd~20"`
> ```
> 
> and
> 
> ```
> > $(?e pd) $(?e "~20")
> ```

No, I ended up with a different approach after some input on Telegram. Command substitutions cannot create new commands or "tokens" (it can't add a grep, for example).

If you want to interpret the entire output of a command as r2 commands, you should use `.`, not backticks. So your example:
```
 > `?e "pd~20"`
```
Instead should be:
```
> .?e pd~20
```
(we actually need to choose how to deal with the ambiguity here, as this may be interpreted in two ways: 1) execute `pd` and then grep the output of pd with `20` or 2) execute `pd~20`)

Anyway, I ended up allowing command substitutions only where an "argument" is expected.
So, `$(?e pd) $(?e "~20")` is not valid. However, it is valid something like `pd $(?e 10)` or something like `om $(?e 4 0xdeadbeef)` or `pd $(?e 10)~$(pad 90)`. Reasons being we don't want the syntax too complicated, but if you have proper uses cases that I'm not considering, please do share them.

**Comment by ret2libc** [comment]
Also, if you do:
```
> pd $(?e "~20")
```

this won't be interpreted as `pd~20`, but rather as `pd '~20'` (so the `~20` is considered as an argument to `pd` and not as a grep. This is similar to how bash works. In bash if you do `ls $(echo "-l"; echo ";"; echo "ls /root")` it is translated to `ls -l ';' ls /root`(which just consider all those things as arguments of the first `ls`).

**Comment by radare** [comment]
> On 12 Feb 2020, at 11:24, Riccardo Schirone <notifications@github.com> wrote:
> 
> Are you suggesting to add/replace current backticks with $() ?
> 
> Current implementation already supports both $() and backticks, so I'm supporting both of them as well. The only difference is that $() can be nested, backticks cannot.
> 
> 
ok, sgtm, yeah totally forgot i added $() support a while ago
> Also those examples are using quotes to separate arguments instead of the whole command like its in the current parser. it is indended?
> 
> Yes, it is intended. I think everybody finds it very confusing having to wrap the entire command in " when, instead, you would only want to wrap specific arguments. In bash, for example, you do echo "hello;world" and not "echo hello;world".
> 
yep, this means that we should change all commands to handle **argv instead of *args, i know this is an expected thing to happen soon or late, and we will need a plan for this, i would suggest adding an r_str_argv and r_str_list_join()
> i think all your suggestions look good to me, but my question here is... do we want to substitute the internal grep after substituting the command? i mean:
> 
> > pd~20
> will be the same as:
> 
> > `?e "pd~20"`
> and
> 
> > $(?e pd) $(?e "~20")
> No, I ended up with a different approach after some input on Telegram. Command substitutions cannot create new commands or "tokens" (it can't add a grep, for example).
> 
this makes sense because we can end up interpreting it like you show below
> If you want to interpret the entire output of a command as r2 commands, you should use ., not backticks. So your example:
> 
>  > `?e "pd~20"`
> Instead should be:
> 
> > .?e pd~20
> (we actually need to choose how to deal with the ambiguity here, as this may be interpreted in two ways: 1) execute pd and then grep the output of pd with 20 or 2) execute pd~20)
> 
> 
yeah
> Anyway, I ended up allowing command substitutions only where an "argument" is expected.
> So, $(?e pd) $(?e "~20") is not valid. However, it is valid something like pd $(?e 10) or something like om $(?e 4 0xdeadbeef) or pd $(?e 10)~$(pad 90). Reasons being we don't want the syntax too complicated, but if you have proper uses cases that I'm not considering, please do share them.
> 
> 

sounds good to me

**Comment by ret2libc** [comment]
> > Also those examples are using quotes to separate arguments instead of the whole command like its in the current parser. it is indended? Yes, it is intended. I think everybody finds it very confusing having to wrap the entire command in " when, instead, you would only want to wrap specific arguments. In bash, for example, you do echo "hello;world" and not "echo hello;world".
>
> yep, this means that we should change all commands to handle **argv instead of *args, i know this is an expected thing to happen soon or late, and we will need a plan for this, i would suggest adding an r_str_argv and r_str_list_join()

Yeah that's the plan long term. Short-term the idea is to have `LEGACY_COMMAND` and `NEW_COMMAND`. As long as a command is marked as "LEGACY" RCmd will pass a single string to it and the handler can deal with the input as it wants (what it is done now). Whenever we convert a command handler to the new way, we can remove the "LEGACY" flag and RCmd will split the arguments and just pass `*argv[]`.

**Comment by ret2libc** [comment]
Closing this as we agreed on what to do.
