### ISSUE TITLE
Removal of ` |<something>` syntax to execute r_io_system

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#15880]
If you do `pd 10 | grep xor`, you expect the output of `pd 10` to be sent through grep.
Now, if you do `| grep xor`, you expect it to be an invalid command. However, it turns out there is some special syntax which is not documented that would instead pass whatever is after `|` to `r_io_system` (actually, you can't do `|pid`, but you should do ` |pid`, otherwise it won't work).

I think this feature is useless as there is already `=!pid` which does the same. Moreover, it just makes the r2 syntax more complicated (and it's already complicated enough IMO).

I propose we just drop support for this feature.

**Comment by ret2libc** [comment]
@XVilka @thestr4ng3r @radare

**Comment by thestr4ng3r** [comment]
Agreed

**Comment by XVilka** [comment]
Afaik it was an extension proposed by the @radare
If it stands in the way of the new commands parser - it can be dropped,
imho. We can add other extensions, more consistent ones, once we migrate to
the new parser.

**Comment by radare** [comment]
```
[0x00000000]> |?
Usage: [cmd] | [program|H|T|.|]
| [cmd] |?           show this help
| [cmd] |            disable scr.html and scr.color
| [cmd] |H           enable scr.html, respect scr.color
| [cmd] |T           use scr.tts to speak out the stdout
| [cmd] | [program]  pipe output of command to program
| [cmd] |.           alias for .[cmd]
[0x00000000]>
```

the | is already a command, not just a modifier. i never liked the =! because most people confuse it with !=

**Comment by ret2libc** [comment]
It is not documented and it does not work well (you have to put a space in front of |). It's also very confusing because | is supposed to be piping and using it as an alternative for =! seems out of place. How many times do you use it? I guess others don't use it as it's not documented.

**Comment by radare** [comment]
the reason for havaing | as a comment alias was because people was doing things like .p? and cause mayehm (yes, the help msg starts with |)

**Comment by ret2libc** [comment]
WUT? Is `|hello` equal to `#hello`???

**Comment by radare** [comment]
not exactly. it will be "# hello"

because the char after '#' matters because of the hashbang and such :) the # char is special for comments and hashbangs

**Comment by ret2libc** [comment]
I think that sucks even more than what I thought :dagger: 

My proposal for the new parser:
1) No reason to have `|` as an alias for `#`. `|` is for piping (and other smaller stuff like `|H`, etc.), `#` is for comments and for `#!` (this is something I already implemented in the radare2-shell-parser and you don't really need a space after the `#` to distinguish between a comment and the command `#!`).
2) No reason to have ` |cmd`. There is already `!=cmd`. If we don't like `!=` we can use something else, but I think we should keep the meaning of `|` clear.

**Comment by radare** [comment]
> On 24 Jan 2020, at 11:30, Riccardo Schirone <notifications@github.com> wrote:
> 
> ﻿
> I think that sucks even more than what I thought 🗡
> 
> My proposal for the new parser:
> 
> No reason to have | as an alias for #. | is for piping (and other smaller stuff like |H, etc.), # is for comments and for #! (this is something I already implemented in the radare2-shell-parser and you don't really need a space after the # to distinguish between a comment and the command #!).
Agree on killing the | command we can just not do anything if the pipe have no input 
> No reason to have |cmd. There is already !=cmd. If we don't like != we can use something else, but I think we should keep the meaning of | clear.


I added ‘ as an alias for =! and as an alias for \ so we have 3 commands to do the same. Actually the != thing is just because =! Exists and everybody confuses them

**Comment by radare** [comment]
@ret2libc so?

**Comment by ret2libc** [comment]
So this can be closed if we agree `|grep xor` is an invalid command.

**Comment by radare** [comment]
Thanks!
