### ISSUE TITLE
Consider to use C/C++ package manager

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15882]
We have so many issues with some libraries, maybe we can consider doing it the modern way - splitting into the smaller libraries connected with a modern source-level package manager, like [Conan](https://conan.io).

See more examples on how to use it:
- https://github.com/jonico/libzengithub
- https://blog.openshift.com/conan-accelerates-your-c-c-applications-in-openshift/

What parts we can extract:
- SDB
- Many libraries from `shlr/`
- Binutils-imported code

**Comment by radare** [comment]
Just V ir C using the r2 apis should be enough

**Comment by ret2libc** [comment]
> Just V ir C using the r2 apis should be enough

@radare What does this mean? I don't understand.

@XVilka I'm not sure I see the direct clear benefits of this. I think before worrying about these things, we should at least split the big r2 project in multiple subprojects (e.g. many libraries in shlr, libr_util, etc.)

**Comment by radare** [comment]
i vote for rewriting r2pm in C, r2pm.go is taking too long to come

**Comment by XVilka** [comment]
Wait until GSoC. Also if written in C the cross-compiling r2pm is a PITA,
while Go compilation is uniform between platforms.

**Comment by radare** [comment]
R2 is c and we compile it for all plstforms so this doesnt seems like a good excuse to avoid c to me

**Comment by XVilka** [comment]
So no consensus, closing.
