### ISSUE TITLE
Free the memory after searching instructions by /ad/

### ISSUE THREAD

**Issue by mkYYY** [radareorg/radare2#15888]
**Is your feature request related to a problem? Please describe.**
When I search a sequence of instructions in the binary by `/ad/`, radare2 consumes the extra memory for that (which can be observed from  htop). However, even after the search finishes, it seems that the memory consumed here does not get freed.  
I experienced this when I was analyzing iOS kernelcache as a radare2 project. 

**Describe the solution you'd like**
If there is no reason to keep that memory allocated, it will be nice to let those memory get released so that we can do other operations (e.g. another instruction search) on the same radare2 session without closing it. 
In case this solution doesn't work and it needs to keep those memory, could someone tell me why? (or relevant source code?)

**Comment by radare** [comment]
can you run  r2 in XCode Instruments with the memleak probe and paste some logs here to determine who are the main leakers here? that will save us some time to fix the bug.

thanks!

**Comment by sagnik-chatterjee** [comment]
Can i take up this issue if it is not taken already ??

**Comment by radare** [comment]
yes

**Comment by radare** [comment]
fixed in fdb75d3bf9a3d09f3c95ca0bed0bfb5eaab02684

**Comment by radare** [comment]
calling r_regex_comp after r_regex_new is leaking because its initializing it twice, the leak should be fixed, so maybe worth to open an issue
