### ISSUE TITLE
Replace some eprintf with r_cons_printf

### ISSUE THREAD

**Issue by tzneal** [radareorg/radare2#15900]
**Is your feature request related to a problem? Please describe.**

I was working on a r2-pipe Go wrapper that read radare2's stderr to detect and report errors.  This *mostly* works, except there are a lot of places where eprintf is used for non-error messages:

https://github.com/radareorg/radare2/blob/6c8cc9294b4a7095273dcb5045b0bee86276ecdb/libr/io/p/io_debug.c#L487

https://github.com/radareorg/radare2/blob/11dad4facbe0913457092f127cfae12e40cc714c/libr/main/radare2.c#L1099

https://github.com/radareorg/radare2/blob/11dad4facbe0913457092f127cfae12e40cc714c/libr/debug/debug.c#L112

https://github.com/radareorg/radare2/blob/11dad4facbe0913457092f127cfae12e40cc714c/libr/debug/debug.c#L599

**Describe the solution you'd like**
Replace some non-error usages of eprintf with r_cons_printf

Would there be interest in merging some commits in that do that, or is there a better solution?

**Comment by karliss** [comment]
Without more careful investigation I can't comment if the specific cases you mentioned above are suitable for stderr or not, but assumption that everything in stderr is an error isn't correct. There are plenty of examples of common command line tools using stderr for any diagnostics and status messages not only errors. Some examples are grep, curl, most c compilers when preprocessing a file with `-E` flag. Those tools have their primary output going to stdout and you don't want anything that isn't part of it in stdout as that would make output unusable. It means that all the status messages in  addition to errors must go to stderr. Even if stderr contained only errors you can't know if they are critical or not.

**Comment by tzneal** [comment]
Yes, but grep/curl have process exit codes that can be used to determine if an error occurred. As far as I could tell, there's no way to identify if a command was successful other than by adding support for parsing the possible outputs of each individual command.

**Comment by radare** [comment]
the reason for using eprintf in debiugger code is usually related to non-blocking situations where you want to get the message in the right moment instead of having to wait for the prompt to be calling RCons.flush(). i understand how anoying those messages could be if you are scripting it and we should get rid of them, maybe enabling them like its done with bin.verbose. we can have dbg.verbose to be disabled by default. and just show errors by default, informative messages should be displayed only when this var is set

**Comment by karliss** [comment]
What about use of num->value $? as means of reporting command error. From what I understand some commands use it that way but not consistently so it currently can't be relied on

**Comment by radare** [comment]
What do you mean its not consistent?

**Comment by karliss** [comment]
I meant that there are plenty of commands that don't set $?

**Comment by radare** [comment]
Agree. We should unify this somehow in the new command parser cc @ret2libc

**Comment by trufae** [comment]
Closing because:

* eprintf should be replaced with R_LOG macros
* The error code / return code / return value logic is now implemented
* all those things are known topics and they are being slowly fixed, hopefully completed for 5.8
