### ISSUE TITLE
Wrong assembly for 'not al'

### ISSUE THREAD

**Issue by x0urc3** [radareorg/radare2#15946]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | 
| File format of the file you reverse (mandatory)      | 
| Architecture/bits of the file (mandatory)            | 
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.2.0-git 23640 @ linux-x86-64 git.4.1.1-153-gd0a915458 commit: d0a915458abaa429926840c9fa41e2cd1fedfb1b build: 2020-01-22__11:37:15

### Expected behavior
'not al' should produce f6d0
### Actual behavior
'not al' produce f7d0

### Steps to reproduce the behavior 
```
$ rasm2 -a x86.ks "not al"
f6d0
$ rasm2 -a x86.nz "not al"
f7d0
```
### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by karliss** [comment]
Solved by #15945 ?

**Comment by Maijin** [comment]
Can you add tests @x0urc3 ?

**Comment by x0urc3** [comment]
> Solved by #15945 ?

#15945 is neg

**Comment by karliss** [comment]
Ok, got confused by mismatch between issue name and content.

**Comment by x0urc3** [comment]
My bad. Update title

**Comment by x0urc3** [comment]
> Can you add tests @x0urc3 ?

Done
