### ISSUE TITLE
User/Programmatic instruction/block highlighting

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#15941]
**Is your feature request related to a problem? Please describe.**
For other disassemblers (i.e.: IDA/Binary Ninja) we're able to programmatically inform the disassembler that we want certain instructions or blocks highlighted/colored in a certain way in the graph display (or even just disassemble display).

This is particularly helpful when creating heat maps of addresses visited to emphasize what has been reached or where execution went.

**Describe the solution you'd like**
I want to be able to set colors (background mostly) for instructions or blocks displayed in the disassemble and graph views. 

**Describe alternatives you've considered**
Closest thing i can find is adding comments to every line, but that gets confusing and not something that can be quickly understood by looking at the output.

**Additional context**
Example of using colors for taint propagation is in pictures here:

https://www.osti.gov/servlets/purl/1508238

**Comment by XVilka** [comment]
It's already possible - was done in r2angr afaik. Please check, and close if you think it works for you. Feedback and improvement suggestions are welcome.

**Comment by bannsec** [comment]
Hmm.. So I checked out r2angr but couldn't run it as angr doesn't support python 2 anymore and 2to3 didn't seem to do the trick. I didn't see any refs in the source about colorizing disassembly.

**Comment by bannsec** [comment]
Ah, ok you were thinking of pimp.

Ok, so found what I was looking for i think:
 - set color type: `e scr.color=(0-3)`
 - see color options: `ecs`
 - set color for given instruction: `ecHi <color> @ instruction`

Couple bugs (?)
1. When you're in `VV` mode and run a `ecHi` command, it will not immediately update. Instead, you need to exit VV mode and re-enter it to see the new colors.
1. `ecHi` on an address where you have set a color before ends up not changing the color. You must first `ecH-` before you set it. This may be the intended functionality though.

**Comment by bannsec** [comment]
Gonna close this as the main issue of this ticket is done.
