### ISSUE TITLE
ecHi should return existing highlight information

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#15977]
**Is your feature request related to a problem? Please describe.**
I cannot find a way to programmatically retrieve what the current applied highlight is on a given address.

**Describe the solution you'd like**
I'd like for the `ecHi` command, when provided with no color, to return what colors have been applied to the current address. It would also be helpful to have a `j` option for the same thing.

**Describe alternatives you've considered**

**Additional context**

**Comment by radare** [comment]
Agree. This would be useful and easy to do. Want to contribute?

**Comment by radare** [comment]
its fixed in master
