### ISSUE TITLE
Incorrect ESIL for PPC load/store with update

### ISSUE THREAD

**Issue by quantumdude836** [radareorg/radare2#15970]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | DOL
| Architecture/bits of the file (mandatory)            | PPC/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 23723 @ linux-x86-64 git.4.2.1-56-g037a521d3 commit: 037a521d39a5111477e9248677a1a12d7db30c9e build: 2020-02-13__15:52:54

### Expected behavior

ESIL of e.g. `stwu r1,-8(r1)` is e.g. `r1,-8,r1,+,=[4],-8,r1,+=`

### Actual behavior

ESIL of above example is `r1,-8,r1,+,=[4],4,r1,+=`; the issue is the `4` at the very end; it should be the immediate value from the instruction.
All other load/store with update ESILs have similar issues

### Steps to reproduce the behavior 
- https://asciinema.org/a/WckXWM3qMYYaZHHeIAc0OiMiB (not sure why lines kept overlapping)

**Comment by quantumdude836** [comment]
Test case (db/esil/ppc_32):
```
NAME=load/store with update ppc-32
FILE=-
EXPECT='stwu r1, -8(r1)
0x00000000 r1,-8,r1,+,=[4],-8,r1,+='
CMDS=<<EOF
e asm.arch=ppc
e asm.bits=32
e cfg.bigendian=true
"(pi bytes,wx $0,pi 1,pie 1)"
.(pi 9421fff8)
EOF
RUN
```

**Comment by radare** [comment]
Can you make a pr instead of describing the fix here?
