### ISSUE TITLE
cannot download release windows version

### ISSUE THREAD

**Issue by TheCyborgX** [radareorg/radare2#16006]
Hi, i am actually trying to download the latest version of radare2 for windows, but literally i get 404...

![image](https://user-images.githubusercontent.com/18564537/74892570-c11f9c80-5368-11ea-8b82-eec2b02f259f.png)

is there some alternative documentation available for compiling on this platform?

thanks.

**Comment by XVilka** [comment]
For now, you can download the latest master CI builds for windows:
- VS2017 https://ci.appveyor.com/project/radareorg/radare2/builds/30923252/job/7m96k3g0vc3wd9hp/artifacts
- VS2019 https://ci.appveyor.com/project/radareorg/radare2/builds/30923252/job/w89srtgtx3ktd2p5/artifacts

**Comment by radare** [comment]
Can we upload those artifacts into the Continous releases assets?

**Comment by radare** [comment]
omg you did it <3
