### ISSUE TITLE
4.2.1 is tagged but not marked as a release

### ISSUE THREAD

**Issue by Mic92** [radareorg/radare2#16008]
4.2.1 has been tagged as a release almost a month ago but since there is not 
a release yet, people watching releases did not get a notification.
Currently our update script in nixpkgs also rely on tags being marked as a release: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/analysis/radare2/update.py#L33

### Expected behavior

4.2.1 is marked as a release

### Actual behavior

it is just a tag

**Comment by radare** [comment]
Done
