### ISSUE TITLE
capstone pull doesn't seem to be working - can't build

### ISSUE THREAD

**Issue by jvsteiner** [radareorg/radare2#16011]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS 10.14.6
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64  commit: 17026c8c6251c6c2a8a634ce7a3e6c20b980cb5c build: Feb 20, 2020 at 3:26 PM

### Expected behavior
installation would work

### Actual behavior
failed, with output:
```
Run 'make CS_COMMIT_ARCHIVE=1' to download capstone with wget/curl instead of git

[capstone] Cloning capstone from git...
CC libbochs.c
clang: warning: argument unused during compilation: '-L../../libr/util' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L../../libr/util' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L../../libr/util' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L../../libr/util' [-Wunused-command-line-argument]
ar: creating archive lib/libbochs.a
a - src/libbochs.o

BUILD SUMARY
============
COMPILER gcc
CC gcc
HOST_CC gcc
HOST_OS darwin
BUILD_OS darwin
============

>>>>>>>>>>>>>>>>
NATIVE BUILD SDB
>>>>>>>>>>>>>>>>
ar: creating archive libr_windbg.a

/bin/sh: line 0: cd: src: No such file or directory
make[3]: *** [clean] Error 1
make[2]: *** [sdb/sdb] Error 2
make[1]: *** [targets] Error 2
make[1]: *** Waiting for unfinished jobs....
capstone.sh: line 65: cd: capstone: No such file or directory
[capstone] Failed to chdir
make[1]: *** [capstone-sync] Error 1
make: *** [all] Error 2
```

### Steps to reproduce the behavior 
1. clone repository
2. cd radare2
3. ./sys/install.sh

**Comment by jvsteiner** [comment]
I saw there was a commit this morning - `213bfb622c76a1f4053290dd6406f9cb6368d22f` that seemed like an attempt to fix this.  I tried it, but same error occurred :(

**Comment by radare** [comment]
Looks fine in all our CI runs

**Comment by jvsteiner** [comment]
any ideas what I can try to do to figure out what is going on then?

**Comment by radare** [comment]
are  you using sys/install.sh ? or which  commands/steps are you doing to build r2? also is this a clean checkout? otherwise `git clean -xdf`

**Comment by jvsteiner** [comment]
Yes, this was previously a clean checkout.  Now I ran `git clean -xdf`.  I issued the command `./sys/install.sh`  I realize that the documentation says it should be issued simply `sys/install.sh`, however when I try without `./`, I get:

```
sys/install.sh: line 57: cd: sys: No such file or directory
sys/install.sh: line 103: ./sys/build.sh: No such file or directory
```

Is the omission of the customary `./` before the script a minor typo in the docs, or is there something sranger at work here?

with `./sys/install.sh` at least the build process kicks off, however, after some compilation output, at some point, it fails with the errors in the original post.

I can see that the `shlr/capstone` directory is being created, so I am assuming that the pull is actually happening, however, for some reason, the cd into the directory fails.  

My hunch is that this is a simple, strange issue with the build script, but I cannot work out why it would happen to me, and apparently no one else, since there is nothing particular exotic about my setup.

Thanks

**Comment by radare** [comment]
./foo/bar and foo/bar are exactly the same. No typo. Just a shorter expression

I dont see why it couldnt cd unless there r some permissions issues :? Which operating system is this?

**Comment by jvsteiner** [comment]
> ./foo/bar and foo/bar are exactly the same.
I'm no unix greybeard, but my empirical experience suggests otherwise, since the results are not the same.  This might be an aside however, since the actual problem is the building part.

The OS is MacOS 10.14.6, as per the OP.  I have verified that permissions through the entire tree are for my user.  For good measure I threw in a `chown -R {me} .` with no changes in behavior.

**Comment by jvsteiner** [comment]
Update:  addinga  `sudo` worked.  I would have tried this earlier, but after some browsing through the scripts, I saw where you shouldn't run the install script as root.  Nevertheless, after running it that way, and having the script scold me for doing so, installation worked. 

I anticipate this might cause some head scratching, and, afaiac, this issue is solved, however, I imagine this is not the behavior you expect from your build script.

**Comment by XVilka** [comment]
There is a `sudo` called inside the script, so maybe some kind of regression?

**Comment by radare** [comment]
Which script?
