### ISSUE TITLE
fd -> f. , ff -> fd, f. -> ff

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16033]
Command change plan:

fd -> f. -> flag description can be just f. to chk the flag in the current offset
f. -> ff -> local function flags are accessed thru the f. command, but ff (function flags) makes more sense and doesnt conflict with the meaning of the . suffix
ff -> fd -> ff is used to compute the distance in byte between current and next flag, fd makes more sense because its 'flag distance'

```
| ff ([glob])              distance in bytes to reach the next flag (see sn/sp)
```

**Comment by ret2libc** [comment]
Against it. What's the reason? I would avoid changing the user experience just for.. what? What's the advantage of using these new names?

**Comment by thestr4ng3r** [comment]
I prefer `fd` int the way it is right now because it can mean "flag description" in the sense of "describe this address in terms of flags".
I have no strong opinion about the other two, so I am rather against it.

**Comment by kazarmy** [comment]
A complication here is:

```
[0x00006894]> fd?
Usage: fd[d]  [offset|flag|expression]   # Describe flags
| fd $$         # describe flag + delta for given offset
| fd. $$        # check flags in current address (no delta)
| fdd $$        # describe flag without space restrictions
| fdw [string]  # filter closest flag by string for current offset
```

Changing `fd` -> `f.` is going to be tricky.

**Comment by radare** [comment]
We can keep fd and make f. Just an alias for fd $$

**Comment by XVilka** [comment]
In a way this can be solved by the new parser, when we can have ".", "j" or whatever prefix for each command.

**Comment by radare** [comment]
We broke macros in 4.4, what about breaking those commands as well as the sy/install too?

**Comment by trufae** [comment]
The only benefit was to be consistent with the `.` suffix, and behave like the other commands that end with a dot. But its clear that fd and f. are currently quite used and would be a big breakage if changed.

Other issues i can think of:

* ff label - cons: doesnt imples the . prefix which looks inconsistent
* ff label - cons: requires space (in conrast to f.label)
* actually `f .foo` is the same as `f.foo` 
* `f..` should be an error? or maybe it can act as an `fd` alias?

I will close this ticket as it seems like an unnecessary change, but it was good to discuss
