### ISSUE TITLE
Unable to set 32 bit default interpretation of binaries

### ISSUE THREAD

**Issue by jstaursky** [radareorg/radare2#16046]
#### OS/arch/bits (mandatory) 
Ubuntu x86_64
#### File format of the file you reverse (mandatory)  
ELF
#### Architecture/bits of the file (mandatory)
Raw binary output e.g. `=(echo -n $'\x55\..etc')` (zsh cmd substitution)
#### r2 -v full output, **not truncated** (mandatory)
radare2 4.3.0-git 23835 @ linux-x86-64 git.4.2.1-139-g97498c377
commit: 97498c377ce0ca9aa896631fc7d838a544b679d7 build: 2020-02-24__18:41:48
 
### Expected behavior
setting
```
e asm.arch=x86
e asm.bits=32
```
in .radare2rc should make the default interpretation of binaries as 32 bit
### Actual behavior
These settings in .radare2rc seem to make no difference.
### Steps to reproduce the behavior 
` r2  =(echo -n $'\xc2\x04\x00')` bit any raw binary (e.g. `nasm example.asm -o example`) should work.

example
[asciinema.zip](https://github.com/radareorg/radare2/files/4247491/asciinema.zip)

**Comment by radare** [comment]
Just use -b32. Raw binaries contain no bin info. So r2 picks the default system arch/bits settings
