### ISSUE TITLE
Changes to a function signature don't apply properly

### ISSUE THREAD

**Issue by oxcabe** [radareorg/radare2#16059]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 23856 @ linux-x86-64 git.3.3.0-2767-g74d832d0b commit: 74d832d0b97dbc0973d5b480f1528b0bc601d140 build: 2020-02-26__13:49:00

### Expected behavior
`afs` should properly set return type and function parameters.

### Actual behavior
`afs` changes function name, but keeps type and function parameters from original signature definition.

### Steps to reproduce the behavior 
- Binary: ls (GNU coreutils) 8.31

```
~  $ r2 /bin/ls
[0x00005b10]> af
[0x00005b10]> afs
entry0 (int64_t arg3);
[0x00005b10]> "afs int foo.bar(int a, char *b);"
[0x00005b10]> afs
foo.bar (int64_t arg3);
[0x00005b10]>
```

**Comment by radare** [comment]
can you add a test?, because the one you are showing here seems to be wrong

**Comment by oxcabe** [comment]
I'll try to fix the wrong one
