### ISSUE TITLE
cbin.c: missing semicolon

### ISSUE THREAD

**Issue by donovank** [radareorg/radare2#16075]
Line 2542 of `cbin.c` (see [here](https://github.com/radareorg/radare2/blob/5b8366441db2efefe8143de7bd84593076a5e6c1/libr/core/cbin.c#L2542)) seems to be missing a semicolon.

It was introduced in the most recent [commit](https://github.com/radareorg/radare2/commit/5b8366441db2efefe8143de7bd84593076a5e6c1).

**Comment by AhmedMkadem** [comment]
Same issue here.

**Comment by Bigsby** [comment]
Yup.

**Comment by karliss** [comment]
Fixed in #16076
