### ISSUE TITLE
ANSI escape codes after JSON output causes failures in r2pipe

### ISSUE THREAD

**Issue by haystack-ia** [radareorg/radare2#16097]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 24103 @ linux-x86-64 git.4.2.1-186-gf5aecb853
commit: f5aecb853408008c9f0c7b9d2576909ea232e402 build: 2020-03-02__12:56:43

### Expected behavior

r2pipe library 'cmdj' should parse output of json commands.

### Actual behavior

Trailing ANSI escape codes in json output cause output errors.

### Steps to reproduce the behavior

asciinema link here: https://asciinema.org/a/306630. I am sorry for the weird asciinema output, not sure how to fix.

demonstrates that two json commands (`aflj` and `axtj`) share this behavior. also shows that setting `scr.color=0` fixes the issue.

**Comment by radare** [comment]
comments on this @ret2libc ?

**Comment by ret2libc** [comment]
I don't really know how r2pipe works, but I believe `cmdj` should set scr.color=0 before calling any command, as when using it you don't really care about colors. Right?

**Comment by haystack-ia** [comment]
@ret2libc that would have to be implemented across all the different `r2pipe` language bindings, no? If there were a way to implement the fix in r2 then it would work across all implementations.

I also noticed that output of `cmd` has no trailing ANSI junk regardless of `scr.color` settings. I don't know if that is implemented in r2 or the python library though.

**Comment by radare** [comment]
Suffixing any command with a pipe will disable html and colors.

**Comment by radare** [comment]
The solution must be in r2 imho. Otherwise we will have to fix all the r2pipe implementations

**Comment by radare** [comment]
i think it should be fixed now in master (4.3 release)
