### ISSUE TITLE
`r_strbuf_fini` in PPC analop "hides" longer ESIL statements

### ISSUE THREAD

**Issue by quantumdude836** [radareorg/radare2#16102]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | DOL
| Architecture/bits of the file (mandatory)            | PPC/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 23907 @ linux-x86-64 git.4.2.1-188-gcf1e7d9a6 commit: cf1e7d9a680f12b85895ae317f10366c7330ddf7 build: 2020-03-02__13:38:39

### Expected behavior

`pie` shows all supported ESIL statements regardless of their length

### Actual behavior

ESIL statements longer than about 30 characters (i.e. the static buffer size of RStrBuf) aren't shown

### Steps to reproduce the behavior 
Example test case:

    EXPECT=<<EOF
    bdnz 0xfffffffffffffff0
    0x00000000 1,ctr,-=,$z,!,?{,0xfffffffffffffff0,pc,=,}
    EOF
    CMDS=<<EOF
    e asm.arch=ppc
    e asm.bits=32
    e cfg.bigendian=true
    "(pi bytes,wx $0,pi 1,pie 1)"
    .(pi 4200fff0)
    EOF

**Comment by quantumdude836** [comment]
Looks like most of the generated ESIL fits within the 32-byte static buffer of `RStrBuf`, which isn't touched by `r_strbuf_fini`

**Comment by pelijah** [comment]
IMO `r_strbuf_fini()` shouldn't be called from `analop()` at all.

**Comment by pelijah** [comment]
Seems `ppc_cs` and `risc_cs` plugins are affected by this bug too.

**Comment by quantumdude836** [comment]
> Seems `ppc_cs` and `risc_cs` plugins are affected by this bug too.

I noticed that too (in `riscv_cs` and `mips_cs`), but the difference is that they're called if `analop_esil` fails (i.e. doesn't return 0), so IMO those are acceptable.

That's why my fix changes it to only call `r_strbuf_fini` if `R_ANAL_OP_MASK_ESIL` isn't set (since the PPC analysis doesn't have a separate `analop_esil` function).

**Comment by radare** [comment]
Can you fix the other affected plugins too? I also agree strbuf.fini shouldnt be called from there
