### ISSUE TITLE
Radare2 crashes processing .sig file

### ISSUE THREAD

**Issue by yjGT** [radareorg/radare2#16104]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.1 LTS, x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86-64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 23894 @ linux-x86-64 git.4.2.1-180-g53f21d9ae commit: 53f21d9ae6e50cc6a76745829c37c134e50542f4 build: 2020-03-02__07:14:45

### Expected behavior
When running `zfs` on a flirt signature, it should report the found flirt function.
example:
```
[0x00400a30]> zfs ./libc6_2.11.1-0ubuntu7.15_amd64.sig
Found flirt.__new_pclose
Found flirt.__geteuid
Found flirt.__getuid
Found flirt.__getegid
Found flirt.__getgid
Found flirt._setjmp
Found flirt._dl_mcount_wrapper_check
Found flirt.__wmemcpy
Found flirt.release_libc_mem
Found flirt.__wmemcpy
Found flirt.__wmemcpy
Found flirt.__dcgettext
Found flirt.__profile_frequency
```

### Actual behavior
It crashes with a failed assertion:
```
[0x00400194]> zfs ./libc6_2.27-3ubuntu1_amd64.sig
WARNING: r_list_join: assertion 'list1 && list2' failed (line 147)
radare2: block.c:359: r_anal_block_unref: Assertion `bb->ref >= r_list_length (bb->fcns)' failed.
Aborted (core dumped)
```

### Steps to reproduce the behavior
- Excuse me but the file upload keeps failing.. Two files are needed to reproduce the crash. The .sig file from an open source sig library; and the target binary (a hello world example)
Attachments:

1) sig file link:
[https://github.com/push0ebp/sig-database/blob/master/ubuntu/libc6/18.04%20(bionic)/amd64/libc6_2.27-3ubuntu1_amd64.sig](url)

2) test_sample:

hello.c
```
#include "stdio.h"

int main() {
	printf("first_c\n");
	return 0;
}
```

build: `gcc hello.c -s -static -o test_sample`

- Reproducing steps:
```
$ radare2 test_sample
 [0x00400194] aac
 [0x00400194] zfs ./libc6_2.27-3ubuntu1_amd64.sig
```

**Comment by thestr4ng3r** [comment]
reproduced

**Comment by thestr4ng3r** [comment]
for reference: [test_sample.gz](https://github.com/radareorg/radare2/files/4281248/test_sample.gz)

**Comment by radare** [comment]
Is this bin in the testsuite now?

**Comment by thestr4ng3r** [comment]
yes
