### ISSUE TITLE
Refactor function renaming API

### ISSUE THREAD

**Issue by oxcabe** [radareorg/radare2#16124]
```
libr/core/cmd_anal.c:2547:static bool __setFunctionName(RCore *core, ut64 addr, const char *_name, bool prefix) {
core/canal.c:692:static void function_rename(RFlag *flags, RAnalFunction *fcn) {
core/vmenus.c:2653:static void function_rename(RCore *core, ut64 addr, const char *name) {
include/r_anal.h:1410:R_API bool r_anal_function_rename(RAnalFunction *fcn, const char *name);
include/r_anal.h:1546:R_API void r_anal_fcn_rename(RAnalFunction *f, const char *newName);
```

I think we should be able to have just one of these. Opinions?

**Comment by radare** [comment]
the conflict is with those two mainly

**Comment by radare** [comment]
```
pmb:radare2 pancake$ git grep r_anal_fcn_rename
libr/core/cmd_anal.c:/* TODO: move into r_anal_fcn_rename(); */
libr/include/r_anal.h:R_API void r_anal_fcn_rename(RAnalFunction *f, const char *newName);

pmb:radare2 pancake$ git grep r_anal_function_rename
libr/anal/function.c:R_API bool r_anal_function_rename(RAnalFunction *fcn, const char *name) {
libr/core/canal.c:                      r_anal_function_rename (fcn, f->name);
libr/core/canal.c:                      r_anal_function_rename (fcn, f->name);
libr/core/canal.c:              r_anal_function_rename (fcn, sdb_fmt ("%s.%08" PFMT64x, fcnpfx, fcn->addr));
libr/core/cmd_anal.c:           r_anal_function_rename (fcn, name);
libr/include/r_anal.h:R_API bool r_anal_function_rename(RAnalFunction *fcn, const char *name);
pmb:radare2 pancake$
```

... fcn_rename() is not used at all, so we can start by removing dead code :D

**Comment by pparmin** [comment]
Hello everyone :) 
This is the first time for me to ever work on an open source project. I really love radare2 and would love to start contributing and help move the project forward. I think this could be a good issue to get my feet wet with the whole process, so I would like to see if I can help out with removing the dead code. 

As I am new to this, could someone provide me with some guidance on how to approach this? 

> ``` pmb:radare2 pancake$ git grep r_anal_fcn_rename libr/core/cmd_anal.c:/* TODO: move into r_anal_fcn_rename(); */ libr/include/r_anal.h:R_API void r_anal_fcn_rename(RAnalFunction *f, const char *newName); pmb:radare2 pancake$ git grep r_anal_function_rename libr/anal/function.c:R_API bool r_anal_function_rename(RAnalFunction *fcn, const char *name) { libr/core/canal.c: r_anal_function_rename (fcn, f->name); libr/core/canal.c: r_anal_function_rename (fcn, f->name); libr/core/canal.c: r_anal_function_rename (fcn, sdb_fmt ("%s.%08" PFMT64x, fcnpfx, fcn->addr)); libr/core/cmd_anal.c: r_anal_function_rename (fcn, name); libr/include/r_anal.h:R_API bool r_anal_function_rename(RAnalFunction *fcn, const char *name); pmb:radare2 pancake$ ``` 
... fcn_rename() is not used at all, so we can start by removing dead code :D >

If I understand your last answer correctly, all that would need to be done for this is to remove r_anal_fcn_rename from anal.c and anal.h, correct?

**Comment by trufae** [comment]
Yes, this is a good task to start with!

r_anal_fcn_rename was already removed a while ago. but it needs still to remove `function_rename` from vmenus.c and canal.c as well as __setFunctionName.

The task is to understand how those functions are called and remove them if they are bare wrappers of the final r_anal_fcn_rename() just to avoid direct access fields in the RAnalFunction struct for example and review that code without breaking the functionality.

**Comment by radare** [comment]
Only remaining task is the static camelcase function in canal.c, so its fine to close this now
