### ISSUE TITLE
what technique does radare use for type inference in binaries?

### ISSUE THREAD

**Issue by Ruturaj4** [radareorg/radare2#16128]
I have read papers like - TIE, artiste and bytewrite - these are type inference techniques in binary. I would like to ask what technique does radare use for type inference.

I recently found that "Polymorphic type inference" is another (better ?) technique. This may not be considered as a feature request. I have seen the radare doc and it is mentioned that some types are omitted and types like "int_64" are used instead of conventional types.

I would like to ask what papers/ techniques can be better in this case (so that these can be implemented in radare).

I appreciate your replies and thanks in advanced.

**Comment by XVilka** [comment]
It's nothing from the papers, was hand-crafter to have the suitable performance. I am afraid the code is the only source of ground truth here. But we want to improve this code, see the corresponding projects:
- https://github.com/radareorg/radare2/projects/19
- https://www.radare.org/gsoc/2020/ideas.html#title_0
