### ISSUE TITLE
Projects regression on latest master - Windows + Clang-cl

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16127]
It shows only on the clang-cl build, MSVC on AppVeyor is fine (all versions), Travis is all fine.

See full log here: https://ci.appveyor.com/project/radareorg/radare2/builds/31224494/job/ebn3edg590l9ovcw#L3636
```
[XX] db\cmd\cmd_project Delete a saved project and used directory (with Pd)  1889
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -n -i C:\Users\appveyor\AppData\Local\Temp\1\tmp-4128Z7F7LoqLKOTx ../bins/elf/analysis/main
e dir.projects = .tmp/
Ps blah > nul
Pd blah > nul
Pl~blah
ls -l `e dir.projects`~blah
+d-r-xr-x  1    0:0     0           .tmp/blah/
EXPECT='d-r-xr-x  1    0:0     0           .tmp/blah/'
```

**Comment by radare** [comment]
is marked as broken afaik

**Comment by XVilka** [comment]
No: https://github.com/radareorg/radare2/blob/master/test/new/db/cmd/cmd_project#L305

**Comment by radare** [comment]
this test was marked as broken, its not a regression

**Comment by XVilka** [comment]
It wasn't - see no "BROKEN=1" line in the failing test.

**Comment by XVilka** [comment]
Was fixed
