### ISSUE TITLE
om= crash

### ISSUE THREAD

**Issue by xmikasax** [radareorg/radare2#16143]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0 23884 @ linux-x86-64 git.4.3.0-3-g4271bce commit: 4271bce56a5434064e84a6b1809532a9a64768fd build: 2020-03-04__21:50:55

### Expected behavior

`om=` should list all maps in ascii art

### Actual behavior

`om=` crashes radare2

### Steps to reproduce the behavior 

[ls.zip](https://github.com/radareorg/radare2/files/4289889/ls.zip)

```
➜  test r2 ls
[0x004049a0]> om=
[1]    18308 segmentation fault  r2 ls
```

**Comment by radare** [comment]
fixed
