### ISSUE TITLE
wopD reports "Failed to write" error

### ISSUE THREAD

**Issue by xmikasax** [radareorg/radare2#16142]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0 23884 @ linux-x86-64 git.4.3.0-3-g4271bce commit: 4271bce56a5434064e84a6b1809532a9a64768fd build: 2020-03-04__21:50:55

### Expected behavior

`wopD 5` should write a De Bruijn Pattern of length 'len' at address 'addr' without errors

### Actual behavior

`wopD 5` reports `Failed to write` error

### Steps to reproduce the behavior 

[ls.zip](https://github.com/radareorg/radare2/files/4289889/ls.zip)

```
➜  test r2 -w ls
[0x004049a0]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x004049a0  31ed 4989 d15e 4889 e248                 1.I..^H..H
[0x004049a0]> wx 414141
[0x004049a0]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x004049a0  4141 4189 d15e 4889 e248                 AAA..^H..H
[0x004049a0]> wopD 5
Failed to write
Failed to write
Failed to write
Failed to write
Failed to write
[0x004049a0]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x004049a0  4141 4142 415e 4889 e248                 AAABA^H..H
[0x004049a0]>
```

**Comment by XVilka** [comment]
Can you please craft a testcase for this? Also for the https://github.com/radareorg/radare2/issues/16141 ?

**Comment by xmikasax** [comment]
> Can you please craft a testcase for this? Also for the #16141 ?

How do I check stderr in the testcase? Because an error appears in stderr, but EXPECT is only for stdout
