### ISSUE TITLE
Make capstone, grub, zlib, etc Meson subrojects

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16145]
It will allow both to easily decouple and update them, but also to build everything in-place with [Meson Wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html).

Meson has a concept of subprojects. They are a way of nesting one Meson project inside another. Any project that builds with Meson can detect that it is built as a subproject and build itself in a way that makes it easy to use (usually this means as a static library).

To use this kind of a project as a dependency you could just copy and extract it inside your project's subprojects directory.

However there is a simpler way. You can specify a Wrap file that tells Meson how to download it for you. If you then use this subproject in your build, Meson will automatically download and extract it during build. This makes subproject embedding extremely easy.

All wrap files must have a name of `<project_name>.wrap` form and be in `subprojects` dir.

Currently Meson has four kinds of wraps:

-    wrap-file
-    wrap-git
-    wrap-hg
-    wrap-svn

There exist [WrapDB](https://wrapdb.mesonbuild.com/) database of some popular libraries, that can be reused, similar to the package management. It has [zlib](https://wrapdb.mesonbuild.com/zlib), for example.

**Comment by trufae** [comment]
That was made by rizin, closing here, no plans to split up the project
