### ISSUE TITLE
wopD* ignoring len

### ISSUE THREAD

**Issue by xmikasax** [radareorg/radare2#16141]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0 23884 @ linux-x86-64 git.4.3.0-3-g4271bce commit: 4271bce56a5434064e84a6b1809532a9a64768fd build: 2020-03-04__21:50:55

### Expected behavior

`wopD* 1` should print wx command that creates a debruijn pattern of a specific length

### Actual behavior

`wopD*` ignores provided length

### Steps to reproduce the behavior 

[ls.zip](https://github.com/radareorg/radare2/files/4289889/ls.zip)

```
➜  test r2 -w ls
[0x004049a0]> wopD* 1
wx 4141414241414341414441414541414641414741414841414941414a41414b41414c41414d41414e41414f41415041415141415241415341415441415541415641415741415841415941415a41416141416241416341416441416541416641416741416841416941416a41416b41416c41416d41416e41416f41417041417141417241417341417441417541417641417741417841417941417a41413141413241413341413441413541413641413741413841413941413041424241424341424441424541424641424741424841424941424a41424b41424c41424d41424e41424f414250414251414252414253414254414255414256414257414258414259
[0x004049a0]>
```

**Comment by xmikasax** [comment]
Added testcase for this #16148

**Comment by radare** [comment]
fixed
