### ISSUE TITLE
Symbol relocations broken

### ISSUE THREAD

**Issue by karliss** [radareorg/radare2#16159]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux/x86_64/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.1 23994 @ linux-x86-64 git.4.3.1  commit: e7f940d27b3b4eb2738afef78a6ea09ed770318c build: 2020-03-07__13:53:00
### Expected behavior
When reopening file in debug mode function addresses get adjusted according with address where the executable is loaded.
### Actual behavior
Function addresses remain unchanged.

### Steps to reproduce the behavior 
* Open executable `radare2 /usr/bin/ls`
* Do basic analysis for detecting functions `aa`
* list functions `afl`
* Reopen in debug mode `ood`
* list functions `afl` observe that addresses didn't change
* compare against memory map `dm`

**Comment by karliss** [comment]
ASLR makes writing a test a bit more complicated.
The test could use something like this to verify offset against memory map.
```
?v main-`dmm~ls[0]`
```

**Comment by radare** [comment]
Yep
