### ISSUE TITLE
r2 -c "pa b addr" assembly arror

### ISSUE THREAD

**Issue by Tigre000** [radareorg/radare2#16158]
# r2 -c "pa b addr" assembly arror

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | iOS 13.3.1 Darwin 19.3.0 arm64
| File format of the file you reverse (mandatory)      | mach-O
| Architecture/bits of the file (mandatory)            | arm64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.1 23912 @ darwin-arm-64 git.4.3.1-1-ge55661bd4 commit: e55661bd4c229b9095982675709bdd52e1b4c068 build: 2020-03-07__17:17:35

Test in iOS binary

	[0x10000a94c]> s 0x1000057e8
	[0x1000057e8]> pa b 0x100005fcc
	f9010017
	[0x1000057e8]> s 0
	[0x00000000]> pa b 0x7e4
	f9010014

When you open the binary, and assemble it with a pa command, the assembly is good at offset 0, but not in offset 0x1000057e8.
The resulting value of the pa command appears to vary depending on the address.

	Jail-SE:~ root# rasm2 -a arm -b 64 "b 0x7e4"
	f9010014
	
I think it is better to assemble it into the relative address, as if using rasm2 when using the pa command in radare2.
Or I think it is good to correct the error when using the pa command. #

**Comment by radare** [comment]
The assembler Is always relative mainly because many instructions dont provide absolute addressing options. Use the -o flag to specify the offset u want yhat thing to be assembled

**Comment by Tigre000** [comment]
r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x7e4"
    f9010014
    r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x100005fcc"
    f3170014
    r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x100005fcc" -o 0x1000057e8
    f9010017
The same problem occurs when using the -o flag.

**Comment by Tigre000** [comment]
r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x7e4"
    f9010014
    r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x100005fcc"
    f3170014
    r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x100005fcc" -o 0x1000057e8
    f9010017
The same problem occurs when using the -o flag.

**Comment by Tigre000** [comment]
I think the branch function in libr/asm/arch/arm/armass64.c is the problem.

**Comment by Tigre000** [comment]
I found another problem.

    r2@Tigre000:~$ rasm2 -a arm -b 64 "b 0x100005004" -o 0x1000057e8
    07ffff17
    r2@Tigre000:~$ rasm2 -a arm -b 64 -d 07ffff17 -o 0x1000057e8
    b 0x100005404
    r2@Tigre000:~$ rasm2 -a arm -b 64 -d 07feff17 -o 0x1000057e8
    b 0x100005004

**Comment by radare** [comment]
Same issue again. The hexpairs are not an argument for -d . You are passing flags after optarg which are ignored
