### ISSUE TITLE
Mac Os X 4.2.1 version download - 404

### ISSUE THREAD

**Issue by Kuzcoo** [radareorg/radare2#16162]
Hi,

When I click on "Download 4.2.1 for OS X" from the home page, I got a 404.
However I see there is a 4.3.1 version available in `.pkg` on the same domain.
Wich is the latest stable version ?

Besides, I don't find this domain very trustworthy.
Is there a way to host the bin versions on radare.org or at least the hashes ?

Thank you

**Comment by radare** [comment]
4.3.1 is out and all the bins have been generated. when i did 4.2.1 i was not at home, and noww alllt he releases happen in CI. so closing
