### ISSUE TITLE
afc null in afi*

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16169]
```
[0x100004560]> afi*
"f sym.imp.tputs 6 0x100004560"
"af+ 0x100004560 sym.imp.tputs s n"
afb+ 0x100004560 0x100004560 6 0xffffffffffffffff 0xffffffffffffffff
afB 64 @ 0x100004560
afc (null) @ 0x100004560
axc 0x100006230 0x100004560
afS 0 @ 0x100004560
```

**Comment by c-urly** [comment]
Is this for particular machine/arch? because i am getting this output in mac.

<img width="549" alt="Screenshot 2020-03-09 at 9 04 12 PM" src="https://user-images.githubusercontent.com/14140421/76230322-8c0cb880-6249-11ea-9c7a-38641985d577.png">
