### ISSUE TITLE
rax2 - support conversion and calculation at the same time

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16173]
Currently you either can convert the decimal to hexadecimal with `rax2 =16 16` or calculate the expression with `rax2 0x8+0x8`. But you can't do it at the same time:
```
$ rax2 =16 0x8+0x8
16
```
But if you do the same with `rax2 =16 8+8` it will return the right output of `0x10`. Seems it can't handle the `0x` prefix in this case.

**Comment by radare** [comment]
thats a regression. use -k for now

**Comment by radare** [comment]
and this needs tests
