### ISSUE TITLE
Interactive radiff2 mode is broken

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16183]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 26044 @ linux-x86-64 git.4.3.1-25-gc1c54be39 commit: c1c54be39e3dc61367d5d08ab87bf11623fe8355 build: 2020-03-11__12:53:04

### Expected behavior
Show the visual graph interactive mode

### Actual behavior
Shows nothing, just empty output

### Steps to reproduce the behavior 
```
radiff2 -g main -m i /bin/false /bin/true
```

**Comment by kuqadk3** [comment]
It works fine on my ubuntu 16.04.

![image](https://user-images.githubusercontent.com/12135974/76403368-66052680-63b7-11ea-99fd-89a4eef3fad5.png)

**Comment by radare** [comment]
i doubt the issue have anything to do with the version of the OS

provide sample binary and version of r2

**Comment by XVilka** [comment]
Was fixed.
