### ISSUE TITLE
types can contain spaces and commands dont consider this

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16195]
<img width="628" alt="Screenshot 2020-03-12 at 12 00 11" src="https://user-images.githubusercontent.com/917142/76514971-124b1980-6459-11ea-9877-0c4c5e7d7130.png">

**Comment by ret2libc** [comment]
Can you be more specific in describing the issue? I guess following the template would help everybody understand what's going on. What is the problem, how to reproduce, what is the expected outcome...

**Comment by radare** [comment]
the command takes two arguments (separated by a space)

* the first one can contain spaces
* the second one does not

BOOM
