### ISSUE TITLE
Do not print strings in `radiff2 -qu file1 file2`

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16190]
`radiff2 -qu file1 file2` currently prints strings, while it's unnecessary. For now the only difference between `radiff2 -qu` and `radiff2 -u` is the color. Would be nice to have the option to print just changes, without the strings or change the behavior of the current one.

```
-0x000004f8:05 "\x05"
-0x000004fc:07 "\a"
-0x00000500:08 "\b"
-0x00000508:1800 "\x18"
+0x00000508:3a03
-0x00000510:09 "\t"
+0x00000510:34
-0x00000514:03 "\x03"
+0x00000520:01
-0x00000528:4803 "H\x03"
```
should become
```
-0x000004f8:05
-0x000004fc:07
-0x00000500:08
-0x00000508:1800
+0x00000508:3a03
-0x00000510:09
+0x00000510:34
-0x00000514:03
+0x00000520:01
-0x00000528:4803
```
Also I am not sure - may be it's better to align the data bytes, add spacing between them like in the hex mode?
```
-0x000004f8: 05
-0x000004fc: 07
-0x00000500: 08
-0x00000508: 18 00
+0x00000508: 3a 03
-0x00000510: 09
+0x00000510: 34
-0x00000514: 03
+0x00000520: 01
-0x00000528: 48 03
```

**Comment by kuqadk3** [comment]
Nice, I will take this.

**Comment by kuqadk3** [comment]
If I modify 'u', it also modifies 'qu'.
Should we implement a new option or change behavior of the current one?

**Comment by kuqadk3** [comment]
Ah nvm, seems like -qu is supposed to not print any string out. Gonna fix this.
