### ISSUE TITLE
Dietline segfault

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16192]
reproducer:

* type something
* press ctrl-a
* press ctrl-x

segfaullt

**Comment by XVilka** [comment]
Cannot reproduce in Linux.

**Comment by radare** [comment]
r2 /bin/ls
 -- Greetings, human.
=================================================================
==47815==ERROR: AddressSanitizer: strncpy-param-overlap: memory ranges [0x0001094e7498,0x0001094e74a5) and [0x0001094e7498, 0x0001094e74a5) overlap
    #0 0x112a25a4e in wrap_strncpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5ba4e)
    #1 0x10940d826 in r_line_readline_cb dietline.c:1481
    #2 0x10940a252 in r_line_readline dietline.c:830
    #3 0x10d13ac52 in r_core_fgets core.c:1996
    #4 0x109442aa3 in r_cons_fgets input.c:363
    #5 0x10d15569e in r_core_prompt core.c:3021
    #6 0x10d1551a6 in r_core_prompt_loop core.c:2888
    #7 0x112946fd2 in r_main_radare2 radare2.c:1350
    #8 0x1093b4462 in main (r2:x86_64+0x100001462)
    #9 0x7fff6d35a7fc in start (libdyld.dylib:x86_64+0x1a7fc)

0x0001094e7498 is located 88 bytes inside of global variable 'r_line_instance' defined in 'line.c:6:14' (0x1094e7440) of size 4384
0x0001094e7498 is located 88 bytes inside of global variable 'r_line_instance' defined in 'line.c:6:14' (0x1094e7440) of size 4384
SUMMARY: AddressSanitizer: strncpy-param-overlap (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5ba4e) in wrap_strncpy
==47815==ABORTING
Abort trap: 6
pmb:radare2 pancake$

**Comment by radare** [comment]
just do asan, but may be related to the mac libc. fixed now
