### ISSUE TITLE
Getting wrong heap info with 'dmh'

### ISSUE THREAD

**Issue by CTSinon** [radareorg/radare2#16206]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali Linux, 64 bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.1 0 @ linux-x86-64 git.4.3.1</br>commit: HEAD build: 2020-03-08__19:32:56

### Expected behavior

An output like what peda-gdb does:

```
0x564ab250f000 SIZE=0x290 DATA[0x564ab250f010] |................................| INUSED PREV_INUSE
0x564ab250f290 SIZE=0x20 DATA[0x564ab250f2a0] |........................!.......| INUSED PREV_INUSE
0x564ab250f2b0 SIZE=0x20 DATA[0x564ab250f2c0] |........................!.......| INUSED PREV_INUSE
0x564ab250f2d0 SIZE=0x20 DATA[0x564ab250f2e0] |................................| INUSED PREV_INUSE
0x564ab250f2f0 SIZE=0x20d10 TOP_CHUNK
```

### Actual behavior

The output is

```
  Malloc chunk @ 0x56464fdfa250 [corrupted]
   size: 0x0
   fd: 0x0, bk: 0x0

  Top chunk @ 0x56464fdfa2f0 - [brk_start: 0x56464fdfa000, brk_end: 0x56464fe1b000]
```

And it takes almost half a minute to get this.

### Steps to reproduce the behavior 
- compile this program with gcc

```
#include <stdlib.h>

int main(void) {
    char *a = (char *) malloc(sizeof(char));
    char *b = (char *) malloc(sizeof(char) * 3);
    int *c = (int *) malloc(sizeof(int));

    free(a);
    free(b);
    free(c);
    return 0;
}
```

- load with `r2 -d a.out` 
- `dcu main;dso 12;dmh`

There is also an error message after loading the file
`Warning: r_bin_file_hash: file exceeds bin.hashlimit`

**Comment by x0urc3** [comment]
-Which glibc version? `dcu main;dm~libc`
-Could you try disabling tcache. `e dbg.glibc.tcache=false`

**Comment by CTSinon** [comment]
> -Which glibc version? `dcu main;dm~libc`
> -Could you try disabling tcache. `e dbg.glibc.tcache=false`

My glibc version is libc-2.29.so
It works! Thank you very much!

**Comment by CTSinon** [comment]
But it seems 'dmh' does not response the free operation now
