### ISSUE TITLE
Incorrect disassembly for 32 bit MIPS R3000 binary

### ISSUE THREAD

**Issue by PabloMansanet** [radareorg/radare2#16207]
* Radare 2 version: radare2 4.3.0-git 23701 @ linux-x86-64 git.4.2.1-3-gb6080f86c0

# Description

While reversing a mips32 binary extracted from a commercial home access point, the disassembly output is incorrect. 

# Target

The sample binary is attached. : [sample.zip](https://github.com/radareorg/radare2/files/4329426/sample.zip)

Here is the rabin2 -I output:

```
      arch     mips
      baddr    0x400000
      binsz    27184
      bintype  elf
      bits     32
      canary   true
      class    ELF32
      crypto   false
      endian   big
      havecode true
      intrp    /lib/ld-musl-mips-sf.so.1
      laddr    0x0
      lang     c
      linenum  true
      lsyms    true
      machine  MIPS R3000
      maxopsz  16
      minopsz  1
      nx       true
      os       linux
      pcalign  0
      pic      false
      relocs   true
      relro    full
      rpath    NONE
      sanitiz  false
      static   false
      stripped false
      subsys   linux
      va       true
```

# Configuration

Here are the relevant options (to my knowledge):
```
:> e asm.cpu
mips32/64
:> e asm.arch
mips
:> e asm.bits
32
:> e cfg.bigendian
true
```

I have tested all possible combinations of the options above, and while they produced different assembly code, none of it was correct.

# Comparison with Ghidra

Here is a snippet of the disassemble code in Ghidra and r2 respectively:

Ghidra:
```
        00402938 f4 00 b2 14     lw         v0,0x414(pc)=>->__stack_chk_guard                = 00416820
        0040293c f0 50 64 f3     save       0x298,ra,s0-s1
        00402940 67 24           move       s1,argc
        00402942 9a 40           lw         v0,0x0(v0)=>__stack_chk_guard
```

radare2:
```
        0x00402938      f400b214       sdc1 f0, -0x4dec(zero)
        0x0040293c      f05064f3       invalid
        0x00402940      67249a40       invalid
        0x00402944      6705d2a1       invalid
```

**Comment by radare** [comment]
r2 is not a disassembler. the issue (if any) it's in capstone or gnu binutlis. check this:


$ rasm2 -a mips -b32 -d f400b214
bne a1, s2, 0x3d4
$ rasm2 -e -a mips -b32 -d f400b214
sdc1 f0, -0x4dec(zero)

$ rasm2 -e -a mips.gnu -b32 -d f400b214
sdc1 $f0, -19948(zero)
$ rasm2 -a mips.gnu -b32 -d f400b214
bne a1, s2, 0x000003d4

actually, the closest i can get to have a load instruction there is by using the micro CPU (e asm.cpu=micro) for the capstone MIPS disassembler, but still is not the same as the ghidra one.

Can you provide the binary?
Can you provide the CPU details?

**Comment by PabloMansanet** [comment]
Hey, thanks for the response. The binary is attached on my original post above (sample.zip).

As for my environment, uname -a:

```
Linux 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux
````

**Comment by radare** [comment]
Please fill this issue in the capstone repository., i dont think this is an issue in r2
