### ISSUE TITLE
Introduce a debugger's target base address variable

### ISSUE THREAD

**Issue by 0xThiebaut** [radareorg/radare2#16219]
**Is your feature request related to a problem? Please describe.**
Whenever I am debugging a binary with Ghidra opened on the side I need to be able to easily place breakpoints using relative addresses. Each time I want to set relative breakpoint, say at `0x2488`, I must first use `di` to get the base address.

```bash
di
```

> ```
> type=dead
> signal=none
> signum=0
> sigpid=0
> addr=0x0
> bp_addr=0x0
> inbp=false
> baddr=0x55f9b8067000
> pid=3528
> tid=3528
> stopaddr=0x0
> uid=1000
> gid=1000
> exe=/home/user/Downloads/cr4ckMe.bin
> cmdline=./aNn0yIng_cr4ckMe.bin
> cwd=/home/user/Downloads
> ```
> 

To finally be able to set the breakpoint using `db`.
```bash
db 0x55f9b8067000+0x2488
```

**Describe the solution you'd like**
I would like to have a variable reference the debugger's target base address as obtained using the `di` command. As the `$D` variables seem related to the debugger, may I suggest `$Db` as debugger base?

**Describe alternatives you've considered**
I have tried relying on `$D` which is described as follow:

> current debug map base address ?v $D @ rsp

However, the value of `$D` doesn't match the `baddr` obtained using `di`.

```
[0x7fba7338c100]> di
type=dead
signal=none
signum=0
sigpid=0
addr=0x0
bp_addr=0x0
inbp=false
baddr=0x5596721e4000
pid=4966
tid=4966
stopaddr=0x0
uid=1000
gid=1000
exe=/home/user/Downloads/cr4ckMe.bin
cmdline=./cr4ckMe.bin
cwd=/home/user/Downloads
[0x7fba7338c100]> db 0x5596721e4000+0x2488
[0x7fba7338c100]> db $D+0x2488
[0x7fba7338c100]> db
0x5596721e6488 - 0x5596721e6489 1 --x sw break enabled valid cmd="" cond="" name="0x5596721e4000+0x2488" module="/home/user/Downloads/cr4ckMe.bin"
0x7fba7338e488 - 0x7fba7338e489 1 --x sw break enabled valid cmd="" cond="" name="$D+0x2488" module="/usr/lib/x86_64-linux-gnu/ld-2.30.so"
```

I furthermore checked the output of `di*` but was unable to understand if `dbg.baddr` was somehow usable.

```
[0x7fba7338c100]> di*
f dbg.signal = 0
f dbg.sigpid = 0
f dbg.inbp = 0
f dbg.sigaddr = 0x0
f dbg.baddr = 0x5596721e4000
f dbg.pid = 4966
f dbg.tid = 4966
f dbg.uid = 1000
f dbg.gid = 1000
```

**Additional context**
Given the above output, I would expect something which works as follow:
```
[0x7fba7338c100]> db $Db+0x2488
[0x7fba7338c100]> db
0x5596721e6488 - 0x5596721e6489 1 --x sw break enabled valid cmd="" cond="" name="$Db+0x2488" module="/home/user/Downloads/cr4ckMe.bin"
```
I don't expect this feature request to be complicated as the variable's content just has to point to the already existing information contained in `di`.

**Comment by x0urc3** [comment]
- `$D` shows the current debug map base address. So you need to continue until main to get the base address for the text section
- However its still not usable due to a bug in `$D` #16224  that show the current debug map **end** base address.  
- maybe you can do
```
[0x55f0bd241df0]> di~baddr[1]
0x55f0bd23d000
[0x55f0bd241df0]> ?v `di~baddr[1]`+0xaa
0x55f0bd23d0aa
[0x55f0bd241df0]>
```
