### ISSUE TITLE
command: "=+" Segmentation fault

### ISSUE THREAD

**Issue by aar0nge** [radareorg/radare2#16214]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.1 23928 @ linux-x86-64 git.4.3.1-10-g1271d65 commit: 1271d653c7691047284a1de99d209972e3cee6d9 build: 2020-03-11__10:01:54

### Expected behavior
Handle input error
### Actual behavior
Segmentation fault

### Steps to reproduce the behavior 
$ r2 -
[0x00000000]> =+
Error: Missing '/'
Segmentation fault (core dumped)

### Additional Logs, screenshots, source-code,  configuration dump, ...
![image](https://user-images.githubusercontent.com/20163299/76677588-f4bdb180-660a-11ea-9060-2f93b9400845.png)

**Comment by radare** [comment]
cant reproduce. even with asan, can you submit a crashlog or something?
