### ISSUE TITLE
Show number of matches in realtime during `/m` search

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16264]
If you run `/m` command in radare2 on a big file it takes quite some time. But it shows nothing in the process apart from the current address:
```
[0x0000000]> /m
-- 0 8e6fe4
0x0051345
```
It would be awesome to print the current number of found signatures on the top in the realtime, something like that:
```
[0x0000000]> /m
-- 0 8e6fe4 [5 matches found]
0x0051345
```

**Comment by 08A** [comment]
@XVilka, do you have a example binary with your example?

**Comment by 08A** [comment]
If you want the update number to be like in the example, the function r_core_magic_at in 
libr/core/cmd_magic.c need to have different parameters. Indeed, we need to add parameter. And we count the global number of hit or the number inside the segment?

**Comment by 08A** [comment]
the simplest solution is (with global count):
```
diff --git a/libr/core/cmd_magic.c b/libr/core/cmd_magic.c
index facccbee3..2462b1a66 100644
--- a/libr/core/cmd_magic.c
+++ b/libr/core/cmd_magic.c
@@ -46,8 +46,8 @@ static int r_core_magic_at(RCore *core, const char *file, ut64 addr, int depth,
                }
        }
        if (((addr&7)==0) && ((addr&(7<<8))==0))
-               if (!json) {
-                       eprintf ("0x%08"PFMT64x"\r", addr);
+               if (!json) { // update search display
+                       eprintf ("0x%08" PFMT64x " [%d matches found]\r", addr, *hits);
                }
        if (file) {
                if (*file == ' ') file++;
```
example:
```
[0x0000000]> /m
-- 0 8e6fe4
0x0051345 [5 matches found]
```

**Comment by radare** [comment]
What about sending a PR?
