### ISSUE TITLE
Do not insert empty lines between switch cases

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16263]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86_64
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            | x86/64.
| r2 -v full output, **not truncated** (mandatory)     | **https://github.com/radareorg/radare2/commit/823ab26095aa11b0a30829c25fc63bfe33c2d736**

### Expected behavior

Do not insert emply lines between swtich cases

### Actual behavior

Inserts empty lines between switch cases

### Steps to reproduce the behavior 
```
r2 -AA /bin/ls
> Vp
<scroll>
```

![image](https://user-images.githubusercontent.com/203261/77137899-b57bde80-6aaa-11ea-9e4f-85b35c76a2f4.png)

**Comment by radare** [comment]
fixed in https://github.com/radareorg/radare2/issues/16263

**Comment by dennisschagt** [comment]
> fixed in #16263

That is the ID of this issue.
Actual PR at #16267.

**Comment by radare** [comment]
my pr is not 100% correct because now we have a tailing ':' at the end of the line
