### ISSUE TITLE
ood does not handle  iomap and fd properly

### ISSUE THREAD

**Issue by x0urc3** [radareorg/radare2#16283]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 23778 @ linux-x86-64 git.4.1.1-494-g4f853172a commit: 4f853172a82d180590b2827cf6f350c66b93e69f build: 2020-03-15__06:17:46

### Expected behavior
`ood` should remove old iomap and does not need to find old fd
### Actual behavior
- `ood` does not remove old iomap and print error message regarding old fd
- old iomap and old fd list kept increasing everytime `ood` is used 
- I could remove the old iomap using `om-`

### Steps to reproduce the behavior 
```
$> r2 -d /bin/ls
[0x7f43c4ced100]> om
 1 fd: 3 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx 
[0x7f43c4ced100]> ood
Unable to find filedescriptor 3
Unable to find filedescriptor 3
[0x7fe6788cb100]> om
 2 fd: 4 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx 
 1 fd: 3 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx 
[0x7fe6788cb100]> om-1
[0x7fe6788cb100]> om
 2 fd: 4 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx 
[0x7fe6788cb100]> 
```

**Comment by radare** [comment]
cant reproduce on mac, but found this other bug which is not taking 100% cpu but gets stuck in here

```
$ r2 -d rax2
= attach 90108 90108
bin.baddr 0x100000000
Using 0x100000000
asm.bits 64
Warning: r_bin_file_hash: file exceeds bin.hashlimit
 -- Long time no C
[0x1000594ca]> om
 1 fd: 3 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx
[0x1000594ca]> ood
EXC_SOFTWARE
fail to restore exception ports
= attach 90114 90114
File dbg:///Users/pancake/prg/radare2/binr/rax2/rax2  reopened in read-write mode
[0x100005000]> om
 2 fd: 4 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx
[0x100005000]> om-1
[0x100005000]> om
 2 fd: 4 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx
[0x100005000]> om-2
[0x100005000]> om
[0x100005000]> ood
(stuck forever here)
```
