### ISSUE TITLE
radare2 double-loads plugin libraries

### ISSUE THREAD

**Issue by imyxh** [radareorg/radare2#16281]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux on x86-64
| File format of the file you reverse (mandatory)      | all
| Architecture/bits of the file (mandatory)            | all
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 24044 @ linux-x86-64 git.4.3.1-95-g537a811f0 commit: 537a811f0fa6d39303cf91d729ef7868ced56a43 build: 2020-03-22__15:20:58

### Behavior

After installing both radare2 and r2ghidra-dec from Archlinux repositories, I found this:

```
$ r2 /bin/ls
Not loading library because it has already been loaded from somewhere else: '/usr/lib/radare2/4.3.1/core_ghidra.so'
```

Seems like that path is trying to be loaded twice:

```
$ R_DEBUG=1 r2 /bin/ls       
Cannot open directory '/usr/lib/radare2/4.3.1'
Cannot open directory '/usr/lib/radare2/4.3.1'
Cannot open directory '/usr/lib/radare2-extras/4.3.1'
Cannot open directory '/usr/lib/radare2-bindings/4.3.1'
USER CONFIG loaded from /home/imyxh/.config/radare2/radare2rc
```

Also, confirmed on a build straight from git, installed with sys/user.sh—but this time, because of a redundant symlink:

```
$ R_DEBUG=1 ~/bin/radare2 /bin/ls
Cannot open /home/imyxh/bin/prefix/radare2/lib/radare2/last
Cannot open /home/imyxh/bin/prefix/radare2/lib/radare2/4.4.0-git
Cannot open directory '/home/imyxh/bin/prefix/radare2/lib/radare2-extras/4.4.0-git'
Cannot open directory '/home/imyxh/bin/prefix/radare2/lib/radare2-bindings/4.4.0-git'
USER CONFIG loaded from /home/imyxh/.config/radare2/radare2rc

$ file ~/bin/prefix/radare2/lib/radare2/last 
/home/imyxh/bin/prefix/radare2/lib/radare2/last: symbolic link to 4.4.0-git
```

Not exactly sure why this is occurring. One relevant source file seems to be [libr/core/libs.c](https://github.com/radareorg/radare2/blob/master/libr/core/libs.c).

**Comment by radare** [comment]
fixed in my PR

**Comment by radare** [comment]
but can be improved
