### ISSUE TITLE
Fix OpenBSD failing tests

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16285]
See full log here
[radare2_r2r.v_openbsd.log.zip](https://github.com/radareorg/radare2/files/4368373/radare2_r2r.v_openbsd.log.zip)

**Comment by radare** [comment]
at least r2r.v is running fine :)

**Comment by XVilka** [comment]
Looks like fixed in https://github.com/radareorg/radare2/commit/91c58506e54519e11f0ec0acb1c09825522af38b
@thestr4ng3r

**Comment by thestr4ng3r** [comment]
Except for the gnu as tests we set to BROKEN, everything is fixed.

**Comment by radare** [comment]
The gnu ass should assemble a different instructionn like i said. Can you do the change?

**Comment by thestr4ng3r** [comment]
No, these two tests were explicitly about the instructions from #1167, so not sure what we should do about them. There are already tests with other instructions.

**Comment by XVilka** [comment]
Closing then.
