### ISSUE TITLE
unmatched  array length in core_java.c

### ISSUE THREAD

**Issue by aar0nge** [radareorg/radare2#16304]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | rradare2 4.3.1 23909 @ linux-x86-64 git.4.3.1-1-ge55661b commit: e55661bd4c229b9095982675709bdd52e1b4c068 build: 2020-03-22__22:18:20

### Expected behavior
Handle input error
### Actual behavior
seg fault

### Steps to reproduce the behavior 
$ r2 -
[0x00000000]> java 0
Segmentation fault (core dumped)

### Additional Logs, screenshots, source-code,  configuration dump, ...
![image](https://user-images.githubusercontent.com/20163299/77502165-0289f700-6e95-11ea-9e63-c1b0fa9d6039.png)

in `core_java.c`, `END_CMDS` not match the actual length in `JAVA_CMDS`

**Comment by radare** [comment]
send the pr with the fix please
