### ISSUE TITLE
Improve glibc version detection

### ISSUE THREAD

**Issue by x0urc3** [radareorg/radare2#16315]
- tcache feature was introduced in glibc > 2.25
- glibc version is required during runtime to correctly parse heap data structure
- Current detection will fail if version number is not included in filename 

https://github.com/radareorg/radare2/blob/80f59a7c5f87a15bdab3ad1945491d6d251087ef/libr/core/linux_heap_glibc.c#L42-L46

Thanks @XVilka  for pointing this out. Ref: https://benohead.com/blog/2015/01/28/linux-check-glibc-version/

**Comment by XVilka** [comment]
Related: https://github.com/radareorg/radare2/issues/8185

**Comment by s00kee** [comment]
Hi, I'm very new to open source but I'd like to give this a try as my first issue if it's ok. Thanks.

**Comment by koyaan** [comment]
It always can use improvements but i this particular code is gone now, so maybe close 
this issue? @trufae

**Comment by trufae** [comment]
Yup! Good work!
