### ISSUE TITLE
Retire JavaScript tests and remove them from the repository

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16314]
Now there is V and C r2r testsuite, no need for JavaScript anymore.
Also:
- Remove [`test/Attic`](https://github.com/radareorg/radare2/tree/master/test/Attic)
- Rename `test/new` just into `test/db` and rename irrelevant files
- Update [`test/README.md`](https://github.com/radareorg/radare2/blob/master/test/README.md) accordingly

**Comment by radare** [comment]
Can we stop adding obvious issues?

**Comment by XVilka** [comment]
It's not obvious for external contributors - notice the "good first issue" label.
