### ISSUE TITLE
Upgrade `r_getopt` implementation to optparse

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16322]
There are good portable `getopt()` implementations with a suitable license, maybe just to reuse them?
- https://github.com/skeeto/getopt
- https://github.com/skeeto/optparse

Way more powerful than the current implementation:

# Optparse

Optparse is a public domain, portable, reentrant, embeddable,
getopt-like option parser. It's a single header file and can be
trivially dropped into any project. It supports POSIX getopt option
strings, GNU-style long options, argument permutation, and subcommand
processing.

To get the implementation, define `OPTPARSE_IMPLEMENTATION` before
including `optparse.h`.

~~~c
#define OPTPARSE_IMPLEMENTATION
#include "optparse.h"
~~~

Optionally define `OPTPARSE_API` to control the API's visibility
and/or linkage (`static`, `__attribute__`, `__declspec`).

~~~c
#define OPTPARSE_API static
#include "optparse.h"
~~~

## Why not getopt()?

The POSIX getopt option parser has three fatal flaws. These flaws are
solved by Optparse.

1. The getopt parser state is stored entirely in global variables,
some of which are static and inaccessible. This means only one thread
can use getopt. It also means it's not possible to recursively parse
nested sub-arguments while in the middle of argument parsing. Optparse
fixes this by storing all state on a local struct.

2. The POSIX standard provides no way to properly reset the parser.
For portable code this means getopt is only good for one run, over one
argv with one option string. It also means subcommand options cannot
be reliably processed with getopt. Most implementations provide an
implementation-specific method to reset the parser, but this is not
portable. Optparse provides an `optparse_arg()` function for stepping
through non-option arguments, and parsing of options can continue
again at any time with a different option string. The Optparse struct
itself could be passed around to subcommand handlers for additional
subcommand option parsing. If a full parser reset is needed,
`optparse_init()` can be called again.

3. In getopt, error messages are printed to stderr. This can be
disabled with opterr, but the messages themselves are still
inaccessible. Optparse solves this by writing the error message to its
errmsg field, which can be printed to anywhere. The downside to
Optparse is that this error message will always be in English rather
than the current locale.

**Comment by radare** [comment]
Those assume argv is mutable

And we dont want different order of flags neither longopt. So better to kiss

**Comment by XVilka** [comment]
Sorry, no kissing amidst pandemic.
