### ISSUE TITLE
segfault with `tc struct`

### ISSUE THREAD

**Issue by hexagonal-sun** [radareorg/radare2#16336]
I found this one when writing the bug report for #16335 .

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x86_64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     |  radare2 4.3.1 0 @ linux-x86-64 git.4.3.1 commit: unknown build: 2020-03-20__16:02:58

### Expected behavior
No segfault

### Actual behavior
Segmentation fault.

### Steps to reproduce the behavior 
```
r2 -
tc struct
```

**Comment by radare** [comment]
its a stupid null deref, its easy to fix. anyone?

<img width="1251" alt="Screenshot 2020-03-29 at 13 18 30" src="https://user-images.githubusercontent.com/917142/77847765-ca99f100-71bf-11ea-8d27-94ba7bc66287.png">
