### ISSUE TITLE
o+ does not set maps writeable

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/radare2#16347]
![Screenshot from 2020-03-29 15-27-13](https://user-images.githubusercontent.com/1460997/77850315-f32ae680-71d1-11ea-8b7d-36e78d37fe3c.png)

The first `om` result (after `o+`) should be the same as the second (after `oo+`) and the first write should succeed.

**Comment by thestr4ng3r** [comment]
@kazarmy Since you are doing o commands, you might be interested in this.

**Comment by kazarmy** [comment]
Ok I'll have a look.
