### ISSUE TITLE
Forward type declaration support

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16345]
as long as Tenis is not defined this wont be parsed properly. but we can just assume this is a void* until the type is defined

```
[0x00000000]> "td struct Fuck { Tenis* loop; };"
<string>:1: error: bracket expected
<string>:1: error: '}' expected (got "Tenis")
<string>:1: error: declaration expected
[0x00000000]>
```

**Comment by thestr4ng3r** [comment]
You can use `"td struct Fuck { struct Tenis* loop; };"`

**Comment by radare** [comment]
Oh right ill try this approach for my ivar pr

**Comment by radare** [comment]
it works this way which makes sense because of C :P
