### ISSUE TITLE
unnamed struct named as 0 and no difference with struct and typedef

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16343]
```
pmb:core pancake$ r2 -
 -- Buy a Mac
[0x00000000]> "td typedef struct {int a;} Foo;"
[0x00000000]> ts
0
Foo
[0x00000000]> q
pmb:core pancake$ r2 -
 -- There's more than one way to skin a cat
[0x00000000]> "td typedef struct Anon{int a;} Foo;"
[0x00000000]> ts
Anon
Foo
[0x00000000]>
```

**Comment by radare** [comment]
cc @XVilka

**Comment by radare** [comment]
please @oxcabe or @XVilka can you pls fix this issue and add a test before 4.4? thanks!

**Comment by oxcabe** [comment]
> unnamed struct named as 0

This is necessary for the typedefs to work AFAIK, typedefs reference those dummy structs when used.

> no difference with struct and typedef

So... typedefs shouldn't be included in `ts` commands right?

**Comment by radare** [comment]
that '0' shouldnt be there, i think thats the only thing to fix here. because the typedef assigns the name already
