### ISSUE TITLE
I Can't Use A Saved Project

### ISSUE THREAD

**Issue by RHL120** [radareorg/radare2#16353]
I am new to Radare so this is probably my fault not Radare's.
To save a project I use Ps proejectname
but whenever I open a project with r2 -p projectname or Po project name (within Radare) I get
afb+: Cannot add basic block at 0x00001040
afB: Cannot find function to set bits at 0x00001040
afc: Cannot find function here
Missing function at 0x00001040
afb+: Cannot add basic block at 0x00001070
afb+: Cannot add basic block at 0x00001083
afb+: Cannot add basic block at 0x0000108f
afb+: Cannot add basic block at 0x00001098
afB: Cannot find function to set bits at 0x00001070
afc: Cannot find function here
afb+: Cannot add basic block at 0x000010a0
afb+: Cannot add basic block at 0x000010c4
afb+: Cannot add basic block at 0x000010d0
afb+: Cannot add basic block at 0x000010d8
afB: Cannot find function to set bits at 0x000010a0
afc: Cannot find function here
afb+: Cannot add basic block at 0x000010e0
afb+: Cannot add basic block at 0x000010ed
afb+: Cannot add basic block at 0x000010fb
afb+: Cannot add basic block at 0x00001108
afb+: Cannot add basic block at 0x00001120
afB: Cannot find function to set bits at 0x000010e0
afc: Cannot find function here
afb+: Cannot add basic block at 0x00001130
afB: Cannot find function to set bits at 0x00001130
afc: Cannot find function here
afb+: Cannot add basic block at 0x00001000
afb+: Cannot add basic block at 0x00001014
afb+: Cannot add basic block at 0x00001016
afB: Cannot find function to set bits at 0x00001000
afc: Cannot find function here
afb+: Cannot add basic block at 0x000011c0
afB: Cannot find function to set bits at 0x000011c0
afc: Cannot find function here
afb+: Cannot add basic block at 0x000011c8
afB: Cannot find function to set bits at 0x000011c8
afc: Cannot find function here
afb+: Cannot add basic block at 0x00001150
afb+: Cannot add basic block at 0x00001187
afb+: Cannot add basic block at 0x00001190
afb+: Cannot add basic block at 0x000011a6
afB: Cannot find function to set bits at 0x00001150
afc: Cannot find function here
Missing function at 0x00001150
Missing function at 0x00001150
Missing function at 0x00001150
afb+: Cannot add basic block at 0x00001139
afB: Cannot find function to set bits at 0x00001139
afc: Cannot find function here
afb+: Cannot add basic block at 0x00001030
afB: Cannot find function to set bits at 0x00001030
afc: Cannot find function here
No file to load bin from?
I try to run pdf but I got :
p: Cannot find function at 0x00001139
then I quit, reopened the project  and ran aa and pdf
but i got the same error
if I run afl I get  :
0x00001040    0 0            entry0
0x00001070    0 0            sym.deregister_tm_clones
0x000010a0    0 0            sym.register_tm_clones
0x000010e0    0 0            entry.fini0
0x00001130    0 0            entry.init0
0x00001000    0 0            sym._init
0x000011c0    0 0            sym.__libc_csu_fini
0x000011c8    0 0            sym._fini
0x00001150    0 0            sym.__libc_csu_init
0x00001139    0 0            main
0x00001030    0 0            sym.imp.puts
here is my project's rc file
[rc.txt](https://github.com/radareorg/radare2/files/4399568/rc.txt)
(it is a .txt because Github doesn't allow uploading files without an extention )  
my Radare Version
radare2 4.4.0-git 24135 @ linux-x86-64 git.4.3.1-142-g2c7ecc973
commit: 2c7ecc973633fc0bed0d0e71b58d2fae192d3b3d build: 2020-03-29__20:13:30
I am running Archlinux

**Comment by radare** [comment]
Yeah totally expected. Projects have been broken for years, if you want to help you are welcome to add tests and submit fixes

**Comment by trompetin17** [comment]
Hello, today I was reviewing what is the current problem about this, and I found something that I want to share.
Everything is about vars(e command) when the project load from file some properties load badly.
It looks like boolean and numbers, but what I found is not all properties just this:

cfg.fortunes (instead true load 1)
esil.stack.pattern (instead "0" load 0)
http.maxport (instead "9999" load 9999)
http.port (instead "9090" load 9090)
io.pcache.read (instead false load 0)
io.pcache.write (instead false load 0)
scr.interactive (instead true load 1)
scr.prompt (instead true load 1)

You can reproduce this just doing this
- Open a file like "r2 yourfile" then "Ps yourname"
- Close radare2
- Open once again the file "r2 yourfile", use the command "ej", copy the values and paste in http://www.jsondiff.com/
- Use command "px" and you see binaries
- Load the project "Po yourname", use the command "ej", copy the new values and paste in
http://www.jsondiff.com/
- Once again use "px" and now you only see "ffffff" "invalid
- Then compare and you can see what I found

I'm going to examine what is doing this variable inside the code. but @radare is you can give a hint I could help with a patch.

Thx

**Comment by trompetin17** [comment]
> 0x00001040
@RHL120 could you open your file rc (look in P? the path for projects and loop up over there) with text editor
And tell me if you see something like
"f fcn.0x00001040 0 0x00001040"???

**Comment by trompetin17** [comment]
Ok digging my RS file I found some "f fn.xxxxx 0 0xxxxxx"
to show you and example

_"f fcn.01423af4 0 0x01423af4"
"af+ 0x01423af4 fcn.01423af4 f n"
afB 64 @ 0x01423af4
afc arm64 @ 0x01423af4
afvr x2 arg3 int64_t @ 0x1423ab8
afvr x1 arg2 int64_t @ 0x1423ab8
afvr x0 arg1 int64_t @ 0x1423ab8
afS 0 @ 0x1423af4_
<img width="665" alt="Screen Shot 2020-04-12 at 12 03 59 AM" src="https://user-images.githubusercontent.com/5893641/79061025-5cd6d600-7c51-11ea-9381-0ab73d2e963d.png">

but using 
_s 0x01423af4
s afi_
<img width="521" alt="Screen Shot 2020-04-12 at 12 07 01 AM" src="https://user-images.githubusercontent.com/5893641/79061047-8e4fa180-7c51-11ea-9e8e-5d824c0d8a34.png">

so no information about 0x01423af4 but when you use afl* is setting over there but with 0 in size

Any Ideas what could be?
