### ISSUE TITLE
DEX loading is slow

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16387]
Optimizations to speedup the dex loading:

* [ ] Use r_buf_data once and then r_read APIs to avoid all the rbuf backend messing and unnecessary memory copies.
* [ ] Cache the result of r_buf_data() to speedup consecutive calls
* [ ] Use buffer backend instead of the io one for RBuffer from RIO
* [ ] Use the RBuffer everywhere. maybe worth adding an uleb methods in rbuffer for dwarf and dex
* [ ] Avoid strdup() in getstr() this duplicates lot of elements in memory

Difference is this patch:
```
--- a/libr/bin/bin.c
+++ b/libr/bin/bin.c
@@ -280,7 +280,8 @@ R_API bool r_bin_open_buf(RBin *bin, RBuffer *buf, RBinOptions *opt) {
                }
        }
        if (!bf) {
-               bf = r_bin_file_new_from_buffer (bin, bin->file, buf, bin->rawstr,
+               RBuffer *b = r_buf_new_slurp (bin->file);
+               bf = r_bin_file_new_from_buffer (bin, bin->file, b, bin->rawstr,
                        opt->baseaddr, opt->loadaddr, opt->fd, opt->pluginname);
                if (!bf) {
                        return false;
```

<img width="328" alt="Screenshot 2020-03-31 at 23 41 01" src="https://user-images.githubusercontent.com/917142/78077752-3d19f500-73a9-11ea-9fd0-beac8f7bc400.png">

**Comment by radare** [comment]
This is because the IO buffer backend plugin is 2x slower than the byte buffer one and the whole parsing depends on RBuffer. 20s is still too much and the dex parser should do bigger reads and then r_read endian APIs instead of depending so much with RBuffer.

**Comment by radare** [comment]
Another optimization reduces the time to 14s

```
$ git diff buf.c
diff --git a/libr/util/buf.c b/libr/util/buf.c
index 71e1ad632..20a69e64a 100644
--- a/libr/util/buf.c
+++ b/libr/util/buf.c
@@ -65,6 +65,9 @@ static ut8 *get_whole_buf(RBuffer *b, ut64 *sz) {
        if (bsz == UT64_MAX) {
                return NULL;
        }
+       if (b->whole_buf) {
+               return b->whole_buf;
+       }
        free (b->whole_buf);
        b->whole_buf = R_NEWS (ut8, bsz);
        if (!b->whole_buf) {
```

**Comment by radare** [comment]
https://github.com/radareorg/radare2/pull/16388

**Comment by ret2libc** [comment]
@radare could you provide the "classes.dex" you are testing?

**Comment by radare** [comment]
[classes.dex.zip](https://github.com/radareorg/radare2/files/4414050/classes.dex.zip)

**Comment by radare** [comment]
This is fixed now

**Comment by radare** [comment]
Closing this issue because its fixed in the pr
