### ISSUE TITLE
Add GPG/RSA crypto finding commands

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16393]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Darwin pmb.lan 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
| Architecture/bits of the file (mandatory)            | any
| r2 -v full output, **not truncated** (mandatory)     | 4.4.0-git aka 4.3.1-178-gdc790f525 commit 25802

### Expected behavior

/cg exists

### Actual behavior

/cg doesnt exist, its not a valid command

### Steps to reproduce the behavior 

Right now the only way to search for GPG keys is using /m or pm

*  See `libr/magic/d/default/gpg`

Ideally we should be able to search for those patterns using a core / command, instead of depending on libmagic for this. same goes for SSL certificates, PEMs, etc

**Comment by sylvainpelissier** [comment]
Do you have practical use cases or example for this one ?

**Comment by trufae** [comment]
@sylvainpelissier Scaning memory for private keys for example.

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/radare2/pull/18949
