### ISSUE TITLE
Wrong size of jump table error when comparing with memory

### ISSUE THREAD

**Issue by bin2415** [radareorg/radare2#16399]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian, Ubuntu 18.04, amd64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23257 @ linux-x86-64 git.3.9.0-297-g619099582 commit: 61909958287077012115341a99ca71dd0f457ef8 build: 2019-11-01__22:11:01

### Expected behavior

```
  40fc53:       48 8b 45 d8             mov    -0x28(%rbp),%rax
  40fc57:       0f b6 00                movzbl (%rax),%eax
  40fc5a:       0f be c0                movsbl %al,%eax
  40fc5d:       89 45 90                mov    %eax,-0x70(%rbp)
  40fc60:       83 7d 90 7a             cmpl   $0x7a,-0x70(%rbp)
  40fc64:       0f 87 54 1c 00 00       ja     4118be <__strftime_internal+0x1f45>
  40fc6a:       8b 45 90                mov    -0x70(%rbp),%eax
  40fc6d:       48 8b 04 c5 e8 67 41    mov    0x4167e8(,%rax,8),%rax
  40fc74:       00
  40fc75:       ff e0                   jmpq   *%rax
```

The size of this jump table is 0x7a.
### Actual behavior

However, radare2 solves that the size is 0x5.

I checked the source code and found that radare2 deems the size is `op.refptr` not `op.val` [here](https://github.com/radareorg/radare2/blob/master/libr/anal/jmptbl.c#L178).

### Steps to reproduce the behavior 

The binary is attached:
[date.strip.zip](https://github.com/radareorg/radare2/files/4418502/date.strip.zip)

And my command is `aaa`.

**Comment by bilboed** [comment]
Seems to detect it fine with radare2 4.2.1 0 @ linux-x86-64 git.4.2.1

```
│           0x0040fc53      488b45d8       mov rax, qword [var_28h]
│           0x0040fc57      0fb600         movzx eax, byte [rax]
│           0x0040fc5a      0fbec0         movsx eax, al
│           0x0040fc5d      894590         mov dword [var_70h], eax
│           0x0040fc60      837d907a       cmp dword [var_70h], 0x7a
│       ┌─< 0x0040fc64      0f87541c0000   ja case.0x40fc75.1
│       │   0x0040fc6a      8b4590         mov eax, dword [var_70h]
│       │   0x0040fc6d      488b04c5e867.  mov rax, qword [rax*8 + 0x4167e8]
│       │   ;-- switch
│       │   0x0040fc75      ffe0           jmp rax                     ; switch table (123 cases) at 0x4167e8
│       │   ; CODE XREF from fcn.0040f979 @ 0x40fc75
│       │   ;-- case 37:                                               ; from 0x40fc75
│       │   0x0040fc77      837dd000       cmp dword [var_30h], 0
│      ┌──< 0x0040fc7b      0f85fa1b0000   jne 0x41187b
│      ││   0x0040fc81      48c78540ffff.  mov qword [var_c0h], 1
│      ││   0x0040fc8c      b800000000     mov eax, 0

```

**Comment by bin2415** [comment]
The newest version works. Thanks, I'll switch to newest version.

**Comment by radare** [comment]
Please dont use debian packages for r2. 4.2 is 3 month old. There are tons of fixes and changes since that release. Next week i’ll release 4.4. Please test it from git.

**Comment by bin2415** [comment]
Yeah, I am using 4.4.0 now. Thanks!
