### ISSUE TITLE
Do emscripten JS/WASM builds in CI

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16407]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git

### Steps to implement

```
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
git clone https://github.com/radareorg/radare2
cd radare2
sys/emscripten.sh
```

See https://github.com/radareorg/radare2/pull/16406

**Comment by radare** [comment]
Already done. but we are not publishing the binr/*/*.js yet. will be good to do so. anyone?

**Comment by XVilka** [comment]
Probably worth to move to GitHub Actions too

**Comment by radare** [comment]
@XVilka can you do that change before sunday?

**Comment by radare** [comment]
right now: https://travis-ci.com/github/radareorg/radare2/jobs/318387799
i would like to get those .wasm and .js zipped and uploaded in gh releases. maybe this way we will get r2.js with xterm.js working at some point..

**Comment by XVilka** [comment]
Fixed in https://github.com/radareorg/radare2/commit/00a30c943a79d2da265f11d18cb05b9801c3a430

It's probably better to move this into GitHub Actions

**Comment by radare** [comment]
Yes but as i said it was not ready to mwrge and it is not uploading anything
