### ISSUE TITLE
Radare2 doesn't detect all functions for ELF-MIPS malware sample

### ISSUE THREAD

**Issue by DanusMinimus** [radareorg/radare2#16413]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF 
| Architecture/bits of the file (mandatory)            | MIPS
|$ r2 Mozi_unpacked.bin 

[0x00400260]> aaa

[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Finding xrefs in noncode section with anal.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00400000 to 0x00437680 (aav)
[x] 0x00400000-0x00437680 in 0x400000-0x437680 (aav)
[x] Emulate code to find computed references (aae)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.

[0x00400260]> afl
0x00400260    2 100          entry0
0x004000b8    1 104          fcn.004000b8
0x0042c924    1 56           fcn.0042c924
0x00428384   16 976  -> 332  fcn.00428384
0x00431314    1 32           fcn.00431314

### Expected behavior
Ida produces about 750 functions so I'd assume the same amount should be produced in radare2
### Actual behavior
5 Functions are produced 
### Steps to reproduce the behavior 
Download attached zip file and analyze file mozi_unpacked.bin. 
$ r2 Mozi_unpacked.bin
[0x00400260]> aaa
[0x00400260]> afl

**Comment by DanusMinimus** [comment]
[Mozi.zip](https://github.com/radareorg/radare2/files/4431319/Mozi.zip)

**Comment by radare** [comment]
Can we ship this binary in our testsuite? i have opened a PR fixing the issue

**Comment by DanusMinimus** [comment]
This is a malware sample, so watch out with it.
