### ISSUE TITLE
Analyzing with `aaa` hangs at `Check for vtables` for small binary

### ISSUE THREAD

**Issue by mohe2015** [radareorg/radare2#16411]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 24144 @ linux-x86-64 git.4.3.1-189-g0ab6296238 commit: 0ab6296238cc0f0bcbcc27901ea2fe8ec60942aa build: 2020-04-02__17:41:43

### Expected behavior

Analyzing doesn't hang

### Actual behavior

Analyzing hangs (probably in an infinite loop) at `Check for vtables`

### Steps to reproduce the behavior 

- [out.elf.zip](https://github.com/radareorg/radare2/files/4422897/out.elf.zip)
- Just run `aaa`

### Notes

This is a binary from an assembler I'm writing so it's probably not completely following the specification. (Yes, I'm insane)

**Comment by mohe2015** [comment]
I found the issue. It's basically a parser differential attack.
[out.working.elf.zip](https://github.com/radareorg/radare2/files/4423349/out.working.elf.zip)
[out.nonworking.elf.zip](https://github.com/radareorg/radare2/files/4423350/out.nonworking.elf.zip)
```
readelf -a out.working.elf
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 1] .text             PROGBITS         0000000000401000  00001000
       000000000000004d  0000000000000000  AX       0     0     1
  [ 5] .rodata           PROGBITS         0000000000402000  00002000
       0000000000000007  0000000000000000   A       0     0     1
```
vs
```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 1] .text             PROGBITS         0000000000000000  00001000
       000000000000004d  0000000000000000  AX       0     0     1
  [ 5] .rodata           PROGBITS         0000000000000000  00002000
       0000000000000007  0000000000000000   A       0     0     1
```
So the address of the section header is invalid.
This is the only difference of the binaries.
```
radiff2 out.working.elf out.nonworking.elf
0x00000101 1040 => 0000 0x00000101
0x00000201 2040 => 0000 0x00000201
```
But `r2 -c 'aaa' -Q out.nonworking.elf` hangs at:
```
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[ ] Check for vtables
```
and `r2 -c 'aaa' -Q out.working.elf` finishes more or less instantly.

**Comment by XVilka** [comment]
It is fixed now. Please recheck @mohe2015
