### ISSUE TITLE
abr - anal block registers

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16429]
The purpose of this new command proposal is the following:

- every RAnalBlock store an RRegArena

So we can swap it when doing recursive emulation

- add a command to manually get/set the register values in a specific basic block
- add another command to propagate the values to the rest of bbs

related to the current code we use in the anal graph with esil info

feedback/ideas on this? cc @mrmacete @thestr4ng3r @condret

**Comment by radare** [comment]
ref  https://github.com/radareorg/radare2/pull/6110

**Comment by trufae** [comment]
This is done with the "abe" command introduced in 5.9.0
