### ISSUE TITLE
Make CI fast again

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16421]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 17284 @ darwin-x86-64

### Expected behavior

wait about 10 minutes to determine if we can merge a PR

### Actual behavior

wait > 2h, even more if there are more PRs open

### Steps to reproduce the behavior 

Create a PR, click on the travis results and see how long it takes

**Comment by XVilka** [comment]
AppVeyor now faster - disabled unnecessary tests.

**Comment by XVilka** [comment]
Fixed now.
