### ISSUE TITLE
Debugger broken on OpenBSD.

### ISSUE THREAD

**Issue by vext01** [radareorg/radare2#16432]
### Work environment

 * OpenBSD-current amd64
 * ELF

```
radare2 4.4.0-git 24204 @ openbsd-x86-64 git.4.3.1-206-g38b8d5929
commit: 38b8d5929d1855e7ca6b5b82956c03b46dd07eef build: 2020-04-05__22:02:03
```

### Expected behavior

```
$ r2 -d /tmp/a.out
```

Should open debug session for the binary.

### Actual behavior

```
Process with PID 15528 started...
Process with PID 59532 started...
[w] Cannot open 'dbg:///tmp/a.out' for writing.
```

and exits.

Also tried `ood`:

```
$ r2 /tmp/a.out   
 -- Setup dbg.fpregs to true to visualize the fpu registers in the debugger view.
[0x00001000]> ood
Process with PID 62226 started...
Process with PID 35393 started...
r_core_file_reopen: Cannot reopen file: dbg:///tmp/a.out  with perms 0x7, attempting to open read-only.
[0x00000000]> db main
Cannot place a breakpoint on 0x00001340 unmapped memory.See e? dbg.bpinmaps
```

Also found this seg:
```
$ r2 -                        
 -- This is fine.
[0x00000000]> ood /tmp/a.out
Cannot debug file (malloc://512) with permissions set to 0x7.
Reopening the original file in read-only mode.
zsh: segmentation fault (core dumped)  r2 -
```

All of these behaviours seem to work on Debian, so I assume this is OpenBSD specific.

Thanks

**Comment by radare** [comment]
Try r2 -d ls

**Comment by vext01** [comment]
```
$ r2 -d ls
Process with PID 58801 started...
Process with PID 96584 started...
[w] Cannot open 'dbg:///bin/ls' for writing.
$ r2 -d /bin/ls
Process with PID 88509 started...
Process with PID 42093 started...
[w] Cannot open 'dbg:///bin/ls' for writing.
```

**Comment by radare** [comment]
i can repro. the thing is that r2 -d pid works as expected. what is failing is the fork+ptraceme function. i tried disabling the ptrace-wrap as well as reverting the last commits related to this function without any change.

i wonder if this issue affects netbsd and freebsd too :?

**Comment by radare** [comment]
can you help us find the commit (or r2 version) where this stopped to work?

**Comment by radare** [comment]
im going back in time  (until 2018) and i cant find a single commit that works wtf. so i assume is something related with OpenBSD. btw im testing on openbsd 6.3

**Comment by vext01** [comment]
Check it out:
```diff
--- a/libr/io/p/io_ptrace.c
+++ b/libr/io/p/io_ptrace.c
@@ -216,16 +216,7 @@ static RIODesc *__open(RIO *io, const char *file, int rw, int mode) {
 #ifdef __ANDROID__
                        eprintf ("ptrace_attach: Operation not permitted\n");
 #else
-                       switch (errno) {
-                       case EPERM:
-                               ret = pid;
-                               eprintf ("ptrace_attach: Operation not permitted\n");
-                               break;
-                       case EINVAL:
-                               perror ("ptrace: Cannot attach");
-                               eprintf ("ERRNO: %d (EINVAL)\n", errno);
-                               break;
-                       }
+            eprintf ("ptrace_attach: %s\n", strerror(errno));
 #endif
                        return NULL;
                } else if (__waitpid (pid)) {
```

```
$ ./inst/bin/r2 -d a.out 
Process with PID 30802 started...
ptrace_attach: Device busy
Process with PID 25646 started...
ptrace_attach: Device busy
[w] Cannot open 'dbg://./a.out' for writing.
```

so `ptrace(2)` is erroring with `EBUSY`.

Man page says:
```
     [EBUSY]
           •   PT_ATTACH was attempted on a process that was already being
               traced.
           •   A request attempted to manipulate a process that was being
               traced by some process other than the one making the request.
           •   A request (other than PT_ATTACH) specified a process that
               wasn't stopped and waited for.
```

## Using gdb to look at ptrace(2) args

(fresh run)

```
Thread 1 hit Breakpoint 1, r_io_ptrace (io=0x39f6c3a9000, request=927, pid=-54722560, 
    addr=0x7f7fffff9aa0, data=7) at io.c:618
618     R_API long r_io_ptrace(RIO *io, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
(gdb) n
627             return ptrace (request, pid, addr, data);
(gdb) p request
$1 = 9
(gdb) p pid
$2 = 42351
(gdb) p addr
$3 = (void *) 0x0
(gdb) p data
$4 = 0
```

```
$ ps -p 42351
  PID TT  STAT        TIME COMMAND
42351 p4  TX       0:00.00 ./a.out
```

```
$  grep PT_ATTACH /usr/include/sys/ptrace.h
#define PT_ATTACH       9       /* attach to running process */
```

Do you see anything wrong?

**Comment by vext01** [comment]
Here's the permission checking code in the kernel:
https://github.com/openbsd/src/blob/15eef8140673a1d26e3b3703d4a0f2551d7c7ad6/sys/kern/sys_process.c#L334-L410

**Comment by vext01** [comment]
And here's a `pstree` snippet showing the relationship between r2 and the process to be traced:
```
 | \-+- 85038 edd /usr/X11R6/bin/xterm
 |   \-+= 32994 edd zsh
 |     \-+= 37950 edd egdb ./inst/bin/r2
 |       \-+= 33678 edd /home/edd/source/radare2/inst/bin/r2 -d a.out (radare2)
 |         \--- 69649 edd ./a.out
```

`a.out` does not appear anywhere else in the output...

**Comment by radare** [comment]
Do the child calls pt attach? Because i think so by adding printfs the other day.

**Comment by radare** [comment]
I also tried without the ptrace wrapper and same issue

**Comment by vext01** [comment]
> Do the child calls pt attach?

Not sure what you mean.

**Comment by radare** [comment]
See the configure flag. Its enabled by default. Which makes r2 use a worker thread to communicate with the child.

**Comment by vext01** [comment]
> See the configure flag.

I think you are talking about `--without-ptrace-wrap`.

It seems this is the default on OpenBSD (the end of configure says `USE_PTRACE_WRAP = 0`). Passing `--with-ptrace-wrap` doesn't turn it on either. So it's **always** disabled on OpenBSD.



When I said:
>  Not sure what you mean.

This was in response to:
>  Do the child calls pt attach?

Do you mean: does the child process use `PT_ATTACH`?

No. The child is just a simple piece of asm compiled with gcc:
```
.intel_syntax noprefix
.global main

main:
    mov rax, 0x666
    ret
```

I also tried some C:
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int
main(int argc, char **argv)
{
    sleep(1000);
    sleep(1000);
    sleep(1000);
    sleep(1000);
    return (EXIT_SUCCESS);
}
```

I thought perhaps it might be to do with the child being short lived, hence all the sleeps :P 

That's a red herring.

**Comment by radare** [comment]
> On 9 Apr 2020, at 10:58, Edd Barrett <notifications@github.com> wrote:
> 
> 
> See the configure flag.
> 
> I think you are talking about --without-ptrace-wrap.
> 
> It seems this is the default on OpenBSD (the end of configure says USE_PTRACE_WRAP = 0). Passing --with-ptrace-wrap doesn't turn it on either. So it's always disabled on OpenBSD.
> 
> When I said:
> 
> Not sure what you mean.
> 
> 
this is an issue, it should be 1. im hardcoding this and testing to verify. will be good to test on netbsd and freebsd too
> This was in response to:
> 
> Do the child calls pt attach?
> 
> Do you mean: does the child process use PT_ATTACH?
> 
> 

it's r2 who forks and must call ptrace(PT_ATTACH) before calling execve to run the executable
> No. The child is just a simple piece of asm compiled with gcc:
> 
well just try 'ls' like we all do for now, and same issue

**Comment by radare** [comment]
i have a workaround.. seems to work fine here.. but maybe worth merging if its not breaking anything. comments in here @thestr4ng3r ? will be good to test on freebsd and netbsd too, any volunteer with some time?

![Screenshot 2020-04-09 at 18 53 16](https://user-images.githubusercontent.com/917142/78920276-6fa3ac00-7a93-11ea-8cce-9c16c22537fa.png)

**Comment by radare** [comment]
see https://github.com/radareorg/radare2/pull/16505

**Comment by thestr4ng3r** [comment]
Will check this around the weekend when I have time. I have freebsd and openbsd set up locally to test.

Actually I think with the new r2r we should be able to run debug tests in CI for *bsd.

**Comment by thestr4ng3r** [comment]
Btw the reason ptrace-wrap is not enabled on OpenBSD is that it is Linux-specific. *BSD don't seem to have the limitation that this fixes.

**Comment by thestr4ng3r** [comment]
Now there is another issue:
![Screenshot from 2020-04-10 12-31-24](https://user-images.githubusercontent.com/1460997/78984700-3452bd00-7b27-11ea-8d18-4224d14b74ae.png)
But stepping and io seems to work fine.

**Comment by vext01** [comment]
Hi,

Seems that fix gets us somewhere. On OpenBSD-current/amd64 I get the same kind of thing as @thestr4ng3r:
```
arrakis:radare2> ./inst/bin/r2 -d ls
Process with PID 17731 started...
= attach 17731 17731
Could not get memory map: Operation not permitted
Could not get memory map: Operation not permitted
asm.bits 64
Could not get memory map: Operation not permitted
Warning: r_bin_file_hash: file exceeds bin.hashlimit
 -- Error: cannot yank negative sleep
[0xfc19e60c000]> 
```

i.e. some warnings, but stepping over the binary and the reported register values look ok to me at a glance.

**Comment by thestr4ng3r** [comment]
Follow-up: #16525

**Comment by vext01** [comment]
Would it be worth adding a test so that this can regress in the future?

**Comment by radare** [comment]
Yes but we should ensure the suite runs on openbsd ci too
