### ISSUE TITLE
Make the distinction between assembly and disassembly plugins clearer

### ISSUE THREAD

**Issue by wizeman** [radareorg/radare2#16450]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | NixOS x86 64-bit
| File format of the file you reverse (mandatory)      | None
| Architecture/bits of the file (mandatory)            | x86/16 but other bit modes are broken too
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.1 0 @ linux-x86-64 git.4.3.1 commit: HEAD build: 1970-01-01__00:00:01
### Expected behavior

```
$ rasm2 -a x86 -b 16 -d 31c0
xor ax, ax
$ rasm2 -a x86.as -b 16 -d 31c0
xor ax, ax
$ rasm2 -a x86.nz -b 16 -d 31c0
xor ax, ax
```

### Actual behavior
```
$ rasm2 -a x86 -b 16 -d 31c0
xor ax, ax
$ rasm2 -a x86.as -b 16 -d 31c0

$ rasm2 -a x86.nz -b 16 -d 31c0

```

### Steps to reproduce the behavior 

See above.

Note that 32-bit and 64-bit modes are broken too.

**Comment by XVilka** [comment]
Because they are assembler plugins, not disassembler plugins. But maybe we can indicate it better somehow.

**Comment by imyxh** [comment]
Idea: we change the checks involving r_asm_use() in [rasm2.c](https://github.com/radareorg/radare2/blob/dcbb114a9d05300a5f5268e5417810d7d6f3b572/libr/main/rasm2.c#L682) to first check the return value of r_asm_use(), and if it is true, we further check that we have either `as->disassemble` or `as->assemble` depending on if `dis` (the flag for -d and -D) is set or not.

**Comment by radare** [comment]
Just check rasm2 -L, its clear there
