### ISSUE TITLE
Rename asm.sysz into asm.s390x

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16478]
It's basically the same thing, and for consistency i think s390x makes more sense

```
        { "systemz", CS_ARCH_SYSZ, CS_MODE_BIG_ENDIAN },
        { "sysz", CS_ARCH_SYSZ, CS_MODE_BIG_ENDIAN },
        { "s390x", CS_ARCH_SYSZ, CS_MODE_BIG_ENDIAN },
```

![IMAGE 2020-04-08 11:23:42](https://user-images.githubusercontent.com/917142/78767833-68917680-798b-11ea-98e5-f52cd3d06a23.jpg)
![IMAGE 2020-04-08 11:23:46](https://user-images.githubusercontent.com/917142/78767856-6af3d080-798b-11ea-8cd0-43be4c5b796a.jpg)

**Comment by radare** [comment]
uhm maybe we should just keep it as sysz, and use asm.cpu to select the model of CPU from IBM. capstone is really broken, so nobody will notice, and i should find some time to get linux/s390x emulator for local development at some point

**Comment by XVilka** [comment]
Yes, lets keep sysz and use the a variant selection.
