### ISSUE TITLE
iD command doesn't accept rust lang

### ISSUE THREAD

**Issue by pelijah** [radareorg/radare2#16489]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | any
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 24258 @ windows-x86-64 git.4.0.0-951-g60ee0daa9 commit: 60ee0daa9113eac731388d2316faaea9c64bb921 build: 08.04.2020__23:58:09,3

### Expected behavior
Command returns the result of demangling of the provided name.

### Actual behavior
Command returns list of supported languages which includes `rust`.

### Steps to reproduce the behavior 
```
[0x00000000]> iD rust blahblahblah
c++
java
objc
swift
dlang
msvc
rust
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

As you can see here https://github.com/radareorg/radare2/blob/master/libr/core/cmd_info.c#L106-L111 there are no even handler for `R_BIN_NM_RUST`

**Comment by radare** [comment]
Can you make a PR?
