### ISSUE TITLE
Build all radare2 plugins weekly in the cronjob of GitHub Actions

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16535]
To check if something is broken, we can set the job every few days or weekly, like Coverity one.

**Comment by radare** [comment]
Thsi is r2extras

**Comment by XVilka** [comment]
@radare no, extras fires only on the change in the extras. This one should reflect ongoing radare2 changes and check if all plugins are compatible still.

**Comment by ret2libc** [comment]
I doubt I'm gonna be able to do it for 4.5.0, moving already to 4.6.0

**Comment by ret2libc** [comment]
I will be able to do this for next release, it's already in plan. Also, this is done on the `release-*` branches, so it's already something.

**Comment by ret2libc** [comment]
In theory this should be done, since the merge of #17355 . I'm going to close this once I see it working. https://github.com/radareorg/radare2/actions?query=workflow%3ACI+event%3Aschedule should list something in next days. I'll keep an eye on this and close if everything works right.

**Comment by ret2libc** [comment]
Ok, looks like this ran correctly. https://github.com/radareorg/radare2/actions?query=workflow%3ACI+event%3Aschedule There are problems with the build-static build, but everything runs. Closing.
