### ISSUE TITLE
Only the first function is displayed among symbols of imported DLL on debug mode

### ISSUE THREAD

**Issue by 0xballistics** [radareorg/radare2#16531]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
OS/arch/bits (mandatory)                             | Windows 10 64-bit
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.1 6 @ windows-x86-64 git.4.3.1 commit: 54ac837b5503f10f91e2069ac357791f7a3e635a build: Fri 03/06/2020__15:52:24.93

### Expected behavior
When "vulserver.exe" file is opened with -d modifier (radare2.exe -d .\vulnserver.exe) and analyzed (aaa):
All symbols of  ws2_32.dll appears in the list when using "is" from the radare2 command prompt.
All imported functions from ws2_32.dll are displayed when using "ii" from the radare2 command prompt.
Imported functions (ws2_32.dll):
WSACleanup
WSAGetLastError
WSAStartup
accept
bind
closesocket
freeaddrinfo
getaddrinfo
htons
inet_ntoa
listen
recv
send
socket

### Actual behavior
Only the first function of ws2_32.dll (WSACleanup) is listed in imported functions. 

### Steps to reproduce the behavior 
Extract "vulnserver.exe" and "essfunc.dll" into a directory.
Open "vulnserver.exe" with radare2.
Execute analysis (aaa).
List imports (ii)
List symbols (is)

### Additional Logs, screenshots, source-code,  configuration dump, ...
Binaries: 
[vulnserver.zip](https://github.com/radareorg/radare2/files/4465009/vulnserver.zip)

Screenshot of "is" (truncated)
![Screenshot of is (truncated)](https://user-images.githubusercontent.com/50373525/79049890-f0e37600-7c2e-11ea-84ec-84592500bd28.png)
Screenshot of "ii"
![Screenshot of ii](https://user-images.githubusercontent.com/50373525/79049909-12446200-7c2f-11ea-99b3-583443417d18.png)
Original imports (CFF Explorer)
![Original imports (CFF Explorer)](https://user-images.githubusercontent.com/50373525/79049980-a6aec480-7c2f-11ea-8b0f-e0019f9aeda8.png)

**Comment by sanguinawer** [comment]
I'm looking at this issue, can confirm only hapend on debug mode.
Problem come into r_buf_read_at, on debug mode the readed result is incorrect , possible issue with FD.

**Comment by radare** [comment]
It is reading from disk or memory?
