### ISSUE TITLE
Missing strings on iOS binary with izz

### ISSUE THREAD

**Issue by federicodotta** [radareorg/radare2#16543]
### Work environment
OS/arch/bits (mandatory) : Arch Linux x86_64
File format of the file you reverse (mandatory): Mach-O 64-bit arm64 executable
Architecture/bits of the file (mandatory): Arm64
r2 -v full output: radare2 4.3.1 0 @ linux-x86-64 git.4.3.1/ commit: unknown build: 2020-03-20__16:02:58

### Expected behavior
izz find all the strings of the binary

### Actual behavior
izz missed the 'encryptPassword:' string: 
![r24](https://user-images.githubusercontent.com/1651767/79066866-5c732500-7cbb-11ea-8722-2fb3640d1251.png)
that is present both in "strings" command:
![r26](https://user-images.githubusercontent.com/1651767/79066779-c50dd200-7cba-11ea-96af-6eeb426ce107.png)
and is shown also in the binary:
![R21](https://user-images.githubusercontent.com/1651767/79066788-ce973a00-7cba-11ea-82af-e628bccf0b74.png)
![r23](https://user-images.githubusercontent.com/1651767/79066883-71e84f00-7cbb-11ea-8891-534473e90473.png)

The string has not strange encoding. Is a simple ASCII string.

### Steps to reproduce the behavior 

-> r2 ipa://DemoHITB.ipa
-> aaa
-> e emu.str=true
-> aaa
-> izz~encryptPassword  # String 'encryptPassword:' is missing
1638 0x0004d016 0x10004d016 29  30                             ascii   +[LoginUtil encryptPassword:]
2409 0x00056ef0 0x100056ef0 29  30                             ascii   +[LoginUtil encryptPassword:]
-> s 0x100012fc4  # In the next three instruction you can see missing string 'encryptPassword:'
-> s 0x100029749  # In this location there is the missing string. The string view fail to print it correctly:
![r22](https://user-images.githubusercontent.com/1651767/79066111-7c074f00-7cb5-11ea-8a08-75de5157e2d0.png)
but it is a simple string, as show in the HEX view:
![r23](https://user-images.githubusercontent.com/1651767/79066737-92fc7000-7cba-11ea-83c3-92143e920efe.png)

### Additional Logs, screenshots, source-code,  configuration dump, ...

[ipaBugRadare.zip](https://github.com/radareorg/radare2/files/4466122/ipaBugRadare.zip)

**Comment by radare** [comment]
this is not a string, its a method name. you can list it with the ic command.

symbol sections is skipped from the iz strings command.

**Comment by federicodotta** [comment]
Uhmm... I might be wrong but it should be a string. ObjC does not invoke methods directly but uses *objc_msgSend* method, supplying a string that contains the method name as second argument (in my example that string was *encryptPassword:*)

Thank you for your great work!

**Comment by radare** [comment]
yes, it is a string, in the region that contains the class and method names. which r2 ignores because otherwise the amount of foound strings will be massive. you can  use izz ifyou want to get it

**Comment by federicodotta** [comment]
As you can see in the first screenshot, I used izz, not iz. For this reason it seems strange to me that that string was not present in the result

**Comment by federicodotta** [comment]
Hi! 

I just tried with the last git code (radare2 4.5.0-git 0 @ linux-x86-64 git.4.5.0-git, commit: HEAD build: 2020-04-17__00:00:16) on the same environment/same application (last time I tried with version 4.3.1 but I realized that it was not the last version of radare2).

Unfortunately I have the same issue: izz still does not find the string.

Thank you for your great work!

**Comment by federicodotta** [comment]
Hi!

Maybe I found the problem. After a very short string (1 char), radare seems to fail to identify many subsequent strings (including the one that miss), as you can see at address 0x1000295db of the following screenshot:

![Screenshot from 2020-04-25 19-28-56](https://user-images.githubusercontent.com/1651767/80283813-ceffee00-871a-11ea-8bcf-d71c1018862b.png)

Thank you,
Federico

**Comment by radare** [comment]
Cc @kazarmy

**Comment by kazarmy** [comment]
> -> r2 ipa://DemoHITB.ipa

You can use `r2 -e bin.str.enc=ascii ipa://DemoHITB.ipa` if you want matching flags.
