### ISSUE TITLE
Move test/scripts into test/bins/src

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16576]

**Comment by valdaarhun** [comment]
Hi. I am a beginner and would like to work on this.

**Comment by valdaarhun** [comment]
@radare I wanted to clarify one thing. Will the contents of `test/scripts` finally lie in `test/bins/src` or will `test/bins/src` contain the directory `scripts` which in turn will have all the files?

**Comment by trufae** [comment]
moving the test scripts into bins sounds good to me

**Comment by valdaarhun** [comment]
@trufae I have moved the contents of test/scripts into src/ in the test-bins repository. Could you please review the [PR](https://github.com/radareorg/radare2-testbins/pull/54)?

**Comment by trufae** [comment]
Done
