### ISSUE TITLE
Rename some repositories

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16599]
No need for the duplication in the name, imho:
- [radare2-r2pipe](https://github.com/radareorg/radare2-r2pipe) to just "radareorg/r2pipe"
- [radare2-testbins](https://github.com/radareorg/radare2-testbins) to just "radareorg/testbins"
- [radare2book](https://github.com/radareorg/radare2book) to just "radareorg/book"
- [radare2-bindings](https://github.com/radareorg/radare2-bindings) to just "radareorg/bindings"
- [radare2-rlang](https://github.com/radareorg/radare2-rlang) to just "radareorg/lang"

Also: maybe remove these:
- [radare2-regressions](https://github.com/radareorg/radare2-regressions) Now, after everything was moved there is no reason to keep it here.
- [unicorn](https://github.com/radareorg/unicorn)
- [void-packages](https://github.com/radareorg/void-packages)
- [udis86](https://github.com/radareorg/udis86)

**Comment by ITAYC0HEN** [comment]
Makes sense :)

**Comment by thestr4ng3r** [comment]
> Also: maybe remove these:
> 
>     * [radare2-regressions](https://github.com/radareorg/radare2-regressions) Now, after everything was moved there is no reason to keep it here.

This one should stay as an archived repo, to be able to track the history.

**Comment by radare** [comment]
I prefer the radare2- prefix on all of them othwrwise its anoying to use tab imho

**Comment by XVilka** [comment]
what tab?

**Comment by radare** [comment]
Thst key in the keyboard at the left of q

**Comment by thestr4ng3r** [comment]
You are aware that your folder name doesn't have to match the repo name?

**Comment by eagleoflqj** [comment]
imho for users that fork a repo, there may be confusion without a prefix. radareorg/book looks good but eagleoflqj/book doesn't.

**Comment by ret2libc** [comment]
I personally prefer `radare2-*` prefix. It makes it clear they are radare2 related repositories.
