### ISSUE TITLE
Cannot open large files

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16590]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior

r2 large.file
r2 mmap://large.file
r2 posix://large.file

### Actual behavior

Right now its quite hidden whats the actual backend, mmap is faster, but wont work for mapping HUGE files, in the test.

```
r2 mmap://recorder_image.raw
[r] Cannot open 'mmap://recorder_image.raw'
```

### Steps to reproduce the behavior 
* buy an rpi
* install debian
* install r2
* generate an 8GB file
* open it with r2

### Additional Logs, screenshots, source-code,  configuration dump, ...

cc @shaddy

**Comment by Shaddy** [comment]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 32, Raspbian GNU/Linux 10 (buster)
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A (8GB File)
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0 24351 @ linux-arm-32 git.4.4.0-2-g08210f3d0 commit: 08210f3d0eefaebde8134ddf3d33599c47694b99 build: 2020-04-14__14:23:53


* 4GB of RAM

```
shaddy@rasp01:~/analysis $ cat /proc/meminfo
MemTotal:        3999756 kB
MemFree:          183528 kB
MemAvailable:    3503348 kB
```

* Commands output

```
shaddy@rasp01:~/analysis $ r2 posix://recorder_image.raw
[r] Cannot open 'posix://recorder_image.raw'

shaddy@rasp01:~/analysis $ r2 recorder_image.raw
[r] Cannot open 'recorder_image.raw'

shaddy@rasp01:~/analysis $ r2 mmap://recorder_image.raw
[r] Cannot open 'mmap://recorder_image.raw'
```

**Comment by imyxh** [comment]
This is interesting. If it's of any help, I can't reproduce this on AArch64—my Android phone with 3 GB RAM lets r2 open a 4 GiB file with no problem.

**Comment by ret2libc** [comment]
Hi @Shaddy , could you test the fix provided in https://github.com/radareorg/radare2/pull/16648 and see if it works for you? Thanks!

**Comment by Shaddy** [comment]
@ret2libc I've tested and talked with @radare internally. It was not working, but found out the reason and it is working now (see #166148)

**Comment by Shaddy** [comment]
@ret2libc @radare I tested the last branch and it works fine in 32-bit, good job :)!

**Comment by XVilka** [comment]
@Shaddy @trufae can be this closed?
