### ISSUE TITLE
Release CI

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16593]
We need to upload/deploy all the following builds when there's a tag

* [ ] Debian builds (with capstone5 and libuv dependency)
* [ ] linux-sdk-static (sys/sdk.sh)
* [ ] macOS builds
* [ ] Windows builds (2017)
* [ ] Emscripten (WASM/JS)

**Comment by ret2libc** [comment]
Well, since we are at it...
- [ ] AppImage  (like Cutter does)
- [ ] container image

**Comment by XVilka** [comment]
Dupe of:
- https://github.com/radareorg/radare2-release/issues/34
- https://github.com/radareorg/radare2-release/issues/35

**Comment by XVilka** [comment]
See also https://github.com/radareorg/radare2/issues/16126

**Comment by XVilka** [comment]
Fixed by https://github.com/radareorg/radare2/pull/17192
