### ISSUE TITLE
Bugs in libr/bin/format/dex/dex_uleb128.inc

### ISSUE THREAD

**Issue by eagleoflqj** [radareorg/radare2#16617]
Take https://en.wikipedia.org/wiki/LEB128#Unsigned_LEB128 as an example.
Given {0xE5, 0x8E, 0x26}, this function
https://github.com/radareorg/radare2/blob/9222e458e253c7c00374a4ba69cbb13459d3f595/libr/bin/format/dex/dex_uleb128.inc#L4-L24
returns 166 rather than 624485, while another leb128 decoder https://github.com/radareorg/radare2/blob/9222e458e253c7c00374a4ba69cbb13459d3f595/libr/util/uleb128.c#L7
works well.
I notice its last [big change](https://github.com/radareorg/radare2/pull/5588) may have something to do with big endian (before which the result is 624485 too), but
* it calls dex_uleb128_len which assumes little endian
https://github.com/radareorg/radare2/blob/9222e458e253c7c00374a4ba69cbb13459d3f595/libr/bin/format/dex/dex_uleb128.inc#L26-L34
* line 16 `(byte & 0x7f << shift)` is wrong as `<<` has higher precedence
* line 17 shows the loop will terminate at the first byte having 1 as the most significant bit

Moreover, [LGTM](https://lgtm.com/projects/g/radareorg/radare2/snapshot/7d858aee32577fcd95b43afcbff23aec58305f29/files/libr/bin/format/dex/dex_uleb128.inc?sort=name&dir=ASC&mode=heatmap) says there are dead statements in dex_read_sleb128 too.
So how to deal with that? If big endian is not relevant, should this file be removed since uleb128.c already provides correct version?

**Comment by radare** [comment]
What do you mean by Big endian not relevant?

**Comment by XVilka** [comment]
It should be probably moved to `libr/util/uleb`

**Comment by radare** [comment]
No. It should be removed. We have 3 implementations of uleb already and the one in util is the one that should stay

**Comment by eagleoflqj** [comment]
> What do you mean by Big endian not relevant?
> […](#)
I can’t see how endian affects dex_read_uleb128‘s behavior. It doesn’t work on any endian.

**Comment by XVilka** [comment]
Lets remove it then, and see if tests are still passing.

**Comment by eagleoflqj** [comment]
> Lets remove it then, and see if tests are still passing.

I'll have a try.
