### ISSUE TITLE
Types API

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/radare2#16624]
Types are stored in sdb and there is a lot of code in r2 that uses it.
But there is almost no API for types and currently all of this code directly accesses the sdb, resulting in huge amounts of code duplication and highly fragile code in case the format will change in the future. Even r2ghidra has to manually pull out information from the sdb:
https://github.com/radareorg/r2ghidra-dec/blob/3773ed1a33f1e0aec77d4975c02ce573651eb7ad/src/R2TypeFactory.cpp#L42-L85

This should be made into a nice API. I am thinking about something like this (rough sketch):
```c
typedef enum {
    R_ANAL_BASE_TYPE_KIND_STRUCT,
    R_ANAL_BASE_TYPE_KIND_UNION,
    R_ANAL_BASE_TYPE_KIND_ENUM,
    ...
} RAnalBaseTypeKind;

typedef struct r_anal_base_type_struct {
    RVector members; // describe the struct in some way
} RAnalBaseTypeStruct;

typedef struct r_anal_base_type_enum {
    RVector cases; // list of all the enum cases
} RAnalBaseTypeEnum;

typedef struct r_anal_base_type {
    RAnalBaseTypeKind kind;
    union {
        RAnalBaseTypeStruct ztruct;
        RAnalBaseTypeEnum inum;
        ...
    };
} RAnalBaseType;

R_API RAnalBaseType *r_anal_get_base_type(const char *name);
```

Note: I am explicitly calling this `RAnalBaseType` because these are basically the "atomic" types that are stored in the database. These base types are definitions of structs, unions, enums, int types, etc. but NOT something like `Something *[]`.

**Comment by XVilka** [comment]
Yes, good idea and will make the types code more readable

**Comment by HoundThe** [comment]
Shouldn't the second **r_anal_base_type_struct** be an **r_anal_base_type_enum** ?

**Comment by thestr4ng3r** [comment]
Yes, good catch.

**Comment by XVilka** [comment]
Since the PR was merged, please update the issue text.

**Comment by thestr4ng3r** [comment]
The scope of the issue is done. For further steps we should make follow-up issues.
