### ISSUE TITLE
Feature Request - seek to highlight

### ISSUE THREAD

**Issue by liranzw** [radareorg/radare2#16636]
I just moved from IDA to radare2 and i miss the Alt-T option for searching free text in graph mode.
You already have the feature to highlight searched text, but it would be great if i could jump to it.

Maybe add the highlighted text to the hit flags, or let me jump with n/N between highlights.
That would be great.

If there is another method to search&seek in graph mode that i'm not aware of, please enlighten me.

Thank you and have a great day

**Comment by radare** [comment]
I have started to implement this in here: https://github.com/radareorg/radare2/pull/16683

still very wip, but hopefully ready soon :)

**Comment by radare** [comment]
Now the feature is working, but the implementation could be much better. feel free to try the branch if you can't wait until merged :)

**Comment by liranzw** [comment]
Wow. That was really fast. Thank you very much!
