### ISSUE TITLE
drtj fpu returns invalid json

### ISSUE THREAD

**Issue by bannsec** [radareorg/radare2#16635]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 1 @ linux-x86-64 git.4.5.0-git commit: dae5bb43ee8e3c6ba9964caf6569ce28918dd000 build: 2020-04-16__23:30:26

### Expected behavior
`drtj fpu` should return valid json.

### Actual behavior
it does not. Instead, at least for registers `st<x>` r2 decides to return hex, which is not valid json.

```
[0x7f1634629090]> drtj fpu
{"cwd":895,"swd":0,"ftw":0,"fop":0,"frip":0,"frdp":0,"mxcsr":8064,"mxcr_mask":0,"st0":0x00000000000000000000,"st1":0x00000000000000000000,"st2":0x00000000000000000000,"st3":0x00000000000000000000,"st4":0x00000000000000000000,"st5":0x00000000000000000000,"st6":0x00000000000000000000,"st7":0x00000000000000000000,"xmm0h":0,"xmm0l":0,"xmm1h":0,"xmm1l":0,"xmm2h":0,"xmm2l":0,"xmm3h":0,"xmm3l":0,"xmm4h":0,"xmm4l":0,"xmm5h":0,"xmm5l":0,"xmm6h":0,"xmm6l":0,"xmm7h":0,"xmm7l":0,"xmm8h":0,"xmm8l":0,"xmm9h":0,"xmm9l":0,"xmm10h":0,"xmm10l":0,"xmm11h":0,"xmm11l":0,"xmm12h":0,"xmm12l":0,"xmm13h":0,"xmm13l":0,"xmm14h":0,"xmm14l":0,"xmm15h":0,"x64":0}
```

Note the "0x" indicating hex where hex is not valid.

### Steps to reproduce the behavior 
- Simply try using `drtj fpu` to notice hex. Even more apparent if you attempt `r2.cmdj('drtj fpu')` as it will cause an exception

**Comment by bannsec** [comment]
I should note, xmm and ymm are doing the same thing.

```
In [17]: target.r2.cmd('drtj xmm')                                                                                                                                                                                                                                                
Out[17]: '{"xmm0":0x3a657265682065646f63207265746e45,"xmm1":0x203a657265682065646f63207265746e,"xmm2":0x0000ff00000000000000000000000000,"xmm3":0x0000000000000000000000000000ff00,"xmm4":0x2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f,"xmm5":0x00000000000000000000000000000000,"xmm6":0xffffffffffffffffffffffffffffffff,"xmm7":0x00000004000000040000000400000004,"xmm8":0x6e450021737261657920657669662074,"xmm9":0x00000000000000000000000000000000,"xmm10":0x00000000000000000000000000000000,"xmm11":0x00000000000000000000000000000000,"xmm12":0x00000000000000000000000000000000,"xmm13":0x00000000000000000000000000000000,"xmm14":0x00000000000000000000000000000000,"xmm15":0x00000000000000000000000000000000}\n'

In [18]: target.r2.cmd('drtj ymm')                                                                                                                                                                                                                                                
Out[18]: '{"ymm0":0x00007ffc9380d46000000030000000203a657265682065646f63207265746e45,"ymm1":0xaaeba00657ef6b0000007ffc9380d3a0203a657265682065646f63207265746e,"ymm2":0x00007f209f39817a00007f209b4a78600000ff00000000000000000000000000,"ymm3":0x000000000000000200000000000000000000000000000000000000000000ff00,"ymm4":0x000000000000000200000000000000002f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f,"ymm5":0x00007f209f39817000007f209f39817a00000000000000000000000000000000,"ymm6":0x00007f2086686c200000000000000000ffffffffffffffffffffffffffffffff,"ymm7":0x00007f20a20e07e8000000000000000000000004000000040000000400000004,"ymm8":0x00000009e8bb9a74000000000000000a6e450021737261657920657669662074,"ymm9":0x00007f20a3b0ea3e00007ffc9380d43000000000000000000000000000000000,"ymm10":0x00007f20a20e07df000000000000000000000000000000000000000000000000,"ymm11":0x000000000000400000007ffc9380d45000000000000000000000000000000000,"ymm12":0x000000000000000700000072c32c6c7800000000000000000000000000000000,"ymm13":0x0000555bc31cb008000000000000000000000000000000000000000000000000,"ymm14":0xffffffffffffffb0000000000000403000000000000000000000000000000000,"ymm15":0x0000013000000401000000000000010000000000000000000000000000000000}\n'
```

**Comment by abcSup** [comment]
It is because those registers are implemented with big numbers (over 64 bits). I could implement the conversion from a big number to decimal string, but that will not be optimized. Currently, the best way is to convert them into hex strings by giving them quotes ("). I am sorry, let me know if that is ok for you or we could wait for others to implement the conversion from big numbers to decimal strings in `r_big` to make it valid.

**Comment by bannsec** [comment]
Given that at the moment cmdj and json decoding doesn't work without doing
some very gross regex, making them strings as an interim solution would at
least let those commands start working again.

**Comment by karliss** [comment]
This is related to https://github.com/radareorg/cutter/issues/2142 . How to better report >= 64 bit integers using JSON in general. Most programming languages don't have native big integer types and even 64 bit integers are problematic due JSON originating from JavaScript. Many JSON parsers use Double for all integer types which can't store 64 bit integers properly. According to JSON spec such implementations are considered valid.

JSON output which can't be parsed by many JSON parsing libraries defeats the purpose of having JSON output - having a format with sufficiently clear parsing rules that can be read using widely available libraries.

**Comment by bannsec** [comment]
Sounds like placing quotes around the hex representation is the way to go then.
