### ISSUE TITLE
p: Cannot find function at 0x（some address）

### ISSUE THREAD

**Issue by smithCoderLeo** [radareorg/radare2#16646]
r2 version:  radare2 4.5.0-git 0 @ linux-x86-64 git.4.5.0-git
operation:
1. r2 (my file) 
![image](https://user-images.githubusercontent.com/13193519/79724854-cf634800-831a-11ea-8803-cacdb872c478.png)
2. aaa
![image](https://user-images.githubusercontent.com/13193519/79724899-e1dd8180-831a-11ea-991e-4f747164082a.png)
3. s 0x14002A14C
![image](https://user-images.githubusercontent.com/13193519/79725371-b4450800-831b-11ea-9c2e-41618c5bcd92.png)
4.pdf
![image](https://user-images.githubusercontent.com/13193519/79725420-c9ba3200-831b-11ea-8d9d-5f29c81a2835.png)

other my bin all occur this problem，so i want to ask whether my operation is wrong，or a bug？thank you ！

when i user “pdf @ 0x......” to disassembly some function， cannot find it。But when i use IDA Pro，i can find this function，as the graph shows，up is r2， down is IDA pro，I've been obsessed for a long time，thank  you：
![r2cannotfindfunc](https://user-images.githubusercontent.com/13193519/79719701-b5713780-8311-11ea-9b44-6ed9e6de9ec3.jpg)
![IDAfunc](https://user-images.githubusercontent.com/13193519/79719714-b99d5500-8311-11ea-9fb7-96c922221491.jpg)

**Comment by radare** [comment]
Please fill the issue properly, which file are you using, which version of r2? Which commands are you typing before pdf?

**Comment by trufae** [comment]
Thanks for the details. Can you try with latest r2 from git and share the binary? what i understand is that r2 is not finding the function in aaa for some reason. you can try enabling `-e anal.hasnext=true` before `aaaa` or run `af` before calling `pdf` in that offset.

**Comment by radare** [comment]
ping?

**Comment by trufae** [comment]
Closing as there's no feedbcak in 2 years and imho it should just work well with hasnext set to true or using the aafs command
