### ISSUE TITLE
Fix 'q' command in cfg.newshell

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16668]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior
It exit.

### Actual behavior
It does not exit

### Steps to reproduce the behavior 
```
> e cfg.newshell=true
> q
```

**Comment by ret2libc** [comment]
I will work on this soon. The problem is that `core_cmd_tsr2cmd` and all the handlers just return bool, but they should probably return `int` (or better an enum) with `q` returning `R_CORE_CMD_EXIT`.

**Comment by radare** [comment]
There was an issue about this 2 weeks ago becuse there was a missusage of bool vs int in corecmd to return 0,1 -1 and -2 with different meanings
