### ISSUE TITLE
Is it feasible to open another binary file on r2 command line?

### ISSUE THREAD

**Issue by chenjinzhi1990** [radareorg/radare2#16666]
![image](https://user-images.githubusercontent.com/25029027/79816798-a5f7fa00-83b6-11ea-9659-c2fb6240cad3.png)

Use radare2 to open a binary code file for the iOS app, and later open another binary code file on the command line. How to achieve this goal.

**Comment by XVilka** [comment]
Yes, just use `o` commands: https://radare.gitbooks.io/radare2book/content/basic_commands/mapping_files.html
