### ISSUE TITLE
Take tests from BAP repo

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16676]
https://github.com/BinaryAnalysisPlatform/bap-testsuite

**Comment by XVilka** [comment]
Another interesting candidate is https://github.com/LL-MM/approxis-groundtruth

**Comment by trufae** [comment]
This doesn't make much sense to me and we have enough workload by maintaining our tests, units and use cases. Importing tests from other projects wont reduce the  pain or improve the quality of the testing or project
