### ISSUE TITLE
Wrong multi-line handling in r2shell?

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#16684]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 27975 @ linux-x86-64 git.4.4.0-58-g06ab29b93 commit: 06ab29b93cb0168a8ec1cb39f860c6b990678838 build: 2020-04-21__13:48:08

### Expected behavior
First command:
```
Found flirt.__libc_start_main
```
Second command:
```
Found flirt.__libc_start_main
0x004e2420   40 664          flirt.__libc_start_main
```

### Actual behavior
First command:
```
Found flirt.__libc_start_main
```
Second command:
```
0x004e2420   40 664          flirt.__libc_start_main
```

### Steps to reproduce the behavior 
```
$ R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 's 0x4e2420 ; af ; s 0x4e25c7 ; af ; zfs bins/other/sigs/libc-v10.sig' bins/elf/analysis/pid_stripped
$ R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 's 0x4e2420 ; af ; s 0x4e25c7 ; af ; zfs bins/other/sigs/libc-v10.sig ; afl ~4e2420' bins/elf/analysis/pid_stripped
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

As you can see, the two commands are the same, apart from the fact that in the second one there is an additional `afl ~4e2420`. I would expect the output of the second command to be the same as the output of the first one, plus the output of `afl ~4e2420`. However, somehow `afl ~4e2420` hides even the output of the previous `zfs bins/other/sigs/libc-v10.sig`.

I think this is wrong and inconsistent.

Indeed, if you do:
```
$ R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 's 0x4e2420 ; af ; s 0x4e25c7 ; af ; zfs bins/other/sigs/libc-v10.sig
afl ~4e2420' bins/elf/analysis/pid_stripped
```
It prints both output. IMHO this is wrong, as both the one-liner and the command split in two lines should give you the same output.

**Comment by ret2libc** [comment]
cc @radare @thestr4ng3r @XVilka @karliss

**Comment by XVilka** [comment]
We need a testcase for this as well. Good catch!

**Comment by ret2libc** [comment]
There is actually a tests for this, but it checks the "wrong" behavior. What I'd like to know if this is really a bug or a feature?! @radare

**Comment by radare** [comment]
Only for comments afaik

**Comment by ret2libc** [comment]
Perfect, then I will treat this as a bug (which should be fixed by newshell).
