### ISSUE TITLE
Fix temporary seek with deltas (e.g. cmd @ +0x10) in cfg.newshell

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#16682]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 27975 @ linux-x86-64 git.4.4.0-58-g06ab29b93 commit: 06ab29b93cb0168a8ec1cb39f860c6b990678838 build: 2020-04-21__13:48:08

### Expected behavior
```
            0x00000002      92             xchg eax, edx
```

### Actual behavior
```
            0x00000001      91             xchg eax, ecx
```

### Steps to reproduce the behavior 
```
[0x00000000]> e cfg.newshell=true
[0x00000000]> wx 9091929394
[0x00000000]> pd 4
            0x00000000      90             nop
            0x00000001      91             xchg eax, ecx
            0x00000002      92             xchg eax, edx
            0x00000003      93             xchg eax, ebx
[0x00000000]> s 1
[0x00000001]> pd 1 @ +1
```

**Comment by radare** [comment]
fix? this has never been suposed to work

use $$+1 if you want that, but this syntax has never been supported

**Comment by ret2libc** [comment]
If so, even better but it works with old parser.

**Comment by radare** [comment]
:magic:

**Comment by ret2libc** [comment]
Are you ok with NOT supporting this feature? If so, I'm going to close this bug.

**Comment by radare** [comment]
well if we support it it will be nce because it will be in sync with `s`

s +10 works

and yeah i probably added @+ and @- support but i always use the $$+- syntax
