### ISSUE TITLE
Panel mode can be accesed in non-interactive mode

### ISSUE THREAD

**Issue by karliss** [radareorg/radare2#16689]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArchLinux x86_64
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 25839 @ linux-x86-64 git.4.4.0-64-gd3ecd271c commit: d3ecd27 build: 2020-04-22__20:43:21

### Expected behavior

When `e scr.interactive=false` is set visual panel mode is disabled and trying to enter it shows an error.

### Actual behavior

When scr.interactive=false visual mode is disabled but panel mode isn't.

### Steps to reproduce the behavior 
- open an executable using r2
- `e scr.interactive=false`
- `V` observe that visual mode isn't entered (it would be nicer if it printed an error)
- `v` observe that panel mode is started

**Comment by Emi1305** [comment]
Similar issue occurs with other features that run interactive, f.e. internal less

```
e scr.interactive=false
pd 10~..
```

Should I open a new issue?

**Comment by ret2libc** [comment]
@Emi1305 yes please. However, it would also be awesome if you'd like to provide a PR to fix the problem :) I/We can guide you if you need help navigating the code.
