### ISSUE TITLE
Add --with-sys-tree-sitter in acr

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#16698]
With https://github.com/radareorg/radare2/pull/16679 we got the possibility of using system tree-sitter library instead of the bundled one, in meson.

This issue is to track the additional support for this in acr as well.

**Comment by ret2libc** [comment]
@radare I think `acr` does not support CHKLIB with a name that contains `-` (e.g. `CHKLIB tree-sitter`). This would generate the var HAVE_LIB_TREE-SITTER, which does not work. Can this be fixed? Until then, systreesitter will work only on meson. It's not that important for now anyway.

**Comment by radare** [comment]
fixed in acr-1.8.2

**Comment by radare** [comment]
You can finish the pr after updating acr

**Comment by ret2libc** [comment]
I will do it sometime in the next weeks, it's not high prio as anyway few distros are shipping tree-sitter right now and those who do are probably using meson. Anyway, it's in my todo list.

**Comment by radare** [comment]
Should be done before the release (may 25)

**Comment by trufae** [comment]
treesitter was killed a while ago
