### ISSUE TITLE
Parser for `to` command can't handle typedef for multiple types

### ISSUE THREAD

**Issue by typoon** [radareorg/radare2#16704]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04 x86_64
| File format of the file you reverse (mandatory)      | All formats
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | Cutter-v1.10.3-pre-x64.Linux.AppImage

### Expected behavior

Loading a header file where a `typedef` defines two or more names should work. The following should create the types `EnumT1` and `EnumT2`.

```c
typedef enum {
    SomeEntry1,
    SomeEntry2
} EnumT1, EnumT2;
```

### Actual behavior

When trying to load a header file that contains a `typedef` that declares two or more types at the same time cause the `to` command to fail with the error:

~~~
to /home/gilgamesh/tmp/efi/bla.h

Not found
/home/gilgamesh/tmp/efi/bla.h:12: error: declaration expected
~~~ 

### Steps to reproduce the behavior 

* Load a binary on radare
* Create a header file with the following contents

```c
typedef enum {
    SomeEntry1,
    SomeEntry2
} EnumT1, EnumT2;
```

* Load the header file created with the `to` command
* Notice the error

```
error: declaration expected
```

* Change the contents of the file to:

```c
typedef enum {
    SomeEntry1,
    SomeEntry2
} EnumT1;
```

* Load the file again with the `to` command
* Notice that the file is loaded correctly.

**Comment by typoon** [comment]
Just to make it clear, this is not happening just with enums, but with any typedef that declares more than one type. So the following causes the same error:

```c
typedef struct {
    int x;
} myStruct, myStruct2;
```

**Comment by trufae** [comment]
I dont think this should be a valid or supported syntax, despite it's valid in C i dont think it's a good practice, so i'm fine with the error.

the TCC parser used to load the types is not 100% following the C standard, as it also aims to support other usecases and definitions that are not possible in C.

```
$ r2 -
 -- I did it for the pwnz.
[0x00000000]> to b.h
b.h:3: error: declaration expected
[0x00000000]> to a.h
a.h:4: error: declaration expected
[0x00000000]> cat a.h
typedef enum {
    SomeEntry1,
    SomeEntry2
} EnumT1, EnumT2;
[0x00000000]> cat b.h
typedef struct {
    int x;
} myStruct, myStruct2;
[0x00000000]>
```

dont define multiple typedefs in a single statement and that will work. I thikn having a type defined in many ways it's just an overcomplication and root of confusion/problems.
