### ISSUE TITLE
Rename core->assembler to rasm

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16727]

**Comment by radare** [comment]
comments @thestr4ng3r @ret2libc ?

**Comment by thestr4ng3r** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/include/GL/gl.h#L549

**Comment by ret2libc** [comment]
Same as https://github.com/radareorg/radare2/issues/16727#issuecomment-619830239

**Comment by radare** [comment]
🙄

**Comment by radare** [comment]
Fixed in https://github.com/radareorg/radare2/pull/16814
