### ISSUE TITLE
[PE][Header] Missing import entries

### ISSUE THREAD

**Issue by SylvainCecchetto** [radareorg/radare2#16739]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.15.4
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 0 @ darwin-x86-64 git.4.5.0-git commit: HEAD build: 2020-04-28__13:16:37

### Expected behavior
R2 should be able to list all entries from the IAT

### Actual behavior
R2 returns zero import, IDA reports two imports

### Steps to reproduce the behavior 
- Open the binary with `r2 bin.bin`
- Print sections with `ii` command
- This is what Radare2 prints:
```
[Imports]
nth vaddr bind type lib name
――――――――――――――――――――――――――――
```

Open the same binary file with Binary Ninja or IDA and compare imports provided by both:

* IDA:

```
Address	Ordinal	Name	Library
0100500C		LoadLibraryA	kernel32
01005010		GetProcAddress	kernel32
```

**Binary:** [bin.bin.zip](https://github.com/radareorg/radare2/files/4545770/bin.bin.zip)

**Comment by XVilka** [comment]
Would be nice to have a test for this
