### ISSUE TITLE
RVector api to assign, but not to get

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16732]
to get the ptr at a given index you have to use index_ptr and then dereference the pointer, ideally that pointer should be peeked with a proper api

```
R_API void *r_vector_assign_at(RVector *vec, size_t index, void *elem) {
        void *p = r_vector_index_ptr (vec, index);
        if (elem) {
                r_vector_assign (vec, p, elem);
        }
        return p;
}
```

**Comment by thestr4ng3r** [comment]
I think most of the time you will want to do something like this, without copying:
```c
RVector *vec;
// ...
MyType *el = r_vector_index_ptr(vec, 42);
eprintf("%d\n", el->somemember);
```

But ofc a getter that copies could be added too.

**Comment by ret2libc** [comment]
I'm not sure I understand exactly what you'd like to have @radare

**Comment by trufae** [comment]
Let's close it for now, it's just an internal API improvement
