### ISSUE TITLE
RPVector grows without filling the new slots with nulls

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16731]
This results in UB and crashes when trying to use those unitialized slots.

not initializing to null only makes sense when initializing the whole array with user provided data. otherwise it should be initialized to null

**Comment by thestr4ng3r** [comment]
> not initializing to null only makes sense when initializing the whole array with user provided data.

Exactly. That is why it doesn't initialize and it's the desired behavior. It's the user's responsibility to initialize the data.
