### ISSUE TITLE
[PE][Header] Missing section

### ISSUE THREAD

**Issue by SylvainCecchetto** [radareorg/radare2#16737]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.15.4
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 0 @ darwin-x86-64 git.4.5.0-git commit: HEAD build: 2020-04-28__13:16:37

### Expected behavior
R2 should be able to list all sections find in the header.

### Actual behavior
R2 forgets the first section (`.text` section).

### Steps to reproduce the behavior 
- Open the binary with `r2 bin.bin`
- Print sections with `iS` command
- This is what Radare2 prints:
```
nth paddr         size vaddr        vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00001890   0xf76 0x01004290   0xf76 -rwx blob
1   0x00000a00   0x200 0x01002000  0x1000 -rw- .data
2   0x00000c00   0xa00 0x01003000  0x1000 -rw- .rsrc
3   0x00001600  0x1000 0x01004000  0x1000 -rw- .nPack
```

Open the same binary file with Binary Ninja or IDA and compare sections listing provided by both:

* Binary Ninja:

```
Sections:
0x01001000-0x01002000  .text  {Code}
0x01002000-0x01003000  .data  {Writable data}
0x01003000-0x01004000  .rsrc
0x01004000-0x01005000  .nPack
```

* IDA:

```
.text:01001000 ; Format      : Portable executable for 80386 (PE)
.text:01001000 ; Imagebase   : 1000000
.text:01001000 ; Section 1. (virtual address 00001000)
.text:01001000 ; Virtual size                  : 00001000 (   4096.)
.text:01001000 ; Section size in file          : 00000600 (   1536.)
.text:01001000 ; Offset to raw data for section: 00000400
.text:01001000 ; Flags E0000020: Text Executable Readable Writable
.text:01001000 ; Alignment     : default
.data:01002000 ; Section 2. (virtual address 00002000)
.data:01002000 ; Virtual size                  : 00001000 (   4096.)
.data:01002000 ; Section size in file          : 00000200 (    512.)
.data:01002000 ; Offset to raw data for section: 00000A00
.data:01002000 ; Flags C0000040: Data Readable Writable
.data:01002000 ; Alignment     : default
.nPack:01004000 ; Section 4. (virtual address 00004000)
.nPack:01004000 ; Virtual size                  : 00001000 (   4096.)
.nPack:01004000 ; Section size in file          : 00001000 (   4096.)
.nPack:01004000 ; Offset to raw data for section: 00001600
.nPack:01004000 ; Flags C0000040: Data Readable Writable
.nPack:01004000 ; Alignment     : default
```

**Binary:** [bin.bin.zip](https://github.com/radareorg/radare2/files/4545353/bin.bin.zip)

**Comment by XVilka** [comment]
Would be nice to have a test for this

**Comment by SylvainCecchetto** [comment]
Thank you for the fix. Should I add the binary in https://github.com/radareorg/radare2-testbins/tree/master/pe via a PR? Or you will do? Not sure about the unit test procedure.
