### ISSUE TITLE
Tab complete improvments

### ISSUE THREAD

**Issue by karliss** [radareorg/radare2#16750]
**Is your feature request related to a problem? Please describe.**
Having structured information about about all the commands as could be provided after a few iterations in the direction started by #16738 opens potential for improving tab complete.

**Describe the solution you'd like**
* Knowing all the commands removes the need for hard-coded list currently used
* Grid of few hundred command names starting with given prefix isn't very useful. When completing command (first word) show help summary of shortest commands starting with given prefix. Don't show all the nested commands that would be too much. Some people might like old behavior this can be a setting.
* When command name is completed (there is a space after it) tab or double tab could show the extended description of current command. Asking for help at this point likely means that user doesn't the format of arguments.
* After writing first character after space autocomplete should give suggestions for arguments.
   * If we had type information about arguments they could be completed, this is far future one step past argc/argv
   * We have some information about expected argument type for the commands that have special handling in the parser like `@` and macro. `@` already completes flag names but it probably doesn't use information from treesitter parser.
   * Simpler approach is to have some kind of heuristics if the current argument could be file path or flag name. If argument starts with `./` `/` or `C:` assume its path, if it is a valid prefix for flag assume it's a flag.

**Comment by trufae** [comment]
There are some improvements planned for a better structured autocompletion and recursive command resolution. But there's no need to keep a ticket open.

thanks
