### ISSUE TITLE
RVector have no way to chk if its empty

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16758]

**Comment by eagleoflqj** [comment]
https://github.com/radareorg/radare2/blob/be95cf339de67ed26cf8fadce8d8778a334e6dd0/libr/include/r_vector.h#L72-L75
There is. Do you mean it should be made public api?

**Comment by ret2libc** [comment]
> There is. Do you mean it should be made public api?

By being in the r_vector.h file it is already public. I think this issue was an old one and it can be closed.
