### ISSUE TITLE
Register names list as comments at top of AVR binary.

### ISSUE THREAD

**Issue by ivanzinhoa** [radareorg/radare2#16768]
I have created a simple blinky program using Atmel Studio 7, it is just 5 lines of code, I convert the produced HEX file into a BIN, run R2 with that binary file, get the first disassembled instructions with the command line "pD 10" and then I see a list of the names of the registers as comments along with the 10 instructions I requested, it is useless and I don't need to list the register names, actually I don't need comments at all and there is no way to disable them either in Cutter or R2. Could you please fix that or provide a way to disable all auto-generated comments? Thank you.
![Untitled](https://user-images.githubusercontent.com/39418676/81022295-e46bcb00-8e32-11ea-950c-a0501e723e5f.png)

**Comment by radare** [comment]
e asm.comments=false

**Comment by ivanzinhoa** [comment]
Please, I tried that before posting the issue. The problem is really annoying especially on Cutter, I'm using a laptop screen so if I jump to the first instruction it just shows those unuseful comments. This is a bug.

**Comment by GustavoLCR** [comment]
e asm.flags=false

**Comment by ivanzinhoa** [comment]
> e asm.flags=false

Thank you, that worked for the command line.

Now I want to do it on Cutter but there isn't a check on Preferences menu, I also run Cutter.exe --help but there is no option, also I looked for a config file or so but I wasn't able to find any, is there a way to achieve that same "asm.flags=false"?

**Comment by GustavoLCR** [comment]
click on Windows->Console, then you can type the command in there

**Comment by ivanzinhoa** [comment]
> click on Windows->Console, then you can type the command in there

Thank you very much @GustavoLCR that also worked.
