### ISSUE TITLE
`movq rax, xmm0` doesn't work in native debugger

### ISSUE THREAD

**Issue by rickhg12hs** [radareorg/radare2#16778]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 29/x86_64
| File format of the file you reverse (mandatory)      | ELF 64-bit LSB shared object
| Architecture/bits of the file (mandatory)            | x86-64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24563 @ linux-x86-64 git.4.4.0-117-g311ad8189<br>commit: 311ad818945e88ca38059adb7ce3962af394d44e build: 2020-05-03__17:33:49

### Expected behavior

Debugger step `movq rax, xmm0` should move the lower 64 bits of `xmm0` to `rax`.

### Actual behavior

Debugger doesn't move contents of `xmm0[0:63]` to `rax`.

```
[0x0003b0e0]> drr
role reg    value            ref
――――――――――――――――――――――――――――――――
SN   rax    0                 0 R 0x3010102464c457f
     rbx    0                 0 R 0x3010102464c457f
A3   rcx    0                 0 R 0x3010102464c457f
A2   rdx    7ff0000000000000 
A1   rsi    0                 0 R 0x3010102464c457f
A0   rdi    0                 0 R 0x3010102464c457f
A4   r8     0                 0 R 0x3010102464c457f
A5   r9     0                 0 R 0x3010102464c457f
A6   r10    0                 0 R 0x3010102464c457f
A7   r11    0                 0 R 0x3010102464c457f
     r12    0                 0 R 0x3010102464c457f
     r13    0                 0 R 0x3010102464c457f
     r14    0                 0 R 0x3010102464c457f
     r15    0                 0 R 0x3010102464c457f
PC   rip    3b0ee             241902 (.text) sym.finite R X 'movq rax, xmm0'
BP   rbp    10078000          268926976 R W 0x0 -->  0 R 0x3010102464c457f
     rflags 0                 0 R 0x3010102464c457f
SP   rsp    10078000          268926976 R W 0x0 -->  0 R 0x3010102464c457f
[0x0003b0e0]> dr xmm0
0xaaaaaaaaaaaaaaaa5555555555555555
[0x0003b0e0]> ds
[0x0003b0e0]> drr
role reg    value            ref
――――――――――――――――――――――――――――――――
SN   rax    8000000000000000 
     rbx    0                 0 R 0x3010102464c457f
A3   rcx    0                 0 R 0x3010102464c457f
A2   rdx    7ff0000000000000 
A1   rsi    0                 0 R 0x3010102464c457f
A0   rdi    0                 0 R 0x3010102464c457f
A4   r8     0                 0 R 0x3010102464c457f
A5   r9     0                 0 R 0x3010102464c457f
A6   r10    0                 0 R 0x3010102464c457f
A7   r11    0                 0 R 0x3010102464c457f
     r12    0                 0 R 0x3010102464c457f
     r13    0                 0 R 0x3010102464c457f
     r14    0                 0 R 0x3010102464c457f
     r15    0                 0 R 0x3010102464c457f
PC   rip    3b0f3             241907 (.text) sym.finite R X 'and rax, rdx'
BP   rbp    10078000          268926976 R W 0x0 -->  0 R 0x3010102464c457f
     rflags 0                 0 R 0x3010102464c457f
SP   rsp    10078000          268926976 R W 0x0 -->  0 R 0x3010102464c457f
[0x0003b0e0]>
```

### Steps to reproduce the behavior 

1. `r2 libm-2.28.so` (in this zip --> [libm-2.28.so.zip](https://github.com/radareorg/radare2/files/4585942/libm-2.28.so.zip), but it's just `/lib64/libm-2.28.so` on my system)
2. `aa`
3. `s sym.finite`
4. `dr rip=$$ + $l`
5. `dr xmm0l=0xdeadc0de`  ... or whatever
5. `ds;drr` and continue as shown in _Actual Behavior_ section above

### Additional Logs, screenshots, source-code,  configuration dump, ...

Is there anything else relevant?

**Comment by karliss** [comment]
I don't see you starting the debugger. So you are probably running ESIL emulation not the native debugger. ESIL currently isn't properly supported SIMD  #4327 #11421

**Comment by rickhg12hs** [comment]
@karliss I'm still getting familiar with radare2.  How would I use the native debugger to step through a few instructions, like I tried here in this ELF SO?

**Comment by kazarmy** [comment]
> Should I close this issue?

Why not?
