### ISSUE TITLE
Support writing Python byte data

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16779]
If you dump some data in Python it looks something like that:
```
b'\x00\xf0U\x10[.\xabB'
```
where `\x00` is `0x00`, `\xf0` is `0xf0`, `\x10` is `0x10`, `\xab` is `0xab`.
On the other hand, `U`, `[.`, and `B` here are the ASCII characters.
Often you need to deal with such data from logs/etc. Would be awesome to support not also for printing it with `pcpb` (as opposed to `pcp` which uses `struct.pack()`), but also `wxp`.

**Comment by radare** [comment]
Seems like a very issue thing you can make a pr for it will be easier to do it than describing how you want it

**Comment by xarkes** [comment]
The description is clear enough in my opinion, at least I understood it after first read, so correct me if I am wrong but XVilka is suggesting the addition of the command `wxp` that would work as follow:
`wxp b'Hello'` will write the bytes `Hello` (`0x48 0x65 0x6c 0x6c 0x6f`)
`wxp b'\xc0\xfe\xba\xbe'` that will write the bytes `0xc0 0xfe 0xba 0xbe`
`wxp b'Hi\x20there'` that will write the bytes `Hi there` (`0x48 0x69 0x20 0x74 0x68 0x65 0x72 0x65`)
`wxp b''` would write nothing
`wxp b'`, `wxp b'123123`, `wxp 123123`, `wxp 123b'123`, `wxp 123b'hello'` would be invalid

**Comment by radare** [comment]
That will break the new parser @ret2libc

**Comment by ret2libc** [comment]
> That will break the new parser @ret2libc

Why? I don't think it breaks it, it should be supported (unless there are bugs ofc)

**Comment by radare** [comment]
Well it will require a specific parser to handle this specific argument syntax and dont escape the escaped chars

**Comment by ret2libc** [comment]
> Well it will require a specific parser to handle this specific argument syntax and dont escape the escaped chars

It works well already, there is no need to modify anything because strings between single quotes are not modified (same as in bash)

This is the syntax tree:
```
wxp b'Hi\x20there'
---
(commands [0, 0] - [1, 0]
  (arged_command [0, 0] - [0, 18]
    command: (cmd_identifier [0, 0] - [0, 3])
    args: (args [0, 4] - [0, 18]
      (arg [0, 4] - [0, 18]
        (concatenation [0, 4] - [0, 18]
          (arg_identifier [0, 4] - [0, 5])
          (single_quoted_arg [0, 5] - [0, 18]))))))
```

**Comment by elp0t0r1c0** [comment]
hmm:

```
$ r2 malloc://0x1000
 -- There's no way you could crash radare2. No. Way.
[0x00000000]> "w \x00\xf0U\x10[.\xabB"
[0x00000000]> px 8
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  00f0 5510 5b2e ab42                      ..U.[..B
[0x00000000]>
```
This is already implemented, by just using 'w'.

**Comment by radare** [comment]
Yep. But if people want the b’’ wrap..

**Comment by xarkes** [comment]
I would say either make `w` compliant or chose not to support `b''`.
I'm not in favor of adding yet another command.

**Comment by radare** [comment]
Me neither. Never seen the point of having python3 specific syntax to work as input for r2 when we have very similar and more generic ways to do so

**Comment by XVilka** [comment]
I didn't knew it's supported in plain "w". Marking as solved.
