### ISSUE TITLE
x86 pseudo for LEA is wrong

### ISSUE THREAD

**Issue by ishitatsuyuki** [radareorg/radare2#16777]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10/Arch linux amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86 (32-bit)
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24573 @ linux-x86-64 git.4.4.0-138-g64e6df500 commit: 64e6df5004b2718526761503a48437e82be3471e build: 2020-05-06__18:01:55

### Expected behavior

```
> e asm.pseudo = false
0x0804843c      8d45f8         lea eax, [var_8h]
```

```
> e asm.pseudo = true
0x0804843c      8d45f8         eax = var_8h
```

### Actual behavior

```
> e asm.pseudo = true
0x0804843c      8d45f8         eax = [var_8h]
```

The brackets are unneeded for pseudo, and therefore this syntax is inconsistent with arithmetic operators (which outputs like `eax = eax * edx`).

It is possible to tell the difference between a `mov` and `lea` in pseudo as the latter has no `dword` prefix, but this is still very confusing.

It was supposed to be fixed by #6618 but then reverted for #9126 which left the pseudocode part broken.

### Steps to reproduce the behavior 
Bin: crackme0x02 from [IOLI crackmes series](https://dustri.org/b/files/IOLI-crackme.tar.gz) (from #9126)

**Comment by ishitatsuyuki** [comment]
@radare Can you comment on which syntax is expected for the pseudocode? Was the revert in #9126 supposed to give the correct behavior?

**Comment by radare** [comment]
I prefer

Lea rax, sym.foo

Rather than

Lea rax, [sym.foo]

**Comment by ishitatsuyuki** [comment]
I asked for pseudocode, and you replied with x86 disassembly.

If it's about pseudocode then I prefer `rax = sym.foo` as well.

**Comment by radare** [comment]
Yes. Actually if you change the disassembly like i propose the pseudocode will look like u said
