### ISSUE TITLE
Remote debugging problems for ARM via OpenOCD connection 

### ISSUE THREAD

**Issue by yusefkarim** [radareorg/radare2#16788]
While attempting to connect to the gdb-compatible server provided by running OpenOCD I ran into several issues.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux (kernel 5.6.10) x86-64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM Cortex-M4 (STM32F401CC) thumbv7em-none-eabihf - 32 bit instruction set
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24602 @ linux-x86-64 git.4.4.0-143-g2a4cc154f6 commit: 2a4cc154f6ea78a77e512234b286e40b13efe2ca build: 2020-05-08__17:25:22

### Expected behavior
Be able to debug and analyze running program via OpenOCD connection.

### Actual behavior
OpenOCD refuses connection by r2 most of the time, printing `Error: attempted 'gdb' connection rejected`. Continually running the r2 command will eventually lead to a successful connection but all commands run inside the r2 shell yield `WARNING: r_reg_get: assertion 'reg && name' failed (line 302)`.

When printing the CPU registers via `dr` it outputs the below:
```
WARNING: r_reg_get: assertion 'reg && name' failed (line 302)
sp = 0x00000000
lr = 0x00000000
pc = 0x00000000
xPSR = 0x00000000
sb = 0x00000000
sl = 0x00000000
fp = 0x00000000
ip = 0x00000000
sp = 0x00000000
lr = 0x00000000
pc = 0x00000000
r0 = 0x00000000
r1 = 0x00000000
r2 = 0x00000000
r3 = 0x00000000
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00000000
r12 = 0x00000000
r13 = 0x00000000
r14 = 0x00000000
r15 = 0x00000000
cpsr = 0x00000000
blank = 0x00000000
<repeat>
<repeat>
...
WARNING: r_reg_get: assertion 'reg && name' failed (line 302)
```

Where the registers `sp-blank` are repeated around 15-16 times (denoted by \<repeat\>). 

One thing to note, is that I can switch into remotecmd mode with !=! and use the OpenOCD commands `monitor reset halt/reset` and they actually work, but are followed by a message `Try: '=!?'`.

### Steps to reproduce the behavior

First I run OpenOCD:
```
openocd -f interface/stlink-v2.cfg -f target/stm32f4x.cfg
```
Then in another terminal I run:
```
r2 -e dbg.exe.path=<elf> -m 0x08000000 -a arm -b 32 -d gdb://127.0.0.1:3333
```
The above command usually fails as explained above, so I rerun the above command around 6-10 times until it actually works.

On success I am greeted with:
```
Unknown architecture parsing XML (<?xml version="1.0"?>
<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target version="1.0">
<feature name="org.gnu.gdb.arm.m-profile">
<reg name="r0" bitsize="32" regnum="0" save-restore="yes" type="int" group="general"/>
<reg name="r1" bitsize="32" regnum="1" save-restore="yes" type="int" group="general"/>
<reg name="r2" bitsize="32" regnum="2" save-restore="yes" type="int" group="general"/>
<reg name="r3" bitsize="32" regnum="3" save-restore="yes" type="int" group="general"/>
<reg name="r4" bitsize="32" regnum="4" save-restore="yes" type="int" group="general"/>
<reg name="r5" bitsize="32" regnum="5" save-restore="yes" type="int" group="general"/>
<reg name="r6" bitsize="32" regnum="6" save-restore="yes" type="int" group="general"/>
<reg name="r7" bitsize="32" regnum="7" save-restore="yes" type="int" group="general"/>
<reg name="r8" bitsize="32" regnum="8" save-restore="yes" type="int" group="general"/>
<reg name="r9" bitsize="32" regnum="9" save-restore="yes" type="int" group="general"/>
<reg name="r10" bitsize="32" regnum="10" save-restore="yes" type="int" group="general"/>
<reg name="r11" bitsize="32" regnum="11" save-restore="yes" type="int" group="general"/>
<reg name="r12" bitsize="32" regnum="12" save-restore="yes" type="int" group="general"/>
<reg name="sp" bitsize="32" regnum="13" save-restore="yes" type="data_ptr" group="general"/>
<reg name="lr" bitsize="32" regnum="14" save-restore="yes" type="int" group="general"/>
<reg name="pc" bitsize="32" regnum="15" save-restore="yes" type="code_ptr" group="general"/>
<reg name="xPSR" bitsize="32" regnum="16" save-restore="yes" type="int" group="general"/>
</feature>
<feature name="org.gnu.gdb.arm.m-system">
<reg name="msp" bitsize="32" regnum="17" save-restore="yes" type="data_ptr" group="system"/>
<reg name="psp" bitsize="32" regnum="18" save-restore="yes" type="data_ptr" group="system"/>
<reg name="primask" bitsize="1" regnum="19" save-restore="yes" type="int8" group="system"/>
<reg name="basepri" bitsize="8" regnum="20" save-restore="yes" type="int8" group="system"/>
<reg name="faultmask" bitsize="1" regnum="21" save-restore="yes" type="int8" group="system"/>
<reg name="control" bitsize="2" regnum="22" save-restore="yes" type="int8" group="system"/>
</feature>
<feature name="org.gnu.gdb.arm.vfp">
<reg name="d0" bitsize="64" regnum="23" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d1" bitsize="64" regnum="24" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d2" bitsize="64" regnum="25" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d3" bitsize="64" regnum="26" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d4" bitsize="64" regnum="27" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d5" bitsize="64" regnum="28" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d6" bitsize="64" regnum="29" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d7" bitsize="64" regnum="30" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d8" bitsize="64" regnum="31" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d9" bitsize="64" regnum="32" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d10" bitsize="64" regnum="33" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d11" bitsize="64" regnum="34" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d12" bitsize="64" regnum="35" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d13" bitsize="64" regnum="36" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d14" bitsize="64" regnum="37" save-restore="yes" type="ieee_double" group="float"/>
<reg name="d15" bitsize="64" regnum="38" save-restore="yes" type="ieee_double" group="float"/>
<reg name="fpscr" bitsize="32" regnum="39" save-restore="yes" type="int" group="float"/>
</feature>
</target>
)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
= attach 0 1
No debug register profile defined for 'PC'.
= attach 0 0
No debug register profile defined for 'PC'.
No debug register profile defined for 'PC'.
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
WARNING: using oba to load the syminfo from different mapaddress.
TODO: Must use the API instead of running commands to speedup loading times.
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
No debug register profile defined for 'PC'.
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
r_reg_set_profile_string: Parse error @ line 20 (Invalid size)
WARNING: r_reg_get: assertion 'reg && name' failed (line 302)
No debug register profile defined for 'PC'.
 -- SSAbotage from ISIL
WARNING: r_reg_get: assertion 'reg && name' failed (line 302)
```
### Additional Logs, screenshots, source-code,  configuration dump, ..

Running `file` on my ELF file yields:
```
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, with debug_info, not stripped
```

**Comment by radare** [comment]
Seems like the gdb regprofile is not being parsed properly

**Comment by abcSup** [comment]
@yusefkarim Currently, I do not own any hardware to reproduce the error. Based on the error messages you provide, I have created a small branch fix on my fork https://github.com/abcSup/radare2/tree/fix-16788-regprofile . For now, you could just `git clone` and build from source yourself. I would not create a PR yet until I can make sure that this works for you and I do not break gdb for other targets as well.

**Comment by yusefkarim** [comment]
@abcSup Thank you for looking into this! Your patch fixed the `r_reg_get` assertion, the output of `dr` now yields:
```r0 = 0x241574f5
r1 = 0x72e494e4
r2 = 0x86460512
r3 = 0x17460752
r4 = 0x42577626
r5 = 0x06329706
r6 = 0x5626c716
r7 = 0x07924716
r8 = 0xe6e65627
r9 = 0xe272e696
r10 = 0xc2c61604
r11 = 0x16863606
r12 = 0x325776e6
sp = 0x22447404
lr = 0x42964606
pc = 0x07f24607
xPSR = 0x97765626
```
which looks correct to me (ignoring the values).

I am still having the same problem when trying to start `r2` though. I must run the command,
```
~/bin/r2 -e dbg.exe.path=<elf> -m 0x08000000 -a arm -b 32 -d gdb://127.0.0.1:3333
```

several times before it successfully connects, each failure I get the error:

```
read_packet: read failed
gdb.io.open: Cannot connect to host.
WARNING: using oba to load the syminfo from different mapaddress.
TODO: Must use the API instead of running commands to speedup loading times.
No file to load bin from?
[r] Cannot open 'gdb://127.0.0.1:3333'
```
Does this warrant a new bug report?

**Comment by abcSup** [comment]
Thanks for letting me know that it works.
> Does this warrant a new bug report?

Best to keep it in this issue. I have read that, but the error messages are not enough for me to debug.
```
Error: attempted 'gdb' connection rejected
```
```
read_packet: read failed
gdb.io.open: Cannot connect to host.
```
Let me know if there is a way I can setup OpenOCD connecting a VM without the hardware or you could capture the packets between the gdb server/client using Wireshark.

**Comment by yusefkarim** [comment]
I am not aware of any way to do my setup without actual hardware. I have gone ahead and done several packet captures of successful and failed attempts. I have attached two pcaps of each type.

One thing I found is on a **successful** attempt, OpenOCD prints out:
```
Warn : keep_alive() was not invoked in the 1000ms timelimit. GDB alive packet not sent! (1087). Workaround: increase "set remotetimeout" in GDB
```
I don't know if that helps at all.

I don't use Wireshark very often so if I did something wrong or you need more information just let me know!

[pcaps.tar.gz](https://github.com/radareorg/radare2/files/4623034/pcaps.tar.gz)

**Comment by abcSup** [comment]
@yusefkarim Those packet captures are great. `[55030] r2` `[3333] OpenOCD gdb server`

![image](https://user-images.githubusercontent.com/6021307/82719212-6fcfc380-9c5d-11ea-8ac5-b083ee5994aa.png)
![image](https://user-images.githubusercontent.com/6021307/82719225-8413c080-9c5d-11ea-9223-66e80eb0b6be.png)

Apparently, in failed cases, OpenOCD gdb server sent a RST packet that resets the connection and produced the output `Error: attempted 'gdb' connection rejected`. This is out of my ability to fix it since it is not part of the GDB Remote protocol problem.

I could only assume that it might be an OpenOCD issue which sometimes closes the connection after `r2` sends a `+` gdb acknowledgment packet (maybe a timeout?). I will create a PR to fix the register profile that was done previously.

In a success case (screenshots for future reference),
![image](https://user-images.githubusercontent.com/6021307/82719357-ac4fef00-9c5e-11ea-9bef-3e8dcc48898d.png)
![image](https://user-images.githubusercontent.com/6021307/82719375-e7eab900-9c5e-11ea-8781-d02d9e37030e.png)

**Comment by yusefkarim** [comment]
Hi @abcSup,

Thank you for taking the time to look into this. I decided to ask about this on the OpenOCD Freenode channel.

A developer there found that r2 seems to be waiting for a second (consistently) before sending an ACK. To test his theory, I recompiled OpenOCD with a timeout of 2 seconds instead of 1 when accepting a connection. This gave enough time for r2 to connect, and it now works as expected.

Would you happen to know if there is a reason r2 waits before sending an ACK when connecting to a GDB server? It seems like the change would better be made on the r2 side, rather than the OpenOCD side.

**Comment by abcSup** [comment]
> A developer there found that r2 seems to be waiting for a second (consistently) before sending an ACK. To test his theory, I recompiled OpenOCD with a timeout of 2 seconds instead of 1 when accepting a connection. This gave enough time for r2 to connect, and it now works as expected.

I have noticed that as well by comparing two cases and thank you for the info which confirms that OpenOCD actually timeout after 1 second when not receiving the `+` acknowledgement packet.

https://github.com/radareorg/radare2/blob/fea70914e8b04e10825f6e79c623cdb1b5d49591/libr/socket/socket.c#L374-L378

I found that `r_socket_connect` does the above, which wait for nothing because all fd_set are set to NULL. Therefore, this statement will just wait for x second and timeout and always return 0 as a result.

**Comment by yusefkarim** [comment]
Hi @abcSup 

Thank you for pointing this out. Before I even had a chance to think about it the amazing @paulfertser who initially pointed out the timing issue made a few changes to `r_socket_connect` that fixed the issue.

I have made a pull request #16946 with his changes.

**Comment by abcSup** [comment]
Great. I will make another PR for the register profile fix as well. Thank you very much!
