### ISSUE TITLE
Segmentation fault opening binary

### ISSUE THREAD

**Issue by SjRNMzU** [radareorg/radare2#16791]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian Sid, x86_64
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | x64 ELF
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24604 @ linux-x86-64 git.4.4.0-146-g242f1efdf commit: 242f1efdfaf2bec7f643e6ef424959ad4621c572 build: 2020-05-09__14:39:15
### Expected behavior
Radare2 opens to the shell prompt
### Actual behavior
Radare2 seg faults
### Steps to reproduce the behavior 
- Opening the binary attached. `r2 libBlocksRuntime.so.0.0.0`

ELF

**Comment by SjRNMzU** [comment]
Uploading the file through Github failed. I've also uploaded it here - https://transfer.sh/69vmM/libBlocksRuntime.so.0.0.0

**Comment by XVilka** [comment]
GitHub expects you to zip it before.
