### ISSUE TITLE
Qiling/gdb remote debugging not working 

### ISSUE THREAD

**Issue by redmed666** [radareorg/radare2#16797]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali x64 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24691 @ linux-x86-64 git.4.4.0-138-g64e6df500 commit: 64e6df5004b2718526761503a48437e82be3471e build: 2020-05-06__08:57:06

### Expected behavior

Remote debug working.

### Actual behavior

radare2 outputs this:

```
= attach 0 0
ptrace (PT_ATTACH): No such process
= attach 0 0
ptrace (PT_ATTACH): No such process
= attach 0 0
ptrace (PT_ATTACH): No such process
ptrace (PT_ATTACH): No such process
= attach 0 0
ptrace (PT_ATTACH): No such process
```

It is also breaking at address 0x0 instead of the entry point of the executable. Moreover, no matter if I continue or step, it doesn't change anything.

### Steps to reproduce the behavior 

Step 1: `./qltool run -f ./your.exe --rootfs ./rootfs/ --gdb 0.0.0.0:9999`
Step 2: `r2 gdb://127.0.0.1:9999`

**Comment by XVilka** [comment]
Qiling is based on the unicorn, right? Which is based on the very old qemu, whose gdbserver has changed protocol a bit since. Just a blind guess though.

**Comment by redmed666** [comment]
Hi,

Apparently, Qiling is implementing itself its gdbserver (in `qiling/debugger/gdbserver/gdbserver.py`). I will try to see the differences between their implementation and what radare2 expects.

**Comment by radare** [comment]
You missed the -d flag in r2

R2 wprks well with qilin

**Comment by redmed666** [comment]
Indeed, the -d flag was missing. But I have another issue. It seems that radare2 doesn't handle properly the breakpoint address properly. It doesn't add the PE base address to the entrypoint address. So it connects to qiling's gdbserver, it receives correctly the address of entrypoint but doesn't break at it and begins at 0x00000 instead of 0x<base_address>

**Comment by radare** [comment]
use -B or -m to map the bin in the same baddr of the remote site to slide those offsets

**Comment by redmed666** [comment]
Ok, found a way to make it work.

1) `r2 -`
2) `doof gdb://127.0.0.1:9999/0`
3) enjoy

The file is mapped and the commands are working as expected so that's nice. But that seems pretty quirky that `r2 -d gdb://127.0.0.1:9999/0` doesn't work, no? Or at least maybe that could be documented somewhere?

Thanks for your help!

**Comment by radare** [comment]
Yeah the -d way should work
