### ISSUE TITLE
Add Docker Publish action

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#16808]
https://github.com/marketplace/actions/publish-docker

To push here: https://hub.docker.com/repository/docker/radare/radare2

I tried to trigger it on DockerHub, but seems not working, probably because of the `radare`->`radareorg` repository transfer.

**Comment by XVilka** [comment]
Added, but feel free to improve

**Comment by radare** [comment]
Imho we should ship it in Alpine , the final base image would be smaller

**Comment by XVilka** [comment]
We can try Docker-slim: https://github.com/docker-slim/docker-slim

**Comment by XVilka** [comment]
Also, ideally we should move the Docker image from [`radare/radare2`](https://hub.docker.com/repository/docker/radare/radare2) to `radareorg/radare2`, where Cutter is: https://hub.docker.com/repository/docker/radareorg/cutter

**Comment by XVilka** [comment]
It was done, any improvements could wait.

**Comment by ret2libc** [comment]
@XVilka isn't this already done? What does remain? IMO we already have the publish action and that's good enough for now. Can we close?
