### ISSUE TITLE
`aaa;zg` fails assertion `size > 0` in sign.c

### ISSUE THREAD

**Issue by swoops** [radareorg/radare2#16820]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali and Arch Linux, amd64 
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86 64 bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24961 @ linux-x86-64 git.4.4.0-172-g7451b6744 commit: 7451b67448ba005886b7f42d8354a6cdf16a605a build: 2020-05-13__19:30:24|

### Expected behavior
`aaa;zg` should not result in a failed assertion.

### Actual behavior
`aaa` produces a zero length function. So when `zg` iterates over functions, calling `addFcnZign` on them, the assertion [here](https://github.com/radareorg/radare2/blob/master/libr/anal/sign.c#L736) fails because `size` is zero.
### Steps to reproduce the behavior 
Run `aaa;zg` on the provided file. 
```
 -- For HTTP authentification 'e http.auth = 1', 'e http.authfile = <path>'
[0x00006130]> aaa;zg
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
WARNING: r_sign_add_anal: assertion 'a && name && size > 0 && bytes' failed (line 736)
generated zignatures: 254
[0x00006130]> s fcn.00014100
[0x00014100]> afi # returns nothing

0x00014100]>
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
[file.zip](https://github.com/radareorg/radare2/files/4625376/file.zip)

**Comment by trufae** [comment]
Can't reproduce

**Comment by XVilka** [comment]
Apparently it's fixed. Please reopen if it doesn't work for you.
