### ISSUE TITLE
Flags should not start with numbers

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16843]
This is something that is valid now for some reason. dunno when this changed but imho flags should not start with digits and we should have tests for this

![Screenshot 2020-12-11 at 13 49 16](https://user-images.githubusercontent.com/6431515/101905387-aea47700-3bb7-11eb-907a-732d83195b7e.png)

![Screenshot 2020-12-11 at 13 50 16](https://user-images.githubusercontent.com/6431515/101905472-d1369000-3bb7-11eb-989d-1cf643ebbb59.png)

Done in https://github.com/radareorg/radare2/pull/18020

**Comment by thestr4ng3r** [comment]
Why not?

**Comment by radare** [comment]
For the same reason we dont like variables starting with numbers.

**Comment by kazarmy** [comment]
Agree

**Comment by ITAYC0HEN** [comment]
> Why not?
Currently, you can define flags which are only numbers (decimal, hex) and they will conflict with decimal and hex number in the commands. How would the program know what the user (or the automation) meant

**Comment by thestr4ng3r** [comment]
> Currently, you can define flags which are only numbers (decimal, hex) and they will conflict with decimal and hex number in the commands. How would the program know what the user (or the automation) meant

Depends on the parser. If we want to support args in commands that can be both a number or a flagname then I agree on this suggestion and I think forbidding leading digits is a good way to do so since you also catch cases like `0x1337`.

**Comment by radare** [comment]
Yes. Thats how r2 worked always with rnum

**Comment by ITAYC0HEN** [comment]
Yes, so we agree :)
That's a good suggestion

**Comment by XVilka** [comment]
Personally, I don't think starting from numbers is a good idea. It's against on how many programming languages work.

**Comment by ITAYC0HEN** [comment]
Yeah we all agree, flags shouldn't start with leading digits.
I improved the title so it will be more clear

**Comment by karliss** [comment]
> Depends on the parser. If we want to support args in commands that can be both a number or a flagname then I agree

The simplest case is expressions. Is `123+321` flag `123` with offset 321, flag `321` with offset 123 or just 444?

**Comment by thestr4ng3r** [comment]
> > Depends on the parser. If we want to support args in commands that can be both a number or a flagname then I agree
> 
> The simplest case is expressions. Is `123+321` flag `123` with offset 321, flag `321` with offset 123 or just 444?

444 is illegal in my country.

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/radare2/pull/18020
