### ISSUE TITLE
Output doesn't show up if `\n` isn't used

### ISSUE THREAD

**Issue by Ruturaj4** [radareorg/radare2#16933]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSI Ubuntu
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            |  x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 24020 @ linux-x86-64 git.4.3.1-78-g71d3709
commit: 71d3709d254050011ecc4a0005929e9bcd4322ea build: 2020-03-20__08:55:17

### Expected behavior
Should print the output in debugging mode
### Actual behavior
Doesn't print the output if `\n` isn't used
### Steps to reproduce the behavior 
#include <stdio.h>

Source code:

```
int main()
{
 printf("You win!");
  return 0;
}
```
Output shows up if I change this to printf("You win!\n"), otherwise it doesn't

### Additional Logs, screenshots, source-code,  configuration dump, ...

```
$ gcc main.c
$ radare2 -d a.out
Process with PID 16389 started...
= attach 16389 16389
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
Warning: r_bin_file_hash: file exceeds bin.hashlimit
 -- radare2 is like windows 7 but even better.
[0x7f979a000c30]> dc
[0x7f9799cfc748]>
[0x7f9799cfc748]> quit
Do you want to quit? (Y/n) y
Do you want to kill the process? (Y/n)
```
Now fixing the file.
```
$ gcc main.c
$ radare2 -d a.out
Process with PID 16398 started...
= attach 16398 16398
bin.baddr 0x00400000
Using 0x400000
asm.bits 64
Warning: r_bin_file_hash: file exceeds bin.hashlimit
 -- Wait a minute! I found a bug, self-fixing ... OK
[0x7f9d4d000c30]> dc
You win!
[0x7f9d4ccfc748]> 
```

**Comment by XVilka** [comment]
Use rarun2 profiles for proper redirection of stdin and stdout of the program.
