### ISSUE TITLE
scanf and printf not work corrrect at visual mode

### ISSUE THREAD

**Issue by 18345093167** [radareorg/radare2#16943]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu18.04 x64 
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32

### Expected behavior
scanf("%s",a) a is exepected.
### Actual behavior
There is a char ~ before what i input
### Steps to reproduce the behavior 
[00.zip](https://github.com/radareorg/radare2/files/4672058/00.zip)
Steps:
(1)r2 -d 00 -> aa -> afl -> dcu ->pdf @ main ->v->F8
(2)Use F8 to debug
(3)After printf call, there is no output 
(4)When call scanf, there will be a "~" before what I input

### Additional Logs, screenshots, source-code,  configuration dump, ...
![prinf](https://user-images.githubusercontent.com/20567891/82735010-1c3ea200-9d51-11ea-9dc4-897052b4943e.png)

![123456](https://user-images.githubusercontent.com/20567891/82734826-054b8000-9d50-11ea-9ea3-6fa1921342d3.png)
![~123456](https://user-images.githubusercontent.com/20567891/82734825-054b8000-9d50-11ea-83f4-bbf9b2870804.png)

**Comment by XVilka** [comment]
It is because how it radare2 debugging works. You need to redirect output like in rarun2: https://radare.gitbooks.io/radare2book/tools/rarun2/intro.html

**Comment by 18345093167** [comment]
Thanks very much.
