### ISSUE TITLE
r2 does not work with files containing space

### ISSUE THREAD

**Issue by prusnak** [radareorg/radare2#16958]
### Expected behavior

r2 does work with files containing spaces

### Actual behavior

r2 does not work with files containing spaces

### Steps to reproduce the behavior 
```
$ cp /bin/bash bash
$ cp /bin/bash "ba sh"
$ r2 -nn -Nqc "pfj.elf_header @ 0" bash
[{ ... }]
$r2 -nn -Nqc "pfj.elf_header @ 0" "ba sh"
Cannot find 'elf_header' format.
```

**Comment by XVilka** [comment]
@ret2libc could you please check this bug before the 4.5.0 release?
