### ISSUE TITLE
not work well with frida 12.9.4

### ISSUE THREAD

**Issue by oxpy** [radareorg/radare2#16989]
frida version 12.9.4 
  r2 -version
radare2 4.5.0-git 24705 @ linux-x86-64 git.4.4.0-228-g9b6160cf5
commit: 9b6160cf5f9b405a99c5a7d053dadbd500270d9a 

r2 cannot work well with  frida server ,it crashes
DetachReason: FRIDA_SESSION_DETACH_REASON_PROCESS_TERMINATED
CrashReport: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/aosp_sailfish/sailfish:9/PQ3A.190605.003/andy05060257:userdebug/test-keys'
Revision: '0'
ABI: 'arm'
pid: 24055, tid: 24073, name: Thread-20  >>> com.ho.mi <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xd0e88768
    r0  d291804c  r1  00000008  r2  00000004  r3  00000000
    r4  e4d463b0  r5  e4f74028  r6  d291804c  r7  d29181e0
    r8  d29182e0  r9  e4c8df38  r10 e9d81300  r11 00000008
    ip  80000000  sp  d2917fb0  lr  00000539  pc  d0e88768

backtrace:
    #00 pc 0013c768  /data/local/tmp/re.frida.server/frida-agent-32.so

Target process terminated
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed
error: Script is destroyed

But I can use frida communicate with frida server rightly.

**Comment by radare** [comment]
This is a bug in frida. Theres an env var in r2frida to workaround it. Its been reported several times already in r2frida. Hope this will be addressed soon we can get rid of the hackaround

See r2 frida://?

R2FRIDA_SAFE_IO

**Comment by oxpy** [comment]
please give me some more details,thanks.
what exactly the command I should use?

**Comment by trufae** [comment]
This is a bug in Frida, not in r2, and it is exposed by r2frida, not r2, so i'm closing the issue now.

There are several issues in the other repository explaining how to to solve this, you can take a look at https://github.com/nowsecure/r2frida/issues?q=is%3Aissue+R2FRIDA_SAFE_IO+is%3Aclosed

in short, the following line should work fine:

```
$ R2FRIDA_SAFE_IO=1 r2 frida://...
```
