### ISSUE TITLE
radare2 assemble 00 instead of the right instruction for ld hl, 0xc3a0 for gameboy

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#16995]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ubuntu 19.10 x64 
| File format of the file you reverse (mandatory)      | gameboy save file with gameboy instructions
| Architecture/bits of the file (mandatory)            | gameboy
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24710 @ linux-x86-64 git.4.4.0-229-g5817770e2 commit: 5817770e290b3c66a3fe57850db6dda1c44c6a19 build: 2020-06-01__20:40:26

### Expected behavior

wa ld hl, 0xc3a0 should write some ocpodes obviously different than 00

### Actual behavior

wa ld hl, 0xc3a0 actually writes 00

### Steps to reproduce the behavior 
I did r2 -w myfile;
e cfg.bigendian=false; e asm.arch=gb
then wa ld hl, 0xc3a0;
then r2 still writes 00

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by condret** [comment]
fixed here https://github.com/condret/radare2/tree/fix_%2316995 , I haven't got time to write boring tests now

**Comment by gogo2464** [comment]
@condret I tested your plugin. `wa ld bc, 0x188`
`cannot insert wa ld bc, 0x188 at line 3` 

There may be a  bug.

**Comment by condret** [comment]
oh, ld bc is a thing

**Comment by condret** [comment]
I push -f updated the commit, this should work now

**Comment by gogo2464** [comment]
@condret  this part works now. But the command to translate opcodes of `call 0x36e0` translates to the opcodes of `call 0x0000`.
