### ISSUE TITLE
program 'python.exe' failed to run: the specified executable is not a valid application

### ISSUE THREAD

**Issue by ItsPoom123** [radareorg/radare2#17017]
I don't know what is going on. I tried to use pip but it didn't allow me.

`PS C:\Users\User> pip install requests
Fatal error in launcher: Unable to create process using '"c:\users\user\appdata\local\programs\python\python38-32\python.exe"  "C:\Users\User\AppData\Local\Programs\Python\Python38-32\Scripts\pip.exe" install requests'
PS C:\Users\User> python -c "import pip.__main__"
Program 'python.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
+ python -c "import pip.__main__"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ python -c "import pip.__main__"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\Users\User> python
Program 'python.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
+ python
+ ~~~~~~.
At line:1 char:1
+ python
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed`

**Comment by ret2libc** [comment]
Hi! How is this related to radare2?

**Comment by ItsPoom123** [comment]
I'm very confused right now and I need some help

**Comment by trufae** [comment]
You may ask for help in Python forums/chats instead, this issues doesn't seems to be related to radare2 at all.

Apart from that by reading the error message you pasted it seems like you downladed a 64bit python in 32bit windows or the other way around.
