### ISSUE TITLE
strrchr vs r_str_rchr

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17023]
**Is your feature request related to a problem? Please describe.**

Some platforms didnt support (or supported) `strrchr` i cant recall them. thats why i wrote r_str_rchr() for portability purposes

**Describe the solution you'd like**

Seems like now we have strrchr in a couple of places but no CI or user have complained about it.

```
$ git grep strrchr
dbginfo.c:                      file_nopath = strrchr (file_line, '/');
dbginfo.c:                      char *slash = strrchr (file, '/');
p/bin_dyldcache.c:              /*char * last_slash = strrchr (file, '/');
p/bin_dyldcache.c:                              char *last_slash = strrchr (file, '/');
p/bin_dyldcache.c:                              char *last_slash = strrchr (file, '/');
p/bin_xnu_kernelcache.c:                cursor = strrchr (cursor, '.');\
p/bin_xnu_kernelcache.c:                        cursor = strrchr (cursor, '.');\
p/bin_xnu_kernelcache.c:        const char *sn = strrchr (kext->name, '.');
```

**Describe alternatives you've considered**

Wll be good to clarify where is strrchr not available, and remove the r_str_rchr implementation

**Additional context**

git grep is your friend

**Comment by ret2libc** [comment]
I've looked quickly at commits with `strrchr` and they were introduced before 2018, so I guess we can just remove `r_str_rchr` since nobody complained in these 2 years. If anyone does at some point, we can reintroduce it from git log (and documen the culprit compiler so we'll know in the future).

**Comment by trufae** [comment]
According to the manpage this API was introduced in POSIX C90

**Comment by ret2libc** [comment]
On Fedora 31 my man page says:
```
CONFORMING TO
       strchr(), strrchr(): POSIX.1-2001, POSIX.1-2008, C89, C99, SVr4, 4.3BSD.
```
I'm not an expert about standards and such. Is this enough for us or shall we use `r_str_rchr`?

**Comment by unixfreaxjp** [comment]
Just want to confirm that my testbed systems are not affected if `r_str_rchr` is being deleted.
 `strrchr` still resides in string.h on native systems please don't delete it.

Thank you in advance.

**Comment by ret2libc** [comment]
> strrchr still resides in string.h on native systems please don't delete it.

What do you mean by "don't delete it"? Don't delete `r_str_rchr` or don't delete `strrchr`?

**Comment by unixfreaxjp** [comment]
sorry for additional comment:

> we have `strrchr` in a couple of places but no CI or user have complained about it.

which means good is t?

> Some platforms didnt support (or supported) `strrchr` i cant recall them

That unsupported platform should be non-POSIX then.

Many native compilation apps in ports like sudo, lynx, nano etc is using `strrchr` also still.

@trufae @ret2libc

**Comment by unixfreaxjp** [comment]
> What do you mean by "don't delete it"? Don't delete r_str_rchr or don't delete strrchr?

Please do not delete `strrchr`, and feel free to delete `r_str_rchr`

@trufae @ret2libc

**Comment by unixfreaxjp** [comment]
@trufae can I test as part of test result on "Continuos Built" or the version after it? Is it merged now? Is it test-able now??  This recent "uncertainty" is making me super nervous now..
cc: @XVilka 
cc: fyi, @condret (I will include tests on your ESIL new change too why I cc)

**Comment by ret2libc** [comment]
> @trufae can I test as part of test result on "Continuos Built" or the version after it? Is it merged now? Is it test-able now?? This recent "uncertainty" is making me super nervous now..

You can test it from git or from a tarball got from github (e.g. https://github.com/radareorg/radare2/archive/master.zip) . There is no recent "uncertainty" though, this kind of changes has always occured. 

In this particular case, `r_str_rchr` was changed slightly to use `strrchr` in some cases. However, both `r_str_rchr` and `strrchr` were used for a very long time in radare2 code base (like, even before 2016 and probably even before). Also, we have unit tests to check the functionality of `r_str_rchr` function. Even though I agree we should engage with the community as much as poossible, in this particular case it wasn't really a big deal, because it is just an implementation detail that users won't care about, since both `strrchr` and `r_str_rchr` have been used for more than 4/5 years. This is the commit https://github.com/radareorg/radare2/commit/b045d2553bd089b57b7cfc3e6cb7435bbc028dba btw. If this doesn't build on some machine, probably it didn't build in the last 4/5 years either.

**Comment by trufae** [comment]
@unixfreaxjp right now (and as @ret2libc said), strrchr has been used for a long while, afaik the only reason for not using it was windows9x, in which the windows maintainers of r2 decided to stop supporting. So right now r2 uses strrchr and r_str_rchr, the reason of having a wrapper on top of it is because in some situations we need to specify the end of the string (or we want to tell where to start looking backward). So it shouldnt be an issue and, yes this has been tested on all the CI systems.

I have also tested on old macppc and i confirm it works

**Comment by unixfreaxjp** [comment]
> I have also tested on old macppc and i confirm it works

Just tested in almost all instances I got. No bad affect at all @trufae 💯

**Comment by radare** [comment]
Awesome! Thanks for confirmation!!
