### ISSUE TITLE
Long identifiers in Mach-O are mishandled

### ISSUE THREAD

**Issue by phakeobj** [radareorg/radare2#17056]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS 64-bit
| File format of the file you reverse (mandatory)      | Mach-O dynamic library
| Architecture/bits of the file (mandatory)            | arm64, arm64e
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24799 @ darwin-x86-64 git.4.4.0-274-g77cc18ba0 commit: 77cc18ba046bc1966704df759f37833a063f9e01 build: 2020-06-12__12:13:52

While working with some dylibs I noticed that long identifiers are being truncated. I created a tiny Mach-O dynamic library to investigate this behavior. The dylib exports 2 symbols, one is 1024 chars long and the other is 2048 chars long.

### Expected behavior

radare2 should be able to handle long identifier, similarly to how nm, `Apple LLVM version 11.0.3 (clang-1103.0.32.62)` handles them

```
$ nm longIdentifiers.dylib
0000000000007fa8 T _abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij
0000000000007fb0 T _abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst
                 U dyld_stub_binder
```

### Actual behavior

radare2 truncates one of the identifiers and ignores the other one

```
$ rabin2 -s longIdentifiers.dylib
[Symbols]

nth paddr       vaddr      bind   type size lib name
――――――――――――――――――――――――――――――――――――――――――――――――――――
0    0x00007fa8 0x00007fa8 GLOBAL FUNC 0        _abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs
1    0x00007fa8 0x00007fa8 LOCAL  FUNC 0        func.00007fa8
2    0x00007fb0 0x00007fb0 LOCAL  FUNC 0        func.00007fb0
```

### Steps to reproduce the behavior 

```
rabin2 -s longIdentifiers.dylib
```
[longIdentifiers.zip](https://github.com/radareorg/radare2/files/4770242/longIdentifiers.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...

The following code in `mach0.c` is pretty staright forward.

```
2900	stridx = bin->symtab[i].n_strx;
2901	char *sym_name = get_name (bin, stridx, false);
2902	if (sym_name) {
2903		r_str_ncpy (symbols[j].name, sym_name, R_BIN_MACH0_STRING_LENGTH);
2904		free (sym_name);
2905	}
```

`get_name()` returns an `strdup`ed copy of the string, then the string is copied with max length of `R_BIN_MACH0_STRING_LENGTH`, into the relevant `symbol_t` and the `strdup`ed pointer is freed. Peeking in `mach0.h:11` we can see `#define R_BIN_MACH0_STRING_LENGTH 256`. 

Then, the code continues to

```
2920	if (inSymtab (hash, symbols[j].name, symbols[j].addr)) {
2921		symbols[j].name[0] = 0;
2922		j--;
2923	}
```

and `inSymtab()` returns `true` for the second identifier. Therefore, the second identifier is dropped form `bin->symbols` and not shown in `rabin2 -s`.

### Discussion

Initially I tried to solve it by changing `256` to `512` and for the purpose of my work, it did the job. But later, while thinking about how to fix this bug I searched for long identifiers in the Dyld Shared Cache and found out some extremely long identifiers, such as `__ZN3WTF18__destroy_op_tableINS_7VariantIJN7WebCore15CanvasDirectionENS2_14CanvasFillRuleENS2_13CanvasLineCapENS2_14CanvasLineJoinENS2_15CanvasTextAlignENS2_18CanvasTextBaselineENS2_21ImageSmoothingQualityENS2_15DOMMatrix2DInitEPNS2_7ElementEPNS2_16HTMLImageElementEPNS2_11ImageBitmapEPNS2_9ImageDataEPNS2_6Path2DEPNS2_11WebGLBufferEPNS2_16WebGLFramebufferEPNS2_12WebGLProgramEPNS2_10WebGLQueryEPNS2_17WebGLRenderbufferEPNS2_12WebGLSamplerEPNS2_11WebGLShaderEPNS2_9WebGLSyncEPNS2_12WebGLTextureEPNS2_22WebGLTransformFeedbackEPNS2_20WebGLUniformLocationEPNS2_22WebGLVertexArrayObjectENS_6RefPtrIN3JSC11ArrayBufferENS_13DumbPtrTraitsIS1B_EEEENS19_INS1A_15ArrayBufferViewENS1C_IS1F_EEEENS19_INS2_14CanvasGradientENS1C_IS1I_EEEENS19_INS2_13CanvasPatternENS1C_IS1L_EEEENS19_INS1A_21GenericTypedArrayViewINS1A_14Float32AdaptorEEENS1C_IS1Q_EEEENS19_INS2_17HTMLCanvasElementENS1C_IS1T_EEEENS19_ISD_NS1C_ISD_EEEENS19_INS2_16HTMLVideoElementENS1C_IS1Y_EEEENS19_ISF_NS1C_ISF_EEEENS19_INS2_20TypedOMCSSImageValueENS1C_IS23_EEEENS19_ISH_NS1C_ISH_EEEENS19_INS1O_INS1A_12Int32AdaptorEEENS1C_IS29_EEEENS19_INS1O_INS1A_13Uint32AdaptorEEENS1C_IS2D_EEEENS1_IJS1X_S1V_S22_S25_S20_EEENS1_IJNS_6StringES1K_S1N_EEENS1_IJS1E_S1H_EEENS_8OptionalIS2J_EENS1_IJS22_S27_S1X_S1V_S20_EEENS2K_IS2M_EENS_6VectorIS2H_Lm0ENS_15CrashOnOverflowELm16ENS_10FastMallocEEENS2O_IfLm0ES2P_Lm16ES2Q_EENS2O_IjLm0ES2P_Lm16ES2Q_EENS2O_IiLm0ES2P_Lm16ES2Q_EENS1_IJS1S_S2S_EEENS1_IJS2B_S2U_EEENS1_IJS2F_S2T_EEES2H_dfNS2K_IfEEyxjihbEEENS_16__index_sequenceIJLl0ELl1ELl2ELl3ELl4ELl5ELl6ELl7ELl8ELl9ELl10ELl11ELl12ELl13ELl14ELl15ELl16ELl17ELl18ELl19ELl20ELl21ELl22ELl23ELl24ELl25ELl26ELl27ELl28ELl29ELl30ELl31ELl32ELl33ELl34ELl35ELl36ELl37ELl38ELl39ELl40ELl41ELl42ELl43ELl44ELl45ELl46ELl47ELl48ELl49ELl50ELl51ELl52ELl53ELl54ELl55ELl56ELl57ELl58ELl59ELl60EEEEE14__destroy_funcILl48EEEvPS2Z_` of `WebCore`, which is 1836 chars long. Then, I went to look up if there's any hard upper boundry for identifiers lengths.

Given the fact that the C++ standard defines identifiers as an ["arbitrarily long sequence of letters and digits"](https://timsong-cpp.github.io/cppwp/lex.name#1), we should rethink about how we handle identifiers memory.

The only solution I can think of, that can handle arbitrary long identifiers, is changing `name` of `symbol_t` from `char[R_BIN_MACH0_STRING_LENGTH]` to `char *` and storing the pointer returned by `get_name()` there. It would require additional cleanup when `bin` object is destroyed, to avoid memory leaks.

**Comment by trufae** [comment]
yes, symbol names should have no fixed size, so changing to char * is imho the way to go. It will be neat if you are willing to work on that change. Can you submit a PR for it?

thanks!

**Comment by trufae** [comment]
cc @mrmacete

**Comment by phakeobj** [comment]
>  It will be neat if you are willing to work on that change. Can you submit a PR for it?
certainly.

**Comment by trufae** [comment]
Awesome! thanks
