### ISSUE TITLE
DWARF crash

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#17076]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 31 x86-64bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | unknown
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 27076 @ linux-x86-64 git.4.4.0-283-g08c36524d commit: 08c36524d1c87264835ff694446148da00de8024 build: 2020-06-15__13:16:39

### Expected behavior
No crash.

### Actual behavior
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==968539==ERROR: AddressSanitizer: SEGV on unknown address 0x000030303030 (pc 0x7f0be599db26 bp 0x7ffeae745280 sp 0x7ffeae7449a8 T0)
==968539==The signal is caused by a READ memory access.
    #0 0x7f0be599db25  (/lib64/libasan.so.5+0x126b25)
    #1 0x7f0be59142b4  (/lib64/libasan.so.5+0x9d2b4)
    #2 0x7f0be59150f6 in __interceptor_vfprintf (/lib64/libasan.so.5+0x9e0f6)
    #3 0x7f0be59151fe in fprintf (/lib64/libasan.so.5+0x9e1fe)
    #4 0x7f0be2a48fa7 in r_bin_dwarf_parse_comp_unit ../libr/bin/dwarf.c:1534
    #5 0x7f0be2a49d69 in r_bin_dwarf_parse_info_raw ../libr/bin/dwarf.c:1611
    #6 0x7f0be2a4ab0e in r_bin_dwarf_parse_info ../libr/bin/dwarf.c:1745
    #7 0x7f0be31969e7 in bin_dwarf ../libr/core/cbin.c:899
    #8 0x7f0be31ad48a in r_core_bin_info ../libr/core/cbin.c:4083
    #9 0x7f0be319075a in r_core_bin_set_env ../libr/core/cbin.c:208
    #10 0x7f0be33d46ff in r_core_file_do_load_for_io_plugin ../libr/core/cfile.c:437
    #11 0x7f0be33d5da7 in r_core_bin_load ../libr/core/cfile.c:643
    #12 0x7f0be5534cda in r_main_radare2 ../libr/main/radare2.c:1054
    #13 0x401522 in main ../binr/radare2/radare2.c:96
    #14 0x7f0be536b1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #15 0x40115d in _start (/home/rschiron/.local/bin/radare2+0x40115d)
```

### Steps to reproduce the behavior 
```
$ radare2 test/bins/fuzzed/r2_ir_sdb_set_internal
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
https://github.com/radareorg/radare2/issues/10465 seems the same bug, however a lot of time has passed, so I'm creating a new one. Apart from the (wrong) workaround done in https://github.com/radareorg/radare2/commit/bd1bab05083d80464fea854bf4b5c49aaf1b8401 (instead of ` if (name > 1024)` we should just check for `if (name)`) there is something wrong there.

In `r_bin_dwarf_parse_comp_unit`:
```C
			memset (&cu->dies[cu->length].attr_values[i], 0, sizeof (cu->dies[cu->length].attr_values[i]));
			buf = r_bin_dwarf_parse_attr_value (buf, buf_end - buf,
					&da->decls[abbr_code - 1].specs[i],
					&cu->dies[cu->length].attr_values[i],
					&cu->hdr, debug_str, debug_str_len);
			if (cu->dies[cu->length].attr_values[i].name == DW_AT_comp_dir) {
				const char *name = cu->dies[cu->length].attr_values[i].encoding.str_struct.string;
				if (name) { // solve some null derefs
					sdb_set (s, "DW_AT_comp_dir", name, 0);
```
This code expects to always have a valid `encoding.str_struct.string` when `attr_values[i].name == DW_AT_comp_dir`. However, that does not seem the case for the testing binary. We should choose what to do in this case. Shall we just enforce the value `encoding.str_struct.string` to be set in `r_bin_dwarf_parse_attr_value` or does the DWARF spec says something else?

**Comment by ret2libc** [comment]
Necessary for https://github.com/radareorg/radare2/pull/17075

**Comment by HoundThe** [comment]
Yeah one way to fix this is move the string structure outside of the union and check if its set or just checking if the attribute form is of a string type (the latter seems better), because the segfault is caused by reading DATA4 and interpreting it as a string pointer which results in dereferencing invalid pointer.

Before fixing this tho, I don't understand if this is useful anymore because in real binary there are multiple comp_dirs, one for each compilation unit, before I started working on the debug_info parsing, it could only parse single compilation unit so it might seemed fine, but now it just rewrites each comp dir so only the last stays I think.

**Comment by ret2libc** [comment]
> Yeah one way to fix this is to move the string structure outside of the union and check if its set or just checking if the attribute form is of a string type AKA if we're expecting string then check if the attr_form is of a string type, DW_FORM_strp or DW_FORM_string etc. (this solution seems better to me, but this reminds that malformed read of DW_FORM_string could also result in a crash), because the segfault is caused by reading DATA4 and interpreting it as a string pointer which results in dereferencing invalid pointer.

I don't think moving the string outside the struct is the best approach. We should probably check if the string was ever set... In any case, there is some logic bug there, as the code assumes that if there is DW_AT_comp_dir, then string is set, which is not always true apparently (and in any case we should not crash. Either report just an error, or handle it somehow).

> Before fixing this tho, I don't understand if this is useful anymore because in real binary there are multiple comp_dirs, one for each compilation unit, before I started working on the debug_info parsing, it could only parse single compilation unit so it might seemed fine, but now it just rewrites each comp dir so only the last stays I think.

I'm not sure either at the moment. I'm not very familiar with DWARF, but I should probably have a look eventually at the spec :)

**Comment by HoundThe** [comment]
Yeah, thats why I think checking if the DW_FORM is of a string type is better

**Comment by HoundThe** [comment]
I think this crash is fixed, can we close this?

**Comment by ret2libc** [comment]
Yes thanks!
