### ISSUE TITLE
Minor *BSD build warnings

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17072]
```
dwarf.c:391:7: warning: initializing 'unsigned char *' with an expression of type 'const unsigned char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        ut8 *tmp_buf = buf; // So I can skip parsing DWARF 5 headres for now
             ^         ~~~
1 warning generated.
p/debug_native.c:1526:2: warning: list filedescriptors not supported for this platform [-W#warnings]
#warning list filedescriptors not supported for this platform
 ^
p/debug_native.c:95:12: warning: unused function 'r_debug_handle_signals' [-Wunused-function]
static int r_debug_handle_signals(RDebug *dbg) {
           ^
p/debug_native.c:175:12: warning: unused function 'r_debug_native_select' [-Wunused-function]
static int r_debug_native_select(RDebug *dbg, int pid, int tid) {
           ^
3 warnings generated.
/home/build/radare2/libr/..//libr/bin/p/../format/elf/elf.c:74:19: warning: unused function 'UTX_MUL' [-Wunused-function]
static inline int UTX_MUL(ut64 *r, ut64 a, ut64 b) {
                  ^
1 warning generated.
/8051/8051_disas.o p/../arch/8051/8051_disas.c
p/../arch/8051/8051_disas.c:64:14: warning: unused function 'r_8051_disas' [-Wunused-function]
static char *r_8051_disas(ut64 pc, const ut8 *buf, int len, int *olen) {
             ^
1 warning generated.
```
See more at:
- https://azusa.runners.sr.ht/logs/340070/build/log
- https://azusa.runners.sr.ht/logs/340071/build/log

**Comment by officialcjunior** [comment]
How should I get around the error `-Wunused-function`?
I tried putting `R_UNUSED` from `r_types.h` as an attribute on one of those functions, but it gave me:
` warning: GCC does not allow '__unused__' attribute in this position on a function definition`

**Comment by trufae** [comment]
Fixing the code. 
 adding compiler specific attributes is never a good idea

**Comment by officialcjunior** [comment]
Alright.
For the warnings about macro redefinitions, can I rename the macros?

**Comment by XVilka** [comment]
@officialcjunior yes, renaming the macros is the best way to do this.

**Comment by officialcjunior** [comment]
I think the errors related to the macro redefinition has been fixed and you can remove them out.

https://github.com/radareorg/radare2/blob/14f82ee3012e10b56674a01c360ac1fbc4b4bf52/libr/bin/format/dmp/dmp_specs.h#L24

https://github.com/radareorg/radare2/blob/14f82ee3012e10b56674a01c360ac1fbc4b4bf52/libr/core/disasm.c#L481

**Comment by XVilka** [comment]
Thanks, updated, see also updated build logs.

**Comment by trufae** [comment]
No need to keep issues open for old build logs, fixing warnings on CI builds and local builds is kind of a routine in r2land
