### ISSUE TITLE
Add JSON support for variable xref (afvx, afvR, afvW)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radare2#17108]
**Is your feature request related to a problem? Please describe.**

The commands `afvx`, `afvR`, `afvW` and `axv`, shows references to a variable inside the function:
Currently, the output of the variable references isn't supporting the JSON format.

```
[0x0804846b]> afvx
afvR
    arg_8h  0x8048471,0x804848a,0x8048499,0x80484a8,0x80484b0,0x80484c5,0x80484d4,0x80484e3,0x80484eb,0x80484fd
    var_4h  0x8048487,0x8048496,0x80484a5,0x80484ad,0x80484c2,0x80484d1,0x80484e0,0x80484e8,0x80484fa,0x8048509,0x8048518
afvW
    arg_8h
    var_4h  0x804847b
```

**Describe the solution you'd like**

It would be great to have these commands support the JSON output by appending the `j` letter to each command

**Comment by XVilka** [comment]
I think it's important enough to have in 4.5.0

**Comment by kuqadk3** [comment]
Maybe it's better to just output all those stuff in one command afvj

https://github.com/radareorg/radare2/blob/2ffa790e0aec3c77a596ce5b76f1ea470956f534/libr/core/cmd_anal.c#L1208-L1218
