### ISSUE TITLE
Ignore option for `r2r`

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17105]
Currently there is no option to ignore some particular type of the tests, e.g. "debug" tests.
It would be nice to have the option `-I @debug` to ignore them, similar like we have `@json`, `@unit`, etc test types.

**Comment by XVilka** [comment]
@kazarmy since you are working on `r2r` lately, maybe you could take a look at this one?

**Comment by kazarmy** [comment]
wasn't working on every part of r2r though
