### ISSUE TITLE
Error opening empty string files

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17100]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.15
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | 50de58171e92f57b191a4f28cf3a0cdcf96e6e2e

### Expected behavior

**

### Actual behavior

```
**$ r2 ""
WARNING: r_io_def_mmap_check_default: assertion 'filename && *filename' failed (line 160)
WARNING: r_io_def_mmap_check_default: assertion 'filename && *filename' failed (line 160)
Missing file to open
```

other tools also fail in the same way:

```
$ rabin2 -s ""
WARNING: r_io_def_mmap_check_default: assertion 'filename && *filename' failed (line 160)
Couldn't open bin for file ''
r_bin: Cannot open file
WARNING: r_core_file_free: assertion 'cf' failed (line 964)
```

### Steps to reproduce the behavior 

Open the shell and run the tools using "" as filename

### Additional Logs, screenshots, source-code,  configuration dump, ...

nothing so far

**Comment by ret2libc** [comment]
Is the issue about the `WARNING`s messages?

**Comment by trufae** [comment]
yes, and probably the unnecessary amount of things done before failing can be shortened

**Comment by phakeobj** [comment]
would it make sense to bail out before calling `r_core_file_open()` in `radare2.c:1026` if `pfile[0] == '\0'`?

**Comment by trufae** [comment]
Yes, that could be an option. But actually i dont think opening "" should
be valid in any way

**Comment by phakeobj** [comment]
right, there's no sense in processing anything if we already know pfile is an empty string. I would say radare2.c:690 is the earliest place we can tell that.

**Comment by trufae** [comment]
all the other tools are failing in the same way (try rabin2, radiff2...) so
the patch must handle all the usercases and we need tests

**Comment by ret2libc** [comment]
@phakeobj wants to work on that, according to IRC messages. Is that ok with you @trufae ? @phakeobj  do you want to create a PR with the proposed changes and related tests?

**Comment by trufae** [comment]
yep. i'm happy about that. i'll review the PR when submitted.

thanks!

**Comment by phakeobj** [comment]
> @phakeobj do you want to create a PR with the proposed changes and related tests?
you bet

**Comment by phakeobj** [comment]
> all the other tools are failing in the same way (try rabin2, radiff2...)

actually, I was only able to trigger the assert with `radare2` and `rabin2`. Other tools exit cleanly (e.g. https://asciinema.org/a/IKz90CuiNaS6T0ZZwH1FbzPVR) am I missing something @trufae ?
