### ISSUE TITLE
set bitness for rax2

### ISSUE THREAD

**Issue by unclenull** [radareorg/radare2#17112]
**Is your feature request related to a problem? Please describe.**
I want rax2 convert a negative number to hex of 32bit in a 64bit machine. e.g. 

`rax2 -1` -> 0xffffffff instead of 0xffffffffffffffff

manually truncate it is cumbersome.

**Comment by radare** [comment]
use `rax2 1u32`

**Comment by trufae** [comment]
But i do understand the ability to define the bitness boundaries for RNum. The 1u32 is just a workaround for this case, and in fact, it should be -1u32 and we may want to have -b 32 -b 16 -b 64 in rax2 to specify this `dim`.. but -b is already handled and RNum doesnt rsupports such thing yet.
