### ISSUE TITLE
Stack Smashing with less (~...) when the input buffer > 0x200

### ISSUE THREAD

**Issue by 08A** [radareorg/radare2#17122]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24819 @ linux-x86-64 git.4.4.0-322-g5124bef43 commit: 5124bef4343d114a1e781aaa79aca3a36bcbf713 build: 2020-06-22__09:27:13

### Expected behavior
No Stack Mash

### Actual behavior
![2020-06-22-093059_404x62_scrot](https://user-images.githubusercontent.com/32521367/85260514-18df2900-b46b-11ea-82a2-eb0b27242a12.png)

![2020-06-22-093658_714x561_scrot](https://user-images.githubusercontent.com/32521367/85261067-f39eea80-b46b-11ea-95c9-cbabc7fbea28.png)

### Steps to reproduce the behavior 
```
> aaa
> afl~...
> # (Move the mouse wheel until there is so much garbage char that you can't see the input line and press CTRL-C, it complicated to reproduced every time)
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
[bin.zip](https://github.com/radareorg/radare2/files/4811808/bin.zip)

**Comment by ret2libc** [comment]
@08A do you intend to work on it?

**Comment by 08A** [comment]
I can try but i don't have a lot of time to spare for radare2 right now.

**Comment by ret2libc** [comment]
> I can try but i don't have a lot of time to spare for radare2 right now.

Ok, no problem just wanted to know ;)

**Comment by swoops** [comment]
For anyone working on this. 

I peeked at this a bit. This also happens if you just hold the 'a' key for long enough (>0x200 chars). The overflow happens on line 261 of hud.c [here](https://github.com/radareorg/radare2/blob/master/libr/cons/hud.c#L261)

```
memcpy (hud_prompt + I(line)->buffer.index, "|", 1); # <- overflow here!
```
Which is why you see the `\x7c` ('|') in the stack. There does not appear to be any bounds check on `I(line)->buffer.index` or `I(line)->buffer.length`. Holding `a` in the hud will cause those values to grow arbitrarily large.

I might try to look at this more later.

**Comment by 08A** [comment]
> I peeked at this a bit. This also happens if you just hold the 'a' key for long enough (>0x200 chars). The overflow happens on line 261 of hud.c [here](https://github.com/radareorg/radare2/blob/master/libr/cons/hud.c#L261)

Indeed this is not related to #16963

**Comment by 08A** [comment]
@ret2libc @swoops I pushed the simple fixed found by @swoops, i will try to implement this function with a buffer so no more boundary check.

**Comment by 08A** [comment]
```
257                 int i;
258                 for (i = I(line)->buffer.length; i > I(line)->buffer.index; i--) {
259                         hud_prompt[i] = hud_prompt[i - 1];
260                 }
```

Do you know the purpose of those lines?

**Comment by 08A** [comment]
I those line are not useful we could remove hud_prompt buffer and use the string format of printf

**Comment by ret2libc** [comment]
> ```
> 257                 int i;
> 258                 for (i = I(line)->buffer.length; i > I(line)->buffer.index; i--) {
> 259                         hud_prompt[i] = hud_prompt[i - 1];
> 260                 }
> ```
> 
> Do you know the purpose of those lines?

I have no idea... but all that code with hud_prompt seems a bit messy :/ Feel free to improve it.

**Comment by 08A** [comment]
@deepakchethan  Any idea?
(You seems to be the creator of this piece of code (git blame))
https://github.com/radareorg/radare2/issues/17122#issuecomment-650103627
https://github.com/radareorg/radare2/pull/17152#issuecomment-650110407

**Comment by 08A** [comment]
> i will try to implement this function with a buffer so no more boundary check.

The buffer implementation slow to much the program, imho it is not worth it.
