### ISSUE TITLE
Show "static" or "asan" in r2 -v

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17166]
**Is your feature request related to a problem? Please describe.**

The idea behind this FR is to show if the build of r2 you are running have some features enabled, other configure flags can be added too, this will be handy for filling the issue report.

**Describe the solution you'd like**

r2 -v is not showing all the possible information we may want to know when someone is reporting an issue. I propose exposing this info in r2 -jv for json version information (which is not yet implemented)

* [ ] configure flags
* [ ] plugins loaded
* [ ] radare2rc (b64)
* [ ] static
* [ ] asan
* [ ] release/git
* [ ] capstone version
* [ ] ...

**Describe alternatives you've considered**

🤔

**Additional context**

ref https://github.com/radareorg/radare2/issues/17166

**Comment by ret2libc** [comment]
> this will be handy for the 

? for what?

**Comment by trufae** [comment]
updated

**Comment by XVilka** [comment]
I second this. Especially the JSON version. It will be handy for this: https://github.com/BinaryAnalysisPlatform/bap/issues/1163

**Comment by Maijin** [comment]
Definitely +1 on this, the more information we can get from -v, the better we will be able to help people on Telegram/IRC etc.

**Comment by trufae** [comment]
i think we are good now with the current output in r2 -v. we can use this ticket in the future for ideas, but no longer a blocker thing
