### ISSUE TITLE
Filling issues is tedious and error prone

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17165]
When creating an issue people must fill a table with information from the running environment. i think this can be spitted out by r2 with a core plugin or a specific flag so we can create an http url to click in the console and get the bug report issue filled with the OS/r2/fileformat/..

### Work environment

see below ----v

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior

We can spit out this table when running r2 -vv path/to/file <- to get filetype , or with an r2pm pkg using an r2-extras script.

### Actual behavior

The user must fill the form every time (r2-2.4 is very old)

### Steps to reproduce the behavior 

- open github
- click issues
- click new issue
- pain

### Additional Logs, screenshots, source-code,  configuration dump, ...

nope

**Comment by karliss** [comment]
The part that annoys me is that when copying `r2 -v` output into the table it gets split across two lines like this:
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | rradare2 4.5.0-git 26201 @ linux-x86-64 git.4.4.0-303-g70cad635b
commit: 70cad635b9e3fe4b6bc8bdf962e28020520c5272 build: 2020-06-16__20:22:40

So you have to do extra steps to replace the newline with space.

**Comment by ret2libc** [comment]
I agree it would be cool to have a way to create the template to report issues within r2. It was also requested through the form I created some days ago about commands/help in r2.

**Comment by XVilka** [comment]
We can create simple Python script "sys/report_issue.py" which will collect
the information about OS/platform/r2 version then using the GitHub API open
an issue for you.

**Comment by karliss** [comment]
Instead of actually opening an issue it is possible to open the issue creation page with data prefilled like this https://github.com/radareorg/radare2/issues/new?title=TestIssue&body=This%20should%20not%20save%20the%20issue .

**Comment by condret** [comment]
I personally dislike these templates as a whole. It feels bureaucratic and overall doesn't fit to the bleeding edge (let's go and do fast progress, even if we break something) mentality, that once attracted me towards r2. However I can understand, that you want to know which version of r2 the reporter is using (in some cases). I'd remove these templates completly meanwhile providing the plugin that creates issue with that table.

**Comment by trufae** [comment]
Closing
