### ISSUE TITLE
zignature mask from `zj`  is differ from  `z`

### ISSUE THREAD

**Issue by terrynini** [radareorg/radare2#17179]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Ubuntu18.04.2/x86_64/64
| File format of the file you reverse (mandatory)      |  ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24833 @ linux-x86-64 git.4.4.0-346-gf061b49c1 commit: f061b49c14d05f37109901037744ed51652f5cac build: 2020-06-29__22:02:16

### Expected behavior

`zj` should ouput json format  of zignature which includes `mask` for mask unwanted relative bytes in instructions  

### Actual behavior

zignature `mask` from `zj`  is differ from `z`, and it's identical to zignature `bytes` 

### Steps to reproduce the behavior 

asciinema won't change to newline, so I directly copy from terminal
And this is not a issue relative to target binary, forgive me not to attach binary

```
~ > cd ~/Desktop
~/Desktop > r2 /bin/ls
Dynamic tag 12 not handled
Dynamic tag 13 not handled
Dynamic tag 25 not handled
Dynamic tag 27 not handled
Dynamic tag 26 not handled
Dynamic tag 28 not handled
Dynamic tag 1879047925 not handled
Dynamic tag 21 not handled
 -- Find wide-char strings with the '/w <string>' command
[0x00005850]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x00005850]> zaf entry0 test
[0x00005850]> z
test:
  bytes: 31ed4989d15e4889e24883e4f050544c8d05ca0a0100488d0d530a0100488d3d1ce6ffffff155ea72100
  mask: ffffffffffffffffffffffffffffffff000000000000ff000000000000ff000000000000ff0000000000
  graph: cc=1 nbbs=1 edges=0 ebbs=1 bbsum=42
  addr: 0x00005850
  realname: entry0
  vars: r119
  types: func.entry0.args=1, func.entry0.arg.0="int64_t,arg3"
  bbhash: 89dd69b234afa73fa67574700e3afe53dded6b77f78cf19ffc79f600cadba2b8
[0x00005850]> zj
[{"name":"test","bytes":"31ed4989d15e4889e24883e4f050544c8d05ca0a0100488d0d530a0100488d3d1ce6ffffff155ea72100","mask":"31ed4989d15e4889e24883e4f050544c8d05ca0a0100488d0d530a0100488d3d1ce6ffffff155ea72100","graph":{"cc":1,"nbbs":1,"edges":0,"ebbs":1,"bbsum":42},"addr":22608,"realname":"entry0","refs":[],"xrefs":[],"vars":["r119"],"types":[{"name":"arg3","type":"int64_t"}],"hash":{"bbhash":"89dd69b234afa73fa67574700e3afe53dded6b77f78cf19ffc79f600cadba2b8"}}]
[0x00005850]> 
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

None

**Comment by karliss** [comment]
Copy paste bug:
```
	} else if (format == 'j') {
		pj_ks (pj, "bytes", strbytes);
		pj_ks (pj, "mask", strbytes);
	} else {
		a->cb_printf ("  bytes: %s\n", strbytes);
		a->cb_printf ("  mask: %s\n", strmask);
	}
```

**Comment by terrynini** [comment]
I thought it was deserialize problem, ok ... you are faster
It's there any document about source code of radare2 ?

**Comment by ret2libc** [comment]
This should be fixed with the commit mentioned above. Closing.
