### ISSUE TITLE
Wrong tcache parsing between different glibc version

### ISSUE THREAD

**Issue by meowmeowxw** [radareorg/radare2#17205]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86-64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86-64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24844 @ linux-x86-64 git.4.4.0-353-g114a5a594
commit: 114a5a59438be07e5ffea8f757ab0df242f0be41 build: 2020-07-03__17:08:09

Currently the tcache is parsed using the tcache_perthread_struct:  https://github.com/radareorg/radare2/blob/80202e6ad5b45efc3de5f2210019eb948dd797b6/libr/include/r_heap_glibc.h#L148
in: https://github.com/radareorg/radare2/blob/80202e6ad5b45efc3de5f2210019eb948dd797b6/libr/core/linux_heap_glibc.c#L877

This works fine for glibc version >= 2.30,  however in 2.29 and in precedent versions the struct is defined as: 
https://elixir.bootlin.com/glibc/glibc-2.29/source/malloc/malloc.c#L2916

With char instead of u_int16_t for `count`

### Expected behavior
```
$ r2 -e dbg.profile=profile.rr2 -i script.rr2 -d ./tcache-2.27

Tcache main arena @ 0x7fd2785589e0
bin : 0, items : 6, fd :0xd02740->0xd02720->0xd02700->0xd026e0->0xd026c0->0xd026a0
```

### Actual behavior

```
$ r2 -e dbg.profile=profile.rr2 -i script.rr2 -d ./tcache-2.27

Do you want to print 4 lines? (y/N)
bin :33, items :351, fd :0xfffffffffffffff0->0xffffffffffffffef->0xfffffffffffffff0->0xffffffffffffffef->0xfffffffffffffff0->0xffffffffffffffef->0xfffffffffffffff0->0xffffffffffffffef->0xfffffffffffffff0->0xffffffffffffffef
[...] more output
```

### Steps to reproduce the behavior

I provide a zip with a simple program that malloc and free some memory (to put chunk inside tcache),  to use the version for glibc2.27 use:

```
$ r2 -e dbg.profile=profile.rr2 -i script.rr2 -d tcache-2.27
```

And it should work, if not try:

```
$ gcc tcache.c -o tcache-2.27 -no-pie
$ patchelf --set-interpreter ./ld-2.27.so tcache-2.27
$ # RUN
$ LD_PRELOAD=./libc-2.27.so ./tcache-2.27
```

I would like to work on it, however I don't know what approach should I use to solve the problem.
Currently we are reading the memory where the tcache_perthread_struct is, and we pass the memory values inside our tcache_perthread_struct, which makes sense if we have only one type of tcache_perthread_struct (but we need two different type).

So I thought about adding a new struct inside r_heap_glibc.h:

```c
typedef struct r_tcache_perthread_struct_old_32 {
	ut8 counts[TCACHE_MAX_BINS];
	ut32 entries[TCACHE_MAX_BINS];
} RHeapTcacheOld_32;

typedef struct r_tcache_perthread_struct_old_64 {
	ut8 counts[TCACHE_MAX_BINS];
	ut64 entries[TCACHE_MAX_BINS];
} RHeapTcacheOld_64;
```

And then create two function inside linux_heap_glibc.c:

```
static void GH(parse_tcache_old)(RCore *core, GH(RHeapTcacheOld) *tcache_heap);
static void GH(parse_tcache)(RCore *core, GH(RHeapTcache) *tcache_heap);
```

The two function would have the same exact code so it wouldn't be a super clean solution. The codeof the function would be this `for`: https://github.com/radareorg/radare2/blob/80202e6ad5b45efc3de5f2210019eb948dd797b6/libr/core/linux_heap_glibc.c#L882

Another approach is to not parse all the memory at once, but parsing the tcache step by step like gef is doing: 
https://github.com/hugsy/gef/blob/1d5cffd459bc25e0b02657d0300cb51609b8df6c/gef.py#L6425 and https://github.com/hugsy/gef/blob/1d5cffd459bc25e0b02657d0300cb51609b8df6c/gef.py#L722

In this way they only check the glibc version twice which is not a bad idea.

Another approach would be to use `union` and implement some getter and setter, example:

```c
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <sys/types.h>

enum tcache_type {NEW, OLD};

typedef struct r_heap_old {
	char counts[10];
	void* entries[10];
} RHeapTcacheOld;

typedef struct r_heap_t {
	u_int16_t counts[10];
	void* entries[10];
} RHeapTcache;

typedef struct {
	enum tcache_type type;
	union {
		RHeapTcache heap_tcache;
		RHeapTcacheOld heap_tcache_old;
	} RHeapUnion;
} RHeap;

int getCount(RHeap *heap, int index) {
	if (heap->type == OLD) {
		return heap->RHeapUnion.heap_tcache_old.counts[index];
	} else {
		return heap->RHeapUnion.heap_tcache.counts[index];
	}
}

void setCount(RHeap *heap, int index, int value) {
	if (heap->type == OLD) {
		heap->RHeapUnion.heap_tcache_old.counts[index] = value;
	} else {
		heap->RHeapUnion.heap_tcache.counts[index] = value;
	}
}

int main(int argc, char **argv) {
	RHeap *heap = malloc(sizeof(RHeap));
	heap->type = NEW;
	setCount(heap, 0, 10);
	printf("get: %d\n", getCount(heap, 0));
	return 0;
}
```

What approach should I use, or do you have any other suggestion?

### Additional Logs, screenshots, source-code,  configuration dump, ...

[test-tcache.zip](https://github.com/radareorg/radare2/files/4872992/test-tcache.zip)

**Comment by ret2libc** [comment]
This would be a nice addition! I would not call the types and functions "old" and "new" though, but with something a bit more expressive (e.g. pre_227, post_227 or something like that, where it is a bit clearer what is "old" and what is "new". Also, in case of new differences in the future we can easily adapt).

Personally, I prefer the second approach better (the one with union), but I'm ok also with the other approach. I would say whatever you prefer works, at least for me. And don't hesitate to start working on a PR for this ;)

**Comment by XVilka** [comment]
@ret2libc there is already PR for this: https://github.com/radareorg/radare2/pull/17206
