### ISSUE TITLE
Bad Function names example: projectInit

### ISSUE THREAD

**Issue by RHL120** [radareorg/radare2#17207]
I want to contribute to this project so I decided to fix a problem I have been having with projects but there is a small problem 
function names are very bad for example the function projectInit should propably be called mkProjectDir or something similar

**Comment by ret2libc** [comment]
Feel free to create a PR with the proposed changes, we are always open to improvements. However, I would advice you to just ignore the project code for now as it has been sort of abandoned for a while and we are already working on a replacement.
