### ISSUE TITLE
Error while starting radare2, python plugins crash

### ISSUE THREAD

**Issue by chase1635321** [radareorg/radare2#17235]
# |ERROR| Invalid command '�3�dU' (0xffffffa0) while starting radare2

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04, x86, 64 bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24886 @ linux-x86-64 git.4.4.0-394-g31fe7b29e commit: 31fe7b29e397b96ecd9962356c241e5b68453a25 build: 2020-07-07__10:56:02

### Expected behavior

Radare2 starts cleanly.

### Actual behavior

On starting r2, it prints an error message. Also, if installed, python plugins crash on load. Example output is shown below.

```
$ r2 /bin/ls
|ERROR| Invalid command ' ��IV' (0x20)
 -- Default scripting languages are NodeJS and Python.
[0x00005850]> 
```

### Steps to reproduce the behavior 

Simply start radare2.

### Additional Logs, screenshots, source-code,  configuration dump, ...

I did some digging, and this issue first appears at commit c706d0b69f3a7192100664c218910104122fbc99.

**Comment by ret2libc** [comment]
How did you install the python plugin?

**Comment by chase1635321** [comment]
To be clear, the error message is printed whether or not any python plugin is installed. Plugin tested both by placing in `plugins/` folder and with `-i`

**Comment by ret2libc** [comment]
Could you provide the output of `radare2 -V`?

**Comment by chase1635321** [comment]
$ r2 -v
radare2 4.5.0-git 24886 @ linux-x86-64 git.4.4.0-394-g31fe7b29e
commit: 31fe7b29e397b96ecd9962356c241e5b68453a25 build: 2020-07-07__14:20:55
$ r2 -V
4.4.0-394-g31fe7b29e  r2
4.4.0-394-g31fe7b29e  r_anal
4.4.0-394-g31fe7b29e  r_lib
4.4.0-394-g31fe7b29e  r_egg
4.4.0-394-g31fe7b29e  r_asm
4.4.0-394-g31fe7b29e  r_bin
4.4.0-394-g31fe7b29e  r_cons
4.4.0-394-g31fe7b29e  r_flag
4.4.0-394-g31fe7b29e  r_core
4.4.0-394-g31fe7b29e  r_crypto
4.4.0-394-g31fe7b29e  r_bp
4.4.0-394-g31fe7b29e  r_debug
4.4.0-394-g31fe7b29e  r_main
4.4.0-394-g31fe7b29e  r_hash
4.4.0-394-g31fe7b29e  r_fs
4.4.0-394-g31fe7b29e  r_io
4.4.0-394-g31fe7b29e  r_magic
4.4.0-394-g31fe7b29e  r_parse
4.4.0-394-g31fe7b29e  r_reg
4.4.0-394-g31fe7b29e  r_sign
4.4.0-394-g31fe7b29e  r_search
4.4.0-394-g31fe7b29e  r_syscall
4.4.0-394-g31fe7b29e  r_util

**Comment by trufae** [comment]
Can you provide a script, asciinema or something more clear to show us how to reproduce this issue, it seems to me that you placed a binary file in a scripts directory and r2 is trying to interpret it as commands.

Also, i miss the information about which plugins you have installed, the contents of your radare2rc

**Comment by chase1635321** [comment]
Ok here's an [asciinema](https://asciinema.org/a/346002), in which I did the following things:

- Uninstalled and reinstalled the latest r2 version
- Showed the error message by opening several files
- Reverted to 4.4.0
- Showed that the errors go away

radare2rc is empty and the only plugin installed is lang-python.

**Comment by ret2libc** [comment]
> Ok here's an [asciinema](https://asciinema.org/a/346002), in which I did the following things:
> 
> * Uninstalled and reinstalled the latest r2 version
> * Showed the error message by opening several files
> * Reverted to 4.4.0
> * Showed that the errors go away
> 
> radare2rc is empty and the only plugin installed is lang-python.

Could you try recompiling the Lang python plugin as well?

**Comment by chase1635321** [comment]
The issue persists. I tried both recompiling lang-python and uninstalling it completely.

**Comment by chase1635321** [comment]
Does no one else have this issue? If so, I'll wipe my OS and reinstall which I've been planning to do anyway, but I was concerned that c706d0b69f3a7192100664c218910104122fbc99 introduced a bug

**Comment by trufae** [comment]
wipe your ~/.local/share/radare2 first

why do you think this commit introduced a bug, seems unrelated to your problem, did you tried compiling a specific commit before and after to repro the issue? can you place a breakpoint in the given error message to see who is trying to run this trashy command? wha'ts the relationship with the python plugin? which plugin did you installed. if you uninstall it the error is gone?

Because after your "To be clear, the error message is printed whether or not any python plugin is installed" it seems to me like the issue is not related to python. And no i cant reproudce this issue, so i would suggest removing your local r2 config path and see if that solves the issue or use a debugger to catch the call

**Comment by XVilka** [comment]
@chase1635321 could you please retry with the latest master? Python plugins are now autotested with our CI, and locally I don't see any problems.

**Comment by chase1635321** [comment]
@trufae Issue persists after wiping ~/.local/share/radare2. I was pointing out this commit because I tried recompiling a bunch of different commits, and the issue first appears for me on that one. This includes with no plugins installed.

@XVilka Issue persists after updating to latest master.

**Comment by XVilka** [comment]
Could you please try to recompile it with ASAN and UBSAN?

**Comment by chase1635321** [comment]
@XVilka 

```
$ r2 -
=================================================================
==18881==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x619000051380 at pc 0x7f323211f6a2 bp 0x7ffc344b48e0 sp 0x7ffc344b4088
READ of size 1025 at 0x619000051380 thread T0
    #0 0x7f323211f6a1 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x776a1)
    #1 0x7f3229dfd0e7 in r_core_cmd_lines /home/chase/software/radare2/libr/core/cmd.c:6804
    #2 0x7f3229dfd499 in r_core_cmd_file /home/chase/software/radare2/libr/core/cmd.c:6858
    #3 0x7f3229e3e16a in r_core_parse_radare2rc /home/chase/software/radare2/libr/core/cconfig.c:3725
    #4 0x7f3231348605 in r_main_radare2 /home/chase/software/radare2/libr/main/radare2.c:834
    #5 0x564013e52908 in main /home/chase/software/radare2/binr/radare2/radare2.c:96
    #6 0x7f32301d9b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #7 0x564013e523e9 in _start (/home/chase/software/radare2/binr/radare2/radare2+0x13e9)

0x619000051380 is located 0 bytes to the right of 1024-byte region [0x619000050f80,0x619000051380)
allocated by thread T0 here:
    #0 0x7f3232186f30 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef30)
    #1 0x7f32318d3d07 in r_file_slurp /home/chase/software/radare2/libr/util/file.c:356
    #2 0x7f3229dfd465 in r_core_cmd_file /home/chase/software/radare2/libr/core/cmd.c:6853
    #3 0x7f3229e3e16a in r_core_parse_radare2rc /home/chase/software/radare2/libr/core/cconfig.c:3725
    #4 0x7f3231348605 in r_main_radare2 /home/chase/software/radare2/libr/main/radare2.c:834
    #5 0x564013e52908 in main /home/chase/software/radare2/binr/radare2/radare2.c:96
    #6 0x7f32301d9b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x776a1) in strdup
Shadow bytes around the buggy address:
  0x0c3280002220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280002230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280002240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280002250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280002260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3280002270:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280002280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280002290: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c32800022a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c32800022b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c32800022c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==18881==ABORTING

```

**Comment by ret2libc** [comment]
@chase1635321 are you sure your ~/.radare2rc is empty? Could you try to delete it?

**Comment by trufae** [comment]
Mixed builds of r2 maybe? Try r2 -vv and check your system library path for stale r2 libs and plugins

**Comment by chase1635321** [comment]
Unfortunately none of the above revealed the issue for me. 

Ok it seems like, regardless of what the issue is, it's a problem with my system rather than radare2, so I'll just wipe my system and re-install. If the issue persists I'll re-open this issue.

**Comment by ret2libc** [comment]
Thanks @chase1635321 ! Let us know ;)
