### ISSUE TITLE
Visual mode freeze when entering debugger panel

### ISSUE THREAD

**Issue by qwuau06** [radareorg/radare2#17257]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24916 @ linux-x86-64 git.4.4.0-411-g7ee93fb45
|commit | 7ee93fb4573a7c165100483ff8848e3e3c84880e build: 2020-07-11__14:27:27

### Expected behavior

Enter debugger panel and show memory graph. om should show correct mapped spaces.

### Actual behavior

r2 hang when using Vpp. om shows only one block with rwx permission. strace shows it hangs at futex. 

### Steps to reproduce the behavior 

[target.zip](https://github.com/radareorg/radare2/files/4907555/target.zip)
```
r2 -d a.out
om
Vpp
```

_strace log when it hangs:_

> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> [pid 249427] read(8, 0x558bf3558120, 1024) = -1 EACCES (Permission denied)
> ....

**Comment by ret2libc** [comment]
First faulty commit is e56c78479111c3dc804bdfd86af8558730d5e5c3
