### ISSUE TITLE
Debugger broken on Alpine linux

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17278]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux localhost 5.4.12-1-virt #2-Alpine SMP Thu, 16 Jan 2020 12:53:54 UTC x86_64 Linux
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            |  x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24935 @ linux-x86-64 git.4.4.0-411-g7ee93fb45

### Expected behavior

working debugger

### Actual behavior
![Screenshot 2020-07-14 at 14 48 43](https://user-images.githubusercontent.com/6431515/87427575-48540200-c5e1-11ea-98c1-9fa75f3f6adc.png)

![Screenshot 2020-07-14 at 14 50 16](https://user-images.githubusercontent.com/6431515/87427613-5a35a500-c5e1-11ea-853b-fef113def6fe.png)

### Steps to reproduce the behavior 

install alpine linux and run `r2 -d ls`

**Comment by lberrymage** [comment]
I know you haven't said anything about virtualization, but if you're running Alpine from a container or a VM you typically have to allow the guest to use ptrace explicitly.

**Comment by trufae** [comment]
Yes I know. .i'm running alpine natively

**Comment by lberrymage** [comment]
Maybe test this on the stock vanilla and/or LTS kernel since the -virt ones are mainly intended for guests. I wouldn't be surprised if the Alpine Linux kernels, -virt or no, had configs limiting ptrace, considering the distro's orientation on security. The most common problem (and solution) relates to [Yama](https://www.kernel.org/doc/html/v5.4/admin-guide/LSM/Yama.html), but since [it's not enabled in the linux-vert kernel](https://git.alpinelinux.org/aports/tree/main/linux-lts/config-virt.x86_64#n4145) that's a scratch.

I don't know much about userland security, so this could well be a `radare2` thing as opposed to a kernel thing as far as I know.

**Comment by trufae** [comment]
Gdb works perfectly fine. And eperm shouldnt be a reason to let the child continue

**Comment by ret2libc** [comment]
This is not due to something recently introduced. Apparently also 4.0.0 fails to debug on alpine linux.

**Comment by ret2libc** [comment]
In 3.7.0 the debugger could attach to the process, but then everything else was broken... I would say that this has been broken for so long that I doubt we shall fix it in 4.5.0. Maybe next release.

**Comment by trufae** [comment]
i wroet this thing to at least kill the child if the parent can't control it. There are no complains on abusive actions in familiar environments yet. so i guess it can be accepted:

```c
diff --git a/libr/io/p/io_ptrace.c b/libr/io/p/io_ptrace.c
index fcee06151..88d4c021f 100644
--- a/libr/io/p/io_ptrace.c
+++ b/libr/io/p/io_ptrace.c
@@ -181,7 +181,7 @@ static bool __plugin_open(RIO *io, const char *file, bool many) {
 static inline bool is_pid_already_attached(RIO *io, int pid) {
 #if defined(__linux__)
 	siginfo_t sig = { 0 };
-	return r_io_ptrace (io, PTRACE_GETSIGINFO, pid, NULL, &sig) != -1;
+	return r_io_ptrace (io, PTRACE_GETSIGINFO, pid, NULL, (size_t)&sig) != -1;
 #elif defined(__FreeBSD__)
 	struct ptrace_lwpinfo info = { 0 };
 	int len = (int)sizeof (info);
@@ -216,6 +216,7 @@ static RIODesc *__open(RIO *io, const char *file, int rw, int mode) {

 			switch (errno) {
 			case EPERM:
 				ret = pid;
+				kill (pid, 9); // kill the child to avoid undesired behav
iour
 				eprintf ("ptrace_attach: Operation not permitted\n");
 				break;
 			case EINVAL:

```

**Comment by ret2libc** [comment]
Does that kill it also when you are doing `pid://`? We probably don't want to kill existing processes in case of failure.

**Comment by lberrymage** [comment]
So I did a bisect... ironically the offending commit is f6bda32cb91841be902fb25d1ffd96cc598ff3ff: "Fixed ptrace 'Operation not permitted' errors (#15287) ##debug."

**Comment by trufae** [comment]
lel

**Comment by ret2libc** [comment]
> So I did a bisect... ironically the offending commit is [f6bda32](https://github.com/radareorg/radare2/commit/f6bda32cb91841be902fb25d1ffd96cc598ff3ff): "Fixed ptrace 'Operation not permitted' errors (#15287) ##debug."
> 
> Said commit emits the error at least. I frankly don't know if the root problem exists before then.

I already compiled even older version than 4.0.0 and even though the process is attached correctly (so it seems), the debugger doesn't really work. I'm not really sure where the problem is :(

**Comment by XVilka** [comment]
Might be also related (error message looks the same) https://github.com/radareorg/radare2/issues/17417

**Comment by trufae** [comment]
Dupe of https://github.com/radareorg/radare2/issues/17919, closing all the debugger issues to be all in one place

**Comment by dirkbike** [comment]
This issue is different from #17919. The debugger fails on Alpine because there is a typedef in `r_io.h` that defines `r_ptrace_data_t` as an `int` when it should be a `void *`. The parent can control the child process just fine, it's just using bad `ptrace` calls.

**Comment by trufae** [comment]
Yeah thats wrong indeed. Even size_t would make more sense than int. But changing this doesnt fixes the attach for me. Do you have a working fix?

**Comment by dirkbike** [comment]
Changing just that worked for me on Alpine 64-bit running on bare metal. Try making the change to `void *` using a fresh git master and see what kind of errors you get.

**Comment by trufae** [comment]
Can you make a pr with the patch that works for you? I’ll try again today

**Comment by trufae** [comment]
nvm, fixed that in master. its now void* and no warnings are shown during the build.. the thing is.. why i can do `r2 -d r2` but `r2 -d ls` fails? is there any option in the kernel to avoid ptracing binaries outside user home directory? cp /bin/ls $HOME and debugging that same binary from the home works. so i consider the debugger fixed . but im just curious about this behaviour.

thanks!

**Comment by dirkbike** [comment]
Sounds like it might be a path issue. Does it work if you run `r2 -d /bin/ls`?

**Comment by trufae** [comment]
I tried that alread but it was not working either
