### ISSUE TITLE
Remove duplicated implementation of uleb128 in the MACHO parser

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17353]
There was a time in which r2 had 4 different implementations of uleb128, right now there's only 2.

```c
$ git grep ^static | grep leb128
libr/bin/format/mach0/mach0.c:static ut64 read_uleb128(ulebr *r, ut8 *end) {
libr/bin/format/mach0/mach0.c:static st64 read_sleb128(ulebr *r, ut8 *end) {
```

* Time to get rid of it!
* Probably good to add some tests

Related: https://github.com/radareorg/radare2/issues/15479

**Comment by phakeobj** [comment]
The code in mach0 looks very much like the code in dyld which makes it pretty convenient to understand, and this is also right for the leb128 implementation which are a bit different from the variants in libr/util/uleb128.c. most of the differences are minor, like what's returned in the return value of the function and what's returned in the arguments, some sanity checks, but nothing more (if I'm not missing anything).

Now while I can surely refactor the code in mach0 to use the functions in uleb128.c, I wonder if changing it to not match the code in dyld is an expected outcome of this issue. I mean, the other option is to write a wrapper in uleb128.c that will preserve the how-it-looks and how-to-use of the functions in mach0 (that matches dyld) but use the existing functions to actually do the work.

Both options are quite simple to implement, I just wonder if the similarity to the code of dyld is something you guys wish to preserve or not.

**Comment by phakeobj** [comment]
The code in mach0 looks very much like the code in dyld which makes it pretty convenient to understand, and this is also right for the leb128 implementation which are a bit different from the variants in libr/util/uleb128.c. most of the differences are minor, like what's returned in the return value of the function and what's returned in the arguments, some sanity checks, but nothing more (if I'm not missing anything).

Now while I can surely refactor the code in mach0 to use the functions in uleb128.c, I wonder if changing it to not match the code in dyld is an expected outcome of this issue. I mean, the other option is to write a wrapper in uleb128.c that will preserve the how-it-looks and how-to-use of the functions in mach0 (that matches dyld) but use the existing functions to actually do the work.

Both options are quite simple to implement, I just wonder if the similarity to the code of dyld is something you guys wish to preserve or not.
