### ISSUE TITLE
Show section for address in r2

### ISSUE THREAD

**Issue by schrodyn** [radareorg/radare2#17358]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.15.6 amd64
| File format of the file you reverse (mandatory)      | PE, ELF & macho-o.
| Architecture/bits of the file (mandatory)            | x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 24976 @ darwin-x86-64 git.4.4.0-454-gd30ca79e2 commit: d30ca79e2de175226fc76d6bcb38364a9943f027 build: 2020-07-20__15:54:54

Sample file:
[win7notepad.zip](https://github.com/radareorg/radare2/files/4977517/win7notepad.zip)

### Expected behavior
`rabin2` behaves like this:

```
$ rabin2 -S -@ 0x0100c334 c4232ddd4d37b9c0884bd44d8476578c54d7f98d58945728e425736a6a07e102_notepad

nth paddr         size vaddr        vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x0000ac00  0x1000 0x0100c000  0x3000 -rw- .data
```

Using `iS@offset` I expected the same output in r2.

### Actual behavior
```
$ rabin2 -S -@ 0x0100c334 c4232ddd4d37b9c0884bd44d8476578c54d7f98d58945728e425736a6a07e102_notepad

nth paddr         size vaddr        vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x0000ac00  0x1000 0x0100c000  0x3000 -rw- .data

$ r2 c4232ddd4d37b9c0884bd44d8476578c54d7f98d58945728e425736a6a07e102_notepad
 -- Use the 'id' command to see the source line related to the current seek
[0x01003689]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
Warning: aao experimental on 32bit binaries
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x01003689]> iS@0x0100c334
[Sections]

nth paddr          size vaddr         vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000400   0xa800 0x01001000   0xb000 -r-x .text
1   0x0000ac00   0x1000 0x0100c000   0x3000 -rw- .data
2   0x0000bc00  0x1f200 0x0100f000  0x20000 -r-- .rsrc
3   0x0002ae00   0x1000 0x0102f000   0x1000 -r-- .reloc


[0x01003689]>
```

r2 doesn't show me the section which the address resides. Was expecting the same output as given by rabin2. Ideally I was hoping to use the JSON format `iSj@0x0100c334`.

### Steps to reproduce the behavior 
- git clone radare2 master.
- compile.
- Repeat steps documented above.

**Comment by ret2libc** [comment]
```
[0x00000000]> iS?
| iS [entropy,sha1]  Sections (choose which hash algorithm to use)
| iS.                Current section
```

`iS` just list all the sections in the binary.
What you probably want is `iS.` (or in your case `iS.@0x0100c334`).

I'm closing this issue, but if you feel like your problem is not actually solved, feel free to re-open it. Thanks!
