### ISSUE TITLE
newshell: # comment wrongly parsed

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#17351]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Irrelevant
| File format of the file you reverse (mandatory)      | Irrelevant
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 27772 @ linux-x86-64 git.4.4.0-472-gaaa51ec0e commit: aaa51ec0ee12f9188e71800dd3c4dbd537076d2e build: 2020-07-24__10:14:53

### Expected behavior
```

```
Nothing should be printed, because `#!....` should be treated as a comment if not used as a command.

### Actual behavior
```
!ciao
```

### Steps to reproduce the behavior 
```
$ radare2 -e cfg.newshell=true -
> ?e #!ciao
```

**Comment by trufae** [comment]
Start by adding the following test. this issue is specific to newshell:

```
$ r2 -
[0x00000000]> ?e #!ciao

[0x00000000]> e cfg.newshell =1
[0x00000000]> ?e #!ciao
!ciao
[0x00000000]>
```

**Comment by ret2libc** [comment]
Yes, this is what I said. Maybe I did not make it clear in the description, but the title starts with `newshell`. It's indeed a newshell specific bug. I'm going to fix it ASAP and add tests.
