### ISSUE TITLE
[x86_64][ELF] Segmentation fault opening binary.

### ISSUE THREAD

**Issue by SjRNMzU** [radareorg/radare2#17379]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF 
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0-git 24750 @ linux-x86-64 git.4.4.0-247-ga934a3923
commit: a934a39236b3604e0e6ecebbee2b3b4d9c16bf06 build: 2020-06-09__09:28:44

### Expected behavior

`$ radare2 libpcl_segmentation.so.1.10.1` opens the file in radare2 and displays the r2 shell to the user.

### Actual behavior

```
$ radare2 libpcl_segmentation.so.1.10.1
r_uleb128: undefined behaviour in 70 shift on ut32
r_uleb128: undefined behaviour in 70 shift on ut32
r_uleb128: undefined behaviour in 77 shift on ut32
r_uleb128: undefined behaviour in 84 shift on ut32
r_uleb128: undefined behaviour in 91 shift on ut32
r_uleb128: undefined behaviour in 70 shift on ut32
r_uleb128: undefined behaviour in 70 shift on ut32
r_uleb128: undefined behaviour in 77 shift on ut32
r_uleb128: undefined behaviour in 70 shift on ut32
Segmentation fault (core dumped)
```

### Steps to reproduce the behavior 
- Open the file. 
- I cannot drag and drop to github so the file is hosted temporarily [here](https://ufile.io/0xhfd2en). (Please download it and re-upload it before the link expires)

**Comment by ret2libc** [comment]
Interesing... ASAN does not catch anything, but a regular build segfaults.

**Comment by SjRNMzU** [comment]
[Here](http://178.62.54.169:8081/7XDwj/libBlocksRuntime.so.0.0.0) is another file which causes r2 to crash on opening. This may be a separate issue but I can't be bothered to create a new ticket.

**Comment by SjRNMzU** [comment]
[Here](http://178.62.54.169:8081/7Ru67/libpcl_segmentation.so.1.10.1) is the original file uploaded using a more long-term host.

**Comment by ret2libc** [comment]
> [Here](http://178.62.54.169:8081/7XDwj/libBlocksRuntime.so.0.0.0) is another file which causes r2 to crash on opening. This may be a separate issue but I can't be bothered to create a new ticket.

It doesn't crash for me with this one.

**Comment by ret2libc** [comment]
@SjRNMzU please see https://github.com/radareorg/radare2/pull/17387 . As I am not able to test your second binary, check if the PR fixes that as well for you.

**Comment by SjRNMzU** [comment]
I can confirm the patch fixes this issue. Both binaries do not crash using the latest master.

```
r2 ./libpcl-segmentation1.10/usr/lib/x86_64-linux-gnu/libpcl_segmentation.so.1.10.1
WARNING: parse_line_header: assertion 'hdr && bf && buf' failed (line 545)
[0x0062dcf0]>
```

Thanks!
