### ISSUE TITLE
Collect all ARM64 security features under one RAnalOpFamily 

### ISSUE THREAD

**Issue by phakeobj** [radareorg/radare2#17378]
In addition to #17371, I wanted to add BTI to ##anal as well, but there's no RAnalOpFamily that fits it. I think it's time to create a new RAnalOpFamily for all ARM64 security features (PAC, MTE, and BTI).

I suggest 

- `R_ANAL_OP_FAMILY_SECURITY` 
- `r_anal_op_family_to_string(R_ANAL_OP_FAMILY_SECURITY)` = `"sec"`

Thoughts?

**Comment by XVilka** [comment]
ARM is only one of the supported architectures, calling it PAC is a bit too specific. We might do something like `R_ANAL_OP_FAMILY_SECURITY` that is generic enough for any architecture that has something designed specifically for that.

**Comment by phakeobj** [comment]
Yeah that’s just a copy-paste accident. The suggestion should have been SECURITY, that’s why str was suggested to be “sec”.

**Comment by phakeobj** [comment]
woops, that's a typo. was supposed to be `R_ANAL_OP_FAMILY_SECURITY`. I'll edit it.
