### ISSUE TITLE
Signature matching take so much memory that triggers oom killer

### ISSUE THREAD

**Issue by himekifee** [radareorg/radare2#17418]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch/x86/64 bits
| File format of the file you reverse (mandatory)      | PE(dll)
| Architecture/bits of the file (mandatory)            | x86/64 bits
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0 0 @ linux-x86-64 git.4.4.0 commit: unknown build: 2020-05-08__21:16:55

### Expected behavior
Not causing oom killer, finish matching

### Actual behavior
oom killer triggered

### Steps to reproduce the behavior 
[binary.tar.gz](https://github.com/radareorg/radare2/files/5042626/binary.tar.gz)
- r2 synaWudfBioUsb.dll
- aaa
- zo updated.sdb
- z/

**Comment by swoops** [comment]
I can reproduce this. To reproduce it faster disable the bytes search (`e zign.bytes = false`). I will look into it further.

**Comment by himekifee** [comment]
I think it's still leaking on your branch but with a lower rate.

**Comment by swoops** [comment]
I suspect you are right. I plan on refactoring that code soon. I should be able to significantly speed up signature matching. So I don't want to invest too much time tracking down leaks in code that I might be replacing anyways.
