### ISSUE TITLE
ARMv8 build failure

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17438]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu aarch64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | ARMv8
| r2 -v full output, **not truncated** (mandatory)     |  https://github.com/radareorg/radare2/commit/18c052c2665d05aa222def67e83afa1fc0d99ec9

See full log at https://travis-ci.com/github/radareorg/radare2/jobs/370233921
```
+./configure --prefix=/home/travis/build/radareorg/radare2/install
cp: './plugins.cfg' and 'plugins.cfg' are the same file
+make -s -j2
ar: creating libr_z.a
ar: creating libr_zip.a
ar: creating librz.a
In file included from /home/travis/build/radareorg/radare2/libr/include/r_list.h:6:0,
                 from /home/travis/build/radareorg/radare2/libr/include/r_util/r_graph.h:4,
                 from /home/travis/build/radareorg/radare2/libr/include/r_cons.h:10,
                 from /home/travis/build/radareorg/radare2/libr/include/r_diff.h:6,
                 from /home/travis/build/radareorg/radare2/libr/include/r_util.h:7,
                 from ../../shlr/spp/spp.h:81,
                 from ../../shlr/spp/spp.c:3:
/home/travis/build/radareorg/radare2/libr/../shlr/sdb/src/sdb.h:19:10: fatal error: sdb_version.h: No such file or directory
 #include "sdb_version.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [../../shlr/spp/spp.o] Error 1
make[1]: *** [spp_config] Error 2
make[1]: *** Waiting for unfinished jobs....
ar: creating libsdb.a
make: *** [all] Error 2
+exit 1
```

**Comment by trufae** [comment]
i dont think this is related to arm at all. it seems a problem with 2d160f250918609fa8f399a33f003cedaa85d888

**Comment by trufae** [comment]
i have native ubuntu on arm64, so i'll try

**Comment by XVilka** [comment]
Works now.
