### ISSUE TITLE
Finish r_time APIs

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/radare2#17444]
Follow-up for #17276, about `r_sys_now()` and `r_sys_now_mono()`:

* [x] Make a pr moving the API into `r_time.h`
* [ ] Make another pr splitting `r_sys_now(_mono)?` into `r_sys_now(_mono)?_ms` and `r_sys_now(_mono)?` where the latter will give you a full timespec-like struct.

**Comment by XVilka** [comment]
See also:
![image](https://user-images.githubusercontent.com/203261/90094346-42784a80-dd60-11ea-8be5-2334c2703210.png)

**Comment by thestr4ng3r** [comment]
That's not new, but yes `strftime()` should be used instead

**Comment by trufae** [comment]
i tried to read the `r_time` and `r_print_time` apis 2 days ago and had to run out to the toilet. All of them need to be rewritten and fixed. Assigned to me and will do for 5.8
