### ISSUE TITLE
Rename asm.filter to asm.sub and asm.sub.* to sub.* like it's done in asm.emu/emu.*

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#17455]
This is not really an issue but a proposal to change this for consistency, because asm.filter is related to asm.sub, so it makes sense to use similar names.

```
[0x100001060]> e??~asm.sub
         asm.sub.jmp: Always substitute jump, call and branch targets in disassembly
         asm.sub.reg: Substitute register names with their associated role name (drp~=)
         asm.sub.rel: Substitute pc relative expressions in disasm
     asm.sub.section: Show offsets in disasm prefixed with section/map name
        asm.sub.tail: Replace addresses with prefix .. syntax
      asm.sub.varmin: Minimum value to substitute in instructions (asm.var.sub)
     asm.sub.varonly: Substitute the entire variable expression with the local variable name (e.g. [local10h] instead of [ebp+local10h])
[0x100001060]> e??~asm.filter
          asm.filter: Replace numeric values by flags (e.g. 0x4003e0 -> sym.imp.printf)
[0x100001060]>
```

**Comment by ret2libc** [comment]
I do not think it makes sense to have `sub.` at the top level but `asm.sub` under `asm.` which enables/disables `sub.*` vars. If we want to extract `asm.sub.*` into `sub.*` then `asm.filter` should be `sub.something` otherwise you have some config vars at the top level and the "trigger" somewhere else. If, instead, you think the `sub.*` variables are only related to `asm`, then all the `asm.sub.*` vars should remain where they are imo.

**Comment by trufae** [comment]
we have asm.sub already, but we also have asm.emu and emu., im trying to find a consistent solution

**Comment by ret2libc** [comment]
Actually, now that i look again at this, I don't see why `asm.filter` should be considered special. I think it should just go under `asm.sub.filter`.

![image](https://user-images.githubusercontent.com/562321/92497545-c4418380-f1f9-11ea-9f4b-778df3a96f49.png)

As it can be seen in the image, you can have `asm.sub.rel` work even with `asm.filter=false`.

**Comment by trufae** [comment]
the thing is that filter is a different word as sub, so its confusing, and it ends up doing the same. maybe asm.filter should be better renamed to asm.sub.names

**Comment by ret2libc** [comment]
> the thing is that filter is a different word as sub, so its confusing, and it ends up doing the same. maybe asm.filter should be better renamed to asm.sub.names

On this, I agree. `asm.sub.names` looks good to me! :+1: 

@XVilka @thestr4ng3r @kazarmy @wargio WDYT?

**Comment by wargio** [comment]
agree

**Comment by officialcjunior** [comment]
So, rename `asm.filter` to  `asm.sub.names` and `asm.sub*` to  `sub.*` ?

**Comment by trufae** [comment]
Only asm.filter to asm.sub.names, there's no such asm.sub*

**Comment by ret2libc** [comment]
@trufae @officialcjunior since you rename stuff, we should probably rename `asm.var.sub` as `asm.sub.var`. What do you think? We have a `asm.sub` section, so I would expect to find all the "substitute" related stuff under that.

**Comment by officialcjunior** [comment]
I think that makes sense.
I agree.

**Comment by officialcjunior** [comment]
So:
`asm.var.sub` to `asm.sub.var` and `asm.filter` to `asm.sub.names`
Has everyone agreed to this? Can I do this over the weekend?

**Comment by trufae** [comment]
Agree from me

**Comment by ret2libc** [comment]
Yep, ok for me as well! Go ahead, thanks :)

**Comment by wargio** [comment]
Yes go!
