### ISSUE TITLE
`/a` command doesn't take `asm.arch` and `asm.bits` from the binary file

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17458]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu PPC
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | PPC
| r2 -v full output, **not truncated** (mandatory)     | https://github.com/radareorg/radare2/commit/bb3e80c040dfb6b1a4729f3b7b409b235e490b08

### Expected behavior

`/a xor al, 0x80` should work on non-x86 architectures if the ELF or PE binary is opened where architecture is set to 'x86'

### Actual behavior

```
[XX] db/cmd/cmd_search /a search from/to (seek 0)
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -n -Qc 'e io.va = false
s 0
e search.from = 0
e search.to = 0x50
/a xor al, 0x80
' bins/elf/ioli/crackme0x00
-- stdout
@@ -1,2 +0,0 @@
-0x0000003c hit0_0 3480
-0x00000040 hit0_1 3480
-- stderr
Cannot assemble 'xor al, 0x80' at line 3
```

See full log here: https://travis-ci.com/github/radareorg/radare2/jobs/371485918#L10287

**Comment by trufae** [comment]
The test is wrong. this file is loaded with -n which ignores the arch, and xor al, 0x80 is not a valid powerpc instruction. so its not a bug in /a
