### ISSUE TITLE
Clarify the interface module inside r2

### ISSUE THREAD

**Issue by 08A** [radareorg/radare2#17450]
**Is your feature request related to a problem? Please describe.**
The interface is a mess right now.
Just open a random file and try to understand what the heck is going on.

**Describe the solution you'd like**
Create a ref of what is implemented, what need to be simplify, rework, write.

**Describe alternatives you've considered**
Search for alternative rendering lib and implement the basics.

**Additional context**
Right now there some bug that can't be solved right now (to much time consuming)  #16963

**Comment by karliss** [comment]
By interface do you mean the text user interface? Not r2 API in general or r2 module for analyzing interfaces in executables.

**Comment by 08A** [comment]
> By interface do you mean the text user interface? Not r2 API in general or r2 module for analyzing interfaces in executables.

I talk about TUI

**Comment by ret2libc** [comment]
Could you explain a bit more what you mean? If you are talking about UI, also some screenshots would help and try to describe exactly the problem instead of "it is a mess".

**Comment by 08A** [comment]
The libr/cons/* file are not documented (for example r_line_readline_cb).

You can't add things without breaking some stuff.
It is really complicated to contribute to this part of the project.

**Comment by 08A** [comment]
libr/cons/dietline.c line 49: static void backward_kill_word(void)
libr/cons/dietline.c line 77 static void backward_kill_Word(void)

The difference between those 2 functions?

**Comment by XVilka** [comment]
https://book.rada.re/basic_commands/dietline.html

**Comment by 08A** [comment]
From what i understand it is user documentation. What i want is dev documentation (I know self-documented).
But if we don't have any documentation for the dev, we need a cleaner implementation.

**Comment by trufae** [comment]
kill_Word, in uppercase makes me think that stops the microsoft Word process, but it's probably going to be a mistake

**Comment by ret2libc** [comment]
@08A I see :( unfortunately, we don't have anything for it and I do agree it is very hard to touch some parts of the code without breaking stuff. At the same time, it is also hard to test this kind of things. And the same applies for all the Visual things as well. We don't have any test for anything that requires user interaction :( and we don't have code documentation... The code documentation can come only from someone who understands that part of the code well, but maybe we can improve the testing part?
