### ISSUE TITLE
Exclude shlr dir from lgtm analysis

### ISSUE THREAD

**Issue by 08A** [radareorg/radare2#17464]
**Is your feature request related to a problem? Please describe.**
There is a lot of lgtm issue not related to the r2 codebase (shlr/*)

**Describe the solution you'd like**
Modification of the .lgtm.yml

**Describe alternatives you've considered**
...

**Additional context**
#16493

**Comment by trufae** [comment]
sgtm

**Comment by 08A** [comment]
> sgtm

?

**Comment by trufae** [comment]
sounds-good-to-me to disable the looks-good-to-me in shlr

**Comment by trufae** [comment]
But there's some stuff in shlr/ that its not from 3rd party projects (like the gdb code)

**Comment by 08A** [comment]
> sounds-good-to-me to disable the looks-good-to-me in shlr

Okay ty

**Comment by XVilka** [comment]
In fact not all of `shlr/` should be excluded.
For example, these are either presented only in radare2 or an independent fork:
- `shlr/windbg`
- `shlr/gdb`
- `shlr/tcc`
- `shlr/qnx`
- `shlr/java`
- `shlr/heap`
- `shlr/ar`
- `shlr/bochs`

**Comment by 08A** [comment]
@XVilka Could you explain which subdir in shlr should be discard?

**Comment by ret2libc** [comment]
I can tell some directories that *should be monitored* by LGTM:
* radare2-shell-parser

And some that *should NOT be monitored*, as they are separate projects:
* capstone
* sdb
* spp
* tree-sitter

Maybe someone else can integrate/correct these.

**Comment by trufae** [comment]
Lgtm no longer exists
