### ISSUE TITLE
bins/fuzzed/r2-SEGV-186-34e-f41 fail

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17478]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | -
| r2 -v full output, **not truncated** (mandatory)     | https://github.com/radareorg/radare2/commit/e3504eb0d92d9ff6dd4cdb9f9edd95eb4e7bc050 

```
[XX] /home/runner/work/radare2/radare2/test/bins/fuzzed <fuzz> /home/runner/work/radare2/radare2/test/bins/fuzzed/r2-SEGV-186-34e-f41
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc aaa /home/runner/work/radare2/radare2/test/bins/fuzzed/r2-SEGV-186-34e-f41
-- stdout

-- stderr

-- exit status: -1


[XX] /home/runner/work/radare2/radare2/test/bins/fuzzed <fuzz> /home/runner/work/radare2/radare2/test/bins/fuzzed/SEGV-341-892-d00
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc aaa /home/runner/work/radare2/radare2/test/bins/fuzzed/SEGV-341-892-d00
-- stdout

-- stderr

-- exit status: -1
[**] /home/runner/work/radare2/radare2/test/bins/fuzzed      503 OK         0 BR        2 XX        0 FX
```

**Comment by XVilka** [comment]
We don't run fuzzed tests on PR while do for master - this is why PRs were green while master is read.

**Comment by trufae** [comment]
Shouldnt this be the other way around?

**Comment by XVilka** [comment]
Probably, but then the complaints about PR check speed would be way bigger.

**Comment by XVilka** [comment]
Fixed in https://github.com/radareorg/radare2/commit/4bc96b847aed10d3c04eea62bad5d7bc0ba3c228
