### ISSUE TITLE
Alt+key triggers quit

### ISSUE THREAD

**Issue by zsugabubus** [radareorg/radare2#17492]
Pressing any <kbd>Alt+key</kbd> makes r2 quit, except the ones that needed for line editing (like <kbd>Alt+f/b</kbd>; maybe these are the only two exceptions). Issue _does not_ seem to be terminal dependent.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0 0 @ linux-x86-64 git.4.4.0 commit: unknown build: 2020-05-08__21:16:55
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.0 24955 @ linux-x86-64 git.4.4.0-426-g9d7eda5ec  commit: 9d7eda5ec7367d1682e489e92d1be8e37e459296 build: 2020-07-17__11:05:37 (also tried with r2 from the prebuilt deb package)
| Terminal Emulators | Alacritty, Kitty, rxvt-unicode, Termite, Linux console
| Config | None

**Comment by karliss** [comment]
<kbd>Alt+f</kbd> and <kbd>Alt+b</kbd> Seems to work for me, please fill out the information requested in issue template and describe your environment in more details.

**Comment by trufae** [comment]
Cant repro. Please specify version of r2, os, arch and terminal you are using

**Comment by zsugabubus** [comment]
Updated the issue report.

> Alt+f and Alt+b Seems to work for me

Sorry for my English. I wanted to say that the issue occurs with most keys **except** the ones that needed for line editing, like <kbd>Alt+f/b</kbd>. They are working fine for me too. The issue is with key presses like <kbd>Alt+v/h/j/k/l</kbd>.
