### ISSUE TITLE
Can not open file via http

### ISSUE THREAD

**Issue by alex-bender** [radareorg/radare2#17506]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25587 @ linux-x86-64 git.4.4.0-574-g3c8890013 commit: 3c889001347fb764db98594b97e65b4e22cf9600 build: 2020-08-21__14:19:08

### Expected behavior
r2 opens file via http

### Steps to reproduce the behavior 
```
r2 http://host/path
[r] Cannot open '...
```

**Comment by trufae** [comment]
as a workaround you can set R2_CURL=1 env var
