### ISSUE TITLE
Debugger broken on BSD again

### ISSUE THREAD

**Issue by crv-intel** [radareorg/radare2#17500]
Using radare2 4.5.0 on FreeBSD 12.1

[~]$ r2 -d /bin/ls
Process with PID 17121 started...
= attach 17121 17121
bin.baddr 0x00400000
Using 0x400000
asm.bits 32
 -- Wait a minute! I found a bug, self-fixing ... OK
[0x2040c000]> ds
Stepping failed!
Step failed

**Comment by XVilka** [comment]
Could you please retry with the version from git?
