### ISSUE TITLE
r_reg_get_name_idx doesn't check string length

### ISSUE THREAD

**Issue by FXTi** [radareorg/radare2#17518]
Problem:
When my `get_reg_profile` is called:
> Ignoring duplicated register definition 'PCR'

Here's functions result:
```
=PC	PC
=SP	SP
=R0	D0
...
gpr	PC	.32	72	0
...
gpr	PCR	.32	176	0
...
```

`PC` and `PCR` register should not collide. 
According to my understanding, the issue is that: In `parse_def(RReg *reg, char **tok, const int n)`, it calls `r_reg_get` to verify if given register is already exists. 
And when `PCR` is passed to `r_reg_get`, `=PC	PC` is processed.
So `r_reg_get(..., PCR, -1)` -> `r_reg_get_name_idx(PCR)`, and return `R_REG_NAME_PC` since it doesn't check string length.
In the end, `r_reg_get` find `PC` and `parse_def` think `PCR` is already exists.

---

Also, I will use `r_reg_get` in my code, consider this:

```
=PC RIP
=SP RSP
gpr RSP .64 32  0
gpr ESP .32 32  0
gpr SP  .16 32  0
```

When I try to get `SP`, if I call `r_reg_get(..., SP, -1)`, I will get `RSP`. So I will specify third argument of `r_reg_get` to avoid alias lookup process. Then the only thing need to change is make `r_reg_get_name_idx` check string length == 2.

**Comment by trufae** [comment]
As discussed in Telegram:

* Registers must be lowercase
* Reg aliases must be 2 char in length and uppercase

So, using uppercase registers will work for X86, but not for ARM for example, so my suggestion here is:

* Make all the registers lowercase in your side
* Add the if (!name[0] || !name[1] || name[2]) check in this function to ensure length = 2
