### ISSUE TITLE
`zo` does not seem to load my handcrafted SDB file

### ISSUE THREAD

**Issue by Artoria2e5** [radareorg/radare2#17510]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS amd64
| File format of the file you reverse (mandatory)      | Mach-O
| Architecture/bits of the file (mandatory)            | amd64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 1 @ darwin-x86-64 git.4.6.0-git; commit: b67d1bf7c22be6e5e31a9fa37347bab10fe00f28 build: 2020-08-24__17:17:32

### Expected behavior

radare2 should tell me what is wrong with my SDB file, if any

### Actual behavior

`zo objc.sdb.txt` completes without a message, but `z` gives no output, suggesting a failed load

### Steps to reproduce the behavior 

Test file (not really relevant): 
[StandardAdditions_uu.zip](https://github.com/radareorg/radare2/files/5116947/StandardAdditions_uu.zip)

SDB file in question: [objc.sdb.txt](https://github.com/radareorg/radare2/files/5116950/objc.sdb.txt)

1. Run `r2`
2. `zo objc.sdb.txt; z`
3. `o StandardAdditions_uu; aaaa` if you want to (not relevant)

P.S. someone should probably add more objc runtime functions to the built-in prototypes. someday.

**Comment by trufae** [comment]
txt != sdb

**Comment by ret2libc** [comment]
As @trufae said, you should use a `sdb` file, not a txt file. To get a sdb file from txt, you can use something like `sdb output.sdb = < input.sdb.txt` (you have to compile and/or install sdb). However, even by doing so I do not think your file would work.

I believe `zo` expects to find a sdb file as saved by `zos`, which is different from the format used by your example SDB file.

Does that help you?

**Comment by Artoria2e5** [comment]
I get it now. But since zos is a different format, do we have a command that reads the same format as given in the many sdb.txt files in this repo?

**Comment by XVilka** [comment]
The format is different, yes. Closing the issue then.
