### ISSUE TITLE
Travis project failures for ARM, PPC, ASAN builds: WARNING: r_file_abspath: assertion 'file' failed (line 237)

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17556]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64, Ubuntu ARM64, Ubuntu PPC
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | PPC, x86/64, ARMv8
| r2 -v full output, **not truncated** (mandatory)     |  https://github.com/radareorg/radare2/commit/55c56206d0de03b51c5b6da72d6d49080261fef2
### Actual behavior

```
[XX] db/cmd/cmd_project Save project for a file with asm.bits=32 and check the value after loading again
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e dir.projects = .tmp/
e asm.bits=16
Ps sun > /dev/null
Po sun > /dev/null
e asm.bits
' bins/src/hello.c
-- stdout
@@ -1 +1 @@
-16
+64

[XX] db/cmd/cmd_project Delete a saved project and used directory (with Pd)
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -n -Qc 'e dir.projects = .tmp/
Ps anesthetize > /dev/null
Pd anesthetize > /dev/null
Pl~blah
ls -l `e dir.projects`~anesthetize
' bins/elf/analysis/main
-- stdout
@@ -0,0 +1 @@
+WARNING: r_file_abspath: assertion 'file' failed (line 237)
-- stderr
rm /home/travis/build/radareorg/radare2/test/.tmp/anesthetize/rc

[XX] db/cmd/cmd_project Delete a saved project (with P-)
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -n -Qc 'e dir.projects = .tmp/
Ps erase > /dev/null
P- erase > /dev/null
Pl~erase
' bins/elf/analysis/main
-- stdout
@@ -0,0 +1 @@
+WARNING: r_file_abspath: assertion 'file' failed (line 237)
```

See:
- https://travis-ci.com/github/radareorg/radare2/jobs/379333410#L3374
- https://travis-ci.com/github/radareorg/radare2/jobs/379333412#L1551

**Comment by ret2libc** [comment]
I think there is no need for these kind of issues... If one wants to fix them there are already relevant (and always updated) travis logs to look at and these issues do not provide additional values. For me it is ok to close this issue.

**Comment by XVilka** [comment]
It was fixed. Only another issue remained:
```
[XX] db/cmd/cmd_project Save project for a file with asm.bits=32 and check the value after loading again
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e dir.projects = .tmp/
e asm.bits=16
Ps sun > /dev/null
Po sun > /dev/null
e asm.bits
' bins/src/hello.c
-- stdout
@@ -1 +1 @@
-16
+32
```
But I am closing this issue anyway.
