### ISSUE TITLE
New 'continuous' CI release breaks version/release tracking

### ISSUE THREAD

**Issue by Nicceboy** [radareorg/radare2#17598]
**Is your feature request related to a problem? Please describe.**

New "continuous" CI release breaks release and version tracking through GitHub API. Release and version tracking is useful when automating tool packaging for third-party providers and keeping it up-to-date with official releases instead of master branch.
Example:
```
curl https://api.github.com/repos/radareorg/radare2/releases/latest
```
Returns release with tag 'continuous', which is not useful and will be always the same. Instead, it would be useful to see the latest real release, in this case the one with tag 4.5.1.

**Describe the solution you'd like**

Continuous release could be marked as 'pre-release`. Then it is not included, when making the request to see the latest actual release.

**Comment by karliss** [comment]
It was discussed a few times that current approach isn't great. A better solution might be running those builds as github actions and uploading results as artifacts without polluting release list and notifications, but someone needs to do it. So far no one has been sufficiently annoyed to do the required work and make a PR.

Marking as pre-release sounds like reasonable and simple improvement until a better solution is done.

**Comment by ret2libc** [comment]
What I also wonder is whether those .Deb continuous files are really used/downloaded by anyone. Unfortunately I don't think there is a clear way to know...

**Comment by karliss** [comment]
Github release counts are tracked. Not sure where it's displayed in UI but It is available using API. An easy way of viewing it is with this website https://somsubhra.com/github-release-stats/?username=radareorg&repository=radare2 .  One problem is that each time new continuous release is uploaded numbers are reset.

**Comment by ret2libc** [comment]
Ok, I'm assigning this to me. The task would be to create a Github workflow that will create artifacts on each commit to master, as @karliss suggested. So we can disable the push from the travis job. @trufae ok with this? Asking because the script is uploading those artifacts with your account.

**Comment by ret2libc** [comment]
Unfortunately there is this "small" problem with GitHub artifacts https://github.com/actions/upload-artifact/issues/51 :( This makes them quite useless imo. If we want to keep support continuous build (which I still question...) we may have to do a pre-release.

**Comment by ret2libc** [comment]
Ok, PR merged. Let's see how it goes. Now they should be marked as pre-releases. (I'd still be very happy to just remove those "continuous build" pre-releases :D)

**Comment by Nicceboy** [comment]
Thank you. Seems to be working well!
