### ISSUE TITLE
Dead link on the documentation

### ISSUE THREAD

**Issue by SakiiR** [radareorg/radare2#17616]
The second link of the page [https://radare.gitbooks.io/radare2book/content/crackmes/ioli/intro.html](https://radare.gitbooks.io/radare2book/content/crackmes/ioli/intro.html) is dead (https://github.com/radareorg/radare2book/tree/master/crackmes/ioli/IOLI-crackme.tar.gz).

Just a brief report .

**Comment by xp073** [comment]
This is not the right repository to open an issue. Here's the right one -> https://github.com/radareorg/radare2book

**Comment by SakiiR** [comment]
whoops, sorry

**Comment by XVilka** [comment]
It's now here: https://github.com/radareorg/radare2book/issues/276
