### ISSUE TITLE
HTTP server: "Cannot listen on http.port"

### ISSUE THREAD

**Issue by meme** [radareorg/radare2#17638]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux amd64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25337 @ linux-x86-64 git.4.4.0-678-g5ccf9fd48 commit: 5ccf9fd4824ee54e999e92993442ba200c65ab80 build: 2020-09-12__21:41:00

### Expected behavior

When running: `r2 -q -e http.port=0 -e http.sandbox=false -e http.homeroot=dev -e http.ui=m -c=H /bin/ls`, a random port is selected and the server begins listening.

### Actual behavior

Outputs: "Cannot listen on http.port" and exits

### Additional Logs, screenshots, source-code,  configuration dump, ...

Explicitly setting the protocol before listening fixes the issue, I do not know if this is the correct way to do it or if there is a specific socket creation function.

```diff
diff --git a/libr/core/rtr_http.c b/libr/core/rtr_http.c
index 02c0067a2..1746438a6 100644
--- a/libr/core/rtr_http.c
+++ b/libr/core/rtr_http.c
@@ -81,6 +81,7 @@ static int r_core_rtr_http_run(RCore *core, int launch, int browse, const char *
                }
                memset (&so, 0, sizeof (so));
        }
+       s->proto = R_SOCKET_PROTO_TCP;
        if (!r_socket_listen (s, port, NULL)) {
                r_socket_free (s);
                eprintf ("Cannot listen on http.port\n");
```

An error should also be printed here: https://github.com/radareorg/radare2/blob/master/libr/socket/socket.c#L509-L510

**Comment by trufae** [comment]
Please send a PR. Its easier than filling the issue template
