### ISSUE TITLE
The help for /ai and /aI are inverted

### ISSUE THREAD

**Issue by m2jean** [radareorg/radare2#17719]
`/ai` should be asm search while `/aI` should be infinite loop search

https://github.com/radareorg/radare2/blob/ae0b5e503fd391be4d99b428dd4918094edc5fb9/libr/core/cmd_search.c#L96-L97

https://github.com/radareorg/radare2/blob/ae0b5e503fd391be4d99b428dd4918094edc5fb9/libr/core/cmd_search.c#L3239-L3244

**Comment by ret2libc** [comment]
@m2jean thanks for the report! Would you be willing to fix the help with a PR? Since you have already found the interesting pieces it should be quick :) Thanks again
