### ISSUE TITLE
Integrate V35 ARM64 disassembler ##disasm

### ISSUE THREAD

**Issue by meme** [radareorg/radare2#17759]
**Is your feature request related to a problem? Please describe.**
Integrate Vector35's ARM64 disassembler in radare2. The source is now available here: https://github.com/Vector35/arch-arm64

**Describe the solution you'd like**
Much like the other supported disassembler backends in rasm2, this disassembler should be supported as well.

**Additional context**
It is licensed under Apache 2.0 and can be moved in-tree.

**Comment by trufae** [comment]
This disassembler is written in C++ and it's maintained in a separate repository. i wouldnt consider having it inside r2. But fits perfectly in radare2-extras as an optional disassembler plugin. Can you open the issue there?, anyway, writing such plugin shouldnt be hard, its just taking the skeleton asm plugin and replacing the call to use that lib instead. Would you like to try to do that? it shouldnt take more than 10 minutes of coding.

**Comment by trufae** [comment]
Oh wait, it's just C and a single file. that works best for r2core instead of r2extras

**Comment by trufae** [comment]
ill submit the pr now. seems interesting to have it for embeddeds, and its the only way to get modern arm disassembler in (8KLOC), i dont expect capstone to release v5 which have the PAC isntructions and such in less than 5 years. so i'm happy to have this in core.

**Comment by trufae** [comment]
if you want commit access to my branch to add the ESIL, ANAL and other stuff it needs to be a first class citizen?

**Comment by meme** [comment]
Sure, sounds good.

**Comment by meme** [comment]
Done: https://github.com/radareorg/radare2-extras/pull/269. Thanks
