### ISSUE TITLE
Getting 32bit binary verbose function listings in Radare on Windows causes crash

### ISSUE THREAD

**Issue by bocajspear1** [radareorg/radare2#17791]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 1909
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | 32-bit (`C:\Windows\system32\notepad.exe`, since radare is built 32bit for Windows, this will be a 32bit version)
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.1 1 @ windows-x86-32 git.4.5.1, commit: 293cf5ae65ba4e28828095dcae212955593ba255 build: Thu 09/03/2020__ 6:26:33.97 |

### Expected behavior

Running `afll` with a 32bit binary will list functions and not crash.

### Actual behavior

Running `afll` with a 32bit binary causes radare2 to crash. 

### Steps to reproduce the behavior 

Unzipped the Radare static binaries to `C:\radare2` and added `C:\radare2\bin` to path.

In a `cmd.exe`:
```
radare2.exe C:\Windows\system32\notepad.exe
```
Then in radare:
```
aaa
afll
```
After a few momments, Radare will exit. Viewing the event log indicates it has crashed.

### Additional Logs, screenshots, source-code,  configuration dump, ...

Using x64dbg to get a little more info, saw this in logs:
![image](https://user-images.githubusercontent.com/1709228/96153744-071f0700-0edc-11eb-968c-82db9a1b32a8.png)

**Comment by radare** [comment]
Cant reproduce, at least on master, Can you try again with latest code in git?

**Comment by trufae** [comment]
i will also suggest you to submit a PR with the tests that crash on your system, so the CI can test them on all the platforms, but aaa+afll is pretty basic and i think its already covered

**Comment by bocajspear1** [comment]
radare2 4.6.0-git 25146 appears to work (build retrieved from appveyor)
