### ISSUE TITLE
Analyzing 64bit binary on Windows causes crash

### ISSUE THREAD

**Issue by bocajspear1** [radareorg/radare2#17790]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 1909
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | 64-bit (`C:\Windows\notepad.exe`)
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.1 1 @ windows-x86-32 git.4.5.1, commit: 293cf5ae65ba4e28828095dcae212955593ba255 build: Thu 09/03/2020__ 6:26:33.97 |

### Expected behavior

Running `aaa` with a 64bit binary will analyze the binary and not crash.

### Actual behavior

Running `aaa` with a 64bit binary causes radare2 to crash.  32bit binaries appear to not cause the crash.

### Steps to reproduce the behavior 

Unzipped the static binaries to `C:\radare2` and added `C:\radare2\bin` to path.

In a `cmd.exe`:
```
radare2.exe C:\Windows\notepad.exe
```
Then in radare:
```
aaa
```

At `[ ] Check for vtables`, radare will exit. Viewing the event log indicates it has crashed.

### Additional Logs, screenshots, source-code,  configuration dump, ...

Using x64dbg to get a little more info, saw this in logs:
![radare-bug-1](https://user-images.githubusercontent.com/1709228/96151095-0b95f080-0ed9-11eb-86bb-457dc0c94321.png)
c0000374 is STATUS_HEAP_CORRUPTION

**Comment by trufae** [comment]
Cant reproduce either. please use r2 from git

**Comment by bocajspear1** [comment]
radare2 4.6.0-git 25146 appears to work. Seeing how much of a breakage this is, maybe the Windows binaries should be removed from version 4.5.1?

**Comment by trufae** [comment]
@ret2libc ^

**Comment by ret2libc** [comment]
Are windows binaries for 4.5.1 broken or is it just that there are bugs in 4.5.1 in general? If the latter, I don't think we should remove windows binaries at all. If the former, we probably need to fix them.

**Comment by XVilka** [comment]
We probably need a test for this.

**Comment by ret2libc** [comment]
I've noticed that for some reasons the windows binaries are 32bit! So probably something wrong with the builds used to generate those binaries, I will have a look and maybe we need to do a new release just to fix this thing.
