### ISSUE TITLE
Do I have to install Radare system wide to run tests?

### ISSUE THREAD

**Issue by sudoWin** [radareorg/radare2#17808]
Hi, I was trying to contribute to radare2, and I tried running `make tests` to run all tests, but unfortunately, it shows, `r2r command not found`. Now my question is whether I have to install radare system-wide to run tests on every commit?

I have read CONTRIBUTING.md, README.md, and DEVELOPERS.md.

The steps I followed.

1. Clone my fork of radare2
2. ```./configure```
3. ```make```
4. ```make tests```

Please help me if I am missing out on something. Thanks

**Comment by trufae** [comment]
if you want to install, you need to type `make install`. or just use sys/install.sh which takes care of all this stuff
