### ISSUE TITLE
MSVC 2019 warnings

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17814]
Check the CI logs:

* 2020-01-17 https://github.com/radareorg/radare2/runs/1715637143?check_suite_focus=true

**Comment by eagleoflqj** [comment]
What to do with C4146? It doesn't seem a bug and msvc might be too pedantic.

**Comment by XVilka** [comment]
@eagleoflqj just ignore it.

**Comment by tanmay-pro** [comment]
I am a newcomer and I intend to contribute. Can I work on this issue? I will need some guidance though.

**Comment by eagleoflqj** [comment]
> I am a newcomer and I intend to contribute. Can I work on this issue? I will need some guidance though.

You can work on any issues you want. PRs are welcomed. There are also other good first issues.
These logs are outdated, but you can always get the latest log of CI on master branch.

**Comment by trufae** [comment]
Ignore the warnings in the issue most of them are old. The last build is in the CI and you can check the logs there. https://github.com/radareorg/radare2/runs/1715637143?check_suite_focus=true

**Comment by trufae** [comment]
Already fixed them all
