### ISSUE TITLE
gdb list command ?

### ISSUE THREAD

**Issue by Susanne588586** [radareorg/radare2#1783]
Hi,

what is r2 command is needed to get gdb list like output ?

KInd Regards
Susann E.

**Comment by dkasak** [comment]
This still throws the same error for me:

    [0x7f4662920d70]> CL sym.main
    Cannot find meta information at 0x7f4662920d70

Was this closed because it was fixed?

**Comment by radare** [comment]
works perfectly fine for me:

```
[0x0040052d]> CL $$
file /tmp/r2-regressions/.//dwarftest.c
line 4
  002
  003  int main(void)
> 004  {
  005  	int i;
  006
[0x0040052d]>
```

**Comment by radare** [comment]
works perfectly fine for me:

```
[0x0040052d]> CL $$
file /tmp/r2-regressions/.//dwarftest.c
line 4
  002
  003  int main(void)
> 004  {
  005  	int i;
  006
[0x0040052d]>
```

**Comment by radare** [comment]
and obviously /bin/ls doesnt have debugging information

**Comment by dkasak** [comment]
I did that on a binary with debugging information, though, not on `/bin/ls`.

**Comment by radare** [comment]
using the last version from git of today?
this was fixed  this morning

**Comment by dkasak** [comment]
Oh. That's quite a coincidence. I didn't notice and was going by the closing date of this issue. Thanks!

**Comment by Susanne588586** [comment]
@radare @dkasak

```
[0x004004a6]> CL $$
Cannot find meta information at 0x004004a6
[0x004004a6]> !date
Tue Jan 31 14:28:32 CET 2017
[0x004004a6]> !cat oob.c
//#include <stdio.h>
int main() {
int i[3] = { 3, 1,2 };
printf("%i\n", i[3]);
}
```
is there another command before needed?

**Comment by Susanne588586** [comment]
[0x004004a6]> CL oob.c:2
No meta info for oob.c|2 found

**Comment by radare** [comment]
If the bin is not compiled with dwarf CL will not work

**Comment by dkasak** [comment]
I'm not sure how the file:line argument is supposed to work (I can't get it to work either), but a plain `CL` works for me to list the source code of the current location. You can then use `@` to get source code of an arbitrary symbol, like this:

    CL @ sym.main

However, that's not quite like gdb yet since `CL source.c:<num>` doesn't seem to work. Also, the bin is compiled with DWARF.

**Comment by dkasak** [comment]
I should note I don't have the latest master however, since it doesn't compile for me at the moment, so it may have been fixed later on.

**Comment by Susanne588586** [comment]
@radare is dwarf the same as -g ?

**Comment by Susanne588586** [comment]
ok, works with CL @ sym.main, maybe that is more useful, then displaying only one line of source
