### ISSUE TITLE
missing response after `/*` command

### ISSUE THREAD

**Issue by Heersin** [radareorg/radare2#17848]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Manjaro 20.1.2 / x86_64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.5.1 0 @ linux-x86-64 git.4.5.1
commit: unknown build: 2020-09-24__20:31:44

### Expected behavior
when encounter an unexpected argument, r2 shell should report the usage info : 
```sh
[0x08048400]> /*
Usage: /[!bf] [arg]  Search stuff (see 'e??search' for options)
......
```

### Actual behavior
conflict with the "no news is good news". this command don't report any message. Besides, there is no response to subsequent commands. I only found this weird behavior under "/" command space.
```sh
 [xxx]$ r2 ./crackme
 -- Your r2 was built 20h ago. TOO OLD!
[0x08048400]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x08048400]> fs
    0 * classes
    1 * functions
    8 * imports
    8 * relocs
   27 * sections
   10 * segments
    6 * strings
    3 * symbols
[0x08048400]> /*
[0x08048400]> aa
[0x08048400]> fs
[0x08048400]> quit
[0x08048400]> 
# can quit by ctrl-D
```
### Steps to reproduce the behavior 
- use r2 to open a file (or enter the r2 shell)
- type "/*"

### Additional Logs, screenshots, source-code,  configuration dump, ...
By the way, Could anybody tell me how did u debug radare2 itself? I compiled it with `meson --buildtype=debug` but gdb reports no symbols (with debug-symbol-directory set)

**Comment by trufae** [comment]
Its a multiline comment command. Just type */

**Comment by trufae** [comment]
For ddbugging i always use sys/install.sh, so configure/make not meson. The meson people can probably help you on that issue because it should be working too

**Comment by Heersin** [comment]
> For ddbugging i always use sys/install.sh, so configure/make not meson. The meson people can probably help you on that issue because it should be working too
Thanks~ 
configure it without any argument ?

**Comment by Heersin** [comment]
> Its a multiline comment command. Just type */

OK, maybe we could add the description about "/*" under "/" command space. And I will update the docs then close this issus.
Thank u for ur help ～

**Comment by trufae** [comment]
Would you like to send a PR extending the help of / and * with this? 

anyway, those two commands doesnt work with the cfg.newshell cc @ret2libc

**Comment by ret2libc** [comment]
Which commands exactly? Could you open a bug with the exact commands?

**Comment by trufae** [comment]
The /* and */ commands

**Comment by ret2libc** [comment]
Ah ok I'm aware of those, though I would treat them as comments not commands.

**Comment by Heersin** [comment]
I will send a PR to extend the usage info
