### ISSUE TITLE
Consistent failure of db/archos/darwin-x64/http =h test on MacOS CI

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17867]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | https://github.com/radareorg/radare2/commit/b0ee85edbf230091ffbb46bdfe33a24004c84381

### Expected behavior

Test passes

### Actual behavior

```

[XX] db/archos/darwin-x64/http =h
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc !scripts/test-webserver.sh --
-- stderr
@@ -1 +1,2 @@
 
+scripts/test-webserver.sh: line 9: 45934 Terminated: 15          r2 -N -e http.port=9393 -qq -c=h bins/elf/arg > /dev/null 2>&1
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

https://github.com/radareorg/radare2/runs/1318601157#step:13:690

If there is no fix - I just suggest to mark it as broken.

**Comment by trufae** [comment]
Mark it as broken. i dont expect any fix anytime soon
