### ISSUE TITLE
C types parser - doesn't handle arrays

### ISSUE THREAD

**Issue by ricnar456** [radareorg/radare2#17884]
I parsed a structure like that, I created a .h and paste it and loaded using the to command

struct My_struct
{
  void *buf2;
  int cookie2;
  int cookie;
  char buf[50];
  char *p_size;
  int *p_cookie;
  char size;
  int leidos;
  int maxsize;
  void *foo2;
 _iobuf *f1;
} ;

but the char buf [50] is not well parsed

:> tsc My_struct
struct My_struct {
        void *buf2;
        int32_t cookie2;
        int32_t cookie;
        **char buf;**
        char *p_size;
        int32_t *p_cookie;
        char size;
        int32_t leidos;
        int32_t maxsize;
        void *foo2;
        void *f1;
};

and the fields are incorrectly listed

**:> ahts 4**
My_struct.cookie2
_FILETIME.dwHighDateTime
_GUID.Data2
_SYSTEMTIME.wDayOfWeek
**:> ahts 64
:> ahts 72**

this command doesn't show results

**Comment by ricnar456** [comment]
I'm trying to assign manually the field

using the internal representation tk

![image](https://user-images.githubusercontent.com/8556494/97800452-07c1d800-1c14-11eb-94ec-6c6e579392bc.png)

this display correctly the type, offset and size of the field

but when I tried to assign


the first fields are assigned nicely

the last fields cannot be assigned

![image](https://user-images.githubusercontent.com/8556494/97800459-14463080-1c14-11eb-9459-6bdfd84dd3d0.png)


I don't know if the bug is only related to the print of the fields

**Comment by ricnar456** [comment]
![image](https://user-images.githubusercontent.com/8556494/97800479-48215600-1c14-11eb-9d26-24d4907787f8.png)

if cannot be assigned manually maybe the bug is not only related to the print of the fields.

**Comment by ricnar456** [comment]
I suppose that a problem about print is only a visualization problem, if so I suppose that the field could be assigned manually, since it cannot be, it seems to be something more than just a problem when printing.

**Comment by ricnar456** [comment]
The first patch corrects the print problem but the assign or parse problem remains.

![image](https://user-images.githubusercontent.com/8556494/97848973-a0b62900-1cd0-11eb-8885-2091dbedb499.png)

I think the fixer knows this, for this reason he renamed the issue.

**Comment by pelijah** [comment]
```asm
[0x00401000]> aht My_struct.size @ 0x40101e
[0x00401000]> aht My_struct.cookie2 @ 0x40100a
[0x00401000]> aht My_struct.cookie @ 0x401014
[0x00401000]> pdf
/ 61: fcn.00401000 ();
|           ; var int32_t var_4h @ ebp-0x4
|           0x00401000      55             push ebp
|           0x00401001      8bec           mov ebp, esp
|           0x00401003      51             push ecx
|           0x00401004      894dfc         mov dword [var_4h], ecx
|           0x00401007      8b45fc         mov eax, dword [var_4h]
|           0x0040100a      c74004000000.  mov dword [eax + My_struct.cookie2], 0
|           0x00401011      8b4dfc         mov ecx, dword [var_4h]
|           0x00401014      c74108000000.  mov dword [ecx + My_struct.cookie], 0
|           0x0040101b      8b55fc         mov edx, dword [var_4h]
|           0x0040101e      c6424800       mov byte [edx + My_struct.size], 0
|           0x00401022      8b45fc         mov eax, dword [var_4h]
|           0x00401025      c7404c000000.  mov dword [eax + 0x4c], 0
|           0x0040102c      8b4dfc         mov ecx, dword [var_4h]
|           0x0040102f      c74150320000.  mov dword [ecx + 0x50], 0x32 ; '2'
|                                                                      ; [0x32:4]=-1 ; 50
|           0x00401036      8b45fc         mov eax, dword [var_4h]
|           0x00401039      8be5           mov esp, ebp
|           0x0040103b      5d             pop ebp
\           0x0040103c      c3             ret
```
