### ISSUE TITLE
ARM32 build warnings

### ISSUE THREAD

**Issue by eagleoflqj** [radareorg/radare2#17898]
On my rpi4 (Linux liumeo-rpi4 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux), all test errors fixed now.
```
pi@liumeo-rpi4:~/github/radare2/test $ r2 -v
radare2 4.6.0-git 25454 @ linux-arm-32 git.
commit: 8c742b28f089385cd76fd6b7a35cb658eb911237 build: 2020-12-20__14:25:02
pi@liumeo-rpi4:~/github/radare2/test $ r2r -L
Skipping db/archos/linux-x64 because it does not match the current platform.
Skipping db/archos/darwin-x64 because it does not match the current platform.
Skipping db/archos/windows-x64 because it does not match the current platform.
Skipping db/extras because it requires additional dependencies.
Loaded 14214 tests.
...
[**]                               db/cmd/cmd_zignature    13274 OK       927 BR        0 XX       13 FX

Finished in 14 minutes and 5 seconds.
```

**Comment by eagleoflqj** [comment]
Build warnings
```
CC hex.c
In file included from /home/pi/github/radare2/libr/include/r_types.h:220,
                 from str.c:3:
str.c: In function ‘r_str_encoded_json’:
/home/pi/github/radare2/libr/include/r_types_base.h:77:18: warning: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘18446744073709551615’ to ‘4294967295’ [-Woverflow]
 #define UT64_MAX 0xFFFFFFFFFFFFFFFFULL
                  ^~~~~~~~~~~~~~~~~~~~~
/home/pi/github/radare2/libr/include/r_types_base.h:110:18: note: in expansion of macro ‘UT64_MAX’
 #define SZT_MAX  UT64_MAX
                  ^~~~~~~~
str.c:1525:52: note: in expansion of macro ‘SZT_MAX’
   if (!SZT_MUL_OVFCHK (((buf_sz * increment) + 1), SZT_MAX)) {
                                                    ^~~~~~~
```
```
CC fs_io.c
In file included from /home/pi/github/radare2/libr/../shlr/sdb/src/sdb.h:13,
                 from /home/pi/github/radare2/libr/include/r_list.h:6,
                 from /home/pi/github/radare2/libr/include/r_util/r_graph.h:4,
                 from /home/pi/github/radare2/libr/include/r_cons.h:10,
                 from /home/pi/github/radare2/libr/include/r_diff.h:6,
                 from /home/pi/github/radare2/libr/include/r_util.h:7,
                 from /home/pi/github/radare2/libr/include/r_bin.h:4,
                 from dwarf.c:16:
dwarf.c: In function ‘dwarf_read_address’:
dwarf.c:403:12: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
   eprintf ("Weird dwarf address size: %lu.", size);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
/home/pi/github/radare2/libr/../shlr/sdb/src/types.h:12:37: note: in definition of macro ‘eprintf’
 #define eprintf(...) fprintf(stderr,__VA_ARGS__)
                                     ^~~~~~~~~~~
```
```
CC asm_arm_winedbg.c
/home/pi/github/radare2/libr/..//libr/bin/p/bin_dex.c: In function ‘dex_fields’:
/home/pi/github/radare2/libr/..//libr/bin/p/bin_dex.c:2100:86: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  r_list_append (ret, r_bin_field_new (addr, addr, siz, nam, sdb_fmt ("0x%08"PFMT64x, (ut64)val), fmt, false)); \
                                                                                      ^
/home/pi/github/radare2/libr/..//libr/bin/p/bin_dex.c:2109:2: note: in expansion of macro ‘ROW’
  ROW ("dex_signature", 8, signature, "[20]c");
  ^~~
```
```
CC hexagon.c
/home/pi/github/radare2/libr/..//libr/bin/p/../format/le/le.c: In function ‘r_bin_le_get_relocs’:
/home/pi/github/radare2/libr/..//libr/bin/p/../format/le/le.c:546:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    rel->addend = (ut64)r_list_get_n (entries, ordinal - 1);
                  ^
```
```
CC asm_riscv.c
/home/pi/github/radare2/libr/asm/arch/pyc/opcode.c: In function ‘new_pyc_opcode’:
/home/pi/github/radare2/libr/asm/arch/pyc/opcode.c:167:45: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
   ret->opcodes[i].op_name = r_str_newf ("<%lu>", i);
                                           ~~^    ~
                                           %u
```
```
CC var.c
var.c: In function ‘r_anal_extract_rarg’:
var.c:1011:30: warning: format ‘%lu’ expects argument of type ‘long unsigned in’, but argument 2 has type ‘size_t’ {aka ‘unsigned int’} [-Wformat=]
     name = r_str_newf ("arg%lu", i + 1);
                            ~~^   ~~~~~
                            %u
```
```
CC block.c
CC cond.c
CC value.c
CC cc.c
block.c: In function ‘automerge_predecessor_successor_cb’:
block.c:841:52: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  RAnalBlock *pred = ht_up_find (ctx->predecessors, (ut64)block, &found);
                                                    ^
block.c:845:37: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    ht_up_update (ctx->predecessors, (ut64) block, NULL);
                                     ^
block.c:849:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   ht_up_insert (ctx->predecessors, (ut64) block, ctx->cur_pred);
                                    ^
block.c: In function ‘automerge_get_predecessors_cb’:
block.c:856:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  const RAnalFunction *fcn = (const RAnalFunction *)k;
                             ^
block.c:861:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   ht_up_find (ctx->visited_blocks, (ut64)block, &already_visited);
                                    ^
block.c:868:38: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   ht_up_insert (ctx->visited_blocks, (ut64)block, (void *)ctx->cur_succ_count);
                                      ^
block.c: In function ‘r_anal_block_automerge’:
block.c:896:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    ht_up_insert (relevant_fcns, (ut64)fcn, NULL);
                                 ^
block.c:907:59: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   RAnalBlock *predecessor = ht_up_find (ctx.predecessors, (ut64)block, NULL);
                                                           ^
block.c:911:69: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   size_t pred_succs_count = (size_t)ht_up_find (ctx.visited_blocks, (ut64)predecessor, NULL);
                                                                     ^
block.c:923:59: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    RAnalBlock *fixup_pred = ht_up_find (ctx.predecessors, (ut64)clock, NULL);
                                                           ^
block.c:934:38: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    ht_up_update (ctx.visited_blocks, (ut64)predecessor, (void *)ctx.cur_succ_count);
                                      ^
block.c:937:37: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     ht_up_update (ctx.predecessors, (ut64)clock, predecessor);
```
```
CC debug_native.c
CC debug_null.c
CC debug_qnx.c
CC debug_rap.c
CC debug_winkd.c
In file included from p/debug_native.c:74:
p/native/linux/linux_coredump.h:60: warning: "R_DEBUG_REG_T" redefined
 #define R_DEBUG_REG_T struct user_regs_struct
 
In file included from p/debug_native.c:65:
p/native/linux/linux_debug.h:68: note: this is the location of the previous definition
 #define R_DEBUG_REG_T struct user_regs
 
p/debug_native.c: In function ‘r_debug_native_map_protect’:
p/debug_native.c:1513:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   "}\n", num, (void*)addr, size, io_perms_to_prot (perms));
               ^
```
```
CC linux_debug.c
CC procfs.c
CC linux_coredump.c
p/native/linux/linux_debug.c: In function ‘linux_handle_signals’:
p/native/linux/linux_debug.c:95:19: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   dbg->stopaddr = (ut64)siginfo.si_addr;
                   ^
p/native/linux/linux_debug.c: In function ‘print_fpu’:
p/native/linux/linux_debug.c:1058:2: warning: #warning print_fpu not implemented for this platform [-Wcpp]
 #warning print_fpu not implemented for this platform
  ^~~~~~~
p/native/linux/linux_debug.c: In function ‘linux_reg_read’:
p/native/linux/linux_debug.c:1162:3: warning: #warning getfpregs not implemented for this platform [-Wcpp]
  #warning getfpregs not implemented for this platform
   ^~~~~~~
p/native/linux/linux_debug.c:1063:7: warning: variable ‘showfpu’ set but not used [-Wunused-but-set-variable]
  bool showfpu = false;
       ^~~~~~~
At top level:
p/native/linux/linux_debug.c:970:13: warning: ‘print_fpu’ defined but not used -Wunused-function]
 static void print_fpu(void *f){
             ^~~~~~~~~
```
```
CC panels.c
CC pseudo.c
CC vmarks.c
panels.c: In function ‘__fix_layout_w’:
panels.c:2612:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   r_list_append (list, (void *)(t));
                        ^
panels.c:2626:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    if ((int64_t)num - 1 == tx) {
        ^
panels.c:2630:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    int sub = (int64_t)num - tx;
              ^
panels.c:2633:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     target_num = (int64_t)num;
                  ^
panels.c: In function ‘__fix_layout_h’:
panels.c:2653:24: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   r_list_append (list, (void *)(t));
                        ^
panels.c:2668:8: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    if ((int64_t)num - 1 == ty) {
        ^
panels.c:2672:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    int sub = (int64_t)num - ty;
              ^
panels.c:2675:18: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     target_num = (int64_t)num;
                  ^
```

**Comment by XVilka** [comment]
Can you please update these? I believe some should be fixed already.

**Comment by eagleoflqj** [comment]
Unit tests. For test_r_anal_block*, I fail on ubuntu x64 too, which may be my misconfiguring something, since there's no problem on CI.
pi@liumeo-rpi4:~/github/radare2/test $ make unit
make -C unit
make[1]: 进入目录“/home/pi/github/radare2/test/unit”
make[1]: 对“all”无需做任何事。
make[1]: 离开目录“/home/pi/github/radare2/test/unit”
make -C unit run
make[1]: 进入目录“/home/pi/github/radare2/test/unit”
r=0 ; cd .. ; for a in bin/test_parse_ctype bin/test_diff bin/test_bin bin/test_json bin/test_debruijn bin/test_anal_var bin/test_cmd bin/test_bitmap bin/test_debug bin/test_sign bin/test_event bin/test_sparse bin/test_queue bin/test_glob bin/test_base64 bin/test_anal_function bin/test_id_storage bin/test_util bin/test_dwarf_info bin/test_anal_types bin/test_anal_xrefs bin/test_uleb128 bin/test_dwarf_integration bin/test_buf bin/test_tree bin/test_agraph bin/test_str bin/test_anal_hints bin/test_intervaltree bin/test_stack bin/test_ovf bin/test_esil_dfg_filter bin/test_vector bin/test_rbtree bin/test_table bin/test_anal_cc bin/test_anal_block bin/test_r2r bin/test_unum bin/test_hex bin/test_strbuf bin/test_io bin/test_addr_interval bin/test_big bin/test_anal_class_graph bin/test_list bin/test_pj bin/test_idpool bin/test_anal_meta bin/test_pdb bin/test_binheap bin/test_flags bin/test_cons bin/test_reg bin/test_dwarf bin/test_graph bin/test_idstorage bin/test_r2pipe bin/test_annotated_code bin/test_debug_session bin/test_spaces bin/test_skiplist bin/test_contrbtree ; do  ./unit/$a || r=1; done ; echo unit$r ; exit $r
test_r_parse_ctype OK
test_r_parse_ctype_identifier_kind OK
test_r_diff_buffers_distance OK
test_r_bin OK
test_json (1) OK
test_json (2) OK
test_json (3) OK
test_json (4) OK
test_json (5) OK
test_json (6) OK
test_json (7) OK
test_json (8) OK
test_json (9) OK
test_json (10) OK
test_json (11) OK
test_json (12) OK
test_json (13) OK
test_json (14) OK
test_json (15) OK
test_json (16) OK
test_json (17) OK
test_json (18) OK
test_json (19) OK
test_json (20) OK
test_json (21) OK
test_json (22) OK
test_json (23) OK
test_json (24) OK
test_json (25) OK
test_json (26) OK
test_json (27) OK
test_json (28) OK
test_json (29) OK
test_json (30) OK
test_json (31) OK
test_json (32) OK
test_json (33) OK
test_json (34) OK
test_json (35) OK
test_json (36) OK
test_json (37) OK
test_json (38) OK
test_json (39) OK
test_json (40) OK
test_json (41) OK
test_json (42) OK
test_json (43) OK
test_json (44) OK
test_json (45) OK
test_json (46) OK
test_json (47) OK
test_json (48) OK
test_json (49) OK
test_json (50) OK
test_json (51) OK
test_json (52) OK
test_json (53) OK
test_json (54) OK
test_json (55) OK
test_json (56) OK
test_r_debruijn_pattern OK
test_r_debruijn_offset OK
test_r_anal_var OK
test_parsed_args_noargs OK
test_parsed_args_onearg OK
test_parsed_args_args OK
test_parsed_args_nospace OK
test_parsed_args_newcmd OK
test_parsed_args_newargs OK
test_cmd_descriptor_argv OK
test_cmd_descriptor_argv_nested OK
test_cmd_descriptor_oldinput OK
test_cmd_descriptor_tree OK
test_cmd_descriptor_group OK
test_cmd_get_desc OK
test_cmd_call_desc OK
test_cmd_help OK
test_cmd_group_help OK
test_cmd_oldinput_help OK
test_remove_cmd OK
test_r_bitmap_set OK
test_r_debug_use OK
test_r_debug_reg_offset OK
test_anal_sign_get_set ERR
[XX] Fail at line 60: get item: expected to not be NULL but it was.

test_r_event OK
test_r_buf_new_sparse OK
test_r_queue_add_remove OK
test_r_queue_zero_size OK
test_r_glob OK
test_r_base64_decode_dyn OK
test_r_base64_decode OK
test_r_base64_decode_invalid OK
test_r_base64_encode_dyn OK
test_r_base64_encode OK
test_r_anal_function_relocate OK
test_r_anal_function_labels OK
test_r_id_storage_prev_next_eq_0 OK
test_r_id_storage_prev_next_eq_1 OK
test_r_id_storage_prev_next_eq_2 OK
test_r_id_storage_prev_next_min OK
test_r_id_storage_toomany OK
test_prevnext OK
test_r_id_storage_empty OK
test_r_id_storage_wrong OK
test_ignore_prefixes OK
test_remove_r2_prefixes OK
test_dll_names OK
test_references OK
test_autonames OK
test_file_slurp OK
test_initial_underscore OK
test_dwarf3_c OK
test_dwarf4_cpp_multiple_modules OK
test_dwarf2_big_endian OK
Segmentation fault
test_r_anal_xrefs_count OK
test_uleb128_small OK
test_sleb128_small OK
test_uleb128_big OK
test_sleb128_big OK
test_leb128_correctness OK
Segmentation fault
test_r_buf_file OK
test_r_buf_bytes OK
test_r_buf_mmap OK
test_r_buf_with_buf OK
test_r_buf_slice OK
test_r_buf_io OK
test_r_buf_sparse OK
test_r_buf_sparse2 OK
test_r_buf_bytes_steal OK
test_r_buf_format OK
test_r_buf_get_string OK
test_r_buf_get_string_nothing OK
test_r_buf_slice_too_big OK
test_r_tree OK
test_graph_to_agraph OK
test_r_str_newf OK
test_r_str_replace_char_once OK
test_r_str_replace_char OK
test_r_str_replace OK
test_r_str_bits64 OK
test_r_str_rwx OK
test_r_str_rwx_i OK
test_r_str_bool OK
test_r_str_trim OK
test_r_str_case OK
test_r_str_split OK
test_r_str_tokenize OK
test_r_str_char_count OK
test_r_str_word_count OK
test_r_str_ichr OK
test_r_str_lchr OK
test_r_sub_str_lchr OK
test_r_sub_str_rchr OK
test_r_str_rchr OK
test_r_str_ansi_len OK
test_r_str_len_utf8_ansi OK
test_r_str_utf8_charsize OK
test_r_str_utf8_charsize_prev OK
test_r_str_sanitize_sdb_key OK
test_r_str_escape_sh OK
test_r_str_unescape OK
test_r_str_constpool OK
test_r_str_format_msvc_argv OK
test_r_str_str_xy OK
Segmentation fault
test_r_anal_addr_hints OK
test_r_anal_hints_arch OK
test_r_anal_hints_bits OK
seed for test_intervaltree: 1606220984
test_r_interval_tree_insert_at OK
test_r_interval_tree_in_end_exclusive_point OK
test_r_interval_tree_in_end_inclusive_point OK
test_r_interval_tree_in_end_exclusive_interval OK
test_r_interval_tree_in_end_inclusive_interval OK
test_r_interval_tree_all_at OK
test_r_interval_tree_node_at_data OK
test_r_interval_tree_delete OK
test_r_interval_tree_resize_start_and_end OK
test_r_interval_tree_resize_end_only OK
test_r_stack_pop_empty OK
test_r_stack_push_pop OK
test_r_stack_push_pop_multi OK
test_r_stack_grow OK
test_overflow_add OK
test_underflow_add OK
test_underflow_sub OK
test_overflow_mul OK
test_overflow_mul2 OK
test_filter_regs OK
test_vector_init OK
test_vector_new OK
test_vector_fini ERR
[XX] Fail at line 68: init elem_size: expected 8, got 4.

test_vector_clear OK
test_vector_free OK
test_vector_clone OK
test_vector_empty OK
test_vector_remove_at OK
test_vector_insert OK
test_vector_insert_range OK
test_vector_pop OK
test_vector_pop_front OK
test_vector_push OK
test_vector_push_front OK
test_vector_reserve OK
test_vector_shrink OK
test_vector_foreach OK
test_vector_lower_bound OK
test_pvector_init OK
test_pvector_new OK
test_pvector_clear OK
test_pvector_free OK
test_pvector_at OK
test_pvector_set OK
test_pvector_contains OK
test_pvector_remove_at OK
test_pvector_insert OK
test_pvector_insert_range OK
test_pvector_pop OK
test_pvector_pop_front OK
test_pvector_push OK
test_pvector_push_front OK
test_pvector_sort OK
test_pvector_foreach OK
test_pvector_lower_bound OK
test_r_rbtree_bound OK
test_r_rbtree_bound_iterate OK
test_r_rbtree_insert_delete OK
test_r_rbtree_traverse OK
test_r_rbtree_augmented_insert_delete OK
test_r_rbtree_augmented_insert_delete2 OK
test_r_table OK
test_r_table_column_type OK
test_r_table_tostring OK
test_r_table_sort1 OK
test_r_table_uniq OK
test_r_table_group OK
test_r_table_columns OK
Segmentation fault
seed for test_anal_block: 1606302770
test_r_anal_block_chop_noreturn ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r_anal_block_create ERR
[XX] Fail at line 34: created initial ref: expected 1, got 19376464.

test_r_anal_block_contains OK
test_r_anal_block_split ERR
[XX] Fail at line 90: ref after nop split: expected 2, got 19501592.

test_r_anal_block_split_in_function ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r_anal_block_merge OK
test_r_anal_block_merge_in_function ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r_anal_block_delete ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r_anal_block_set_size ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r_anal_block_relocate ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r_anal_block_query ERR
[XX] Fail at line 428: block refd in returned list: expected 2, got 20236384.

test_r_anal_block_successors ERR
[XX] Fail at line 545: block refd in returned list: expected 2, got 20395840.

test_r_anal_block_automerge ERR
[XX] Fail at line 48: function references block, but block does not reference function

test_r2r_database_load_cmd OK
test_r2r_fix OK
test_r_num_units OK
test_r_num_minmax_swap_i OK
test_r_num_minmax_swap OK
test_r_num_between OK
test_r_num_str_len OK
test_r_num_str_split OK
test_r_num_str_split_list OK
test_r_hex_from_c OK
test_r_hex_from_py OK
test_r_hex_from_code OK
test_r_hex_no_code OK
test_r_strbuf_append OK
test_r_strbuf_strong_string OK
test_r_strbuf_strong_binary OK
test_r_strbuf_weak_string OK
test_r_strbuf_weak_binary OK
test_r_strbuf_slice OK
test_r_strbuf_setbin OK
test_r_strbuf_set OK
test_r_strbuf_setf OK
test_r_strbuf_initf OK
test_r_io_mapsplit OK
test_r_io_mapsplit2 OK
test_r_io_mapsplit3 OK
test_r_io_pcache OK
test_r_io_desc_exchange OK
test_r_io_priority OK
test_r_io_priority2 OK
test_va_malloc_zero OK
test_r_itv_contain OK
test_r_itv_include OK
test_r_itv_overlap OK
test_r_big_from_to_int OK
test_r_big_from_to_hexstr OK
test_r_big_assign OK
test_r_big_cmp OK
test_r_big_add OK
test_r_big_sub OK
test_r_big_mul OK
test_r_big_div OK
test_r_big_divmod OK
test_r_big_mod OK
test_r_big_and OK
test_r_big_or OK
test_r_big_xor OK
test_r_big_inc OK
test_r_big_dec OK
test_r_big_is_zero OK
test_r_big_lshift OK
test_r_big_rshift OK
test_r_big_powm OK
test_r_big_isqrt OK
test_inherit_graph_creation OK
test_r_list_size OK
test_r_list_values OK
test_r_list_join OK
test_r_list_free OK
test_r_list_del_n OK
test_r_list_sort OK
test_r_list_sort2 OK
test_r_list_sort3 OK
test_r_list_sort4 OK
test_r_list_sort5 OK
test_r_list_mergesort_pint OK
test_r_list_length OK
test_r_list_append_prepend OK
test_r_list_set_get OK
test_r_list_reverse OK
test_r_list_clone OK
test_pj_reset OK
test_r_id_pool_broken_parameters OK
test_r_id_pool_start_id OK
test_r_id_pool_id_reuse0 OK
test_r_id_pool_id_reuse1 OK
test_r_id_pool_id_unique OK
test_r_id_pool_id_end_of_pool OK
test_r_id_pool_initial_pattern OK
test_meta_set ERR
[XX] Fail at line 46: set count: expected 3, got 0.

test_meta_get_at OK
test_meta_get_in OK
test_meta_get_all_at OK
test_meta_get_all_in OK
test_meta_get_all_intersect OK
test_meta_del OK
test_meta_rebase ERR
[XX] Fail at line 485: set count: expected 3, got 0.

test_meta_spaces ERR
[XX] Fail at line 534: set count: expected 4, got 0.

test_pdb_tpi_cpp OK
test_pdb_tpi_rust OK
Segmentation fault
test_basic OK
test_pushpop OK
test_r_flag_get_set OK
test_r_flag_by_spaces OK
test_r_flag_get_at OK
test_r_cons OK
test_cons_to_html OK
test_r_reg_set_name OK
test_r_reg_set_profile_string OK
test_r_reg_get_value_gpr OK
test_r_reg_get_value_flag OK
test_r_reg_get OK
test_r_reg_get_list OK
test_r_reg_get_pack OK
test_dwarf_cpp_empty_line_info OK
test_dwarf2_cpp_many_comp_units OK
test_dwarf3_c_basic OK
test_dwarf3_cpp_basic OK
test_dwarf3_cpp_many_comp_units OK
test_dwarf4_cpp_many_comp_units OK
test_big_endian_dwarf2 OK
test_legacy_graph OK
test_r_id_storage_add0 OK
test_r_id_storage_add1 OK
test_r_id_storage_set OK
test_r_id_storage_delete OK
test_r_id_storage_take0 OK
test_r_id_storage_take1 OK
test_r2pipe OK
sh: 1: rodoro2: not found
return code 32512 for rodoro2 -q0 -
[+] r2pipe link error.
test_r2pipe_404 OK
test_r_annotated_code_new OK
test_r_annotated_code_free OK
test_r_annotated_code_add_annotation OK
test_r_annotated_code_annotations_in OK
test_r_annotated_code_annotations_range OK
test_r_annotated_code_line_offsets OK
test_r_core_annotated_code_print_json OK
test_r_core_annotated_code_print_json_context_annotations OK
test_r_core_annotated_code_print OK
test_r_core_annotated_code_print_comment_cmds OK
test_r_annotation_free_and_is_annotation_type_functions OK
test_session_save OK
test_session_load OK
test_space_basic OK
test_space_stack OK
test_space_event OK
test_empty OK
test_oneelement OK
test_insert OK
test_insert_existing OK
test_purge OK
test_delete OK
test_join OK
test_r_rbtree_cont_insert OK
test_r_rbtree_cont_delete OK
unit1
make[1]: *** [Makefile:18：run] 错误 1
make[1]: 离开目录“/home/pi/github/radare2/test/unit”
make: *** [Makefile:55：unit] 错误 2

**Comment by eagleoflqj** [comment]
This test is slow.
pi@liumeo-rpi4:~/github/radare2/test $ time ~/bin/prefix/radare2/bin/r2 -Qc 'aa
om~?
s   
pi 1
q!
' bins/pe/65535sects.exe
[x] Analyze all flags starting with sym. and entry0 (aa)
65536
0x291120
mov edi, 0x7027aff9

real	1m50.779s
user	1m50.360s
sys	0m0.371s

**Comment by trufae** [comment]
Thanks for identifying it. I found other slow tests too. We can do different things here:

* disable it
* Rewrite it to be fast (using a smaller binary or reproducer)
* only run it in asan builds which are already slow
* Optimize r2 to make this test fast


Ci time is precious. We must take care of it.

i cactually wanted to have a benchmark ci. Like the V people do

**Comment by trufae** [comment]
Is this issue fixed now?

**Comment by eagleoflqj** [comment]
> Is this issue fixed now?

Yes, tests are all passed now. Only warnings remain. Feel free to close it.

**Comment by trufae** [comment]
Can you paste the updated list of warnings in here?

**Comment by eagleoflqj** [comment]
> Can you paste the updated list of warnings in here?

Updated above https://github.com/radareorg/radare2/issues/17898#issuecomment-724775961 when 5.0.0 released.

**Comment by trufae** [comment]
Some of them can be solved with an intermediate size_t cast, just if the destination is ut64. For the other cases in afraid its bad code that must be fixed. I can take care of the one in panels unless you started already

**Comment by eagleoflqj** [comment]
> Some of them can be solved with an intermediate size_t cast, just if the destination is ut64. For the other cases in afraid its bad code that must be fixed. I can take care of the one in panels unless you started already

I'm still dealing with pj of lazula's branch. I'll take care of the intermediate casts and you may fix other stuff.
