### ISSUE TITLE
r2 -V shows incorrect version

### ISSUE THREAD

**Issue by fr0ster** [radareorg/radare2#17918]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
| r2 -v full output, **not truncated** (mandatory)     | rradare2 4.6.0-git 25377 @ linux-x86-64 git.4.4.0-925-g14f82ee30
commit: 14f82ee3012e10b56674a01c360ac1fbc4b4bf52 build: 2020-11-13__22:50:40

### Expected behavior

When I use r2 -v I get version 4.6.0
$ r2 -v 
radare2 4.6.0-git 25377 @ linux-x86-64 git.4.4.0-925-g14f82ee30
commit: 14f82ee3012e10b56674a01c360ac1fbc4b4bf52 build: 2020-11-13__22:50:40

when I check libs version I get
$ r2 -V
4.4.0-925-g14f82ee30  r2
4.4.0-925-g14f82ee30  r_anal
4.4.0-925-g14f82ee30  r_lib
4.4.0-925-g14f82ee30  r_egg
4.4.0-925-g14f82ee30  r_asm
4.4.0-925-g14f82ee30  r_bin
4.4.0-925-g14f82ee30  r_cons
4.4.0-925-g14f82ee30  r_flag
4.4.0-925-g14f82ee30  r_core
4.4.0-925-g14f82ee30  r_crypto
4.4.0-925-g14f82ee30  r_bp
4.4.0-925-g14f82ee30  r_debug
4.4.0-925-g14f82ee30  r_main
4.4.0-925-g14f82ee30  r_hash
4.4.0-925-g14f82ee30  r_fs
4.4.0-925-g14f82ee30  r_io
4.4.0-925-g14f82ee30  r_magic
4.4.0-925-g14f82ee30  r_parse
4.4.0-925-g14f82ee30  r_reg
4.4.0-925-g14f82ee30  r_sign
4.4.0-925-g14f82ee30  r_search
4.4.0-925-g14f82ee30  r_syscall
4.4.0-925-g14f82ee30  r_util

### Actual behavior

r2 -V should show correct version - 4.6.0

### Steps to reproduce the behavior 
$ git clone https://github.com/radareorg/radare2.git && cd radare2
$ ./sys/install.sh --install --with-capstone5
$ r2 -v
radare2 4.6.0-git 25377 @ linux-x86-64 git.4.4.0-925-g14f82ee30
commit: 14f82ee3012e10b56674a01c360ac1fbc4b4bf52 build: 2020-11-13__22:50:40
$ r2 -V
4.4.0-925-g14f82ee30  r2
4.4.0-925-g14f82ee30  r_anal
4.4.0-925-g14f82ee30  r_lib
4.4.0-925-g14f82ee30  r_egg
4.4.0-925-g14f82ee30  r_asm
4.4.0-925-g14f82ee30  r_bin
4.4.0-925-g14f82ee30  r_cons
4.4.0-925-g14f82ee30  r_flag
4.4.0-925-g14f82ee30  r_core
4.4.0-925-g14f82ee30  r_crypto
4.4.0-925-g14f82ee30  r_bp
4.4.0-925-g14f82ee30  r_debug
4.4.0-925-g14f82ee30  r_main
4.4.0-925-g14f82ee30  r_hash
4.4.0-925-g14f82ee30  r_fs
4.4.0-925-g14f82ee30  r_io
4.4.0-925-g14f82ee30  r_magic
4.4.0-925-g14f82ee30  r_parse
4.4.0-925-g14f82ee30  r_reg
4.4.0-925-g14f82ee30  r_sign
4.4.0-925-g14f82ee30  r_search
4.4.0-925-g14f82ee30  r_syscall
4.4.0-925-g14f82ee30  r_util

**Comment by pelijah** [comment]
Tags `4.5.0` and `4.5.1` aren't merged. Thats why `git describe --tags --match "[0-9]*"` (which is used by buildsystems to generate version string) returns `4.4.0` (the latest merged tag).
```
$ git tag --list --no-merged
...
4.5.0
4.5.1
...
```

**Comment by ret2libc** [comment]
@pelijah true,that's the issue, though I wonder why we take two different versions from git instead of just one.

**Comment by trufae** [comment]
Its actually wrong to assume the last tag is actually the last one. Order must depend on the branch. Also the ci adds the anoying continous tag and other non version syntax tags can appear sometimes. I dont know why those tags were not merged either. I implemented the -q thing in acr just for that. So we can get the version from there instrad of asuming the git knows what its doing

**Comment by trufae** [comment]
I will fix this when tagging a new release

**Comment by trufae** [comment]
After tagging for the release it went worst.. on tarball and git..

```
$ r2 -V
  r2
  r_anal
  r_lib
  r_egg
  r_asm
  r_bin
  r_cons
  r_flag
  r_core
  r_crypto
  r_bp
  r_debug
  r_main
  r_hash
  r_fs
  r_io
  r_magic
  r_parse
  r_reg
  r_sign
  r_search
  r_syscall
  r_util
$
```

Targetting 5.1.0

**Comment by pelijah** [comment]
So at least tag `5.0.0` is merged
```cmd
$ git describe --tags --match "[0-9]*"
5.0.0
```

**Comment by pelijah** [comment]
With option `--long` an output looks fine
```
$ git describe --long --tags --match "[0-9]*"
5.0.0-0-ga476454c0
```

**Comment by trufae** [comment]
I think this is fixed now
