### ISSUE TITLE
Changing scr.color removes part of reloff in disassembly

### ISSUE THREAD

**Issue by flobotics** [radareorg/radare2#17961]
hi,
if you change the color with  e scr.color=0  it removes part of the reloff in the disassembly.  If you start radare2 

radare2 4.5.0-git 24414 @ linux-x86-64 git.4.4.0-418-g74d5a677e
commit: 74d5a677e10d311b2c4ddf489eb617925609d1d4 build: 2020-07-15__00:00:56

then with pdf command, the lines start with e.g. 
    0x00001346

If you set  "e asm.reloff=true" , the lines start with e.g. 
   fcn.00001289+0xbd 

if you then set "e scr.color=0", the lines start with e.g. 
    +0xbd

Expectation:
i expect that the lines still look like:
     fcn.00001289+0xbd

just without terminal color codes.

         0x00001346      90             nop
│           0x00001347      488b45e8       mov rax, qword [var_18h]
│           0x0000134b      644833042528.  xor rax, qword fs:[0x28]
│       ┌─< 0x00001354      7425           je 0x137b
└      ┌──< 0x00001356      eb1e           jmp loc.00001376
[0x00001289]> e asm.reloff
asm.reloff         asm.reloff.flags   
[0x00001289]> e asm.reloff
false
[0x00001289]> e asm.reloff=true
[0x00001289]> pdf
│           fcn.00001289+0xbd                     90             nop
│           fcn.00001289+0xbe                     488b45e8       mov rax, qword [var_18h]
│           fcn.00001289+0xc2                     644833042528.  xor rax, qword fs:[0x28]
│       ┌─< fcn.00001289+0xcb                     7425           je 0x137b
└      ┌──< fcn.00001289+0xcd                     eb1e           jmp loc.00001376
[0x00001289]> e scr.color
3
[0x00001289]> e scr.color=0
│           +0xbd     90             nop
│           +0xbe     488b45e8       mov rax, qword [var_18h]
│           +0xc2     644833042528.  xor rax, qword fs:[0x28]
│       ┌─< +0xcb     7425           je 0x137b
└      ┌──< +0xcd     eb1e           jmp loc.00001376

thx

**Comment by XVilka** [comment]
We probably should have a few tests with colors enabled.
