### ISSUE TITLE
PE corkami timeouts after PE parsing and skyline refactoring

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17979]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | https://github.com/radareorg/radare2/commit/58ac34cea519de46d5a5e0ff391ca1ef3ff6dcd8

### Expected behavior

No timeouts

### Actual behavior

See https://github.com/radareorg/radare2/runs/1462057408#step:13:627 (ASAN build)
```
[XX] TIMEOUT db/formats/pe/foldedhdrW7 PE: corkami foldedhdrW7.exe - open
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc q! bins/pe/foldedhdrW7.exe
-- exit status: -1
[XX] TIMEOUT db/formats/pe/foldedhdrW7 PE: corkami foldedhdrW7.exe - open
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc q! bins/pe/foldedhdrW7.exe
-- exit status: -1
```

Looks like they were introduced by combining two refactors together - skyline refactor and PE/MDMP parsing refactoring @eagleoflqj @GustavoLCR

**Comment by eagleoflqj** [comment]
I can't reproduce locally on ubuntu x64, whether using meson or configure+make. commit a335247dacde918d027b776cea13bba20238de8c

**Comment by XVilka** [comment]
Yes, it's about ASAN time limit.
