### ISSUE TITLE
"Error: Unknown escape sequence" message occurred when start debugging

### ISSUE THREAD

**Issue by mug896** [radareorg/radare2#17970]
### Work environment

$ r2 -v full
radare2 4.6.0-git 25531 @ linux-x86-64 git.4.4.0-960-gb81cf6665
commit: b81cf6665f918720bd6c7b2e90f96f6789a03627 build: 2020-11-24__15:17:40

$ hostnamectl 
         Icon name: computer-laptop
           Chassis: laptop
  Operating System: Ubuntu 20.10
            Kernel: Linux 5.8.0-29-generic
      Architecture: x86-64

### Additional Logs, screenshots, source-code,  configuration dump, ...

$ r2 -dA a.out
Error: Unknown escape sequence. 
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Error: Unknown escape sequence.
Process with PID 254274 started...
= attach 254274 254274
bin.baddr 0x5589b2d9f000
Using 0x5589b2d9f000
asm.bits 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[TOFIX: aaft can't run in debugger mode.ions (aaft)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Integrate dwarf function information.
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x7f102ebb30d0]>

**Comment by trufae** [comment]
Cant repro in 5.2, please reopen in case im missing something ( i tested it on ubuntu-amd64, macos and debian-arm64)
