### ISSUE TITLE
Breakpoints don't work with Golang elf files

### ISSUE THREAD

**Issue by mooncat-greenpy** [radareorg/radare2#18013]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
$ radare2 -v
radare2 4.3.1 0 @ linux-x86-64 git.4.3.1
commit: HEAD build: 2020-03-06__15:05:41
$ uname -ms
Linux x86_64
```

## Description
Breakpoints don't work with Golang elf files.
I suspect this issue is due to the thread handling at the start of debugging using the odd command.
But there is no basis.

## Test
The following is a command for reproduction/
Sample: [sample.zip](https://github.com/radareorg/radare2/files/5665729/sample.zip)
```
$ radare2 sample
> ood
> aaa
> db sym.main.main
> dc
```

The image below is the execution result.
![radare2_compare](https://user-images.githubusercontent.com/73331490/101628317-f960aa80-3a62-11eb-907b-d803c8e2352e.JPG)

**Comment by ELSS-ZION** [comment]
I run into the same issue.
```
# r2 -v
radare2 5.9.9 32984 @ linux-x86-64
birth: git.5.9.8-74-gdcbfb8e869 2024-12-02__12:10:57
commit: dcbfb8e869be4440efb839c088e0b6a147148fb2
options: gpl -O? cs:5 cl:2 make
```

**Comment by trufae** [comment]
They work fine, it's just that Go signal initialization needs some tweaking to ignore the events that happen before main.

```
 r2 -d ./hello 
WARN: Compressed dwarf sections not yet supported
WARN: Relocs has not been applied. Please use `-e bin.relocs.apply=true` or `-e bin.cache=true` next time
 -- Do you want to restart to install these updates now or try tonight?
[0x0046cf40]> dko 19 cont
[0x0046cf40]> dko 23 cont
[0x0046cf40]> db sym.main.main 
[0x0046cf40]> dc
(350559) Created thread 350566
(350559) Created thread 350567
[+] SIGNAL 23 errno=0 addr=0x3e80005595f code=-6 si_pid=350559 ret=0
INFO: Continue into the signal 23 handler
(350559) Created thread 350568
[+] SIGNAL 19 errno=0 addr=0x00000000 code=0 si_pid=0 ret=0
INFO: Continue into the signal 19 handler
INFO: hit breakpoint at: 0x48f6e0
[+] signal 23 aka SIGURG received 1 (Urgent)
[0x0048f6e0]> dc
hello world
(350559) Process exited with status=0x0
[0x0046cfeb]> 
```

**Comment by trufae** [comment]
ood doesnt seems to work, but there's a separate issue about that. maybe we can have a default signal handling configuration. but i think that's up to the user and stop on all the signals is better behaviour even if not intuitive.

If you think that should change please fill a ticket about that
