### ISSUE TITLE
Esil Syscalls

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#18029]
So far, esil only has an operation for interrupts `$`, but not for syscalls. I propose `()` as operation for syscalls.
This feature requires:
- [ ] r_anal_esil_do_syscall (like r_anal_esil_fire_interrupt)
- [ ] `()` operation in esil
- [ ] load commands for syscall implementation like aeli (propose: aels)

**Comment by condret** [comment]
implemented

**Comment by trufae** [comment]
i marked the three tasks as done, but the last pr is not yet merged. and will be good to introduce a basic plugin with some syscalls implemented too
