### ISSUE TITLE
Segfault while decoding specific AArch64 instruction

### ISSUE THREAD

**Issue by BenHall-7** [radareorg/radare2#18038]
## Environment

Sun 12/13/2020
radare2 4.5.0 1 @ windows-x86-32 git.4.5.0
commit: 9d7eda5ec7367d1682e489e92d1be8e37e459296 build: Fri 07/17/2020__11:10:04.28

Info about the ELF file in case any of it is meaningful:

```
fd       3
file     [REDACTED]
size     0x15a748
humansz  1.4M
mode     rwx
format   elf64
iorw     true
blksz    0x0
block    0x100
type     DYN (Shared object file)
arch     arm
baddr    0x0
binsz    1417784
bintype  elf
bits     64
canary   false
class    ELF64
crypto   false
endian   little
havecode true
laddr    0x0
lang     c++
linenum  false
lsyms    false
machine  ARM aarch64
maxopsz  4
minopsz  4
nx       false
os       linux
pcalign  4
pic      true
relocs   false
relro    no
rpath    NONE
sanitiz  false
static   true
stripped true
subsys   linux
va       true
```

## Description

This instruction I ran across causes radare2's instruction decoder to segfault for a reason I don't yet know: `ldur x0, [x29, foo]`. It seems to crash for any negative value of 'foo'.

## Test

In my case the value of "foo", as in the above snippet, is -0x58. I've tried writing an instruction in its place to test with, with other numbers as well (positive, negative, and 0); decoding negative values crashes reliably.

Example commands to reproduce segfault (with write mode active):

```
wa ldur x0, [x29, -0x58]
pi 1
```

**Comment by trufae** [comment]
Cant reproduce in master is this r2 from git?

**Comment by trufae** [comment]
The commit referenced in your output is 3 month old

**Comment by BenHall-7** [comment]
It's present in releases 4.5.0 and 4.5.1 at least, which I understand are dated. However without a more recent release I don't have an option to avoid it currently. I could try building from source, but it's a bit difficult in part because I use Windows. I'd like to try it when I'm home again but that may be a while

**Comment by pelijah** [comment]
Can't reproduce in master branch on Windows.
```asm
[0x00000000]> wx a0835af8
[0x00000000]> pi 1
ldur x0, [x29, -0x58]
```

**Comment by BenHall-7** [comment]
Thank you for confirming. I’ll close the issue but I would greatly appreciate if you could provide a windows build for me. I’ve been trying to build on windows with meson and msvc, but have run into linker errors

**Comment by pelijah** [comment]
[radare2_vs2019_x64.zip](https://github.com/radareorg/radare2/files/5705594/radare2_vs2019_x64.zip)
