### ISSUE TITLE
Initial value of anal.cc variable is empty

### ISSUE THREAD

**Issue by pelijah** [radareorg/radare2#18086]
## Environment

```sh
radare2 5.0.0 25770 @ windows-x86-64 git.4.4.0-1083-ga476454c0
commit: a476454c00f64acbb7425c178c98714ef76e26d7 build: 21.12.2020__22:56:22,76
```

## Description

`anal.cc` variable value is not synced with the actual value of `default.cc` kv in `anal/cc` namespace.
The variable value is initialized before loading of a CC sdb to `anal/cc` namespace. So its initial value is set to `""` since there is no `default.cc` kv yet. During analysis r2 uses the actual value of `default.cc` kv.
This behaviour can confuse r2 user if a binary doesn't contain info about default CC.

## Test

```asm
$ radare2 --
[0x00000000]> k anal/cc/default.cc
amd64
[0x00000000]> e anal.cc

[0x00000000]>
```

**Comment by pelijah** [comment]
The same applies to `anal.syscc` variable.

**Comment by pelijah** [comment]
Idea of solution: implement getter callback for config variables.

**Comment by trufae** [comment]
So we need to use sdb hooks, to trigger a function when a specific key is touched.

https://github.com/radareorg/sdb/blob/a74da11b61ab585299d1b1594ff01618307a7c06/src/sdb.h#L359

**Comment by trufae** [comment]
Or we can have getters in rconfig too as you said :)

**Comment by trufae** [comment]
I fixed this using getters which is already supported by RConfig
