### ISSUE TITLE
Doesn't `af` in `on page 0xADDR`

### ISSUE THREAD

**Issue by s0i37** [radareorg/radare2#18099]
## Environment

```
Ср 23 дек 2020 14:02:52 +05
radare2 5.0.0 25286 @ linux-x86-64 git.
commit: 15d8de3819d25dd24575a520e19af908d2c18d16 build: 2020-12-22__21:06:21
Linux x86_64
```

## Description

I use r2 for analisys memory obtained from volatility (vaddump). I map all virtual memory successfully, however I can't create any functions:

`on memory_page.0x00010000-0x00010fff.dmp 0x00010000`

`af`

## Test

`r2 -a x86 -b 32 -`

`on somefile 0x00010000`

`af`

**Comment by trufae** [comment]
Add exec perms to the map

**Comment by s0i37** [comment]
`on somefile 0x00010000 r-x`
`af`
👍
