### ISSUE TITLE
Wrong tst opcode interpretation

### ISSUE THREAD

**Issue by LucCappellaro** [radareorg/radare2#18108]
Hello,

It seems that ARM32's [tst](https://developer.arm.com/documentation/dui0489/i/arm-and-thumb-instructions/tst) opcode is incorrectly interpreted.
The ESIL emulation and the pseudo code are wrong.
The screenshot is from cutter 0.12.0 but I have tested this in radare too.
Ida, Ghidra and QEMU do it differently/correctly.

I know that emulation is partial and imprecise, but you also say
"One of the most common usages of such emulation is to calculate indirect jumps and conditional jumps."
But if even this is not working, it's clearly a bug, or am I missing a thing?

![tst](https://user-images.githubusercontent.com/9829985/103132959-e9260d80-46a7-11eb-84bb-67d77d19bbc4.png)

**Comment by trufae** [comment]
The output you are showinf there is the pseudodisasm which have nothing to do with esil or capstone. The instruction tests the two values so it does == but its true that its not taking in consideration the size of the bytes to compare in the register so the and operation is not added ther. Can you provide a binary or the bytes of the instruction in order to reproduce it so i can fix?

if you are interested the related code lives in libr/parse/p/parse_arm.c

**Comment by eagleoflqj** [comment]
> The output you are showinf there is the pseudodisasm which have nothing to do with esil or capstone. The instruction tests the two values so it does == but its true that its not taking in consideration the size of the bytes to compare in the register so the and operation is not added ther. Can you provide a binary or the bytes of the instruction in order to reproduce it so i can fix?
> 
> if you are interested the related code lives in libr/parse/p/parse_arm.c

Esil is indeed wrong though. The link OP provides says `tst` uses `and` operation. It can be confirmed on rpi32.
```sh
pi@liumeo-rpi4:~$ cat a.c
int f(int x) {
	if(x & 15)
		return 0;
	return 1;
}
pi@liumeo-rpi4:~$ gcc -O3 -S a.c
pi@liumeo-rpi4:~$ cat a.s
	.arch armv6
	.eabi_attribute 28, 1
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 2
	.eabi_attribute 34, 1
	.eabi_attribute 18, 4
	.file	"a.c"
	.text
	.align	2
	.global	f
	.arch armv6
	.syntax unified
	.arm
	.fpu vfp
	.type	f, %function
f:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	tst	r0, #15
	moveq	r0, #1
	movne	r0, #0
	bx	lr
	.size	f, .-f
	.ident	"GCC: (Raspbian 8.3.0-6+rpi1) 8.3.0"
	.section	.note.GNU-stack,"",%progbits
```

**Comment by trufae** [comment]
This is the test script i wrote just for reference:

```
$ cat libr/anal/test.r2

e asm.arch=arm
e asm.bits=32
wx 050010e3 0100a003
pd 2
ao 2~esil
aei
ar r0=5
2aes
ar?r0
```

**Comment by trufae** [comment]
Fixed by @eagleoflqj !
