### ISSUE TITLE
Change R_API signature to use bool?

### ISSUE THREAD

**Issue by ratijas** [radareorg/radare2#18129]
## Environment

```sh
Tue Dec 29 01:16:56 AM MSK 2020
radare2 5.0.1-git 25519 @ linux-x86-64 git.5.0.0-50-g85cce84722
commit: 85cce84722708274fce5432174b3d9f2a64df76a build: 2020-12-29__00:14:46
Linux x86_64
```

## Description

There is a function in `cmd.c` declared with `R_API` macro. It's signature contains `int log`, but it should be bool instead. Two other functions in the same file, including one with `R_API`, use `bool log` for the same purpose. They even use C auto conversion to pass value around.

My question is: can we change such exported function?

```c
R_API int r_core_cmd(RCore *core, const char *cstr, int log) {...}
R_API int r_core_cmd_task_sync(RCore *core, const char *cmd, bool log) {...}
static RCmdStatus core_cmd_tsr2cmd(RCore *core, const char *cstr, bool split_lines, bool log) {...}
```

## Test

Needs integration testing only. Unit tests won't help much.

**Comment by trufae** [comment]
yes, make it bool
