### ISSUE TITLE
Missing Copyright and License

### ISSUE THREAD

**Issue by AndreRH** [radareorg/radare2#18121]
https://github.com/radareorg/radare2/blob/44755fe08d53b7426bbd33c2b5a0e0796d5cc343/libr/asm/arch/arm/winedbg/be_arm.c#L1

Hi guys,

Is there a specific reason that my Copyright and License notice is missing here?

**Comment by eagleoflqj** [comment]
Sorry about that. It was missing when the file was imported. Will add it soon.

**Comment by eagleoflqj** [comment]
Fixed via 531cfd252e076d47cf1a0f809e4ff8c635d772c5

**Comment by AndreRH** [comment]
Thank you!
