### ISSUE TITLE
ddd not working as expected

### ISSUE THREAD

**Issue by CryoCrunch** [radareorg/radare2#18138]
## Environment

```
Tue Dec 29 05:39:57 PM EST 2020
radare2 5.0.1-git 25416 @ linux-x86-64 git.5.0.0
commit: 97954c6ca4acc6f33227c160fc5eb2e72ba8fdf4 build: 2020-12-29__17:31:48
Linux x86_64
```

## Description
When opening the file using o <INPUTFILE> everything works fine
However using ddd to remap the fd of the file to something custom does not; Instead prints "dx HEX DUMP"
I would like to map a custom file from my working directory to file descriptor 393
The binary I'm working on is from pwn.college and it's named babyrev_level7_teaching1

I've also tried opening the file via dd <file> but this does not work either, giving me output like 'WARNING: No room in the static stackframe! (0 must be 6)'

Steps to reproduce:
1. Create a local file in the same directory as binary
2. r2 -d 'binary'
#INSIDE R2
3. aaa
4. o 'file'
5. ddd 4 393
#CHECK FD
6. dd
#UNCHANGED
7. o
#FD UNCHANGED

Note: This is my very first issue on github. I'm also very new to reversing. Please be gentle.

**Comment by Lazula** [comment]
`o` opens a new file in the r2 process. `dd <file>` opens the file in the child. `ddd` can then be used to remap file descriptors in the child process. `dd` commands will print an r2 command, so you can run them by prepending a `.`: `.dd file`. Regarding the error message, that problem has been fixed.
