### ISSUE TITLE
Fix all memleaks in test and enable memleak detection in ASAN

### ISSUE THREAD

**Issue by eagleoflqj** [radareorg/radare2#18150]
On Ubuntu 20.10 x64
```sh
sys/sanitize.sh
export ASAN_OPTIONS=detect_odr_violation=0
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.6
```
Then run tests. Memory leak everywhere.

**Comment by trufae** [comment]
uhm not sure if we really need to have an issue to track this

**Comment by eagleoflqj** [comment]
> uhm not sure if we really need to have an issue to track this

Maybe newcomers see and know where to start? I made my first pr after noticing how many LGTM alerts there were.

**Comment by trufae** [comment]
that could be

**Comment by eagleoflqj** [comment]
Feel free to close. I only remember tpi stuff result in terrible memleak.
