### ISSUE TITLE
rabin2.exe heap corruption error

### ISSUE THREAD

**Issue by thenesk** [radareorg/radare2#18161]
## Environment
radare2 5.0.0 0 @ windows-x86-64 git.5.0.0

## Description
Rabin2 on Windows crashes with certain arguments.  Debug builds trigger a "Microsoft Visual C++ Runtime Library" error dialog saying "HEAP CORRUPTION DETECTED".  

## Test
Examples that cause heap corruption:
```
rabin2.exe -g rabin2.exe
rabin2.exe -SSS rabin2.exe
rabin2.exe -S -SS rabin2.exe
```

**Comment by thenesk** [comment]
I think I have narrowed down the issue a bit, it has something to do with a string buffer in the function `bin_map_sections_to_segments` in the file `libr\core\cbin.c`.  Commenting out `free (json_output);` on line 2732 prevents the crash.

**Comment by eagleoflqj** [comment]
> I think I have narrowed down the issue a bit, it has something to do with a string buffer in the function `bin_map_sections_to_segments` in the file `libr\core\cbin.c`. Commenting out `free (json_output);` on line 2732 prevents the crash.

We refactored cbin.c recently and removed the variable json_output recently. Does this problem still exist in current master branch?

**Comment by thenesk** [comment]
I just tried now, but it looks like the master branch is not building on Windows

**Comment by trufae** [comment]
Its building fine in the fix-ci pr. I should finish this branch asap and merge

**Comment by trufae** [comment]
Please confirm the issue is still there by using the last windows builds (i dont have windows)

https://github.com/radareorg/radare2/actions/runs/482779363#artifacts

(see the installer.exe and the radare2-git.zip)

**Comment by thenesk** [comment]
The crash on Windows does not occur with the above build, thanks!

**Comment by trufae** [comment]
Thanks for confirming!
