### ISSUE TITLE
Projects don't load files correctly

### ISSUE THREAD

**Issue by ntegan** [radareorg/radare2#18191]
## Environment

```sh
$ r2 -v
radare2 5.0.1-git 25454 @ linux-x86-64 git.5.0.0
commit: 0fd95f1f676f1a4dbff774f9a71831f456f9cf14 build: 2021-01-09__12:43:53
$ uname -ms
Linux x86_64
```

## Description

File data in a project are replaced with all 0s after analyzing and saving project

Also in step 5 when running `aaaa`

```
WARNING: WARNING (canal.c:773):__core_anal_fcn: runtime check failed: (!core->anal->sdb_cc->path || fcn->cc)
```

sdb path is non-null but fcn->cc is null

## Test
1. r2 -  ,       Po test_proj
2. o a.exe
3. Ps
4. close radare then r2 -p test_proj. The a.exe will be loaded and visible.
5. run aaaa and Ps to save
6. Reopen project with r2 -p test_proj and now the file a.exe appears as all zeros

**Comment by ntegan** [comment]
```
[0x00011490]> o
 3 - r-x 0x00006760 ./phymem.sys
 4 - r-- 0x00000e00 null://3584
 5 - r-- 0x00000800 null://2048
 6 - rwx 0x00000a00 null://2560
 7 * rw- 0x000f0000 malloc://983040
```

Looks like this malloc mapping is added after step 5

**Comment by ntegan** [comment]
https://github.com/ntegan/r2_issue/commit/4f4536169b2bc69a0fe0ec8ec36b02a2408342a3

This is the difference in the project `rc.r2` that seems to be causing the issues. It is the resulting commit after saving the project for the second time

**Comment by ntegan** [comment]
https://github.com/ntegan/r2_issue/commit/4f4536169b2bc69a0fe0ec8ec36b02a2408342a3#diff-ff710b1ad2354182889e513459cbec7ee351ed58a4048795071993873187081dR600

this line in the project rc.r2 seems to be the issue

**Comment by trufae** [comment]
Please try this branch https://github.com/radareorg/radare2/pull/18193

would you like to add some tests?

**Comment by ntegan** [comment]
Do you mean create some tests like the checks in Github Actions?

I tried that branch  
```
$ r2 -v
radare2 5.0.1-git 25458 @ linux-x86-64 git.5.0.0
commit: c339616c07c6e3293668b454f9b7b6b09e98c872 build: 2021-01-09__14:56:33
```

It didn't fix my issue with the binary showing up as all `00`s after saving project with analysis.

Regarding the calling convention stuff, I now see these during `aaaa`

```
WARNING: WARNING (canal.c:770):__core_anal_fcn: runtime check failed: (fcn->cc)
Unknown calling convention
```

**Comment by ntegan** [comment]
If this is what you mean by test, to reproduce what I'm seeing you can

```bash
echo 'int main() {}' > a.c
gcc -o a.exe a.c
r2 -qq -c 'P- test; Po test; o ./a.exe; Ps' -
r2 -qq -p test -c 'aaaa' -
```

**Comment by ntegan** [comment]
To reproduce the zeroing out of the binary (from r2's view)

```bash
$ echo 'int main() {}' > a.c
$ gcc -o a.exe a.c
$ r2 -qq -c 'P- test; Po test; o ./a.exe; Ps' -

$ r2 -qq -p test -c 'px 4' -
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x000010c0  f30f 1efa                                ....

$ r2 -qq -p test -c 'aaaa; Ps' -
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
Unknown calling convention
WARNING: WARNING (canal.c:770):__core_anal_fcn: runtime check failed: (fcn->cc)
[master 224fcac] i
 1 file changed, 169 insertions(+), 18 deletions(-)

$ r2 -qq -p test -c 'px 4' -
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
afb+: Cannot add basic block at 0x00001078
afb+: Cannot add basic block at 0x000010b8
afb+: Cannot add basic block at 0x00001100
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x000010c0  0000 0000                                ....
```

**Comment by trufae** [comment]
The on is missing the base address because the map is not added later properly. In the project.c file you can find the code that generates this on line depending on some conditions.

About tests, see the test/db/cmd/cmd_projects

**Comment by ntegan** [comment]
I have a test  
https://github.com/ntegan/radare2/commit/4f476968bf931cef56eb427fe5e5d93ca5788a6c

that passes with `bins/elf/analysis/main` but not with a `echo 'int main() {}` > a.c; gcc a.c -o a.exe` `a.exe`

**Comment by ntegan** [comment]
Also, when adding a second test  
https://github.com/ntegan/radare2/commit/9ced6ffa017a9f0536b0e9ad0b54ef8a05ccdd44

that tests `bins/elf/analysis/main` in addition to the test added in my previous comment, there seems to be different output on running the tests multiple times

**Comment by ntegan** [comment]
Or you can ignore the above two messages and here's a test that fails with `bins/elf/analysis/a.out.cpp`

https://github.com/ntegan/radare2/commit/0c300de9c4cee7017d54e2ed5f63fc14fddc81d9

**Comment by trufae** [comment]
I did this PR to address the issue. didnt tested, but ill merge after the other pr gets green. https://github.com/radareorg/radare2/pull/18199

**Comment by ntegan** [comment]
That fixed my issue, thank you!

**Comment by trufae** [comment]
Thanks for confirming!
