### ISSUE TITLE
Seg fault on print meta data in visual disassembly

### ISSUE THREAD

**Issue by sjgallagher2** [radareorg/radare2#18202]
## Environment

```sh
Mon 11 Jan 2021 05:47:11 PM EST
radare2 5.0.1-git 25378 @ linux-x86-64 git.5.0.0
commit: f26a35a8dd50112c8467caa0e4ed9beaa2e79958 build: 2020-12-30__20:42:27
Linux x86_64
```

## Description

Setting display type metadata to 'data' for a section causes a segfault when scrolling up into it in visual disassembly. It should be able to show parts of the data section, letting you scroll through, but it pauses and faults out. Problem is disasm.c with ds_print_meta_infos(), case R_META_TYPE_DATA, where `hexlen` is set to be smaller than `delta`, then in the next line:
`r_print_hexdump (core->print, ds->at, buf+idx, hexlen-delta, 16, 1, 1);`
A negative length is passed in causing invalid memory access. A TODO is nearby to add checks for this but it has not been implemented as of 30 dec 2020 build.

## Test

Open a binary file (whose size is larger than 1 kB). Set the first 1000 bytes to data (`Cd 1000 @ 0x00`), go into visual disassembly mode, scroll down past the data section, then scroll back up, and a segmentation fault occurs.

**Comment by trufae** [comment]
Thanks for reporting that! i added a couple of tests and i know there are still some corners around Cd in disasm to support cursor and such, so feel free to report other related issues.
