### ISSUE TITLE
Error in "this shouldn't happen" test in similarity code

### ISSUE THREAD

**Issue by aamcintosh** [radareorg/radare2#18235]
## Environment

```sh
$ date
Fri Jan 15 11:35:03 EST 2021
$ r2 -v
radare2 4.5.1 6 @ linux-x86-64 git.4.5.1
commit: b148fa3e1cbf0d4e4d1d279af90e30520669e397 build: 2021-01-15__08:02:23
$ uname -ms
Linux x86_64

```

## Description

libr/anal/diff.c

This problem exists in the current version (as of a few minutes ago) as well as the version I am running.  It's a problem with some "this can't happen" code, so I can't set up something that actually triggers it.

Line 189 in `r_anal_diff_fcn()`:
```
        if (fcn->name && fcn2->name && strcmp (fcn->name, fcn2->name)) {
           continue;
       }
```
If `fcn->name` is `NULL` and `fcn2->name` is not `NULL,` (or vice versa) this test fails and control falls into the code
that checks functions with equal names.  This is wrong.
Suggested fix:
```
        if (!fcn->name || !fcn2->name || strcmp (fcn->name, fcn2->name)) {
           continue;
       }
```
This keeps the guard on `strcmp().`  It does mean that two functions with empty names will never compare as equal, but that's reasonable anyway.

## Test

I wish I could give you an example, but the test should never fail this way.  Fortunately it's easy to see the error.

**Comment by trufae** [comment]
This is fixed now. Thanks!
