### ISSUE TITLE
Graphviz output rendered incorrectly

### ISSUE THREAD

**Issue by aamcintosh** [radareorg/radare2#18264]
## Environment

```sh
$ date
Wed 20 Jan 2021 11:51:39 PM EST
$ r2 -v
radare2 4.5.1 9 @ linux-x86-64 git.4.5.1
commit: 613af284cebb633d0c5fc2e674b993e4b6c89eca build: 2021-01-15__19:42:46
    (my commit not yours)
$ uname -ms
Linux x86_64
$ uname -v
#43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021
    (Ubuntu 20.04)
$ dpkg-query -l | grep xdot
ii  xdot 1.1-2
dpkg-query -l | grep graphviz
ii  graphviz 2.42.2-3build2
```

## Description

This really isn't a bug in `radiff2`, but it's one of those "the example didn't work" things.  There is a small documentation issued contained herein.

When I try to use `radiff2` to generate output that I feed to `xdot`, I get mangled output.

## Test

Run the example described in the blog page on binary-diffing:
```
radiff2 -g main -m d /bin/true /bin/false | xdot -
```
(Note that the -m is required.  This is not documented in the blog page on binary-diffing.)
A small chunk of the output looks something like this:
![badfont](https://user-images.githubusercontent.com/6467050/105425004-782a3500-5c16-11eb-90ec-1f72cc79ca7c.png) The 4 digit characters in the boxes are right ASCII single byte values, but they are not being rendered properly.  An overkill fix is to make the font selection go away:
```
radiff2 -g main -m d /bin/true /bin/false | sed 's/ fontname="Courier"//' | xdot -
```
Another approach is to give up on xdot completely.  The output renders fine using something like
```
radiff2 -g main -m d /bin/true /bin/false | dot -Tpdf > foo.pdf
okular foo.pdf
```
If others have been bitten by this it might help to update the blog with this workaround.

**Comment by trufae** [comment]
thanks! this is reproducible in master. im fixing it right now!

**Comment by trufae** [comment]
-m is not necessary, but the default output will print nothing if both functions are the same. you can use -e graph.font to select the font to use
