### ISSUE TITLE
xdot generates bogus error message

### ISSUE THREAD

**Issue by aamcintosh** [radareorg/radare2#18266]
## Environment

```sh
$ date
Thu 21 Jan 2021 07:10:02 PM EST
$ r2 -v
radare2 4.5.1 9 @ linux-x86-64 git.4.5.1
commit: 613af284cebb633d0c5fc2e674b993e4b6c89eca build: 2021-01-15__19:42:46
    (my commit not yours)
$ uname -ms
Linux x86_64
$ uname -v
#43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021
    (Ubuntu 20.04)
$ dpkg-query -l | grep xdot
ii  xdot 1.1-2
dpkg-query -l | grep graphviz
ii  graphviz 2.42.2-3build2
```

## Description

`xdot` throws errors when given `radiff2` output containing strings with backslashes.  The problem is apparently with the `xdot` back end of `dot`.  The problem is discussed [here](https://gitlab.com/graphviz/graphviz/-/issues/165).  It looks like it has been fixed, but only recently.

## Test

Compile the following as `hello2.c`:
```
#include <stdio.h>
int main(int argc, char **argv) {
	printf("\"Hello world\"\n"); return 0;
}
```
```
gcc -o hello2 hello2.c
radiff2 -g main -m d hello2 hello2 | xdot -
```
The error message is
```
24:107:unexpected char b'\\'
```
This works fine when the output of `radiff2` is fed directly to `dot`:
```
radiff2 -g main -m d hello2 hello2 | dot -Tpdf > hello2.pdf
okular hello2.pdf
```

**Comment by aamcintosh** [comment]
Someone with the right permissions should mark this "fix upstream" and maybe just close it.

**Comment by trufae** [comment]
Will fix today

**Comment by trufae** [comment]
Nvm, there's no such issue in master. Please dont report issues on old versions of r2 without testing in master

**Comment by trufae** [comment]
```
[0x100003f50]> agdd
digraph code {
	graph [bgcolor=azure fontsize=8 fontname="Courier" splines="ortho"];
	node [fillcolor=gray style=filled shape=box];
	edge [arrowhead="normal"];
 "0x100003f50" [fillcolor="lightgray",color="black", fontname="Courier", label="     ; [00] -r-x section size 49 named 0.__TEXT.__text\l       ;-- main, section.0.__TEXT.__text, sym._main, sym.func.100003f50, rip:\l49: entry0 (int64_t arg1, int64_t arg2);\l     ; var int64_t var_14h @ rbp-0x14\l     ; var int64_t var_10h @ rbp-0x10\l     ; var int64_t var_8h @ rbp-0x8\l     ; var int64_t var_4h @ rbp-0x4\l     ; arg int64_t arg1 @ rdi\l     ; arg int64_t arg2 @ rsi\l     push rbp\l     mov rbp, rsp\l     sub rsp, 0x20\l     mov dword [var_4h], 0\l     ; arg1\l     mov dword [var_8h], edi\l     ; arg2\l     mov qword [var_10h], rsi\l     ; const char *format\l     ; section.3.__TEXT.__cstring\l     ; 0x100003fa2\l     ; \"\\\"Hello world\\\"\\n\"\l     lea rdi, str._Hello_world__n\l     mov al, 0\l     ; int printf(const char *format)\l     call sym.imp.printf\l     xor ecx, ecx\l     mov dword [var_14h], eax\l     mov eax, ecx\l     add rsp, 0x20\l     pop rbp\l     ret\l", URL="entry0/0x100003f50"]
}
[0x100003f50]> agdd > a.dot
[0x100003f50]>
zsh: suspended  r2 a.out
$ dot -Tpng < a.dot > a.png
$
```
![a](https://user-images.githubusercontent.com/6431515/105639343-12d57e80-5e78-11eb-9471-81a6cddd606a.png)

**Comment by trufae** [comment]
Also confirmed pdf, and png and standard graph as well as diffing graph, all of them work well with this, if you can still repro the issue in master please provide a test that we can run in test/db/ for better reproducibility

**Comment by aamcintosh** [comment]
I think misunderstood the problem.  The issue exists in `dot`.  Using anything but `xdot`, such as `dot` to pdf or png works fine for me also.  `xdot` calls `dot -Txdot` and **that's** where the problem lies.  There is nothing wrong with `radare2`.  The code emitted by
```
radiff2 -g main -m d hello2 hello2 | dot -Txdot
```
is bad, _depending on what version of `dot` (from `graphviz`) you have_.  In my case, with `graphviz` 2.43, I get the following for output:
```
_ldraw_="
    (stuff with no double quotes omitted)
\"\\"Hello world\\"\"
   (more stuff with no double quotes)
ret ",
color=black,
    (and so on)
```
The double quote before `Hello` closes the string (because there should be three backslashes ahead of it, not two), and the following double backslash is an error.

My point was that the example appears not to work.  It's not the fault of `radare2`, but it can look that way, especially if one notices that other invocations of `dot` work fine.

I don't mind upgrading `radare2`, but I can't get away with replacing the world, and that includes `graphviz`.  2.43 is what comes with Ubuntu 20.04 so that's what I'm stuck with.
