### ISSUE TITLE
Possibly unnecessary confusion over stripped binary

### ISSUE THREAD

**Issue by aamcintosh** [radareorg/radare2#18260]
## Environment

```sh
$ date
Wed 20 Jan 2021 11:51:39 PM EST
$ r2 -v
radare2 4.5.1 9 @ linux-x86-64 git.4.5.1
commit: 613af284cebb633d0c5fc2e674b993e4b6c89eca build: 2021-01-15__19:42:46
  (My commit, not yours)
$ uname -ms
Linux x86_64
```

## Description

`Radiff2` seems to be unnecessarily confused by a stripped binary.  I know it's not easy, and I don't expect perfection, but this one seems a little strange.  `Radiff2` matches up a function in a stripped binary with its unstripped counterpart, but the similarity index it computes is nowhere near 1.

## Test

contents of hello.c:
```
#include <stdio.h>
int main(int argc, char **argv) {
	printf("Hello world\n"); return 0;
}
```
Run
```
clang -v
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
  (output omitted)
clang -c hello.c
clang -o hello-notstripped hello.c
cp hello-notstripped hello-stripped
strip hello-stripped
radiff2 -q -O -A -A -C hello-notstripped hello-stripped
```
Objdump output from the unstripped file attached: [objdump.txt](https://github.com/radareorg/radare2/files/5847017/objdump.txt) The line of interest in the radiff2 output is the following:
```
sym.__libc_csu_init 101 0x401170 |   MATCH  (0.702970) | 0x401170  101 fcn.00401170
```
A little poking around shows that in computing the function similarity the BBs in the unstripped file are traversed in the order 0x401170, 0x4011a7, 0x4011b0, 0x4011c6 while those in the stripped file are traversed in the order 0x401170, 0x4011c6, 0x4011a7, 0x4011b0.  (Without the second -A radiff2 does not find the function in the stripped binary.)

Why the difference in the traversal order?  Both are plausible.  I doubt there are any global constructors, so it is unlikely that the two BBs in the middle will execute at all.  While flowgraph isomorphism is hard in general, some consistency would improve the similarity score and make it harder to fool `radiff2`.  In particular, straight up comparison of the code of the two functions would give a better answer.

**Comment by trufae** [comment]
I see no reason for this order change to happen, bbs should be sorted by offset before processing. As long as you dig into that Would you like to submit a fix?
