### ISSUE TITLE
Change "aflj" behavior for file with no functions

### ISSUE THREAD

**Issue by CTSinon** [radareorg/radare2#18284]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
Mon Jan 25 17:24:29 CST 2021
radare2 5.0.1-git 25565 @ linux-x86-64 git.5.0.0
commit: bdbcc780310e74b319c3fffc46706d86b9c1dab1 build: 2021-01-21__19:08:06
Linux x86_64
```

## Description

When using r2pipe to analyze a file with no functions, the "aflj" command would return an empty string instead of "{}", thus causing an exception in json.load method.

**Comment by mrglm** [comment]
JSON command are indeed supposed to yield valid JSON. I suspect that it is not the only place where this behavior happens. I will look into this in order to fix it. Could you produce an example of a file with no function for testing purpose?

**Comment by CTSinon** [comment]
> JSON command are indeed supposed to yield valid JSON. I suspect that it is not the only place where this behavior happens. I will look into this in order to fix it. Could you produce an example of a file with no function for testing purpose?

Ok, how about this one 

[no_func.zip](https://github.com/radareorg/radare2/files/6099323/no_func.zip)
