### ISSUE TITLE
POLL: Vdn vs Vdr

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#18292]
## Description

in visual mode, pressing dn to rename a function doesnt work and pressing dr seems confusing because 'r' is about rename but "define rename" doesnt make sense.

So imho Vdn should do what Vdr does right now, but also handle flags.

Vdr can be changed to define registers or keep it for compat for some time before removal

**Comment by condret** [comment]
Maybe we need to rethink the whole Vd-command. To me d stands for debugging in r2 ... so shouldn't Vd as well?

**Comment by trufae** [comment]
yeah but thats visual, not console.. how would you reorganize the visual flags? which changes would you do?

**Comment by condret** [comment]
If I start thinking about this, I'd change a lots of visual commands.
visual flags : Vf
