### ISSUE TITLE
Typo in sys/debian.sh

### ISSUE THREAD

**Issue by gordboy** [radareorg/radare2#18293]
The line in `sys/debian.sh`

`export CFLAGS="${CFLAGS} -Wno-stringpop-truncation"`

contains a typo which totally breaks things. It should probably read

`export CFLAGS="${CFLAGS} -Wno-stringop-truncation"`

which leads to an actual completed build.

**Comment by trufae** [comment]
The script is running in the ci and it works fine. Can you submit a pr fixing this line? It can be done via web by pressing the pencil button in the filebrowser of github.

Thanks!

**Comment by gordboy** [comment]
Made a pull request, as asked.
