### ISSUE TITLE
Support heap-located RIOPlugins

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#18305]
This relates to https://github.com/radareorg/radare2-rlang/issues/25 .
Problem is that RIOPlugin->open needs to use global-scope in order to access the python objects.
I'd like to fix this by extending RIOPlugin in radare2-rlang and use container_of.
Even then the python wrapper still needs to use global space, to access the plugin-struct itself.
Fix for that would be changing RIOPlugin->open(io, uri, perm, mode) to RIOPlugin->open(io, plugin, url, perm, mode)

**Comment by trufae** [comment]
This is already done and possible, theres no need to modify the api imho. adding one more argument to the open callbacks and check ones makes no sense, the plugin itself knows which is its own plugin, and this is binded into the riodesc
