### ISSUE TITLE
aa ignores anal.calls

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#18323]
tried today on master

**Comment by trufae** [comment]
Can you provide the binary you are testing? i have a fix but i would like to have a test too

**Comment by trufae** [comment]
nvm :D i found the perfect sample
![Screenshot 2021-02-01 at 23 27 17](https://user-images.githubusercontent.com/6431515/106525929-0e970a00-64e5-11eb-818a-900aa7ee44de.png)

**Comment by condret** [comment]
nope, I cannot share this file
