### ISSUE TITLE
Sort Improvements

### ISSUE THREAD

**Issue by aamcintosh** [radareorg/radare2#18322]
## Description

`r_list_sort()` is not optimal.  It "wisely" picks insertion sort if the list is small, and chooses `r_list_merge_sort()` otherwise.  However, once it has settled on merge sort it stays stuck there even when the lists become small.  This might be reasonable behavior when `r_list_merge_sort()` is called externally (so the caller is presumably forcing use of merge sort) but it's not reasonable when the caller is asking that the best algorithm be used.

A fix could add some redundant code (I don't like this idea) or pass a flag to `_merge_sort()` - call it `force_merge_sort` or something.  Some list length bookkeeping would also be required, which may make this impractical.

**Comment by trufae** [comment]
It's already doing this

**Comment by trufae** [comment]
ftr in sdb:

```c
117 SDB_API bool ls_sort(SdbList *list, SdbListComparator cmp) {
118         if (!cmp || list->cmp == cmp) {
119                 return false;
120         }
121         if (list->length > 43) {
122                 ls_merge_sort (list, cmp);
123         } else {
124                 ls_insertion_sort (list, cmp);
125         }
126         list->cmp = cmp;
127         list->sorted = true;
128         return true;
129 }
```

in r2:

```c
571 //chose wisely based on length
572 R_API void r_list_sort(RList *list, RListComparator cmp) {
573         r_return_if_fail (list);
574         if (list->length > 43) {
575                 r_list_merge_sort (list, cmp);
576         } else {
577                 r_list_insertion_sort (list, cmp);
578         }
579 }

**Comment by trufae** [comment]
The magic 43 comes after the results in benchmarks

**Comment by aamcintosh** [comment]
I certainly saw that code.  I wrote "It "wisely" picks insertion sort if the list is small, and chooses `r_list_merge_sort()` otherwise."  43 sounds about right for the decision point.  That's not where the problem lies.

Consider what happens if `r_list_sort()` is called with a list of size 50.  It calls `r_list_merge_sort()`.  `r_list_merge_sort()` calls `_merge_sort()`, which splits the list in half, _and unconditionally recurses on the two halves, length 25._  `_merge_sort()` takes each list of length 25 and merge sorts each.  It splits the lists in half (producing lists of length 12 and 13) and recurses on each.  `_merge_sort()`  gets called on lists of length 6 when these are split.  The lists of length 6 are split into lists of length 3 and so on.  My point is that once control gets into `_merge_sort()` insertion sort is never called on a small list.  Calling `_merge_sort()` on lists that are this small may not be such a good idea.  If it's not optimal initially, it probably won't be optimal at some intermediate stage either.

I think it would be interesting to see how this revised strategy benchmarks against a pure merge sort.

Quicksort routines usually follow this strategy.  Any initial object and any sublist smaller than some threshold are sorted by some means other than quicksort (often insertion sort).  Quicksort has the advantage that the insertion sort can easily be done as a single step at the end (the partitioning guarantees locality) but the principle is the same.

**Comment by aamcintosh** [comment]
I can put it on my "to-do" list.  I'd be doing it on my own time, so it's not going to be high priority.

You say there were benchmarks done.  Is the code around?  (I haven't poked around the test suite yet.)

**Comment by trufae** [comment]
I have implemented this logic in sdb's ls, but benchmark are not really good unless i'm missing something:

```
  1 nosort = 3
  2 stdsort = 11
  3 fastsort = 12
```

See https://github.com/radareorg/sdb/pull/239
