### ISSUE TITLE
Potential Memory Leak in radiff2

### ISSUE THREAD

**Issue by aamcintosh** [radareorg/radare2#18331]
## Environment

```sh
$ date
Wed 03 Feb 2021 07:48:55 PM EST
$ r2 -v
radare2 4.5.1 13 @ linux-x86-64 git.4.5.1
commit: 06b6696298531a43301c56df00dd9c2805732b50 build: 2021-01-26__23:32:14
$ uname -ms
Linux x86_64
```

## Description
`r_anal_diff_fcn()` frees up fingerprints in functions it matches.  It does not free up fingerprints in unmatched functions (ones that would be labeled `NEW` under the `-C` option).  This memory does get freed when the `RAnalFunction` object that owns it is freed.  This means that subsequent use of this field (after `r_anal_diff_fcn()` has been called but before the `RAnalFunction` object is freed) must check for non-null values and free them before re-using the field.  Unsuspecting code that assumes that the fingerprint is always freed will leak memory.  I suspect that there is a similar problem with `r_anal_diff_bb()`.

This isn't a big deal and my use this way is non-standard.  Maybe the code should be left as-is.  A fix would loop over all functions and bbs, which could be excessive churn.

## Test

Run `radiff2 -C` on two small binaries where at least one function doesn't match.  Add a conditional breakpoint in `r_anal_function_free()` that trips when `fcn->fingerprint` is non-null.

**Comment by trufae** [comment]
Can you submit a PR with this fix?

**Comment by trufae** [comment]
Also we dont fix bugs in old versions of r2, is the bug still happening in master?

**Comment by trufae** [comment]
ping?

**Comment by trufae** [comment]
fcn->fingerprint is freed in master, closing as no feedback for long time
