### ISSUE TITLE
`sys/user.sh --install-path` fails when given a relative path

### ISSUE THREAD

**Issue by Pamplemousse** [radareorg/radare2#18360]
I tried to install `radare2` using the `sys/user.sh` script, with a custom `--install-path <my path>`, and it kept failing with a `gcc: error <my path>/lib: No such file or directory`.

After a bit of debugging, it became apparent that `--install-path` works only when providing a **absolute path**.
In particular, here is the reconstituted "stack trace" leading to what seems to be the cause of the error.
  * `./sys/build.sh "${ROOT}" && ${MAKE} symstall` in [sys/user.sh](https://github.com/radareorg/radare2/blob/9398ce4eb7bcf2e30482d8fb37ca5b7d68efdbb7/sys/user.sh#L73)
  * `${MAKE} -s -j${MAKE_JOBS} MAKE_JOBS=${MAKE_JOBS} || exit 1` in [sys/build.sh](https://github.com/radareorg/radare2/blob/9398ce4eb7bcf2e30482d8fb37ca5b7d68efdbb7/sys/build.sh#L140)
  * `${MAKE} -C libr/util` in [Makefile](https://github.com/radareorg/radare2/blob/master/Makefile#L52)
  * `include ../rules.mk` in [libr/util/Makefile](https://github.com/radareorg/radare2/blob/9398ce4eb7bcf2e30482d8fb37ca5b7d68efdbb7/libr/util/Makefile#L72)
  * `LINK+=-Wl,-rpath "${LIBDIR}"` in [libr/rules.mk](https://github.com/radareorg/radare2/blob/9398ce4eb7bcf2e30482d8fb37ca5b7d68efdbb7/libr/rules.mk#L37)

IMHO, if relative paths are too complicated to implement, `sys/user.sh` could at least check that an absolute one is given, and warn the user with a more explicit message about what the issue is.

**Comment by trufae** [comment]
Fixed in the pr
