### ISSUE TITLE
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)

### ISSUE THREAD

**Issue by Syuukakou** [radareorg/radare2#18370]
## Environment

```sh
Wed 17 Feb 2021 06:17:12 PM JST
radare2 4.2.1 0 @ linux-x86-64 git.4.2.1 commit: unknown build:
Python 3.8.5
r2pipe==1.5.3
Linux x86_64 (VMware Workstation 15 Pro 15.5.6 build-16341506  Memory: 4GB, Processors: 2)
```

## Description

I used the `r2pipe.cmdj(aaij)` in python to extract 56800 files' `aai` info. And used `r2.quit()` to quit.
I don't know why, but the blow error(warning) occurred, and the python script is stopped when the 411th file is processed.
I think it is a file I/O error, but I have used `r2pipe.quit()`. Can anyone help me or give me some tips? 
Thank you!! 
## Code
                r2 = r2pipe.open(filepath)
                r2.cmd("aaa")
                # using json.loads to convert strin dict to dict
                result = r2.cmdj("aaij")
                temp["percent"] = result["percent"]
                code_covrage[basename] = result["percent"]

                #using pwntools to identify packer
                if basename in packed_list:
                    temp["is_packed"] = True
                else:
                    temp["is_packed"] = False
                
                # {basename: {"percent":"", "is_packed":""}}
                hash_packed_covrage[basename] = temp
                print(basename, " percent: ", temp["percent"], " is_packed: ", temp["is_packed"])
                r2.quit() 

## Error 
88db2995e5fa95696f432a0188b685c7  percent:  86  is_packed:  False
407
ed85d9d169731a81402270a8782cee41  percent:  46  is_packed:  False
408
73f8be03a44a6205d162460a50f5e1c6  percent:  11  is_packed:  False
409
51cc6a8e80ff26c1306ec8ee7bbe3017
0fd9966331ac660ab9e642791fbb3934
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: r_io_read_at: assertion 'io && buf && len >= 0' failed (line 282)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)
WARNING: try_get_cmpval_from_parents: assertion 'fcn && fcn->bbs && cmp_reg' failed (line 292)

(the python script is stopped)

**Comment by trufae** [comment]
4.2.1 is very old. Please confirm the issue is still hapening in latest release

**Comment by Syuukakou** [comment]
Thank you for your reply!!!  :blush:
I have updated the radare2 version to 5.1.1. 
```
date: Wed 17 Feb 2021 11:46:17 PM PST
r2 -v: radare2 5.1.1 25832 @ linux-x86-64 git.5.1.1 commit: 4c8f20309d19a7fb233a94ef0dee289b26750484 build: 2021-02-17__21:32:30
uname -ms: Linux x86_64
```
But a new warning occurred when the 213th file was processed. :disappointed: Similarly, the script was stopped.

![image](https://user-images.githubusercontent.com/32434879/108323813-74380580-720a-11eb-863e-aa9c5e399338.png)

**Comment by Syuukakou** [comment]
I used `r2 -A -qc a <file>` to extract info successfully. This issue can be closed.
