### ISSUE TITLE
newline inserting

### ISSUE THREAD

**Issue by jstaursky** [radareorg/radare2#18376]
How do I insert a newline between outputs? for example I will run
``pd -2 @@=`/x c3~[0]` ``
To 1st search for `c3` bytes and then disassemble 2 instructions backwards from each of the resulting addresses.

But with how things currently output, its very difficult to discern which 2 instructions are before which c3 address.

**Comment by trufae** [comment]
You can use an anonymous macro:

```
(;pd-2;?e)()@@=`...
```

**Comment by trufae** [comment]
As long as its a common pattern and its a bit anoying to type the macro syntax i added this https://github.com/radareorg/radare2/pull/18378
