### ISSUE TITLE
Symbolic Representation of e/rflags

### ISSUE THREAD

**Issue by rgnkn** [radareorg/radare2#18418]
If I don't remember wrong earlier versions of radare2 displayed the content of the e/rflags in the Debug View (V -> pp) in a symbolic manner (e.g.: something like "ZP" if Zero and Parity Flag have been set). Now it only shows the content as a hex value.

I'm well aware of "dr 1", so technically it's not necessary, but for didactic reasons I'd prefer to have the symbolic representation straight on the Debug View Interface. After fruitlessly playing around for quite some time with configuration variables I'd like to ask you if it is possible to return to the old style and how to do this? Is there a configuration variable I missed to rules this behaviour?

Thx in advance: for your help and for radare2 itself.

**Comment by trufae** [comment]
Totally agree, the default visual mode for the debugger shuold be improved. And this one is actually one of the important ones. thanks for the heads up

**Comment by trufae** [comment]
You can add a panel or visual command to run the `drc` command

**Comment by trufae** [comment]
Fixed in master, its calling drcq
