### ISSUE TITLE
Order section name/symbol comments so section names have priority.

### ISSUE THREAD

**Issue by roboman2444** [radareorg/radare2#18427]
## Description

Symbol name comments should appear after section name comments.

![2021-03-09-121127_303x168_scrot](https://user-images.githubusercontent.com/3598431/110509951-ada8b600-80d0-11eb-9e86-c347d5368d30.png)

";-- str.string_A:" should come after ";-- .rodata:"

The XREF comments should also probably come after the section name comments too.

**Comment by trufae** [comment]
Good point :) ill take care of this
