### ISSUE TITLE
Infosystem on Machine Instructions (~ CutterRef within terminal)

### ISSUE THREAD

**Issue by rgnkn** [radareorg/radare2#18426]
I don't know if I'm the only one using radare2 for tuition (Assembler, Compiler Construction, Optimization, RevEng, etc.), but given that there are others too, I think it might be interesting to have a search function on Machine Instructions, just like CutterRef (https://github.com/yossizap/cutterref), but within terminal radare2 itself.

If this isn't accepted as a builtin feature I foresee implementing a r2 plugin using 'pM' (~ print Mnemonic (Info)) by 'porting' CutterRef to terminal, but this won't happen before next month and I haven't been into r2 plugin development yet.

Comments on this idea and on the suggested command are welcome.

Here some ideas for this feature:

- 'pM.' Info on instruction at seek
- 'pM [addr]' Info on instruction at [addr]
- 'pMs [ins] [arch]' Searching info on instruction [ins] for [arch]

**Comment by trufae** [comment]
I have reimplemented cutterref in shellscript. you can install it like this: `r2pm -ci iref` check this video to see how to use it https://youtu.be/jne9e_kBS8E
