### ISSUE TITLE
Immediaetly quitting Visual Mode

### ISSUE THREAD

**Issue by rgnkn** [radareorg/radare2#18421]
This is a simple feature request with regards to Visual Mode quitting (pure usability).

If I entered any Visual Mode (e.g. 'V!')  other than the HexView I need to type 'q' twice in order to return to the main radare2 prompt - the first 'q' returns to the HexView, the second to the prompt. I'd like to ask whether it might be possible to stop this annoying behaviour. 

Suggestion: maybe optionally by introducing a new configuration variable in order to control the quitting, luxury version would be some kind of View Stack in order to pop to last view ['q' after 'V!" would return to prompt / 'q' after 'V' -> 'V' would return to HexView]).

As mentioned, I'm well aware that this feature request has no urgency what so ever and that it is most likely quite subjective.

**Comment by trufae** [comment]
This behaviour is expected and correct. You are entering the panels mode via the visual mode. This means that you have to press q twice to quit that mode.

To enter the panels mode directly just use the lowercase `v`

**Comment by trufae** [comment]
The chars passed after the V command are feeded to the stdin reader of visual mode. So, typing V! in the shell is the same as typing V and then pressing !

**Comment by rgnkn** [comment]
Thx alot.

As mentioned in my earlier post, I know that this request isn't important and that it is controversial, it only runs a bit against my workflow.

Explanation: In my courses I generally run radare2 in prompt mode (if I don't use it through r2pipe in ipython) and - for example - I use 'VV' as a quite frequently used shortcut for 'agfv'. as there is no 'vV' to enter graph mode in order to jump back directly. Very strange workflow as a result of my laziness to type and to remember too many prompt commands I guess.

I shall close this.issue.

**Comment by rgnkn** [comment]
Btw.: Again no issue, off topic and I don't expect anyone to answer as I already closed this issue.

Is there anything like CutterRef (https://github.com/yossizap/cutterref) for usage within radare2?

**Comment by trufae** [comment]
Can you open a separate issue for this cutterref thing? thanks! No, there's no such thing for r2, but would be doable to support a generic interface for accessing arch specific information inside r2. Actually there's a wip project for svd integration which may be also extended with those details and should be easily integrated as a plugin and displayed in panels or in r2cutter, there's no need to have a cutter plugin for this, having the feature in r2 will make that available directly into r2cutter,

Thanks for asking!
