### ISSUE TITLE
Annotated hexdump panel movement in visual mode

### ISSUE THREAD

**Issue by jstaursky** [radareorg/radare2#18443]
## Description

*Please describe what are you missing or wanting to be improved*
it looks like the latest release has moved the Annotated hexdump panel from atop the disassembly view.

*Provide images, ascii-art, test files and anything that may help us understand your request*
how can I put it back? can this be made an option?

**Comment by jstaursky** [comment]
actually this only occurs when using r2ghidra. is that normal behavior?

**Comment by trufae** [comment]
I dont understand the explanation. Can you provide a screenshot or more details?

**Comment by jstaursky** [comment]
even better I've attached a gif

![hex-annot](https://user-images.githubusercontent.com/25406664/111005865-a0eac300-8359-11eb-81af-7929c475900d.gif)

**Comment by trufae** [comment]
I guess the question you mean is why disassembling with r2ghidra in the emulation  visual mode shows so many registers that lefts no room for the disasm?

**Comment by jstaursky** [comment]
close. But its not just that theres no room, but that there is no disassembly even when you try and scroll down w/ r2ghidra. Regardless, why is the behavior different?

**Comment by trufae** [comment]
The disasm is below the registers. Make the terminal bigger or change the register list wider. The behaviour is different because r2ghidra is generating the regprofile in a wrong way so it shows all registers instead of just the gpr ones. Probably because it lacks this info or so. I will look into that and i have already fixed an issue yesterday in r2ghidra about regprofiles.

**Comment by jstaursky** [comment]
Ah I see it now, my laptop screen just was not big enough.

**Comment by trufae** [comment]
I have tweaked the way r2ghidra generates the regprofile for r2. please update the plugin and try again

**Comment by condret** [comment]
have you tried zooming out?

**Comment by jstaursky** [comment]
@trufae that fixed it. Thank you.

**Comment by jstaursky** [comment]
Actuallyyy, I checked for x86 and it appeared to work but I just tried RISCV and now I have
![image](https://user-images.githubusercontent.com/25406664/111228575-d215fe00-85ba-11eb-931b-6195c093bbd5.png)

and now I run into an issue where RISCV freezes

https://user-images.githubusercontent.com/25406664/111229353-22419000-85bc-11eb-99c8-a0f0298bf3f8.mp4

**Comment by jstaursky** [comment]
[hello.zip](https://github.com/radareorg/radare2/files/6144893/hello.zip)
I have added the riscv binary

**Comment by jstaursky** [comment]
Interestingly if I run it as `r2 -a r2ghidra -e asm.cpu=riscv hello`
I do not have the freeze, however the original issue persists and now watch what happens on zooming out.

https://user-images.githubusercontent.com/25406664/111230525-1fe03580-85be-11eb-8464-a9591a678ce1.mp4

**Comment by trufae** [comment]
Type `aeim` if you want to initialize the stack for emulation

**Comment by jstaursky** [comment]
ah nvm I realized my last post was non-sense (the x-register are named differently in their standardized ABI form). Thanks for not closing anyway, but I see where I was being stupid now.
