### ISSUE TITLE
Implement r_io_submap_set_from and r_io_submap_set_to (siol eternal)

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#18476]
### Motivation
When inserting new submaps into a RIOBank, adjusting the boundaries of existing submaps is necessary, to ensure that submaps don't intersect.

### Task
Implement r_io_submap_set_from and r_io_submap_set_to in libr/io/io_submap.c on siol_eternal branch:
```
R_API bool r_io_submap_set_from(RIOSubmap *sm, const ut64 from);
R_API bool r_io_submap_set_to(RIOSubmap *sm, const ut64 to);
```
Both functions shall return false, if sm is NULL or changing boundaries would result in negative interval size.
Else return true

**Comment by arvindmuralie77** [comment]
@condret , do the functions also have to change the values of `sm->itv.addr` and `sm->itv.size`?

**Comment by condret** [comment]
@arvindmuralie77  yes, sorry I didn't see your comment until now, I just implemented them
