### ISSUE TITLE
Segfault when changing graph mode

### ISSUE THREAD

**Issue by rhythmize** [radareorg/radare2#18493]
## Environment

```
Thursday 18 March 2021 04:33:14 PM EET
radare2 5.2.0-git 26081 @ linux-x86-64 git.5.1.1
commit: 990d6c9855768bbc18471b1ab909d644080c7446 build: 2021-03-18__13:03:08
Linux x86_64
```

## Description
In visual mode, when I try to change the graph mode radare2 segfaults. 

My assumption (Not entirely sure):
The error seems to be originating from [here](https://github.com/radareorg/radare2/blob/master/libr/core/agraph.c#L3903).
It looks like `g->back_edges` is pointing to some garbage address leading to the segfault. 

## Test
Steps to reproduce:
1. Open any binary in analysis mode
```
radare2 -AAAA binary
```
2. Enter graph mode by pressing 'v' key twice.
3. Press 'p' key to change graph mode.

**Comment by trufae** [comment]
i can repro and i this reminds me not to sync crap again. thanks for the heads up, reverting the commit

**Comment by trufae** [comment]
Fixed in master
