### ISSUE TITLE
libr/socket/run.c sets incorrect function pointer

### ISSUE THREAD

**Issue by intruder-kat** [radareorg/radare2#18501]
Freshly cloned from https://github.com/radareorg/radare2

The following code in `libr/socket/run.c` is supposed to set up the `dyn_openpty`, `dyn_login_tty`, and `dyn_forkpty` function pointers. No other assignments to `dyn_login_tty` or `dyn_forkpty` exist, this is the only place that sets them.
```c
#if HAVE_PTY
static int (*dyn_openpty)(int *amaster, int *aslave, char *name, struct termios *termp, struct winsize *winp) = NULL;
static int (*dyn_login_tty)(int fd) = NULL;
static id_t (*dyn_forkpty)(int *amaster, char *name, struct termios *termp, struct winsize *winp) = NULL;
static void dyn_init(void) {
	if (!dyn_openpty) {
		dyn_openpty = r_lib_dl_sym (NULL, "openpty");
	}
	if (!dyn_login_tty) {
		dyn_openpty = r_lib_dl_sym (NULL, "login_tty");
	}
	if (!dyn_forkpty) {
		dyn_openpty = r_lib_dl_sym (NULL, "forkpty");
	}
}

#endif
```
The lines `dyn_openpty = r_lib_dl_sym (NULL, "login_tty");` and `dyn_openpty = r_lib_dl_sym (NULL, "forkpty");` are setting the `dyn_openpty` function pointer instead of the function pointers they are supposed to be setting up. Consequently, `dyn_login_tty` and `dyn_forkpty` will always be NULL and can never be used, resulting in errors if they are needed. A fixed version of this function would _possibly_ be
```c
static void dyn_init(void) {
	if (!dyn_openpty) {
		dyn_openpty = r_lib_dl_sym (NULL, "openpty");
	}
	if (!dyn_login_tty) {
		dyn_login_tty = r_lib_dl_sym (NULL, "login_tty");
	}
	if (!dyn_forkpty) {
		dyn_forkpty = r_lib_dl_sym (NULL, "forkpty");
	}
}
```
However, this may require additional work, as the use of hardcoded `NULL` (instead of a pointer returned by  might be causing issues. `r_lib_dl_sym(NULL, "forkpty")` returns NULL when this is compiled and run on up to date Arch Linux (which receives `forkpty` from /`usr/lib/libutil.so`, provided by the `core/util-linux-libs` package). On linux and unix systems, `r_lib_dl_sym` calls `dlsym` under the hood. However, dlsym expects an object returned by `dlopen` and fails to find the symbols queried here. using LD_PRELOAD to preload `/usr/lib/libutil.so` allows the `dlsym` call to find these symbols, however.

**Comment by intruder-kat** [comment]
I can try to hack on this some more soon to attempt to fix the need for LD_PRELOAD, however I'm not very familiar with this code base and therefore I'm wary of inadvertently breaking portability (or breaking something else). Perhaps `dyn_init` should be made to use system-specific IFDEFs and call `dlopen` to load libutil.so.

**Comment by intruder-kat** [comment]
Wrote a fix to fall back on libutil.so if these symbols failed to be found on Linux, getting it reviewed for potential breakage (I don't usually account for portability so there might be footguns I'm unaware of) before I submit a PR for it.

**Comment by trufae** [comment]
Dont be shy and push the pr :) its better to discuss over code

**Comment by trufae** [comment]
Thanks for the research and the fix! we can close this issue after your PR 🥳
