### ISSUE TITLE
Crash of output saved breakpoints db*

### ISSUE THREAD

**Issue by 9Demien9** [radareorg/radare2#18502]
## Environment

```sh
Ср 24 мар 2021 09:02:25 +04
radare2 5.2.0-git 25821 @ linux-x86-64 git.5.1.1
commit: 510ddab0e523bed173b3954e5f61abf395812f7d build: 2021-03-23__09:17:49
Linux x86_64

```

## Description

During debugging, after saving and then reading the breakpoints, the db* output crashe 

## Test

We run for debugging ls:
r2 -d /usr/bin/ls
]> aaa
]> db main             ; arbitrary breakpoints
]> db main+4        ; arbitrary breakpoints
}> db main+6        ; arbitrary breakpoints
]>s main
]> pd 10
 4759: int main (int argc, char **argv, char **envp);
│ bp: 0 (vars 0, args 0)
│ sp: 9 (vars 9, args 0)
│ rg: 2 (vars 0, args 2)
│           0x56421d7200a0 b    4157           push r15                ; rsp=0x7fff28eae908 (cstr 0x7fff28eb0b01) "/usr/bin/ls"
│           0x56421d7200a2      4156           push r14                ; rsp=0x7fff28eae900
│           0x56421d7200a4 b    4155           push r13                ; rsp=0x7fff28eae8f8
│           0x56421d7200a6 b    4154           push r12                ; rsp=0x7fff28eae8f0
│           0x56421d7200a8      4189fc         mov r12d, edi           ; argc ; r12=0x0
│           0x56421d7200ab      55             push rbp                ; rsp=0x7fff28eae8e8
│           0x56421d7200ac      4889f5         mov rbp, rsi            ; argv ; rbp=0x0
│           0x56421d7200af      53             push rbx                ; rsp=0x7fff28eae8e0
│           0x56421d7200b0      4883ec48       sub rsp, 0x48           ; rsp=0x7fff28eae898 ; of=0x0 ; sf=0x0 ; zf=0x0 ; pf=0x0 ; cf=0x0 ; af=0x0
│           0x56421d7200b4      488b3e         mov rdi, qword [rsi]    ; argv ; rdi=0xffffffffffffffff

]> db*
dbm /usr/bin/ls 160
dbm /usr/bin/ls 164
dbm /usr/bin/ls 166
]> db* > bpls
]> q

Again we run it for debugging ls:
r2 -d /usr/bin/ls
]> aaa
]>. bpls
]> db*
dbm �Z��U 160
dbm �Z��U 166
dbm @Z��U 164

db* output crashe. 

Thank you in advance!

**Comment by trufae** [comment]
Thanks for reporting! just had some mins to check this out, i can repro and im fixing it right now

**Comment by 9Demien9** [comment]
Thank you very much! You make the world's best debugger!
