### ISSUE TITLE
Cannot Install the program

### ISSUE THREAD

**Issue by Dka233** [radareorg/radare2#18527]
I have this log:

`WARNING: Updating from remote repository
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
error: cannot open .git/FETCH_HEAD: Permission denied
Building on Linux : computing number of allowed parallel jobs.
Maximum allowed RAM memory per job is 150000 kB.
Number of CPUs is 4 and current free RAM allows us to run 42 jobs in parallel.
So, the build will run on 4 job(s).
rm: cannot remove 'plugins.cfg': Permission denied
/home/douglas/radare2
configure-plugins: Loading ./plugins.cfg ..
configure-plugins: Generating libr/config.h ..
./configure-plugins: 136: cannot create libr/config.h: Permission denied
./configure-plugins: 137: cannot create libr/config.h: Permission denied
./configure-plugins: 138: cannot create libr/config.h: Permission denied
./configure-plugins: 139: cannot create libr/config.h: Permission denied
configure-plugins: Generating libr/config.mk ..
./configure-plugins: 142: cannot create libr/config.mk: Permission denied
./configure-plugins: 143: cannot create libr/config.mk: Permission denied
./configure-plugins: 144: cannot create libr/config.mk: Permission denied
SHARED: io.shm
STATIC: anal.6502 anal.6502_cs anal.8051 anal.amd29k anal.arc anal.arm_cs anal.arm_gnu anal.avr anal.bf anal.chip8 anal.cr16 anal.cris anal.dalvik anal.ebc anal.gb anal.h8300 anal.hexagon anal.i4004 anal.i8080 anal.java anal.m680x_cs anal.m68k_cs anal.malbolge anal.mcore anal.mips_cs anal.mips_gnu anal.msp430 anal.nios2 anal.null anal.or1k anal.pic anal.ppc_cs anal.ppc_gnu anal.pyc anal.riscv anal.riscv_cs anal.rsp anal.sh anal.snes anal.sparc_cs anal.sparc_gnu anal.sysz anal.tms320 anal.tricore anal.v810 anal.v850 anal.vax anal.wasm anal.ws anal.x86_cs anal.xap anal.xcore_cs anal.xtensa anal.z80 asm.6502 asm.6502_cs asm.8051 asm.amd29k asm.arc asm.arm_as asm.arm_cs asm.arm_gnu asm.arm_winedbg asm.avr asm.bf asm.chip8 asm.cr16 asm.cris_gnu asm.dalvik asm.dcpu16 asm.ebc asm.gb asm.h8300 asm.hexagon asm.hppa_gnu asm.i4004 asm.i8080 asm.java asm.lanai_gnu asm.lh5801 asm.lm32 asm.m680x_cs asm.m68k_cs asm.malbolge asm.mcore asm.mcs96 asm.mips_cs asm.mips_gnu asm.msp430 asm.nios2 asm.null asm.or1k asm.pic asm.ppc_as asm.ppc_cs asm.ppc_gnu asm.propeller asm.pyc asm.riscv asm.riscv_cs asm.rsp asm.sh asm.snes asm.sparc_cs asm.sparc_gnu asm.sysz asm.tms320 asm.tricore asm.v810 asm.v850 asm.v850_gnu asm.vax asm.wasm asm.ws asm.x86_as asm.x86_cs asm.x86_nasm asm.x86_nz asm.xap asm.xcore_cs asm.xtensa asm.z80 bin.any bin.art bin.avr bin.bf bin.bflt bin.bios bin.bootimg bin.cgc bin.coff bin.dex bin.dmp64 bin.dol bin.dyldcache bin.elf bin.elf64 bin.fs bin.java bin.le bin.mach0 bin.mach064 bin.mbn bin.mdmp bin.menuet bin.mz bin.ne bin.nes bin.nin3ds bin.ninds bin.ningb bin.ningba bin.nro bin.nso bin.omf bin.p9 bin.pe bin.pe64 bin.pebble bin.prg bin.psxexe bin.pyc bin.qnx bin.sfc bin.smd bin.sms bin.symbols bin.te bin.vsf bin.wasm bin.xbe bin.xnu_kernelcache bin.z64 bin.zimg bin_ldr.ldr_linux bin_xtr.xtr_dyldcache bin_xtr.xtr_fatmach0 bin_xtr.xtr_pemixed bin_xtr.xtr_sep64 bp.arm bp.bf bp.mips bp.ppc bp.x86 core.a2f core.java crypto.aes crypto.aes_cbc crypto.base64 crypto.base91 crypto.blowfish crypto.cps2 crypto.des crypto.punycode crypto.rc2 crypto.rc4 crypto.rc6 crypto.rol crypto.ror crypto.rot crypto.serpent crypto.xor debug.bf debug.bochs debug.esil debug.gdb debug.io debug.native debug.null debug.qnx debug.rap debug.winkd egg.exec egg.xor esil.dummy fs.ext2 fs.fat fs.fb fs.hfs fs.hfsplus fs.io fs.iso9660 fs.jfs fs.minix fs.ntfs fs.posix fs.r2 fs.reiserfs fs.sfs fs.tar fs.udf fs.ufs fs.xfs io.ar io.bfdbg io.bochs io.debug io.default io.fd io.gdb io.gprobe io.gzip io.http io.ihex io.mach io.malloc io.mmap io.null io.procpid io.ptrace io.qnx io.r2k io.r2pipe io.r2web io.rap io.rbuf io.self io.shm io.sparse io.tcp io.w32 io.w32dbg io.winedbg io.winkd io.zip lang.c lang.cpipe lang.pipe lang.rust lang.spp lang.v lang.vala lang.zig parse.6502_pseudo parse.arm_pseudo parse.att2intel parse.avr_pseudo parse.chip8_pseudo parse.dalvik_pseudo parse.m68k_pseudo parse.mips_pseudo parse.ppc_pseudo parse.riscv_pseudo parse.sh_pseudo parse.tms320_pseudo parse.v850_pseudo parse.wasm_pseudo parse.x86_pseudo parse.z80_pseudo
cp: './plugins.cfg' and 'plugins.cfg' are the same file
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr/local'
checking for c compiler... ./configure: 384: cannot create test.c: Permission denied
no
cleaning temporally files... done
ERROR: gcc cannot create executables
`

**Comment by trufae** [comment]
Can you describe the steps you followed to get this and which is your environment? Looks like you have issues in the git folder permissions and more errors appear like missing compiler and such

**Comment by Dka233** [comment]
I did this:

git clone https://github.com/radare/radare2
cd radare2
sys/install.sh

And it was the output.

**Comment by trufae** [comment]
Which system are u running those commands in?

- the git folder complains about wrong permissions
- do u have a c compiler installed?

you are cloning the wrong repo: radare vs radareorg

**Comment by Dka233** [comment]
It seems like the wrong repo was the problem, I use radareorg and then it works. How can I close this issue? Thanks

**Comment by trufae** [comment]
Thx ill remove the other repo

**Comment by trufae** [comment]
Wait.. theres no such repo at all

**Comment by Dka233** [comment]
Then you should check the info in this website:

https://rada.re/r/down.html

**Comment by trufae** [comment]
This page is very outdated and its kept there just for historic reasons. You should check https://radare.org
