### ISSUE TITLE
`r2 -qc 'oba 0; ia'` segfaults on this binary (stack exhaustion)

### ISSUE THREAD

**Issue by Pamplemousse** [radareorg/radare2#18534]
[files.zip](https://github.com/radareorg/radare2/files/6251086/files.zip)

---

## Environment

```
$ date
Fri Apr  2 11:06:31 AM MST 2021

$ ./myR2/bin/r2 -v
radare2 5.2.0-git 3186 @ linux-x86-64 git.5.1.1
commit: 6ac85fc2789a042e71ff7b0d943984c5295bebf1 build: 2021-04-02__16:05:01

$ uname -ms
Linux x86_64
```

## Description

Discovered by fuzzing.

A specially crafted binary file can make `radare2` segfault on analysis, because of an illegal memory access in `libr/anal/dwarf_process.c`.
In particular, an infinite recursion exhausts the stack.

## Test

Binary `id:000010,sig:11,src:007149,time:85810536,op:havoc,rep:4` provided as attachment.

```
$ ./myR2/bin/r2 -qc 'oba 0; ia' id:000010,sig:11,src:007149,time:85810536,op:havoc,rep:4
Segmentation fault (core dumped)
```

Also included `id:000010,sig:11,src:007149,time:85810536,op:havoc,rep:4.patch`, the "dirty patch" we wrote to clean our fuzzing session.

---

cc @aaronjsteele, @capuanob, @dyunus
cc @crowell

**Comment by trufae** [comment]
Thanks for the samples and quickfixes! i have fixed them all in master and commited the bins int he testbins repo in the fuzzed directory.
