### ISSUE TITLE
r2 -V does not work properly

### ISSUE THREAD

**Issue by gordboy** [radareorg/radare2#18576]
## Environment

```sh
Mon 12 Apr 17:36:52 BST 2021

radare2 5.2.0 0 @ linux-x86-64 git.
commit: HEAD build: 2021-04-11__21:08:42

Linux x86_64
```

## Description

r2 -V does not give version numbers

## Test

```sh
$ r2 -V
  r2
  r_anal
  r_lib
  r_egg
  r_asm
  r_bin
  r_cons
  r_flag
  r_core
  r_crypto
  r_bp
  r_debug
  r_main
  r_hash
  r_fs
  r_io
  r_magic
  r_parse
  r_reg
  r_sign
  r_search
  r_syscall
  r_util
```

**Comment by trufae** [comment]
ill take a look. thanks

**Comment by trufae** [comment]
Is this happening when building from the release tarball or git?

**Comment by gordboy** [comment]
It happens with release tarball and also all the release deb packages.

I'm beginning to think this project is not worth pursuing.
Elementary schoolboy errors are the mark of a project about to expire.
