### ISSUE TITLE
aesb in VV

### ISSUE THREAD

**Issue by s0i37** [radareorg/radare2#18603]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
Ср 21 апр 2021 12:19:11 +05
radare2 5.2.0 26151 @ linux-x86-64 git.5.2.0
commit: cf3db945083fb4dab951874e5ec1283128deab11 build: 2021-04-12__11:00:54
Linux x86_64
```

## Description

I use reverse debugging in VV mode.
Then I make step back (aesb) VV mode doesn't update. It requires manual redraw via `r` key.

## Test

aei;aeip;aeim;aets+
af
VV
aes; aes; aes; aesb

**Comment by trufae** [comment]
this "VV" mode i guess is the visual interactive graph mode, right? running commands in the prompt wont update the graph view, its hard to say when its necessary and when its not to refresh because whats rendered is being invalidated. so i dont think that `aes` updates the graph either, so its not an issue for just the step backward

**Comment by s0i37** [comment]
But `aes` refresh VV normaly.

**Comment by trufae** [comment]
Nope. it does not. it refresh if you press 's' to step in the graph, but not if you press `:aes` in the prompt there

**Comment by s0i37** [comment]
Yes. I mean F7.
I have hotkey `e key.f6 = aesb` for stepping back. And I wanted that F6 has the similar behavior.

**Comment by trufae** [comment]
tahts why:

```
                case R_CONS_KEY_F7:
                        cmd = r_config_get (core->config, "key.f7");
                        if (cmd && *cmd) {
                                (void)r_core_cmd0 (core, cmd);
                        } else {
                                graph_single_step_in (core, g);
                        }
                        break;
```

i think it makes sense to refresh the graph on all F keys unconditionally. what do u think?

**Comment by trufae** [comment]
can u test https://github.com/radareorg/radare2/pull/18606 ?

**Comment by s0i37** [comment]
I think it would be nice.

**Comment by trufae** [comment]
Merged, you can test master :) consider it fixed

**Comment by trufae** [comment]
The ideal fix would be to create an invalidation API that may handle events and support regions. this api can be used by other frontends like iaito or panels, ill think about that, but for now i guess that the F refresh thing will work for you.

**Comment by s0i37** [comment]
Thanks a lot!
I've already tested. It works great. Thanks again)
