### ISSUE TITLE
Wrong assembly generated for: "add x0, x0, 1, lsl #12" (ARM64)

### ISSUE THREAD

**Issue by ValdikSS** [radareorg/radare2#18619]
## Description

rasm2 ARM64 ADD command seems to ignore LSL #XX and generates opcode without it.

Generated opcode with keystone:
```
$ kstool arm64 'add x0, x0, 1, lsl #12'
add x0, x0, 1, lsl #12 = [ 00 04 40 91 ]
```

Generated opcode with rasm2 commit 9a14c294fc5ea3f8677b86ffffbdb1403b28ade2:
```
$ rasm2 -a arm -b 64 'add x0, x0, 1, lsl #12'
00040091

$ rasm2 -a arm -b 64 'add x0, x0, 1'
00040091
```

The issue seems to be similar to #16969

**Comment by trufae** [comment]
Should be easy to fix, tagging for 5.3 if anyone is in the mood to tweak the r2 assembler to handle it properly go for it!
