### ISSUE TITLE
remove the command ds <num>

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#18647]
## Description

*Please describe what are you missing or wanting to be improved*

In my humble opinion there is no need to do a command `ds <num>`or `dso <num>` because we already can do `<num>ds` so these command are redondant. So I plan to remove the command `ds <num>`. I just need your opinion then I do.

*Provide images, ascii-art, test files and anything that may help us understand your request*

**Comment by trufae** [comment]
An operation like step is important to be executed many times and faster. Running thru the command parser on every step is not necessary. That was the reason i did it like this. But i agree 3ds makes more sense than 3wx. So maybe repeat operation should behave differently on commands that print or write increasing the current seek.

cool to discuss command design things like this!
