### ISSUE TITLE
Overwriting projects

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#18641]
Imagine the following scenario:

```
$ r2 /bin/ls
> Ps jeje
> q
```

And then:

```
$ r2 /bin/sleep
> Ps jeje
> q
```

Issues found: 

* Nothing blocks the user to overwrite an existing project
* Projects should be only saved if they were loaded first or they dont exist
* Quitting asks the user to save the project again
* We may delete projects before overwriting them imho

**Comment by Shadorain** [comment]
This is the same with layouts but is not as much of a big deal.

**Comment by trufae** [comment]
Both issues should be easy to fix. Do you want to give it a try? Otherwise i will fix them as soon as i get some spare time

**Comment by Shadorain** [comment]
> Both issues should be easy to fix. Do you want to give it a try? Otherwise i will fix them as soon as i get some spare time

For sure if u could point me in the right direction, I'll grep through and see where it'd be in the project tho unless u have a specific place.

**Comment by trufae** [comment]
Everything you need to touch is in project.c. Just use the commands above and make it behave as described.
