### ISSUE TITLE
Can't scroll completely down in disassembler.

### ISSUE THREAD

**Issue by Kakiking** [radareorg/radare2#18645]
## Environment

```
Fri Apr 30 08:46:22 CEST 2021
radare2 5.3.0-git 26220 @ linux-arm-32 git.5.2.1
commit: d9e7ae80ad5850cf43ee4dcbc71ef6eba1a071cb build: 2021-04-30__07:29:28
Linux aarch64
```

I'm using a Raspberry Pi 3B+ with Raspbian.

## Description

When trying to scroll to the bottom of the disassembler output at a certain point the screen goes black for a split second and I further up in the disassembler output

## Test

The command I ran to start the webserver:
`r2 -c=H crackme_02.exe `

The command output:
```
Metadata Signature: 0xe60 0x10001424a5342 12
.NET Version: v2.0.50727
Number of Metadata Streams: 5
DirectoryAddress: 6c Size: fec
Stream name: MZ\ufffd 4
DirectoryAddress: 1058 Size: f3c
Stream name: MZ\ufffd 4
DirectoryAddress: 73676e69 Size: 0
Stream name: MZ\ufffd 4
DirectoryAddress: 2d0 Size: 535523
Stream name: MZ\ufffd 4
DirectoryAddress: 10 Size: 49554723
Stream name: MZ\ufffd 4
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/
Opening in existing browser session.
```

The executable:
[crackme_02.exe.zip](https://github.com/radareorg/radare2/files/6403409/crackme_02.exe.zip)

A Video of the bug happening:
https://user-images.githubusercontent.com/66200818/116658596-7c41bd80-a990-11eb-94e8-24bab40f5ca6.mp4

**Comment by trufae** [comment]
This seems like a bug in https://github.com/radareorg/radare2-webui r2 ships a build of that webui, but the source is in a different repository. Can you reopen the issue there?

thanks!

**Comment by trufae** [comment]
Did you tried the behaviour with different browsers?

**Comment by Kakiking** [comment]
ah, ok
