### ISSUE TITLE
Cannot run the latest releases in Ubuntu Bionic

### ISSUE THREAD

**Issue by eadmaster** [radareorg/radare2#18652]
## Environment

```
Mon May  3 18:30:41 CEST 2021
(nothing)
Linux x86_64
```

## Description

I've Tried installing both the `radare2_5.2.1_amd64.deb` and the `r2-static.tar.xz` from the Releases section.
In both cases i get this error when launching any executable:
````
rasm2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libr_io.so)
rasm2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libr_hash.so)
rasm2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libr_socket.so)
rasm2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libr_magic.so)
````

**Comment by trufae** [comment]
Github removed the non lts  ubuntu images. And bionic is not there.. so i can setup a chroot of 18 on 20 to get it working again . But ideally people using non supported systems should upgrade or build their own. I can do local builds for it but thats extra debt for me and ideally i would prefer the CI to do all the magic

**Comment by eadmaster** [comment]
i understand... nevermind then, i've found another static build that works in my system.

**Comment by eadmaster** [comment]
btw static binaries should not be linked with glibc in order to avoid this issue...

**Comment by trufae** [comment]
Glibc is the standard c library. 99.9% of the programs depend on it, and r2 is also needing it. The only way would be use statically linked binaries, but linking to libc is needed

**Comment by trufae** [comment]
Static bins dont link to any library. If the static build is depending on it, its not a staric build. Ill recheck the ci to see what happened there
