### ISSUE TITLE
radare freezes program in Linux when attach

### ISSUE THREAD

**Issue by D1mon** [radareorg/radare2#18663]
Same as #15937 but for Linux(Manjaro)
## Environment

```sh
# copypaste this script into your shell and replace it with the output
Thu May  6 03:19:41 PM MSK 2021
radare2 5.2.1 0 @ linux-x86-64 git.5.2.1
commit: unknown build: 2021-04-26__23:00:17
Linux x86_64
```

## Description

Any programs freezes after attach

## Test

terminal 1:
run `kate`

terminal 2:
`r2 -d <pid of kate>`

kate freezes (buttons, keypress not working)

**Comment by trufae** [comment]
Yeah that's expected, you have to run `dc` to continue the execution of the process if you want that. If there's an issue after this it could be related to the way threads are processed

**Comment by D1mon** [comment]
Yes, it works, but sometimes needes few times `dc`. Application is running, but i can't put any radare command except ^C (Ctrl + C), and app freezes again.

**Comment by radare** [comment]
Then it seems that dc is not continuing all the threads. But only the
currently selected one

**Comment by D1mon** [comment]
I testing in `gdb`. In gdb same bug(maybe not bug, but i don't like this behavior). `gdb` freezes after attaching and unfreeze after `cont` and i can't input any commands until press ^C

**Comment by trufae** [comment]
Well thats how debuggers work. They have a blocking interface when the process is running. You cant interact with the debugee until the process is stoped again. Windows have some async apis but you cant do everything. In r2, the memory reads go thru the proc interface so if u just want to read write memory while the process runs you can do that. But reading registers and such is not possible or make sense at all

**Comment by trufae** [comment]
If you want interactivity use r2frida

**Comment by trufae** [comment]
Can you try setting -e dbg.threads=true ?

**Comment by D1mon** [comment]
No works, still freezes.

**Comment by trufae** [comment]
Yes, thats usually how debuggers work on Linux. because ptrace is blocking and must be used from the same thread.

**Comment by D1mon** [comment]
This may not apply to this topic, but I just wonder. And how then does Cheat Engine (CE) work? When CE works in the debugger mode, it does not block the program (game).

**Comment by trufae** [comment]
Cheat engine is a windows tool. Windows api permit that. On linux/mac the debugger needs to block/queue calls and have dedicated threads to handle this. Its just that r2 debugger for windows behaves like linux/mac debuggers work. Which nay not be the expected way.

This will eventually be addressed but its not yet done

**Comment by gogo2464** [comment]
I really hope this issue does not come from cast on the refactor of this PR: https://github.com/radareorg/radare2/pull/18669

**Comment by trufae** [comment]
This is not an issue. Its normal behaviour and its not a regression. And no, your patch is harmless and unrelated
