### ISSUE TITLE
Grep negation modifier not working as expected

### ISSUE THREAD

**Issue by jorlamd** [radareorg/radare2#18690]
## Environment

```sh

$ date
Thu May 13 11:22:38 AM BST 2021
$ r2 -v
radare2 5.3.0-git 26199 @ linux-x86-64 git.5.2.1
commit: 053fca8585f7893fb5ccc0ff4246ace37fb28c73 build: 2021-05-13__11:11:10
$ uname -ms
Linux x86_64

```

## Description
Negation modifier might not be working as expected on internal grep operator, it seems to have no effect.

## Test

```sh

[0x00005b20]> is~FUNC~GLOBAL[6]~libc
imp.__libc_start_main
[0x00005b20]> is~FUNC~GLOBAL[6] | grep libc
imp.__libc_start_main
**[0x00005b20]> is~FUNC~GLOBAL[6]~!libc
imp.__libc_start_main**
[0x00005b20]> is~FUNC~GLOBAL[6] | grep -v libc
...  (expected large output)

```

**Comment by trufae** [comment]
Related https://github.com/rizinorg/rizin/commit/ec3bde4c8e67d1c2d92e8b40c068f02794d7b9f9#diff-f7433eab8a4faf4341e548a61aa561dee14c029be75bda64eec07b09ed2120b2

**Comment by trufae** [comment]
See the new BROKEN tests for the cons_neg introduced in https://github.com/radareorg/radare2/pull/18763
