### ISSUE TITLE
rafind2 outputs partially wrong with some blocksizes

### ISSUE THREAD

**Issue by ianmatt** [radareorg/radare2#18699]
## Description
rafind2 output is partially wrong when search hit overlaps blocksize

## Test
for eg. the attached test.bin file has the string "1234" at offset 0xfe
case 1) rafind2 -s "1234" -X -b 0x100 test.bin (string will be located in 2 blocks)
case 2) rafind2 -s "1234" -X test.bin
in both cases search hit(offset) is ok, but in first case the hexdump output is wrong (same behaviour when output as json -j or string -Z)

![photo_2021-05-15_15-48-01](https://user-images.githubusercontent.com/28786798/118361626-f5e2c980-b594-11eb-9c45-b6997be14ed8.jpg)

[test.zip](https://github.com/radareorg/radare2/files/6487177/test.zip)

**Comment by radare** [comment]
I did a test for with with your sample bin, added 3 more tests and fixed the issue in a PR. will merge soon :)

thanks for the detailed tests and explanation!

**Comment by ianmatt** [comment]
> I did a test for with with your sample bin, added 3 more tests and fixed the issue in a PR. will merge soon :)
Thanks!

I've tried last build, played a little and I've noticed the hex dump is inconsistent on some cases
for eg. the attached test2.bin file, 0x2000 (zero) bytes and the string "1234" at offset 0xffe and depending on how the search is made, in some case hex dump will have garbage bytes or missing bytes inplace of string

**Comment by radare** [comment]
thank you! ill fix now. it's hard to catch all that without tests, so i really appreciate all those samples

**Comment by trufae** [comment]
Should be good now :) thanks for the rechecks

**Comment by ianmatt** [comment]
> Should be good now :) thanks for the rechecks

yes, all fine
gracias!
