### ISSUE TITLE
Support for more than 65535 segments in ELF64

### ISSUE THREAD

**Issue by IridiumXOR** [radareorg/radare2#18783]
Hi,
as specified by `man elf` and also in [https://docs.oracle.com/cd/E18752_01/pdf/817-1984.pdf](https://docs.oracle.com/cd/E18752_01/pdf/817-1984.pdf)

```
e_phnum
This member holds the number of entries in the program header table.  Thus the product of e_phentsize and e_phnum gives the table's size in bytes.  If a file has no program header, e_phnum holds the value zero.
If the number of entries in the program header table is larger than or equal to PN_XNUM (0xffff), this member holds PN_XNUM (0xffff) and the real number of entries in the program header table is  held  in  the  sh_info member of the initial entry in section header table.  Otherwise, the sh_info member of the initial entry contains the value zero.

PN_XNUM
This is defined as 0xffff, the largest number e_phnum can have, specifying where the actual number of program headers is assigned.
```
This is a issue if you try to load, for example, a QEMU virtual memory dump (`memsave` command) because the ELF64 contains more than 65535 segments and Radare is not able to show, access and operates on segments with index > 65535
Please can you fix/add it?

**Comment by trufae** [comment]
Enotime for this release but sure, sounds like a good improvement to support in the r2 elf parser. I’ll label it for 5.4

thanks!

**Comment by IridiumXOR** [comment]
Thanks :)

**Comment by trufae** [comment]
Could you provide a sample elf for testing purposes? how big are those files?

**Comment by IridiumXOR** [comment]
Yes, here a "synthetic" example: it contains 131070 segments, the firsts 65535 point to offset 0x1040 the second ones to the offset 0x2040. I created it because QEMU memsave dumps have a size equal to the VM RAM, so they are very big :)  `readelf` is able to parse it correctly, while `file` inform you that it has too much segments
[test_elf.zip](https://github.com/radareorg/radare2/files/6575026/test_elf.zip)

**Comment by trufae** [comment]
Just pushed the bin in the testbins repo: https://github.com/radareorg/radare2-testbins/commit/7a3bf0ac9ba0d993a919caad2538dc0534032fa2

i have gzipped it (600KB) and can be loaded via gzip://core65k but i didnt fixed the sections issue yet. will do tomorrow (hopefully)

sorry for the late response and really thanks for submitting the test bin!

**Comment by trufae** [comment]
Just implementet that in a dirty way. i'm now cleaning and adding tests :)
