### ISSUE TITLE
Windows CI builds are not ready for consumption

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#18791]
The following steps must be done by hand right now after the release to get iaito/r2ghidra/r2frida builds to work automatically.

* unzip the zip
* unzip the zip inside the zip
* rename radare2_install to radare2-${R2V}
* zip it back

ideally the zip generated in the CI should be generated that way

**Comment by gogo2464** [comment]
Assign me to this issue. I will see if I have time.

**Comment by trufae** [comment]
I will assign when you have time, anyway i dont expect anyone to pick it. Should be good to fix for 5.4

**Comment by trufae** [comment]
Fixed
