### ISSUE TITLE
Is there a 32 bit debug mode in radare2?

### ISSUE THREAD

**Issue by sordidlist** [radareorg/radare2#18810]
I'm attempting to use radare2 to duplicate the debug process I'm using in Immunity, which is a 32 bit debugger. Still a bit new to reverse engineering.

Is there a way to switch radare2 to debug in 32 bit mode? So that I have EIP instead of RIP, for instance? Or is that not possible?

**Comment by trufae** [comment]
You mean for windows?

**Comment by sordidlist** [comment]
Either Linux or Windows, but yeah, ideally it'd be cool to be able to get practice with r2 using binaries I already know how to overflow, and most of them are windows 32 bit.

**Comment by trufae** [comment]
I’m sorry but the Windows 32bit support was removed a couple of years ago by the cutter team. Im not a windows person but i would certainly like to see r2 in reactos and w95.js. So it will be good to bring it back (as well as mingw support as it was before)

**Comment by trufae** [comment]
For all the unixes, yes, r2 runs fine on 32bit for mips, arm, x86, ... for linux, *bsd, solaris, macos..

**Comment by radare** [comment]
Sorry totally forgot i added back the msvc rules to build r2 for 32bit, so yes, you can download it from the artifacts page from github actions or take this copy i got from the last master build, didnt tried, so let me know if it works as expected

[radare2-install.zip](https://github.com/radareorg/radare2/files/6617618/radare2-install.zip)

**Comment by sordidlist** [comment]
Oh nice! Thanks so much for linking this.

I checked it out in my Windows debugging VM. For some reason the memory addresses are a little different from the ones I get when I debug my binary in Immunity (address randomization is off on this bin so I'm not quite sure why).

However I think I've managed to work out the main steps! I might put together a little guide in case anyone else is interested in doing what I'm doing.

I'm happy to call this closed, just curious if you might know why the addresses are a little different between debuggers.

**Comment by trufae** [comment]
Not sure which addresses u are refering to, but if its heap or stack that could be affected by the apis used by the debugger which end up changing the context like the env vars and such. But i cant say much without more details.

happy to close the issue ^^
