### ISSUE TITLE
handle the signal `SIGPWR` in the command di

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#18835]
## Description

*Please describe what are you missing or wanting to be improved*

*Provide images, ascii-art, test files and anything that may help us understand your request*
Detect the signal `SIGPWR` in `di`.

The command $ radare2 -e cfg.fortunes=false -e dbg.args=30 -d elf/signals/signal-input
[0x7fa88217e7bb]> di~signal:0
signal=none

Prints none as signal. it should raise `SIGPWR`. Then I suggest a new PR to replace `none` by `SIGPWR`.

**Comment by radare** [comment]
Thats a signal not a debug stop reason. And in my 30 years using unix i have never seen such signal in real apps. So dont wanna mess the debug stop reasons when it could be just a system specific signal that never happens

**Comment by gogo2464** [comment]
@radare you are right. I have been too fast reading my linux interface c book. I have not care it yet.
