### ISSUE TITLE
List DLL imports correctly (with function name and virtual address)

### ISSUE THREAD

**Issue by newlog** [radareorg/radare2#1884]
Hi there,

I think that there's a bug listing the imported functions of DLL. For example, with rabin2 I get the following output listing functions:

```
ordinal=017 plt=0x00000000 bind=NONE type=FUNC name=GDI32.dll_CreateDIBSection
ordinal=001 plt=0x00000000 bind=NONE type=FUNC name=PSAPI.DLL_EnumProcessModules
ordinal=002 plt=0x00000000 bind=NONE type=FUNC name=PSAPI.DLL_GetModuleFileNameExA
ordinal=018 plt=0x00000000 bind=NONE type=FUNC name=WS2_32.dll_Ordinal_18
ordinal=011 plt=0x00000000 bind=NONE type=FUNC name=WS2_32.dll_Ordinal_11
ordinal=052 plt=0x00000000 bind=NONE type=FUNC name=WS2_32.dll_Ordinal_52
```

I think that the PLT field should show the RVA, but with Windows symbols it's not correctly listed. This output is extracted from LAB05-01.dll from the Practical Malware Analysis book. This DLL is in the git from the r2 regression project.

Finally, in my notes I had the following note: 
"In the end, some imports should be listed from r2 with the "ir" commmand. It's weird to have to check some imports with "aa" and "afl", and others with "ir"."

I'm not sure about it and I cannot test it right now, but it might help you.

Thanks for your work!

**Comment by condret** [comment]
Hi,

I was just wondering , have you ever seen something like that? Just take a look <http://gentochuzi.zombiefleshjerky.com/lnpvutt>

Yours faithfully, lukas-runas@gmx.de
