### ISSUE TITLE
(Maybe) Incorrect ESIL for "mul rdx"

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [radareorg/radare2#18860]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
$ date
Sat Jun 26 01:03:32 EDT 2021

$ r2 -v
radare2 5.4.0-git 26454 @ darwin-x86-64 git.5.3.1
commit: 635fad4eb9a7b6c7f41de7f72525083fc74213c1 build: 2021-06-26__00:24:45

$ uname -ms
Darwin x86_64
```

## Description

For x64, the ESIL of `mul rdx` seems incorrect.

```sh
$ rasm2 -a "x86" -b 64 "mul rdx"
48f7e2

$ rasm2 -a "x86" -b 64 -E 48f7e2
64,rdx,rax,*,>>,rdx,=,rdx,rax,*=,rdx,?{,1,1,}{,0,0,},cf,:=,of,:=
```

Specifically, the value of _rdx_ is changed before setting the value of _rax_.

For example, if we have `rdx = 8` and `rax = 4` at the beginning. 

For the result ESIL `64,rdx,rax,*,>>,rdx,=,rdx,rax,*=,rdx,?{,1,1,}{,0,0,},cf,:=,of,:=`,

When interpreting the first`64,rdx,rax,*,>>,rdx,=`, we will have: `rdx = 0` and `rax = 4`.
Then we interpret `rdx,rax,*=`, we will have: `rdx = 0` and `rax = 0`.

However, the correct result should be: `rdx = 0` and `rax = 32`.

## Test

Following aforementioned steps.

**Comment by radare** [comment]
as for reference it should be:

```c
void multiply64(uint64_t a, uint64_t b, uint64_t *h, uint64_t *l) {
	uint64_t const base = 0x100000000;
	uint64_t al = a % base;
	uint64_t ah = a / base;
	uint64_t bl = b % base;
	uint64_t bh = b / base;
	*l = al * bl;
	*h = ah * bh;
	uint64_t rlh = *l / base + al * bh;
	*h += rlh / base;
	rlh = rlh % base + ah * bl;
	*h += rlh / base;
	*l = (rlh % base) * base + *l %base;
}
```

**Comment by aemmitt-ns** [comment]
I wrote this and will fix, it should be using the L* operator that exists now for 64 bit muls.

**Comment by aemmitt-ns** [comment]
Though that isn't really the issue here, the esil will also fail for mul edx but I will fix that too.
