### ISSUE TITLE
The binary file can't be opened with error: Cannot open 'dbg://./out' for writing.

### ISSUE THREAD

**Issue by clock999** [radareorg/radare2#18883]
Hello, 

I try to debug a bin file with r2, but failed to open it.
The file format is as below.
out: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
The command is : r2 -d out
And the error message is: [w] Cannot open 'dbg://./out' for writing.

Could you give me some help? Thanks a lot!

**Comment by trufae** [comment]
Which version of r2 are you using and is your host machine  a 32bit arm linux system?

**Comment by clock999** [comment]
Hello, 

This is my r2 versiosn: 
radare2 5.4.0-git 26401 @ linux-x86-64 git.5.3.1
commit: 4eba32d4f67ea7fc76f7f8870aac08022a4d1cc9 build: 2021-07-02__10:16:26

My PC is ubuntu-x86-64bit, on which I run the r2.

**Comment by radare** [comment]
Thats expected. You cant debug arm binaries on intel hardware unless you use a vm or emulator or something

**Comment by clock999** [comment]
Ok, got it. Thanks a lot!
