### ISSUE TITLE
Can not save changed assembly code on raspberry pi aarch64

### ISSUE THREAD

**Issue by AiziChen** [radareorg/radare2#18882]
## Environment
Raspberry pi OS (64bit) on raspberry pi

```sh
Sat 03 Jul 2021 05:58:36 PM CST
radare2 5.3.1 0 @ linux-arm-64 git.5.3.1
commit: 5.3.1 build: 2021-06-29__14:50:35
Linux aarch64
```

## Description

I use `r2 -w binary` command to change the assembly code and can not save successful.

these are my operations:

```sh
> r2 -w some-program
> aaa
> s main
> V + p
> Shift + a
> "change some line such as `movz w0, 1` to `movz w0, 2`"
> "prompt `Save changes?`, then I click `Y`"
```

after these operations, I quit the radare2, but the `some-program` do not change.

**Comment by trufae** [comment]
cant reproduce, is this still an isse foro you? pllease tetst the last release or git

**Comment by AiziChen** [comment]
@trufae I tried version 5.4.2, but this issue still exists.

**Comment by trufae** [comment]
Can you share any binary you repro the issue for me to try? Do you have io.cache enabled? Is there anything in your radare2rc?

**Comment by AiziChen** [comment]
@trufea yeah~, I set io.cache=true on .radare2rc file. After I disabled it now, it works well. Thank you!
