### ISSUE TITLE
Version string in 5.4.0 release tarball still contains git postfix

### ISSUE THREAD

**Issue by nmeum** [radareorg/radare2#18891]
The version string in the 5.4.0 release tarball still contains the `-git` postfix (i.e. `5.4.0-git`) in the configure script. This is the case since commit 87c6bd0f2eab441a4b46d2cb1ace1bc9a1043b52. Since previous versions did not contain this postfix and the version is also copied, with the postfix, to the version field of the pkgconfig files this seems like a mistake to me.

**Comment by trufae** [comment]
Because it's a git tag, not a release
