### ISSUE TITLE
Invalid chunk size or double free detected when reusing clipboard

### ISSUE THREAD

**Issue by nikkej** [radareorg/radare2#18932]
## Environment

Sat Jul 24 04:46:31 PM EEST 2021
radare2 5.4.0 27436 @ linux-x86-64 git.5.4.0-git-40-g3c416c54c
commit: 3c416c54cc6f5acefdd362b115c0782b459d928e build: 2021-07-22__13:58:47
Linux x86_64

## Description

I'd like to use clipboard in a python loop (via r2pipe) to read function raw bytes into program by dumping the clipboard to named pipe (fdata in this case) and reading said pipe from python but if I reuse clipboard with less data (i.e. like a smaller function size) I get 'invalid chunk size':
```
$ r2 test_openssl.exe 
 -- r2 talks to you. tries to make you feel well.
[0x004014e0]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
...
[x] Enable constraint types analysis for variables
[0x004014e0]> y 64 @dbg.mainCRTStartup
[0x004014e0]> ytf fdata
[0x004014e0]> y 64 @dbg.mainCRTStartup
[0x004014e0]> ytf fdata
[0x004014e0]> y 32 @dbg.mainCRTStartup
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

```
And if I reuse clipboard so that I do or do not operations with clipboard in between reading into it (honestly, this is not 100% clear to me what steps need to be not done with clipboard to reproduce issue) while altering the amount of bytes read into it so that subsequent reads are less than initial read, I get 'double free detected':
```
$ r2 test_openssl.exe 
 -- **** COMMODORE 64 RADARE V2 ****  64K RAM SYSTEM  38911 DISASM BYTES FREE  READY.
[0x004014e0]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
...
[x] Enable constraint types analysis for variables
[0x004014e0]> y 64 @dbg.mainCRTStartup
[0x004014e0]> y 32 @dbg.mainCRTStartup
[0x004014e0]> yx
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  83ec 0cc7 0518 3757 0000 0000 00e8 eece  ......7W........
0x00000010  1300 83c4 0ce9 66fc ffff 9090 9090 9090  ......f.........
[0x004014e0]> ytf fdata
[0x004014e0]> y 50 @dbg.mainCRTStartup
free(): double free detected in tcache 2
Aborted (core dumped)
```

## Test

Commands fed exactly as above shall reproduce issues mentioned here

## Programs used in analysis

Binary attached, OpenSSL pre compiled attached. Files to reproduce binary are:
```
#include <stdio.h>
#include <windows.h>
#include <openssl/ssl.h>

int main( void ) {
    SSL_library_init();

    return( 0 );
}
```
And:
```
test_openssl.exe: test_openssl.c
	i686-w64-mingw32-gcc -I include -L lib -g -o test_openssl.exe -mconsole test_openssl.c -static -lssl -lcrypto -lws2_32 -lgdi32

test_openssl_dce.exe: test_openssl.c
	i686-w64-mingw32-gcc -I include -L lib -g -fdce -ftree-dce -fdse -ftree-dse -Wl,--gc-sections -o test_openssl_dce.exe -mconsole test_openssl.c -static -lssl -lcrypto -lws2_32 -lgdi32

clean:
	rm -f *.exe *.o
```
OpenSSL: [https://wiki.openssl.org/index.php/Binaries](https://wiki.openssl.org/index.php/Binaries)
[test_openssl.exe.gz](https://github.com/radareorg/radare2/files/6872659/test_openssl.exe.gz)
[openssl-1.0.2h-win32-mingw.zip](https://github.com/radareorg/radare2/files/6872660/openssl-1.0.2h-win32-mingw.zip)

**Comment by trufae** [comment]
Thanks for reporting! Nice spot!

**Comment by nikkej** [comment]
My pleasure!

-nikke
