### ISSUE TITLE
type recovery

### ISSUE THREAD

**Issue by Frankenstein-bit** [radareorg/radare2#18947]
I am just start to know abot radare2.i want to know how radare2 recover type info like array,struct and so on?

**Comment by trufae** [comment]
This is not an issue or a feature request, so i'm closing here.

Right now r2 is just assuming types of arguments and local variables by deriving them from the function signatures involved, there's no array detection and structs need to be defined manually if not autodetected by a function signature.

There's a lot to improve on those aspects, so feel free to suggest changes and improve with contributions.
