### ISSUE TITLE
Pin vector35-arch-arm64 to a fixed revision

### ISSUE THREAD

**Issue by Mic92** [radareorg/radare2#19004]
At the moment the aarch64 assembler repo is not pinned, which is a bit of a foot gun since it is not clear
what versions has been used by the developer when testing the code and also user might forgot to update this repository
since it is not enforced by the build system:
https://github.com/radareorg/radare2/blob/a604152750011b9f37533d43db8a6847e8d4619c/libr/asm/arch/arm/v35arm64/Makefile#L20

Our current approach in nixpkgs is to check what the latest revision of the repo is when we update radare2: https://github.com/NixOS/nixpkgs/pull/135015/files#diff-c68dcfa0c8bc8d2c0b95b10d99216635053724661d30c26aad8ad6974161902eR30

**Comment by trufae** [comment]
Can you please retest and confirm the fix works as expected? I'm trying to avoid submodules because of different reasons that has been discussed already, you may want to run ./preconfigure for offline builds. Same workflow works on windows by using the preconfigure.bat script

**Comment by Mic92** [comment]
This won't help git users but I rather much prefer it this way, since it does not assume git during the build.

**Comment by Mic92** [comment]
Using `preconfigure` is not an option since in nixpkgs we don't allow buildsystem download stuff but rather have explicit checksums passed to special fetcher functions to capture all dependencies in a reproducible and cache-able manner.
