### ISSUE TITLE
Can't use install.sh when a non-posix-compatible shell is used by default

### ISSUE THREAD

**Issue by pavlukivan** [radareorg/radare2#19011]
## Environment

Fish shell, Arch Linux

## Description

I have fish set as the default shell. When I try to build radare2 using the install scripts, even when using sh/bash, the build.sh script is ran using the default shell. That means build.sh will run using fish as opposed to sh/bash. That happens because it uses `${SHELL} ./sys/build.sh` as opposed to `./sys/build.sh` or `/usr/bin/env sh ./sys/build.sh` or similar.

## Test

1. set default shell to fish
2. try using install.sh

**Comment by trufae** [comment]
Unfortunely, fish is not posix compliant.. so i just added a check in sys/install.sh to handle that and fallback to /bin/sh

Thanks for reporting! but ideally it would be better to make fish follow the ancient and well known unix standards :D
