### ISSUE TITLE
architecture 8051 : implement JNB instruction

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#19028]
## Description

*Please describe what are you missing or wanting to be improved*

radare2 does not disassemble the instruction 30 in 8051 as JNB. It prints invalid instead.

*Provide images, ascii-art, test files and anything that may help us understand your request*

I want to fix it. Assign me to this issue please.

**Comment by trufae** [comment]
No need to ask for things to beassigned. Just make them. There are  almost 1000 issues and almost no contributors at all . The chance to have someone taking any issue is lower than winning the lottery.

but ill assign it just in case
