### ISSUE TITLE
provide a tutorial with a common template to write plugins

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#19031]
## Description

*Please describe what are you missing or wanting to be improved*

In his current state radare2 allow any contributor to submit plugins. This is great. Everybody in the world can contribute in upstream. Sadly there is no template to write the body of plugins. This has as effect that each plugin is written in a very different style. Some have many many functions. some do not have so.

Then I suggest to write in the r2book some guidelines to write plugins as tutorial.

You could move this issue to r2book repo if you agree with me.

*Provide images, ascii-art, test files and anything that may help us understand your request*

**Comment by trufae** [comment]
This belongs to the r2book

**Comment by gogo2464** [comment]
> This belongs to the r2book

Yes butit does also implies to reimplements plugins like avr to a template like 8051.
