### ISSUE TITLE
Inconsistent directory names in Windows zip distributions

### ISSUE THREAD

**Issue by MarkKoz** [radareorg/radare2#19055]
## Description

In 5.3.1, the directory in the Windows distributions was named `radare2-5.3.1-w64` or `radare2-5.3.1-w32`. These followed a consistent format. However, in 5.4.0, the w64 directory is named `radare2-5.4.0` but the w32 directory is named `radare2-install`. This matters for automated tools e.g. [scoop autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate). I suppose changing the name formats once isn't too bad, but doing it several times would become disruptive. I don't really see a reason to have deviated anyway, but probably no one was considering that it would even matter.

**Comment by radare** [comment]
I think the w32/w64 suffix should be kept, i will change the ci scripts accordingly.

**Comment by trufae** [comment]
Fixed ! i'll do the 5.4.2 release soon. Stay tuned! and thanks for the heads up! i hope to also sync r2env with the consistent zip names.

**Comment by MarkKoz** [comment]
Thanks for taking care of this so quickly in the sea of 800+ issues you have!

**Comment by trufae** [comment]
You are welcome :) feel free to report whatever you see. Im trying to make windows another first tier platform for r2.

also, would you like to give it a try to r2env? Its in pip, but better go for the git. It doesnt support windows zip downloading yet but its on the plans

**Comment by MarkKoz** [comment]
> Im trying to make windows another first tier platform for r2.

Your efforts have not gone unnoticed. Really nice that there are official Windows builds in CI now.

> would you like to give it a try to r2env

I'm a novice in this sort of domain, so I don't currently have a need for multiple versions of radare. That being said, the main scoop bucket, which I use to download radare, is out of date and PRs aren't getting addressed in a timely manner. r2env may end up being a nice alternative to just installing radare at all.
