### ISSUE TITLE
COFF: ARM Windows CE objects are not recognized

### ISSUE THREAD

**Issue by dogtopus** [radareorg/radare2#19061]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
Thu Sep  9 02:14:04 AM UTC 2021
r2 -v
radare2 5.3.1 0 @ linux-x86-64 git.5.3.1
commit: unknown build: 2021-06-12__00:39:47
uname -ms
Linux x86_64

```

## Description

COFF files targeting ARM Windows CE (machine 0x1c0) is not recognized at all unless I use `r2 -F coff -a arm -b 32`.

## Test

1. Run `r2 empty.o`
2. Run `i`
3. See it fail.

[empty.o.gz](https://github.com/radareorg/radare2/files/7132845/empty.o.gz)

**Comment by dogtopus** [comment]
Just gave it a try. Now it recognizes the file but it's still opened in x86 mode...

**Comment by trufae** [comment]
Wooops missed a case. Should be good now
