### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock subprocs_mutex

### ISSUE THREAD

**Issue by ryancaicse** [radareorg/radare2#19083]
Hi, developers, thank you for your checking. It seems the lock `subprocs_mutex` is not released correctly when `write (proc->killpipe[1], &r, 1) != 1 `**(the second break)** in the function `static RThreadFunctionRet sigchld_th(RThread *th)`?
https://github.com/radareorg/radare2/blob/7c14bac05b55196f500358c81a31acee99338d4b/binr/r2r/run.c#L428-L451

**Comment by ryancaicse** [comment]
Also, the lock could be released before `exit (-1); `  for better resource management and code symmetry. 

https://github.com/radareorg/radare2/blob/601f3174ea35473a3211c901aa654b52cca72819/binr/r2r/r2r.c#L458-L489

**Comment by trufae** [comment]
Please submit a pullreq with the suggested changes. You can press the pencil button in github’s site to do the pr directly from the web

**Comment by ryancaicse** [comment]
@trufae OK, I created one. Please check.

**Comment by ryancaicse** [comment]
Hi, I think there could be security issues for the first bug - unreleased lock could lead to deadlock(a DoS), wreaking a DoS. Could we apply CVE for this?

**Comment by ryancaicse** [comment]
Thanks. It seems the developers can request CVE ID more easily through Github, and radare2 has requested them for other vulnerabilities according to the CVE records. But I will try.
