### ISSUE TITLE
question ida

### ISSUE THREAD

**Issue by rafalohaki** [radareorg/radare2#19106]
Is ida pro better than radare2?

**Comment by trufae** [comment]
Looks like you did the same question in other repositories and this is far from being an issue, so i’m closing the ticket.

Each tool have its goods and bads but that doesnt makes one better or worse.

feel free to submit a more specific question when you have a chance to test the tools and build an opinion by yourself.

**Comment by rafalohaki** [comment]
im looking for alternative but idk if its better

**Comment by trufae** [comment]
Then you must give it a try. But as i said, it depends a lot on your usecase, your workflow, the targets and your style/taste, for some people and some uses IDA is great. For others r2 is better, just dont stick to one tool and try to get the best of all
