### ISSUE TITLE
rename variabls

### ISSUE THREAD

**Issue by khireddine10** [radareorg/radare2#19219]
## Description
hello radare2 developers, I wish you're doing well.
I have a problem with renaming variables.
when I reload the program with the doo "command", the renaming occurs only in variables created by radare2

*deep description*
# first renaming 
my code looks like 
![image](https://user-images.githubusercontent.com/44124081/137156422-186cd5e9-2b93-4bc7-8482-6ac7ff70b722.png)

after changing the name of variables
![image](https://user-images.githubusercontent.com/44124081/137157220-84afb41a-da4f-4f52-8328-4364940fb93b.png)

# in case of doo "reload the program"
![image](https://user-images.githubusercontent.com/44124081/137158412-b5ef67d3-50cf-44e6-936d-611bb43b3109.png)

thanks for your great work and art.

**Comment by condret** [comment]
fixed

**Comment by khireddine10** [comment]
Thanks for your quick response sir.
