### ISSUE TITLE
Replace rbtree implementation

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#19252]
Current rbtree implementation has some issues with UAF after using the delete function.
It would be more desirable to fix that, but let's face it: Nobody in the dev-community has the gigachad brain to understand this compactly written piece of code in all details and it's effectively unmaintainable for us.

https://github.com/leiless/jw_rbtree this implementation looks much more simple, clean and seems easier to understand.

Befor start porting it, here are some rules:
- no single character varnames
- keep complexity as low as possible

I'll do the port, @radare pls do the review later

**Comment by trufae** [comment]
Thats merged. Good job

**Comment by trufae** [comment]
Now its time to replace the old one
