### ISSUE TITLE
issue with colored flags displaying

### ISSUE THREAD

**Issue by unabomber78** [radareorg/radare2#19396]
windows10x64 radare2 5.4.3

* [x] px is not displaying colored flags
* [x] pxa is displaying only some of colored flags not all.
* [x] fc flagname is displaying nothing

**Comment by trufae** [comment]
Thanks for filling the ticket! i will take a look at this after release!

Note that github issues use markdown syntax, so you can create a check list (let me edit your message)

**Comment by trufae** [comment]
i did some improvements in ed2030b79e68986bf04f3a6279463ab989fe400f

**Comment by trufae** [comment]
Evertyhing implemented in master. please feel free to test and suggest more and better places to use the flag color feature, thanks!
