### ISSUE TITLE
The result of the esil statement is inconsistent with expectations

### ISSUE THREAD

**Issue by junchao98** [radareorg/radare2#19391]
## Environment

```sh
2021年 11月 09日 星期二 10:33:30 HKT
radare2 5.3.1 0 @ linux-x86-64 git.5.3.1
commit: unknown build: 2021-06-12__20:28:34
Linux x86_64
```

## Description

This problem may also be my misunderstanding of esil.

I executed the following esil instructions in r2
```
[0x0000a128]> ae 8,1,>>
No output?
1
8
[0x0000a128]> ae 8,1,|
1
8
[0x0000a128]> ae 8,1,<<
0x100
[0x0000a128]> ae 8,1,+
0x9
[0x0000a128]> 

```
In my understanding, the first instruction and the second instruction should be expressed in C as

```
printf("%d", 8U>>1)
printf("%d", 8|1)
```
But esil output is not what I thought it would be, and I'm not sure if this is

**Comment by junchao98** [comment]
After being prompted by my friend I tried to execute the instruction in the following way and got the same result as expected
```
[0x0000a128]> ae 8,1,\|
0x9
[0x0000a128]> ae 8,1,\>>
0
[0x0000a128]> 
```

**Comment by trufae** [comment]
Use quotes like this: “ae 8,1,<<“

**Comment by junchao98** [comment]
i got it!
