### ISSUE TITLE
r2 -d debug not printing output to console

### ISSUE THREAD

**Issue by huornlmj** [radareorg/radare2#19398]
When I debug an ELF program that prints output to stdout, I don't see any output.  After googling I see some less than basic workarounds with something called rarun2.  Is there any native option that will work here rather than using additional tools?

**Comment by trufae** [comment]
Unless you are using visual mode, the output of the command should be printed in the screen.

Ideally is better to run the command in a separate terminal and then attach to it.

rarun2 is part of r2, its nothing external. you can use the -r and -R flags with the options described in `man rarun2`.
