### ISSUE TITLE
Panels Mode: Top menu bug

### ISSUE THREAD

**Issue by PROPHESSOR** [radareorg/radare2#19409]
## Environment

```sh
prophessor@prophessor-X555LJ ~> date
Пн ноя 15 15:41:07 EET 2021
prophessor@prophessor-X555LJ ~> r2 -v # v5.5.0 master, has the bug
radare2 5.5.0 1 @ linux-x86-64 git.
commit: eb301fdea05654a749f8014166aefa915ea7e6ff build: 2021-11-15__15:24:46
prophessor@prophessor-X555LJ ~> /usr/bin/r2 -v # v4.3.1 doesn't have the bug
radare2 4.3.1 0 @ linux-x86-64 git.4.3.1
commit: HEAD build: 2020-03-06__15:05:41
prophessor@prophessor-X555LJ ~> uname -ms
Linux x86_64
```

## Description

In the master version, it is impossible to switch between the tabs of the top menu. Also, when choosing a view mode, the menu does not close. See video in `## Test` for details

## Test

https://youtu.be/96bSZKSCdBc

**Comment by trufae** [comment]
The top menu is unfocused when pressing the 'm' key to toggle menu access or pressing the tab key to select a different panel. not sure if i understand the issue you are having here, but maybe it's not an issue :?

**Comment by trufae** [comment]
ping?

**Comment by PROPHESSOR** [comment]
@trufae There are two bugs:
1. You can't move to menu's header by pressing up arrow key like it was in v4.3.1
2. In the video after changing view to Breakpoints the menu is still on the screen. It looks like missed repaint call, so you need open menu again to re-render and hide it

**Comment by trufae** [comment]
sorry for the delay again, was busy as hell catching other bugs. from what i understand.

1) this is expected, the old behaviour was wrong imho.
2) fixed

**Comment by PROPHESSOR** [comment]
1. It's not convenient to move through menus in this case. For example, in the case of new behaviour pressing right arrow will open Colors submenu instead of moving to Edit tab.

![image](https://user-images.githubusercontent.com/19251320/154366481-013ad21b-95bc-4d59-b719-eeb6beec55f1.png)
