### ISSUE TITLE
Panels Mode: Cursor boundary issues in frames

### ISSUE THREAD

**Issue by PROPHESSOR** [radareorg/radare2#19410]
## Environment

```sh
prophessor@prophessor-X555LJ ~> date
Пн ноя 15 15:41:07 EET 2021
prophessor@prophessor-X555LJ ~> r2 -v # v5.5.0 master, has the bug
radare2 5.5.0 1 @ linux-x86-64 git.
commit: eb301fdea05654a749f8014166aefa915ea7e6ff build: 2021-11-15__15:24:46
prophessor@prophessor-X555LJ ~> /usr/bin/r2 -v # v4.3.1 doesn't have the bug
radare2 4.3.1 0 @ linux-x86-64 git.4.3.1
commit: HEAD build: 2020-03-06__15:05:41
prophessor@prophessor-X555LJ ~> uname -ms
Linux x86_64
```

## Description

The cursor can't move in the Functions window in the current master version. But it works in 4.3.1. See video in `## Test` for details

## Test

https://youtu.be/NKMTVfEta0E

**Comment by PROPHESSOR** [comment]
Also, in version 4.3.1 there were frequent cases when the cursor went out of the screen down to the Symbols bar.

**Comment by trufae** [comment]
I have updated the issue title to make clear this is not an issue in visual mode, but in panels mode.

 thanks for recording the video!

**Comment by PROPHESSOR** [comment]
@trufae It seems to be related: https://youtu.be/6M7opygeorg
On previous versions, scrolling worked fine

**Comment by trufae** [comment]
udp?

**Comment by PROPHESSOR** [comment]
> udp?

Ah, it's like post scriptum :grin: 
Came later/added later

**Comment by trufae** [comment]
if you set R2_DEBUG_ASSERT=1 and then start r2 with a debugger attached, you will find out why's the panels glitching with this r_anal_op call. if you paste the backtrace ill fix it . because i cant repro, and this is probably tied to your usecase/workflow

**Comment by trufae** [comment]
i can reproduce. fixing now
