### ISSUE TITLE
Is Win7 deprecated ?

### ISSUE THREAD

**Issue by kimstik** [radareorg/radare2#19421]
radare2-5.5.0-w64.zip
under Win7 shows popup "Entry Point Not Found" for GetSystemTimePreciseAsFileTime
this function available since Win8

**Comment by kimstik** [comment]
It seems it it problem not radare2 itself but plugin core_pdd.dll

**Comment by condret** [comment]
r2 actually doesn't use this, so it's an issue of r2ghidra or maybe even the ghidra decompiler using this

**Comment by trufae** [comment]
It was an issue in r2dec and its now solved
