### ISSUE TITLE
several integer overflows in marchal.c leading to heap corruption / crashes

### ISSUE THREAD

**Issue by RickdeJager** [radareorg/radare2#19455]
## Environment

```sh
$ date
di 30 nov 2021 20:48:19 CET
$ r2 -v
radare2 5.5.1 27159 @ linux-x86-64 git.5.5.0
commit: f50d5c41654500acfe3ffdd843e8607cc41c8743 build: 2021-11-30__20:21:25
$ uname -ms
Linux x86_64
```

## Description
While fuzzing, we ran into the following issue (last one for now I promise). The `marshal.c` decoder contains several instances of the following parser logs:
```c
// n1 is read from the input file
// In our fuzz case, n1 = 0xffffffff (aka MAX_INT)
u32 n1 = get_st32 (buffer, &error);
// ... <snip> ...
// The allocation essentially becomes malloc(0) after integer overflow.
ut8 *s1 = malloc (n1 + 1);
// ... <snip> ...
// Both of these next lines can cause a crash.
r_buf_read (buffer, s1, n1); // (1)
s1[n1] = '\0';               // (2)
```
This pattern happens twice in `get_complex_object` ([here](https://github.com/radareorg/radare2/blob/99d7b1f7a2e57360f1aa158546d6a9ea1a0f72c0/libr/bin/format/pyc/marshal.c#L345) and  [here](https://github.com/radareorg/radare2/blob/99d7b1f7a2e57360f1aa158546d6a9ea1a0f72c0/libr/bin/format/pyc/marshal.c#L366)). The attached zip contains test bins for both cases.  

## GDB log
For example, here is a GDB view of the second case:
```
In file: /home/rick/git/radare2/libr/bin/format/pyc/marshal.c
   373 		R_FREE (s1);
   374 		R_FREE (s2);
   375 		R_FREE (ret);
   376 		return NULL;
   377 	}
 ► 378 	s2[n2] = '\0';
   379 
   380 	ret->type = TYPE_COMPLEX;
   381 	ret->data = r_str_newf ("%s+%sj", s1, s2);
   382 	R_FREE (s1);
   383 	R_FREE (s2);
```
`r2` segfaults on the above instruction, and when examining `n2`, we can see it is equal to max_int
```
pwndbg> p/x n2
$1 = 0xffffffff
```

## Test
1. Unzip the test files: [crashes_n_plus_1.zip](https://github.com/radareorg/radare2/files/7628361/crashes_n_plus_1.zip)
2. open them in `r2` (with or without asan)

## (Potential duplicates)
I don't have a test bin ready for these (sorry), but I wanted to highlight some similar cases here in case it's of use:
* `get_float_object` with a user controlled u8 + 1 [here](https://github.com/radareorg/radare2/blob/99d7b1f7a2e57360f1aa158546d6a9ea1a0f72c0/libr/bin/format/pyc/marshal.c#L284)
* `get_ascii_interned_object` and `get_ascii_object`, which take a user controlled , unchecked size and can potentially overflow the `u32 size` to create an object of the wrong size [here](https://github.com/radareorg/radare2/blob/99d7b1f7a2e57360f1aa158546d6a9ea1a0f72c0/libr/bin/format/pyc/marshal.c#L79)

**Comment by trufae** [comment]
Thanks!
