### ISSUE TITLE
Disallow system commands execution when opening projects?

### ISSUE THREAD

**Issue by OctavioGalland** [radareorg/radare2#19458]
## Description

When working with radare2 projects, with @ogianatiempo we noticed that all r2 commands can be executed in a `.rc` file, including `!<some shell cmd>`, which may allow someone sharing a malicious project file to execute commands on another host. I think it would make sense to restrict projects' `.rc` files to disallow the use of `!`. Maybe this is a design decision, but we thought maybe it would be worth mentioning.

The `.rc` file gets parsed here: https://github.com/radareorg/radare2/blob/master/libr/core/project.c#L304 so maybe a possible fix would be to add a function like `r_core_safe_cmd_file` (or something like that) which executes the project file after removing all potentially malicious commands (We can provide a PR for this, we just wanted to make sure if you agree that this shouldn't be expected behavior).

**Comment by trufae** [comment]
The sandbox right now disables:
* networking/sockets
* filesystem/read/write
* program execution

Project scripts do load files so it require filesystem access, but it's true that program execution, network or file modification is not needed. So maybe we can make the sandbox more finegrained for this specific case and enable it when loading projects

**Comment by trufae** [comment]
Please submit a PR with your fix proposal and i'll review. Thanks!

**Comment by OctavioGalland** [comment]
We weren't aware of the existence of a sandbox. To be honest, adding more granular permissions looks somewhat complicated because the `sandbox_enabled` flag is being checked throughout the whole codebase before issuing different commands.
We were just thinking about filtering commands when opening a project file, but such a big change is a bit out of our possibilities at the moment, given our knowledge about the codebase.

**Comment by condret** [comment]
I'd suggest adding prj.sandbox config var

**Comment by trufae** [comment]
Project scripst need to be able to open files from disk. so not sure how that will work with that sandbox thing unless we just disable command execution. but project scripts shouldnt contain any of this unless the user have modified them on purpose.

So maybe we can define that "light" sandbox mode as is:

* read-only file system access
* networking disabled (as it can be used for data exfiltration)
* disable command execution.

ill work on that patch. so im self assigning this to myself :D

**Comment by radare** [comment]
fine grained sandbox implemented in https://github.com/radareorg/radare2/pull/19516 

when green ill merge and use it from projects :)

**Comment by trufae** [comment]
Solved via prj.sandbox, but needs more testing and its not enabled by default, can you please test it and provide some feedback and ideas to improve it? thanks! (its in master)
