### ISSUE TITLE
issue on arm ADRP instruction 

### ISSUE THREAD

**Issue by smartether** [radareorg/radare2#19464]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
r2 -v
uname -ms
```

## Test

code from rasm2
![image](https://user-images.githubusercontent.com/3928724/144570441-cc351094-0a4a-4462-a0a1-7f967651dbfa.png)
code from ida keypatch
![image](https://user-images.githubusercontent.com/3928724/144570516-0cc83f56-1aad-4c82-9e61-ee76b54dc359.png)

**Comment by smartether** [comment]
![image](https://user-images.githubusercontent.com/3928724/144574506-4e14ffb7-5717-426c-9254-7e8bec6c2352.png)

**Comment by trufae** [comment]
i can confirm this issue. you can use the keystone plugin for now. but ill fix it asap.

Thanks!

`r2pm -ci keystone ; rasm2 -a arm.ks -b64 'adrp x16, 0x1000'`
