### ISSUE TITLE
/a does not work as expected

### ISSUE THREAD

**Issue by nkamadan** [radareorg/radare2#19488]
## Environment
Fri 10 Dec 2021 10:28:07 PM +03
radare2 5.4.2 1 @ linux-x86-64 git.
commit: 84e6cc6a21ec1c816d4d3eb3510d2cdc94330414 build: 2021-09-20__04:53:52
Linux x86_64

## Description
/a option doesn't work as I expect and I think there is a problem with it. When I search for a specific instruction such as "rdtsc" it shows me some addresses, and when I go to those addresses I see that there exists rdtsc instructions. However, the problem is that there are actually no rdtsc instructions there. When /a is used, the binary is searched and when 0f31 opcode is found which stands for rdtsc, it is directly replaced with the original instructions. In the original case, 0f belongs to the opcode of mov and 31 belongs to the opcode of xor, (see my example case).  

## Test
1) r2 /bin/ls
2) aaa
3) /a rdtsc
4) Go to the first address and switch to visual mode (V). And save the first address for later use.
5) You see an rdtsc there.
6) Close the analysis and start over from the step 1 and skip step 3. Now in step 5 you will not see an rdtsc but you will see the real instructions there. 

![image](https://user-images.githubusercontent.com/63115827/145631565-37a71d36-b5b8-466b-be97-6e792e3fad51.png)
![image](https://user-images.githubusercontent.com/63115827/145631682-b62307aa-808e-4f1c-a9e3-cf00287f6cfd.png)
![image](https://user-images.githubusercontent.com/63115827/145631961-1606b692-ebbd-48ae-83bd-3d6fd270f6f9.png)

**Comment by gogo2464** [comment]
This might not be a bug. Could you share the output of `e search.in` please? Maybe you did not specify where to search.

**Comment by Lazula** [comment]
this behavior appears to be intentional. /a searches for the literal bytes of the assembled instruction, so the matches are valid. the `~` character seems to mark the duplicated byte that was searched for (`0f` appears in both instructions). this seems fine to me

**Comment by trufae** [comment]
I think that it makes sense to add a search.in for functions that only scan for aligned instructions in basic blocks. But that could be a subcommand of /a.  Default behaviour is this one because intel allows variable size instructions to any offset could be valid

**Comment by trufae** [comment]
I have implemented /aF and /aFd for this purpose. please try, and feel free to suggest improvements on the /a subcommands help message and organization . thanks!
