### ISSUE TITLE
Disassembling using 'pdf' command returns null. 

### ISSUE THREAD

**Issue by saneeha-amir** [radareorg/radare2#19486]
I am working with the process dump of an android application. The application under analysis was running on x64 android emulator. I have used volatility to obtain the process dump from the memory image of the emulator.

My goal is to record the complete disassembly of the process dump. I am using r2pipe with python. 

I have tried the command r.cmd('pdf > out') 

Some times the output file is empty and some time it contains half the assembly. An error is also reported as under:

                p: Cannot find function at 0x00001ed4

Note: r.cmd('pd') returns the disassembly but it is not complete. 

Please guide , where am i wrong and how to make r2 read the complete disassembly of the process dump. 
Thanks

**Comment by trufae** [comment]
pdf disassembles a single function. If you dont a analyze there are no functions and pdf wont print anything.

to didassemble a range of bytes use pI or pD.

Please dont use issues for quesrions

**Comment by saneeha-amir** [comment]
Thanks for your reply.
Problem was solved by using 'aaa' command for analyzing all functions before 'pdf' command
r.cmd('aaa')
r.cmd('pdf @@ fcn > out')
