### ISSUE TITLE
izz seems to ignore memory maps for binaries without header

### ISSUE THREAD

**Issue by cavedon** [radareorg/radare2#19524]
## Environment

Radare 5.5.4 (or today's master, 0c6d40c) on Ubuntu focal 64 bit

## Description

```sh
% echo "this is string" > textfile
% r2 -m 0x1000 textfile 
Warning: using oba to load the syminfo from different mapaddress.
 -- Mind that the 'g' in radare is silent
[0x00001000]> izz
[Strings]
nth paddr      vaddr      len size section type  string
―――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000000 0x00000000 15  15           ascii this is string\n

[0x00001000]> om
* 1 fd: 3 +0x00000000 0x00001000 - 0x0000100e r-x 
[0x00001000]> xs 0x1000
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00001000  7468 6973 2069 7320 7374 7269 6e67 0aff  this is string..
0x00001010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
 ...
[0x00001000]> xs 0x0
[0x00001000]> 
```

I expect  the `vaddr` in the output of `izz` to be `0x1000` instead of `0x0`.

This is a follow up from https://discord.com/channels/698492940917538878/788195469636796446/922220406822281226

**Comment by cavedon** [comment]
I found out that if set
```c
ret->has_va = 1;
```
in `RBinInfo *info(RBinFile *bf)` in `bin_any.c`, then the `vaddr` column in `izz` output is correct.
Should that be set whenever `-m` is passed?
I can create a patch, but it is not clear to me how know if the file was mapped at a different address from inside bin_any.c...

**Comment by cavedon** [comment]
Actually this is a duplicate of #17372. The bug is actually in the capstone project https://github.com/capstone-engine/capstone/issues/1673.
It may be worthwhile keeping the bug open in radare2 as well until the upstream bug is resolved, as it manifests as bug in radare2 as well.

**Comment by trufae** [comment]
Can you make a PR with this change? thanks!

**Comment by radare** [comment]
im on it

**Comment by trufae** [comment]
https://github.com/radareorg/radare2/pull/19684

**Comment by trufae** [comment]
https://github.com/radareorg/radare2/pull/19684

**Comment by trufae** [comment]
ill finish the pr for the next release. couldnt merge before that because ther was enough critical bugs accumulated :D
