### ISSUE TITLE
isqq. command not working

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#19534]
Should just print the symbol name in the current offset.

like is. or isq., but only showing the name

**Comment by c-urly** [comment]
this good? @trufae 
`[0x00001050]> isqq. `<br>`
0x000002a8 .interp`<br>`
0x000002c4 .note.gnu.build-id`<br>`
0x000002e8 .note.ABI-tag`<br>`
0x00000308 .gnu.hash`<br>`
0x00000330 .dynsym`<br>`
0x000003d8 .dynstr`<br>`
0x0000045a .gnu.version`<br>`
0x00000468 .gnu.version_r`<br>`
0x00000488 .rela.dyn`<br>`
0x00000548 .rela.plt`<br>`
0x00001000 .init`<br>`
0x00001020 .plt`<br>`
0x00001040 .plt.got`<br>`
0x00001050 .text`<br>`
0x000011c4 .fini`<br>`
0x00002000 .rodata`<br>`
0x0000200c .eh_frame_hdr`<br>`
0x00002050 .eh_frame`<br>`
0x00003de8 .init_array`<br>`
0x00003df0 .fini_array`<br>`
0x00003df8 .dynamic`<br>`
0x00003fd8 .got`<br>`
0x00004000 .got.plt`<br>`
0x00004020 .data`<br>`
0x00004030 .bss`<br>`
0x00000000 .comment`<br>`
0x00000000 crtstuff.c`<br>` `

**Comment by trufae** [comment]
No. This output is not listing symbols or even being quiet

**Comment by c-urly** [comment]
Misunderstood the command. is this fine?
[0x00004610]> is.

nth paddr      vaddr      bind   type size lib name
―――――――――――――――――――――――――――――――――――――
98  0x00004610 0x00004610 GLOBAL FUNC 16       imp.fwrite

[0x00004610]> isq.
0x00004610 16 imp.fwrite

[0x00004610]> isqq.
imp.fwrite

**Comment by trufae** [comment]
Yeah thats how it should work :)

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/radare2/pull/19551
