### ISSUE TITLE
File not want to patch

### ISSUE THREAD

**Issue by lkz0ne** [radareorg/radare2#19589]
I am learning by doing some cracking in files that i made in C. One of this files is this:

file.c:

```
#include <stdio.h>
#include <stdlib.h>

int main() {
        char s[15] = "disassemba";
        int x;
        x=555;
        printf("%d",x);

        if (x == 2000) {
                printf("You win");
        } else {
                printf("You lose");
        }
}
```

So i compile with: gcc file.c -o file

open the file with radare: r2 -w file

The commands i use is the following, in radare2, in order:

```
aaa
s main
V
```

in visual mode, i need modify the line of code where sets x=555 to x=2000. So i navigate in visual mode to:

![image](https://user-images.githubusercontent.com/64380275/149668015-3d6fa101-932d-4cc6-b5ed-6d842b46f2d1.png)

And i hit shift+a, but when i try insert

mov dword [var_4h], 0x7D0

the file is not patched (no changes in asm code).

any hint?

note:Preferably in some easy way where i can write the code in asm and not in machine code.

**Comment by lasek0** [comment]
You need to reopen file in read-write mode (look to oo+)
I done that like this:
```
$ gcc hello.c -o hello
$ ./hello 
555You lose$
$ r2 hello
oo+ # reopen file in read-write mode
aaa # analyse
s main # seek to main
pdf # print code assembly
```

in my case I have x=555 as following code
```
│           ; var uint32_t var_1ch @ rbp-0x1c
...
│           0x000011a3      c745e42b0200.  mov dword [var_1ch], 0x22b
```

I need to generate instructions bytes from mnemonic, can do that in r2 like this:
`pa mov dword [rbp-0x1c], 0x7d0`

then I got this as result:
`c745e4d0070000`

next I patch the file like this:
`wx c745e4d0070000 @ 0x000011a3 # write this bytes in hexstring form @ address 0x11a3
`
then print again function assembly using
`pdf
`
I got now:
`│           0x000011a3      c745e4d00700.  mov dword [var_1ch], 0x7d0  ; 2000
`

then You can quit from r2:
`q # quit`

and file should be patched:
```
$ ./hello 
2000You win$
```
If You are learning I can give You few hints to r2:
firs of all You need to know how to seek through help:
?*~some_words
for example:
```
[0x00000000]> ?*~assemble
| dtd[qi] [nth-start]                List all traced disassembled (quiet, instructions)
| pa[edD] [arg]           pa:assemble  pa[dD]:disasm or pae: esil from hex
| pd[?] [sz] [a] [b]      disassemble N opcodes (pd) or N bytes (pD)
...
```

or:
```
[0x00000000]> ?*~reopen
| oo[?][+bcdnm]                reopen current file (see oo?) (reload in rw or debugger)
| oo              reopen current file
| oo+             reopen in read-write

```
?*~word # becomes:
? - help 
?* - all possible help lines 
?*~bananna - internal grep through all help lines searching word bananna

there is other ways You can do this, there is much more smarter peoples than I, that can place few words on that topic.

**Comment by lkz0ne** [comment]
That play of the 'pa' command was incredible and worked here.

**Comment by lasek0** [comment]
If my answer satisfy Your question please close this issue.
In general I suggest in such cases to try searching on stackoverflow.com first,
then try radare2 IRC channel.
I whish You have nice time sped on r2.

**Comment by lkz0ne** [comment]
Closed
