### ISSUE TITLE
dij inconsistent json output

### ISSUE THREAD

**Issue by Talos878** [radareorg/radare2#19617]
## Environment

```
Sun 23 Jan 2022 09:54:07 AM CST
radare2 5.5.5 27833 @ linux-x86-64 git.5.5.4
commit: ed2030b79e68986bf04f3a6279463ab989fe400f build: 2022-01-23__09:45:00
Linux x86_64

```

## Description
Esilsolve is breaking if you pass in the "-d" flag because it calls dij expecting output like this:

{"stopreason":"stopped","type":"stopped","signal":"none","signum":0,"sigstr":"unhandled","sigpid":0,"addr":0,"inbp":false,"baddr":94204625620992,"stopaddr":0,"pid":30863,"tid":30863,"uid":1000,"gid":1000,"exe":"/home/talos878/Documents/gets","cmdline":"./gets","cwd":"/home/talos878/Documents/"}

but instead the curly braces end early:

{"stopreason":"stopped"}
"type":"stopped","signal":"none","signum":0,"sigstr":"unhandled","sigpid":0,"addr":0,"inbp":false,"baddr":94204625620992,"stopaddr":0,"pid":30863,"tid":30863,"uid":1000,"gid":1000,"exe":"/home/talos878/Documents/gets","cmdline":"./gets","cwd":"/home/talos878/Documents/"

## Test

run esilsolve/examples/defcamp_r200/r200.py
or just run dij and examine the output in radare2

**Comment by Talos878** [comment]
https://github.com/radareorg/radare2/pull/19618

See here for pr for fix.

**Comment by trufae** [comment]
👍
