### ISSUE TITLE
Bugs with panel mode

### ISSUE THREAD

**Issue by Luxvoo** [radareorg/radare2#19664]
## Environment

```sh
Fri  4 Feb 16:30:30 CET 2022
radare2 5.6.0 0 @ linux-x86-64 git.
commit: 5.6.0 build: 2022-02-04__11:59:56
Linux x86_64
```

## Description

Bug 1: When in visual panels mode and one of the panels on the left is selected, the outline of the panel is extended to the part of the panel on the right: 
![image](https://user-images.githubusercontent.com/95533447/152557014-a5f48410-4dcf-4369-bb46-d0796e8a6ffd.png)

Bug 2: When in panel mode and having the decompiler open, then choosing a different decompiler like ghidra, the settings freeze and when you click off them, the settings are still there.
![image](https://user-images.githubusercontent.com/95533447/152557534-7087f953-df48-405f-b114-4e19dadf1eed.png)
As you can see it shows that the settings are closed but are clearly open.

Bug 3: When changing the decompiler, the decompiler panel changes (like the c code changes), but the command in brackets near the panel name doesn't change:
![image](https://user-images.githubusercontent.com/95533447/152558390-e2e675ee-5137-485e-a92d-261f04db0be3.png)
If I remember correctly it prob. should say pdg (for Ghidra decompiler).
## Test

Bug 1: Open panel mode and click on a panel on the left. The one on the right should be partially outlined.

Bug 2: Open panel mode, then open settings and change the decompiler (if you have only one decompiler install it with r2ps -ci r2ghidra).

Bug 3: Open panel mode, then open a decompiler panel, then open settings and change the decompiler (if you have only one decompiler install it with r2ps -ci r2ghidra). The command in the bracket shouldn't change even if you close the decompiler panel and open it again

**Comment by trufae** [comment]
Please test master. Both issues should be fixed now. Thanks for such a detailed report!
