### ISSUE TITLE
meson tries to execute 'shlr/zip/meson.build' even when building with system-wide shared zip library

### ISSUE THREAD

**Issue by xambroz** [radareorg/radare2#19681]
Hello,
when trying to build the release version 5.6.0 without access to internet, the messon build throws this error:
meson.build:427:0: ERROR: Non-existent build file 'shlr/zip/meson.build'

---- cut here ----
$ rpmbuild -bp radare2.spec 
setting SOURCE_DATE_EPOCH=1644364800
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.mhHFrg
+ umask 022
+ cd /home/mambroz/rpmbuild/BUILD
+ cd /home/mambroz/rpmbuild/BUILD
+ rm -rf radare2-5.6.0
+ /usr/bin/gzip -dc /home/mambroz/rpmbuild/SOURCES/radare2-5.6.0.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd radare2-5.6.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm -rf shlr/zip shlr/lz4
+ rm -f libr/hash/xxhash.c libr/hash/xxhash.h
+ rm -rf ./shlr/www/console.html ./shlr/www/d3 ./shlr/www/f ./shlr/www/favicon.ico ./shlr/www/graph ./shlr/www/index.html ./shlr/www/index.old.html ./shlr/www/log.html ./shlr/www/m ./shlr/www/old ./shlr/www/r2.svg ./shlr/www/rlogo.png ./shlr/www/t ./shlr/www/upload.html
+ echo 'The radare2 source usually comes with a pre-built version of the web-interface, but without the source code.'
+ echo 'This has been removed in the Fedora package to follow the Fedora Packaging Guidelines.'
+ echo 'Available under https://github.com/radare/radare2-webui'
+ RPM_EC=0
++ jobs -p
+ exit 0

$ ./install.sh
/home/mambroz/rpmbuild/BUILD/radare2-5.6.0
Warning: Your system-wide capstone is too old for me
[*] Configuring the build system ... configure-plugins: Loading ./plugins.cfg ..
configure-plugins: Generating libr/config.h
configure-plugins: Generating libr/asm/d/config.inc
configure-plugins: Generating libr/config.mk
SHARED: io.shm
STATIC: anal.6502 anal.6502_cs anal.8051 anal.amd29k anal.arc anal.arm_cs anal.arm_gnu anal.arm_v35 anal.avr anal.bf anal.chip8 anal.cr16 anal.cris anal.dalvik anal.ebc anal.evm_cs anal.gb anal.h8300 anal.hexagon anal.i4004 anal.i8080 anal.java anal.loongarch_gnu anal.m680x_cs anal.m68k_cs anal.malbolge anal.mcore anal.mips_cs anal.mips_gnu anal.msp430 anal.nios2 anal.null anal.or1k anal.pic anal.ppc_cs anal.ppc_gnu anal.pyc anal.riscv anal.riscv_cs anal.rsp anal.s390_cs anal.sh anal.snes anal.sparc_cs anal.sparc_gnu anal.tms320 anal.tricore anal.v810 anal.v850 anal.v850_np anal.vax anal.wasm anal.ws anal.x86_cs anal.xap anal.xcore_cs anal.xtensa anal.z80 asm.6502 asm.8051 asm.alpha asm.amd29k asm.arc asm.arm_as asm.arm_cs asm.arm_gnu asm.arm_v35 asm.arm_winedbg asm.avr asm.bf asm.cr16 asm.cris_gnu asm.dalvik asm.dcpu16 asm.gb asm.h8300 asm.hppa_gnu asm.i4004 asm.i8080 asm.java asm.jdh8 asm.lanai_gnu asm.lh5801 asm.lm32 asm.m680x_cs asm.m68k_gnu asm.malbolge asm.mcore asm.mcs96 asm.mips_cs asm.mips_gnu asm.nios2 asm.null asm.or1k asm.pdp11_gnu asm.pic asm.ppc_as asm.ppc_cs asm.ppc_gnu asm.propeller asm.pyc asm.riscv asm.riscv_cs asm.rsp asm.s390_cs asm.s390_gnu asm.sh asm.snes asm.sparc_cs asm.sparc_gnu asm.tms320 asm.tricore asm.v810 asm.v850 asm.v850_gnu asm.vasm asm.vax asm.ws asm.x86_as asm.x86_cs asm.x86_nasm asm.x86_nz asm.xap asm.xcore_cs asm.xtensa asm.z80 bin.any bin.art bin.avr bin.bf bin.bflt bin.bios bin.bootimg bin.cgc bin.coff bin.dex bin.dmp64 bin.dol bin.dyldcache bin.elf bin.elf64 bin.fs bin.hunk bin.java bin.le bin.mach0 bin.mach064 bin.mbn bin.mdmp bin.menuet bin.msx bin.mz bin.ne bin.nes bin.nin3ds bin.ninds bin.ningb bin.ningba bin.nro bin.nso bin.off bin.omf bin.p9 bin.pe bin.pe64 bin.pebble bin.prg bin.psxexe bin.pyc bin.qnx bin.sfc bin.smd bin.sms bin.symbols bin.te bin.tic bin.vsf bin.wad bin.wasm bin.xbe bin.xnu_kernelcache bin.z64 bin.zimg bin_ldr.ldr_linux bin_xtr.xtr_dyldcache bin_xtr.xtr_fatmach0 bin_xtr.xtr_pemixed bin_xtr.xtr_sep64 bp.arm bp.bf bp.mips bp.ppc bp.x86 core.a2f core.java core.sixref crypto.aes crypto.aes_cbc crypto.aes_wrap crypto.base64 crypto.base91 crypto.blowfish crypto.cps2 crypto.des crypto.punycode crypto.rc2 crypto.rc4 crypto.rc6 crypto.rol crypto.ror crypto.rot crypto.serpent crypto.xor debug.bf debug.bochs debug.esil debug.gdb debug.io debug.native debug.null debug.qnx debug.rap debug.winkd egg.exec egg.xor esil.dummy fs.ext2 fs.fat fs.fb fs.hfs fs.hfsplus fs.io fs.iso9660 fs.jfs fs.minix fs.ntfs fs.posix fs.r2 fs.reiserfs fs.sfs fs.tar fs.udf fs.ufs fs.xfs io.ar io.bfdbg io.bochs io.debug io.default io.fd io.gdb io.gprobe io.gzip io.http io.ihex io.isotp io.mach io.malloc io.mmap io.null io.procpid io.ptrace io.qnx io.r2k io.r2pipe io.r2web io.rap io.rbuf io.self io.shm io.socket io.sparse io.tcpslurp io.w32 io.w32dbg io.winedbg io.winkd io.zip lang.c lang.cpipe lang.pipe lang.rust lang.spp lang.v lang.vala lang.zig parse.6502_pseudo parse.arm_pseudo parse.att2intel parse.avr_pseudo parse.chip8_pseudo parse.dalvik_pseudo parse.m68k_pseudo parse.mips_pseudo parse.ppc_pseudo parse.riscv_pseudo parse.sh_pseudo parse.tms320_pseudo parse.v850_pseudo parse.wasm_pseudo parse.x86_pseudo parse.z80_pseudo
cp: './plugins.cfg' and 'plugins.cfg' are the same file
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr/local'
checking for c compiler... gcc
checking for dynamic library... required
checking for pkg-config... /usr/bin/pkg-config
checking for patch... /usr/bin/patch
checking for ar... /usr/bin/ar
checking for git... /usr/bin/git
checking for gperf... no
checking for libmagic ... yes
checking for libz ... yes
checking for libzip ... yes
checking for libxxhash ... yes
checking declaration of ADDR_NO_RANDOMIZE in sys/personality.h... yes
checking declaration of __GLIBC__ in features.h... yes
checking function arc4random_uniform() in c... no
checking function explicit_bzero() in c... yes
checking function explicit_memset() in c... no
checking function clock_nanosleep() in c... yes
checking function sigaction() in c... yes
checking function clock_gettime() in c... yes
checking cflags  -std=gnu99... yes
checking for libssl ... yes
checking pkg-config flags for openssl... yes
checking version of library libuv >= 1.0.0... ok
checking pkg-config flags for libuv... yes
creating ./config-user.mk
creating libr/include/r_userconf.h
creating pkgcfg/r_io.pc
creating pkgcfg/r_magic.pc
creating pkgcfg/r_asm.pc
creating pkgcfg/r_bin.pc
creating pkgcfg/r_anal.pc
creating pkgcfg/r_hash.pc
creating pkgcfg/r_cons.pc
creating pkgcfg/r_core.pc
creating pkgcfg/r_lang.pc
creating pkgcfg/r_socket.pc
creating pkgcfg/r_debug.pc
creating pkgcfg/r_reg.pc
creating pkgcfg/r_config.pc
creating pkgcfg/r_flag.pc
creating pkgcfg/r_syscall.pc
creating pkgcfg/r_util.pc
creating pkgcfg/r_search.pc
creating pkgcfg/r_bp.pc
creating pkgcfg/r_parse.pc
creating pkgcfg/r_fs.pc
creating pkgcfg/r_egg.pc
creating pkgcfg/r_crypto.pc
cleaning temporally files... done

Final report:
 - R_CHECKS_LEVEL = 2
 - PREFIX = /usr/local
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - HAVE_LIBUV = 1
 - USE_CAPSTONE = 0
 - HAVE_PTRACE = 1
 - USE_PTRACE_WRAP = 1
 - HAVE_FORK = 1
 - VERSION = 5.6.0
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - USE_LIB_XXHASH = 0
 - DEBUGGER = 1
 - CC = gcc
 - USERCC = gcc
 - HAVE_ARC4RANDOM_UNIFORM = 0
 - PKGCONFIG = /usr/bin/pkg-config
 - HAVE_GPERF = 0
 - HAVE_EXPLICIT_BZERO = 1
 - HAVE_EXPLICIT_MEMSET = 0
 - WANT_DYLINK = 1
 - USEROSTYPE = gnulinux
 - LIBVERSION = 5.6.0
 - BUILD = x86_64-unknown-linux-gnu
 - HOST = x86_64-unknown-linux-gnu
 - TARGET = x86_64-unknown-linux-gnu
 - CFLAGS = (null)
 - LDFLAGS = (null)
[*] Checking out capstone... ^C

$ rpmbuild -ba radare2.spec 
setting SOURCE_DATE_EPOCH=1644364800
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.GRDZdT
+ umask 022
+ cd /home/mambroz/rpmbuild/BUILD
+ cd /home/mambroz/rpmbuild/BUILD
+ rm -rf radare2-5.6.0
+ /usr/bin/gzip -dc /home/mambroz/rpmbuild/SOURCES/radare2-5.6.0.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd radare2-5.6.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm -rf shlr/zip shlr/lz4
+ rm -f libr/hash/xxhash.c libr/hash/xxhash.h
+ rm -rf ./shlr/www/console.html ./shlr/www/d3 ./shlr/www/f ./shlr/www/favicon.ico ./shlr/www/graph ./shlr/www/index.html ./shlr/www/index.old.html ./shlr/www/log.html ./shlr/www/m ./shlr/www/old ./shlr/www/r2.svg ./shlr/www/rlogo.png ./shlr/www/t ./shlr/www/upload.html
+ echo 'The radare2 source usually comes with a pre-built version of the web-interface, but without the source code.'
+ echo 'This has been removed in the Fedora package to follow the Fedora Packaging Guidelines.'
+ echo 'Available under https://github.com/radare/radare2-webui'
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.oNEk1j
+ umask 022
+ cd /home/mambroz/rpmbuild/BUILD
+ cd radare2-5.6.0
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . redhat-linux-build -Duse_sys_magic=true -Duse_sys_zip=true -Duse_sys_zlib=true -Duse_sys_lz4=true -Duse_sys_xxhash=true -Duse_sys_openssl=true -Duse_libuv=true -Duse_sys_capstone=true -Denable_tests=false -Denable_r2r=false
The Meson build system
Version: 0.59.4
Source dir: /home/mambroz/rpmbuild/BUILD/radare2-5.6.0
Build dir: /home/mambroz/rpmbuild/BUILD/radare2-5.6.0/redhat-linux-build
Build type: native build
Project name: radare2
Project version: 5.6.0
C compiler for the host machine: gcc (gcc 11.2.1 "gcc (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)")
C linker for the host machine: gcc ld.bfd 2.37-10
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Message: r2 lib version: 5.6.0
Library dl found: YES
Run-time dependency threads found: YES
Library util found: YES
Library m found: YES
Configuring config.h using configuration
Library magic found: YES
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libxxhash found: YES 0.8.1
Message: Using system xxhash library
Run-time dependency libuv found: YES 1.43.0
Message: Using libuv
Message: HAVE_PTRACE: true
Message: USE_PTRACE_WRAP: true
Message: R2_CHECKS_LEVEL: 2
Header <sys/personality.h> has symbol "ADDR_NO_RANDOMIZE" : YES 
Checking for function "clock_gettime" : YES 
Checking for function "arc4random_uniform" : NO 
Checking for function "explicit_bzero" : YES 
Checking for function "explicit_memset" : NO 
Checking for function "clock_nanosleep" : YES 
Checking for function "clock_gettime" : YES (cached)
Checking for function "sigaction" : YES 
Configuring r_userconf.h using configuration
Configuring r_version.h using configuration
Configuring libr.pc using configuration

meson.build:427:0: ERROR: Non-existent build file 'shlr/zip/meson.build'

A full log can be found at /home/mambroz/rpmbuild/BUILD/radare2-5.6.0/redhat-linux-build/meson-logs/meson-log.txt
error: Bad exit status from /var/tmp/rpm-tmp.oNEk1j (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.oNEk1j (%build)

Best regards
Michal Ambroz

**Comment by eli-schwartz** [comment]
From your rpm spec, it logs:

> rm -rf shlr/zip shlr/lz4

From the build, it logs:

> meson.build:427:0: ERROR: Non-existent build file 'shlr/zip/meson.build'

This is not a bug in the radare2 project, you have an utterly broken spec file. Probably you tried to update Fedora's package by bumping the version number alone, which is NOT at all guaranteed to work when Fedora extensively patches the project.

You will need to do a more thorough update yourself.

P.S. The Fedora modifications seem unnecessary, given the option `-Duse_sys_zlib=true` is passed that bundled source code can never be used anyway whether it is deleted or not.

**Comment by xambroz** [comment]
This build error was introduced between radare2-5.5.4 and radare2-5.6.0

> From your rpm spec, it logs:
> > rm -rf shlr/zip shlr/lz4
> P.S. The Fedora modifications seem unnecessary, given the option `-Duse_sys_zlib=true` is passed that bundled source code can never be used anyway whether it is deleted or not.

By Fedora packaging rules we are mandated to unbundle all libraries which are provided by system.
Removing the directories with embedded code is the recommended way to ensure it won't be used accidentally in the compilation. That is the reason why we delete the zip and lz4 embedded directories - this approach was working till version 5.5.4
https://koji.fedoraproject.org/koji/packageinfo?packageID=27515

Hence we are running messon with " -Duse_sys_magic=true -Duse_sys_zip=true -Duse_sys_zlib=true -Duse_sys_lz4=true -Duse_sys_xxhash=true -Duse_sys_openssl=true -Duse_libuv=true -Duse_sys_capstone=true "
Unfortunately these define values are in version 5.6.0 not ensuring that the build of the embedded libraries would not be executed.

> This is not a bug in the radare2 project, you have an utterly broken spec file. 
Sorry I forgot to introduce myself again ... I am one of the 2 Fedora packagers taking care of this package ;).
https://src.fedoraproject.org/rpms/radare2

> Probably you tried to update Fedora's package by bumping the version number alone,
> which is NOT at all guaranteed to work when Fedora extensively patches the project.
No this is not true ... currently there are no additional patches in fedora package.
All patches we had were considered useful for others as well, and are now upstream in radare2.
https://src.fedoraproject.org/rpms/radare2/blob/rawhide/f/radare2.spec

**Comment by xambroz** [comment]
> There's dist/rpm which would be worth updating.
> I'm not a big fan of rpm but i understand it would be useful to also ship an rpm in the ci. 
> Any recommendations on this? Is there any baseline to cover most rpm based distros?
Hi Pancake - the mentioned Fedora package is aimed to build well also on the current RHEL systems.
https://src.fedoraproject.org/rpms/radare2/blob/rawhide/f/radare2.spec

**Comment by xambroz** [comment]
Seems that the embedded zip build stuff was between 5.5.4 and 5.6.0 moved from 
shlr/meson.build to shlr/zip/meson.build

OK ... I will try to not purge whole directory but just things around.

Please do you plan to do the same modular change for lz4?

**Comment by trufae** [comment]
Im in the process to write my fork of the lz4 library because i found a couple of usecases that make this library not suitable for r2 purposes.

will be great if we could test fedora way of packaging r2 in our CI. Could you submit an updated spec to reproduce so i can fix the mesons and ensure nothing breaks in the future?

**Comment by xambroz** [comment]
I will try to prepare pull request in that sense.
In your CI package you want to be using the embedded libraries (ask you have it in git by default) or system wide libraries (as it is mandated by Fedora/Redhat) ?

**Comment by trufae** [comment]
I think the way to go is to check this using the proper fedora environment and linking to system libraries. This way fedora can pick the spec from radare and not viceversa. Less work for maintainers and more stability in the build system :)

**Comment by eli-schwartz** [comment]
> This build error was introduced between radare2-5.5.4 and radare2-5.6.0

This is a deceptive comment. There is no "build error", there is "a fedora-specific error in the unbundling code".

But also: if you are reporting this on behalf of Fedora, I am slightly curious why your report consisted of two pieces of information:
- the statement, offered as relevant information, that it occurred "without access to internet"
- the debug log from rpm

:)


> By Fedora packaging rules we are mandated to unbundle all libraries which are provided by system.
> Removing the directories with embedded code is the recommended way to ensure it won't be used accidentally in the compilation. That is the reason why we delete the zip and lz4 embedded directories - this approach was working till version 5.5.4

The obvious way to work within the constraints of both Fedora's "preferred" mechanism of deleting unused files, and the Meson build system's requirement that you do not delete large swathes of the build description, would be to delete the *.c and *.h files in that directory, but not delete the directory itself. Leave the `meson.build` file intact.

> No this is not true ... currently there are no additional patches in fedora package.

I would call deleting directories and files an extensive patching process. The fact that it doesn't specifically use files named .patch and filtered through a program called `/usr/bin/patch` is not important.

**Comment by xambroz** [comment]
> * the statement, offered as relevant information, that it occurred "without access to internet"
Fedora builds are occuring without access to internet.
I was wrongly guessing this could be related to some ad-hoc pulling/updating of the source code of the embedded libraries.
In the past there were some issues like that.

> * the debug log from rpm
When reporting to build issue I was considering that relevant.

> The obvious way to work within the constraints of both Fedora's "preferred" mechanism of deleting unused files,
> and the Meson build system's requirement that you do not delete large swathes of the build description,
> would be to delete the *.c and *.h files in that directory, but not delete the directory itself. Leave the `meson.build` file intact.
I appologize, I am still quite new to the meson build system. It took me some time to understand that some stanzas moved from shlr/meson.build to shlr/zip/meson.build.

What you propose is what I do now:
Instead of 
rm -rf shlr/zip shlr/lz4

I do now dirs one directory deeper:
rm -rf shlr/zip/{zip,zlib,include} shlr/lz4

**Comment by radare** [comment]
I dont think the last r2 from git supports linking to system lz4, but ill handle it before today's 5.6 release, thakns for the headsup on this topic, but still removing folders is not the way to go imho. there should be a configure and meson options to do that, the same way its done with all the other external libraries in r2

**Comment by xambroz** [comment]
> but still removing folders is not the way to go imho.

Even if I would agree on this (and I don't as I was seeing some cases where option was not enough), as Fedora packager I am bound to the rules of Fedora/RedHat packaging guidelines:
https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling
"All packages whose upstreams allow them to be built against system libraries MUST be built against system libraries. In this case, bundled libraries (and/or their source code) MUST be explicitly deleted during %prep. "

Please note I am not pushing this to upstream and I understand you might have reasons to bundle.

For completeness - Debian rules are not so strict about this and they do not mandate the removal of the bundled folders.
They mandate to unbundle as well, but working of the policy is not prescribing how to do that:
https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

**Comment by xambroz** [comment]
Issue closed. Build code moved from shlr/meson.build to shlr/zip/meson.build which needed to be reflected in the Fedora package and its purging of embedded libraries.
