### ISSUE TITLE
LZ4 bundled code unconditionally referenced from libr/util/meson.build

### ISSUE THREAD

**Issue by xambroz** [radareorg/radare2#19711]
## Environment
R2 current snapshot - 5a7ffe4c0a71794fbb0b945d52065c7c11d1eec2

## Description
The bundled LZ4 code is unconditionally referenced from libr/util/meson.build even though the -D use_sys_lz4=true is used for build.

## Test
git clone https://github.com/radareorg/radare2
cd radare2
git checkout 5a7ffe4c0a71794fbb0b945d52065c7c11d1eec2
rm -rf shlr/lz4
/usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . redhat-linux-build -Duse_sys_lz4=true 

It throws this error:
libr/util/meson.build:113:0: ERROR: File ../../shlr/lz4/lz4.c does not exist.

**Comment by trufae** [comment]
Please try again. but dont remove shlr/lz4 which is now containing a meson.build

https://github.com/radareorg/radare2/pull/19715

**Comment by trufae** [comment]
Lets consider it fixed until someone tries that
