### ISSUE TITLE
meson build Unknown variable "libr2lz4".

### ISSUE THREAD

**Issue by xambroz** [radareorg/radare2#19726]
## Environment

release tarball radare2-5.6.2.tar.gz

## Description

Hello,
In release tarball 5.6.2, when using the meson AND trying to use the system provided lz4 library, the build complains that there is unknown variable "libr2lz4" used in libr/util/meson.build
The defitinion seems to be provided by shlr/lz4/meson.build, but it is probably not loaded at that time.
## Test

+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . redhat-linux-build -Duse_sys_magic=true -Duse_sys_zip=true -Duse_sys_zlib=true -Duse_sys_lz4=true -Duse_sys_xxhash=true -Duse_sys_openssl=true -Duse_libuv=true -Duse_sys_capstone=true -Denable_tests=false -Denable_r2r=false
The Meson build system
Version: 0.59.4
Source dir: /home/mambroz/rpmbuild/BUILD/radare2-5.6.2
Build dir: /home/mambroz/rpmbuild/BUILD/radare2-5.6.2/redhat-linux-build
Build type: native build
Project name: radare2
Project version: 5.6.2
C compiler for the host machine: gcc (gcc 11.2.1 "gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)")
C linker for the host machine: gcc ld.bfd 2.37-10
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Message: r2 lib version: 5.6.2
Library dl found: YES
Run-time dependency threads found: YES
Library util found: YES
Library m found: YES
Configuring config.h using configuration
Library magic found: YES
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libxxhash found: YES 0.8.1
Message: Using system xxhash library
Run-time dependency libuv found: YES 1.43.0
Message: Using libuv
Message: HAVE_PTRACE: true
Message: USE_PTRACE_WRAP: true
Message: R2_CHECKS_LEVEL: 2
Header <sys/personality.h> has symbol "ADDR_NO_RANDOMIZE" : YES 
Checking for function "clock_gettime" : YES 
Checking for function "arc4random_uniform" : NO 
Checking for function "explicit_bzero" : YES 
Checking for function "explicit_memset" : NO 
Checking for function "clock_nanosleep" : YES 
Checking for function "clock_gettime" : YES (cached)
Checking for function "sigaction" : YES 
Configuring r_userconf.h using configuration
Configuring r_version.h using configuration
Configuring libr.pc using configuration
Run-time dependency zlib found: YES 1.2.11
Message: Use system-provided zlib library
Run-time dependency libzip found: YES 1.8.0
Message: Use system-provided zip library
Run-time dependency liblz4 found: YES 1.9.3
Message: Using system-provided lz4 library

libr/util/meson.build:101:2: ERROR: Unknown variable "libr2lz4".

**Comment by trufae** [comment]
sorry for the delay i was busy having covid. im fixing this now. meson is a disaster as a build system :facepalm: but guess most of those problems are tied to the horrendous python ecosystem. 

I just fixed this in master. Can you try from git? I'll release 5.6.4 next sunday

thanks for reporting!

**Comment by xambroz** [comment]
Hope you are doing well?

Unfortunateli it is not fixing the build issue. Even with the most recent git snapshot it is failing the same way:


```
$ rpmbuild -ba radare2.git.spec 
setting SOURCE_DATE_EPOCH=1644796800
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.DwoeKS
+ umask 022
+ cd /home/mambroz/rpmbuild/BUILD
+ cd /home/mambroz/rpmbuild/BUILD
+ rm -rf radare2-3b774834dcc4c4d1cf78e4675c05589e77d8f969
+ /usr/bin/unzip -qq /home/mambroz/rpmbuild/SOURCES/radare2-5.6.3-3b77483.zip
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd radare2-3b774834dcc4c4d1cf78e4675c05589e77d8f969
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/mambroz/rpmbuild/SOURCES/radare2-5.6.0-dec99.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch -f
+ sed -i -e 's|5.6.3-git|5.6.3|g;' configure configure.acr
+ rm -rf shlr/zip/zip shlr/zip/zlib shlr/zip/include
+ rm -f libr/hash/xxhash.c libr/hash/xxhash.h
+ rm -rf ./shlr/www/console.html ./shlr/www/d3 ./shlr/www/f ./shlr/www/favicon.ico ./shlr/www/graph ./shlr/www/index.html ./shlr/www/index.old.html ./shlr/www/log.html ./shlr/www/m ./shlr/www/old ./shlr/www/r2.svg ./shlr/www/rlogo.png ./shlr/www/t ./shlr/www/upload.html
+ echo 'The radare2 source usually comes with a pre-built version of the web-interface, but without the source code.'
+ echo 'This has been removed in the Fedora package to follow the Fedora Packaging Guidelines.'
+ echo 'Available under https://github.com/radare/radare2-webui'
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.iFsX7e
+ umask 022
+ cd /home/mambroz/rpmbuild/BUILD
+ cd radare2-3b774834dcc4c4d1cf78e4675c05589e77d8f969
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . redhat-linux-build -Duse_sys_magic=true -Duse_sys_zip=true -Duse_sys_zlib=true -Duse_sys_lz4=true -Duse_sys_xxhash=true -Duse_sys_openssl=true -Duse_libuv=true -Duse_sys_capstone=true -Denable_tests=false -Denable_r2r=false -Dwant_threads=false
The Meson build system
Version: 0.59.4
Source dir: /home/mambroz/rpmbuild/BUILD/radare2-3b774834dcc4c4d1cf78e4675c05589e77d8f969
Build dir: /home/mambroz/rpmbuild/BUILD/radare2-3b774834dcc4c4d1cf78e4675c05589e77d8f969/redhat-linux-build
Build type: native build
Project name: radare2
Project version: 5.6.3
C compiler for the host machine: gcc (gcc 11.2.1 "gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)")
C linker for the host machine: gcc ld.bfd 2.37-10
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Program git found: YES (/usr/bin/git)
Message: r2 lib version: 5.6.3
Library dl found: YES
Run-time dependency threads found: YES
Library util found: YES
Library m found: YES
Configuring config.h using configuration
Library magic found: YES
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libxxhash found: YES 0.8.1
Message: Using system xxhash library
Run-time dependency libuv found: YES 1.43.0
Message: Using libuv
Message: HAVE_PTRACE: true
Message: USE_PTRACE_WRAP: true
Message: R2_CHECKS_LEVEL: 2
Header <sys/personality.h> has symbol "ADDR_NO_RANDOMIZE" : YES 
Checking for function "clock_gettime" : YES 
Checking for function "arc4random_uniform" : NO 
Checking for function "explicit_bzero" : YES 
Checking for function "explicit_memset" : NO 
Checking for function "clock_nanosleep" : YES 
Checking for function "clock_gettime" : YES (cached)
Checking for function "sigaction" : YES 
Configuring r_userconf.h using configuration
Configuring r_version.h using configuration
Configuring libr.pc using configuration
Run-time dependency zlib found: YES 1.2.11
Message: Use system-provided zlib library
Run-time dependency libzip found: YES 1.8.0
Message: Use system-provided zip library
Run-time dependency liblz4 found: YES 1.9.3
Message: Using system-provided lz4 library

libr/util/meson.build:102:2: ERROR: Unknown variable "libr2lz4".

A full log can be found at /home/mambroz/rpmbuild/BUILD/radare2-3b774834dcc4c4d1cf78e4675c05589e77d8f969/redhat-linux-build/meson-logs/meson-log.txt
error: Bad exit status from /var/tmp/rpm-tmp.iFsX7e (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.iFsX7e (%build)
```

**Comment by xambroz** [comment]
I believe the condition is negated then it should be.

What is in shlr/lz4/meson.build  kinda makes sense:

```
lz4_dep = dependency('liblz4', required: false)
if not lz4_dep.found() or not get_option('use_sys_lz4')
  message('Using bundled lz4')
  lz4_files = [
    'lz4.c',
  ]

  lz4_inc = [platform_inc, include_directories('.')]

  libr2lz4 = static_library('r2lz4', lz4_files,
    include_directories: lz4_inc,
    implicit_include_directories: false
  )

  lz4_dep = declare_dependency(
    link_with: libr2lz4,
    include_directories: lz4_inc
  )
else
  message('Using system-provided lz4 library')
endif
```

I read it as:
- check for liblz4 
- if liblz4 is not available or if I do not want to use the system one, then declare your own libr2lz4="r2lz4" and use it for lz4_dep as dependency

However what is in libr/util/meson.build seems to be negated and hence not defined:
```
if lz4_dep.found() and get_option('use_sys_lz4')
  # r_util_deps += lz4_dep
  r_util_deps += declare_dependency(
    link_with: libr2lz4,
    include_directories: lz4_inc
  )
else
  r_util_sources += '../../shlr/lz4/lz4.c'
endif
```

I dead as :
- if we have lz4 library and we want to use the system library, 
- then use the embedded libr2lz4

**Comment by trufae** [comment]
it's now fixed :) just tested in local and confirmed the library gets linked to the system lz4

**Comment by xambroz** [comment]
OK works with 5.6.4:

$ ldd /usr/lib64/libr_util.so.5.6.4
	linux-vdso.so.1 (0x00007ffe2cfc6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2972a29000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f2972a05000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f29729eb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f29727e1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2972c45000)

**Comment by trufae** [comment]
thanks for confirming!
