### ISSUE TITLE
Specifying rarun2 parameters dynamically 

### ISSUE THREAD

**Issue by thamugadi** [radareorg/radare2#19768]
## Description

Not being able to reload stdin from a second file makes it painful to debug some programs that require several inputs, especially those where putting a backline isn't a solution (using directly the read syscall).

Would it be possible to be able to reload parameters of rarun2 during the debug?

**Comment by trufae** [comment]
No. Rarun is only used to spawn proframs. When the target is running theres nothing you can do with it. You can check the dd command which allows to manipulate the file descriptors at runtime. But thats a different story

**Comment by thamugadi** [comment]
Unfortunately I can't find a usage example where `dd` would be able to achieve similar result, `dd file` gives the following output on my machine `radare2 5.6.4 27790 @ linux-x86-64 git.5.5.4`
```
Cannot assemble 'mov rax, file' at line 71
fail assembling
r_egg_assemble: invalid assembly
dx 
```

**Comment by Lazula** [comment]
Regarding the error message, see #19795

**Comment by trufae** [comment]
imho this is a task for dd not rarun2. closing because rarun is only designed to work before the child is spawned
