### ISSUE TITLE
Error creating zignatures for function(s) in Mach-O binary

### ISSUE THREAD

**Issue by whoami-defnotme** [radareorg/radare2#19805]
## Environment

```sh
Wed Mar  9 15:38:11 +08 2022
radare2 5.6.5 28988 @ darwin-x86-64 git.5.5.0
commit: 6a4dd942f853e77ddf7fab1ddafbc4f44a1cf3ba build: 2022-03-09__13:55:36
Darwin x86_64
```

## Description

I'm observing failures when attempting to create zignatures for a Mach-O binary. It's unclear if there's an issue with the function or if this is an r2 bug.

## Test

```
# First, file hashes
[0x100003790]> it
md5 95d76db3a8cd1bb4e2a1bdfeb54f35fb
sha1 e7204d84b60ef5a03d51680c2f0c568684a4addd
sha256 1e19e76af67ffc7249c99ef66c28f4425f79e4f97d4976bb093fda2d0fee1a2b

# Try to create the zig for the target function
[0x100003790]> zaf "method.OnePasswordNativeMessageHost.OPNMXPCConnection.setXpcConnection:" test

# Then, try to view all zigs as this was the only one created.
[0x100003790]> z
Invalid types: ```void method.OnePasswordNativeMessageHost.OPNMXPCConnection.setXpcConnection: (int64_t arg1, void *instance)``` in signatuer for zign|*|test
error: cannot deserialize zign
```

**Comment by swoops** [comment]
@whoami-defnotme if you are trying to get some work done, you can just remove `:` from the function name before creating the signature and it should work. I will see about getting it to work otherwise.

**Comment by whoami-defnotme** [comment]
Oh sweet as - yea, suspected it might have been a sanitization issue. I can replace semi-colons with underscores and keep going.

**Comment by swoops** [comment]
#19807 should fix it completely, so I am going to close. Let us know if anything else goes bad @whoami-defnotme
