### ISSUE TITLE
Disassembly problem

### ISSUE THREAD

**Issue by tower111** [radareorg/radare2#19813]
## Environment

When I use to analyze a program for an arm architecture, a function is split

![image](https://user-images.githubusercontent.com/31761342/158000573-e82d720c-f42b-447e-bb1f-c9bdddcc81c8.png)

Shown in ida as
![image](https://user-images.githubusercontent.com/31761342/158000620-786e718b-ced9-47d0-be8a-2ee378317eaf.png)

The corresponding bytecode in ida has been modified, I don't know if it is because of radare or ida
![image](https://user-images.githubusercontent.com/31761342/158000636-578e6a7f-8c07-4622-99a6-393b747609bf.png)

**Comment by trufae** [comment]
Can you share the binary or at least the hexpair array to recreate this function for me to test?

**Comment by tower111** [comment]
> 

Sent to your email, thanks

**Comment by trufae** [comment]
i cant reproduce. are you using the latest r2 from git?

**Comment by trufae** [comment]
Ping?

**Comment by trufae** [comment]
I assume the issue you are experiencing is because `aaaa` runs `aav` under the hood and this causes the fnuction to split. But as i said i cant repro and i would appreciate some feedback

**Comment by tower111** [comment]
Thanks,
I tested the latest version now, there is no problem, it should be the previous version is too low. It was previously installed using Ubuntu16 apt.

thank you very much.
