### ISSUE TITLE
String search problem

### ISSUE THREAD

**Issue by a1gx** [radareorg/radare2#19815]
## Environment
Ubuntu18.04

## Description
Some strings are not recognized properly and only address is displayed.
<img width="904" alt="image" src="https://user-images.githubusercontent.com/49387206/158054688-6db5a418-3913-4c99-ac3c-b7f8d411f41e.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/49387206/158054708-a6a9984b-f927-4b29-83fd-574656dde42a.png">

**Comment by trufae** [comment]
This seems like a bug in r2ghidra, also, without a file to test or without knowing the version of r2 and r2g is hard to say. If you are using r2g please fill the ticket in the right repo.

**Comment by a1gx** [comment]
I think this is radare2's problem, because when I use iz to search for the string, I don't find the string I want, but I do with strings
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/49387206/158063283-913777f8-b203-4a35-a2a3-3a25d360a4b9.png">

**Comment by a1gx** [comment]
Version information: radare2 5.6.5 3 @ linux-x86-64 git.
commit: 3fc98d4e7f5381352d6c1de2d0f40f0f690f1c15

**Comment by trufae** [comment]
Thats weird. Can you share the binary?

**Comment by a1gx** [comment]
This is the binary I used.
[MyDriver1.zip](https://github.com/radareorg/radare2/files/8239827/MyDriver1.zip)

**Comment by Lazula** [comment]
Looks like `iz` only searches `.rdata` while the string at `0x00401262` is in `.text`, so you need to use `izz`.

**Comment by a1gx** [comment]
Thanks, it solved my problem.

**Comment by trufae** [comment]
I assume that setting anal.strings would solve the problem. Maybe its time to enable it by default when we switch to 5.7?
