### ISSUE TITLE
Wrong order of arguments of C function

### ISSUE THREAD

**Issue by hehaoqian** [radareorg/radare2#19876]
## Environment

```
-msSat Mar 26 20:53:36 CST 2022

radare2 5.6.7 27661 @ linux-x86-64 git.5.6.6
commit: 7a310d863f633e3bb514015858edd714e8c9414e build: 2022-03-26__20:54:3

Linux x86_64
```

## Description

See also https://github.com/wargio/r2dec-js/issues/271

The original function

```
int sub(int a, int b){
   return a - b;
}
```

Compiled with gcc test.c -c -o test.o

The disassembly:

```
endbr64                         
push rbp          
mov rbp, rsp          
mov dword [rbp - 4], edi       
mov dword [rbp - 8], esi       
mov eax, dword [rbp - 4]         
sub eax, dword [rbp - 8]         
pop rbp                          
ret
```

The order of arguments printed in `afv` is wrong ( and the json output)

```
var int64_t var_8h @ rbp-0x8
var int64_t var_4h @ rbp-0x4
arg int64_t arg2 @ rsi
arg int64_t arg1 @ rdi
```

I suppose they should be
```
arg int64_t arg1 @ rdi
arg int64_t arg2 @ rsi
var int64_t var_4h @ rbp-0x4
var int64_t var_8h @ rbp-0x8
```

**Comment by trufae** [comment]
Can you provide the binary? not all gcc are made equal. the order of the vars/args is not about reversing the current list, but instead, just take into account the calling convention associated and honor it before listing/printing the json.

I'll handle that

**Comment by hehaoqian** [comment]
@trufae 
[test.zip](https://github.com/radareorg/radare2/files/8408197/test.zip)

**Comment by trufae** [comment]
Thanks!

**Comment by trufae** [comment]
Fixed in a PR.. waiting for the CI to merge! thanks for reporting.
