### ISSUE TITLE
relro entry missing in JSON output of "iIj"

### ISSUE THREAD

**Issue by cpuinfo** [radareorg/radare2#19964]
## Environment

date
Sun 17 Apr 2022 02:15:05 PM IST
r2 -v
radare2 5.4.2 0 @ linux-x86-64 git.5.4.2
commit: 5.4.2 build: 2021-09-26__11:56:56
uname -ms
Linux x86_64

## Description
For two different binaries, I fired the "iIj" command after "aaa". One of them showed a missing "relro" entry as shown below. Is it not supposed to be there as it becomes easy to process the JSON outcome in a standardized way. Expected to have a **"relro": ""** blank entry atleast. Also no idea on why its not able to extract the relro for the binary.

## Test
Attached zip format of the ELF binary samples
[binary without relro](https://github.com/radareorg/radare2/files/8501276/top.zip)
[binary with relro](https://github.com/radareorg/radare2/files/8501277/netifd.zip)

\> aaa
\> iIj

_**Output of `ilj` from two different binaries**_

![Selection_957](https://user-images.githubusercontent.com/69376519/163708340-e26822f8-1400-4246-98ec-5e1f8c3cdb37.png)

**Comment by trufae** [comment]
thats because this binary doesnt have relro information?

also, `aaa` is not necessary, all this info is in the binary headers, no code analysis required

<img width="320" alt="Screenshot 2022-04-17 at 18 20 42" src="https://user-images.githubusercontent.com/6431515/163723317-abfd2769-2d21-4f21-8202-983a7203d0b8.png">

**Comment by Lazula** [comment]
@trufae I believe the salient part is this:
> Expected to have a "relro": "" blank entry atleast.

**Comment by trufae** [comment]
Imho it will be more correct to say relro:no. But this is just an elf specific thing. It doesnt exist in any other file format. So in case the value is not ther its not printed.

do we want to define json schemas for every command now?

**Comment by trufae** [comment]
My only concern here is that relro only makes sense on elf. So i guess the fix for this relro:no must be done in the elf plugin instead of the json printer. Anyone?

**Comment by trufae** [comment]
sorry for the delay, i just had 5 spare minutes to check this issue, and pushed a pr fixing it.
