### ISSUE TITLE
ESIL Threads

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#19977]
A thread must have an iobank associated and also an RRegArena containing a snapshot of the registers, the memory is shared. memory locking mechanisms should be implemented at ESIL level.

The debug esil plugin could handle this in this way. And it can be also use to implement fork() syscall using r2 commands.

**Comment by trufae** [comment]
Related to https://github.com/radareorg/radare2/issues/19086

**Comment by condret** [comment]
I wouldn't approach this until RArch is done

**Comment by trufae** [comment]
Done in 5.8.0. see apt command
