### ISSUE TITLE
Support for Expert Witness format

### ISSUE THREAD

**Issue by dgmcdona** [radareorg/radare2#20000]
## Description
It would be great to see support for opening Expert Witness Format (EWF) bitstreams. For instance, if I had an E01 file containing an NTFS volume, I could open the file and mount the volume or view the bytes as I normally would in radare2.

**Comment by trufae** [comment]
Its already supported. You need to compile r2 with libewf which is an external dependency

**Comment by trufae** [comment]
https://github.com/radareorg/radare2-extras/blob/master/libr/io/p/io_ewf.c

Its in extras you can install it via r2pm
