### ISSUE TITLE
Current Pebble support

### ISSUE THREAD

**Issue by clach04** [radareorg/radare2#20002]
## Environment

Tried with a couple of different versions:

    radare2 5.6.8 1 @ windows-x86-64 git.5.6.8
    commit: d94100d386e8bc349b500af309e1880447a1e9da build: Mon 04/18/2022__23:23:07.06

    radare2 5.3.1 1 @ windows-x86-64 git.5.3.1
    commit: d894f967e857a1cfa84144eb4bc0bdc87c540eee build: Tue 06/15/2021__10:11:04.68

    ver
    Microsoft Windows [Version 10.0.19042.1586]

## Description

r2 opens up pebble bin (from https://github.com/radareorg/radare2-testbins/blob/master/pebble/pebble-app.bin) without error and displays `info` but nothing else. `pdc` returns error, and attempting to use `iaito` shows nothing in Graph. Does show something in dissasembly

## Test

Get https://github.com/radareorg/radare2-testbins/blob/master/pebble/pebble-app.bin

    C:\Programs\radare2-5.6.8-w64\bin>r2 -v
    radare2 5.6.8 1 @ windows-x86-64 git.5.6.8
    commit: d94100d386e8bc349b500af309e1880447a1e9da build: Mon 04/18/2022__23:23:07.06

    C:\Programs\radare2-5.6.8-w64\bin>r2 C:\Programs\cutter-v2.0.5-x64.Windows\bins_to_explore\pebble-app.bin
     -- I love gradients.
    [0x00000098]> aaaa
    [af: Cannot find function at 0x00000098. and entry0 (aa)
    [x] Analyze all flags starting with sym. and entry0 (aa)
    [x] Analyze all functions arguments/locals
    [x] Analyze function calls (aac)
    [x] Analyze len bytes of instructions for references (aar)
    [x] Finding and parsing C++ vtables (avrr)
    [x] Finding xrefs in noncode section (e anal.in=io.maps.x)
    [x] Analyze value pointers (aav)
    [x] Emulate functions to find computed references (aaef)
    [x] Type matching analysis for all functions (aaft)
    [x] Propagate noreturn information (aanr)
    [x] Finding function preludes
    [x] Enable constraint types analysis for variables
    [0x00000098]> pdc
    Cannot find function in 0x00000098

I'm not clear if Pebble has complete support. I'm not sure if this is related to issue #6647

This might be user error but I'm able to see something in the arm sample https://github.com/radareorg/radare2-testbins/blob/master/arm/elf/hello_world (unlike the pebble sample).

**Comment by clach04** [comment]
Pebble support refs:

* https://radareorg.github.io/blog/posts/radare-0-9-9/
* https://github.com/radareorg/radare2/commit/e35d55e18ab2bfe1d38b4a9398222531982f070a

**Comment by trufae** [comment]
the function is not analyzed because the maps dont have exec perms. let me fix this now

**Comment by trufae** [comment]
Fixed in master, both pebble issues. thanks for highlighting them
