### ISSUE TITLE
tms320 - rasm2 gives "invalid" error - unable to disassemble code from TMS320C6745DPTP3 device

### ISSUE THREAD

**Issue by mungewell** [radareorg/radare2#20020]
## Environment

```ubuntu@xubuntu:/cdrom$ date
Sat Apr 30 01:48:51 AM UTC 2022
xubuntu@xubuntu:/cdrom$ uname -ms
Linux x86_64
xubuntu@xubuntu:/cdrom$ r2 -v
radare2 5.6.8 1 @ linux-x86-64 git.
commit: d94100d386e8bc349b500af309e1880447a1e9da build: 2022-04-18__23:20:50
```

## Description

I am attempting a project with a Guitar effects pedal based on the TMS320C6745DPTP3. The effects for the pedal are contained in a wrapper, but include an ELF blob which is believed to be TMS320 code.

I can extract the `.text` section, but on disassembly just gives me an `invalid` message.

I am newb with radare2, but (falsely) telling `rasm2` that this is arm code does give an output.

Is TMS320 expected to function?

## Test

```
xubuntu@xubuntu:/cdrom$ objdump -s OUT_VP.ZD2.bin -j .text

OUT_VP.ZD2.bin:     file format elf32-little

Contents of section .text:
 0000 e6e21004 5d184d30 92117c30 e6022003  ....].M0..|0.. .
 0010 80ed409e cd1c6e6c 4511cd91 0020c0ee  ..@...nlE.... ..
 0020 64329001 00600000 007e9001 6e4c3400  d2...`...~..nL4.
 0030 65029201 cd916e4c 20b07fc0 000000e5  e.....nL .......
 0040 029e0c02 00400000 76021202 62a38c00  .....@..v...b...
 0050 00000000 00000000 00000000 00000000  ................
 0060 ef212644 2a980000 29008000 6b004000  .!&D*...)...k.@.
 0070 04020430 6800c000 74629000 020220e2  ...0h...tb.... .
 0080 62a38c00 00000000 00000000 00000000  b...............
 0090 00000000 00000000 00000000 00000000  ................

xubuntu@xubuntu:/cdrom$ objcopy -O binary -I elf32-little --only-section=.text OUT_VP.ZD2.bin ~/content.bin
xubuntu@xubuntu:/cdrom$ hexdump -C ~/content.bin
00000000  e6 e2 10 04 5d 18 4d 30  92 11 7c 30 e6 02 20 03  |....].M0..|0.. .|
00000010  80 ed 40 9e cd 1c 6e 6c  45 11 cd 91 00 20 c0 ee  |..@...nlE.... ..|
00000020  64 32 90 01 00 60 00 00  00 7e 90 01 6e 4c 34 00  |d2...`...~..nL4.|
00000030  65 02 92 01 cd 91 6e 4c  20 b0 7f c0 00 00 00 e5  |e.....nL .......|
00000040  02 9e 0c 02 00 40 00 00  76 02 12 02 62 a3 8c 00  |.....@..v...b...|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  ef 21 26 44 2a 98 00 00  29 00 80 00 6b 00 40 00  |.!&D*...)...k.@.|
00000070  04 02 04 30 68 00 c0 00  74 62 90 00 02 02 20 e2  |...0h...tb.... .|
00000080  62 a3 8c 00 00 00 00 00  00 00 00 00 00 00 00 00  |b...............|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0

xubuntu@xubuntu:/cdrom$ rasm2 -a tms320 -d  ~/content.bin
invalid

xubuntu@xubuntu:/cdrom$ rasm2 -a tms320 -d "e6 e2 10 04 5d 18 4d 30"
invalid
invalid
invalid
invalid
invalid
invalid
invalid
invalid

xubuntu@xubuntu:/cdrom$ rasm2 -a arm -d "e6 e2 10 04 5d 18 4d 30"
msb z6.b, p0/m, z16.b, z23.b
adr x29, 0x9a30d

xubuntu@xubuntu:/cdrom$ ls *.deb
r2ghidra_5.6.2_amd64.deb  radare2_5.6.8_amd64.deb
```

**Comment by trufae** [comment]
You need to specify the value of `asm.cpu` in r2, or use `-c` in rasm2:

for example: for c54x cpu model of the tms320 architecture you get:

```
$ rasm2 -a tms320 -c c54x -d "e6e210045d184d30"
mov 0x10, *sp(#71h)
bcc 0x18, ar5 >= 0
|| rpt 0x30
$
```

**Comment by mungewell** [comment]
Thanks for the guidance, with a few more flags I was able to get some disassembly
```
xubuntu@xubuntu:/cdrom$ rasm2 -a tms320 -c c55x -D -B -f ~/content.bin  | head
0x00000000   3                   e6e210  mov 0x10, *sp(#71h)
0x00000003   3                   045d18  bcc 0x18, ar5 >= 0
0x00000006   2                     4d30  || rpt 0x30
0x00000008   2                     9211  call ac1
0x0000000a   4                 7c30e602  sub 0x30E6, ac2, ac0
0x0000000e   1                       20  nop
0x0000000f   3                   0380ed  || retcc ac0 == 0
0x00000012   2                     409e  add 0x9, ar6
0x00000014   2                     cd1c  mov ar5, *sp(#Eh)
0x00000016   1                       6e  invalid
```
[invalid.txt](https://github.com/radareorg/radare2/files/8600519/invalid.txt)

Unfortunately it looks like none of the CPU options is close enough to work with C67x code, as all give `invalid` at some point. I guess the next task is to see if a new `table.h` can be defined for C67x/C67x+ - _or is CapStone the way to go on this?_

Are there tools to parse the TI documentation, and is this permitted? Or does someone have to manually work through the file:
https://www.ti.com/lit/ug/spru733a/spru733a.pdf

I note that compatibility for mostly is 'C62x, C64x, C67x, and C67x+ CPU'.


BTW, I think that this might be a typo (say 'C66', where rest of code says 'C65').
https://github.com/radareorg/radare2/blob/68327eba84348edf3c4d37cc7f4dd0a0ca3edac3/README.md#L138

**Comment by trufae** [comment]
The list of supported CPUs is listed in the plugin .cpus field. this is also shown in the output of `rasm2 -L` or `rasm2 -LL`

```
__A_  32         tms320      LGPLv3  TMS320 DSP family (c54x,c55x,c55x+,c64x)
```

<img width="461" alt="Screenshot 2022-05-02 at 13 14 01" src="https://user-images.githubusercontent.com/6431515/166225315-8779e5ea-c4d3-4983-abdf-7543c59173cb.png">

So, yeah, there's no c67x support. but you can contribute to capstone, which is probably the best option to get that new architecture into r2. 

Yes, c66 is a typo, i just fixed this in master. thanks for spotting it!

btw you can use `asm.invhex` to see hex `.dword` statements instead of `invalid` (in case you have data mixed with code that's usually handy). and maybe one day this will be enabled by default

**Comment by mungewell** [comment]
Thanks for you help. I've fired up a bug on Capstone, and will attempt to implement some code there.

**Comment by trufae** [comment]
amazing! looking forward to get one more target supported :)

thank you
