### ISSUE TITLE
Add proper help for eprintf usages

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#20047]
Find out which ones require some work by doing this:

```
$ git grep 'eprintf' | grep Usage
```

we have sys/counter.sh too

**Comment by qascade** [comment]
I always wanted to contribute to this project. May I give this a try? Will add more options to syscmd.c usage as per manpages.

**Comment by qascade** [comment]
@trufae Thank you for the clarification. I will ping again for any queries as I am new to this project. Is there any advice from your side, anything I should know before starting working on this.

**Comment by Lazula** [comment]
@qascade Just want to inform you of the existence of `r_core_cmd_help_match()` and `r_core_cmd_help_match_spec()`, as they were both created specifically to assist with this kind of task.


Declarations:

```
$ git grep -n 'r_core_cmd_help[^ ]*('
libr/core/cmd.c:357:R_API void r_core_cmd_help(const RCore *core, const char *help[]) {
libr/core/cmd.c:362:R_API void r_core_cmd_help_match(const RCore *core, const char *help[], R_BORROW R_NONNULL char *cmd, bool exact) {
libr/core/cmd.c:366:R_API void r_core_cmd_help_match_spec(const RCore *core, const char *help[], R_BORROW R_NONNULL char *cmd, char spec, bool exact) {
libr/core/cmd_print.c:7682:                              r_core_cmd_help(core, help_msg_p6);
libr/include/r_core.h:876:R_API void r_core_cmd_help(const RCore *core, const char *help[]);
libr/include/r_core.h:877:R_API void r_core_cmd_help_json(const RCore *core, const char *help[]);
libr/include/r_core.h:878:R_API void r_core_cmd_help_match(const RCore *core, const char *help[], R_BORROW R_NONNULL char *cmd, bool exact);
libr/include/r_core.h:879:R_API void r_core_cmd_help_match_spec(const RCore *core, const char *help[], R_BORROW R_NONNULL char *cmd, char spec, bool exact);
```

You can find usage with `git grep 'r_core_cmd_help_match '`.

**Comment by radare** [comment]
Reference commit for anyone who wants to contribute: https://github.com/radareorg/radare2/pull/21418

```
$ sys/counters.sh|grep eUsa
eUsage	     177
```

lets make this number down to zero!

**Comment by trufae** [comment]
I think @Lazula fixed them all. Except the ones in utils like syscmd stuff. Maybe those helps should be implemented in core. But we are 90% good on this now. Thanks for the amazing contribs!
