### ISSUE TITLE
Switch Between Arm/Thumb Mode Analysis 

### ISSUE THREAD

**Issue by apkunpacker** [radareorg/radare2#20059]
A feature request -
a flag/switch in r2 config by which we can enable or disable analysis of thumb or arm mode respectively to speedup analysis 
may be similer
```sh
e anal.armonly = true
e anal.thumbonly = true
```

**Comment by trufae** [comment]
what about `e asm.bits.fixed` to avoid asm.bits to change instead of having arm/thumb-specific config vars?

**Comment by enovella** [comment]
When you want to enforce Thumb mode, you can execute this command `ahb 16` at the respective offset. Instead of adding more flags to over-complicate the analysis and user experience, I'd discuss a better ARM vs Thumb mode detections when analyzing binaries in R2 land.

**Comment by trufae** [comment]
The idea for this variable is to avoid switching between thumb/arm when analizing. Just asuminf the whole binary is one arch. Which in some cases is, that will reduce false positive and lots of wrong code analysis and speedup analysis a mot

**Comment by trufae** [comment]
Mot is lot
