### ISSUE TITLE
mingw build broken by outdated headers

### ISSUE THREAD

**Issue by ypsvlq** [radareorg/radare2#20085]
Currently `debug_windbg.c` and `io_windbg.c` core plugins can't compile under mingw because the mingw-w64 `DbgEng.h` is outdated.

```c
typedef struct { // Keep in sync with io_windbg.c
	bool initialized;
	ULONG64 server;
	ULONG64 processBase;
	DWORD lastExecutionStatus;
	PDEBUG_CLIENT5 dbgClient;
	PDEBUG_CONTROL4 dbgCtrl;
	PDEBUG_DATA_SPACES4 dbgData;
	PDEBUG_REGISTERS2 dbgReg;
	PDEBUG_SYSTEM_OBJECTS4 dbgSysObj;
	PDEBUG_SYMBOLS3 dbgSymbols;
	PDEBUG_ADVANCED3 dbgAdvanced;
} DbgEngContext;
```

All the PDEBUG_xxx members are newer versions than what mingw provides.

**Comment by ypsvlq** [comment]
Problem 2:
```c
#define THISCALL(dbginterface, function, ...) dbginterface->lpVtbl->function (dbginterface, __VA_ARGS__)
#define ITHISCALL(dbginterface, function, ...) THISCALL (idbg->dbginterface, function, __VA_ARGS__)

/* ... */

return SUCCEEDED (ITHISCALL (dbgClient, DetachProcesses));
```

**Comment by ypsvlq** [comment]
Changing the PDEBUG_xxx interfaces to the versions mingw provides and fixing the THISCALL macros (with `,##__VA_ARGS__` extension for now) leaves these errors:
```
../libr/io/p/io_windbg.c:479:43: error: use of undeclared identifier 'DEBUG_ENGOPT_KD_QUIET_MODE'
../libr/io/p/io_windbg.c:611:38: error: no member named 'GetValidRegionVirtual' in 'struct IDebugDataSpaces3Vtbl'
``` 

`debug_windbg.c` compiles successfully.

**Comment by trufae** [comment]
Can you send a PR instead?

**Comment by ypsvlq** [comment]
Yes once done, it isn't suitable for merging in its current state though

**Comment by trufae** [comment]
Just prefix the pr title with WIP, so it makes clear is not suposed to be merged

**Comment by trufae** [comment]
uhm the windbg plugin is not suposed to be built. how are you compiling it to get this error?

**Comment by ypsvlq** [comment]
https://github.com/radareorg/radare2/blob/597496e17ac915d9371616ae0d18905474c0d5ca/libr/debug/meson.build#L64

it's built by default when using meson at least

I'll look at this properly and open a PR soon, I'm on phone rn

**Comment by trufae** [comment]
Oh ok because the ci uses sys/mingw.sh which does acr/make instead to crosscompile to windows. Yes the meson build adds the windbg plugin indeed

**Comment by trufae** [comment]
ping?

**Comment by ypsvlq** [comment]
Oh yeah, I forgot about this sorry

#20217
