### ISSUE TITLE
M68k instruction alignment

### ISSUE THREAD

**Issue by CrypticalCode0** [radareorg/radare2#20102]
*Scope of the Issue*
On the m68k arch there are several CPU's that are limited in their addressing capabilities of instructions, up to and including the 68020 it was not capable of decoding instructions that were not word aligned.(This pertains to 68000 68008 68010 68020 and CPU32) Even after this there was a unaligned penalty 68030 and onward.
Please take this in account because I see byte alignment on CPU's in this Arch that cannot do such a thing.

*Please describe what are you missing or wanting to be improved*

I would like that r2 follows the limitations of the members of this Arch and it's limitations, in this manner.
So if a user defines the m68k 68000 CPU it is limited to only word aligned instruction decoding.

**Comment by condret** [comment]
so you want r2 to take specific alignments into account depending on cpu?

**Comment by CrypticalCode0** [comment]
If at all possible, then Yes. to give an example 68000 didn't have a A0 address line so it was a physical impossibility for this CPU to address a byte Directly and always read and wrote a word depending one external logic to use /UDS & /LDS signals to differentiate upper and lower byte access, the PC however lacked the LSB address bit as a feature.

Condret if i knew that the ABI (and how) allows it i would add it for the m68k arch.

**Comment by CrypticalCode0** [comment]
Good to know but can it be defined by cpu selection. As in can it be defined in anal/p/m68k

**Comment by condret** [comment]
yes, I can do that. Can you give me some kind of table with cpu names and their alignments?

**Comment by CrypticalCode0** [comment]
these use word alignment
68000
68010
68070 (Philips CDR micro controller ISA compliant to 68010 with not documented extensions)
68020
CPU32 (683XX embedded systems)
ColdFire (52XX series, almost ISA )

These allow byte alignment in the instructions, even so word still delivers better performance. (don't get me started on MC68LC040 and any other cost reduced version)
68030
68040
68060

**Comment by condret** [comment]
would you prefer coldfire as cpu name, or something else?

**Comment by CrypticalCode0** [comment]
Coldfire is something i don't know, it's in it's basis compatible with the ISA it lacks some <ea> it's not and yet related to the m68k arch but that is a bee hive i am not willing to stick my finger in just yet.
I have it on the list because I think it should be complete.

**Comment by condret** [comment]
is this list only for code alignment or also data alignment?

**Comment by CrypticalCode0** [comment]
That is for code, data differs in that 68020 can already do miss-aligned data with a smaller penalty. But data alignment doesn't really matter on analysis it incurs a penalty on the platform but it is legal even if not advised. The 68000 even has /UDS & /LDS to define which part of the bus holds the data. This gets swapped so it's in the proper place inside the register if need be.

**Comment by czietz** [comment]
> so there are no m68k cpus with byte alignment?

When talking about *instructions*: no. Instructions must always be word
aligned.

When taking about data: Word (16 bit) or long-word (32 bit) *data* is
allowed to be misaligned on some CPUs, although this adds additional bus
cycles and hurts performance. (But that's of course not relevant for
Radare2.)

**Comment by trufae** [comment]
Yes it is relevant. Cycles cost is also part of the information of the instruction. And its used to compute function cost or play r2wars.

what you need is to change the archinfo() function of the anal.m68k plugin by checking the a->config->cpu value and return different alignment value.

**Comment by condret** [comment]
@trufae so far the m68k plugin provide no cycle info
