### ISSUE TITLE
ragg2 fails if in the same folder another not compatible libc

### ISSUE THREAD

**Issue by b10s** [radareorg/radare2#20127]
## Environment

```sh
$ ragg2 -v
ragg2 5.6.9 28511 @ linux-x86-64 git.5.6.2
commit: 10eb04f5b58ede4a0b01f5ab30a5e03293e38b72 build: 2022-05-07__02:12:01

$ date
Thu May 19 00:05:22 JST 2022

$ uname -ms
Linux x86_64
```

## Description

```
$ ls libc.so.6
libc.so.6

$ ragg2 -v
ragg2: relocation error: /lib/x86_64-linux-gnu/libpthread.so.0: symbol __libc_vfork version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

r2 works well. Probably some other binaries from r2 suit are also broken in the same manner.
Not sure is it bug or feature : )

**Comment by trufae** [comment]
Looks like you are using an ancient version of r2 which is probably shipped by your distro, as long as the distro updated libc that old pkg is probably outdated.

thats not a bug in r2. Fix your system or rebuild r2, preferibly from git 👍

**Comment by b10s** [comment]
@trufae it is build from git 

commit: 10eb04f5b58ede4a0b01f5ab30a5e03293e38b72 build: 2022-05-07__02:12:01

**Comment by b10s** [comment]
tried on fresh VM with latest r2 - can not reproduce

probably my local deviations
