### ISSUE TITLE
Releases > Android - x86_64 variant ~ wrong filetype

### ISSUE THREAD

**Issue by neomafo88** [radareorg/radare2#20229]
https://github.com/radareorg/radare2/releases/download/5.7.0/radare2-5.7.0-android-x86_64.tar.gz

```
$ file radare2-5.7.0-android-x86_64.tar.gz
radare2-5.7.0-android-x86_64.tar.gz: POSIX tar archive (GNU)
```

File is a tar archive i.e. .tar, not .tar.gz

**Comment by trufae** [comment]
i can confirm
