### ISSUE TITLE
Replace drm with drv

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#20242]
replace x86 specific reg-types (XMM, YMM and ZMM) with R_REG_TYPE_VEC.
replace drm command with drv and kill drmy command

**Comment by trufae** [comment]
sounds reasonable, but will users be happy with a DRM-free r2 then?

**Comment by trufae** [comment]
ping. r2580 is in two weeks do u have time for this change?

**Comment by trufae** [comment]
@condret will be useful to differentiate the ymm, zmm, xmm registers , i guess that considering it them all as vectors, and just group them by register size would be enough. can you do this change beofre 5.8 is out? aka 1 week

**Comment by trufae** [comment]
Done
