### ISSUE TITLE
Move all asm plugins into anal plugins

### ISSUE THREAD

**Issue by terorie** [radareorg/radare2#20296]
## Description

The `anal` plugins replace `asm` plugins going forward.

### Progress

- [x] asm.6502 https://github.com/radareorg/radare2/pull/20297
- [x] asm.8501 https://github.com/radareorg/radare2/pull/20298
- [x] asm.alpha https://github.com/radareorg/radare2/pull/20299 https://github.com/radareorg/radare2/pull/20362
- [x] asm.amd29k https://github.com/radareorg/radare2/pull/20325
- [x] asm.arc
- [x] ~~asm.arm.as~~
- [x] ~~asm.arm~~
- [x] asm.arm.gnu
- [x] asm.arm.winedbg
- [x] asm.avr https://github.com/radareorg/radare2/pull/20300
- [x] asm.cr16 https://github.com/radareorg/radare2/pull/20316
- [x] asm.cris
- [x] asm.dalvik
- [x] ~~asm.dcpu16 https://github.com/radareorg/radare2/pull/20318~~
- [x] asm.gb
- [x] asm.h8300 https://github.com/radareorg/radare2/pull/20322
- [x] asm.hppa
- [x] asm.i8080 https://github.com/radareorg/radare2/pull/20303
- [x] asm.java https://github.com/radareorg/radare2/pull/20304
- [x] asm.lanai
- [x] asm.lh5801 https://github.com/radareorg/radare2/pull/20317
- [x] asm.lm32
- [x] asm.m68k.gnu
- [x] asm.m680x
- [x] asm.malbolge https://github.com/radareorg/radare2/pull/20308
- [x] asm.mcs96
- [x] asm.mips https://github.com/radareorg/radare2/pull/20301
- [x] asm.mips.gnu
- [x] ~~asm.null~~
- [x] asm.or1k
- [x] asm.pdp11 hare there any hardttps://github.com/radareorg/radare2/pull/20305
- [x] ~~asm.ppc.as~~
- [x] asm.ppc
- [x] asm.propeller
- [x] asm.riscv #20274
- [x] asm.rsp
- [x] asm.sh
- [x] asm.sparc https://github.com/radareorg/radare2/pull/20302 https://github.com/radareorg/radare2/pull/20363
- [x] asm.sparc.gnu
- [x] asm.tm32 https://github.com/radareorg/radare2/pull/20360
- [x] asm.tms320 https://github.com/radareorg/radare2/pull/20315
- [x] asm.tms320c64x https://github.com/radareorg/radare2/pull/20315
- [x] asm.v810 https://github.com/radareorg/radare2/pull/20306
- [x] asm.v850 https://github.com/radareorg/radare2/pull/20312
- [x] asm.x86
- [x] ~~asm.x86.as~~
- [x] ~~asm.x86.nasm~~
- [x] ~~asm.x86.gas~~
- [x] ~~asm.x86.nz~~
- [x] ~~asm.x86.vm~~ (doesn't exist? typo?)
- [x] asm.xap https://github.com/radareorg/radare2/pull/20327
- [x] asm.xcore https://github.com/radareorg/radare2/pull/20326

**Comment by condret** [comment]
only need to move the disassembling part, the assemble should remain in asm

**Comment by trufae** [comment]
almost there 💪

**Comment by trufae** [comment]
asm.arm is assembler only. somaybe we can just remove it because its duplicating code already available in the anal plugin

**Comment by trufae** [comment]
i did it i fucking did it

**Comment by alex-bender** [comment]
that was a long run! congratulations!

**Comment by trufae** [comment]
Indeed! Thanks for noticing it! It was a big step forward to set the base for more refactorings!
