### ISSUE TITLE
Interactive filter (?*~...) is somehow broken

### ISSUE THREAD

**Issue by nikkej** [radareorg/radare2#20310]
## Environment

```
Thu 16.6.2022 10.27.53 +0300
radare2 5.7.1 29550 @ linux-x86-64 git.5.7.0-130-g7cb7529358
commit: 7cb75293582b36ed2c4306dd8d314da34bdceef8 build: 2022-06-15__13:55:44
Linux x86_64
```

## Description

With some Linux x86_64 binaries it takes a lot of time to open interactive filter for cmd help. I.e. If `?*~...` fed as a first command after launching r2 with such a binary it will take even minutes to output anything on to terminal. Launching r2 without file give r2 almost immediate response for `?\*~...` but even then r2 prompts 'Cannot determine file size' before prompting interactive filter.

## Test

I attach one binary which r2 behaves as I have desribed here and it's source code. Beware: recompiling binary seems to affect r2 interactive filter behavior thus it may not bring the problem visible.
[dfs-iterative.tar.gz](https://github.com/radareorg/radare2/files/8916782/dfs-iterative.tar.gz)

**Comment by trufae** [comment]
thats not related to the ~... but ?* was exposing some commands that didnt handle the help suffix. its now fixed, but i bet there are more :) thats one of the good things of ?*. thanks for spotting it and reporting!
