### ISSUE TITLE
Cannot find SFLIBPATH env var

### ISSUE THREAD

**Issue by miralayipouya** [radareorg/radare2#20341]
I have downloaded [radare2-5.7.0-w64.zip](https://github.com/radareorg/radare2/releases/download/5.7.0/radare2-5.7.0-w64.zip)
and when i run ragg2 like below:
```ragg2.exe -a x86 -b64 test.c```
it shows me error like below:
```
Cannot find SFLIBPATH env var.
Please define it, or fix r2 installation.
Failure while parsing 'test.c'
```
OS: WIN 10

**Comment by trufae** [comment]
I dont think sflib or ragg2 for C code would work at all on windows. It requires gcc installed and there are no syscall definitions for windows. And syscall interfaces on windows change on every single version of the OS.
