### ISSUE TITLE
how to make a memory breakpoint

### ISSUE THREAD

**Issue by b1gcat** [radareorg/radare2#20359]
it break on a memory read or write

**Comment by trufae** [comment]
If you are on intel you can use the drx command.

on other architectures you may want to look and dbw which is a generic interface across all hardware breakpoint implementations. But thats poorly tested.

in addition you can use esil expressions to step until the expression matches, and use that to find which instructions access a specific address in memory.

Another way to do watchpoints is by doing traptracing. Theres a command for that but i dont have it in my head right now. It does run the dmp command to change the debug-map-permissions to be non-readable (or non writable or non executable) and then it analyzes the exception to find out which instruction caused it and if it was related to the watch address.
