### ISSUE TITLE
rafind2 -v4 0x434

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#20439]
Implement /v in rafind2, with support for endian swapping and alignment overlap by default, problem is that -v is handled for version,so maybe we need to use -V for this. any volunteer? comments?

**Comment by alex-bender** [comment]
> with support for endian swapping and alignment overlap by default

Is that already handled in r2 or should be implemented?

**Comment by radare** [comment]
Its already implemented in r2. But maybe handy to have it in rafine2
