### ISSUE TITLE
r2 segfaults on arm64 standalone Darwin kernel

### ISSUE THREAD

**Issue by Siguza** [radareorg/radare2#20492]
## Environment

```sh
Wed Jul 27 05:10:55 CEST 2022
radare2 5.7.5 28639 @ darwin-arm-64 git.5.7.4-106-g7ff05dab3
commit: 7ff05dab3fb0579cdc9686652200d9895364e410 build: 2022-07-27__05:08:18
Darwin arm64
```

## Description

Pretty self-explanatory:

```
% r2 /System/Library/Kernels/kernel.release.t8101 
zsh: segmentation fault  r2 /System/Library/Kernels/kernel.release.t8101
```

## Test

The file in question: [kernel.release.t8101.gz](https://github.com/radareorg/radare2/files/9194740/kernel.release.t8101.gz)  
Though any arm64 Darwin kernel that's not a full kernelcache should reproduce the issue.

I only looked at the crash log briefly, but I suspect the issue is with `__TEXT.__thread_starts` being zero-sized.

**Comment by trufae** [comment]
Thanks for reporting it! it's fixed in https://github.com/radareorg/radare2/pull/20498
