### ISSUE TITLE
ERROR: cannot open file /home/tester/tmp.d/test.img.d/cryptodisk

### ISSUE THREAD

**Issue by leakerlee** [radareorg/radare2#20573]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
r2 -v
uname -ms
```

## Description

when I run:
r2 -p ot_uncompressed_0x9000
ERROR: cannot open file /home/tester/tmp.d/test.img.d/cryptodisk

following is the issue point in ~/.local/share/radare2/projects/ot_uncompressed_0x9000/rc.r2
...
o /home/bayern/tmp.d/test.img.d/cryptodisk@0x7fd6e40L0x0x249e 0x07fd6e40 r-x
...

when I change above line to the following, then the error is missing:

o "/home/bayern/tmp.d/test.img.d/cryptodisk@0x7fd6e40L0x0x249e" 0x07fd6e40 r-x

yes, quotes the path.

**Comment by trufae** [comment]
@ is a special character from the r2 shell so its expected that you need to quote the path. But quotes in r2 should cover the whole command not just the file. You can also escape it with a backslash \@

**Comment by leakerlee** [comment]
> @ is a special character from the r2 shell so its expected that you need to quote the path. But quotes in r2 should cover the whole command not just the file. You can also escape it with a backslash @

Yes, you are right.
But I mean
when the project RC file rc.r2 being saved, program needs to quote the path automatically.

**Comment by trufae** [comment]
Oh! I missed the -p in your output. Yes thats clearly a bug. Sorr

**Comment by trufae** [comment]
Sorry for closing the ticket i missunderstood the actual issue. I will find some time to fix it but i wont probably have time until sunday

**Comment by trufae** [comment]
totally. ill fix this issue this week.
