### ISSUE TITLE
 Cannot find arch plugin with this name. See rasm2 -L and rasm2 -LL

### ISSUE THREAD

**Issue by yehudahs** [radareorg/radare2#20587]
## Environment
Mac M1, macOS Monterey 12.5

date
Tue Aug 16 10:19:29 IDT 2022
r2 -v
radare2 5.7.7 28668 @ darwin-arm-64 git.5.7.6-72-gaa990230c
commit: aa990230cc15a4927a4a622fae4bf6a1ede75dc1 build: 2022-08-16__09:50:38
uname -ms
Darwin arm64

## Description
trying to debug simple binary and getting the next error:
 Cannot find arch plugin with this name. See rasm2 -L and rasm2 -LL

**Comment by trufae** [comment]
Trying to debug how? Which commands did you used and whats the output of the commands suggested?

**Comment by yehudahs** [comment]
after some more play I find that if I run 
`r2 -aaa <the exe>` 
I get 
`ERROR: Cannot find arch plugin with this name. See rasm2 -L and rasm2 -LL` 
BUT if I run
`r2 <the exe> `
and than aaa it fine...
strange...

**Comment by trufae** [comment]
What you are doing with -aaa is the same as -a aa. Aka. Telling r2 to use the arch named "aa" which obviously doesnt exist.

if you want to run the analysis as a flag. You must use the uppercase one. -AAA
