### ISSUE TITLE
Assembly plugins recive tolower strings

### ISSUE THREAD

**Issue by swoops** [radareorg/radare2#20595]
## Environment

```sh
$ date; r2 -v; uname -ms
Wed Aug 17 06:17:37 PM EDT 2022
radare2 5.7.7 29263 @ linux-x86-64 git.5.7.6-51-g6bc75331d
commit: 6bc75331da176084254e973e3b93d527afef7681 build: 2022-08-09__14:37:21
Linux x86_64
```

## Description

Assembler plugins revive user strings that have be turned to lowercase. This likely saves most plugins a bit of work but for some assemblers it prohibits the user from assembling things with upper case strings. Pickle's for example, maybe dalvik too?

## Test
Assembling the pickle code `string AAAA` results in lowercase 'AAAA':
```
$ rasm2 -a pickle 'string AAAA'
53616161610a
$ rasm2 -da pickle $(rasm2 -a pickle 'string AAAA')
STRING "aaaa"
```

**Comment by trufae** [comment]
Thats a convention in r2land. All mnemonics for all archs must be lowercase. Theres asm.ucase to have them in uppercase. It brings some consistency

**Comment by trufae** [comment]
I fixed dat in master
