### ISSUE TITLE
Decompile panel is broken

### ISSUE THREAD

**Issue by ZzEeKkAa** [radareorg/radare2#20651]
## Environment

```
Tue Aug 23 20:40:18 EDT 2022
radare2 5.7.6 0 @ darwin-arm-64 git.5.7.6
commit: 5.7.6 build: 2022-08-01__16:48:39
Darwin arm64
```

## Description

Strange issue happens, when I'm trying to use decompiler in panel mode. It shows on a panel if I switch to Decompile view (shift + "), but once i click with mouse anywhere the panel show nothing. Decompiler panel seems to be broken. Other views seems to work in the same panel, but this one is broken. To see decompiler again, i need to create new panel. But it becomes broken again, once click with a mouse... (mac os, radare2 from brew, up to date).

https://user-images.githubusercontent.com/5175807/186290553-28f6f20c-f9c3-4e16-9fd4-5781cae3e258.mov

## Test

Simple pe32 hello, world program compiled with mingw-gcc under Mac.

**Comment by trufae** [comment]
im back to home and i can confirm this is a bug and i can reproduce
