### ISSUE TITLE
radiff2 always uses physical addresses, no matter what

### ISSUE THREAD

**Issue by gordboy** [radareorg/radare2#20665]
## Environment

```sh
Fri  2 Sep 15:18:44 BST 2022
radare2 5.7.6 0 @ linux-x86-64 git.5.7.6
commit: 5.7.6 build: 2022-08-04__10:15:53
Linux x86_64
```

## Description

`radiff2` always uses `physical` addresses, no matter what the `-p` flag is set to, for all files, no matter what.

I would sincerely like to have `virtual addresses by default`, and `physical addresses with -p` for regular PE/ELF/whatever binaries. The reason being that `-p` is great for file diffing and patching -

```
radiff2 -p -r myfile1 myfile2 > RADIFF2_PATCH
```
this makes a nice small file one can later use perhaps on another system to make `myfile2`

```
cp myfile1 myfile2
r2 -nqw -i RADIFF2_PATCH myfile2
```
All `very nice and useful`, but sometimes I want `virtual` addresses to make `interactive` work in `r2` a whole lot easier ... without using `rabin2` and a nasty script that does the hex calculations to convert PA to VA, or some other `magic`, `guesswork`  or `divination` ...

## Test
I checked various files on my system, and there was no difference with any combo of files and options. So I came up with the following test, which proves the point -

First check that `vaddr` and `paddr` entry points are different, which proves VA != PA for these files

first `myfile1`

```
rabin2 -e myfile1 
[Entrypoints]
vaddr=0x00461b10 paddr=0x00061b10 haddr=0x00000018 hvaddr=0x00400018 type=program
```
and same for `file2`

```
rabin2 -e myfile2
[Entrypoints]
vaddr=0x00461b10 paddr=0x00061b10 haddr=0x00000018 hvaddr=0x00400018 type=program
```
In both cases `vaddr=0x00461b10` and `paddr=0x00061b10`, which differ by `0x400000`, which shows VA != PA for these files.

Now run `radiff2` with and without `-p` flag

first without `-p` flag
```
radiff2 myfile1 myfile2
0x00141430 8b4f3cb81301 => b8db000000c3 0x00141430
```

now with `-p` flag
```
radiff2 -p myfile1 myfile2
0x00141430 8b4f3cb81301 => b8db000000c3 0x00141430
```

and just to be sure, lest our eyesight be faulty or tired

```
diff -s <(radiff2 myfile1 myfile2) <(radiff2 -p myfile1 myfile2)
Files /dev/fd/63 and /dev/fd/62 are identical
```
This proves that the `-p` flag has exactly `zero` effect with files that have different `vaddr` and `paddr`, which is not expected or desirable behaviour.

**Comment by trufae** [comment]
the paddr / vaddr is only used when diffing code, which implies parsing the binary headers and so on. if you use radiff2 -r, it will just do a raw diff. you should use radiff2 -AC for this.

**Comment by trufae** [comment]
i get your point , and i agree that -p is not clearly documented and should probably be also extended to be used in other diffing modes.

**Comment by trufae** [comment]
so that looks to me like a feature request rather than a bug report because its changing the actual behaviour.. would you like to submit a fix for that? should be a matter of touching the libr/main/radiff2.c only

**Comment by gordboy** [comment]
OK I might just do that. First I have some python to unravel.

So I will close this issue, and have a look at what I can do some time soon.

**Comment by trufae** [comment]
Thanks for pointing it out. Radiff needs some care :) let me know if you need anything

**Comment by trufae** [comment]
Maybe we can add a flag to speicfy the base address, so we can get the diff using physical addressing, but that will let us get a patch for any address in memory. handy for patching with aslr enabled.

**Comment by trufae** [comment]
Merged, so i consider it fixed now.
