### ISSUE TITLE
##visual ##print unsigned integer dump like 'pxd'

### ISSUE THREAD

**Issue by nik6ena** [radareorg/radare2#20671]
```
[0x00000000 0x00000000 [Xadvc]8 [0x0..0x0] 1]> pxd                                                                                                                                                
- offset - | 00 01  02 03  04 05  06 07  08 09  0A 0B  0C 0D  0E 0F  10 11  12 13  14 15  16 17  18 19  1A 1B  1C 1D  1E 1F  20 21  22 23  24 25  26 27| 0123456789ABCDEF0123456789ABCDEF01234567 
0x00000000 |           22            86             6             0             0             0          2785          2729          1428             9  ....V................................... 
0x00000028 |            0          3450   -1073741825          1428             9             0          1064   -1073741825          1380             9  ....z...................(.......d....... 
0x00000050 |            0            29   -1073741825           588             9             0         47153    2147483647          8604             9  ............L...........1........!...... 
```

> | pxd[?1248]        signed integer dump (1 byte, 2 and 4)

> 
> :> pf??
> Usage: pf[.k[.f[=v]]|[v]]|[n]|[0|cnt][fmt] [a0 a1 ...]
> Examples:
> | pf n2                                        print signed short (2 bytes) value. Use N instead of n for printing unsigned values

Need an inverse of this print format in the Visual hexdump mode, i.e., all those numbers should be displayed as unsigned values.

I have just stumbled upon r2 yesterday and couldn't for the life of me figure out this one by reading the [book](https://book.rada.re/visual_mode/intro.html) or the program help text.

Is this even doable without introducing a change-set?

excerpt from https://github.com/radareorg/radare2/tree/master/libr/core/visual.c

```
static const char *printHexFormats[PRINT_HEX_FORMATS] = {
	"px", "pxa", "pxr", "prx", "pxb", "pxh", "pxw", "pxq", "pxd", "pxr",
};
```

Or a `"pxu"`? as in the C format specifier `"%u"`.

If it is of any significance here, that I am using Arch linux, latest package `radare2 5.6.6-3`, and also compared master branch to this release but don't see any commit in those 923 sum commits talking about this.

**Comment by trufae** [comment]
You can use the `cmd.visual` variable to choose a different command to run in visual mode. The cmd.vprompt may be also interesting for you. it runs a command before the visual prompt

**Comment by nik6ena** [comment]
Hey! Good to see you there. A fast response from the lead itself.

So I tried config options `cmd.(visual)|([vc]prompt)` with value `pf N4`, one by one. None of them gives me the view I want. Probably not what you wanted me to do either.

Looks like I'll have to do a lot of dig around the source to really understand how the visual hexdump view is generated. And what print format string is behind command `pxd` and then be able to set correct config opt(s) value(s).

I'd state again, I need visual as given by `pxd` print format, but as unsigned values. What opts/value exactly can achieve this?

**Comment by trufae** [comment]
Sorry i misunderstood your original message, there's nothing related to visual for the unsigned decimal hexdump. the pxu command doesnt exist and should be implemented imho. 

So if i understood you correctly, thats what you are looking for: https://github.com/radareorg/radare2/pull/20677

**Comment by nik6ena** [comment]
Whoa, never thought that would be so fast.

Looks all good to me. Soon I'll compile from master and test run it.

Hey, thanks Sergi you really saved the day.

**Comment by trufae** [comment]
You are welcome :) happy to help

**Comment by nik6ena** [comment]
I'll be glad if you could review my first ever PR :)
