### ISSUE TITLE
Allow assembly code scroll on minimal CFG mode of graph view

### ISSUE THREAD

**Issue by arnaugamez** [radareorg/radare2#20672]
## Description

When navigating to basic blocks on the CFG using the minimal graph view, shows the basic block location on the graph and the assembly code of the basic block in the left, if the assembly code is so large that it does not fit the terminal window size, there is no way to scroll over it.

![image](https://user-images.githubusercontent.com/5301529/188264848-707a6433-a4f9-43a9-85d4-ec6d0130feca.png)

It would be great having some dedicated keys to scroll over assembly code (in a similar fashion as `hjkl` and cursor keys navigate through the graph) and/or toggle key to change between scrolling graph and scrolling assembly.

**Comment by trufae** [comment]
You can press 'c' to toggle the cursor mode and then jk acts as a scroll for the disassembly

**Comment by arnaugamez** [comment]
Oh yay! Didn't know cursor mode working here too. Thank you, closing the issue.
