### ISSUE TITLE
ERROR: Cannot assemble 'add x21, x22, 0x20' at line 3

### ISSUE THREAD

**Issue by 16ea** [radareorg/radare2#20733]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
➜  ~ git:(master) ✗ date
2022年 9月14日 星期三 14时51分31秒 CST
➜  ~ git:(master) ✗ r2 -v
radare2 5.7.8 0 @ darwin-x86-64 git.5.7.8
commit: HEAD 5.7.8 build: 2022-09-14__11:25:12
➜  ~ git:(master) ✗ uname -ms
Darwin x86_64
```

## Description

I don't know how to use assembly to patch binary,such as " s 0x1000052d8.        wa add x21, x22, 0x20"
but it has an error "ERROR: Cannot assemble 'add x21, x22, 0x20' at line 3"
i want to know how to do this

**Comment by 16ea** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/85932203/190082251-d79b502c-cf79-46a9-94d2-74f48bdf71a8.png">

**Comment by 16ea** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/85932203/190097675-b576e35f-8445-4d31-8845-ab4e51109c2b.png">
this is ok!

**Comment by trufae** [comment]
it works well for me:

```
0$ rasm2 -a arm -b64 -d `rasm2 -a arm -b64 'add x21, x22, 0x20'`
add x21, x22, 0x20
0$
```
