### ISSUE TITLE
Add aflx? and some subcommands

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#20741]
* [ ] aflxv -> verbose with names instead of addresses
* [ ] aflxj -> json format
* [ ] aflx? -> missing help

**Comment by trufae** [comment]
context https://twitter.com/leathersentinel/status/1570089974791573506?s=21&t=TK0QFaG7oyywib9dGkFAGQ

**Comment by MoonlitPlatypus** [comment]
@trufae I'm interested in giving back to this project by making contributions! Would you mind if I assigned myself this issue and started working on it, since it's a `good first issue`? It would allow me to familiarize myself with both the codebase and the workflows you guys use!

**Comment by trufae** [comment]
Hello @MoonlitPlatypus ! sorry for my late reply :) yes, the `aflx` command has been recently implemented by @MohamedX99 , but not the subcommands listed in this ticket. Sure, this is a good first issue, and i would recommend you to join the irc/telegram/discord for faster interactions on questions if you need them.

i can't assign the ticket to you because github only allows that with users with commit access. but dont worry, nobody will pick that :) all yours
