### ISSUE TITLE
Built in gron functionality

### ISSUE THREAD

**Issue by swoops** [radareorg/radare2#20760]
## Description

Been in love with a tool called gron by @tomnomnom  ([found here](https://github.com/tomnomnom/gron)).

R2 already has built in `jq`-esque support with `~{}`. This is great when you know what you are looking for. But when you have a truely massive JSON blob and are really only interested in the internals of it, gron is the way to go. Gron flattens the JSON so you can grep it:

```
> echo '{"test" : [1,2,3, {"woo":false, "nope": ["foo"]}]}'|gron
json = {};
json.test = [];
json.test[0] = 1;
json.test[1] = 2;
json.test[2] = 3;
json.test[3] = {};
json.test[3].nope = [];
json.test[3].nope[0] = "foo";
json.test[3].woo = false;
> echo '{"test" : [1,2,3, {"woo":false, "nope": ["foo"]}]}'|gron|grep foo
json.test[3].nope[0] = "foo";
```

You can easily do this in `r2` just by piping JSON output to `gron` then use `~{}` to get those elements:
```
[0x00006180]> aflj|gron |grep main
json[29].name = "sym.imp.textdomain";
json[29].signature = "char *sym.imp.textdomain (char *domainname);";
json[33].name = "sym.imp.bindtextdomain";
json[33].signature = "char *sym.imp.bindtextdomain (char *domainname, char *dirname);";
json[115].name = "main";
json[115].signature = "int main (int argc, char **argv);";
[0x00006180]> aflj~{[115][name]}
main
[0x00006180]> aflj~{[115][signature]}
int main (int argc, char **argv);
```
It would be neat to have this built into r2. I am pretty busy, so anyone is free to take ownership and implement. Otherwise, I will do it eventually.

**Comment by condret** [comment]
I personally don't see the necessity to add this to r2, bc the tool already exists and you could just pipe it. I'd prefere to add an r2pm package for it, unless you **really** want it to be in r2
