### ISSUE TITLE
change travis-cicd to deploy automatically on most recent OS such as Linux, Windows, MacOs and Linux distros like Debian, Ubuntu, Kali on each Merge

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#20832]
## Description

r2 is outpdated on most of the Linux distros. I suggest to use travis deployement to automatically submit compiled files.

We have to choose between the old deployement method:

https://docs.travis-ci.com/user/deployment/releases

or the new but beta:

https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release

In case of doubt we can check this:

There is a blog on: https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release

Assign me to this issue please.

**Comment by gogo2464** [comment]
I think use the beta sounds better.

**Comment by trufae** [comment]
We stopped using travis long time ago. Github is publishing the release binaries. R2env is the tool you want to use to get latest r2 on any OS. I dont see how debian will get new packages with what you are proposing here. They have their own rules and burocracy and they will never get those packages.

its distro's fault for not maintaining their packages properly. In a week we will get the flatpak package published so all those problems will be gone at least on ubuntu

**Comment by trufae** [comment]
No, it's distros who maintain and decide which packages they ship. Some distros have 3rd party repositories like arch community ones for example, which accept pull requests. but the main distro repositories are maintained by packagers who need to sign contracts and pass internal reviews and keep up with their packages. so doing a pullrequest is not an option either.

Debian removed r2 from their repositories for several reasons, but not having enough maintainers was not one of them. I personally dislike their policies as they maintain old software, backporting patches which ends up in new vulnerabilities and it's not possible for them to ship updated builds of r2, basically all non-rolling release distros use to fail at maintaining their packages.

During my netbsd days i actively maintained 300 packages and reported all the required patches upstream. Debian never reports back anything. So the only way to get your updated software to work in those distros is by publishing your own debian packages and publish them in a repository that users need to add, like nodejs or many other projects do. Another option is using appimage or flatpak, which at least is not tied to the distro rules and can

I build the debian packages of r2 and all its plugins and ui and publish them in github, any user can download the .deb and install it in their distro, that works in all debian-based distros (kali, ubuntu, ..) but again, those packages wont be accepted by debian and i personally don't have the time and motivation to do any burocracy for such things, despite i understand debian is the most used distro out there and users would like to `apt install r2`.
