### ISSUE TITLE
capstone？

### ISSUE THREAD

**Issue by zzjss12** [radareorg/radare2#20846]

**Comment by trufae** [comment]
What's "off campus"? that file is not required or downloaded during any installation. What commands are you using or which steps you did? if you are on windows you can just download a release build so you dont need to compile it. or use r2env via pip

**Comment by zzjss12** [comment]
![2151534F405E7EFB479B9726C40B6C05](https://user-images.githubusercontent.com/66284098/194015125-0f42fc4a-eb4c-420f-9c60-0766731a5ded.png)
downloading capstone always times out. Is there any other solution？

**Comment by trufae** [comment]
r2-3.2 is very old. Capstone is important for many architectures but you can do different things here:

* install capstone system wide (i would recommend capstone5, cs4 is 4 year old and misses A LOT of important instructions for x64 and arm64), sys/install.sh will autodetect and use that if available
* build r2 without capstone (there's a CI job for that you can read the .github/workflows/*.yml for the `nocs` job (no-capstone)

If you opt for the 2nd. these are the steps you must do:

```
cp -f dist/plugins-cfg/plugins.nocs.cfg plugins.cfg
./configure --without-capstone --with-rpath
make -j
sudo make install
```

**Comment by zzjss12** [comment]
> r2-3.2 is very old. Capstone is important for many architectures but you can do different things here:
> 
> * install capstone system wide (i would recommend capstone5, cs4 is 4 year old and misses A LOT of important instructions for x64 and arm64), sys/install.sh will autodetect and use that if available
> * build r2 without capstone (there's a CI job for that you can read the .github/workflows/*.yml for the `nocs` job (no-capstone)
> 
> If you opt for the 2nd. these are the steps you must do:
> 
> ```
> cp -f dist/plugins-cfg/plugins.nocs.cfg plugins.cfg
> ./configure --without-capstone --with-rpath
> make -j
> sudo make install
> ```

In fact, I use sys/install.sh command has tried to install many times, but each time it is because the capstone download fails. Can I manually download capstone and then install r2?

**Comment by trufae** [comment]
Of course, if you install capstone system wide the script wont try to download it and use the system one
