### ISSUE TITLE
Can't debug in ios

### ISSUE THREAD

**Issue by reverseXiang** [radareorg/radare2#20869]
## Environment

```sh
# r2 -d pid
```

## Description
I run the command "r2 -d pid" to debug an app in ios, but when i run "dc" command, it output error info "hw breakpoints not yet supported". I can't set a break point successfully. The program run normally and other function of r2 run normally.

I use radare2 5.7.8 1 @ darwin-arm-64 git.5.7.8
ios 14.2 jailbreak device

**Comment by reverseXiang** [comment]
it confuse me for a long time, help please

**Comment by reverseXiang** [comment]
I use "db addr" command to set a breakpoint

**Comment by trufae** [comment]
try with `e dbg.hwbp=false`
