### ISSUE TITLE
implement an native decompiler in radare2

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#20877]
## Description

I have got a look at radeco and I am deeply disapointed. Radeco does not reuse the r2 codebase. For example each disassembly is reimplemented. See: https://github.com/radareorg/radeco/blob/master/radeco-lib/src/frontend/instruction_analyzer.rs#L125. Then I suggest a better implementation.

1- The r2 codebase will be reused. Then, each anal disassembly plugin will give extra infos about each instructions. So that the r2 decompiler will be able to use these general info to create C code. These extra infos can also be used in r2 for example to put color in each instructions or more or else.

2- The r2 decompiler will follow the r2 philosophy. Each architecture will be decompilable to r2 decompiler. A tutorial on r2 module writting will be written. The core will work automatically.

3- the r2 decompiler will also read metadata with a plugin for each language.

4- the r2 decompiler will be written in C in the r2 codebase. No extern library.

5- the r2 decompiler will rely on the i | grep lang infos to autodetect languages

I am going to implement this. If you have suggestion or will to help me. DO not hesistate. Contributions are greatly granted.

**Comment by condret** [comment]
good luck

**Comment by trufae** [comment]
please use this issue tracker as an issue tracker, for non concrete proposals use: https://github.com/radareorg/ideas
