### ISSUE TITLE
loading ios binary hangs

### ISSUE THREAD

**Issue by spitzi007** [radareorg/radare2#20881]
## Environment

Tue Oct 11 15:19:12 IDT 2022
radare2 5.7.8 1 @ darwin-x86-64 git.5.7.8
commit: 8e965bef30457a12e07a32a9047a9620a944bc39 build: 2022-09-13__16:26:34
Darwin x86_64

## Description

trying to load the ios binary (see link for downloading the ios binary) into radare2 hangs forever. I never get the radare2 prompt....
[https://drive.google.com/file/d/1THlMBMgZrg3gvjb6OeyxSjxtgwH-nOnE/view?usp=sharing](url)

## Test

1)
r2 <path of the attached binary>/RedditApp

2) 
running with dapptrace hangs as well:
sudo dapptrace r2  /Users/myUser/Downloads/RedditApp
CALL(args) 		 = return
-> main(0x2, 0x7FF7B7A8B670, 0x7FF7B7A8B688)
<- main = 186

What am I doing wrong? Thanks in advance for any help/hint

**Comment by trufae** [comment]
works fine for me, it parses all the objc, swift and headers and i get the prompt after 3s. but im using r2 from git, wont fix an old release if its a bug in there
