### ISSUE TITLE
Static compilation failed with an error “XX.a in archive is not an object”

### ISSUE THREAD

**Issue by DylanSec** [radareorg/radare2#20900]
# **Description**

When I compile radare statically, I get an error as follows:

```
ar/libr_ar.a: member ar/libr_ar.a(ar.o) in archive is not an object
bochs/lib/libbochs.a: member bochs/lib/libbochs.a(libbochs.o) in archive is not an object
capstone/libcapstone.a: member capstone/libcapstone.a(cs.o) in archive is not an object
gdb/lib/libgdbr.a: member gdb/lib/libgdbr.a(libgdbr.o) in archive is not an object
java/libr_java.a: member java/libr_java.a(code.o) in archive is not an object
qnx/lib/libqnxr.a: member qnx/lib/libqnxr.a(packet.o) in archive is not an object
winkd/libr_winkd.a: member winkd/libr_winkd.a(transport.o) in archive is not an object
zip/librz.a: member zip/librz.a(adler32.o) in archive is not an object
Makefile:341: recipe for target 'libr_shlr.a' failed
make[3]: *** [libr_shlr.a] Error 1
make[3]: Leaving directory '/radare2/shlr'
Makefile:159: recipe for target '../shlr/libr_shlr.a' failed
make[2]: *** [../shlr/libr_shlr.a] Error 2
make[2]: Leaving directory '/radare2/libr'
Makefile:22: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/radare2/libr'
Makefile:50: recipe for target 'all' failed
make: *** [all] Error 2

```
# **Environment**

Ubuntu 18.04.6 LTS (docker)
clang 12.0.1
clang++ 12.0.1
Bento4 master branch(21b2640)

**Comment by trufae** [comment]
how are you compiling r2 statically? and which version (git?)

**Comment by DylanSec** [comment]
> how are you compiling r2 statically? and which version (git?)

The git version for 2.17.1

Compilation steps are:
export CFLAGS="-flto -fuse-ld=gold -Wl,-plugin-opt=save-temps -fsanitize=address"
export CXXFLAGS="-flto -fuse-ld=gold -Wl,-plugin-opt=save-temps -fsanitize=address"
export CC=clang
export CXX=clang++
cd radare2
./sys/static.sh

**Comment by trufae** [comment]
i mean the version of radare2 (if it's from git or release).

It works fine for me (ubuntu 22.04 with gcc and macOS 12 with clang and the CI workers (vs, clang)). 

from the error messages above i would say that maybe it's because you are compiling on a dirty working directory :? is this a clean checkout if not `git clean -xdf; rm -rf shlr/capstone;sys/static.sh`.

i'm not using any commandline flag, but fsanitize, flto and static flags are going to require a shiton of ram.

You can also try buildilng with meson (see the linux-static-meson job from the ci yaml files), but in short its sthg like this:

```
        CFLAGS="-static" LDFLAGS="-static" meson --prefix=${HOME}/.local --buildtype release --default-library static build
        ninja -C build && ninja -C build install

```

**Comment by DylanSec** [comment]
> i mean the version of radare2 (if it's from git or release).
> 
> It works fine for me (ubuntu 22.04 with gcc and macOS 12 with clang and the CI workers (vs, clang)).
> 
> from the error messages above i would say that maybe it's because you are compiling on a dirty working directory :? is this a clean checkout if not `git clean -xdf; rm -rf shlr/capstone;sys/static.sh`.
> 
> i'm not using any commandline flag, but fsanitize, flto and static flags are going to require a shiton of ram.
> 
> You can also try buildilng with meson (see the linux-static-meson job from the ci yaml files), but in short its sthg like this:
> 
> ```
>         CFLAGS="-static" LDFLAGS="-static" meson --prefix=${HOME}/.local --buildtype release --default-library static build
>         ninja -C build && ninja -C build install
> ```

Thanks for your reply!
