### ISSUE TITLE
r2 gets stuck after a while just building up memory until the OS kills it (out of memory)

### ISSUE THREAD

**Issue by amaanq** [radareorg/radare2#20902]
## Environment

```sh
Sun Oct 16 01:45:33 EDT 2022
radare2 5.7.9 29203 @ linux-x86-64 git.5.7.8-320-g8f0e9451b7
commit: 8f0e9451b781fc0b239bf1c0e0905be039a7ead3 build: 2022-10-16__01:38:28
Linux x86_64
```

## Description

Running aaa on an android shared object (~25mb in size) results in r2 being stuck where ctrl+c doesn't work after about 15-20 seconds, and it just keeps piling up in memory usage. After about 10 minutes it dies (I have 64gb of ram so it takes a while..)

I believe this is just specific to either arm, or some set of instructions in this binary. The issue doesn't happen with an arm64 version of the same shared library

## Test

Run aaa large arm binary? Or I can upload the binary if desired

**Comment by trufae** [comment]
Thats probably a regression in capstone. Im aware of some bugs they inteoduced recently and plan to fix them next week. You can use the last release or downgrade capstone to confirm and probably fix those problems

**Comment by trufae** [comment]
Can you try again with latest from git?

**Comment by amaanq** [comment]
> Can you try again with latest from git?

Had a friend test it, the bug still appears to exist sadly. I can test in 15 min

**Comment by trufae** [comment]
Ok, i found another memleak that happens when switching between arch/bits configurations because of the recent RArch refactoring. gonna fix it now. hope that makes the leak happy

**Comment by trufae** [comment]
omg found several more when testing on another machine, hold on, i hope to fix them all today before going to sleep so i'll ping you to test again. thanks for reporting :) i wasnt planning to do any leakfixing yet, but guess it's worth :)

**Comment by amaanq** [comment]
thanks again! I wish I could be of more help, but I just started using r2 sorry :)

**Comment by trufae** [comment]
try again

**Comment by amaanq** [comment]
nope issue still exists, just hit 10gb of memory usage :sweat_smile:

**Comment by trufae** [comment]
Can you provide a reproducer?

**Comment by amaanq** [comment]
Yes, something else to know is that I decided to update my system-wide installation of libcapstone, as well as r2. Launching r2 now greets me with this error:
r2: error while loading shared libraries: libr_util.so: cannot open shared object file: No such file or directory

I tried downgrading my capstone installation but that did not help. I assume it has to do with the latest commit or 2?

Reproducer as of yesterday [here](https://cdn.discordapp.com/attachments/993606048768331809/1031962791160066240/libg-15.0.1.so) (discord.com)

**Comment by trufae** [comment]
How are you building r2? Because sys/install.sh takes care of the rpath and it seems like you have multiple installations of r2 too. Run "make purge" in the r2 folder

**Comment by amaanq** [comment]
Ran make purge, then sys/install.sh again and the issue still exists

**Comment by trufae** [comment]
Thanks for the binary. I have fixed some more memleaks and confirm i can repro, but i have reduced the amount of memory required quite a bit. For such sizes i wouldnt recommend to use `aaa` for this specific binary I think that `aab` works much better (finds 46000 functions in 3 minutes and takes 800MB of ram).

This is the PR i'm working on right now https://github.com/radareorg/radare2/pull/20918

**Comment by amaanq** [comment]
Thanks! I didn't know about aab, still learning how to navigate r2 :)

**Comment by amaanq** [comment]
I don't know if this is a bug or not, but better safe than sorry. When analyzing that binary I sent you, I get this a lot:

WARN: r_reg_get: assertion 'reg && name' failed (line 367)

(do note the binary does have quite the obfuscation built in :))

**Comment by trufae** [comment]
I dont get any of those messages, which make me think that you have mixed libraries of r2. Try running r2 -V.

Heavy memory sounds like a bug to me, the extra memory allocated is freed on exit and thats probably why it cant be detected as a leak and it makes it hardee to spot. but still it is good to learn how all the aa subcommands work instead of throwing a blind aaaaa to all the binaries you find.

also, bear in mind that current git is unstable and you may find releases more stable (until 5.8 is released).

**Comment by amaanq** [comment]
Output of r2 -V

5.7.8-359-g9010dd01e8  r2
5.7.8-359-g9010dd01e8  r_anal
5.7.8-359-g9010dd01e8  r_lib
5.7.8-359-g9010dd01e8  r_egg
5.7.8-359-g9010dd01e8  r_asm
5.7.8-359-g9010dd01e8  r_bin
5.7.8-359-g9010dd01e8  r_cons
5.7.8-359-g9010dd01e8  r_flag
5.7.8-359-g9010dd01e8  r_core
5.7.8-359-g9010dd01e8  r_crypto
5.7.8-359-g9010dd01e8  r_bp
5.7.8-359-g9010dd01e8  r_debug
5.7.8-359-g9010dd01e8  r_main
5.7.8-359-g9010dd01e8  r_fs
5.7.8-359-g9010dd01e8  r_io
5.7.8-359-g9010dd01e8  r_magic
5.7.8-359-g9010dd01e8  r_parse
5.7.8-359-g9010dd01e8  r_reg
5.7.8-359-g9010dd01e8  r_sign
5.7.8-359-g9010dd01e8  r_search
5.7.8-359-g9010dd01e8  r_syscall
5.7.8-359-g9010dd01e8  r_util

Thanks anyways! I'm very thankful for the fix to the main memory leak/problem. Closing now :)

**Comment by trufae** [comment]
Happy the leakfixes worked for you too. But i'm curious of this internal leak which is still referenced but unused 🤔

**Comment by trufae** [comment]
I did some more profiling and find out the root reason why its taking that much memory (that is freed later on closing) and that's because it uses too many hashtables, the r_ht strcture allocated too much data even if its empty, and the xrefs database makes an extensive use of this, i wrote in the last a data structure that will improve that a lot but it's not finished or commited. i'll think about ways to improve the runtime memory usage too! thanks for the motivation and usecase!
