### ISSUE TITLE
RFC: Deprecate r_str_new and r_str_dup

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#20959]
* [x] r_str_dup
* [x] r_str_new
* [x] R_STR_DUP
* [x] r_str_ndup / r_str_newlen

It can be tricky for rmalloc as strdup uses libc's malloc and r_str could use r_malloc alternative, causing inconsistencies between new/free and overcomplicates the logic. so maybe we can just move forward and just use strdup and deprecate those.

About r_str_new that could be kept for consistency with r_str_newf()

strdup() is available everywhere and works the same.
<img width="659" alt="Screenshot 2022-10-29 at 01 10 13" src="https://user-images.githubusercontent.com/6431515/198749018-bec4c973-3f28-4087-8672-74a92967747a.png">

**Comment by trufae** [comment]
its anoying to my eyes. but not really a blocker, moving forward

**Comment by Ashishbsharma** [comment]
Hi, I'd like to contribute to this issue, please guide me where to start.

**Comment by trufae** [comment]
As long as this is an abi breaking change this can't be done until we reach 5.9.9.

What can be done before:

* remove the use of all those calls to use only strdup()
* decide/discuss if its needed to have a nullchk version (as a macro) R_STRDUP  (or R_STR_DUP?)

What can't be done:

* remove the public functions

**Comment by trufae** [comment]
Feel free to join the discord for further discussions

**Comment by trufae** [comment]
thank you @satk0 !!
