### ISSUE TITLE
rax2: problem handling null byte in base64

### ISSUE THREAD

**Issue by sylvainpelissier** [radareorg/radare2#20978]
## Environment

```sh
Thu Nov  3 03:00:51 PM CET 2022
radare2 5.7.9 29889 @ linux-x86-64 git.5.7.8-447-g21ae2442cf
commit: 21ae2442cfb38bc13fc89693cd8a7145fd76eb33 build: 2022-11-03__11:01:43
Linux x86_64
```

## Description

When null byte are decoded from a base64 buffer rax2 does not continue the decoding.

## Test

```sh
$ rax2 -s 6500a5 | rax2 -E | rax2 -D | rax2 -S
65
```
A correct output would be:
```sh
$ rax2 -s 6500a5 | rax2 -E | rax2 -D | rax2 -S
6500a5
```

Another example:
```sh
$ rax2 -E "\x65\x00\x65"
ZQ==%
```
But the correct encoding is `ZQBl`

**Comment by trufae** [comment]
Thanks for taking care and fixing it too! <3

**Comment by sylvainpelissier** [comment]
I think the encoding part of the bug is not fixed yet.
