### ISSUE TITLE
radare2 -d exe: Missing file to open

### ISSUE THREAD

**Issue by franck-888** [radareorg/radare2#20988]
Problem is
C:\test>radare2 -d hello.exe
ERROR: Missing file to open

Any idea why ?

Other ways work well:
C:\test>hello.exe
hello
uninitialised t:  0
initialised t:    40

C:\test>radare2 -d hello.exe
ERROR: Missing file to open

C:\test>radare2 hello.exe
[0x004014e0]> q

C:\test>rarun2 program=hello.exe
hello
uninitialised t:  0
initialised t:    40

C:\test>radare2 -d C:\test\hello.exe
ERROR: Missing file to open

using radare2-5.7.8-w64.zip
on windows 10 (in qemu)

C:\Users\w>radare2 -v
radare2 5.7.8 1 @ windows-x86-64 git.5.7.8
commit: 8e965bef30457a12e07a32a9047a9620a944bc39 build: Tue 09/13/2022__16:36:59.94

Microsoft Windows [Version 10.0.19045.2130]

$ file hello.exe
hello.exe: PE32+ executable (console) x86-64, for MS Windows

Thanks

**Comment by franck-888** [comment]
Hi,
### On Windows 10, Fri 11 Nov 2022, using
C:\Users\w>radare2 -v
radare2 5.7.8 1 @ windows-x86-64 git.5.7.8
commit: 8e965be build: Tue 09/13/2022__16:36:59.94


Hi,
### On Windows 10, Fri 11 Nov 2022, using
```
C:\Users\w>radare2 -v
radare2 5.7.8 1 @ windows-x86-64 git.5.7.8
commit: 8e965be build: Tue 09/13/2022__16:36:59.94
```


### <1> To debug an exe: following ways work :-)

Way1:
```
C:\test>radare2 --d hello.exe
[0x004014e0]>
```

Way2:
```
C:\test>radare2 \d hello.exe
[0x004014e0]>
```

Way3:
```
C:\test>radare2 \-d hello.exe
[0x004014e0]>
```

Instead of:
```
C:\test>radare2 -d hello.exe
ERROR: Missing file to open
```

=> It may help others to mention above in documentation at
https://book.rada.re/first_steps/basic_debugger_session.html
after the provided linux example:
```
$ r2 -d /bin/ls
```


### <2> I could not figure how to debug a running process :-(

Documentation says
```
$ r2 -d 32220
```
https://book.rada.re/first_steps/basic_debugger_session.html

But 'radare2 -d PID' & variants report an error:

```
C:\test>tasklist
Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
...
hellosleep.exe                4604 Console                    7      2,928 K
...
```

```
C:\test>radare2 --d 4604
ERROR: Cannot open '4604'
```

```
C:\test>radare2 \d 4604
ERROR: Cannot open '4604'
```

```
C:\test>radare2 --d '4604'
ERROR: Cannot open ''4604''
```

```
C:\test>radare2 \-d 4604
ERROR: Cannot open '4604'
```

```
C:\test>radare2 -d 4604
ERROR: Missing file to open
```

```
C:\test>radare2 -d '4604'
ERROR: Missing file to open
```

```
C:\test>radare2 -d "4604"
ERROR: Missing file to open
```

I would be glad to hear how to proceed.

Thanks

**Comment by trufae** [comment]
You can use 5.7.6 or try the last build from the ci: https://github.com/radareorg/radare2/releases/download/5.7.8/radare2-5.7.9-w64.zip (^F for 5.7.9 in the release page of 5.7.8)

**Comment by franck-888** [comment]
Yes thanks all works nicely with 5.7.9 on Windows 10:

```
C:\test>radare2 -v
radare2 5.7.9 1 @ windows-x86-64 git.5.7.9
commit: bc25b92a28fc74534c005a5bacb36c86e8d36b16 build: Fri 11/11/2022__18:29:42.15
```

### <1> debugging an exe
```
C:\test>radare2 -d hello.exe
INFO: Spawned new process with pid 4384, tid = 2432
[0x7ffc4e4c2680]>
```

### <2> debugging a running process via PID
```
C:\test>radare2 -d 3140
[0x7ffc4bdc1104]>
```

### Lets close this ticket.
