### ISSUE TITLE
Invalid ASN.1 decoding of BIT STRING

### ISSUE THREAD

**Issue by sylvainpelissier** [radareorg/radare2#20993]
## Environment

```sh
Sun  6 Nov 16:01:59 CET 2022
radare2 5.7.9 29679 @ linux-x86-64 git.5.7.8-472-gf3a05a63e1
commit: f3a05a63e1c06872ac020a75608ac95deb0d9994 build: 2022-11-04__12:58:33
Linux x86_64
```

## Description
For some non zero number of unused bits in BIT STRING field of ASN.1 the content is not decoded properly by `pFa` command.

## Test

Correct decoding with a number of unused bits equals zero:
```sh
[0x00000000]> wx 030800016e500dc00001
[0x00000000]> pFa
   0     7: 0: prim BIT_STRING          : 016e500dc00001
```

Incorrect decoding with a number of unused bits equals one:
```sh
[0x00000000]> wx 030801016e500dc00000
[0x00000000]> pFa
   0     8: 0: prim BIT_STRING          : 
   2     1: 1: prim BOOLEAN             : true
```

For the last example the result should be `16e500dc0000` see for example: https://lapo.it/asn1js/#AwgEAW5QDcAAAA

**Comment by trufae** [comment]
Can you have a look at this issue?

**Comment by sylvainpelissier** [comment]
Yes, I'll look at it.
