### ISSUE TITLE
rabin2 -jM generates invalid JSON when main() isn't found

### ISSUE THREAD

**Issue by foobazjo** [radareorg/radare2#21020]
## Environment

Sat 12 Nov 2022 11:29:22 AM EST
radare2 5.7.8 29765 @ linux-x86-64 git.5.7.8
commit: 8e965bef30457a12e07a32a9047a9620a944bc39 build: 2022-11-10__18:15:28
Linux x86_64

## Description

Python/Java/jq parsers all find the invalid char in the JSON output produced:

...,"main":{}**,false,**"imports":[],...

No valid key/value is found where false is (not sure if a "duplicate" of the empty dict preceding)

## Test

rabin2 -jM tc 2>/dev/null | jq .

Attached is the "tc" binary from an old DIR-605L firmware without main apparently, not sure if it hides another bug.
[tc.gz](https://github.com/radareorg/radare2/files/9995442/tc.gz)

**Comment by foobazjo** [comment]
I just pulled the fix-json-jM branch and also realized there's another issue when -g is used to get all info. Initially I thought it was the same bug (e.g. -M included in -g).

**Comment by trufae** [comment]
yeah i though that was about to be a quick fix and im facing more awful bugs the more i dig, hope the person who wrote this code is having a good day now. hope to get this fixed by today

**Comment by trufae** [comment]
Please try again and confirm the bug is fixed, I didn't add any new test but it will be good to have some.

**Comment by foobazjo** [comment]
> Please try again and confirm the bug is fixed, I didn't add any new test but it will be good to have some.

-M seems fine but the -g mentioned above with issue in column 2946 is related to dwarf headers:

..."relocs":[],"dwarf":**,**"size":213556,"versioninfo"...

**Comment by trufae** [comment]
Im reopening . Ill add tests and check again

**Comment by trufae** [comment]
https://github.com/radareorg/radare2/pull/21053

**Comment by trufae** [comment]
Fixed
