### ISSUE TITLE
Discord invite link has expired

### ISSUE THREAD

**Issue by TheAllSeeingOwl** [radareorg/radare2#21047]
## Description

The discord invite has expired: https://discord.gg/UkkuYbNU

Need to update the README.md

**Comment by trufae** [comment]
thats the new one https://discord.gg/YBey7CR9jf for some reason discord decided to expire the unexpirable link -_- thanks for the heads up

**Comment by TheAllSeeingOwl** [comment]
#21048 https://github.com/radareorg/radare2/pull/21048

This was fixed in ^
