### ISSUE TITLE
X86_INS_POP , same ESP rule for X86_OP_REG as for X86_OP_MEM

### ISSUE THREAD

**Issue by ni7r0x** [radareorg/radare2#21052]
X86_OP_REG must follow the same ESP rule as X86_OP_MEM , otherwise wrong result will be produced if DST is ESP.
For example , the sequence : 
push esp
pop esp
will return esp = esp +4  instead of (old) esp .

Solution ( move sp increment before dst store) : 
[libr/anal/p/anal_x86_cs.c#L1240](https://github.com/radareorg/radare2/blob/master/libr/anal/p/anal_x86_cs.c#L1240)
`					esilprintf (op, "%s,[%d],%d,%s,+=,%s,=", sp, rs, rs, sp, dst);`

**Comment by trufae** [comment]
Can you make a PR instead of on opening an issue? from the website you can press the pencil button and edit the line. this way we can check for the testsutie and discuss the changes better.

**Comment by ni7r0x** [comment]
Just reporting, found the issue while testing another project forked from this one (rizin/cutter) , reported the issue there too.
Someone more familiar with the code base should address this.

**Comment by trufae** [comment]
well, there's not much to know about the codebase, you already provided the patch. i pushed this PR and i'll wait for the CI, do you have a test to reproduce the issue? https://github.com/radareorg/radare2/pull/21068

**Comment by trufae** [comment]
i see you reported a testcase and such in the other project https://github.com/rizinorg/rizin/issues/3191 . i'll just add and do my own tests and merge the fix tonight. thanks for reporting

**Comment by ni7r0x** [comment]
Sure , no problem .
Here is the test to reproduce : 
```
radare2 -a x86 -b 64 -

e io.cache=true
aei
aeim
ar rip=0 ; "wa push rsp ; pop rsp" @ 0 ; ?en rsp before : ; ?v rsp ; 2aes  ; ?en rsp after  : ; ?v rsp
```
Output : 
```
rsp before :0x178000
rsp after  :0x178008
```

**Comment by trufae** [comment]
Fixed in master! that was a really awful and longstanding emulation bug. thanks for all the work reporting and posting a reproducer that was really helpful!

**Comment by ni7r0x** [comment]
Thank you for all the great work , glad I could help !
