### ISSUE TITLE
Wrong output value of command "?iy"

### ISSUE THREAD

**Issue by nolongtail** [radareorg/radare2#21058]
## Environment

```sh
Sat Nov 19 02:17:18 PM +08 2022
radare2 5.5.0 0 @ linux-x86-64 git.5.5.0
commit: unknown build: 
Linux x86_64
```

## Description

First time making bug report, plz be gentle to me :)

I'm new to radare2 and learning it recently. However, when testing the command `?iy`, it shows weird behavior.
While pressing ENTER, `?iy` should return TRUE or 1 in `$?` but it returns 0 instead.

After reading the source code, the following lines are found faulty:
```c
r_core_return_value (core, r_cons_yesno (1, "%s? (Y/n)", input));
r_core_return_value (core, r_cons_yesno (0, "%s? (y/N)", input));
```
link of the [faulty lines](https://github.com/radareorg/radare2/blob/a06ade1796f89f4ae1049b2361ceaa4d5cf0c33e/libr/core/cmd_help.c#L1358)

## Test

1. run `?iy ; ? $?` and press ENTER
3. the Expected value should be 1 but it outputs 0 instead

## Possible Solution
simply changing the 1st argument of `r_cons_yesno` to the expected value 'y' and 'n' respectively. For example, [this line](https://github.com/radareorg/radare2/blob/ad1add71cbe462764ced47297a6f08d295838ade/libr/core/vasm.c#L83) and [this line](https://github.com/radareorg/radare2/blob/0b907689317044c5a7d58c85c4c97e5b376cb16b/libr/core/cmd_cmp.c#L512)

**Comment by trufae** [comment]
that works as expected in r2 from git., r2-5.5 is very old, please update
