### ISSUE TITLE
File and dir ownership in debian build

### ISSUE THREAD

**Issue by gordboy** [radareorg/radare2#21198]
## Environment

```sh
Fri 23 Dec 23:38:08 GMT 2022
radare2 5.8.0 1 @ linux-x86-64 git.5.8.0
commit: 7c55e4b61a5463262f5aa999ed52ba1cb777c198 build: 2022-12-22__23:41:43
Linux x86_64
```

## Description

The debian build files and dirs have the ownership `user:group` names of the build system, which when installed on the target system are all wrong. These files and dirs should all be `root:root` in the absence of a `radare2` user/group imho.

## Fix for now

Build your own deb, using `sys/debian.sh` as `root`

** OR **

Unpack `.deb` file, fix ownerships, then repack. This is not trivial for the n00b.

** OR **

Fix ownerships after installation. Again not trivial for the n00b.

**Comment by trufae** [comment]
Those debs are created by the CI, so that was just a matter of using fakeroot. thanks for spotting this issue !
