### ISSUE TITLE
install failed on mac os 13.0.1

### ISSUE THREAD

**Issue by paulhsu** [radareorg/radare2#21206]
## Environment

```
Macbook Pro 16, 2019
MacOS: 13.0.1
Darwin x86_64
```

## Description

install failed, encountered the following error

```
LD libr_util.dylib
ld: warning: ignoring file /Users/bossp/hack/radare2/libr/../shlr/zip/librz.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      _r_inflatew in zip.o
     (maybe you meant: _r_inflate_lz4, _r_inflate_raw , _r_inflate )
  "_inflateEnd", referenced from:
      _r_inflatew in zip.o
  "_inflateInit2_", referenced from:
      _r_inflatew in zip.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libr_util.dylib] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

## Test

doing `radare2/sys/install.sh`

**Comment by trufae** [comment]
Is this a clean checkout? Looks like the zip archive wasnt properly generated.

**Comment by trufae** [comment]
i mean i have the same mac and it builds fine here

**Comment by paulhsu** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/392958/211154783-e51749dd-8b06-40ac-b471-45aedae65c65.png">

@trufae I just pull the code again. And still has the same issue.

**Comment by trufae** [comment]
Do you have any custom flag in the environment? like CFLAGS/LDFLAGS? or maybe you need to fix your toolchain with `xcode-select --install`?

**Comment by trufae** [comment]
"the building for macOS-x86-64 but linking with file built with macOS-x86-64" makes me think that some files were built with a different version of the toolchain

**Comment by paulhsu** [comment]
@trufae 

on my mac
```
% xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" in System Settings to install updates

% xcodebuild -version
Xcode 14.1
Build version 14B47b
```

**Comment by trufae** [comment]
And the environment for custom flags or cc? Can you share the full verbose build log? I mean. It builds fine in all my macs as well as in the ci.

**Comment by paulhsu** [comment]
@trufae 

I solved this issue.

And the solution I found is from this [#17709](https://github.com/radareorg/radare2/issues/17709)

I look up my PATH. 

And I found that in my PATH I have `/usr/local/opt/binutils/bin` before `/usr/bin`.

After I move the position of `/usr/local/opt/binutils/bin` after `/usr/bin`. The `sys/install.sh` can work properly.

**Comment by trufae** [comment]
Yeah its a common issue. Binutils on mac conflicts with xcode

**Comment by trufae** [comment]
Thanks for sharing the solution. I didnt though about it even if i had the same issue some years ago. Hope that will help other users
