### ISSUE TITLE
Best Wishes to the entire Team

### ISSUE THREAD

**Issue by gordboy** [radareorg/radare2#21200]
## Description

We hereby acknowledge the exceptional dedication and application by the entire radare2 team, and wish them every fortune and success now, and in the future.

We have been critical and unkind at times, and are therefore unworthy of your bounty.

## Desired Outcome

We request that you stay true to the course, and regale us with more excellent treasures.

**Comment by trufae** [comment]
Thanks for the kind words but there's no such thing as a "team" or "organization", closing as this is not really an issue :)
