### ISSUE TITLE
How radare2 handles packed samples?

### ISSUE THREAD

**Issue by jasonma1127** [radareorg/radare2#21227]
## Description

Dear All,

Recently I did some comparative experiments on packed sample and unpacked sample.

I use UPX to pack the sample, it is a compressed packing tool.

Then, I used radare2 to reverse them and extract the opcode sequence, since I want to know how rich the opcode sequence can be extracted by radare2 when the sample is packed, and compare it with the unpacked sample.

The results show that there are three cases:

- Unpacked samples's opcode sequence are longer than packed samples's opcode sequence, which makes sense because packed samples should provide less opcodes then unpacked samples.
- Packed samples's opcode sequence are longer than unpacked samples's opcode sequence, this confuses me, how packed samples provide more opcodes then the original samples, the only explanation I think is that the extra opcodes belong to UPX and not to the sample itself.
- Packed samples's opcode sequence are as longer as unpacked samples's opcode sequence, fortunately, the opcode sequence is not exactly the same.

So could you please explain how radare2 handles packed samples?
Can radare2 extract the opcode from the compressed section? And how radare2 did it?
This will let me know more about the process of radare2 reverse engineering, or there are other materials that can be used for my reference and study.

I sincerely appreciate it.

**Comment by trufae** [comment]
This is not an issue or a feature request, please reopen the question into the discussions page. But r2 don't have anything magic or special about packed samples. So the procedure to unpack binaries is the same as with any other debugger out there.

Usually this process implies:

* Bypassing antidebug protections
* Find the right address to place a breakpoint
* Dump the uncompressed executable from memory
* Patch the binary in disk to adjust imports/headers to match the va layout
* profit
