### ISSUE TITLE
The build will fail if the path to radare2 repo contains '.c'

### ISSUE THREAD

**Issue by lveyde** [radareorg/radare2#21287]
## Environment

Linux x86_64 (RHEL 8.7)

## Description

It seems that if the path to radare2 repo contains '.c' then the build through sys/install.sh script will fail, as well as some manual build attempt with make, as it gets replaced with '.o'.

The build will finish with errors:
gmake[1]: *** [Makefile:26: all] Error 2
gmake: *** [Makefile:56: all] Error 2

and searching though the messages will give something like:
gmake[4]: *** No rule to make target '/tmp/test.oat/radare2/libr/../shlr/qjs/src/quickjs.o'.  Stop.

Please note that the actual directory name where the radare2 repo was located in this case was /tmp/test.cat/radare2/

## Test

./sys/install.sh

**Comment by trufae** [comment]
If your path have spaces or dots its better to use meson

**Comment by lveyde** [comment]
> If your path have spaces or dots its better to use meson

If it's a known issue then may be it worth to add it to the instructions, or at least add a note not to clone the repo into any directory with . (dot) in it's name.

BTW from my testing it seems that the issue was specifically with .c as having for example .d in the path was OK.
Of course I haven't tested all .[a-zA-Z] combinations.

**Comment by trufae** [comment]
Well this should be fixable. we have a ci job to test such things, but not for .c. just low prio for me because it makes no sense for me to have dots or spaces in directories. ill keep this open and address it when i get some spare time

**Comment by trufae** [comment]
Had few mins to check this issue and pushed a fix now. thanks for reporting!
