### ISSUE TITLE
Potential memory leak in libr/fs/p/fs_zip.c

### ISSUE THREAD

**Issue by icy17** [radareorg/radare2#21293]
Potential memory leak in [fs_zip.c](https://github.com/radareorg/radare2/blob/master/libr/fs/p/fs_zip.c) line 129. Calling zip_source_buffer_create() without calling zip_source_free() to free the memory will cause a memory leak. [Doc](https://libzip.org/documentation/zip_source.html) says "[zip_source_free(3)](https://libzip.org/documentation/zip_source_free.html) only needs to be called when these functions ([zip_open_from_source](https://libzip.org/documentation/zip_open_from_source.html)) return an error."
![image](https://user-images.githubusercontent.com/39425646/214763398-ace9318c-0ca4-4bf4-9f8e-9f871266102b.png)

**Comment by trufae** [comment]
Can u send a pukkreq instead of explaining the fix?
