### ISSUE TITLE
load plugins from multiple paths

### ISSUE THREAD

**Issue by milahu** [radareorg/radare2#21300]
## what

radare2 should load plugins from multiple paths

```sh
R2_LIBR_PLUGIN_PATH=/path/a:/path/b:/path/c r2
```

similar to MOZ_PLUGIN_PATH, QT_PLUGIN_PATH, QTWEBKIT_PLUGIN_PATH, ...

## why

make radare plugins play nice with package managers like nix

downstream issues:

- https://github.com/NixOS/nixpkgs/issues/86448#issuecomment-622337145
- https://github.com/radareorg/r2ghidra/issues/100#issuecomment-1407609683 (packaging for guix)

## current situation

(i hope that im wrong but ...)

currently, plugins are loaded from \*one\* path

either from `R2_LIBR_PLUGINS` (defined on compiletime)
or from `getenv("R2_LIBR_PLUGINS")` (defined on runtime)

https://github.com/radareorg/radare2/blob/510ddab0e523bed173b3954e5f61abf395812f7d/doc/plugins.md?plain=1#L1-L13

https://github.com/radareorg/radare2/blob/b8e6b52aacf145f36bfe3fba9f07b6a03013d084/libr/include/r_lib.h#L22

https://github.com/radareorg/radare2/blob/1100e12169dbdbe10081d4094129a5247738ecb1/libr/core/libs.c#L76-L78

https://github.com/radareorg/radare2/blob/abb7a7c749ca128b46426b05e2efaa138e254041/libr/util/lib.c#L357

```cc
R_API bool r_lib_opendir(RLib *lib, const char *path) {
// ...
#ifdef R2_LIBR_PLUGINS
	if (!path) {
		path = R2_LIBR_PLUGINS;
	}
#endif
```

## challenges

- deduplicate plugins #16431
- check if plugin version is compatible
- expose this function to plugins, so plugins can find other plugins

## workaround

use the R2_LIBR_PLUGINS env variable and symlink multiple plugins into one folder

## related

https://github.com/radareorg/radare2/blob/abb7a7c749ca128b46426b05e2efaa138e254041/libr/include/r_userconf.h.acr#L66

will be replaced by https://github.com/radareorg/radare2/pull/20545

```cc
#define R2_VERSION_ABI "@R2_VERSION_MAJOR@.@R2_VERSION_MINOR@.x"

#define R2_PLUGINS "lib/radare2/" R2_VERSION_ABI
#define R2_EXTRAS "lib/radare2-extras/" R2_VERSION_ABI
#define R2_BINDINGS "lib/radare2-bindings/" R2_VERSION_ABI
```

... ideally also support multiple paths for extras and bindings

**Comment by trufae** [comment]
Please submit the patch as a pullrequest its better place to discuss code changes than issues

**Comment by milahu** [comment]
sorry, this is low priority because has workaround

**Comment by trufae** [comment]
ill take a look when i have some spare time this or next week, thanks for reporting!

**Comment by trufae** [comment]
you can use the `R2_LIBR_PLUGINS` env var already but its just one string with the absolute path, i can split that with colons to support multoiple paths. but libr/core/libs.c already handles this env var
