### ISSUE TITLE
Screen width/height columns/rows

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#21312]
All that is confusing because of the names, so lets just find btter ones:

```
hex.cols = 16
scr.dumpcols = false
```

Do we want to keep cols/rows concept or better use scr.width and scr.height?

* scr.columns -> scr.cols
* scr.fix.columns -> scr.cols.fix
* scr.fix.rows -> scr.rows.fix

Also, we need a variable for the `cmd.cprompt`.. this is column prompt..

and we have hex.cols which can be scr.cols.hex and not sure whats for asm.minicols and scr.dumpcols

feedback is welcome is an easy change but needs some care

**Comment by alex-bender** [comment]
I suppose it's better to rename to scr.width and scr.height

These are obvious, you know that widht is a whole word stands for the size from left to right.
But cols, could mean anythin.

**Comment by trufae** [comment]
Its cols and rows because chars form a matrix. But width/height use to be about pixels

**Comment by alex-bender** [comment]
VT100 was introduced in 1978, so it's 45 years passed. I hope that at least after 100 years we will not think about our interface with computer as 80 chars puchcard.

Width could be measures with anything, not only pixels. even with chars. 

As for now -- i don't know what's dumpcols and have no any idea.

is that size of px dump? or anything else. gonna document all of that.

**Comment by trufae** [comment]
tired of waiting https://github.com/radareorg/radare2/pull/22591
