### ISSUE TITLE
arm/aarch64 gdb connection visual disassembled view, hiding extra registers.

### ISSUE THREAD

**Issue by Goyo2600** [radareorg/radare2#21329]
## Description
Using r2 to connect to gdb remotely to qemu-aarch64 -g 5555 ... or  qemu-arm -g 5555 ...

r2 -a arm -b 64 -D gdb -d gdb http://localhost:5555

We get a lot of registers in visual mode: (red circle).
![r2pantallazo](https://user-images.githubusercontent.com/29276865/217778919-ce7d17d1-d60e-4cdd-ac6b-238d9c047291.png)

The disassembled view with those registers is too  small, and I don't need to view those registers in visual mode for my projects.
In #radare2 chat, it was suggested the solution must be fixed in the gdb reg profile converter.

a rapid and simple patch for getting the same effect is in libr/reg/profile.c in parse_def function:
![pantallazo3](https://user-images.githubusercontent.com/29276865/217775677-81b19457-4553-475a-8db4-447b09262c7a.png)
**This is not a solution**, is a simple patch to hide those registers and get the dissasembled view in Visual mode with the desired effect:
![pantallazo2](https://user-images.githubusercontent.com/29276865/217776182-48888bb2-3d0a-48b5-a537-c607ddfbb691.png)

**Comment by trufae** [comment]
Uppercase registers should be ignored because those are not valid names for r2. But we can handle them as separate group in 5.9 because thats an abi breaking change

**Comment by trufae** [comment]
this fix should work for you and not break anything, for 5.9 i can introduce those new reg types and get this right, so we hav etime to check for other archs if thats the case or improve the parser.
thanks!
