### ISSUE TITLE
Build: openssl does not have use_ssl_crypto set

### ISSUE THREAD

**Issue by zlice** [radareorg/radare2#21332]
## Description

Builds with system openssl fail.

## Test

Build with `-Duse_ssl=true -Duse_sys_openssl=true`

```
The Meson build system
Version: 1.0.0
Source dir: /builddir/radare2-5.8.2
Build dir: /builddir/radare2-5.8.2/build
Build type: native build
Project name: radare2
Project version: 5.8.2
C compiler for the host machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the host machine: cc ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Program git found: NO
--- a/meson.build 2023-01-23 05:53:42.000000000 -0500
WARNING: You should add the boolean check kwarg to the run_command call.
--- a/meson.build 2023-01-23 05:53:42.000000000 -0500
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Message: r2 lib version: 5.8.2
Library dl found: YES
Run-time dependency threads found: YES
Library util found: YES
Library m found: YES
Configuring config.h using configuration
Library magic found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libxxhash found: YES 0.8.1
Message: Using system xxhash library
Run-time dependency openssl found: YES 1.1.1t
Message: Using system openssl library
Run-time dependency libuv found: YES 1.44.2
Message: Using libuv
Message: HAVE_PTRACE: true
Message: USE_PTRACE_WRAP: true
Message: R2_CHECKS_LEVEL: 2

meson.build:380:9: ERROR: Unknown variable "use_ssl_crypto".

A full log can be found at /builddir/radare2-5.8.2/build/meson-logs/meson-log.txt
```

## Patch

Not sure if this is right but `use_ssl_crypto` is set to `false` in the other two locations.

[meson_ssl.txt](https://github.com/radareorg/radare2/files/10702365/meson_ssl.txt)

**Comment by trufae** [comment]
the flags you are looking for are: `~/prg/radare2 $ meson b -Duse_ssl_crypto=true -Duse_ssl=true`

**Comment by zlice** [comment]
`-Duse_ssl_crypto=true` doesn't seem to fix the error on it's own.

`meson.build:380:9: ERROR: Unknown variable "use_ssl_crypto".`

**Comment by trufae** [comment]
Which version of meson are you using? That works for me

**Comment by zlice** [comment]
```
meson -v
1.0.0
```

I saw something in `libr/crypto/meson.build` that has `if use_sys_openssl and use_ssl_crypto`, I don't think this was being built with `use_ssl_crypto` in 5.7.8 https://github.com/radareorg/radare2/commit/5c0bde8ea01a6c3ac6966c8cec231019e4e1b9e7#diff-44656b68430e97b1845afb0def130e534944d68178ea85e77579f8273ed4d5b2R49

It also looks like the `use_ssl_crypto` default is supposed to be `false` in `meson_options.txt:option('use_ssl_crypto', type: 'boolean', value: false)`
