### ISSUE TITLE
Can't delete project

### ISSUE THREAD

**Issue by gur111** [radareorg/radare2#21400]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
r2 -v
uname -ms
```

OUTPUT:
```
Mon Feb 27 00:17:41 IST 2023
radare2 5.7.2 1 @ darwin-arm-64 git.
commit: 448fbfa1ffce69cd450365aa5ea9009ab3222d82 build: 2022-06-22__09:50:26
Darwin arm64
```

## Description
I tried to delete a project I created (copy pasted the suggested command) but it claimed an invalid option:
```
[0x100007fd8]> Ps mydock
A project with this name already exists. Use Ps-mydock to delete it.
Cannot save project.
[0x100007fd8]> Ps-mydock
Invalid project name '-mydock'
Cannot save project.
```

## Test

1. Save something as a project
2. Try to save again using the same name
3. Copy and paste the command from the error produced by the previous command
RESULT: Invalid option

![image](https://user-images.githubusercontent.com/7829415/221440852-d00f2157-7b47-4d44-8cbc-2841a6be63a1.png)

**Comment by gur111** [comment]
The issue is probably a typo in the hint.
Should probably just remove the `s` from the `Ps-<name>`

**Comment by trufae** [comment]
well, that version of r2 is really old. and the message and command has changed and it looks correct at least in git and the last release. So i don't consider this an issue anymore
