### ISSUE TITLE
Sync rax2 -r with r2's ? output (and reuse code)

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#21434]
```
[0x00000000]> ? 12884901880
int64   12884901880
uint64  12884901880
hex     0x2fffffff8
octal   0137777777770
unit    12.0G
segment 2ffff000:fff8
string  "\xf8\xff\xff\xff\x02"
fvalue  12884901880.0
float   nanf
double  0.000000
binary  0b0000001011111111111111111111111111111000
ternary 0t1020020222012211112011
[0x00000000]> 
```

vs

```
$ rax2 -r 123
hex     0x7b
octal   0173
unit    123
segment 0000:007b
int32   123
string  "{"
binary  0b01111011
float:  0.000000f
double: 0.000000
ternary 0t11120
```

**Comment by 167rgc911** [comment]
Is this worth submitting as a PR?

https://github.com/radareorg/radare2/compare/master...167rgc911:radare2:rax2_mods

<rgc@:b:292>./binr/rax2/rax2 -r 12884901880
int64   12884901880
uint64  12884901880
hex     0x2fffffff8
octal   0137777777770
unit    12.0G
segment 2ffff000:0ff8
string  "\xf8\xff\xff\xff\x02"
float   -nanf
double  0.000000
binary  0b0000001011111111111111111111111111111000
ternary 0t1020020222012211112011
<rgc@:b:293>./binr/radare2/radare2 --
[0x00000000]> ? 12884901880
int64   12884901880
uint64  12884901880
hex     0x2fffffff8
octal   0137777777770
unit    12.0G
segment 2ffff000:fff8
string  "\xf8\xff\xff\xff\x02"
fvalue  12884901880.0
float   nanf
double  0.000000
binary  0b0000001011111111111111111111111111111000
ternary 0t1020020222012211112011

**Comment by trufae** [comment]
Why not?

**Comment by trufae** [comment]
Thanks!
