### ISSUE TITLE
DWARF hardcodes ELF section names

### ISSUE THREAD

**Issue by terorie** [radareorg/radare2#21466]
## Description

`libr/bin/dwarf.c` looks up DWARF sections by names that are ELF-specific.

https://github.com/radareorg/radare2/blob/86b5d8e4ab198619c7528c94bac977f84f722586/libr/bin/dwarf.c#L2508

This is a problem because:
1. Other binary formats (e.g. XCOFF) use different names (e.g. `.dwline` instead of `.debug_line`)
2. Other binary formats discover sections by numeric identifiers not strings (e.g. on XCOFF, where the string `.dwline` as section name is technically optional -- the flags bitfield decides the type of the section)

## Suggested Fix

There should be an abstraction for discovering DWARF sections to be implemented by the respective bin plugins. The `dwarf.c` code should retrieve this info via the abstraction and not hardcode any lookups. Possible ways to do this:

A -- Add callback function  `.dbginfo` 
B -- Add more metadata to RBinSection
C -- Change the affected bin plugins (e.g. XCOFF) to hijack the names to change `.dwline` => `.debug_line`, etc. Works without changes to core but hacky

**Comment by trufae** [comment]
What about adding a field in rbinsection specifying the section contains debug information instead of adding a new callback? I think for now we can hardcode this in dwarf.c or at least make some assumptions from there because dwarf.c have access to rbin and knows the file format that is loaded

**Comment by trufae** [comment]
Imho B sounds like a good solution but that will break abi. So i would go for modifying dwarf.c to use the right sectionname depending on plugin used. I dont think we wikl find much more different names to justify bigger breaking changes

**Comment by trufae** [comment]
Can you do a PR with the quickfix (adding the coff dwarf names in dwarf.c depending on the plugin used?)

**Comment by trufae** [comment]
ping @terorie

**Comment by trufae** [comment]
Ping ...

**Comment by terorie** [comment]
Super sorry @trufae Job and life things swamped me. I can't guarantee I can get to this soon... Feel free to take my PRs over if you guys are looking for work...

**Comment by trufae** [comment]
Nobody is looking to contribute or so. Dont feel bad life events suck and there’s no pressure on anything. If anyone really cares about this issue it shouldnt take much time to get fixed, i was just trying to get an update to wrap up remaining tickets to cut a release and organize my time. Thanks for replying, hope things get better soon in your side <3

**Comment by terorie** [comment]
@trufae A simple fix is available in #22449.

I appreciate the kind words, all is well. I hope you're doing good too! It's my first radare PR since moving out from my parents house :)
