### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by albert-github** [radareorg/radare2#21489]
https://github.com/radareorg/radare2/blob/09169f97f7f313fb52af88720a9d9b06d625774c/README.md?plain=1#L86

link `(#Contributing) ` should be `(#contributing) `

https://github.com/radareorg/radare2/blob/09169f97f7f313fb52af88720a9d9b06d625774c/README.md?plain=1#L119

link `(#Community)` should be `(#community)`

**Comment by trufae** [comment]
Press the pencil button and make a pr instead of an issue

**Comment by albert-github** [comment]
I don't think it is completed as I don't see any changes, I just signaled the problem I have not interest in radare so if you won't fix it it is up to you.

**Comment by trufae** [comment]
I just recorded a video to show you the process and make the pr for. I was afk walking in the street so its from phone. I dont know what are you talking abiut downloading files or antiviruses

https://mastodont.cat/@pancakenews/110027700872131653

**Comment by albert-github** [comment]
> I dont know what are you talking abiut downloading files or antiviruses

whilst I opened the file to edit it on GitDev it was setting up a web editor and also started to download one or another index file as my virus scanner kicked in.

**Comment by trufae** [comment]
I just arrived at home and i dont think the patch is correct. the titles of the sections are capitalized already and they work if clicked. Am i missing anything?

**Comment by albert-github** [comment]
Yes, the link titles are in capitals but the link should be all in lowercase as can be seen when hovering over the section title and the "chain" appears:
![image](https://user-images.githubusercontent.com/5223533/225341510-6117a07c-50c9-4d65-b251-883ac4fca50a.png)

Automatic links on GitHub should be in lowercase (that the browser shows it correctly when the case is not correct is useful for the user but is in fact incorrect).

**Comment by trufae** [comment]
merged
