### ISSUE TITLE
aaa detects much less functions than Ghidra

### ISSUE THREAD

**Issue by yuzhichang** [radareorg/radare2#21592]
## Environment

Wed Apr 12 09:45:47 PM CST 2023
radare2 5.8.5 30228 @ linux-x86-64 git.5.8.4-111-g4968d69f18
commit: 4968d69f1848c2f9f2333d649a845009b59ba2a7 build: 2023-04-10__09:53:17
Linux x86_64

## Description

Ghidra detects 15429 functions for stripped ELF `1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so`, see the following attached:
[1.41.1-310.csv](https://github.com/radareorg/radare2/files/11212163/1.41.1-310.csv)

```
$ cat 1.41.1-310.csv | wc -l
15430
```

r2 aaa detects only 6644 functions.

For example, r2 missed `0x00167ab0`, which happens to be the one I'm interested at. Ghidra fid analysis says it's `grpc_chttp2_maybe_complete_recv_initial_metadata`.

![image](https://user-images.githubusercontent.com/153784/231482298-8aecd707-8b81-4985-8e6f-65e35c05d451.png)

![image](https://user-images.githubusercontent.com/153784/231482459-5f6e34bc-604c-44df-93ec-7d80abe017b8.png)

**Comment by trufae** [comment]
`e anal.vars=false;e anal.hasnext=true;afr;aac` is probably the best way to go. dont run `aaaa` and expect it to be good or fast. it all depends on the target and use cases. surely default analysis could be better, but that requires testing and maintainance, and i dont have much time for handling more things

**Comment by trufae** [comment]
can you share the sample?

**Comment by yuzhichang** [comment]
`e anal.vars=false;e anal.hasnext=true;afr;aac` detects more functions including `0x00167ab0` but still miss some on which I'm interested in. Another drawback I noticed that `afr` doesn't  analyze function arguments. I think arguments size matching could be very helpful at `zbr` and `zb`.

```
zhichyu@ck98:~/grpc_whl$ r2 pypi/1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
WARN: run r2 with -e bin.cache=true to fix relocations in disassembly
 -- Use 'zoom.byte=printable' in zoom mode ('z' in Visual mode) to find strings
[0x00075100]> e anal.vars=false;e anal.hasnext=true;afr;aac
WARN: Cannot find basic block for switch case at 0x00405d8f bbdelta = 21
WARN: Cannot find basic block for switch case at 0x004054b4 bbdelta = 28
WARN: Cannot find basic block for switch case at 0x004051c4 bbdelta = 28
WARN: Cannot find basic block for switch case at 0x004049b1 bbdelta = 23
WARN: Cannot find basic block for switch case at 0x005aacd2 bbdelta = 20
WARN: Cannot find basic block for switch case at 0x00176d47 bbdelta = 71
WARN: Cannot find basic block for switch case at 0x001790c6 bbdelta = 35
WARN: Cannot find basic block for switch case at 0x005be384 bbdelta = 28
WARN: Cannot find basic block for switch case at 0x005c1f6e bbdelta = 33
[0x00075100]> aflc
14376
[0x00075100]> afi 0x00167ab0
#
offset: 0x00167ab0
name: fcn.00167ab0
size: 139
is-pure: false
realsz: 128
stackframe: 24
call-convention: amd64
cyclomatic-cost: 46
cyclomatic-complexity: 6
bits: 64
type: fcn [NEW]
num-bbs: 8
num-instrs: 29
edges: 10
minbound: 0x00167ab0
maxbound: 0x00167b3b
is-lineal: false
end-bbs: 2
call-refs: 0x00167b10 J 0x00167b06 J 0x00167b18 J 0x0017d380 C 0x002297d0 C 0x002ac350 C 0x00167ad5 J 0x002ac350 C 0x00167ad5 J
data-refs: 0x00000660 0x00000790 0x000007a0
noreturn: false
in-degree: 0
out-degree: 4
data-xrefs:
locals: 0
args: 0
diff: type: new[0x00075100]> aaa
INFO: Analyze all flags starting with sym. and entry0 (aa)
INFO: Analyze function calls (aac)
INFO: Analyze len bytes of instructions for references (aar)
INFO: Finding and parsing C++ vtables (avrr)
INFO: Type matching analysis for all functions (aaft)
INFO: Propagate noreturn information (aanr)
INFO: Use -AA or aaaa to perform additional experimental analysis
[0x00075100]> afi 0x00178c90
[0x00075100]> aflc
14934
```

Ghidra says `0x00178c90` is `grpc_chttp2_header_parser_parse`.

![image](https://user-images.githubusercontent.com/153784/231630103-5783b45b-aa96-4438-bbb4-9f03879c780b.png)

![image](https://user-images.githubusercontent.com/153784/231630228-eb371d96-e4d3-4ca0-b996-5787cf0fc064.png)

**Comment by trufae** [comment]
`e anal.vars=false` is the one in charge of analyzing the function arguments too. so skip that if you need them.

the warnings show some incorrect cases of jump table analysis, if this function is referenced from a call the `aac` should be finding it. There are some conservative checks too. but i'll try when i get the file.

you can zip it and attach it to the issue or send it to my pesonal email (pancake@nopcode.org) or upload it somewhere and send me the link or via telegram, matrix, discord, etc..

**Comment by yuzhichang** [comment]
@trufae forwarded the simple to [pancake@nopcode.org](mailto:pancake@nopcode.org)

**Comment by trufae** [comment]
received now

**Comment by trufae** [comment]
looks like in `0x00167ab0` there's no code in that address. ive loaded the same file in ghidra and it says the same as r2. this offset is not part of any function. also ghidra is loading the binary in a different offset. so if you do `r2 -B 0x100000 ...` both offsets in ghidra and r2 are the same. so that works fine

<img width="1220" alt="Screenshot 2023-04-13 at 17 45 22" src="https://user-images.githubusercontent.com/6431515/231813857-3068b72d-d628-4e05-8e22-d307a18e5814.png">

the function you are looking for `grpc_chttp2_header_parser_parse` is at 0x271590 and for me if i do `aaa` in r2 without any special flag i get the function analyzed and found the same way its shown in ghidra. so my guess is that you are analyzing a different file in ghidra

**Comment by trufae** [comment]
```
[0x00271590]> aflc
14934
[0x00271590]> e anal.hasnext
false
[0x00271590]>
```

**Comment by yuzhichang** [comment]
The mail title is "stripped ELF of #21592".
Here's the file size and checksum:
```
zhichyu@ck98:~/grpc_whl$ ls -l pypi/1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
-rwxr-xr-x 1 zhichyu eoi 8554128 Mar 17 13:13 pypi/1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
zhichyu@ck98:~/grpc_whl$ md5sum pypi/1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
2d2164047fdf0e73b272bc37cd10dcbc  pypi/1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
zhichyu@ck98:~/grpc_whl$ r2 pypi/1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so
WARN: run r2 with -e bin.cache=true to fix relocations in disassembly
 -- Step through your seek history with the commands 'u' (undo) and 'U' (redo)
[0x00075100]> e anal.hasnext=true;afr;aac
WARN: Cannot find basic block for switch case at 0x00405d8f bbdelta = 21
WARN: Cannot find basic block for switch case at 0x004054b4 bbdelta = 28
WARN: Cannot find basic block for switch case at 0x004051c4 bbdelta = 28
WARN: Cannot find basic block for switch case at 0x004049b1 bbdelta = 23
WARN: Cannot find basic block for switch case at 0x005aacd2 bbdelta = 20
WARN: Cannot find basic block for switch case at 0x00176d47 bbdelta = 71
WARN: Cannot find basic block for switch case at 0x001790c6 bbdelta = 35
WARN: Cannot find basic block for switch case at 0x005be384 bbdelta = 28
WARN: Cannot find basic block for switch case at 0x005c1f6e bbdelta = 33
[0x00075100]> aflc
14376
[0x00075100]> afi 0x00167ab0
#
offset: 0x00167ab0
name: fcn.00167ab0
size: 139
is-pure: false
realsz: 128
stackframe: 24
call-convention: amd64
cyclomatic-cost: 46
cyclomatic-complexity: 6
bits: 64
type: fcn [NEW]
num-bbs: 8
num-instrs: 29
edges: 10
minbound: 0x00167ab0
maxbound: 0x00167b3b
is-lineal: false
end-bbs: 2
call-refs: 0x0017d380 C 0x002297d0 C 0x002ac350 C 0x002ac350 C 0x00167ad5 J
data-refs:
noreturn: false
in-degree: 0
out-degree: 4
data-xrefs:
locals: 1
args: 0
var int64_t var_fh @ rsp+0xf
diff: type: new
```

**Comment by yuzhichang** [comment]
@trufae `aaa` and `afr` give different arguments. Is it normal? Here's the script to show the difference:

```
#!/usr/bin/env python3
import r2pipe, json, os.path

dir_notstripped = '/data01/zhichyu/grpc_whl/notstripped'
dir_pypi = '/data01/zhichyu/grpc_whl/pypi'

sos = '''1.41.1-cygrpc.cpython-310-x86_64-linux-gnu.so'''.splitlines()


def analyze(sofn: str, anal: str, fn_aflj: str) -> dict:
    sopath = os.path.join(dir_pypi, sofn)
    fp_aflj = os.path.join(dir_pypi, fn_aflj)
    r2 = r2pipe.open(sopath)
    r2.cmd('e zign.mangled=true')
    r2.cmd(anal)
    count = r2.cmd('aflc').strip()
    print('radare2 found %s functions' % count)
    funcs = r2.cmdj('aflj')
    f = open(fp_aflj, 'w')
    f.write(json.dumps(funcs, sort_keys=True, indent=4))
    f.close()
    print('created ' + fp_aflj + '\n')
    r2.quit()
    res = dict()
    for func in funcs:
        if func['type'] == 'fcn':
            res[func['name']] = func['signature']
    return res


def main():
    for sofn in sos:
        funcs1 = analyze(sofn, 'aaa', 'aaa.json')
        funcs2 = analyze(sofn, 'e anal.hasnext=true;afr;aac', 'afr.json')
        same = 0
        diff = 0
        for fn, sig in funcs1.items():
            if fn not in funcs2:
                continue
            sig2 = funcs2[fn]
            if sig != sig2:
                diff += 1
                print('different signature of ' + fn + ': ' + sig + '    ' + sig2)
            else:
                same += 1
        print('same %d, diff %d' % (same, diff))


if __name__ == '__main__':
    main()
```

A piece of output:
```
different signature of fcn.00623570: fcn.00623570 (int64_t arg1, int64_t arg2, int64_t arg7, int64_t arg8, int64_t arg9, int64_t arg10, int64_t arg11);    fcn.00623570 ();
different signature of fcn.00624e00: fcn.00624e00 (int64_t arg1, int64_t arg2, int64_t arg3);    fcn.00624e00 ();
different signature of fcn.00628620: fcn.00628620 (int64_t arg1, uint32_t arg2, uint32_t arg3, int64_t arg4);    fcn.00628620 ();
different signature of fcn.0062d170: fcn.0062d170 (int64_t arg1, int64_t arg2);    fcn.0062d170 ();
different signature of fcn.00629340: fcn.00629340 (uint32_t arg1, int64_t arg2, int64_t arg3, int64_t arg4);    fcn.00629340 ();
different signature of fcn.00629bb0: fcn.00629bb0 (int64_t arg1, int64_t arg2);    fcn.00629bb0 ();
different signature of fcn.00628f00: fcn.00628f00 (int64_t arg1, int64_t arg2, int64_t arg7, int64_t arg8, int64_t arg9, int64_t arg10, int64_t arg11);    fcn.00628f00 ();
different signature of fcn.0062a210: fcn.0062a210 (int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg_1b8h);    fcn.0062a210 (int64_t arg_1b8h);
different signature of fcn.0062a390: fcn.0062a390 (int64_t arg1, int64_t arg2, int64_t arg3);    fcn.0062a390 ();
different signature of fcn.00628480: fcn.00628480 (int64_t arg1, uint32_t arg2);    fcn.00628480 ();
different signature of fcn.0062a4e0: fcn.0062a4e0 (int64_t arg1, int64_t arg2, int64_t arg3);    fcn.0062a4e0 ();
different signature of fcn.0062a8d0: fcn.0062a8d0 (int64_t arg1, int64_t arg3);    fcn.0062a8d0 ();
different signature of fcn.0062b1c0: fcn.0062b1c0 (int64_t arg1, int64_t arg2, int64_t arg3, int64_t arg4, signed int64_t arg5, int64_t arg_1h);    fcn.0062b1c0 (int64_t arg_1h);
different signature of fcn.0062b480: fcn.0062b480 (char *s);    fcn.0062b480 ();
different signature of fcn.0062bc20: fcn.0062bc20 (int64_t arg1, int64_t arg2, int64_t arg3);    fcn.0062bc20 ();
different signature of fcn.0062b5b0: fcn.0062b5b0 (int64_t arg1, int64_t arg2);    fcn.0062b5b0 ();
different signature of fcn.0062b970: fcn.0062b970 (int64_t arg1, void *arg2, int64_t arg3);    fcn.0062b970 ();
different signature of fcn.0062b280: fcn.0062b280 (int64_t arg1, int64_t arg2, void *arg3);    fcn.0062b280 ();
different signature of fcn.0062d000: fcn.0062d000 (int64_t arg1);    fcn.0062d000 ();
different signature of fcn.0062c4e0: fcn.0062c4e0 (int64_t arg1, int64_t arg2);    fcn.0062c4e0 ();
same 636, diff 5123

```

**Comment by yuzhichang** [comment]
@trufae Any update on this?

**Comment by trufae** [comment]
No updates, i just pulled the binary from the mail (again), and confirmed all the same answers i gave you before:

* the offset 0x00167ab0 doesnt contain the begining of any function, but its part of the function you mention
* aflc prints `14527` and this is quite closer to what ghidra says
* if i run aaef;aab with anal.calls=true r2 finds `16416` functions which is more than ghidra.

i wonder whats the actual concern now. do you want to know why its different? or which functions r2 is issing? or which functions ghidra is wrongly identifying them as functions?

giving an more detailed answer requires reviewing every single function. and r2 already complains about some jump tables with unlinked basic blocks, but i didnt tried ghidra or compared every single function to see whats the difference.

So i would say that:

* r2 can find many more functions than ghidra when providing the right commands and configuration
* r2 analyzes code different than ghidra, so its normal that the results are different
* r2 is faster than ghidra
* the offset of the function you provide is not the begining of any function
* this is a library, so its normal that every reversing tool uses a different base address. use -B to use the same in r2 and ghidra

**Comment by yuzhichang** [comment]
Thanks for clarifying why ghidra and r2 differ. My last concern is `r2 already complains about some jump tables with unlinked basic blocks`. Could r2 miss detecting some functions due to these complains?

**Comment by trufae** [comment]
It means that r2 is identifying less branch destinations on a jump table. And those are considered separate functions instead of bbs of the same function. So the result may be larger

**Comment by trufae** [comment]
I consider this issue as fixed. Its ok to close it? You can keep asking if you have questions

**Comment by yuzhichang** [comment]
Thanks for answering.
