### ISSUE TITLE
The r2pm contained in version 5.8.4 does not work.

### ISSUE THREAD

**Issue by HKTangyuan** [radareorg/radare2#21666]
The r2pm contained in version 5.8.4 does not work in AlpineLinux.
I just install radare2 with r2pm by running "apk add radare2" in AlpineLinux.
![image](https://user-images.githubusercontent.com/109419998/235174001-8cc55ae2-56ff-42cd-bbb0-569bfda46550.jpeg)

**Comment by HKTangyuan** [comment]
The 5.6.8 version of radare2 with r2pm is working in AlpineLinux.
![image](https://user-images.githubusercontent.com/109419998/235174584-6421c2e7-045e-494e-afde-d17b705227b4.jpeg)

**Comment by trufae** [comment]
it works for me, as well as for the CI, can you show a backtrace or try with git version if there was something fixed in there?

**Comment by trufae** [comment]
i use alpine linux too and it works well there

**Comment by trufae** [comment]
no crash on alpine with r2-5.8.4 from pkg or built from git for me. maybe there's something different in your ~/.local/share/radare2 ? can you try renaming this directory temporarily just to confirm? if that doesnt fixes the problem then we have a bug i cant repro. But if its crashing still i would need some logs to understand why it's crashing and how to fix it

**Comment by HKTangyuan** [comment]
Maybe it is not supported to use the latest radare2 on AlpineLinux 3.16.

I modified the Alpine source to edge before installing radre2.

**Comment by HKTangyuan** [comment]
It's also can't working!
![image](https://user-images.githubusercontent.com/109419998/235177471-fb77bb92-fa7e-4bf8-bff3-f95ef2d0d121.jpeg)

**Comment by trufae** [comment]
Try installing it from git but if you can start r2 with gdb/lldb and show the backtrace and regs+disasm that could help me understand the problem. But if it works in git then just wait for 5.8.6

**Comment by HKTangyuan** [comment]
I’m sorry, I don‘t have enough time to verify whether this step can effectively solve this problem, and the r2 main program can still work well on my device, which is enough for me.

**Comment by trufae** [comment]
Can you try with 5.8.6?

**Comment by HKTangyuan** [comment]
> Can you try with 5.8.6?

Hi, I‘m glad to see that r2pm-5.8.6 works well on AlpineLinux, which will greatly help me solve some problems. I also admire your ability.👍🏼 Thank you for your help very much~

![image](https://github.com/radareorg/radare2/assets/109419998/6b1fd95e-9351-46ab-90c1-cb374085a300)

**Comment by trufae** [comment]
Sweet!
