### ISSUE TITLE
Incorrect Callgraph 16Bit DOS

### ISSUE THREAD

**Issue by alekasm** [radareorg/radare2#21669]
The callgraph traversal should stop on an int 0x20 (terminate program). Obviously if this doesn't happen, then data gets loaded as instructions which messes things up. Below is a screenshot with the int 0x20 instruction highlighted in a red box, data which is interpreted as instructions in a black box. The arrow shows where the retf will return to, a portion of code that will likely *not* be analyzed after the int 0x20 behavior is accounted for.

![image](https://user-images.githubusercontent.com/45739284/235386517-426e243d-3d4f-42b0-ac2b-184dcabcf843.png)

**Comment by trufae** [comment]
Yes this is called noreturn attribute you can set it by hand on any address if you know it. But if you provide the right syscall resolution tables it will be done automatically. Can you share a binary to test?

**Comment by alekasm** [comment]
Sure thing:
[INSTALL.zip](https://github.com/radareorg/radare2/files/11365999/INSTALL.zip)

**Comment by trufae** [comment]
It's fixed here https://github.com/radareorg/radare2/pull/21694 it's a workaround, but i added a test and im in the middle (already for a year) of a big refactoring, and i plan to review and improve all those bits without breaking tests when i finish that. so if it works it works :)
