### ISSUE TITLE
r2 fails to parse /proc/maps from the Android device via gdb remote protocol

### ISSUE THREAD

**Issue by detunized** [radareorg/radare2#21813]
## Environment

```sh
Wed May 31 19:11:45 CEST 2023
radare2 5.8.6 0 @ darwin-arm-64
birth: git.5.8.6 2023-05-05__15:36:00
commit: 5.8.6
options: gpl release -O1 checks=2
Darwin arm64
```

## Description

When I connect to a `gdbserver` running on an Android Arm64 phone I get the following:

```
r_debug_gdb_map_get: Unable to parse "/proc/27546/maps"
Content:
12c00000-12cc0000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
```

It seems to fails to parse the /proc/maps for the target process. I checked the r2 code and seems to expect something more of a filename in last place. Would it be possible to ignore the regions that don't parse or fix up their name to be able to proceed with the debugging? At this point the parsing function aborts the debugger.

## Test

I run the gdbserver on the phone like this:

```sh
gdbserver :1234 --attach $(pidof my.app.package.id)
```

I forward the the port to the host with `adb`:

```
adb forward tcp:1234 tcp:1234
```

And I simply launch `r2` and run the following command there and the following output:

```
[0x0000c500]> doof gdb://localhost:1234

WARN: Duplicated register definition for 'SP' has been ignored
r_debug_gdb_map_get: Unable to parse "/proc/28834/maps"
Content:
12c00000-12c80000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
r_debug_gdb_map_get: Unable to parse "/proc/28834/maps"
Content:
12c00000-12c80000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
```

No debugging is possible after this.

**Comment by trufae** [comment]
Can you try this branch? https://github.com/radareorg/radare2/pull/21815 and see if my blindfix works?

**Comment by detunized** [comment]
@trufae Wow, quick fix. I need to setup the dev env for this first. I have not tried to build yet. I simply installed with `brew`. `r2env` installation failed for me.

**Comment by detunized** [comment]
I managed to build with `./configure && make` and install it into `~/bin` via `make user-install` but it conflicts with the system installation of r2 and I don't want to delete it. Is there any way to run this locally from the source folder?

**Comment by detunized** [comment]
@trufae I tested this via `brew install --HEAD radare2`. I still get a similar error:

```
[0x0000c500]> doof gdb://localhost:1234
WARN: Duplicated register definition for 'SP' has been ignored
WARN: Cannot parse "/proc/11344/maps" with content: 12c00000-12c40000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
WARN: Cannot parse "/proc/11344/maps" with content: 12c00000-12c40000 rw-p 00000000 00:00 0                                  [anon:dalvik-main space (region space)]
```

There's no way for me to reopen this ticket. Should I open a new one?

**Comment by trufae** [comment]
I have reopen permissions ;)

**Comment by trufae** [comment]
Untested pr. need to find some time to test with real device https://github.com/radareorg/radare2/pull/21858 can you give it a try? its not merged yet

**Comment by trufae** [comment]
got the device setup and testing now

**Comment by trufae** [comment]
Fixed and tested :)

**Comment by detunized** [comment]
Thank you, @trufae! I will install from git soon and try. A local build doesn't work for me, only via `brew install --HEAD`.

**Comment by trufae** [comment]
Theres room for improvement but ill do that for the next release as its not a blocker. This should be good now :) thanks for reporting
