### ISSUE TITLE
radiff2 xdot 

### ISSUE THREAD

**Issue by lo-cloud** [radareorg/radare2#21836]
hi, when I use "radiff2 -g main a.out b.out | xdot -" , the xdot doesn't show the diffirences between the main function of the two binary files. The terminal prints the error:  "Error: <stdin>: syntax error in line 1 near 'Usage' and warning: "Warning: syntax ambiguity - badly delimited number '-1a' in line 1 of <stdin> splits into two tokens".

**Comment by trufae** [comment]
pass -m g if you want graphviz format, the default output is ascii art
