### ISSUE TITLE
afbr should show tail calls and jumps as exit instructions

### ISSUE THREAD

**Issue by chinmaydd** [radareorg/radare2#21847]
## Environment

```sh
radare2 5.8.7 30520 @ linux-x86-64
birth: git.5.7.2-2188-geb204788ff 2023-06-01__15:40:15
commit: eb204788ff2a517c03359546c1832a5813327469
options: gpl -O? cs:5 cl:2 make
```

## Description

According to the documentation `afbr` should show instructions that leave the function. However, this does not include tail calls and jumps. Note that the tails are identified but not included as part of the output. I guess the larger discussion is whether these should be included or not.

## Test

![image](https://github.com/radareorg/radare2/assets/6960646/750f9300-f704-46f9-a32e-7ce06c878df2)

Here, `0x00403f26` tail calls to `dbg.twist_` which implies that the execution leaves the current function frame. However, the output of `afbr` does not include this instruction.

![image](https://github.com/radareorg/radare2/assets/6960646/67a9dd96-d168-456b-8802-a970eb8aa0a9)

File is attached below (binary is compression utility pigz)
 
[pigz.gz](https://github.com/radareorg/radare2/files/11671248/pigz.gz)

**Comment by trufae** [comment]
Done in master
