### ISSUE TITLE
Demangle symbol names instead of flags only

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#2186]
There's no way to list all the demangled symbols of a c++ program, for example.

`rabin2 -D. bin` ?

**Comment by jvoisin** [comment]
What about:
```
rabin2 -D Cpp ./bin  # demangle all C++ symbols
rabin2 -D Cpp symbol ./bin  # demange the specific symbol
```

**Comment by radare** [comment]
-D expects <lang> and <symbolname> already, so -D have nothing to do
with `./bin` right now. not sure
if we should change this behaviour. but its a bit confusing imho

**Comment by XVilka** [comment]
:+1: for the changing behavior of '-D' command to be more logic.

**Comment by radare** [comment]
propose a change. i want to be able to demangle by hand.

**Comment by XVilka** [comment]
What about `-DD` command, like here is `-PP`, but for parsing binary then?

**Comment by ret2libc** [comment]
Is this still relevant?
I see this in the rabin2 help:
```
 -D lang name    demangle symbol name (-D all for bin.demangle=true)
```

So `rabin2 -D all bin` should do what proposed in the first comment. Closing for now, feel free to re-open if not alright.
