### ISSUE TITLE
Segfault when loading project created from analyzed RISC-V binary

### ISSUE THREAD

**Issue by lukasfink1** [radareorg/radare2#21907]
## Environment

```sh
Mi 14. Jun 21:40:18 CEST 2023
radare2 5.8.6 0 @ linux-x86-64
birth: git.5.8.6 2023-05-07__07:23:40
commit: unknown
options: gpl release -O1 checks=2
Linux x86_64
```

## Description

When performing an analysis (`aaa`) on the provided RV64 binary (it’s just a example hello world program, the bug also occurs with other binaries) and then saving a project, trying to load this project again will cause radare to segfault. This occurs with both the newest Arch Linux build and with the current (e2f21ac8d7) master.

The Segfault happens in [`libr/anal/fcn.c:1744`](https://github.com/radareorg/radare2/blob/e2f21ac8d75bbd5ca405c3df855fe955e182cffa/libr/anal/fcn.c#L1768), where `a->cur` seems to be NULL.

## Test
[hello.gz](https://github.com/radareorg/radare2/files/11750484/hello.gz)

```sh
$ gunzip hello.gz
$ radare2 hello
> aaa
> Ps hello
> q
$ radare2 hello
> P hello
[1]    159862 segmentation fault (core dumped)  radare2 hello
```

Edit: Fix typo

**Comment by trufae** [comment]
Can you try with r2-5.8.8 (or git?)

**Comment by trufae** [comment]
I cant reproduce. but i just added an extra nullchk in the line you pointed that out.

This code is going to be rewritten next week to not need so much checks
