### ISSUE TITLE
aaaaa analyze 

### ISSUE THREAD

**Issue by yazigegeda** [radareorg/radare2#21957]
## Description

*Please describe what are you missing or wanting to be improved*

*Provide images, ascii-art, test files and anything that may help us understand your request*

I use the aaaaa command to analyze the so Module file. When I exit r2, the next time I use r2 to open the so file, I have to enter the aaaaa command for analysis. Can't I save the analysis of the analyzed file?

**Comment by trufae** [comment]
Use the projects. See the -p flag and the P command
