### ISSUE TITLE
Open engineering inquiry printing

### ISSUE THREAD

**Issue by yazigegeda** [radareorg/radare2#21961]
When I open a project, it will endlessly ask me if I want to print and what to do

https://github.com/radareorg/radare2/assets/63853093/1beafd64-4e39-4232-adc7-b54dbc0f483f

![20230625_215754](https://github.com/radareorg/radare2/assets/63853093/54543e80-2f4d-46e4-84dc-4b570fec5bdc)

**Comment by trufae** [comment]
Oops. Guess i need to disable the interactive mode when loading projects. And you should press "y" otherwise it wont load

**Comment by yazigegeda** [comment]
> Oops. Guess i need to disable the interactive mode when loading projects. And you should press "y" otherwise it wont load

After pressing y, I printed a lot, but will I still be prompted to print?

**Comment by trufae** [comment]
Uhm it shouldnt print anythjng. Can you share the project?

**Comment by yazigegeda** [comment]
> Uhm it shouldnt print anythjng. Can you share the project?

[libcocos2djs.zip](https://github.com/radareorg/radare2/files/11860016/libcocos2djs.zip)

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/radare2/pull/21962

that was a neat finding :) thanks
