### ISSUE TITLE
Compile for android

### ISSUE THREAD

**Issue by xverizex** [radareorg/radare2#22028]
In newer version of android-ndk is using llvm. 
```
Generating r_version.h file

>>>>>>>>
HOST SDB
>>>>>>>>

gmake[4]: aarch64-linux-android-ar: No such file or directory
gmake[4]: *** [Makefile:46: libsdb.a] Error 127
gmake[3]: *** [Makefile:64: bin_deps] Error 2
gmake[2]: *** [Makefile:142: sdb-host] Error 2
gmake[1]: *** [Makefile:127: sdb/sdb] Error 2
gmake: *** [Makefile:51: all] Error 2
```

**Comment by trufae** [comment]
What commands did you run? Because there are sys/android*.sh scripts that do everything automatically

**Comment by xverizex** [comment]
I ran ./sys/android-build.sh arm64-static as have written in guide https://book.rada.re/first_steps/compilation_android.html

**Comment by trufae** [comment]
Do you have the ndk installed and configured? This thing runs in the ci for every commit

https://github.com/radareorg/radare2/blob/7832d2e89595fc8bde6ffb1808b84998a8d73b93/.github/workflows/build.yml#L254

**Comment by xverizex** [comment]
Ndk was installed, but not configured. I set path to Ndk. I try to install with meson, and it's done. But in further in found way to install arm apk from your release, and then I found way to install radare2 in termux with pkg manager. Thanks for your works.

**Comment by trufae** [comment]
Termux is the recommended and easiest way to use r2 in android :) closing this ticket then
