### ISSUE TITLE
Error when asm simple instruction using rasm2

### ISSUE THREAD

**Issue by syheliel** [radareorg/radare2#22061]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
r2 -v
uname -ms
2023年 07月 15日 星期六 19:16:27 CST
radare2 5.8.9 30943 @ linux-x86-64
birth: git.5.8.8-292-g5acdb23f4c 2023-07-15__19:00:31
commit: 5acdb23f4c4f8bdbdfac0c7f19679e3c9e77dac0
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

```
rasm2 -a riscv -b 64 -o 0x0 'auipc t0, 0x0'
ERROR: Cannot assemble 'auipc t0, 0x0' at line 3
```
 It is expected to be `0x297`:
 
![image](https://github.com/radareorg/radare2/assets/45957390/fac6ac6c-f419-46a7-83bd-b3db2ace35f9)

**Comment by trufae** [comment]
https://github.com/radareorg/radare2/blob/master/libr/arch/p/riscv/riscvasm.c

feel free to add it. Shouldnt be more than 1 line of code

**Comment by trufae** [comment]
Fixed in this PR, take it as inspiration to implement more instructions in the assembler if you are in the need and feel free to contribute back with a patch if you want
