### ISSUE TITLE
Can find any xrefs information

### ISSUE THREAD

**Issue by Ret2c7** [radareorg/radare2#22090]
## Environment

```sh
radare2 5.8.7 31247 @ linux-x86-64
birth: git.5.8.6-172-gc9469af1fd 2023-07-21__15:11:28
commit: c9469af1fdc29315f424ef1aba7e898809bdf05e
options: gpl -O? cs:5 cl:2 make
```
```sh
Linux x86_64
```

## Description

I generated a sdb file with rasign2，but i didn't can see any xrefs information.
It seems that all functions have no.
Maybe I'm missing some action or step，please let me know.
Here is the command I use.
```sh
clang-13 server.c -static -o server
```
```sh
rasign2 -o 1.sdb server
```

## Test

![image](https://github.com/radareorg/radare2/assets/59363523/e0828c85-2e88-4595-8448-0105dffc37a2)

![image](https://github.com/radareorg/radare2/assets/59363523/705ecea1-b0b9-4d3f-9d11-dab7b50315d2)

I can provide the files I use, maybe it will be useful:

[file.zip](https://github.com/radareorg/radare2/files/12122217/file.zip)

**Comment by swoops** [comment]
Try `rasign2 -a -o 1.sdb server` or with `-aa`.

**Comment by Ret2c7** [comment]
> Try `rasign2 -a -o 1.sdb server` or with `-aa`.

I tried, but the result is still the same

**Comment by trufae** [comment]
everything is fixed in https://github.com/radareorg/radare2/pull/22105 thanks for reporting

will be good to add some tests. can i use this binary for the testsuite? thanks!

**Comment by Ret2c7** [comment]
> everything is fixed in #22105 thanks for reporting
> 
> will be good to add some tests. can i use this binary for the testsuite? thanks!

Thank you for the repair. 
Of course, you can use this binary.

**Comment by trufae** [comment]
thank you!

**Comment by trufae** [comment]
fixed
