### ISSUE TITLE
xref data prevent normal works

### ISSUE THREAD

**Issue by xverizex** [radareorg/radare2#22100]
## Environment

```sh
Tue Jul 25 04:11:05 PM +05 2023
radare2 5.8.9 30940 @ linux-x86-64
birth: git.5.8.8-349-g514a33e144 2023-07-25__16:05:42
commit: 514a33e144d737ee99217aa9523b50b596a3754f
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description
![Screenshot_20230725_160823](https://github.com/radareorg/radare2/assets/21111024/091ccf25-7329-4b5f-8baa-8f507412b232)

## Test
```
aaaaa
V
```

**Comment by trufae** [comment]
Can you share the reproducer?

**Comment by xverizex** [comment]
I don't know what you meant work reproducer, but I think that you want sampler. Ok.

[HexFrontier.zip](https://github.com/radareorg/radare2/files/12160566/HexFrontier.zip)

**Comment by trufae** [comment]
can i use this binary for the testsuite? (is there any copyright issue or sthg that could be problematic?)

i just fixed this issue and also improved code coverage quite a lot. so thanks for sharing

**Comment by trufae** [comment]
fixed here https://github.com/radareorg/radare2/pull/22102 wait until merged to test, but i dont think it will regress any test

**Comment by xverizex** [comment]
Yes, you can use this binary, this is my game so that I agree.

**Comment by trufae** [comment]
Awesome! Thank you!
