### ISSUE TITLE
Patching binary display bug

### ISSUE THREAD

**Issue by 0xC-M0NK3Y** [radareorg/radare2#22107]
## Environment

```sh
mer. 26 juil. 2023 23:08:50 CEST
radare2 5.8.9 30962 @ linux-x86-64
birth: git.5.8.8-361-gaa72538816 2023-07-26__22:58:08
commit: aa72538816ef107736b5f2150a9fbba05542b2fa
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

When I try to patch a binary, as soon as I type one letter to write an assembly instruction, the whole binary becomes invalid.

For example:
![image](https://github.com/radareorg/radare2/assets/102142537/768eea80-4a79-40b5-b862-cd1cac25bcba)
then I do [shift] + a 
![image](https://github.com/radareorg/radare2/assets/102142537/3bdcf62f-a605-43d4-9c3f-3ec8da72f196)
then when I try to put a nop as soon as I type the letter n this happens
![image](https://github.com/radareorg/radare2/assets/102142537/6fb3888f-ca5c-40cb-a539-432360cc2f86)
then I put the nop and save the changes (while everything is displayed invalid), if I quit r2 and come back the binary was patched correctly
![image](https://github.com/radareorg/radare2/assets/102142537/db8a01d8-d396-4db1-bcc3-fe7d583d1ba7)
Normally this happens :
![image](https://github.com/radareorg/radare2/assets/102142537/d3d6c151-18be-43ed-b57e-b29bc10acaf7)
while I write everything update correctly

note: I recently switched to debian 12, I don't know why it would be the reason, but its working on another computer that runs debian 11

on the debian 11 machine where its working,  r2 -v :
```sh
radare2 5.8.5 1 @ linux-x86-64
birth: git.5.8.5 2023-04-24__11:19:35
commit: 480df2576404bac91f2af3865c2f4663f0751278
options: gpl -O? checks=2
```
## Test

I installed radare2 exactly this way:
```sh
git clone https://github.com/radareorg/radare2
cd radare2
./sys/install.sh
```

**Comment by trufae** [comment]
Thanks for reporting! its fixed in https://github.com/radareorg/radare2/pull/22108
