### ISSUE TITLE
"iz" and "izz" print wrong string addresses on Darwin kernel

### ISSUE THREAD

**Issue by Siguza** [radareorg/radare2#22110]
## Environment

```sh
% date
Fri Jul 28 10:19:55 CEST 2023
% r2 -v
radare2 5.8.9 31059 @ darwin-arm-64
birth: git.5.8.8-364-g7a2b40a9fd 2023-07-28__10:17:44
commit: 7a2b40a9fd470d18ebaa4a6b1966bddc8435b8a6
options: gpl -O2 cs:5 cl:2 make
% uname -ms
Darwin arm64
```

## Description

Example session:

```
% r2 iOS-16.6-20G75-d201ap,d20ap,d211ap,d21ap
SORTING KEXTs...
 -- Switch between print modes using the 'p' and 'P' keys in visual mode
[0xfffffff0071c4570]> iz~pineapple
234   0x0003b5db 0xfffffff00703f5bf 79   80   2.__TEXT.__cstring                                                             ascii   Just like pineapple on pizza, this task/thread port doesn't belong here. @%s:%d
[0xfffffff0071c4570]> ps@0xfffffff00703f5bf
221122112211221122112211221
[0xfffffff0071c4570]> 
```

`iz~pineapple` says the string `Just like pineapple on pizza, this task/thread port doesn't belong here. @%s:%d` should be at address `0xfffffff00703f5bf`, but it's not. The issue does not happen when `-Fmach064` is used.

Sample kernel: [iOS-16.6-20G75-d201ap,d20ap,d211ap,d21ap.gz](https://github.com/radareorg/radare2/files/12192131/iOS-16.6-20G75-d201ap.d20ap.d211ap.d21ap.gz)

**Comment by trufae** [comment]
Fixed in https://github.com/radareorg/radare2/pull/22111

**Comment by trufae** [comment]
Sorry for the delay im in vacations and busy irl. but the fix was merged already O:)
