### ISSUE TITLE
Add support for UF2 file format

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#22274]
documentation: https://github.com/Microsoft/uf2
sample file: [watch.zip](https://github.com/radareorg/radare2/files/12658034/watch.zip)

**Comment by aviciano** [comment]
I wrote a plugin some time ago [uf2-plugin](https://github.com/aviciano/uf2-plugin) & [r2pm](https://github.com/radareorg/radare2-pm/blob/master/db/uf2). It might be a starting point to implement more advanced stuff.

**Comment by trufae** [comment]
Woah totally forgot about it! you are right! we can close this issue now :) amazing!
