### ISSUE TITLE
UAF when quitting

### ISSUE THREAD

**Issue by skyler-ferrante** [radareorg/radare2#22293]
## Environment

```
$ date
Wed Oct  4 16:08:30 EDT 2023
$ r2 -v
radare2 5.8.9 31244 @ linux-x86-64
birth: git.5.8.8-640-g55e292681e 2023-10-04__16:03:36
commit: 55e292681e7bf624d8454ff06a063dd5b9efa318
options: gpl -O? cs:5 cl:2 make
$ uname -ms
Linux x86_64
```

## Description

Segfault from UAF when quitting.

```
$ r2 reproducer.out
 -- SHALL WE PLAY A GAME?
[0x00000402]> q
Segmentation fault
$
```

[reproducer.zip](https://github.com/radareorg/radare2/files/12807846/reproducer.zip)

Manually testing to see that address is freed and not reallocated.
```
$ gdb r2
...
(gdb) run reproducer.out
Starting program: /usr/local/bin/r2 reproducer.out
[0x00000402]> q

Breakpoint 1, r_bin_file_free (_bf=0x55555557a110) at bfile.c:778
(gdb) b malloc
Breakpoint 2 at 0x7ffff7c64120: malloc. (2 locations)
(gdb) b free
Breakpoint 3 at 0x7ffff7c64460: free. (3 locations)
(gdb) c
Continuing.
...
Breakpoint 3, __GI___libc_free (mem=0x5555556ebb10)
...
Program received signal SIGSEGV, Segmentation fault.
r_buf_fini (b=0x5555556ebb10) at buf.c:647
647             if (b->methods->get_whole_buf) {
(gdb) print b
```

The address `0x5555556ebb10` is freed and then used by `r_buf_fini`. The memory is not reallocated.

The issue seems to stem from `r_bin_file_free`.
It firsts calls `plugin->destroy (bf);` which seems to free `bf->buf`.

The reproducer is a file with `0xc2` repeated near the front, and it needs to be at least 1027 bytes long. I couldn't figure out the root cause of why r2 ends up treating this file different.

## Test

```
$ python3 -c "open('rep.out', 'wb').write(b'\0'+b'\xc2'*13+ b'\0'*1012)"
$ r2 rep.out
 -- Invert the block bytes using the 'I' key in visual mode
[0x00000402]> q
Segmentation fault
```

This issue does not seem present for version 5.8.8.

**Comment by trufae** [comment]
Thanks for reporting! the issue was that the RBin.avr plugin was freeing something that was not owned. it's now fixed in master :)
