### ISSUE TITLE
radare2 does not hook onto process by PID, attempts to open as file instead

### ISSUE THREAD

**Issue by ir0nstone** [radareorg/radare2#22303]
## Environment

```sh
$ date
Fri  6 Oct 17:47:58 BST 2023
$ r2 -v
radare2 5.8.9 31269 @ linux-x86-64
birth: git.5.8.8-655-gd0ab1aba8a 2023-10-06__17:17:41
commit: d0ab1aba8ac6e842c0377ca84ad923e36eb5881e
options: gpl -O? cs:5 cl:2 make
$ uname -ms
Linux x86_64
```

## Description

Attempting to get radare2 to debug a running process using the PID [as described in the radare2 book](https://book.rada.re/first_steps/basic_debugger_session.html) results in an error, as it appears to be assuming it is a file:
```
ERROR: Missing file to open
```
It appears this message is from `test/db/tools/r2`, although I'm not sure exactly what it is a result of:
```sh
$ grep -R 'ERROR: Missing file to open'
test/db/tools/r2:ERROR: Missing file to open
[... no other matches]
```
## Test
First, create `test.c`:
```c
#include <stdio.h>
#include <stdlib.h>

int main() {
    char *yes = malloc(0x40);
    fgets(yes, 0x40, stdin);
    return 0;
}
```
Then compile it with `gcc`:
```sh
gcc test.c -o test
```
Then start the program:
```sh
./test
```
While it is waiting for input, open another terminal and run `pidof test` to get the PID, then attempt to run `r2 -d <pid>` to attach to the PID:
```sh
$ pidof test
76113
$ r2 -d 76113
ERROR: Missing file to open
```

**Comment by trufae** [comment]
Fixed here https://github.com/radareorg/radare2/pull/22304

thanks for reporting, dunno when this regression was introduced 😱

**Comment by ir0nstone** [comment]
Brilliant!
