### ISSUE TITLE
ax.j throws an invalid JSON

### ISSUE THREAD

**Issue by cpuinfo** [radareorg/radare2#22344]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
date
Wednesday 25 October 2023 06:34:35 AM IST

r2 -v
radare2 5.8.5 30066 @ linux-x86-64 git.5.8.4-9-g9ad89fd980
commit: 9ad89fd9809fcddda50a144f435b18ec3a2c161a build: 2023-03-19__23:00:15

uname -ms
Linux x86_64
```

## Description

After using the command `ax.j sym.open` it throws an invalid JSON. There is an additional empty array i.e [] at the end of the output as show in the attached snapshot.

## Test
r2 any_binary
aaaaa
ax.j any_symbol 

eg. ax.j sym.connect

![Selection_399](https://github.com/radareorg/radare2/assets/69376519/5b018792-5959-454d-be7c-1d3c9074d9df)

**Comment by trufae** [comment]
here's the affected code:

<img width="463" alt="Screenshot 2023-10-25 at 09 49 08" src="https://github.com/radareorg/radare2/assets/6431515/5de445af-ad1e-434f-9c6a-7c3ba604e4ac">

this works fine without .j, so i would add an if( for the 'j'' case and construct the missing json part to specify if its "from" or "to" refs. this isbecause you are not using axtj or axfj.

would you like to submit the fix?
