### ISSUE TITLE
[AIX] Compile fail

### ISSUE THREAD

**Issue by terorie** [radareorg/radare2#22476]
## Description

AIX is IBM's UNIX distribution. r2 can't yet be compiled on it.

## Test

AIX is a proprietary OS and IBM is the only vendor.
It's basically impossible to get a license without getting the hardware.
It runs on IBM's POWER architecture.  As of recent, AIX is a 64-bit OS.

Be warned, setting up AIX for yourself is a massive pain.
The system seems very unstable for open source development, and nothing works out of the box. 

### Virtualization

If you have the AIX license sorted out, QEMU with powerpc soft MMU would probably run it.

### On real hardware

The US government owns a lot of IBM hardware that they are decommissioning, so if you are a US citizen, you can buy boxes in state auctions etc.

ebay.com seems like the best place to get them internationally. Good prices are about $2000 for a POWER8, $3000 for a POWER9.
However, some of the cheap boxes say they can only run Linux via OPAL. Unclear how to run AIX on them. 
Recent AIX "officially" support native virtualization with a "PowerKVM" Linux host. PowerKVM is only officially available on RHEL for POWER. Which, as you guessed it, is expensive and hard to get as an individual. Maybe mainline KVM works too.

### On IBM Cloud

IBM Cloud provides POWER9 servers, but those are ridiculously expensive.
A single core machines costs about $200-1000 per month and the disk I/O is terribly slow (few megs per second).
https://cloud.ibm.com/power/servers

After fighting with it for hours, I got things to run on a 1.0 core, 2GB RAM S922 server.
I used a 100GB external disk, but the larger you make your disk, the better the I/O is. (I got about 100 IOPS out of the 100GB disk, although IBM advertised 3 IOPS per GB... Still ridiculously slow and unusable)

Here are the installation steps that I used.

```shell
# Build Radare2 on IBM AIX 7.1

# Extend volume group and partitions to secondary disk

chdev -l hdisk0 -a pv=yes
chdev -l hdisk1 -a pv=yes
chvg -t 8 rootvg
extendvg rootvg hdisk0
extendvg rootvg hdisk1
chfs -a size=10G /usr
chfs -a size=10G /var
chfs -a size=10G /home
chfs -a size=10G /admin
chfs -a size=10G /opt  
chfs -a size=10G /   
chfs -a size=1G /tmp

# Install OpenSSL 

mkdir /tmp/newOpenSSL
cd /tmp/newOpenSSL
curl -o install.tar.Z https://iwm.dhe.ibm.com/sdfdl/v2/regs2/vikvicky/Xa.2/Xb.YpX6IhcfDwq01zIfDpwDtPq5DP1NQcv6HJEFTThXve0/Xc.openssl-3.0.10.1000.tar.Z/Xd./Xf.lPr.AAvi/Xg.12587434/Xi.aixbp/XY.regsrvs/XZ.eBpfO5QB0An12yYP5hjVspbVYnQfNCjQ/openssl-3.0.10.1000.tar.Z
uncompress install.tar.Z
tar -xvf install.tar
cd openssl-*
installp -qaXFY -d . openssl.base openssl.license openssl.man.en_US
cd /
rm -rf /tmp/newOpenSSL

# Install dnf 

cd /tmp
curl -o dnf_aixtoolbox.sh https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/ezinstall/ppc/dnf_aixtoolbox.sh
chmod +x dnf_aixtoolbox.sh
./dnf_aixtoolbox.sh -y
cd /

# Set up path

export PATH="/opt/freeware/bin:$PATH"

# Run dnf 

dnf update
dnf install git gcc make vim

# Build radare

git clone https://github.com/radareorg/radare2
cd radare2
./sys/build.sh
```

**Comment by mehendarkarprajwal** [comment]
Hi @riptl 
Following the steps given by you I was unable to build radare2 on AIX 7.3
Were you able to build it successfully and load AIX binaries using r2??

**Comment by trufae** [comment]
What errors did you get? I dont have any aix machine but i can do blind fixes

**Comment by riptl** [comment]
I forgot to pay my IBM Cloud bills so they banned my account, if I had an AIX machine I'd help
