### ISSUE TITLE
r2pm -U error on windows 10 : git not found

### ISSUE THREAD

**Issue by gogo2464** [radareorg/radare2#22499]
## Environment

```sh
> r2pm -ci r2yara
INFO: Cleaning r2yara
INFO: Using r2-5.8.8 and r2pm-5.8.8
ERROR: Please run r2pm -U to initialize/update the database
PS C:\PATH> r2pm -U
INFO: git clone --depth=10 --recursive https://github.com/radareorg/radare2-pm C:\Users\PATH\.local\share\\radare2\r2pm/git/radare2-pm
'git' is not recognized as a command
```

git --version
git version 2.43.0.windows.1

## Description

I would like to use r2yara on windows 10

**Comment by trufae** [comment]
Try installing git as reported by the error. But the r2yara package have no windows build instructions. So better go to the r2yara repo and do the meson/batch first so we can get native wndows builds in the ci and use a bin pkg from r2pm

**Comment by trufae** [comment]
This is not a bug or related to r2. Open the ticket or submit a pr in the r2yara repo instead

**Comment by gogo2464** [comment]
ok
