### ISSUE TITLE
Cursor mode bug with right/down key

### ISSUE THREAD

**Issue by kyufie** [radareorg/radare2#22520]
## Environment

```sh
Sun Dec 31 15:28:46 WIB 2023
radare2 5.8.9 115 @ linux-arm-64
birth: git.5.8.9 2023-12-30__18:10:17
commit: 9996cfeb3d38d4f61b220bca181538fd96ac3ddb
options: gpl -O? cs:5 cl:2 make
Linux aarch64
```

## Description
It looks like there is a bug with the cursor mode where it incorrectly sets the location of the cursor and the current offset.
Looks like it has something to do with __print_disassembly_cb which sets the screen_bounds to 1.
Which makes __cursor_down/__cursor_right thinks through __fix_cursor_down that the cursor is not visible.
Thus, adjusting the offset where it's not needed.
![Screenshot_2023-12-31-15-19-31-716_com termux-edit](https://github.com/radareorg/radare2/assets/50861563/46944edc-b75b-4155-83c4-a9312cc1b648)
![Screenshot_2023-12-31-15-19-11-082_com termux-edit](https://github.com/radareorg/radare2/assets/50861563/7b9c861a-534b-47f1-8a5d-a8a36dbd7243)

## Test
- Enter cursor mode in visual disassembly.
- Use right or down key in cursor mode.

### Initial state
![Screenshot_2023-12-31-15-30-32-496_com termux-edit](https://github.com/radareorg/radare2/assets/50861563/bb0081ea-d41b-47b9-81d7-d5041ee394b0)
### After right/down key
![Screenshot_2023-12-31-15-30-55-426_com termux-edit](https://github.com/radareorg/radare2/assets/50861563/a98cdd39-bb2a-4e8c-8bcb-7d95b98fc77b)

**Comment by trufae** [comment]
i can repro. i did a fix on this, but selection is not implemented in panels, which would be good to have at some point, feel free to give it a try and submit a better fix if you are in the mood :) thanks for reporting!

**Comment by kyufie** [comment]
Maybe someday :)

**Comment by NonLogicalDev** [comment]
Looks like this issue still persists on 5.9.9:

```
radare2 5.9.9 33376 @ darwin-arm-32
birth: git.5.9.8-466-gf91ccd923b 2025-03-09__16:34:39
commit: f91ccd923ba51275814a1b7204dbd22c4e61d766
options: gpl -O2 cs:5 cl:2 make
```

**Comment by NonLogicalDev** [comment]
Was able to "fix" that using a similar hack:

```
diff --git a/libr/core/panels.c b/libr/core/panels.c
index 4c4703b2a3..7490380e51 100644
--- a/libr/core/panels.c
+++ b/libr/core/panels.c
@@ -1654,7 +1654,7 @@ static void __cursor_right(RCore *core) {
 		cur->model->addr++;
 	} else if (__check_panel_type (cur, PANEL_CMD_DISASSEMBLY)) {
 		print->cur++;
-		__fix_cursor_down (core);
+		// __fix_cursor_down (core);
 	} else {
 		print->cur++;
 	}
```

**Comment by trufae** [comment]
@NonLogicalDev can you submit a pr instead?
