### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Ret2c7** [radareorg/radare2#22529]
the version of capstone
```bash
Name: capstone
Version: 5.0.1
Summary: Capstone disassembly engine
Home-page: https://www.capstone-engine.org
Author: Nguyen Anh Quynh
Author-email: aquynh@gmail.com
License: UNKNOWN
```

All the errors seem to come from the p/arm/plugin_cs.c file

![image](https://github.com/radareorg/radare2/assets/59363523/940489c9-dfc9-4bfd-930a-90ad1f27af05)

**Comment by trufae** [comment]
Maybe this capstone was compiled without arm64  support? Can you share more context like how did u installed capstone or the configure flags to r2?

**Comment by Ret2c7** [comment]
for the capstone：
```bash
pip3 install capstone
```

and for the radare2
```
curl -Ls https://github.com/radareorg/radare2/releases/download/5.8.8/radare2-5.8.8.tar.xz | tar xJv
radare2-5.8.8/sys/install.sh
```
I tried again, and the installation command is as follows. However, the output log indicates 'Cannot find system-wide Capstone.
The final error message displayed is as follows:
![image](https://github.com/radareorg/radare2/assets/59363523/bef08bbe-093a-4bb9-8bdd-c4a9706c5590)

**Comment by trufae** [comment]
Try building r2 from git. The last release is very old
