### ISSUE TITLE
Characters of a string after 2044th byte are discarded in string finding logic

### ISSUE THREAD

**Issue by israelsucks** [radareorg/radare2#22539]
## Environment

```sh
Wed Jan 17 14:20:34 EST 2024
radare2 5.8.9 31644 @ darwin-arm-64
birth: git.5.8.8-1011-g72e00141b3 2024-01-11__00:05:04
commit: 72e00141b32082394592a624ed8567fdb1051b3c
options: gpl -O2 cs:5 cl:2 make
Darwin arm64
```

## Description

String parser mechanism of radare2 has an issue which affects both r2 and rabin2. In `string_scan_range()` function of `bfile.c`, a stack buffer called `tmp` with hardcoded size of `R_STRING_SCAN_BUFFER` (which expands to 2048) is used to parse strings for any encoding. For every sting that are spotted in the input file, the loop in  `string_scan_range()` parses the found string and copies every char of it to the `tmp` buffer. Then this `tmp` buffer is `memcpy`ed to the final `RBinString->string`, which is then appended to the result `RList` to return. However, the string scanning logic cuts the search after the end of the `tmp` buffer is reached, and returns the result immediately. So strings larger than 2044 bytes are stored up to their 2044th byte.

Note that the limitation is 2044 bytes, not chars, so the length of result string will depend on encoding.

## Test
```
python3 -c 'print("A"*2044 + "B"*10000, end="")' > /tmp/abc.txt
rabin2 -izzz /tmp/abc.txt
# you should not see any "B" char in the output
```

**Comment by trufae** [comment]
check this out https://github.com/radareorg/radare2/pull/22543
