### ISSUE TITLE
PAC instructions can't be disassembled

### ISSUE THREAD

**Issue by crides** [radareorg/radare2#22547]
## Environment

```
Mon Jan 22 18:31:52 PST 2024
radare2 5.8.8 0 @ darwin-arm-64
birth: git.5.8.8 2023-06-08__13:54:42
commit: 5.8.8
options: gpl release -O1 cs:5 cl:2 make
Darwin arm64
```

## Description

PAC instructions (specifically `pacibsp` and `retab`, haven't tried others) can't be disassembled.

# Test

```sh
$ rasm2 'pacibsp'
7f2303d5
$ rasm2 -a arm -b 64 -d 7f2303d5
invalid
```

**Comment by trufae** [comment]
Works fine for me in with current code in git. If you cant repro in git the issue should be closed

**Comment by trufae** [comment]
![IMG_5799](https://github.com/radareorg/radare2/assets/6431515/5419db42-7c89-4b27-af31-3b4ff0f93e5b)

**Comment by crides** [comment]
current master works, closing

**Comment by crides** [comment]
Not the same but very similar issue on the git version:

`autda` can be disassembled:
```
$ rasm2 -a arm -b 64 -d 301ac1da
autda x16, x17
```
But not assembled:
```
$ rasm2 -a arm -b 64 "autda x16, x17"
ERROR: Cannot assemble 'autda x16, x17' at line 1
```

**Comment by trufae** [comment]
You can use the keystone or gas plugins to assemble those instructions. The default one is handwritten and none of the disassemblers use the same code to assemble, so its expected that sometimes some instructions cannot be assembled. Please create a new ticker or implement this one in armass64.c, it should be quite easy
