### ISSUE TITLE
Str represented as read for local variable

### ISSUE THREAD

**Issue by ShakeHakobyan** [radareorg/radare2#22552]
## Environment

```sh
Ուր 26 Հնվ 2024 07:22:08  +04
radare2 5.8.9 31576 @ linux-x86-64
birth: git.5.8.8-1011-g72e00141b3 2024-01-10__11:14:56
commit: 72e00141b32082394592a624ed8567fdb1051b3c
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

I have mentioned this problem several times — some store-type instructions are marked as read for local variables. This is the result of "afv=" command. 
![image](https://github.com/radareorg/radare2/assets/55894809/094a21e4-8c53-4a5d-bd9e-2db6e1a34d73)

## Test

[Here](https://drive.google.com/drive/folders/1A71e8VoyBadCfeXgR6YbTDFfPmypoG9g?usp=sharing) you can find my source file and binary file. Function name - "sym.foo3".

**Comment by trufae** [comment]
Can you provide the link to the other issues you reported this? Can you share a reproducer that i can use for testing? I assume and i know why this happens but without a repro its hard to say

**Comment by ShakeHakobyan** [comment]
I have not reported this problem before. I have just seen it a few times in my files. I found another file in which I have the same problem. In the [same folder](https://drive.google.com/drive/u/0/folders/1A71e8VoyBadCfeXgR6YbTDFfPmypoG9g) , you can find that file and its source too. I am compiling my source file with the `aarch64-linux-gnu-gcc` command and then opening it with `r2`, in case it will be useful for you.

**Comment by ShakeHakobyan** [comment]
In "edn" file the same problem is in the "sym.jpegdct" function.

**Comment by trufae** [comment]
fix was just 1 line. pls confirm

**Comment by ShakeHakobyan** [comment]
It's fixed, thank you!
