### ISSUE TITLE
agr and pdf are not in sync - call is present in agr, but pdf does not contain the reference, only in a comment

### ISSUE THREAD

**Issue by attilamester** [radareorg/radare2#22573]
## Environment

* r2 5.8.8

**Comment by trufae** [comment]
try with latest r2 from git. 5.8.8 is quite old already

**Comment by trufae** [comment]
R2-5.9 was suposed to be out 6 month ago. But i cant cope with more code alone so i had to move things for later because of the abi stable law. Hope to get things up in a month or so

**Comment by attilamester** [comment]
> R2-5.9 was suposed to be out 6 month ago. But i cant cope with more code alone so i had to move things for later because of the abi stable law. Hope to get things up in a month or so

@trufae I would be glad to help you with the release and the related coding, pr, testing, anything. My research depends on this project, so it is my interest as well to have a release as soon as possible and it would be a pleasure for me to help you. Please consider if you could use my help, and let me know.

**Comment by trufae** [comment]
Is a release really a blocker for your project? I was quite busy irl these days, but I hope to reorganize the issues during the weekend and reduce my expectations to focus on having a release before the end of this month. 🤞

Focus on your ticket first, so you can at least handle your needs. Feel free to join the discord or telegram chats for further conversations.

**Comment by attilamester** [comment]
Closing this issue - a more precise description of the problem is in https://github.com/radareorg/radare2/issues/22576
