### ISSUE TITLE
publish checksums.txt with github releases for verification

### ISSUE THREAD

**Issue by ekristen** [radareorg/radare2#22633]
## Description

Could you please publish a checksums.txt file along with your release assets? 

This would help with verification and automated updates with a project I have that I maintain that installs radare2.

Thanks.

**Comment by ekristen** [comment]
P.S. hi @radare long time no chat :) hope you are doing well.

**Comment by prodrigestivill** [comment]
Hello @ekristen,

Have you considered to use [this GitHub API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release) to detect new releases (either by detecting changes by `id` or `tag_name`)?

For my understanding this API endpoint also works without GitHub credentials although being rate limited.

Even that the checksums file can be generated alongside for each release, we first need to undestand better what you need.

First keep in mind that to validate downloads just by downloading files using TLS (HTTPS) you already have the content validation at transport level.

Another thing would be to sign those checksums using GnuPG.

In any case, if you can clarify us better what is your exact requirement so we can discuss further how we can help fulfill the best solution.

Thanks in advance.

**Comment by trufae** [comment]
Hey @ekristen!

Lots of personal ups and downs lately, but sorting out things.

I have mixed feelings about the checksums file because it's often used as a security measure in case the files has been modified, so for security this file should be stored in a 3rd party server. which could be in this case radare.org.

But if the purpose is to ensure nothing has changed or the files has been downloaded properly or no mitm happened then i guess putting that file directly in the release page will be fine. As @prodrigestivill says, signing those files with gnupg is probably a better solution, as well as storing the file in another server to increase trust will be good too.

Let me/us know what works the best for you and we will come up with a solution :)

Hope everything is going well in your side, and happy to hear from you and glad to know that r2 is part of more projects here and there! Feel free to send me an email for anything else!

--pancake

**Comment by ekristen** [comment]
I managed a distro/config called [SIFT](https://github.com/teamdfir/sift) for linux and I use a tool called [renovatebot](https://github.com/renovatebot/renovate] that has a datasource called github-release-attachments, it requires a checksums.txt file to detect new release assets, basically looks for a known asset and then a new one under a new tag to match vs specific filenames with tag names in it.

checksums.txt would make this work, but also good for those that want to check a download. If you want security I would recommend [cosign](https://github.com/sigstore/cosign) and the `sign-blob` command, you can sign the checksums.txt and use to provide a security check for all downloads without signing all individual files. Cosign also supports keyless signing by using throwaway keys and publishing to a ca transparency log.

If you use cosign, you can just use github releases, upload checksum, sign it with cosign keyless and the transparency log will store the record, cosign can verify off the external server.

Thanks.

**Comment by prodrigestivill** [comment]
Hello @ekristen,

Still don't understand how renovatebot will use those checksums... :(
The GitHub API already lists all the assets for each release and I don't follow the match algorithm you are explaining.

In any case, can you please provide an example of the format for the file that this tool requires, including the hash algorithm, to use the hash in uppercase or lowercase, the asset name (filename) and so on...

I can't find much documentation in their [web page](https://docs.renovatebot.com/modules/datasource/github-release-attachments/).

**Comment by ekristen** [comment]
Well apparently it doesn't always need the checksums.txt it did on the fly calculation of older files to find the correct corresponding one. https://github.com/teamdfir/sift-saltstack/pull/98 see the hashes update https://github.com/teamdfir/sift-saltstack/pull/98/files 

I still think that checksums.txt would be a great addition, but it looks like renovate is a beast on it's own and figures it out.

**Comment by Sreesruth** [comment]
what's to be done ??, is this issue valid to contribute to? if so whats the issue and what is to be done ?

**Comment by prodrigestivill** [comment]
@Sreesruth it has already been merged inside the PR #22664, so nothing left to be done.
This will be added automatically in the coming next radare2 release (5.9.0).

**Comment by Sreesruth** [comment]
Thats awesome, can't wait for the release
Thankyou

**Comment by trufae** [comment]
The release is out
