### ISSUE TITLE
Opening new panels in visual mode can destroy other panels, or open them in background.

### ISSUE THREAD

**Issue by Madghostek** [radareorg/radare2#22640]
## Environment

Sat Feb 24 06:55:15 PM CET 2024
radare2 5.8.9 1 @ linux-x86-64
birth: git.5.8.9 2024-02-22__21:34:37
commit: 7f16936ca6fd94c4addadf25ea0ee5d6b77db078
options: gpl -O? cs:5 cl:2 make
Linux x86_64

## Description

When a new sidepanel is opened, and there already exists a smaller panel, it will appear nowhere on the screen, but still can be cycled into with tab. In special case when the new panel size is exactly the same as some other panel, it will destroy the old panel.

I think the issue lies [here](https://github.com/radareorg/radare2/blob/c158fae44e2048f985780275d3977550224babb5/libr/core/panels.c#L1054), the function doesn't expect a situation when panel's size is less than `PANEL_CONFIG_SIDEPANEL_W` and doesn't adjust anything, so panels end up stacking on top of each other. And when panel is adjusted, but the resulting width is very small or zero, then later at some point `__del_invalid_panels` nukes it. 

It's not a big deal, but can be annoying when it destroys panel with custom command, all it takes is for example opening help. It can also be confusing for new users when it's impossible to open help panel.

## Test

Step 3 makes sure that a sidepanel with same size is opened, the default Disassembly panel can have different size depending on terminal.

Panel getting deleted due to invalid size:
1. Open radare
2. Go to panels mode with `v`
3. Open new side panel, lets say View->Classes
4. press `?` to open help panel
5. press `?` again, help disappeared, but Classes window didn't come back

Invisible panel:
1. Open radare
2. Go to panels mode with `v`
3. Open new side panel, lets say View->Classes
4. press `w` to enter window mode, resize the classes panel to be very narrow
5. Pressing `?` doesn't show help anymore

**Comment by trufae** [comment]
As long as you have checked the code already would you like to try to fix it too?

**Comment by Madghostek** [comment]
Yeah I think I can try, however I'm not sure what would be the best, I was thinking about two solutions:
1. Split the smaller sidepanel to make space. This at least keeps all panels visible
2. Allow the panels to stack on top of each other, but new one should appear on top instead in the back. This would work for peeking at the help panel, but you can stack panels over and over and get lost, so it's probably bad

**Comment by trufae** [comment]
Thank you!
