### ISSUE TITLE
Piping and | in params

### ISSUE THREAD

**Issue by nemanjan00** [radareorg/radare2#22656]
## Environment

```sh
Wed Feb 28 10:34:38 AM CET 2024
radare2 5.8.8 0 @ linux-x86-64
birth: git.5.8.8 2024-02-05__23:36:49
commit: unknown
options: gpl release -O1 cs:5 cl:2 meson
Linux x86_64
```

## Description

Looks like r2 is not really properly parsing arguments and | for commands.

Example

```
aclj | jq ".[] | .bases"
zsh:1: unmatched "
zsh:1: unmatched "
```

From error, I think it is treating this as 2 pipes, not 1, probably just splitting by `|`, running `zsh -c ' jq ".[] '`, writing `aclj` output to that command and then writing output of that command into `zsh -c ' .bases"'`

## Test

Just run:

```
aclj | jq ".[] | .bases"
```

**Comment by trufae** [comment]
thats a quickfix can u check if it works as expected for you?

https://github.com/radareorg/radare2/pull/22659
