### ISSUE TITLE
Incorrect usage of pdj makes r2 hang forever

### ISSUE THREAD

**Issue by dnakov** [radareorg/radare2#22652]
## Environment

Tue Feb 27 14:34:35 EST 2024
radare2 5.8.9 31674 @ darwin-arm-64
birth: git.5.8.8-1056-g7da6f12ef8 2024-02-08__16:28:36
commit: 7da6f12ef8100b2fdf84d78470e3ad050ec8499e
options: gpl -O2 cs:5 cl:2 make
Darwin arm64

## Description

Incorrect usage of pdj makes r2 hang forever. Local mistral LLM model decided to run it like this (r2ai).
`pdj main`

## Test
```
$ r2 -A binfile
pdj main
```
[address.32.zip](https://github.com/radareorg/radare2/files/14424842/address.32.zip)

**Comment by trufae** [comment]
Now ^C is handled.. but its better to tell in the prompt how to use that command instead

**Comment by trufae** [comment]
Actually, there's an anal.timeout which only covers the analysis... but can be easily extended to support RCons.break and add a time limit to all blocking operations. what do you think?

**Comment by dnakov** [comment]
yeah a configurable timeout would be great to have! Another thing which would be useful, not sure if it exists, would be to pre-set a limit to long commands so they don't ask (Y/n.) I've tried prompting the LLM but it doesn't listen sometimes :)
