### ISSUE TITLE
Opening custom layout sets all the addresses to one value in visual panels mode (stack does not follow rsp)

### ISSUE THREAD

**Issue by UjeNeTORT** [radareorg/radare2#22679]
## Environment

```
Вт 12 мар 2024 21:34:15 MSK
radare2 5.8.9 31746 @ linux-x86-64
birth: git.5.8.8-1162-g6673e8a42d 2024-03-01__16:23:38
commit: 6673e8a42dfb56bb4e679486e452e6b1ba9ecfff
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description
Disassembly and stack panels are on different addresses in default layout:
![image](https://github.com/radareorg/radare2/assets/106476252/1fc786ea-30d1-4472-a98a-6298d97ededa)

After loading saved layout they are on the same address:
![image](https://github.com/radareorg/radare2/assets/106476252/bba82763-9546-4b39-bfd8-f40102b7e333)

## Test

1. Create and save a custom layout in Visual Panels mode
2. ``` r2 -d <some_file_with_main_function> ```
3. v
4. Load saved layout you have created.

As a result the stack panel (and others) now are at the same address (which is the beginning of main function in opened file).
Expected behaviour: stack panel is at rsp value and follows it as we press F7.

**Comment by trufae** [comment]
use @r:SP instead of @rsp

**Comment by UjeNeTORT** [comment]
Sorry, I don't understand what you mean. I want to have my panels at correct addresses when i open debugger. I have never typed ```@rsp``` anywhere. What should i do to use @r:SP instead of @rsp by default?

**Comment by trufae** [comment]
Oops. this was actuall y wrong, the stack panel was not following anything, can you git pull and try again?

**Comment by UjeNeTORT** [comment]
Did it. It is still not working properly( Still addresses are the same on disasm, stack and hexdump panels. I managed to make it work right by choosing stack panel and then choosing stack in panel menu again.

Addresses are the same:
![image](https://github.com/radareorg/radare2/assets/106476252/03bde7aa-7502-4932-9f9a-b6afa44a4794)

![image](https://github.com/radareorg/radare2/assets/106476252/c3166424-43aa-4358-961e-06211241bd3c)
"Choose stack panel instead of stack panel"
![image](https://github.com/radareorg/radare2/assets/106476252/54ea45c3-85a7-4c31-bf24-1da41a3bfd0d)
Now stack panel follows rsp as intended.
![image](https://github.com/radareorg/radare2/assets/106476252/56930991-9b8d-42b4-a9a5-e276185cedc6)

```
radare2 5.8.9 31766 @ linux-x86-64
birth: git.5.8.8-1178-g168be38dc4 2024-03-11__09:12:34
commit: 168be38dc4e248e1582755fbbb9ef6391424b1b8
options: gpl -O? cs:5 cl:2 make
```

**Comment by trufae** [comment]
i don't understand the screenshots and i cant reproduce your problem. the commit should be
7150da3e568c59b66d039032cf09dea93ed025c7 and your build is from march 7th (too old). 

you say the addreses are the same but the disasm and stack panels have different addreses. also the "choose stack panel instead of stack panel" not sure if i get it

**Comment by UjeNeTORT** [comment]
I did git pull again and nothing changed. I'll try to give more detailed info about the problem in this comment.
```
netort@thinkpad-x1:~/radare2$ r2 -v
radare2 5.8.9 31766 @ linux-x86-64
birth: git.5.8.8-1178-g168be38dc4 2024-03-11__09:12:34
commit: 168be38dc4e248e1582755fbbb9ef6391424b1b8
options: gpl -O? cs:5 cl:2 make
```

```
r2 -d <file path>
WARN: Relocs has not been applied. Please use `-e bin.relocs.apply=true` or `-e bin.cache=true` next time
 -- This page intentionally left blank.
[0x7a1fdf312290]> 
```

Then i press ```v``` + ```enter```.

As a result addresses are still the same.
![image](https://github.com/radareorg/radare2/assets/106476252/f48700de-7d72-4623-a176-ec7e86652451)

The way i solve problem now is by reloading panels manually ("choose stack panel instead of stack panel"). This way it tracks rsp again. 

I load custom layout automatically via ```~/.radare2.rc``` configuration file. It's contents:
```
e stack.size=256
e scr.theme=white2
e scr.layout=fav_dbg
```

**Comment by trufae** [comment]
after my commit fixing the issue this is what i see by following your steps

<img width="1800" alt="Screenshot 2024-03-14 at 23 08 53" src="https://github.com/radareorg/radare2/assets/6431515/4645d228-d073-40e8-bd09-9ee96ddf4b71">

```
[0x1027cf2c0]> ?V
radare2 5.8.9 34550 @ darwin-arm-64
birth: git.5.8.8-1192-ge662f6be87 2024-03-14__22:57:13
commit: e662f6be8784408f08901fc02b82d2e68eda1203
options: gpl -O2 cs:5 cl:2 make
[0x1027cf2c0]>
```

note that your version is this:

```
birth: git.5.8.8-1178-g168be38dc4 2024-03-11__09:12:34
```

the 1178 is the amount of commits since 5.8.8. you are almost 20 commits behind master

**Comment by trufae** [comment]
note that to update r2 you need to run sys/install.sh, doing git pull wont recompile anything

**Comment by UjeNeTORT** [comment]
Oh, my bad, although nothing changed. Stack still does not track rsp :-(
```
radare2 5.8.9 31794 @ linux-x86-64
birth: git.5.8.8-1191-g61a6a54b5c 2024-03-15__01:55:46
commit: 61a6a54b5ceb2d351345e6494971ccd9dbd3d4bc
options: gpl -O? cs:5 cl:2 make
```

**Comment by UjeNeTORT** [comment]
NO, I resaved my layout and everything is ok now. Stack tracks rsp now by default. Thank you!

**Comment by trufae** [comment]
Yeah the saved layouts keep the commands associated with the panels. So ir makes sense :) thanks for reporting!
