### ISSUE TITLE
Implement showing map names with "dm" on Windows

### ISSUE THREAD

**Issue by xdp0** [radareorg/radare2#22707]
It would be nice if `dm` command on Windows showed module names and mapped file names.

I guess there was such a feature before. From `radare2/libr/debug/p/native/maps/windows_maps.c`:

```
/* get process modules list */
RList *mod_list = NULL; // r_w32_dbg_modules (dbg);
```

And one more line from the same file:

`DWORD len = 0; // r_w32_GetMappedFileName (h_proc, mbi->BaseAddress, f_name, MAX_PATH);`

But it's commented now. What was the reason for commenting it?

**Comment by trufae** [comment]
I think the reason was because it was causing segfaults on some windows if the api was not available or the abi changed between mingw and msvc. But thats just from memory didnt git blamed to find the actual commit. Feel free to try uncommenting and testing again because the toolchains has changes over time and maybe this issue is gone now

**Comment by xdp0** [comment]
OK I will. The actual is commit is 3e032073a33973183753bccb1b50427f0ddad3ee btw. Don't you remember the Windows version/arch where it segfaulted?

**Comment by trufae** [comment]
I use to test wxp 32bit and w11 x64. W95 was working at some point but im not sure whats the state of it now

**Comment by trufae** [comment]
@xdp0 anyupdate here? can you submit a pr fixing that and test if it works with latest code from git? thanks!

**Comment by xdp0** [comment]
Sorry, I am still far away from any computer, will be available to do fixes only after 10 days ><05:02, 16 апреля 2024 г., pancake ***@***.***>:
@xdp0 anyupdate here? can you submit a pr fixing that and test if it works with latest code from git? thanks!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by trufae** [comment]
Just tested your proposal and it seems to work at least on w10.
![IMG_8210](https://github.com/radareorg/radare2/assets/6431515/b101e0d5-5b5f-45ef-a235-90732d87cd99)
![IMG_8209](https://github.com/radareorg/radare2/assets/6431515/991fa30a-8ecc-4c4e-aa60-75bb368edf23)
