### ISSUE TITLE
F7/F8 do not seek to PC in visual debug mode, but "s" and "S" do

### ISSUE THREAD

**Issue by xdp0** [radareorg/radare2#22706]
radare2 version:

```radare2 5.8.9 31788 @ linux-x86-64
birth: git.5.8.8-1191-g61a6a54b5c 2024-03-14__20:28:58
commit: 61a6a54b5ceb2d351345e6494971ccd9dbd3d4bc
options: gpl -O? cs:5 cl:2 make
```

Running Ubuntu 22.04.4 LTS on WSL2:

```WSL version: 2.1.4.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3235
```

I open program for debugging:

`$ r2 -Ad /bin/ls`

Then go to visual debug mode with `Vpp` command and start stepping.

If I step with F7 and F8, no seek to program counter occur, so when it reaches call / jmp / end of the screen, the disassembly remains static and only registers keep changing. But if I step with "s" or "S", it does seek to PC as usual.

Is it the intended behaviour?

**Comment by trufae** [comment]
No ,this is not an intended behaviour but i think i know why it happens. Will check tomorrow

**Comment by trufae** [comment]
according to the code it should behave the same way

<img width="1760" alt="Screenshot 2024-03-17 at 20 52 03" src="https://github.com/radareorg/radare2/assets/6431515/ccd76cb1-2d97-40c0-b87d-8a6eaffed3e7">
