### ISSUE TITLE
malloc bug?

### ISSUE THREAD

**Issue by dududuguo** [radareorg/radare2#22767]
when I start the buf_bytes.c:38 priv->buf = malloc (priv->length); , this will malloc(0).

$ r2 /bin/ls
mallocing 0
mallocing 0
mallocing 0
mallocing 0
WARN: Relocs has not been applied. Please use `-e bin.relocs.apply=true` or `-e bin.cache=true` next time
 -- Did you know that radare2 can decompile to assembly?
[0x00006aa0]>

**Comment by trufae** [comment]
yeah this seems like a very bad thing. good spot! fixing now thanks!
