### ISSUE TITLE
R2 doesn't work on corkami's tiny.asm

### ISSUE THREAD

**Issue by jvoisin** [radareorg/radare2#230]
Here is the code:

```
; initial version based on from Brian Raiter's http://www.muppetlabs.com/~breadbox/software/tiny/teensy.html

BITS 32
ELFBASE equ 10000h

; position independant

ehdr: ; Elf32_Ehdr
    db 7fh, "ELF"             ; e_ident
    dd 1                                  ; p_type
    dd 0                                  ; p_offset
    dd ehdr + ELFBASE                     ; p_vaddr
    dw 2                      ; e_type    ; p_addr
    dw 3                      ; e_machine
    dd main - ehdr + ELFBASE  ; e_version ; p_filesz
    dd main - ehdr + ELFBASE  ; e_entry   ; p_memsz
    dd 4                      ; e_phoff   ; p_flags
main:
    mov bl, 42
    xor eax, eax
    inc eax
    int 80h

    db 0
    dw 34h                    ; e_ehsize
    dw 20h                    ; e_phentsize
    db 1                      ; e_phnum
                              ; e_shentsize
                              ; e_shnum
                              ; e_shstrndx
FILESIZE equ $ - ehdr
```

And here is the compiled binary in b64:

```
f0VMRgEAAAAAAAAAAAABAAIAAwAgAAEAIAABAAQAAACzKjHAQM2AADQAIAAB
```

This is what I get:

```
r2 ./tiny.elf
Error: read (shdr) at 0xc0312ab3
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Error: read (init_offset)
[0x00010020]> aa
[0x00010020]> pdf
Cannot find function at 0x00010020
Cannot find function at 0x00010020
      ; -- entry0:
      0x00010020  0   0     ff               invalid
      0x00010021  0   0     ff               invalid
      0x00010022  0   0     ff               invalid
      0x00010023  0   0     ff               invalid
...
```

It seems to be related to #77

**Comment by kodyabbott** [comment]
> Here is the code:
> 
> ```
> ; initial version based on from Brian Raiter's http://www.muppetlabs.com/~breadbox/software/tiny/teensy.html
> 
> BITS 32
> ELFBASE equ 10000h
> 
> ; position independant
> 
> ehdr: ; Elf32_Ehdr
>     db 7fh, "ELF"             ; e_ident
>     dd 1                                  ; p_type
>     dd 0                                  ; p_offset
>     dd ehdr + ELFBASE                     ; p_vaddr
>     dw 2                      ; e_type    ; p_addr
>     dw 3                      ; e_machine
>     dd main - ehdr + ELFBASE  ; e_version ; p_filesz
>     dd main - ehdr + ELFBASE  ; e_entry   ; p_memsz
>     dd 4                      ; e_phoff   ; p_flags
> main:
>     mov bl, 42
>     xor eax, eax
>     inc eax
>     int 80h
> 
>     db 0
>     dw 34h                    ; e_ehsize
>     dw 20h                    ; e_phentsize
>     db 1                      ; e_phnum
>                               ; e_shentsize
>                               ; e_shnum
>                               ; e_shstrndx
> FILESIZE equ $ - ehdr
> ```
> 
> And here is the compiled binary in b64:
> 
> ```
> f0VMRgEAAAAAAAAAAAABAAIAAwAgAAEAIAABAAQAAACzKjHAQM2AADQAIAAB
> ```
> 
> This is what I get:
> 
> ```
> r2 ./tiny.elf
> Error: read (shdr) at 0xc0312ab3
> Warning: Cannot initialize section headers
> Warning: Cannot initialize strings table
> Error: read (init_offset)
> [0x00010020]> aa
> [0x00010020]> pdf
> Cannot find function at 0x00010020
> Cannot find function at 0x00010020
>       ; -- entry0:
>       0x00010020  0   0     ff               invalid
>       0x00010021  0   0     ff               invalid
>       0x00010022  0   0     ff               invalid
>       0x00010023  0   0     ff               invalid
> ...
> ```
> 
> It seems to be related to #77

I am curious if you dont mind what exactly does this do?

**Comment by radare** [comment]
Isnt it in r2r?
