### ISSUE TITLE
[ARM.GNU] PC <-> R15, R12 <-> IP

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#2309]
The tests show that the usage of PC/R15 or R12/IP is not uniform. Someone should review this problem and select only one notation or an eval variable to choose.
- https://github.com/radare/radare2-regressions/blob/master/t.asm/arm/arm

**Comment by radare** [comment]
Capstone vs gnu vs asm.numreg

**Comment by Maijin** [comment]
And also this anal test is impacted and now marked as broken:
https://github.com/radare/radare2-regressions/blob/master/t.anal/arm/arm_32
