### ISSUE TITLE
Same demangling for two swift names

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#23110]
These two symbols produce the same demangling output, which causes a conflict later on:

* `_OBJC_METACLASS_$__TtCC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery9BridgeKey`

```
0     0x68396098         0x1ea00e098 NONE   FUNC 0        _OBJC_METACLASS_$__TtC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery
0     0x683978e0         0x1ea00f8e0 NONE   FUNC 0        _OBJC_METACLASS_$__TtCC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery9BridgeKey
```

that's translated to `Foundation.__KVOKeyPathBridgeMachinery :: NSObject, NSObject` by our demangler, but the apple one does: `_OBJC_METACLASS_$_Foundation.(__KVOKeyPathBridgeMachinery in _6DA0945A07226B3278459E9368612FF4).BridgeKey`

![photo_2024-07-10_11-48-13](https://github.com/radareorg/radare2/assets/6431515/3c69673d-7654-45b7-9eb8-0d59bae6eea0)
![photo_2024-07-10_11-48-21](https://github.com/radareorg/radare2/assets/6431515/be918583-6333-4810-a6e0-9e98c7c0a7c6)

cc @mrmacete please update the ticket with more details, i'll try to find some time to fix it, meanwhile using the system demangler would work if you are on macos or ios

**Comment by mrmacete** [comment]
i think that happens in general with nested types, the ones from the example above:

mangled: `_TtC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery`
swift-demangle output: `Foundation.(__KVOKeyPathBridgeMachinery in _6DA0945A07226B3278459E9368612FF4)`

mangled: `_TtCC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery9BridgeKey`
swift-demangle output: `Foundation.(__KVOKeyPathBridgeMachinery in _6DA0945A07226B3278459E9368612FF4).BridgeKey`

these 2 demangle to the same on r2's demangler.

Here's another example of symbols which r2 demangles all to `CryptoKit.Curve448.Signing.PublicKey`:

- `$s9CryptoKit8Curve448O7SigningO9PublicKeyV16isValidSignature_3forSbx_q_t10Foundation12DataProtocolRzAjKR_r0_lF`
- `$s9CryptoKit8Curve448O7SigningO9PublicKeyV17rawRepresentation10Foundation4DataVvg`
- `$s9CryptoKit8Curve448O7SigningO10PrivateKeyV06publicF0AE06PublicF0VvpMV`
- `$s9CryptoKit8Curve448O7SigningO9PublicKeyV17rawRepresentationAGx_tKc10Foundation15ContiguousBytesRzlufC`
- `$s9CryptoKit8Curve448O7SigningO9PublicKeyVMa`
- `$s9CryptoKit8Curve448O7SigningO9PublicKeyVMn`
