### ISSUE TITLE
Incorrect handling of OpenBSD specific code

### ISSUE THREAD

**Issue by cjeker** [radareorg/radare2#23158]
The OpenBSD handling in bsd_debug.c is incorrect. The inspected flags have nothing to do with the execution state of the process. In OpenBSD -current the PS_STOPPED field was removed and so this code no longer compiles.

https://github.com/radareorg/radare2/blob/master/libr/debug/p/native/bsd/bsd_debug.c#L194-L203

That code should do the same as the FreeBSD and NetBSD code and inspect `p_stat`. This will return the scheduler state (SSLEEP, SSTOP, SRUN, SONPROC and SDEAD) of the main thread.

I do not use radare2 but was notified about the build failure on OpenBSD-current. This is why I open this issue.

**Comment by trufae** [comment]
Can you submit a pr?

**Comment by cjeker** [comment]
> Can you submit a pr?

Done

**Comment by trufae** [comment]
can we close this issue now?

**Comment by cjeker** [comment]
Sure. Thanks for merging.
