### ISSUE TITLE
It cannot be displayed directly in Chinese

### ISSUE THREAD

**Issue by bqshj** [radareorg/radare2#23273]
## Environment
termux
```sh
# copypaste this script into your shell and replace it with the output
date
Tue Sep  3 09:47:47 CST 2024
r2 -v
radare2 5.9.4 0 @ linux-arm-64
birth: git.5.9.4 2024-08-08__18:20:14
commit: 5.9.4
options: gpl release -O1 cs:5 cl:2 make
uname -ms
```

## Description

pdf @ 0x1850
0x00001850      00802891       add x0, x0, 0xa20           ; 0x1a20 ; "\n\u4fee\u6539\u6210\u529f\n" ; const char *s
......

I expect to see

0x00001850      00802891       add x0, x0, 0xa20           ; 0x1a20 ; "\n修改成功\n" ; const char *s

**Comment by trufae** [comment]
Can you share the binary?

**Comment by bqshj** [comment]
of course
https://github.com/bqshj/bin

**Comment by bqshj** [comment]
of course



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 3, 2024 13:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [radareorg/radare2] It cannot be displayed directly in Chinese(Issue #23273)




 
Can you share the binary?

**Comment by trufae** [comment]
so its just an issue in the disassembly view, right? because this is listed properly in the strings `iz`

```
[0x00001730]> izq
0x1868 9 8 \e[%d;%df
0x1878 11 10 \e[2J\e[0;0f
0x1938 6 5 /proc
0x1940 17 16 /proc/%d/cmdline
0x1960 14 13 /proc/%d/maps
0x1978 12 11 [anon:.bss]
0x1998 23 22 com.mf.monsterblast.mi
0x19b0 13 12 /proc/%d/mem
0x19c0 17 8 获取mem失败!
0x19d8 20 7 \n开始基址搜索
0x19f0 19 6 基址搜索完成
0x1a15 6 5 =%lx\n
0x1a20 15 6 \n修改成功\n
0x1a30 15 14 libmonsters.so
[0x00001730]>
```

**Comment by trufae** [comment]
When the PR gets merged you can do `-e scr.strconv=raw` and get the strings right in the disasm view. use -e emu.str=true for better output

i will improve support for more encodings and better conversions after the next release. but at least having some tests will make the whole thing much easier to improve. thanks!
