### ISSUE TITLE
No ESIL for `movn` on MIPS

### ISSUE THREAD

**Issue by vobst** [radareorg/radare2#23286]
## Environment

```sh
Thu Sep  5 11:39:40 PM CEST 2024
radare2 5.9.2 0 @ linux-x86-64
birth: git.5.9.2 2024-08-01__08:35:56
options: gpl release -O1 cs:5 cl:2 meson
Linux x86_64
```

## Description

No ESIL is displayed for conditional move instructions on MIPS, i.e., they are treated like NOPs.

```
[0x80053bb8]> pd
        :   0x80053bb8      0b304300       movn a2, v0, v1
[...]
[0x80053bb8]> e asm.esil = true
[0x80053bb8]> pd
        :   0x80053bb8      0b304300       ,
[...]
```

The semantics of this particular insn are:

```
movn d,s,t if (t) d = s;
```

I'd expect to either see a notification that is insn is unimplemented or an ESIL expression that is expressing the correct semantics.

Wouldn't mind fixing this myself (I expect it to be rather small fix) but I need some help where to start.

## Test

I guess creating a file with the bytes and basing it at zero should be enough:

```
$ echo -n '\x0b\x30\x83\x00' > /tmp/bytes
$ r2 -e asm.esil=true -c 'pd 1' -q -a mips -b 32 -e cfg.bigendian=false -m 0x0 /tmp/bytes
```

**Comment by trufae** [comment]
check this file: libr/arch/p/mips/plugin_cs.c  i guess you can check the implementation for the MOV or MOVE instructions and add another case for MOVN. You can probably review the rest of MIPS_INS defines or other missing instructions in this switch statement and fill the remaining gaps. adding tests is a plus but not mandatory

thank you! let me know if you need any extra help
