### ISSUE TITLE
r2 : the breakpoint not working...

### ISSUE THREAD

**Issue by rolio37** [radareorg/radare2#23298]
## Environment

sam.  7 sept. 2024 20:13:53 CEST

radare2 5.9.4 1 @ freebsd-x86-64
birth: git.5.9.4 2024-09-06__22:00:50
commit: 02129cb2032f22e445bf98240859a0cca63336fd
options: gpl -O1 cs:5 cl:2 make

FreeBSD amd64

## Description

the breakpoint not working...

## Test

asm exit program compiled with nasm :

r2 -d exit

[0x00201120]> db 0x0020112d
[0x00201120]> dc

![debug_r2](https://github.com/user-attachments/assets/01ce7235-a335-4331-a33e-e4824442873d)

**Comment by trufae** [comment]
The breakpoint seems to work but its not recoiling a byte for an unknown reason. Will chk when i have some time

**Comment by rolio37** [comment]
ok thank you.

**Comment by trufae** [comment]
cant reproduce

**Comment by rolio37** [comment]
ok, it's strange...
$ freebsd-version -kru
14.1-RELEASE-p4
14.1-RELEASE-p4
14.1-RELEASE-p4

**Comment by trufae** [comment]
uh i can repro now! ill take a look

**Comment by trufae** [comment]
here we go :) pull from master

**Comment by rolio37** [comment]
It's ok, breakpoints work under FreeBSD, thanks for the correction :)
