### ISSUE TITLE
rabin2: extremely large address and size 

### ISSUE THREAD

**Issue by AbhiTheModder** [radareorg/radare2#23347]
## Environment

```sh
radare2 5.9.4 0 @ linux-arm-64
birth: git.5.9.4 2024-08-08__18:20:14
commit: 5.9.4
options: gpl release -O1 cs:5 cl:2 make
Linux aarch64
```

## Description
Command to increase size of sections in binary 

`rabin2 -O r/.rodata/64 foo64.uu`

Generates extremely large address and size 
![IMG_20240919_074338_376](https://github.com/user-attachments/assets/58f7770a-21b3-4023-8176-553c400bba0d)

P.S: This issue is based on the request of a user from his discussion on telegram [here](https://t.me/radare/248313) since he doesn't have a GitHub acc he asked me for.

**Comment by trufae** [comment]
thanks for reporting, the elf patcher is clearly patghint the wrong offset and causing mayhem.

**Comment by trufae** [comment]
[foo64.zip](https://github.com/user-attachments/files/17347786/foo64.zip)

**Comment by trufae** [comment]
fixed

**Comment by trufae** [comment]
in https://github.com/radareorg/radare2/commit/9b632bc9d7ba910115cf2829b6f8f65aaa8d14a1
