### ISSUE TITLE
The zf flag is no longer available in debug mode under FreeBSD

### ISSUE THREAD

**Issue by rolio37** [radareorg/radare2#23357]
## Environment

$ date
jeu. 19 sept. 2024 19:32:15 CEST
$ r2 -v
radare2 5.9.5 0 @ freebsd-x86-64
birth: git.5.9.5 2024-09-13__21:45:49
commit: 5.9.5
options: gpl release -O? cs:5 cl:2 make
$ uname -ms
FreeBSD amd64
$ freebsd-version -kru
14.1-RELEASE-p4
14.1-RELEASE-p4
14.1-RELEASE-p4

## Description

Hi, I just want to be able to change the zf flag while debugging.

## Test

![r2](https://github.com/user-attachments/assets/44cd6e6e-721e-4007-896e-d4f860038d6a)

**Comment by trufae** [comment]
Can you make a pr updating the register profile?

**Comment by rolio37** [comment]
Sorry I'm French, I don't understand the question with the term "pr" ?

**Comment by trufae** [comment]
pr means pull request. i just pushed the fix but enotime to test. can you confirm?

**Comment by rolio37** [comment]
I confirm, the patch is good, everything works, thank you.

**Comment by trufae** [comment]
Cool thanks for confirming
