### ISSUE TITLE
download broken

### ISSUE THREAD

**Issue by 3052** [radareorg/radare2#23374]
~~~
> curl -v radare.mikelloc.com/get/4.3.1/radare2-msvc_64-4.3.1.zip
*   Trying 51.68.44.219:80...
* connect to 51.68.44.219 port 80 failed: Timed out
* Failed to connect to radare.mikelloc.com port 80 after 21041 ms: Timed out
* Closing connection 0
curl: (28) Failed to connect to radare.mikelloc.com port 80 after 21041 ms: Timed out
~~~

**Comment by trufae** [comment]
Download from github. This site was shutted down 5 years ago so not sure where you find that link but the latest version is 5.9.4

**Comment by 3052** [comment]
> This site was shutted down 5 years ago so not sure where you find that link

the link is on this page:

https://rada.re/r/

**Comment by trufae** [comment]
This is an archived link that you should never reach it if you go from the root page. Ill add a banner on top to clarify it but this is there for historical reasons
