### ISSUE TITLE
xmm? registers are not available during debugging under FreeBSD

### ISSUE THREAD

**Issue by rolio37** [radareorg/radare2#23417]
## Environment

$ date
mar.  1 oct. 2024 18:28:06 CEST
$ r2 -v
WARN: Duplicated register definition for 'rflags' has been ignored
radare2 5.9.5 0 @ freebsd-x86-64
birth: git.5.9.5 2024-09-20__17:05:17
commit: 5.9.5
options: gpl release -O? cs:5 cl:2 make
$ uname -ms
FreeBSD amd64
$ freebsd-version -kru
14.1-RELEASE-p5
14.1-RELEASE-p5
14.1-RELEASE-p5

## Description

Hi, I would like to display the xmm? registers during debugging.
Thanks.

## Test

![xmm](https://github.com/user-attachments/assets/a13f047e-6539-47a1-861f-4e89ab3c0c5f)

**Comment by trufae** [comment]
drt 128
in visual mode you can press = to change the scr.vprompt variable to add this command and display them all the time

**Comment by trufae** [comment]
oh, if its a fbsd-specific issue then it means that the reg profile needs to be updated, unless these registers are in a different arena. check this commit as inspiration 0189d66dc9093466b4786beeeae07088ee60dd3a

**Comment by rolio37** [comment]
This is indeed a problem under FreeBSD.
It works fine under Linux.

**Comment by rolio37** [comment]
Same problem with fpu registers st0 to st7

**Comment by trufae** [comment]
Can you give it a try by modifying the register profile by hand? use the drp command to dump and restore it. if vector and floating point registers are accessible thru a different ptrace call we will need to touch C code, otherwise if its just a profile issue you can do this without recompiling

**Comment by rolio37** [comment]
ptrace:
for fpu register it's PT_GETFPREGS and PT_SETFPREGS
for xmm? register PT_GETXMMREGS and PT_SETXMMREGS
doc: 
https://man.freebsd.org/cgi/man.cgi?query=ptrace&apropos=0&sektion=2&manpath=FreeBSD+11.0-RELEASE+and+Ports&arch=default&format=html

**Comment by trufae** [comment]
This is fixed now :)

**Comment by rolio37** [comment]
Yes :)
