### ISSUE TITLE
Stack exhaustion prevented trying to analyze Mach-O

### ISSUE THREAD

**Issue by daniel13lm** [radareorg/radare2#23523]
## Environment
```
Thu Oct 24 14:30:51 UTC 2024
radare2 5.9.7 32783 @ linux-x86-64
birth: git.5.9.6-52-g4bfc474729 2024-10-22__11:16:16
commit: 4bfc474729d97de1d0c2176af8638689eac87d1c
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

Just when I try to start the analysis in radare an I open it like r2 and the hash it says: Stack exhaustion prevented

## Test
##The hash to reproduce the print is this one: cf36d7bd51139ceaab6377d19d994551
r2 cf36d7bd51139ceaab6377d19d994551

**Comment by trufae** [comment]
That message comes up from the c++ demangler, it stops demangling after finding very large symbols before segfaulting because of a bug in the gnu demangler i found two years ago. I dont think theres anything to worry about, just be careful because other tools may crash.
