### ISSUE TITLE
Segmentation fault when trying to analyze Mach-O binary

### ISSUE THREAD

**Issue by daniel13lm** [radareorg/radare2#23529]
## Environment

```Fri Oct 25 09:53:03 UTC 2024
radare2 5.9.7 32783 @ linux-x86-64
birth: git.5.9.6-52-g4bfc474729 2024-10-22__11:16:16
commit: 4bfc474729d97de1d0c2176af8638689eac87d1c
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

Just when I try to start the analysis in radare an I open it like r2 and the hash it says: Segmentation fault

## Test

The hash to reproduce the error is this one: 31556fdf67379f7c3558e56bd9fa48ed
r2 31556fdf67379f7c3558e56bd9fa48ed

**Comment by trufae** [comment]
omg taht's another bug in the C++ demangler from GNU. that's the 3rd vulnerability i fix in their code 😭. This means that i'll probably end up rewriting the whole thing because it's another bad practice

thanks for reporting.
