### ISSUE TITLE
Assembling AVX instructions with rasm2

### ISSUE THREAD

**Issue by jukuisma** [radareorg/radare2#23808]
## Environment

```sh
Wed 18 Dec 2024 07:52:46 UTC
radare2 5.9.9 33111 @ linux-x86-64
birth: git.5.9.8-180-gc42a2afb92 2024-12-18__07:49:28
commit: c42a2afb92baff572b1c6c26bdf80532481d208a
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

I was analyzing a core dump with gdb and cross-referencing stuff in radare2. Noticed that `rasm2` can disassemble AVX instructions without a problem, but can't assemble the same instructions. Am I being stupid or is this an actual bug in `rasm2`?

## Test

```
╭─vagrant@testing ~/github/radare2 (master)
╰─➤ rasm2 -d c4e1f97ed0
vmovq rax, xmm2
╭─vagrant@testing ~/github/radare2 (master)
╰─➤ rasm2 'vmovq rax, xmm2'
ERROR: Cannot assemble 'vmovq rax, xmm2' at line 1
```

**Comment by trufae** [comment]
that's totally normal, and its not a bug in rasm2. But just a feature request for the x86.nz plugin, which is a handwritten from scratch implementation for an assembler. no disassembler library supports assembling by itself, those are always separate implementations, you can use the x86.as or x86.ks plugins which support more instruction or implement it in a pullrequest for the default x86.nz plugin which is the only one that is shipped by default and works the best in most situations

**Comment by trufae** [comment]
i should probably have a generic answer to this because it's been a common question and the x86.nz plugin evolves depending on user requests.

**Comment by jukuisma** [comment]
ACK, thanks!
