### ISSUE TITLE
If a dbte at an address for example 0x1048bc3d9 is enabled in dbg.trace=true mode - the command "at" shows hits at 0x1048bc3d9 and 0x1048bc3d8

### ISSUE THREAD

**Issue by z03** [radareorg/radare2#2392]
If a dbte at an address for example 0x1048bc3d9 is enabled in dbg.trace=true mode - the command "at" shows hits at 0x1048bc3d9 and 0x1048bc3d8

**Comment by trufae** [comment]
Can you please confirm the issue is still there? without a testcase or a reproducer is difficuilt to confirm from my side. Otherwise the issue may remain closed
