### ISSUE TITLE
F2 in visual debugger doesnt works like 'b' (no toggle, no cursor)

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#248]

**Comment by tahaaltuntas** [comment]
I'm still able to reproduce the issue.

radare2 0.9.9-git 7645 @ linux-little-x86-64 git.0.9.8-1296-gc7a4b97
commit: c7a4b978d1f271154d28ec725c9e89ccba9dd940 build: 2015-04-15

**Comment by Maijin** [comment]
? Can you do a radare.tv / asciinema of your issue ?

**Comment by radare** [comment]
Which terminal are you using?

**Comment by tahaaltuntas** [comment]
GNU bash, version 4.2.45(1)-release (x86_64-redhat-linux-gnu)

I pressed F2 to set a bp at 0x08048520 (0:33 of asciinema) https://asciinema.org/a/18880

**Comment by radare** [comment]
the shell have nothing to do. terminal emulator is the one that handles
keys and opens a window in your desktop. gnome terminal, xterm, etc... i
always use iterm2 on osx and xterm on linux for example and it works
fine there.

also, confirm that this key is not managed by your window manager, etc

**Comment by tahaaltuntas** [comment]
I was using putty to connect my linux machine. When I used xterm, it worked properly. Thanks for your replies.

**Comment by Maijin** [comment]
\o/

**Comment by radare** [comment]
I think putty handles the function keys for his own purposes. I cant do magic with this. So use the 'b' key which is more portable and almost as easy to use as the f2 one if you need to togglw breakpoints

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://enewsheadlines.com/magnitude.php?n>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://litovskaya2e.ru/rhetoric.php?3>

 

lukas-runas@gmx.de

**Comment by radare** [comment]
Not again...

**Comment by condret** [comment]
Hey,
Have you seen this before? That's something really nice, more info here <http://cihifreze.helpmehealthy.com/lnqraav>

Warmest, lukas-runas@gmx.de
