### ISSUE TITLE
pxw next range wrong offsets

### ISSUE THREAD

**Issue by X-cela** [radareorg/radare2#2619]
```
:> pxw @ 0x0804b070
0x0804b070  0x00000019 0x0804b088 0x0804b064  ........d.
0x0804b07a  0x00000804 0x00000000 0x00000000  ..........
0x0804b084  0x00000000 0x000003e8 0x00000000  ..........
0x0804b08e  0xb0700000 0x00000804 0x00000000  ..p.......
```

Shouldn't the next line start at 
0x0804b07c

**Comment by radare** [comment]
I have added 3 more tests in `t/cmd_pxw` related to this issue. Which hex.cols value are you using to reproduce this issue?

**Comment by protoload** [comment]
```
:> e~hex.cols
hex.cols = 8
```

**Comment by radare** [comment]
i cannot reproduce this isseu with hex.cols=8, are you using r2 from git?

**Comment by protoload** [comment]
Yes I am 
'''
radare2 0.9.9-git 7953 @ linux-little-x86-64 git.0.9.8-1607-gde7ac04
commit: de7ac04df1babafc20eab9e2e2e299883c6cc4a0 build: 2015-05-24
'''

Is there a hotkey that changes hex.cols width that I might be hitting accidentally? 
The value for it changes randomly while I'm debugging

**Comment by radare** [comment]
Scr.responsive

**Comment by radare** [comment]
This is fixed and there are tests messing with hex.cols in `db/cmd/cmd_pxw`
