### ISSUE TITLE
Implement rarun2 r2preload hooking

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#2677]
Add =! command in the r_io_self plugin to dlsym() and override the symbols at runtime. this will probably require plt fengshui, so it will depend on platform.

**Comment by radare** [comment]
```
=!trace malloc d p
=!trace free p
=!trace open zo d
=!trace close d
```

**Comment by ret2libc** [comment]
I'm closing because I can already see `r2preload   preload with libr2, kill -USR1 to get an r2 shell or -USR2 to spawn a webserver in a thread` in the man page of `rarun2`. If the issue was about something else, please update the summary and improve description and reopen it.
