### ISSUE TITLE
Visual disassembly moving byte/byte can be confusing

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#2712]
When you go into visual mode but the offset is not aligned, it's really confusing for end-users.
This has been notified during workshops by the people especially in the data section see:

http://radare.tv/a/70

If aligned (`s str.ASCII` in CLI mode):

```
   |   ; DATA XREF from 0x0041199f (fcn.00411900)                           
   |   ;-- str.ASCII:                                                       
   |   0x00416ffc     .string "ASCII" ; len=6          
```

If not aligned (`s str.ASCII+1` in CLI mode):

```
   |   0x00416ffd    53             push rbx                                
   |   0x00416ffe    434949004348   add byte [r11 + 0x48], al         
```

If it's not aligned it displays assembly code which is wrong. Same happen when you manipulate the code part: 

http://radare.tv/a/71

Aligned :

```
|          0x004028cc    53             push rbx                                
|          0x004028cd    89fb           mov ebx, edi  
```

Can change to this if not aligned which is completly diferrent and prone to error: 

```
|          0x004028ce    fb             sti                                     
|             read (0x0,0x0,0x0) ; section_end.phdr1+-8494577 
```

The fact you can move is very useful when you analyse undefined datas, and unknown stuff so it must be kept in a way, but it should be able to automatically allow the user to have the possibility to use kind of automatic alignement. (asm.midflags improvement?)

**Comment by radare** [comment]
Not my fault. Intel accepts any instruction at any offset as a valid instruction, not like arm/mips/sparc does.. So i dont consider a bug. You are disassembling. Not reading something static that doesnt changes unless you specify this like ida does.

If we want to scroll without unaligned stuff we should write a different frontend that does the same as the webui.

**Comment by jjdredd** [comment]
maybe always start disasm at the beginning of basic block?

**Comment by Maijin** [comment]
@radare Yes I know it's not radare2 fault :p Isn't there an eval variable that force alignment like yes, ida does ?

**Comment by Maijin** [comment]
Or even a display that mention to the user that it is not aligned

**Comment by radare** [comment]
Ida does and ida fails to disasm jumpinthemiddle antidisasm tricks

**Comment by radare** [comment]
This is already done for non-x86 platforms. On intel all instructions are valid at any address. Its not about alignment

**Comment by ret2libc** [comment]
I think that for strings we should continue to display strings even in the middle.
For code, instead, in case we have defined a function, we have already identified what are the correct addresses of the instructions in that function, so if a user move in an unaligned way, maybe we should simply put a sign or something to tell that it's not aligned with what was defined. If we don't have a function, in that case we can do like now...

**Comment by Maijin** [comment]
@ret2libc +1 for this

**Comment by radare** [comment]
that's what the asm.midflags is for. but it doesnt "works" for metadata
(strings, ..) yet. so i guess we can improve on this

**Comment by ret2libc** [comment]
See #3751

**Comment by radare** [comment]
But it can be useful too

**Comment by radare** [comment]
Same issue: https://github.com/radare/radare2/issues/4026

**Comment by ret2libc** [comment]
I'm going to postpone this issue to 0.10.2 because before doing it, it would be better to refactor r_meta because it has no clear API. I'm on it anyway. Ok?

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
any chance to get some time for this one?

**Comment by ret2libc** [comment]
Hard to say at the moment :(

**Comment by radare** [comment]
maybe moving to 0.10.4?

**Comment by radare** [comment]
removing @ret2libc as long as i cant expect this to be done for the next release or by him at all

**Comment by radare** [comment]
if anyone wants to check this go for it, otherwise i'll try to focus on that when i have some spare time next year

**Comment by alvarofe** [comment]
moved to 1.2.0

**Comment by radare** [comment]
Fair

**Comment by XVilka** [comment]
@cyanpencil can you please check this one too (to the end of your list)

**Comment by radare** [comment]
See my asm.meta approach too

**Comment by ret2libc** [comment]
I think this can be closed. The original issue is not relevant any more as now if you go in the middle of the strings you still see strings. If still relevant, please create a new issue.
