### ISSUE TITLE
define widestring from visual mode

### ISSUE THREAD

**Issue by crowell** [radareorg/radare2#2817]
defining string with `ds` doesn't work from visual mode on `wchar_t` type strings. there should be a way to define these

**Comment by radare** [comment]
If it isnt done in VdS it should be there

**Comment by crowell** [comment]
`VdS` does define all strings in current block, doesn't work for widestrings properly

![img](http://i.imgur.com/ChIE1sV.png)

**Comment by radare** [comment]
Ehm.. Iiirc i already added sipport for it. Vds was already checking the type of the string and sets wide or ascii/utf8 automatically. But i should check it again

**Comment by trufae** [comment]
This is already implemented, the vds keystrokes check if the string in the current offset is wide or not and defines it properly
