### ISSUE TITLE
Add command to print N functions

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#2955]
maybe `pdF 3` ?

**Comment by radare** [comment]
This can be useful to quickly determine function boundaries and full-file coverage like `pv` command does.

**Comment by jvoisin** [comment]
Can't you already do that with an iterator?

**Comment by radare** [comment]
there’s no command to list the first N function addresses found after the current address. and a command is simpler to remember than `pdf @@= `aflf $$ 3``

**Comment by ret2libc** [comment]
I'm going to close this as it was opened 5 years ago and nothing happened since then. I don't think it was ever implemented, so after all it wasn't that necessary.
