### ISSUE TITLE
RAGraph as a field of RAnalFunction

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#2976]
I think each function should have a pointer to the RAGraph that represents it, so that we can cache it and switch easily between graph of different functions without losing changes done by the user or having to recalculate each time the whole graph.

Moreover, I think it can make sense to have two RAGraph, one that represents the BasicBlocks and one that represents the CallGraph of that function.

**Comment by radare** [comment]
ok, but if RAGraph uses Sdb, or you use sdb to store all the graph information, better to use a single instance rather than an Sdb instance for every function

**Comment by ret2libc** [comment]
Closing this for now. I did not have time to work on this so far and there hasn't been any interest from others apparently.
