### ISSUE TITLE
'cmd > $$.myfile' $$ is not evaluated

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#2977]
It would be cool to have variables and aliases evaluated also after the '>'.

**Comment by radare** [comment]
You can use backticks and ?v for now

**Comment by ret2libc** [comment]
example?
I'd like to have the output of a command redirected to a file with the name taken from a variable.

**Comment by radare** [comment]
```
k name=filename
x > `k name`
```

**Comment by ret2libc** [comment]
> ```
> k name=filename
> x > `k name`
> ```

The issue above is still relevant, but I'm closing this for now as it didn't get any attention in the last years and probably won't receive any any time soon. By the way, this workaround does not work, at least at the moment.
