### ISSUE TITLE
Support for loading LE files (OS/2) executables

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#314]
Support for LE files/

OS/2

32-bit Linear Executable
    Introduced with OS/2 2.0, these can be identified by the "LX" in ASCII. These can only be run by OS/2 2.0 and higher.[citation needed] They are also used by some DOS extenders.
Mixed 16/32-bit Linear Executable
    Introduced with OS/2 2.0, these can be identified by the "LE" in ASCII. This format is not used for OS/2 applications anymore, but instead for VxD drivers under Windows 3.x and Windows 9x, and by some DOS extenders. 

Here are a few examples:
[BIGRAM.ZIP](https://github.com/radare/radare2/files/2643966/BIGRAM.ZIP)
[CP.ZIP](https://github.com/radare/radare2/files/2643967/CP.ZIP)
[CURSOR.ZIP](https://github.com/radare/radare2/files/2643969/CURSOR.ZIP)

**Comment by Nodepad** [comment]
I'm working on le bin plugin. I have couple questions about plugin development:
1. LE executable contains "objects" which similar to sections in other bin plugins. But this objects doesn't contain raw data. Instead it consist of pages which can be nullable, contain iterated or raw data. Could someone help about how to properly implement this staff?

2. LX executable can contain both 16-bit and 32-bit objects. But right now bits size can be set only for entire executable. Is it possible to modify current code to add or redefine bits size parameter for section?

**Comment by XVilka** [comment]
See the example in TE plugin.

**Comment by Maijin** [comment]
@Nodepad https://github.com/radare/radare2/wiki/Implementing-a-new-format#some-examples

**Comment by Nodepad** [comment]
@XVilka Thank you, I've missed bits field in RBinSection structure.
But what about objects with pages especially iterated and nullable ones? RBinSection only contains `paddr` field which points to raw data.

**Comment by radare** [comment]
You can specify arch/bits per section. Which overrides file defaults. It is also supported at ranalfunction, but out of the scope here

**Comment by Nodepad** [comment]
Could someone answer to this question:
LE executable contains "objects" which similar to sections in other bin plugins. But this objects don't contain raw data. Instead it consist of pages which can be nullable, contain iterated or raw data. Could someone help about how to properly implement this staff?

**Comment by radare** [comment]
I guess those raw data objects are similar to elf's bss sections which are initialized by the loader and used at runtime, right? this is not yet handled for ELF, but i would suggest you to just print r2 commands to setup those regions with `o malloc://1024 0x803804`. I'll think in a way to allow bin plugins to run core commands after loading, or just specify those sections in a different way. for now, just printing the r2 lines.

**Comment by radare** [comment]
related https://github.com/radare/radare2/issues/1573

**Comment by XVilka** [comment]
@Nodepad also you can see how is OMF implemented, it should have the similar structure.

**Comment by Maijin** [comment]
ping @Nodepad

**Comment by XVilka** [comment]
Would be nice to have an examples, from both old IBM OS/2 and new Arca Noae Blue Lion system.

**Comment by radare** [comment]
do we have bins or so? maybe we should put this into extras, and as long as os/2 didnt gave us any license to do that meh :P

**Comment by marespiaut** [comment]
Hello everyone,

LE support for radare2 is still an interesting feature, as I have discovered it's more than useful for MS-DOS binaries that use a DOS extender.

Extenders like DOS4GW or PMODE/W wrap an 32-bit LE binary into 16-bit code. Therefore, when stripping the extender away, there's only a LE left to be analyzed.

**Comment by Maijin** [comment]
And again, please provide resources: slides/docs/existing disassembler/fileformat header/doc, existing binaries etc.

**Comment by marespiaut** [comment]
@Maijin 

Here are all the information I can give you on LE executable.

I got all information from @gynvael and @unavowed who made the Syndicate Wars port from DOS to Linux.

Official website - http://swars.vexillium.org/  
Blog post, part 1 - https://gynvael.coldwind.pl/?id=278  
Blog post, part 2 - https://gynvael.coldwind.pl/?id=279  
Presentation slides - http://vexillium.org/dl.php?recon_swars.pdf  
Video of the presentation - https://infocon.org/cons/REcon/REcon%202010/REcon%202010%20videos/recon_2010_gynvael_coldwind_and_unavowed.mp4

@gynvael and @unavowed made a disassembler for LE executable, called `swdisasm`, available at http://swars.vexillium.org/files/swdisasm-1.0.tar.bz2

It later got forked as `le_disasm` by @samunders-core.

I'm currently working on Rayman. A demo is available at https://archive.org/details/Rayman_1020. Decompressing and unbinding the demo executable produces a LE executable that works perfectly when ran with a DOS extender, like `DOS32A` (https://dos32a.narechk.net/).

[rayman_demo.le.zip](https://github.com/radare/radare2/files/2835499/rayman_demo.le.zip)
