### ISSUE TITLE
Extract complex types from PDB for availability for 't*' and 'pf' commands

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#3143]
When opening PDB file extract all types from it and load into the cparse.

See also https://github.com/wbenny/pdbex

**Comment by radare** [comment]
Wasnt this already done?

**Comment by XVilka** [comment]
Parsing - yes. Integration - nope.

**Comment by radare** [comment]
Isnt this listed with rabin2 -rP?

**Comment by XVilka** [comment]
@oddcoder check this one too pls.

**Comment by XVilka** [comment]
Also it should apply demangling too, if enabled.

**Comment by XVilka** [comment]
Seem broken too.

**Comment by XVilka** [comment]
One more though about integration - currently parsing pdb should be done with selecting baseaddress properly:
```
[0x1f00000]> .!rabin2 -B 0x1f00000 -rP some.pdb
```
Idea is to automate this, taking the baseaddress from the current session. Something like "odf some.pdb" - where new "odf" command should be able to load any kind of debug files: PDB, DWARF or whatever.

**Comment by oddcoder** [comment]
I am not sure if this is any related to me ... like this is new file structure ?

**Comment by XVilka** [comment]
@xarkes can you please check this one?

**Comment by XVilka** [comment]
@sivaramaaa and this - parsing is done, what is missing - loading and using those types automatically.
