### ISSUE TITLE
Verify all search commands honor eval

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#3239]
## Remain to be tested

✅ - Done and tested
🔴 - Need to be added and tested

| Command | cmd.hit | search.from-to | search.in | search.align | search.maxhits |
|---------|---------|----------------|-----------|--------------|--------------|
| /       | ✅       | ✅              | ✅         | ✅            |
| /j      | ✅       | ✅               | ✅          | ✅             |
| /!      | ✅       |                |           |              |
| /!x     | ✅       |                |           |              |
| /+      | ✅       |                |           |              |
| //      | ✅       |                |           |              |
| /a      | ✅       | ✅              |           |              |
| /A      | ✅       | ✅              |           |              |
| /b      | ✅       | ✅              |           |              |
| /B      | ✅       | ✅              |           |              |
| /c      | ✅       |                |           |              |
| /C      |         |                |           |              |
| /d      |         |                |           |              |
| /e      | ✅       |                |           |              |
| /E      | ✅       |                |           |              |
| /f      |         |                |           |              |
| /F      |         |                |           |              |
| /h      |         |                | ✅         | 🔴             |
| /i      | ✅       | ✅              |           |              |
| /m      | ✅       | ✅              |           | ✅            |
| /M      |         |                |           |              |
| /o      |         |                |           |              |
| /p      |         |                |           |              |
| /P      |         |                |           |              |
| /r      | ✅       | ✅              | ✅          |              |
| /R      |         |                |           |              |
| /s      | ✅        | ✅               | ✅          | ✅              
| /v      | ✅       | ✅              | ✅         | ✅            |
| /V      | ✅       | ✅              | ✅         | ✅            |
| /w      |         |                |           |              |
| /x      | ✅       | ✅              |           | ✅            |
| /z      |         |                | ✅         | ✅            |
| s/      |         |                |          |             | ✅

**Comment by XVilka** [comment]
@dukebarman can you please help with those?

**Comment by radare** [comment]
@Maijin ping

**Comment by radare** [comment]
Move to 1.0? @Maijin do you have some time to write tests for all those commands?

**Comment by Maijin** [comment]
First thing will be to ensure search.from, search.to and so on respect prior search.align

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
no time to check all this.. but will be good of @Maijin can do mark some checkboxes here

**Comment by radare** [comment]
booooring do we have tests?

**Comment by radare** [comment]
@Maijin

**Comment by radare** [comment]
@Maijin what about making a table instead of over 9000 lists?

**Comment by radare** [comment]
fixed and verified already some in this release. will begood to have tests for this too

**Comment by ret2libc** [comment]
This is probably very much outdated. Closing. Tests are always welcome.

**Comment by Maijin** [comment]
Most of this is still relevant unfortunately

**Comment by ret2libc** [comment]
@Maijin please open specific bugs for each of those. Generic bugs with "something in search does not work" usually tends to stale and be outdated and not useful for anyone.

**Comment by Maijin** [comment]
That's too much issues, one column probably hundreds

**Comment by ret2libc** [comment]
This sounds like a big refactoring is needed, otherwise it would be a catch a mole game. If you need to implement the same thing in over 30 places, there's something wrong.

**Comment by Maijin** [comment]
yes
