### ISSUE TITLE
bitmask for $z

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#3388]
should we use bitmasks for `$z` computation? the problem is, if u have `0xff,a,=,0x1,a,+=,$z,Z,=`, where a is 8-bit register, a will be 0 but Z won't get set here (but it should). So you have to use this hack for correct computation `0xff,a,=,0x1,a,+=,a,a,=,$z,Z,=`. We could use esil->lastsize for bitmask-generation. I fear that change could break something but i'm not sure.

**Comment by radare** [comment]
Try with a PR, but i guess we dont have enough esil tests to confirm a change doesnt breaks anything.

**Comment by XVilka** [comment]
sounds nice for me

**Comment by Maijin** [comment]
ping.
