### ISSUE TITLE
Retrieve RVA from imports

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#347]
In 0.9.8 (in contrast to 0.9.6), `rabin2 -ri` does'nt export the rva of the import inside the PLT, because they are considered symbols. But this method creates some confusion:
- symbols are prefixed with 'imp' which can be problematic if a symbol is named like this. One will overwrite the other..
- imports are indexed by ordinals, so there should be a way to retrieve them using the api
- maybe we should prefix those symbols with 'plt.' instead of 'sym.imp.' ?
- the naming colision still exists, and imho, they should be flagged in a different flagspace.

**Comment by XVilka** [comment]
Reviving this discussion

**Comment by XVilka** [comment]
@radare what about this one? Any updates on this?

**Comment by radare** [comment]
No updates. The rbin refactoring hasnt happened yet.

**Comment by trufae** [comment]
Closing, nobody will give any relevant feedback and we are in a good shape now
