### ISSUE TITLE
Radare2 is missing section search regex capabilites

### ISSUE THREAD

**Issue by shiftre** [radareorg/radare2#3554]
When listing sections ("S") in r2 it is not possible to search a section or a program header using regex.

It is however possible to pipe them to grep and find them but a proper way to do that would be to use an external utility.

**Comment by crowell** [comment]
this is the case for `~` to support regexp.
internal 'grep' just uses strstr or smth, we should use r_regex for this.

**Comment by crowell** [comment]
how about a var `e scr.regexgrep` or something?

**Comment by radare** [comment]
Wtf dont add config vars for this!

Should be enough if implemented in ~/.../... But do you really need regexp for this? There's also VF_ which can be helpful in your case

**Comment by shiftre** [comment]
what does VF  do ?

**Comment by radare** [comment]
it’s explained in V?

also, i said VF_, not VF.

VF is a visual mode to walk over the flagspaces and flags.
VF_ is the same, but using the hud interface and mixing comments and other meta info for quick searching

**Comment by ret2libc** [comment]
This hasn't received any attention for a long while and I think it should be closed as radare2 has very easy way to export command output and integrate it with any kind of tool, so you can easily filter by regex with another system tool or by using r2pipe or other languages. Thanks!
