### ISSUE TITLE
Enable LTO builds

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#3929]
```
export CFLAGS=-flto
export LDFLAGS=-flto
```

For `sdb` this reduces the size of the final static binary in a half (60KB instead of 120KB). For r2 it produces an error, maybe because of the amount of symbols and a bug in the link-time-optimization gcc wrapper.

**Comment by ret2libc** [comment]
I was able to use the LTO option with meson just with:
```
$ CFLAGS="-flto" LDFLAGS="-flto" meson build ; ninja -C build
```
it did compile correctly. 
```
$ ls -la ./build-no-lto/binr/radare2/radare2
-rwxrwxr-x. 1 rschiron rschiron 26736 Jun 22 15:03 ./build-no-lto/binr/radare2/radare2
$ ls -la ./build-lto/binr/radare2/radare2
-rwxrwxr-x. 1 rschiron rschiron 26400 Jun 22 15:00 ./build-lto/binr/radare2/radare2
```
However, I don't think we should enable this, but people should use it if they feel so (distros usually enable all kind of necessary/default flags they have set).

**Comment by trufae** [comment]
lto imho makes only sense for static builds. im doing this already for my own static builds and it works quite well. 

ive fixed the issue in https://github.com/radareorg/radare2/pull/17138
