### ISSUE TITLE
"out of memory" crash

### ISSUE THREAD

**Issue by fenugrec** [radareorg/radare2#3961]
```
$> r2 -
x 0x03000000
```

Other sequences probably work too. r2 crashes with "out of memory : kill process [x] "
r2 version : latest git
OS : arch linux (32bit) running in VirtualBox (512MB RAM) running on winXP (32bit)

**Comment by fenugrec** [comment]
It's hard to get a bt because the whole VB slows to a crawl, but the top of the stack looks like this:
````
#0 vsnprintf()
#1 r_cons_printf() (format= "%c") at cons.c:599;
 size = 0xfffff7a8
 written = 1
#2 r_print_byte() idx=0x010f8fac
#3 r_print_hexdump() addr=0, len=0x0300ff00 at print.c:713
````

**Comment by radare** [comment]
It is running in 32bit? Maybe it is considering the size as negative which asserts into windows libc.

I will commit a fix soon

**Comment by fenugrec** [comment]
I'm having trouble browsing code atm, but it's probably caused by : 
1) I.buffer_sz is "int" (signed)
2) palloc() does no bounds checking before setting I.buffer_sz
3) in r_const_printf(), you have "size_t" which is unsigned, and != int, with some casts to/from ints. 
There's probably a few bugs related to size_t vs int, fixing all of those will not be pleasant : )

**Comment by radare** [comment]
Can you submit a PR?

**Comment by fenugrec** [comment]
I spent a few hours on this today, and I don't think there's an easy, clean fix.
- palloc() doesn't check the result of malloc()
- nobody verifies the success of palloc()

**Comment by radare** [comment]
it doesnt crashes on linux or osx at all ( it was not crashing either before). so this is just a windows issue and the only solution is to define some limits to avoid huge sprintfs

**Comment by Maijin** [comment]
Is also taking eating all the memory on linux

**Comment by radare** [comment]
But not dying. If you dump a huge amount of data you expect to get a huge amount of data. Not a crash in an internal operating system library

**Comment by condret** [comment]
can we just try to harden r2 more, in order to fix this?

**Comment by ret2libc** [comment]
Shall we just put a limit on the max number of bytes that can be read? Though I'm not very enthusiastic about this option...

**Comment by radare** [comment]
Im not a big fan of limits either but if you do big things in interactive the user must be prompted before esting all the memory or waiting a long time to finish

**Comment by XVilka** [comment]
@ret2libc @radare please check this one, I think can be closed?

**Comment by ret2libc** [comment]
I think nothing has changed on this, so I'm not sure. Though the bug is a very old one and there were no more complaints (?)

**Comment by radare** [comment]
imho it fine to close it

**Comment by fenugrec** [comment]
>  bug is a very old one and there were no more complaints (?)

partly because I haven't used r2 in many years !
palloc() looks better now, but what I said back then still has some truth:

- palloc() doesn't check the result of calloc()  : see https://github.com/radareorg/radare2/blob/9079a7bd96d9cc950002b813d6249ad1d97ce227/libr/cons/cons.c#L602
- some callers do nothing if palloc() returns false

I wasn't able to compile r2 for a quick test, and I'm not running the same setup, and not really interested in working on this further.
