### ISSUE TITLE
refractor bin api for siol

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#4086]
due to several api changes on the siol-branch we had to touch libr/bin/bin.c which uses stuff from io that i do not plan to reintroduce like this https://github.com/radare/radare2/blob/master/libr/io/io.c#L979 . well, now i'm not sure if this code still does the same. It would be nice if someone could review our changes and fix if needed. It would be even better if someone could refactor that code, someone who understands that having sections and maps for mapping is bullshit, and it's much better to use sections as wrappers for maps. if you need anything more in RIObind tell me.

**Comment by XVilka** [comment]
@radare @condret @ret2libc @thestr4ng3r I think this one can be closed, right? Please confirm

**Comment by ret2libc** [comment]
Let's just close this IMHO.
