### ISSUE TITLE
smash r_core io reimplementation

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#4087]
for siol we need to kick this out. Currently r2 builds on the siol-branch until it comes to the core.

**Comment by radare** [comment]
@condret any update on siol? or plans? or milestones?

**Comment by MaskRay** [comment]
I think condret was talking about think wrappers around `io.c` APIs defined in `core/cio.c`:

```
R_API bool r_core_read_at(RCore *core, ut64 addr, ut8 *buf, int size) {
	if (core) {
		return r_io_read_at (core->io, addr, buf, size);
	}
	return false;
}

R_API int r_core_is_valid_offset (RCore *core, ut64 offset) {
	if (!core) {
		eprintf ("r_core_is_valid_offset: core is NULL\n");
		r_sys_backtrace ();
		return R_FAIL;
	}
	return r_io_is_valid_offset (core->io, offset, 0);
}
```

They seem unnecessary

**Comment by ret2libc** [comment]
Closing this. Any refactoring is always welcome anyway. BTW, although wrappers that just wrap without doing anything else are probably useless, I think RCore has the duty to coordinate RIO, RBin, and whatnot, so it may make sense to have r_core wrappers.
