### ISSUE TITLE
Custom Charset translating commands

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#414]
I'm thinking about to add some st-commands(`psT`, `psTz`, `wsT`, `/sT`, `./sT`) for supporting unconventional code-charts like this [one](http://bulbapedia.bulbagarden.net/wiki/Save_data_structure_in_Generation_I#Text_data).
Maybe you remember [this](http://runas-racer.com/foo/incredible.png). It is nasty to overwrite the original string, if you can only use `wx` for this instead of `w`.
I think that there might be a lot of files using unconventional code-charts.

Should this be a cmd-plugin?
Where should I put code-charts? (I think it would be good if they were defined in files in a place like ~/.radare2/ )

**Comment by condret** [comment]
yes, /e is allready used now

**Comment by gogo2464** [comment]
Hello. Can you tell me more about the syntax of `psT` please?

**Comment by gogo2464** [comment]
I finished to made a new command to support gaeboy encoding.

I made an array of structs to store the custom chart encoding of the gameboy. I imagine we want more custom text encoding. Where can I store the arrays?

**Comment by radare** [comment]
please don't say "chart", chart encoding is nothing, but a typo, it's "char", from "character"

also i dont see why this stuff should be in sT for several reasons:

* s is for seeking
* uppercase letters in commands shouldnt be used
* none of the letters have any relationship with encoding chars

kazarmy have been working on character encoding things for the string search functions, he can probably share some ideas in this thread

**Comment by bast233** [comment]
I read your post again and I noticed `pe pokemon  # uses last selected encoding`.

**Comment by gogo2464** [comment]
I noticed your command `pe pokemon  # uses last selected encoding`.

**Comment by kazarmy** [comment]
I think it's fine that you want to do something like the table in https://en.wikipedia.org/wiki/Code_page_437#Character_set but for your own custom encodings. I think what @radare is saying that you should use `pst` instead of `psT` where `t` stands for table (or maybe even `te` and `pe`?). You do have to figure out suitable syntax yourself though, for both the command(s) needed and the data files. You can see the implementations of `eco` and `pfo` for example to see how commands with data files should be implemented.

Don't think this is a task for first-timers but I don't know what you're capable of so good luck!

**Comment by gogo2464** [comment]
@kazarmy I want to load values from a file. Do I implement my own file format and do I make a new function to parse it or do I use an existing function if it exists?


I inspected the files for `pfo` (radare2/libr/bin/d) and `eco` (radare2/libr/cons/d). I saw there are 2 different file formats: .h with c code for type definition only for `pfo` and cmds for `eco`.


I tried to make a .h header with values to get it from a function but the code has failed because the function used is made only for type definition for rabin2 and because my type is too complexe.  I also can not use cmds for my task.

**Comment by kazarmy** [comment]
> I inspected the files for pfo (radare2/libr/bin/d) and eco (radare2/libr/cons/d). I saw there are 2 different file formats: .h with c code for type definition only for pfo and cmds for eco.

If you check e.g. [radare2/libr/bin/d/elf64](https://github.com/radareorg/radare2/blob/46adf34e83e52d12c13181f69ebbac38c3f7a834/libr/bin/d/elf64), you'll notice that it's composed of cmds too. This is apparently the recommended way to define data files in r2 if you're doing them from scratch. This does mean that you can also choose to parse data files that are already in some standard format (say [CP437.TXT](https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP437.TXT)) if it's convenient.

----

> I want to load values from a file. Do I implement my own file format and do I make a new function to parse it or do I use an existing function if it exists?

If you check the code for `pfo` ([here](https://github.com/radareorg/radare2/blob/46adf34e83e52d12c13181f69ebbac38c3f7a834/libr/core/cmd_print.c#L1405-L1433)) and `eco` ([starting here](https://github.com/radareorg/radare2/blob/46adf34e83e52d12c13181f69ebbac38c3f7a834/libr/core/cmd_eval.c#L389-L390)), you will find that they will eventually call `r_core_cmd_file()`. Please use this function.

----

> I also can not use cmds for my task.

You can propose new cmds and even new api functions within reason.

----

> I tried to make a .h header with values to get it from a function but the code has failed because the function used is made only for type definition for rabin2 and because my type is too complexe. I also can not use cmds for my task.

Header files are probably too complicated for this (with their braces and whatnot). Follow Einstein's dictum that:

"Everything should be made as simple as possible, but not simpler."

and you should be fine.

----

> (radare2/libr/bin/d) ... (radare2/libr/cons/d)

Btw, thanks for this. Saved me some time in looking for the data files.

**Comment by gogo2464** [comment]
Thank you very much @kazarmy ! I did not read the part on types on the manual of radare2 yet ;). I should have read that. So I did not used to know the command `k` yet. Now I know it and I will use it in a file opened by the command `pse` that I implemented. When the file will be read, I will prorammatically read the database of radare2. I have already seen some functions. Good bye and give me good luck. ;)

**Comment by kazarmy** [comment]
Good luck! Just be prepared to change things depending on what @radare says 😁

**Comment by radare** [comment]
Someone fix the meaningless issue title

**Comment by gogo2464** [comment]
@kazarmy Thank you very much. I am currently waiting for opinion and change request.

**Comment by gogo2464** [comment]
The build as failed because as developped in the description of the draft pull request: I have generated files. I just wait to know if my folder encoding is on the right place. I can fix this issue. I just want to have opinion on it before.

**Comment by kazarmy** [comment]
> I just wait to know if my folder encoding is on the right place.

See @radare's [comment](https://github.com/radareorg/radare2/pull/16357/files#r399926994) here ... `libr/util/` doesn't have a `d` directory so it should be fine. If you think `util` is too generic, the location can be changed later if needed without much effect on the user. Right now focus on pushing the pr through.

More comments:

- Do first, ask for approval later.
- Do you need to change the encoding dynamically when r2 is running?
- @radare is the ultimate authority on this. If he wants you to define the charsets in a header file, well ... figure out the performance, maintenance etc. ramifications and defend your decision.

**Comment by kazarmy** [comment]
And please change the issue title.

**Comment by trufae** [comment]
This 7yo issue is one of the best examples of why i dont want to automatically close old issues

**Comment by gogo2464** [comment]
I know that people were talking on the future of radare2. I was waiting for.

**Comment by trufae** [comment]
I think we can close this issue, and create other ones for the specific stuff that is missing.
thanks @gogo2464 ! good work!
