### ISSUE TITLE
Implement wired-to-ground registers

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#4152]
MIPS and ARM64 archs have a zero register which always have 0 as a value. we need a way to specify this characteristic in the r_reg profile

**Comment by mrmacete** [comment]
as far i can understand there are several options, for example:

* it could be a new type, say "constant", using the optional field to set the "wired" value
* it could be a new type, say "zero" and it is always zero
* it can be a new flag like "read only" and we assume that the initial value is zero, or just add a field for the initial value

in all cases the major impact is in the r_reg_get_value / r_reg_set_value functions

**Comment by radare** [comment]
yep.  i though about those options too. i would vote for the simplest one. i would just modify the get_value to always return 0, in fact, those registers can be set, but the value is never altered, there’s no hardware exception if you try to change the value of a wired register. so it is not exactly const or read only. but more exactly, wired to ground. so maybe we should just go for the 2nd option (define it as zero), i have never seen any other arch with this kind of regs with different value than 0

**Comment by trufae** [comment]
This was implemented already when using `?` in the offset column in the regprofile

<img width="446" alt="Screenshot 2020-06-16 at 19 30 00" src="https://user-images.githubusercontent.com/6431515/84807612-cb486380-b007-11ea-9092-bc41c7dc4505.png">
