### ISSUE TITLE
Rewrite disasm_strings() from cmd_print.c in effective way

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#4178]
https://github.com/radare/radare2/blob/master/libr/core/cmd_print.c#L1380

Right now it's very slow and leaking through all the holes.

**Comment by radare** [comment]
i think many of those issues has been fixed. can you point out to any memleak in there? better to use specific issues rather than generic ones

**Comment by ret2libc** [comment]
> i think many of those issues has been fixed. can you point out to any memleak in there? better to use specific issues rather than generic ones

Agreed. Let's close this and reopen specific issues if/when needed. There are anyway big "TODO" comments in front of that function and I bet if one wants to refactor it he will do so without looking at a issue.
