### ISSUE TITLE
V[zZ] is confusing

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#4246]

**Comment by alvarofe** [comment]
what about to use visual code analysis menu and add `z` to select which function to fold and unfold?

**Comment by Maijin** [comment]
No, `z` is super useful, but nobody use `Z` changing the letter wouldn't hurt anyone

**Comment by alvarofe** [comment]
I discovered an issue i think introduced to avoid a crash recently. `j` goes up when approaching a folded function. 

http://asciinema.org/a/35is8r22x0lv7aeyboyrd87gb

**Comment by jvoisin** [comment]
I vote for changing `Z` to something else, or even remove it, since I'm not using it.

**Comment by trufae** [comment]
zZ no longer do zxoom in visual mode (rotate print modes and folding functions)
