### ISSUE TITLE
Implement Libs.private in the pkg-config files to allow --static compilations

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#450]

**Comment by trufae** [comment]
any comments on this @ret2libc ? we can have an r_core_static pkgconfig file for static builds because the --static thing have always failed to me. maybe you know better

**Comment by ret2libc** [comment]
This can be closed for me. meson correctly creates the pkgconfig files with the Libs.private required for static linking (I just need to make it compile the `.a` files, but once that is done it works perfectly).
