### ISSUE TITLE
Show ?? instead of ff unallocated area

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#4790]
Some disassemblers/hexeditors show it like this and it can be handy for the reader but a pain to implement because it must work in all print formats and you can't represent 257 values in 8bits

**Comment by ret2libc** [comment]
:+1:

**Comment by trufae** [comment]
I implemented this long time ago in hexdump and disasm:

```
e io.unalloc=true
e io.unalloc=?
```

<img width="972" alt="Screenshot 2020-06-23 at 17 03 00" src="https://user-images.githubusercontent.com/6431515/85420368-6646bd80-b573-11ea-8f6b-b775def3a85d.png">
<img width="817" alt="Screenshot 2020-06-23 at 17 03 10" src="https://user-images.githubusercontent.com/6431515/85420386-6c3c9e80-b573-11ea-86be-23dcf00e6c38.png">

**Comment by trufae** [comment]
The visual glitches are unrelated to this feature

**Comment by trufae** [comment]
and afaik there are tests for this

<img width="629" alt="Screenshot 2020-06-23 at 17 04 42" src="https://user-images.githubusercontent.com/6431515/85420547-a3ab4b00-b573-11ea-9a54-37a0a6ae07c3.png">

**Comment by trufae** [comment]
we may probablyu want to remove this option and just make it by default at some point

**Comment by ret2libc** [comment]
Woah! yes, definitely I think it makes sense to have `io.unalloc` set to true, once the visual glitches are fixed. Awesome ;)
