### ISSUE TITLE
Autoguess arch

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#4863]
It will be nice to have a command or a plugin to try different asm plugins and try to identify which ones result in valid code for the current block.

**Comment by XVilka** [comment]
I think it could be done using this algorithm:
1. Loop through available plugins
2. When in - try to perform simple analysis (functions only)
3. If block has number of functions greater than N with the bodies size greater than M (in opcodes, not in bytes) - it's marked as a probable detection
4. Exit loop.

**Comment by radare** [comment]
Maybe we should do this in radare2-extras and make this tool available via r2pm, as long as its not a core feature and can be implemented as a plugin or r2pipe

**Comment by ret2libc** [comment]
> Maybe we should do this in radare2-extras and make this tool available via r2pm, as long as its not a core feature and can be implemented as a plugin or r2pipe

I agree. This seems a very high level feature, for sure not an easy problem! I'm in favour of closing this and let people implement this kind of things as external plugins/tools.

**Comment by XVilka** [comment]
It's duplicate I think.
