### ISSUE TITLE
Finish SDBtization of the functions code

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#4913]
See `#ifdef FCN_SDB` in `libr/anal/fcn.c`

**Comment by alvarofe** [comment]
I have this still ongoing https://github.com/alvarofe/radare2/tree/fcn-store but using ht instead, two actually to group functions.

**Comment by radare** [comment]
@alvarofe maybe better to go for the siolization of ranal rather than sdbization to get proper performance and memory constraints in expenses of the disk serialization. what do you think?

**Comment by radare** [comment]
not gonna happen for this release, and i doubt it really matters now that we have rbtree and sdbdict

**Comment by XVilka** [comment]
What to do with this one?

**Comment by radare** [comment]
Imho kill
