### ISSUE TITLE
too many functions that do the same thing in r_util

### ISSUE THREAD

**Issue by crowell** [radareorg/radare2#5111]
`libr/util/str.c` for example has 4 functions for tokenizing, 4 for finding first/last characters in a string, and none of them uses the "sub-functions" to implement.

**Comment by radare** [comment]
How many times each one is used? Im aware of this and it was planned after 1.0, but if yoy are in the mood now go for it

**Comment by Maijin** [comment]
Example:

* https://github.com/radare/radare2/blob/master/libr/util/hex.c#L8
* https://github.com/radare/radare2/blob/master/libr/util/str.c#L175
* https://github.com/radare/radare2/blob/master/shlr/gdb/src/utils.c#L55

**Comment by radare** [comment]
the one from str.c should be removed and use the one in hex.c instead

i dont think we can kill the gdb one

**Comment by Maijin** [comment]
@radare https://github.com/radare/radare2/issues/696 then what about the 6th one ?

**Comment by radare** [comment]
tired of waiting just fixed that in f5a73b73d7517916e99a728e9a5e247682960d42

**Comment by Maijin** [comment]
This was an example for futur contributors.

**Comment by trufae** [comment]
I think we can close this issue, this is an on-going refactoring we are doing over time, unless a specific function is spotted or something spends the time to improve the apis it is better to just close the issue for now.
