### ISSUE TITLE
Breakpoint commands are not executed

### ISSUE THREAD

**Issue by monosource** [radareorg/radare2#5182]
Simple example:
https://asciinema.org/a/88v8zgh60xedoz4htc34hfhq2

Also tried with `"dbc 0x4028aa wx deadbeef @ rdx"` and it's left unchanged.

**Comment by radare** [comment]
this is : “breakpoint commands are not executed”

**Comment by jduck** [comment]
Based on the video it seems that setting rdx did not exactly do what one would expect either. Instead it seems to have behaved as if you had set ```edx=```.

**Comment by jduck** [comment]
Err nevermind. I misunderstood what ```*rdx=``` does hehe.

**Comment by jduck** [comment]
FWIW the simple test I added passes on both Linux (without issue) and OSX (after jumping through some signing/password prompt hoops). I'll add a more sophisticated test.

**Comment by jduck** [comment]
I don't know much about radare2 command process, but it seems like the address to write to gets lost somewhere in here:

```
#4  0x00007ffff7b249b4 in r_core_cmd_subst (core=0x55555575c5c0 <r>, cmd=0x555555891030 "wv 0xdeadbeef") at cmd.c:1245
#5  0x00007ffff7b286be in r_core_cmd (core=0x55555575c5c0 <r>, cstr=0x7fffffffa220 "wv 0xdeadbeef@rdx", log=0) at cmd.c:2245
```

**Comment by jduck** [comment]
@monosource The problem is that the registers are not synchronized before executing these commands. Try setting "cmd.bp" to ".dr*" or prepending ".dr*" to your "*rdx=0xdeadbeef"

**Comment by monosource** [comment]
Interesting; indeed, the values seem to be lost somewhere in the code, and `.dr*` forces them back in place. But I think the result of the `dbc` commands should be identical to the result of running them manually when reaching that breakpoint.

**Comment by monosource** [comment]
Found another bug, this time in loops: `dbc <addr> dr eax`. eax is not listed (or only listed at the end of the loop).

**Comment by jduck** [comment]
I agree with you. The thing is that currently the prompt command is changed when you activate the debugger. That is where the registers and so on are synchronized. I think this is not a workable solution and so I will hopefully be able to get things in better shape soon.

IMHO the prompt command is overkill for synchronizing such things. Think about it. If you hit a breakpoint and then execute several commands, is it really necessary to sync everything after every command??

**Comment by jduck** [comment]
I'm not sure about the loop issue. Can you put together a test script like the one linked above?

**Comment by radare** [comment]
Yep i know its suboptimal. But it was enough for my needs and was working properly. I use to develop doing iterations because its hard to understand all the problems you may face when implementing somwthing that needs to work on severa platforms and feature requests that are growing every day :)

So any enhancement is welcome here

**Comment by monosource** [comment]
@jduck https://asciinema.org/a/bh6njbp1yerpp1bc2hdw0em44 loop issue.

**Comment by jduck** [comment]
@monosource there is a loop program in radare2-regressions you can use to make the test. The compiled binary is in bins/elf/x64-loop ...

**Comment by jduck** [comment]
I think the root cause of this issue is "registers are not synchronized before executing breakpoint commands". Registers should be synchronized whenever the inferior stops and then kept up-to-date whenever any commands that change them are used. I'd like to introduce a "cmd.dbgstop" command to allow users to set commands to be executed on stop, but this is not sufficient for handling breakpoint commands.

**Comment by jduck** [comment]
Tracking the stop commands thing as https://github.com/radare/radare2/issues/5264 and this issue should become "registers not synchronized before executing breakpoint commands".
