### ISSUE TITLE
a crazy amount of time is spent in vfprintf

### ISSUE THREAD

**Issue by crowell** [radareorg/radare2#5202]
![!wow](http://i.imgur.com/QfPjn6D.png)

https://gist.github.com/d1c8b5525bc56759050c0815549504c8

**Comment by jjdredd** [comment]
how did you test?

**Comment by crowell** [comment]
@jjdredd `valgrind --tool=cachegrind prog`

**Comment by jjdredd** [comment]
that's not what i was interested in
you just started r2 and exited immediately?

**Comment by crowell** [comment]
oh, did `aaa` and exited. but it's the same even if you do nothing.

r_cons_printf gets called a billion times.

**Comment by radare** [comment]
Pls enumerate the callers but i try to avoid format strings as mich as possuble unless it simplifies code maintainance

**Comment by radare** [comment]
There are non-format-string functions in rcons that will perform better. In fact i think that rconsprintf checks if theres a % in the string before going into the real vprintf function, because concat is faster

**Comment by crowell** [comment]
cut it down a lot with https://github.com/radare/radare2/commit/c1457400308a98f88bed2a4b8f5b533f12dc8a77

there's still some work to do, also some big bottlenecks in other places like some lookup functions in capstone...

**Comment by ret2libc** [comment]
@crowell I'm closing this for now because many changes has happened since it was reported and I don't think it is useful to keep this opened for so long. If there are particular issues from a performance point of view, please open issues with explicit test cases.
