### ISSUE TITLE
How can I enable automatic metadata about operands in r2 anal plugin ?

### ISSUE THREAD

**Issue by Pyraun** [radareorg/radare2#5376]
Hi,

I would like to enhance my anal plugin on a toy architecture ([synacor](https://challenge.synacor.com/)).
r2 already has all the heuristics to detect ASCII immediate value in operands, can I reuse them with this new architecture?
### What I have.

``` nasm
0x00000008      13006500       out,101
```
### What I want.

``` nasm
0x00000008      13006500       out,101            ;'n'
```

Greetings,
Pyraun

**Comment by radare** [comment]
just fill the ->imm or ->ptr field of RAnalOp depending on the op

**Comment by Pyraun** [comment]
Ok thank you.

**Comment by Pyraun** [comment]
I talked a bit too fast, sorry.

There is no ->imm field in RAnalOp, so I tried with ->val and also ->src[] with a new RaAnalValue with the ->imm field set but any of them worked for me.

#### libr/include/r_anal.h
```C
typedef struct r_anal_op_t {
         // ...
	st64 ptr;       /* reference to memory */ /* XXX signed? */
	ut64 val;       /* reference to value */ /* XXX signed? */
	
        // ...
	RAnalVar *var;  /* local var/arg used by this instruction */
	RAnalValue *src[3];
	RAnalValue *dst;

        // ....
} RAnalOp;
```

What am I missing ?
Also I can't find the code in r2 where the ops are processed to fill the comments.

--
pyraun

**Comment by radare** [comment]
I mean ->val, sorry

**Comment by Pyraun** [comment]
Arf, even when I am filling ->val  no comment shows.

**Comment by radare** [comment]
uhm checking the src seems to be ->ptr, and set refptr to 0 if its immediate or 1,2,4,8 to specify memory reference

**Comment by Pyraun** [comment]
Yeah it worked! Thank you.
This part of the API is not so obvious. Is the ->val field deprecated ?

**Comment by radare** [comment]
i dont think ->val is used anywhere.. (only set by some anal plugs), but i agree that it’s not really clear and need to be cleaned up a bit, some days ago i was removing some fields from ranalop. if you have some time feel free to review and track the use of those and submit a PR simplifying it.

thanks!
