### ISSUE TITLE
Setting an Breakpoint changes opcodes of program

### ISSUE THREAD

**Issue by jnnj2019** [radareorg/radare2#5451]
Dear Sir or Madam,
First of all m an newbie for radare2

I'm trying to load an simple program giving below command
r2 -d arch1 
arch1 is an simple program from the Book Mac OS X & iOS Internal by Jonathan Levin which is displaying the different arch which is supported.

r2 -d arch1

I set an break point with command

db entry0

pd 10 @entry0  (decompile few bytes from program)

dc to execute the program.
Once again we i give below command 

pd 10 @entry0 & we see 0xFFFFFFFF bytes.

Am i doing anything wrong ? Please let me know.

Regards, JNNJ

PS: Attached is screen shot of what i did & output for better understanding.
![question-r2-break-point](https://cloud.githubusercontent.com/assets/20858234/17435090/161d4b9e-5b2c-11e6-95eb-8424eb6c0c3e.jpg)

**Comment by radare** [comment]
are you using r2 from git? which version of iOS are you using here? is this a 32 or 64bit device?

**Comment by jnnj2019** [comment]
radare2 0.10.4-git 11928 @ darwin-arm-32 git.0.10.3-418-g48b44e8

ProductName:    iPhone OS
ProductVersion: 7.1.2
BuildVersion:   11D257

**Comment by Maijin** [comment]
can you retry using latest git version?
