### ISSUE TITLE
The http server doesn't work if hosted on Docker machine

### ISSUE THREAD

**Issue by ljani** [radareorg/radare2#5458]
Steps to reproduce:
- Install [Docker Machine](https://docs.docker.com/machine/) 0.12 on Windows 10 14393.10 x64
- Create a docker machine using the VirtualBox driver
- Start [`debian:latest`](https://hub.docker.com/_/debian/) with the port exposed (`9090`)
- Install the git version of radare2
- Start the web server: `r2 -c=h -e http.bind=0.0.0.0 --`
- From your own machine, curl the open port

Actual output:

```
docker-radare2 ❯❯❯ curl -v 192.168.99.100:32775
* STATE: INIT => CONNECT handle 0x600057750; line 1396 (connection #-5000)
* Rebuilt URL to: 192.168.99.100:32775/
* Added connection 0. The cache now contains 1 members
*   Trying 192.168.99.100...
* STATE: CONNECT => WAITCONNECT handle 0x600057750; line 1449 (connection #0)
* Connected to 192.168.99.100 (192.168.99.100) port 32775 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057750; line 1556 (connection #0)
* STATE: SENDPROTOCONNECT => DO handle 0x600057750; line 1574 (connection #0)
> GET / HTTP/1.1
> Host: 192.168.99.100:32775
> User-Agent: curl/7.50.1
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x600057750; line 1653 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057750; line 1780 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057750; line 1790 (connection #0)
* HTTP 1.0, assume close after body
< HTTP/1.0 200 ok
< Content-Type: text/html
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Connection: close
< Content-Length: 6004
<
* Recv failure: Connection reset by peer
* multi_done
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
curl: (56) Recv failure: Connection reset by peer
docker-radare2 ❯❯❯
```

Expected output:
- The web page
- Here's curl output from the docker machine:

```
docker@Default:~$ curl -v localhost:32775
* Rebuilt URL to: localhost:32775/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 32775 (#0)
> GET / HTTP/1.1
> Host: localhost:32775
> User-Agent: curl/7.49.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 ok
< Content-Type: text/html
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Connection: close
< Content-Length: 6004
<
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    SNIP
</html>
* Closing connection 0
docker@Default:~$
```

Other notes:
- curl'ing localhost and the port on the docker machine (boot2docker) works fine. This probably means that if you're running Docker natively, you won't see the problem and Docker Machine is required to reproduce
- The headers seem to go through, but the payload does not. It's like something happens [between `r_socket_printf` and `r_socket_write`](https://github.com/radare/radare2/blob/d07b7887865007519f019925972bc46c25238c1b/libr/socket/http_server.c#L86-L89) or [`r_socket_write`](https://github.com/radare/radare2/blob/d07b7887865007519f019925972bc46c25238c1b/libr/socket/socket.c#L516) is broken
- Running a different web server in the container works fine (`python3 -m http.server 9090`), thus I think this is a problem with radare. Let me know if you think I should report this to the Docker team or the VirtualBox team instead.

EDIT: also, the web server sees the connection:

```
Starting http server...
open http://127.0.0.1:9090/
r2 -C http://127.0.0.1:9090/cmd/
[HTTP] 192.168.99.1:2469 /
```

The client IP differs if the request originates from the docker machine:

```
Starting http server...
open http://127.0.0.1:9090/
r2 -C http://127.0.0.1:9090/cmd/
[HTTP] 172.17.0.1:39024 /
```

**Comment by ljani** [comment]
Also, looking at the traffic with Wireshark, I see some packets `RST` flag send.

This is probably related to #3400?

**Comment by ljani** [comment]
Adding `r_sys_usleep(1000 * 1000);` after the [`r_socket_write`](https://github.com/radare/radare2/blob/d07b7887865007519f019925972bc46c25238c1b/libr/socket/http_server.c#L86-L89) seems to fix the issue. Definitely a race condition.

**Comment by ljani** [comment]
Ah, right. My TCP programming is a bit rusty. Anyway, you're supposed to wait for the client to close the connection to make sure it has received everything. So, you're supposed to read the socket to ensure the client has received the data. [Currently this is done only on Windows and it should be done on Linux as well](https://github.com/radare/radare2/blob/d07b7887865007519f019925972bc46c25238c1b/libr/socket/socket.c#L271-L274).

**Comment by radare** [comment]
We cant wait for the client to close the connection because no browser does that. They always keep all connections open and do more connections to paralelize more requests. The r2 webserver aims to use http/1.0 which doesnt permits multiple requests per connection.

One workaround would be to use a nodejs server using r2pipe. Which is about 5-20x faster than the current r2 webserver and will not have thise problems.

Adding more delays on each connection will slowdown the transfers unless we delegate that operation in a separate thread to allow the main thread handle more requests

**Comment by ljani** [comment]
Actually the browser should close the connection if `Connection: close` header is specified. Sure there are misbehaving implementations and you should guard against them. There's also `SO_LINGER`, but after a bit of reading there are some downsides to using it.

I agree that the performance is not very good because of blocking. But poor performance is better than a broken implementation.

Anyway, as a workaround I guess it's easier to setup a reverse proxy with eg. Nginx.

**Comment by radare** [comment]
Yep the theory is nice. But actually they ignore that header

**Comment by radare** [comment]
You can try to send a patch if you feel brave :)
