### ISSUE TITLE
Feature request: writing output of commands to fd

### ISSUE THREAD

**Issue by monosource** [radareorg/radare2#5520]
There are cases in which you don't want the result of an operation in radare2 to be written to memory, but to stdout.

Examples:
- decrypting some memory region and checking if it results in a printable string before committing to that decryption key
- De Bruijn pattern to copy and paste when debugging

This could also have uses for other fds, like open files or sockets.

**Comment by radare** [comment]
You can use io.cache for this . Theres a command (wc) that allows to list all the changes done in that cache and then you can commit, dump, discard, etc

**Comment by radare** [comment]
I dont see why putting this on a separate fd or socket is gonna solve any problem at all

**Comment by monosource** [comment]
It's not about solving a problem, but about improving workflow.

Example like you describe it:
```
[0x00000000]> e io.cache = true
[0x00000000]> wopD 100
[0x00000000]> ps 100
AAABAACAADAAEAAFAAGAAHAAIAAJAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAeAAfAAgAAh
[0x00000000]> wcr
```

If writing to fd was possible:
```
[0x00000000]> wopD 100 @fd:1
AAABAACAADAAEAAFAAGAAHAAIAAJAAKAALAAMAANAAOAAPAAQAARAASAATAAUAAVAAWAAXAAYAAZAAaAAbAAcAAdAAeAAfAAgAAh
```

**Comment by radare** [comment]
you should be able to do this using the @o:fdnumber thing


just read the ?@? documentation

**Comment by monosource** [comment]
`wopD 10 @o:1` prints nothing.

 Am I using it wrong?

**Comment by radare** [comment]
@o uses r2 filedescriptors which are unrelated to the kernel ones.

So you want to print that pattern to stdout? this should be done with wopD* instead to make it consistent with other commands.

**Comment by Maijin** [comment]
ping1 @monosource

**Comment by monosource** [comment]
> So you want to print that pattern to stdout? this should be done with wopD* instead to make it consistent with other commands.

```
[0x00000000]> wopD* 100
[0x00000000]> 
```

No dice.

**Comment by ret2libc** [comment]
`wopD* 100` seems to be working now. I'm closing this. Thanks for opening this.
