### ISSUE TITLE
Add debug plugin callbacks to inject/unload dylib

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#5767]
Base code from:

OSX: https://github.com/stephank/inject_dylib
OSX: https://github.com/rodionovd/task_vaccine/

libgum. as a portable way...

the simplest solution would be to just resolve the dlopen symbol in the target process and inject code that calls it with a specific library as argument. This is also possible to do with r2frida

**Comment by trufae** [comment]
I think Frida does a great job at this and r2 can use r2frida to address this feature I would say we can close this issue because it can be also implemented using `dx` if improved a little bit.
