### ISSUE TITLE
Debugger questions

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#5947]
Working on a converter from x64dbg to r2 here are some problem I faced (r2script only): 
x64dbg is using module name + address in his project file

I can display modules in radare2 via dmm, but:
- `dmm.` doesn't work #5944
- `dbm mybinary.exe 0x10` doesn't work with name of the binary
- `dbm blabla.dll 0x10` should maybe throw an error if this module isn't loaded yet or be ready to be handled when the module is loaded somehow
- There is no way to add comment based on module + offset (`CCum`)
- There is no way to add comment based on module + offset (`fm` already taken)

**Comment by radare** [comment]
dmm. works i have just tested it and the implemnetation is trivial, proof it otherwise

**Comment by Maijin** [comment]
@radare https://www.youtube.com/watch?v=L38YceH3-k0&feature=youtu.be here you go, randomness of radare2 debugger on windows :<

**Comment by Maijin** [comment]
@skuater see the video too

**Comment by XVilka** [comment]
Afaik it was fixed, please confirm

**Comment by Maijin** [comment]
That's really old, I'll close - you can find my draft for this here https://gist.github.com/Maijin/beff8af9116822c7a96ac34da110b430 but probably need full rewrite now
