### ISSUE TITLE
Goto shortcuts are not shown in Graph Mode Summary view

### ISSUE THREAD

**Issue by newlog** [radareorg/radare2#6018]
Basically, if you are in Graph Mode and press "p" 3 times (go to "summary" view) where all the functions are listed, the shortcuts (;[a]) are not shown as in the more detailed views.

Not sure if this is a bug  or just working as designed. If it's the latter, maybe it would be useful to wonder why was it designed like that, given that moving around functions is best done in the summary view.

If needed, I can create an asciinema to show the issue.

**Comment by Maijin** [comment]
If you want this you can just VV then - multiple time until you get:

![image](https://cloud.githubusercontent.com/assets/1408600/19627175/61105c60-9941-11e6-8d9b-34210be87611.png)


No ?

**Comment by newlog** [comment]
Thanks for the prompt answer, sorry I don't have a laptop in hand to add screenshots.

The problem with that view is that it not show inner function calls. For example, the first graph box can call many other functions, and that's not shown. In the summary view, those calls are shown, but you don't have the shortcuts.

Thanks again

**Comment by Maijin** [comment]
Screenshot please.

**Comment by ret2libc** [comment]
I think shortcuts are printed in any mode right now, so I'm closing this bug. Please re-open if I misjudged. Thanks for your report!
