### ISSUE TITLE
build all script/target

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#6031]
Include as much as possible - lang plugins (for pipes inside the sessions), radare2-extras, etc...

For:
- Travis
- Coverity
- Clang analyzer

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/sys/all.sh this apparently is useless should be used for this purpose then?

**Comment by radare** [comment]
maybe this should go into -extras or -pm .. i dont think r2 should be in charge of building the other repos

**Comment by radare** [comment]
ping?

**Comment by XVilka** [comment]
This is a long run goal.

**Comment by Maijin** [comment]
r2pm are mostly covered they just need to be fixed once for all and add the github cron

**Comment by ret2libc** [comment]
Could you explain this issue more?

**Comment by ret2libc** [comment]
I'm pretty sure there is already another issue for building everything. I'm closing this.
