### ISSUE TITLE
Mouse wheel support

### ISSUE THREAD

**Issue by jvoisin** [radareorg/radare2#610]
It would be nice to have mouse wheel support in r2.

**Comment by qsantos** [comment]
Enabling mouse wheel disables usual terminal mouse events, making copying and pasting impossible. It might be better to set `scr.wheel=false` by default.

The only situation were both mouse wheel and mouse buttons work fine is `less` on `gnome-terminal` because of non-compatible patches.

**Comment by radare** [comment]
Copypaste works if you click first once and then drag the mouse to make the selection. Then press enter to go back to wheel mode

**Comment by radare** [comment]
Xterms and ncurses are a mess. R2 doesnt uses ncurses so we can do so magic tricks like truecolor and such, but making this thing compatible with all the terminals is hard. I use xterm and iterm2 most of the time

**Comment by XVilka** [comment]
I can start "TrueMouse support in the terminals" crusade, if you want.

**Comment by jjdredd** [comment]
lol, sounds epic

**Comment by qsantos** [comment]
@radare : I think you meant **right** clicking. It's a good compromise but really is not obvious. Documenting this when setting `scr.wheel=true` is the best option I can think of now.

**Comment by john-peterson** [comment]
What about horizontal scroll in `VV` I use it in termux

**Comment by trufae** [comment]
Termux diesnt support horizontal scrolling, same as many other unix terminals. But r2 have the m/M keys to toggle vertical/horizontal behaviour when the mouse wheel is used
