### ISSUE TITLE
VV: Broken home/end/mousewheel down in mouse:node-x mode

### ISSUE THREAD

**Issue by dequis** [radareorg/radare2#6155]
Tested with st, xterm, urxvt, gnome-terminal (VTE) and st under tmux.

* Home doesn't work in urxvt or tmux. It works in plain st, xterm and VTE
* End doesn't work in urxvt, tmux or plain st. It works in xterm and VTE.
* Mousewheel down is the equivalent of home when using mouse:node-x mode
* Mousewheel up works

To reproduce:

1. r2 -A /bin/ls
2. s main
3. VV
4. Press down arrow
5. Press home (should break as stated above)
6. Press end (should break as stated above)
7. Press m three times
8. Mousewheel down (should send home)

The mousewheel down issue is a regression introduced by aeddf25348959fd1792de84cf965f155176ccf6d (the fix to #3688), first appeared in 0.10.0.

Pageup/pagedown did improve with that commit, but home/end have the caveats listed above.

[1]: https://github.com/radare/radare2/blob/0.10.6/libr/core/graph.c#L2640-L2645

**Comment by radare** [comment]
proof that i dont use any of those things :P

i never use arrows, HOME/END, urxvt or vte or tmux. r2 doesnt uses termcap so it tries to hardcode and guess some keycodes to work. feel free to send a pr fixing that
