### ISSUE TITLE
[anal] Thumb -> ESIL: stm/ldm should be post, not pre increment

### ISSUE THREAD

**Issue by ekiwi** [radareorg/radare2#6389]
I am not 100% sure on this, but the way I read the manual from ARM, the `ldm`/`stm` instructions increment the address after performing the first load/store.

Checkout the [Architecture Reference Manual](https://www.pjrc.com/teensy/beta/DDI0403D_arm_architecture_v7m_reference_manual.pdf) section `A7.7.40` (LDM) and section `A7.7.156` (STM).

Currently the ESIL that is emitted by `r2` performs the first access at a `4` byte offset.

**Comment by ekiwi** [comment]
Once this has been confirmed as a bug, I will start working on a fix.

**Comment by radare** [comment]
Cool thanks!

**Comment by ekiwi** [comment]
this is related to https://github.com/radare/radare2/issues/6432

**Comment by ninjahacker** [comment]
Ah. Yes. I've been working a lot on 32 bit. So if you already started, I haven't touched 16 yet. STR is completely overhauled now. I've a few minor things to patch up before the pull request, but it does all the bells and whistles. Conditional, pre/post increment, word, byte, half word, etc.

**Comment by ekiwi** [comment]
> I haven't touched 16 yet.

while the encoding of the instructions is different, as far as I know, the analysis code that emits the ESIL commands is the same, so your fix will most likely also fix this issue.

Maybe you could check if the test passes with your changes: https://github.com/radare/radare2-regressions/pull/651

**Comment by ninjahacker** [comment]
Sorry, I wasn't thinking about what was being said. Running the tests made it clear. I am working primarily on STR, and possibly LDR (although I may need a little break once STR is all sorted out -- I've written 100 test cases!). You are talking about STM and LDM which are completely different. So we shouldn't be overlapping at all.

**Comment by ekiwi** [comment]
> You are talking about STM and LDM which are completely different.

urgh sorry, my bad.

**Comment by XVilka** [comment]
Any updates?

**Comment by XVilka** [comment]
Ping?

**Comment by ekiwi** [comment]
> Ping?

sorry haven't had time to work on this.

**Comment by ekiwi** [comment]
No longer working on this. Sorry.

**Comment by XVilka** [comment]
It's still a bit though.

**Comment by 0x8008135** [comment]
@ekiwi Should be fixed with https://github.com/radareorg/radare2/pull/17347

**Comment by ret2libc** [comment]
Thanks @0x8008135
