### ISSUE TITLE
Incorrect offset with ARM android native library

### ISSUE THREAD

**Issue by Flat** [radareorg/radare2#6430]
# Problem

radare2 upon seeking to a position in the binary shows the correct hex, but writes to the wrong offset. using io.va = false shows the offset it thinks it correct (the wrong one) instead of obscuring it with the code that it should be.

# Steps to reproduce

1. Load attached .so in r2 ```r2 -w libandroid_runtime.so``` ([libandroid_runtime.so.tar.gz](https://github.com/radare/radare2/files/686187/libandroid_runtime.so.tar.gz))
3. run analysis 
```
aaa
aae
```
4. search for hex string ```/x FFF72DFD```
5. seek to hit ```s hit0_0```
6. attempt to write hex ```wx 00000000```
7. Print hex ```px```
8. See that nothing has changed and run radiff2 with the modified version and the original and see that some random other data has been overwritten.

I'm pretty new to this stuff so let me know if something is unclear or more information is needed.

**Comment by radare** [comment]
as a workaround you can set a high base address to avoid PA overlap with VA.

$ r2 -B 0x9000000 -w target.so

**Comment by Flat** [comment]
Looks like that does indeed make it work correctly for me.

**Comment by Flat** [comment]
Was this fixed recently? Otherwise why was this closed? The only suggestion was a work around.

**Comment by Maijin** [comment]
I thought this was a fix my bad

**Comment by Flat** [comment]
As of `radare2 4.4.0` this seems to work as intended.
