### ISSUE TITLE
ARM Register profile

### ISSUE THREAD

**Issue by ninjahacker** [radareorg/radare2#6500]
I fixed the bit offsets for the anal register profile, but the bit flags won't set (the cpsr register updates though). Do I need to make a change somewhere else to get this to be recognized?

> ar cpsr
0x00000000
> ar zf=1
> ar cpsr
0x40000000
> ar zf
0x00000000
> ar zf=0
> ar cpsr
0x00000000

**Comment by ninjahacker** [comment]
This only happens if cpsr is the last register in the profile. Mapping the bit fields (e.g. zf) to any other register works. I submitted a pull request (https://github.com/radare/radare2/pull/6504) with a ghost register "blank" to fix this for now. Obviously a better fix should be done later.

**Comment by alvarofe** [comment]
Comment from other issue
--
To make it easier to read by the user. This is the conversion table:

```
    R0–R15 and r0–r15
    c0–c15 coprocessor registers
    p0–p15 coprocessor registers
    a1-a4 scratch registers, synonymous with r0-r3
    v1-v8 variable registers, synonymous with r4-r11
    s0-s32 Vector Floating Point (VFP) single precision registers
    d0-d16 VFP double precision registers
    fpsid VFP system ID register
    fpscr VFP status and control register
    fpexc VFP exception register
    sb and SB stack base, synonymous with r9
    sl and SL stack base, synonymous with r10
    fp and FP frame pointer, synonymous with r11
    ip and IP intra-procedure call scratch register, synonymous with r12
    sp and SP stack pointer, synonymous with r13
    lr and LR link register, synonymous with r14
    pc and PC program counter, synonymous with r15

```
