### ISSUE TITLE
Don't handle well large binary.

### ISSUE THREAD

**Issue by Pyraun** [radareorg/radare2#6642]
Hi,
I was trying to take a look at the libxul.so (amd64) library which is near 1GB.
It's library coming from my own debug build of Firefox.
Both `$r2 libxul.so` and `$rabin2 -e libxul.so` freeze my computer (blow up my 8G RAM).

What's bothering me the most is the rabin2 issue because finding entrypoints is just about parsing the header no ?

I also tried with angr and IDA Pro and both of them did succeed to load the binary.

I made another test with a stripped version of this library, that reduces its size to 77MB.
This time `$rabin2 -e striped.so` succeeded but `$r2 striped.so` is still blocked.

```sh
$ ltrace r2 striped.so 
__libc_start_main(0x7ff77ae3dbcf, 2, 0x7ffe705ae868, 0x7ff77ae404c0 <unfinished ...>
r_list_new(2, 0x7ffe705ae868, 0x7ffe705ae880, 0)              = 0x7ff77ceeb010
r_list_new(0x7ff77ceeb010, 0, 32, 0x7ff776de3620)             = 0x7ff77ceeb040
r_list_new(0x7ff77ceeb040, 0, 40, 5)                          = 0x7ff77ceeb070
r_list_new(0x7ff77ceeb070, 0, 40, 5)                          = 0x7ff77ceeb0a0
r_sys_set_environ(0x7ffe705ae880, 0, 40, 5)                   = 0x7ffe705ae880
r_sys_getenv(0x7ff77ae41407, 0, 40, 5)                        = 0
r_core_init(0x7ff77b042980, 0, 128, 1031)                     = 0
strcmp("striped.so", "-p")                                    = 70
strcmp("striped.so", "-")                                     = 70
strcmp("striped.so", "-H")                                    = 70
getopt(2, 0x7ffe705ae868, "=0AMCwfF:hH::m:e:nk:Ndqs:p:b:B:a"...) = -1
r_config_get(0x7ff77cf6e810, 0x7ff77ae41491, 0x7ff776de3204, 0) = 0x7ff77cf876b0
strdup("striped.so")                                          = 0x7ff77cf943d0
r_sys_getenv(0x7ff77ae41533, 0x7ffe705af913, 0, 0x6f732e64657069) = 0
r_config_get_i(0x7ff77cf6e810, 0x7ff77ae4150a, 4096, 1331)    = 1
r_core_loadlibs(0x7ff77b042980, 0xffffffff, 0, 571)           = 1
r_list_free(0x7ff77ceeb0a0, 0x7ff77ceeb0a0, 0, 24)            = 0
r_bin_force_plugin(0x7ff77cf347d0, 0, 0, 0)                   = 0x7ff77cf347d0
r_str_home(0x7ff77ae4138d, 0, 0, 0)                           = 0x7ff77cf9e8f0
r_core_cmd_file(0x7ff77b042980, 0x7ff77cf9e8f0, 0x7ff77cf9e8f0, 0) = 1
free(0x7ff77cf9e8f0)                                          = <void>
r_str_home(0x7ff77ae41398, 0xffffffff, 0x7ff776de3630, 0x7ff77ceeb090) = 0x7ff77cf9e8f0
r_core_cmd_file(0x7ff77b042980, 0x7ff77cf9e8f0, 0x7ff77cf9e8f0, 0x7ff77cf944b0) = 0
free(0x7ff77cf9e8f0)                                          = <void>
r_str_home(0x7ff77ae413b3, 0xffffffff, 0x7ff776de3630, 0x7ff77ceeb090) = 0x7ff77cf9e8f0
r_file_is_directory(0x7ff77cf9e8f0, 0xffffffff, 0x7ff776de3628, 0) = 0
free(0x7ff77cf9e8f0)                                          = <void>
r_file_is_directory(0x7ff77cf943d0, 0xffffffff, 0x7ff776de3630, 0x7ff77ceeb090) = 0
strcmp("striped.so", "=")                                     = 54
strcmp("r2", "--")                                            = 69
r_config_get(0x7ff77cf6e810, 0x7ff77ae41491, 45, -1)          = 0x7ff77cf876b0
free(0x7ff77cf943d0)                                          = <void>
r_core_file_open(0x7ff77b042980, 0x7ffe705af908, 4, 0)        = 0x7ff77cf96940
r_core_bin_load(0x7ff77b042980, 0x7ff77cf96d60, -1, 24
```

Do you have any interest in these binaries as regression tests even though, they are quite big ?

**Comment by zonkzonk** [comment]
Hi, of course.
please provide a link or a base64 encoded blob somewhere. Note, my libxul.so is only 79mb. Are you using it with debug symbols?

**Comment by Pyraun** [comment]
Yes the biggest binary has debug symbols. Here a link to [download](https://www.dropbox.com/s/5mbxz71nwcgjvut/libxul.7z?dl=0) a 7z archive with libxul.so.

**Comment by radare** [comment]
yet another issue for the same problem

**Comment by radare** [comment]
use -e bin.strings=false to load faster, you can profile with valgrind to see why its that slow. also confirm that you are using r2 from git. but its known issue that loading big executables  takes some time and we are improving on every release. but generalistic issues like this doesnt help too much, profile, find the bottleneck and focus on that

**Comment by Pyraun** [comment]
Ok thanks, my bad i didn't look carefully at the closed issues I suppose so i didn't know the way to go.
I will try that.

**Comment by Pyraun** [comment]
I forget to mention, I'm working with the last version coming from git.

So I run `valgrind --tool=callgrind r2 libxul.so`.
With KCachegrind, I obtain this table and this graph:
![table](https://cloud.githubusercontent.com/assets/2685178/22598117/a825f0be-ea32-11e6-9c75-ca371ad8f058.png)

![callgraph](https://cloud.githubusercontent.com/assets/2685178/22596901/b92ea360-ea2d-11e6-9487-fc742dd2a282.png)

Does it help you ?

It seems the issue is linked to this [comment](https://github.com/radare/radare2/blob/master/libr/bin/format/elf/elf.c#L2438). As a result there is a tight loop [line 2457](https://github.com/radare/radare2/blob/master/libr/bin/format/elf/elf.c#L2457), which seems to be the bottleneck.

I don't really have an idea to fix that. Maybe gdb, which is fast when loading symbols, read the debug symbol in a lazier way ? Thus it could be a good example ?

Unfortunately, this is only the first bottleneck which occurs when there is debug symbols. I may look at the other one, which occurs on the stripped binary, later.

**Comment by radare** [comment]
thanks.

we can improve this function a lot by just avoiding this realloc:

                        tmp = (RBinElfSymbol*)realloc (ret, (nsym + count + 1) * sizeof (RBinElfSymbol));

if you have time feel free to optimize this, im quite busy right now.

**Comment by Pyraun** [comment]
Right now, I don't really know how to do that.
Do you have any pointers ?

**Comment by SchumBlubBlub** [comment]
working on this.

**Comment by Maijin** [comment]
Ping on this, what are new detected blocker ?
