### ISSUE TITLE
Pebble: text section gets defined with end < begin

### ISSUE THREAD

**Issue by robryk** [radareorg/radare2#6647]
```
$ radare2 pebble-app.bin 
 -- radare2 for FideOS, now with extra potato
[0x000006f0]> S
[00] * 0x00000046 mrw- va=0x00000046 sz=0x3e0225dfc vsz=0x3e0225dfc relocs
[01] . 0x00000080 mrwx va=0x00000080 sz=0xffffffffffffffc6 vsz=0xffffffffffffffc6 text
[02] . 0x00000000 mr-- va=0x00000000 sz=0x007c vsz=0x007c header
[0x000006f0]> aap
[>] Scanning mrwx 0x80 - 0x46 aap: Invalid search range 0x00000080 - 0x00000046
done
Analyzed 0 functions based on preludes
[0x000006f0]> ? 0x00000080+0xffffffffffffffc6
70 0x46 0106 70 0000:0046 70 "F" 01000110 18446744073709551616.0 18446744073709551616.000000f 18446744073709551616.000000

```

[The code](https://github.com/radare/radare2/blob/c0c0cba3398466661afed716f709f1fc404a752e/libr/bin/p/bin_pebble.c#L131) that creates these sections seems to assume that relocs will come after the code. Alas, at least in this particular case, they come before the code and thus we get a malformed text section.

EDIT: Actually, it looks like the reloc table location and length are nonsensical. I have no clue why, but this app successfully loads, so I'd guess that we should rather ignore nonsensical values there instead of doing something this surprising.

**Comment by robryk** [comment]
So, actually there are two different versions of the header. The new one is missing reloc table start (presumably we assume it starts just after the header). Thus, we end up parsing the reloc table size as reloc table start and the beginning of UUID as the reloc table size.

According to comments in pebble_process_info.h, the structure is missing the reloc table start address if and only if struct_version.major >= 0x09

**Comment by radare** [comment]
can you provide test files for the radare2-regressions repository?

also if you know what to patch instead of describing just send a PR for testing

thanks!

**Comment by robryk** [comment]
Sure, I'll do both during the weekend.

**Comment by robryk** [comment]
Test file: [repro-6647.zip](https://github.com/radare/radare2/files/764912/repro-6647.zip)

Sorry for the delay, will send a PR for the actual fix sometime soonish.

**Comment by radare** [comment]
❤️

**Comment by Maijin** [comment]
soonish...

**Comment by clach04** [comment]
@robryk did you have any luck with this?
