### ISSUE TITLE
make windows debugging ready for siol

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#6734]
siol does not have any extra sausages for a specific platform. plugin->data should be the place where platform specific things should get stored.
atm, on master, we have things like io->winbase, which is windows specific.
this needs to get removed, or siol won't build for windows.

Further more I think we should discuss, if there is a need for a .gettid callback in the io-plugin like the .getpid callback plugin that I added.
I don't want any direct access to RIODesc->data except from plugin land. This pointer is reserved for plugin usage, and should only be accessed by the plugin, if there is no good reason for an exception.

Yes I want to avoid code like this: https://github.com/radare/radare2/commit/a2a666eda8b789de3ada2f6891d1b679bbb59b4c#diff-088860d1dd32c200ff1ddc1cd2c5ea41L87

@skuater , @radare told me that you are our windows guy now, so could you pls go for this task. I would do it, but I don't know anything about the WinAPI

**Comment by XVilka** [comment]
@condret, @radare there were a lot of changes since, is this still valid?

**Comment by radare** [comment]
I dont see any reason for having this issue at all

**Comment by XVilka** [comment]
@GustavoLCR @yossizap please take a look and check if this should be closed.

**Comment by XVilka** [comment]
Closing as irrelevant then.
