### ISSUE TITLE
Opening file takes too long

### ISSUE THREAD

**Issue by rot256** [radareorg/radare2#6839]
I have a 10MB file, which I would like to debug.
However opening the file (without any analysis) in radare takes ~15 seconds.

The file in question: 
[move.zip](https://github.com/radare/radare2/files/797684/move.zip)

**Comment by radare** [comment]
-e bin.strings=false

90% of time is spent there and you probably dont need the strings carved from disk and loaded in memory

**Comment by radare** [comment]
132891 symbols. not bad

**Comment by radare** [comment]
```
pancake@~/Downloads$ time rabin2 -z move > /dev/null

real	0m8.306s
user	0m6.638s
sys	0m0.293s
pancake@~/Downloads$ time rabin2 -s move > /dev/null

real	0m6.877s
user	0m5.935s
sys	0m0.228s
pancake@~/Downloads$ time rabin2 -e move > /dev/null

real	0m5.916s
user	0m5.299s
sys	0m0.203s
pancake@~/Downloads$
```

we should use hashtables in the elf parser to avoid all those O(n) lookups

**Comment by radare** [comment]
try with r2 -e bin.relocs=false

**Comment by radare** [comment]
```
$ r2 -e bin.relocs=false -e bin.strings=false move
 -- Did you know that radare2 can decompile to assembly?
[0x0804829c]> ?T
plug.init = 31
plug.load = 81065
file.load = 187
```

**Comment by radare** [comment]
```
$ r2  -e bin.strings=false move
[0x0804829c]> ?T
plug.init = 9
plug.load = 94409
file.load = 125
``

**Comment by radare** [comment]
```
$ r2   move
 -- Add comments using the ';' key in visual mode or the 'CC' command from the radare2 shell
[0x0804829c]> ?T
plug.init = 11
plug.load = 57220
file.load = 246
```

**Comment by radare** [comment]
```
$ r2 move
 -- Thanks for using radare2!
[0x0804829c]> ?T
plug.init = 15
plug.load = 25562
file.load = 53
```

**Comment by radare** [comment]
time is reasonable now, we will optimize more stuff soon or late when the rbin refactoring times come

**Comment by radare** [comment]
we have rbin refactoring plans to solve this. and we are priorizing this after 3.0, so not sure if we may close this issue and just keep the issues that track the refactoring plans.

cc @ret2libc

**Comment by ret2libc** [comment]
Let's keep it open for now, I'll consider this binary when doing tests.

**Comment by ret2libc** [comment]
Closing. It takes considerably less now.
