### ISSUE TITLE
Make "Cd" marks permanent (do not depend from scrolling)

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#6871]
For example if I mark something "Cd 4" in a row, e.g. some kind of offsets array:
```
"Cd 4"
....
0x4320000c0 .dword pdb.SomeFunc1
0x4320000c4 .dword pdb.SomeFunc2
0x4320000c8 .dword pdb.SomeFunc3
0x4320000cc .dword pdb.SomeFunc4
```
If I scroll once, using "DOWN" key, it splits the mark of `.dword pdb.SomeFunc1`  in a half - it seeks to the 0x4320000c2 in this case and show e.g. someting like
```
0x4320000c2         0200 add dword [rax], eax
0x4320000c4 .dword pdb.SomeFunc2
0x4320000c8 .dword pdb.SomeFunc3
0x4320000cc .dword pdb.SomeFunc4
```

**Comment by radare** [comment]
There are several issues for this thing already

**Comment by ret2libc** [comment]
I don't think this is still relevant @XVilka . If you do `down` when there are meta defined it skips the entire meta, not just part of it. If I'm wrong, though, please re-open the issue.
