### ISSUE TITLE
Add reg state in darwin kernel and remove the arw printf

### ISSUE THREAD

**Issue by Siguza** [radareorg/radare2#7044]
Opening a darwin kernel in `r2` prints one line of garbage at the top.

E.g. iOS 10.2.1:

    bash$ r2 10.2.1/iPod7,1/kernel 
    arw 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000fffffff0070910700000000000000000
     -- The door controls time and space.
    [0xfffffff007091070]> 

Or with OS X 10.11.6:

    bash$ r2 /System/Library/Kernels/kernel 
    arw 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d0100080ffffff0000000000000000000000000000000000000000000000000000000000000000
     -- Warning, your trial license is about to expire.
    [0xffffff800010d000]>

I haven't seen this happen with any other kind of binary, but that may be due to their size - no other binary I have comes even close to the kernel's size.

My radare2 version:

    radare2 1.4.0-git 14156 @ darwin-x86-64 git.1.3.0-61-g6e64713
    commit: 6e647130d6a4d04ad5e9ee5542cb0b0dccec7ba3 build: 2017-03-16__17:00:11

**Comment by alvarofe** [comment]
This is cause r2 parses mach file and extract a reg state. Basically is a r2 command so nothing to be worried. As long as this feature is not implemented is just a printf

```
 arw <hexnum>    Set contents of the register arena
```

**Comment by Siguza** [comment]
Ahh, makes sense. Binaries other than the kernel usually have no `LC_UNIXTHREAD`.

But, so... unless this is a duplicate, I guess I'll leave it open until this is implemented?

**Comment by Maijin** [comment]
Yes please

**Comment by radare** [comment]
Maybe change the issue title to something clearer

**Comment by sferrini** [comment]
I think we can close this issue, registers are now (not sure since when) correctly set for iOS and macOS kernels.
