### ISSUE TITLE
References should specify the access type

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#7094]
This information shuold be extracted from the referencing instruction. For data references:

* READ `mov ax, [0x800]`
* WRITE `mov [0x800], ax`
* REF `lea ax, [0x800]`

As for namings 'READ' can be 'r', WRITE can be 'w', and REF.. can be PTR this is 'p'. The access type for all the cod refs should be exec.

In addition to the `CALL` `JMP` .. refs which should be of type EXEC

What's left:

* [ ] Define command syntax to set that information in the Ref struct
* [ ] Update the output of the ax commands to show that information
* [ ] Verify the correctness of the results

Those only make sense to be for axd and axs (data references), but ideally will be good to have it working for any for proper flexibility.

So my proposal is to add a 3rd argument specifying the access type:

* axd 0x808080 0x303030 w
* axd 0x808060 0x303030 r

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/7120

**Comment by radare** [comment]
Initial work done in 986ab7a6fda923350c2835b3f8302a09c0346bcd

**Comment by radare** [comment]
related to the xrefs rework you did

**Comment by radare** [comment]
This issue is very easy.. so ill just describe how to fix it:

* [ ] Expose the op->direction info in the xref->direction
* [ ] Show xrefs->direction in the `ax`output
* [ ] Profit

**Comment by radare** [comment]
I just implementd this a while ago its just not dfisplayed in the xrefs info. which is pretty sad. so just chk the RAnalOp.direction field on the referencing instruction and it will be fixed. it can take no more than 3 lines of code to solve this issue (and update the tests..)

**Comment by radare** [comment]
For example:

```
[0x100001237]> ao~write,opcode
opcode: mov dword [rip + 0x428f], 0x50
direction: write
```

**Comment by radare** [comment]
<img width="451" alt="Screenshot 2019-03-23 at 13 00 52" src="https://user-images.githubusercontent.com/917142/54865815-b1b85d80-4d6b-11e9-8aad-3f37bbc3b250.png">

so imho we have different ways to do that:

1) cache the op->direction inside ref->direction
2) cache op->direction by making ref->type a bitmask instead of enum
3) make that enum larger to support all combinations of direction+type
4) ax shouhld be analyzing the op and chking the direction bit when listing (slow and bad idea imho)

comments on this? @ret2libc

**Comment by radare** [comment]
ghidra copied us for being lazy
![IMAGE 2019-04-06 00:02:27](https://user-images.githubusercontent.com/917142/55658811-43f64200-57ff-11e9-907b-919b30c64929.jpg)

**Comment by radare** [comment]
another proof that the nsa snitch on us :P

![Screenshot 2019-04-11 at 14 37 27](https://user-images.githubusercontent.com/917142/55957740-58a36180-5c67-11e9-8d1b-e19f3da3e7d7.png)

**Comment by radare** [comment]
we cannot delay more this feature

**Comment by whoami-defnotme** [comment]
Just dug this issue up and I think it would be great to see this land. It'd be valuable to do things like "find all write references to the DATA section of my target binary."
