### ISSUE TITLE
reverse-i-search does not allow editing the found item before evaluation

### ISSUE THREAD

**Issue by ewtoombs** [radareorg/radare2#7130]
A history item found with ctrl-r can't be edited after it is found. The only way I've found to do so is to run the command as-is, then edit it after. I must say that's no ideal.

Ideally, after having found the history item you're looking for, hitting escape, ctrl-J, or the arrow keys should cancel the reverse-i-search and return to the regular line editing mode with the most recently found history item in the line buffer. This is how it works in bash, zsh, and the python shell, and is what I've come to expect of REPLs.

**Comment by radare** [comment]
Press ctrl-e or ctrl-a or left/right arrows and you can edit

I have never used ^j in my life to do this or even esc, because thats not vi mode, you can cancel with ^c

**Comment by radare** [comment]
I will enhance this reverse mode with this but  there are different ways to use the shell, i implemented the ones i use and the ones i expect, happy to learn some new ones, do you plan to fix this? Theres a commit from this week implementing the ^a/^e thing that you can take as an example.

If not ill do when i find some spare time
