### ISSUE TITLE
Parse __objc_selfrefs section and such

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#7259]
Refs:

* https://github.com/fireeye/flare-ida/blob/master/python/flare/objc2_xrefs_helper.py 
* https://www.fireeye.com/blog/threat-research/2017/03/introduction_to_reve.html

**Comment by radare** [comment]
ping @alvarofe

**Comment by YugoCode** [comment]
Porting the referenced script to radare2 using Python and r2pipe has been done by @alvarofe: https://github.com/alvarofe/r2-scripts/blob/master/ios/objc.py

https://github.com/radare/radare2/issues/9006 can be solved using the approach from the article.

**Comment by radare** [comment]
Done already by me in the aao command

**Comment by ret2libc** [comment]
Closing according to https://github.com/radareorg/radare2/issues/7259#issuecomment-469770470 . Please re-open if this is not done instead.
