### ISSUE TITLE
Add LEB128 support in RBuffer

### ISSUE THREAD

**Issue by cgvwzq** [radareorg/radare2#7267]
Using RBuffer API for reading leb128 values is a mess. Would be nice to have something like`r_buf_read_leb128_at` that returns the number of consumed bytes.

Links:
https://en.wikipedia.org/wiki/LEB128
https://github.com/radare/radare2/blob/master/libr/util/uleb128.c
https://github.com/radare/radare2/blob/master/libr/include/r_util/r_buf.h
https://github.com/radare/radare2/blob/master/libr/util/buf.c

**Comment by radare** [comment]
yeah seems useful for a bunch of file formats

**Comment by ret2libc** [comment]
I think this can be closed, see https://github.com/radareorg/radare2/blob/master/libr/util/buf.c#L645 . If this is not what you meant, feel free to re-open the issue.
