### ISSUE TITLE
notepad.exe 64bit/Win8 function boundaries totally off

### ISSUE THREAD

**Issue by pinkflawd** [radareorg/radare2#7430]
When analyzing notepad.exe 64bit from Windows 8, the detected functions' sizes are wrong in many cases. E.g. function 0x140001358 is noted as 31.005 bytes big, but the function following after is starting at 0x1400014c0.

```
[0x140002c80]> e anal.autoname = false
[0x140002c80]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
[0x140002c80]> afl | sort
0x1400010c0    5 30           fcn.1400010c0
0x140001270   29 29700 -> 671  fcn.140001270
0x140001358   18 31005 -> 820  fcn.140001358
0x1400014c0    1 43           fcn.1400014c0
0x140001500    9 30069 -> 150  fcn.140001500
0x140001574    1 6            fcn.140001574
0x140001bf8    1 6            fcn.140001bf8
0x140001c10   10 28220 -> 422  fcn.140001c10
0x140001d64   85 62513 -> 2111 fcn.140001d64
0x1400021d0    4 23043 -> 155  fcn.1400021d0
0x1400022f8   22 27675 -> 445  fcn.1400022f8
0x1400023b0    3 61993 -> 213  fcn.1400023b0
0x1400023f4    1 6            fcn.1400023f4
0x140002400    4 77           fcn.140002400
```

With jmptbl and hasnext activated the boundaries are still off:
```
[0x140002c80]> afl | sort
0x1400010c0    5 30           fcn.1400010c0
0x1400010df   84 30917 -> 1382 fcn.1400010df
0x140001270   29 29700 -> 671  fcn.140001270
0x140001358   17 31005 -> 507  fcn.140001358
0x1400014c0    1 43           fcn.1400014c0
0x1400014ec    1 20           fcn.1400014ec
0x140001500    5 110          fcn.140001500
0x14000156f    1 5            fcn.14000156f
0x140001574    1 6            fcn.140001574
0x14000157b 1769 63535 -> 46444 fcn.14000157b
0x140001bf8    1 6            fcn.140001bf8
0x140001bff    1 17           fcn.140001bff
0x140001c10    9 28220 -> 407  fcn.140001c10
0x140001d64   84 62513 -> 2108 fcn.140001d64
0x1400021d0    2 101  -> 118  fcn.1400021d0
0x140002236    1 17           loc.140002236
0x1400022f8    2 63           fcn.1400022f8
0x140002338    1 81           fcn.140002338
0x14000238a    1 30           fcn.14000238a
0x1400023a9    1 7            fcn.1400023a9
0x1400023b0    2 65           fcn.1400023b0
0x1400023f2    1 2            fcn.1400023f2
```

password infected
[notepad64.zip](https://github.com/radare/radare2/files/980889/notepad64.zip)

**Comment by radare** [comment]
This is why r2 have function sizes and function ranges. The range is big because the function is splitted in blocks located quite far between them. That happens sometimes when the analysis considers a far jmp to be part of the function. The other just sums all basic block sizes. It helps to find bugs :)

**Comment by pinkflawd** [comment]
The oversizes is what I get from aflj command accessing the 'size' attribute. To be brutally honest, I got no clue what all the numbers mean that afl shows :P 
The real size of e.g. 0x1400010df should be ~290 bytes.

**Comment by pinkflawd** [comment]
Another one with the same problem, 32bit cmd.exe from Win8. I looked at the JSON, the realsize numbers are still a lot too big. With my usual settings with jmptbl and hasnext activated, I find 944 functions, while there should be around ~460. 

password infected
[cmd.zip](https://github.com/radare/radare2/files/985989/cmd.zip)

**Comment by trufae** [comment]
Lots of things has changed and been improved in the analysis since the issue was filled. I think the current results are better, even if the fsize and bbsize differ that much it looks good to me by looking at the code. Please reopen with more specific info if it's still relevant to you. Thanks for reporting!
