### ISSUE TITLE
Add Interface where updating binary propogates changes

### ISSUE THREAD

**Issue by deeso** [radareorg/radare2#757]
Currently, it is not possible to update changes to strings, imports, etc. if a binary format is manually reloaded outside of the r_core_bin_load.  Updating these items requires the RBin object along with RCore, which seems cumbersome.  When Sdb is integrated, it should be possible for a bin format to update any information necessary upon loading or reloading instead of relying on libr/bin.c set_bin_items (which requires the RBinPlugin and the Bin objects).

**Comment by ret2libc** [comment]
I'm going to close this as too much has changed since this was opened and SDB is not really *the* solution to all problems. AFAIK it is also possible to reload current binary with stuff like `ib` or `ob`.
