### ISSUE TITLE
rabin2: names of imported ELF symbols incorrect on aarch64

### ISSUE THREAD

**Issue by armijnhemel** [radareorg/radare2#7570]
$ rabin2 -v
rabin2 1.5.0-git 14823 @ linux-x86-64 git.1.4.0-276-g747b30b
commit: 747b30b4288bc18909643324af4c5dec20537ca0 build: 2017-05-22__19:01:16

Running readelf on a binary from a recent Android firmware:

```
$ readelf --dyn-syms KmInstallKeybox | grep UND | grep OBJECT
    13: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND _ZNSt3__14cerrE
    14: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND _ZNSt3__14coutE
    15: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND _ZNSt3__15ctypeIcE2idE
    19: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND _ZNSt3__17codecvtIcc9mbst
    20: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND _ZNSt3__17num_putIcNS_19o
    32: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND __stack_chk_guard@LIBC (2)
```

which works as expected. However, it seems that rabin2 gets confused:

```
$ rabin2 -i KmInstallKeybox  | grep OBJ
ordinal=013 plt=0x00000000 bind=GLOBAL type=OBJECT name=__stack_chk_guard
ordinal=014 plt=0x00000000 bind=GLOBAL type=OBJECT name=__stack_chk_guard
ordinal=015 plt=0x00000000 bind=GLOBAL type=OBJECT name=__stack_chk_guard
ordinal=019 plt=0x00000000 bind=GLOBAL type=OBJECT name=__stack_chk_guard
ordinal=020 plt=0x00000000 bind=GLOBAL type=OBJECT name=__stack_chk_guard
ordinal=032 plt=0x00000000 bind=GLOBAL type=OBJECT name=__stack_chk_guard
```

As I am unsure whether or not it is legally OK for me to distribute the file, the file is coming from this archive:

https://dl.google.com/dl/android/aosp/marlin-n2g47t-factory-a25a7b1b.zip

You will have to do the following to get the data (just so you don't have to research offsets):

1. unzip the file
2. cd marlin-n2g47t
3. dd if=bootloader-marlin-8996-012001-1703151359.img of=initrd.gz bs=22138880 skip=1
4. gunzip initrd.gz
5. mkdir initrd-unpack
6. cd initrd-unpack
7. cpio -i < ../initrd

In the directory 'sbin' you will find the file KmInstallKeybox that this report is about.

**Comment by armijnhemel** [comment]
I tested a bit more with a few other files: this only seems to be a problem with OBJECT, not with FUNC.

**Comment by armijnhemel** [comment]
For other files there are additional issues. In the same Android firmware you can find libs/libftm_lib_battery_utility.so where some other problems manifest themselves. readelf says this (not: using symbol table, not just the dynamic symbols):

```
$ readelf --syms libftm_lib_battery_utility.so  | grep bss_start
    17: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
    50: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
```
(17 is coming from the dynamic symbols)

while rabin2 says this:

```
$ rabin2 -E libftm_lib_battery_utility.so  | grep bss_start
vaddr=0x00003008 paddr=0x00003008 ord=049 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=__bss_start
vaddr=0x00003008 paddr=0x00003008 ord=050 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=__bss_start
vaddr=0x00003008 paddr=0x00003008 ord=051 fwd=NONE sz=0 bind=GLOBAL type=NOTYPE name=__bss_start
```

ord=49, ord=50 and ord=51 are this according to readelf:

```
    49: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS _edata
    50: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
    51: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS _end
```

Also note that while readelf displays __bss_start twice (once in the list of dynamic symbols, once in the list of symbols) rabin2 does not. I am not sure if that is particularly relevant.

**Comment by armijnhemel** [comment]
Seems like the exact same issue as #7573, feel free to merge the two.

**Comment by 08A** [comment]
@XVilka this bug seems to be fixed

```
❯ readelf --syms ./initrd-unpack/libs/libftm_lib_battery_utility.so | grep bss_start
    17: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
    50: 0000000000003008     0 NOTYPE  GLOBAL DEFAULT  ABS __bss_start
❯ rabin2 -E ./initrd-unpack/libs/libftm_lib_battery_utility.so | grep bss_start
Dynamic tag 1879047925 not handled
Dynamic tag 14 not handled
Dynamic tag 26 not handled
Dynamic tag 28 not handled
17   ---------- 0x00003008 GLOBAL NOTYPE 0        __bss_start
```

**Comment by ret2libc** [comment]
@08A have you also checked the issues in the first comment as well (the ones about KmInstallKeybox)?

**Comment by 08A** [comment]
@ret2libc the result seems to be good.

```
❯ rabin2 -i ./initrd-unpack/sbin/KmInstallKeybox | grep OBJ
Dynamic tag 21 not handled
Dynamic tag 1879047925 not handled
Dynamic tag 32 not handled
Dynamic tag 33 not handled
Dynamic tag 25 not handled
Dynamic tag 27 not handled
Dynamic tag 26 not handled
Dynamic tag 28 not handled
13  0x00000000 GLOBAL OBJ      sym.imp.std::__1::cerr
14  0x00000000 GLOBAL OBJ      sym.imp.std::__1::cout
15  0x00000000 GLOBAL OBJ      sym.imp.std::__1::ctype<char>::id
19  0x00000000 GLOBAL OBJ      sym.imp.std::__1::codecvt<char, char, mbstate_t>::id
20  0x00000000 GLOBAL OBJ      sym.imp.std::__1::num_put<char, std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > >::id
32  0x00000000 GLOBAL OBJ      __stack_chk_guard
```

**Comment by ret2libc** [comment]
Ok then, let's close this unless the reporter thinks otherwise! Thanks @08a ;)
