### ISSUE TITLE
Add meson support to build for android

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#7629]
https://github.com/frida/frida/blob/36abe46a3c9354e7a7312b868bd7796431a69835/releng/setup-env.sh#L359-L512

https://github.com/frida/frida/blob/36abe46a3c9354e7a7312b868bd7796431a69835/releng/setup-env.sh#L817-L867

thx @oleavr

**Comment by trufae** [comment]
@ret2libc did it

**Comment by trufae** [comment]
see https://github.com/radareorg/radare2/pull/17150
