### ISSUE TITLE
DWARF info not loaded on OSX

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#772]
On OSX, the dwarf information is stored on a separate file, so it may not be found on the local file. we should load if available:

```
$ gcc -g a.c
a.out.dSYM/Contents/Resources/DWARF/a.out
```

The MACH0 file that stores this information is located at '<filename>.dSYM/Contents/Resources/DWARF/<filename>'

**Comment by XVilka** [comment]
should we postpone this to 1.0.0 ?

**Comment by radare** [comment]
Yes.

**Comment by radare** [comment]
cc @jpenalbae

**Comment by XVilka** [comment]
Same on Gentoo with `splitdebug`

**Comment by ret2libc** [comment]
Same on Fedora.

**Comment by trufae** [comment]
That's fixed already working otherwise open new ticket with reproducer
