### ISSUE TITLE
Failure to detect UTF-32 strings in ELF binaries

### ISSUE THREAD

**Issue by pyllyukko** [radareorg/radare2#7786]
Continuation of #926.

If I compile the following program to ELF binary:

```
#include <wchar.h>
int main() {
        wchar_t *str = L"Hello World\n";
        wprintf (L"--> %S\n", str);
        return 0;
}
```

```rabin2 -z``` returns nothing. Also checking the code as in https://github.com/radare/radare2/issues/926#issuecomment-76598180 doesn't show the string:

```
│           0x08048555      c745f4608604.  mov dword [local_ch], 0x8048660
│           0x0804855c      83ec08         sub esp, 8
│           0x0804855f      ff75f4         push dword [local_ch]
│           0x08048562      6894860408     push 0x8048694
│           0x08048567      e824feffff     call sym.imp.wprintf        ; int wprintf(const wchar_t *format)
```

Here's what the string looks like:

```
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x08048660  4800 0000 6500 0000 6c00 0000 6c00 0000  H...e...l...l...
0x08048670  6f00 0000 2000 0000 5700 0000 6f00 0000  o... ...W...o...
0x08048680  7200 0000 6c00 0000 6400 0000 0a00 0000  r...l...d.......
```

**Comment by Shaddy** [comment]
Did the same test but with: 

    -fwide-exec-charset=UTF-16 

UTF-16 instead of UTF-32

    - offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
    0x004005e8  fffe 4800 6500 6c00 6c00 6f00 2000 5700  ..H.e.l.l.o. .W.
    0x004005f8  6f00 7200 6c00 6400 fffe 0a00 0000 0000  o.r.l.d.........

which is detected by rabin2

    addr=0x004005ea paddr=0x000005ea ordinal=013 sz=24 len=11 section=.rodata type=wide string=Hello World

and isn't detected as well

    |           0x0040052e      48c745f8e805.  mov qword [local_8h], 0x4005e8
    |           0x00400536      488b45f8       mov rax, qword [local_8h]
    |           0x0040053a      4889c6         mov rsi, rax
    |           0x0040053d      bf08064000     mov edi, 0x400608
    |           0x00400542      b800000000     mov eax, 0
    |           0x00400547      e8c4feffff     call sym.imp.wprintf        ; int wprintf(const wchar_t *format)

**Comment by radare** [comment]
This is utf32. Not widestring. And its not supported by r2 yet. Thanks for reporting, ill implement support for it

Thanks

**Comment by XVilka** [comment]
Please send a PR to radare2-regressions.

**Comment by radare** [comment]
Should be fixed in master, please push the tests

**Comment by pyllyukko** [comment]
Thanks! That was fast❗️ I created a test case.

**Comment by radare** [comment]
I didnt implemented support for detecting those strings with anal.strings yet. Only for bin.strings, will try to find some time to do so

Thanks for reporting

**Comment by pyllyukko** [comment]
Should we re-open this then? I was mostly happy with bin.strings, so I closed this :)

**Comment by radare** [comment]
Yeah why not

**Comment by XVilka** [comment]
@kazarmy maybe you can check also this one?

**Comment by kazarmy** [comment]
Problem isn't specific to UTF strings.

**Comment by kazarmy** [comment]
> Problem isn't specific to UTF strings.

Sorry, `anal.strings` works with ascii strings. Misunderstood the problem.

**Comment by kazarmy** [comment]
Strings are detected as expected by both `r2 -A` and `rabin2 -z` on 75ee57bfb0386492d13d6d1c618e7f31bb235a04 for both the UTF-32 version ([source](https://github.com/radareorg/radare2/issues/7786#issue-237159119)) and the UTF-16 version ([source](https://github.com/radareorg/radare2/issues/7786#issuecomment-309718837)) when compiled under gcc 10.1.1, so closing this issue.
