### ISSUE TITLE
instruction alignment ignored by ESIL

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#7988]
on arm jumping to &1 addresses should switch to thumb and unaligned addresses on mips should throw an exception, etc..

**Comment by radare** [comment]
cc @condret @skuater

**Comment by radare** [comment]
we can make anal.arm to return an ESIL expression that switches asm.bits between thumb/arm and restores the PC when jumping to addr|1

**Comment by radare** [comment]
we need tests, and i think this was implemented already, but stepping into an invalid or unaligned instruction updates the PC when it shouldnt, so it needs more work here

**Comment by radare** [comment]
cc @alvarofe

**Comment by alvarofe** [comment]
This could be handled with anal hints, however when emulation at the end depends many on how you feed the program. If your assumptions are wrong you might end up putting wrong hints - although this could be set and the unset.

Is possible to set hooks when registers changes on ESIL - didn't look at it? Anal when dealing with arm, could hook when PC register changes and act accordingly

**Comment by radare** [comment]
The align info is provided by the anal plugin no need for hints here, but hints can modify the behaviour indeed

Yes you can do such hook

**Comment by ret2libc** [comment]
Closing this as long as there is no reproducer nor anything. It mentions something was already implemented, so it is not clear what should be done next. If you want to re-open it, please explain in a clearer way to remains to be done, with reproducer and such. Thanks!
