### ISSUE TITLE
[Feature Request] ASCII call graph of full program

### ISSUE THREAD

**Issue by xelxebar** [radareorg/radare2#8062]
## Overview

We can generate a Graphiz call graph of an entire program with the `agC` command; however, there doesn't seem to be a way to view this structure from within r2 itself.

Naively, I would expect such a call graph to be visible somehow from within the graph mode of `VV`.

**Comment by radare** [comment]
Yes it was visible inside VV but doing a callgraph of a big binary can take minutes so it was making visual irresponsive and i removed this code. But should work with agC if not it should be calling 2-3 lines of code

**Comment by xelxebar** [comment]
Thanks for the quick feedback. The `agC` command just outputs a raw DOT representation, no? Is there already a command to transform that into an ASCII representation?

**Comment by radare** [comment]
#if 0
// disabled for now, ultraslow in most situations
                case '>':
                        r_core_cmd0 (core, "ag-;.agc* $$;aggi");
                        break;
                case '<':
                        r_core_cmd0 (core, "ag-;.agc*;aggi");
                        break;
#endif

**Comment by XVilka** [comment]
I think maybe reusing algorithm from https://github.com/radareorg/cutter/issues/366 can help to draw it quicker.

**Comment by ret2libc** [comment]
I'm closing this because this seems to be already implemented.
```
[0x00004e60]> ag?
| agC[format]             Global callgraph
Output formats:
| <blank>                 Ascii art
| *                       r2 commands
| d                       Graphviz dot
| g                       Graph Modelling Language (gml)
| j                       json ('J' for formatted disassembly)
| k                       SDB key-value
| t                       Tiny ascii art
| v                       Interactive ascii art
```

So `agCv` should work.

 If there are particular requests about that mode, please open new issue with specific details.
