### ISSUE TITLE
Honor archinfo's ALIGN for data fetch/store

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#8089]
Right now anal.archinfo() returns 4 for mips, arm,. .  and 2 for thumb

this is exposed by the R_ANAL_ARCHINFO_ALIGN query. but we should add another R_ANAL_ARCHINFO_DATA_ALIGN to show the memory alignment restrictions to be honored by the analysis and the emulation engines. non-aligned memory accesses should result in an exception for those archs

**Comment by radare** [comment]
Should be done in https://github.com/radare/radare2/commit/16304fc9a474c324604b50517c7c4b6616feaa8f

but there are no tests and nobody tested it at all :D

also this must be used by the static analysis too, not just for emulation

**Comment by ret2libc** [comment]
Closing this as it was implemented. Whether it works or not... that is going to be known when someone really uses it :)
