### ISSUE TITLE
sys/python.sh seems to be failing

### ISSUE THREAD

**Issue by zardus** [radareorg/radare2#81]
I am getting the following from sys/python.sh:
# 

PYTHON_VERSION=2.7
PYTHON=python${PYTHON_VERSION}
# TODO: PREFIX=/usr

Using PYTHON_VERSION 2.7
Using PYTHON_CONFIG python2.7-config

==> Using valabind valabind 0.6.4 - pancake@nopcode.org
==> Using swig 2.0.4
Checking valabind languages support...
- python: yes
- perl: no
- ruby: no
- lua: no
- go: no
- java: no
- guile: no
- php5: /usr/bin/valabind-cc: 1: /usr/bin/valabind-cc: php-config: not found
  /usr/bin/valabind-cc: 1: /usr/bin/valabind-cc: php-config: not found
  no
- node-ffi: no
- ctypes: no
- cxx: yes (g++)
- valac: yes
  Supported langs:
- python
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking target system type... x86_64-unknown-linux-gnu
  checking for working directories... current
  using prefix '/usr'
  checking for c compiler... gcc
  checking for c++ compiler... g++
  checking for valabind... /usr/bin/valabind
  checking for swig... /usr/bin/swig
  checking for g-ir-compiler... no
  checking pkg-config flags for r_core... yes
  creating ./config.mk
  cleaning temporally files... done

Final report:
- PREFIX = /usr
- HAVE_SWIG = 1
- HAVE_VALABIND = 1
- HAVE_GIRCOMPILER = 0
- DEVEL_MODE = 1
  mkdir -p /usr/share/vala/vapi
  /usr/bin/install -m 644 vapi/_.vapi vapi/_.deps /usr/share/vala/vapi
  rm -f _.so r__
  Build r_core -lr_core -lr_config -lr_cons -lr_cmd -lr_util -lr_flags -lr_asm -lr_lib -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_sign -lr_diff -lr_socket -lr_fs -lr_magic -lr_db  
  valabind-cc python r_core -NRadare --swig -I../../libr/include -x --vapidir=../vapi ../vapi/r_core -I/usr/include/libr -lr_core -lr_config -lr_cons -lr_cmd -lr_util -lr_flags -lr_asm -lr_lib -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_sign -lr_diff -lr_socket -lr_fs -lr_magic -lr_db
  valabind -x -x --vapidir ../vapi -o r_core.i -m r_core ../vapi/r_core --swig -NRadare
  Unknown option -NRadare
  Try --help
  ... r_core.so
  Build r_bin -lr_bin -lr_lib -lr_util  
  valabind-cc python r_bin -NRadare --swig -I../../libr/include -x --vapidir=../vapi ../vapi/r_bin -I/usr/include/libr -lr_bin -lr_lib -lr_util
  valabind -x -x --vapidir ../vapi -o r_bin.i -m r_bin ../vapi/r_bin --swig -NRadare
  Unknown option -NRadare
  Try --help
  ... r_bin.so
  Build r_asm -lr_asm -lr_lib -lr_util -lr_parse -lr_db  
  valabind-cc python r_asm -NRadare --swig -I../../libr/include -x --vapidir=../vapi ../vapi/r_asm -I/usr/include/libr -lr_asm -lr_lib -lr_util -lr_parse -lr_db
  valabind -x -x --vapidir ../vapi -o r_asm.i -m r_asm ../vapi/r_asm --swig -NRadare
  Unknown option -NRadare
  Try --help
  ... r_asm.so
  cd .. ; make install-python
  make[1]: Entering directory `/opt/analrepo/build/radare2/r2-bindings'
  [ -e python/_r_core.so ] && true
  make[1]: *** [install-python] Error 1
  make[1]: Leaving directory`/opt/analrepo/build/radare2/r2-bindings'
  make: **\* [install] Error 2
  ==========================

Radare2 itself installs and works fine. Please let me know if I can provide more info :-)

**Comment by JonathonReinhart** [comment]
I'm seeing this in the latest of both `radare2` (https://github.com/radare/radare2/commit/e7bf11f) and `valabind` (https://github.com/radare/valabind/commit/0164f3b3ff16be1ed799f58070fd21c1873687c1).

```
$ ./sys/python.sh 
Already up-to-date.
=============
PYTHON_VERSION=2.7
PYTHON=python${PYTHON_VERSION}

[ -z "${PREFIX}" ] && PREFIX=/usr
ID=`id -u` 
if [ "$ID" = 0 ]; then
	SUDO=
else
	SUDO=sudo
fi
[ -n "${NOSUDO}" ] && SUDO=
=============
Using PYTHON_VERSION 2.7
Using PYTHON_CONFIG python2.7-config

==> Using valabind 0.9.1-0.9.0-5-g0164f3b
==> Using swig 2.0.10
Checking valabind languages support...
 - python: No valid PYTHON_CONFIG command found
no
 - perl: test_wrap.c:719:20: fatal error: EXTERN.h: No such file or directory
 #include "EXTERN.h"
                    ^
compilation terminated.
no
 - ruby: yes
 - lua: test_wrap.c:709:17: fatal error: lua.h: No such file or directory
 #include "lua.h"
                 ^
compilation terminated.
no
 - go: SWIG -go: -intgosize option required but not specified
no
 - java: test_wrap.c:135:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
no
 - guile: test_wrap.cxx:730:22: fatal error: libguile.h: No such file or directory
 #include <libguile.h>
                      ^
compilation terminated.
no
 - php5: test_wrap.c:706:18: fatal error: zend.h: No such file or directory
 #include "zend.h"
                  ^
compilation terminated.
no
 - node-ffi: no
 - ctypes: yes
 - ocaml: SWIG is buggy. Please set in ocamldec.swg the following line:
#define caml_array_length swig_caml_array_length
/usr/bin/valabind-cc: line 106: ocamlc: command not found
test_wrap.cxx:741:24: fatal error: caml/alloc.h: No such file or directory
 #include <caml/alloc.h>
                        ^
compilation terminated.
no
 - cxx: yes (g++)
 - valac: yes
Supported langs:
 - python
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr'
checking for c compiler... gcc
checking for c++ compiler... g++
checking for valabind... /usr/bin/valabind
checking for swig... /usr/bin/swig
checking for g-ir-compiler... /usr/bin/g-ir-compiler
checking pkg-config flags for r_core... no
This package is required
```
