### ISSUE TITLE
code analysis glitches when a basic block hits the beginning of a function

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#8129]
<img width="823" alt="screen shot 2017-08-05 at 00 24 44" src="https://user-images.githubusercontent.com/917142/28989329-dd60293a-7974-11e7-8874-7ee12dd137d3.png">

**Comment by MaskRay** [comment]
How is this view created?

**Comment by radare** [comment]
e cmd.cprompt=agf
af
V

**Comment by ret2libc** [comment]
@trufae I'm closing this as there is no reproducer and probably a lot has changed. If you can reproduce this exact issue again, please re-open it. Thanks!
