### ISSUE TITLE
reminder: fix reads close to UT64_MAX

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#8331]
![2017-08-27-040159_1920x1080_scrot](https://user-images.githubusercontent.com/5904302/29746499-da1e159e-8acb-11e7-9941-f10eb44e6fbf.png)

Aaaaand I messed up

**Comment by MaskRay** [comment]
This is expected. `UT64_MAX` has an indication of error in so many functions which return `ut64` as an address.

**Comment by condret** [comment]
so I seek into the map, and it works? No, this cannot be what it should be

**Comment by condret** [comment]
UT64_MAX is a valid offset and should not be abused for this. Otherwise, we'll face one day a super retarded platform, which maps 1 byte to UT64_MAX

**Comment by radare** [comment]
ut64-max is as an address is as valid as -1 as filedescriptor

**Comment by condret** [comment]
don't assume that

**Comment by radare** [comment]
unix assumes that, but i know splitting data and errors is a good practice outside unix standards, it just makes apis simpler

**Comment by MaskRay** [comment]
then many interfaces should be redesigned, like `int foo(arg0, arg1, ut64 *ret)` or `bool foo(arg0, arg1, ut64 *ret)`. I am for `int` when there may be more than 1 IO errors (or other errors outside of io/).

**Comment by condret** [comment]
@radare it is a corefeature of libsiol that this works. I know that this is a commonly used practise, but someone has to start being awesom, or the world stays shitty

**Comment by MaskRay** [comment]
Seems to be fixed

**Comment by ret2libc** [comment]
This is fixed for me as well. Closing.
