### ISSUE TITLE
r_io_create_mem_map and r_io_create_file_map

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#8465]
Do we really want this as an API functionallity? Or should be other APIs just go for the section_apply/reapply. What I don't like about it in the first place, is that it requirese exposure of pointers to io-internal sections. Yes there are other functions in io too, that do that, but I want to reduce their number slowly, for hardening. Second this is a very low level function, so I'm not sure if this should be in the api. Pls discuss

**Comment by alvarofe** [comment]
I made it as API cause the command `S` needed kinda the same functionality as `section_apply` so to avoid duplication I took the code out from section.c and made it public.

The function `r_io_create_mem_for_section` makes use of those two functions as well as `_section_apply_for_anal_patch` and so on.

**Comment by radare** [comment]
we have to kill the S command, so imho this stuff should go away or be refactored

**Comment by ret2libc** [comment]
I don't see these functions anymore in the code, so I'm closing this issue as I guess this was already resolved. Thanks!
