### ISSUE TITLE
use RInterval instead of RAddrInterval

### ISSUE THREAD

**Issue by condret** [radareorg/radare2#8511]
RAddrInterval has no type-field, so it cannot provide any interface to different types of intervals.
RAddrInterval api is provides less functionallity, and has a broken interval-type as default.

Discuss @MaskRay @radare @alvarofe

**Comment by MaskRay** [comment]
Look at your code, it is meaningless to keep a `type` field. After constructing, all interval types reduce to the same form.

```c
R_API bool r_interval_init (RInterval *interv, RIntervalType type, ut64 from, ut64 size) {
	if (!size || !interv) {
		return false;
	}
	interv->type = type;
	switch (type) {
	case R_INTERVAL_OPEN_OPEN:
		interv->from = from - 1;
		interv->to = from + size;
		break;
	case R_INTERVAL_OPEN_CLOSED:
		interv->from = from - 1;
		interv->to = interv->from + size;
		break;
	case R_INTERVAL_CLOSED_OPEN:
		interv->from = from;
		interv->to = from + size;
		break;
	case R_INTERVAL_CLOSED_CLOSED:
		interv->from = from;
		interv->to = from + size - 1;
		break;
	case R_INTERVAL_UNDEFINED:
	default:
		return false;
	}
	if (r_interval_first (*interv, NULL) > r_interval_last (*interv, NULL)) {
		//This is a hack, for my lazyness
		r_interval_init (interv, R_INTERVAL_CLOSED_CLOSED, from, UT64_MAX - from + 1);
		interv->type = type;
	}
	return true;
}
```

`r_interval_size` may return 0 for `[0, UT64_MAX]`, you'd better comment that such interval is forbidden. (I've done that in r_addr_interval.h)

**Comment by MaskRay** [comment]
You have a very bad understanding of interval types. I've seen you doing infeasible interval overlapping test several times (and of course when you reverted my commits)
When two intervals are non-empty, say they are both closed intervals:

`a->from <= b->to && b->from <= a->to`

With the `addr,size` representation, you cannot say they are half-closed intervals. The interval type incarnates only when they are used by `itv.addr` ot `r_itv_end (itv)`. Then you can see the call sites use them as half-closed intervals.

**Comment by condret** [comment]
we should at least use them inside of the mapping api as closed intervals. Bc this way it is tested and developed for 3 years. The idea is, that we can use all types of intervals, mix them, and it still works. If we decide for your approach, the RInterval must die and get replaced by your stuff. Does your api provide a way to init an interval like r_interval_init (from, to, type_closed) ?

**Comment by condret** [comment]
and I don't like map->itrv.addr = foo. yes i know setters are often bad, but here they would provide more flexibillity. Further, ensure that the om must print closed interval

**Comment by MaskRay** [comment]
If it's worthwhile, add a `r_itv_init_type (from, to, CLOSED_CLOSED)` or `r_itv_init_closed_closed (from, to)`. But I doubt it is useful. The most important merit of this commit is that it pinpoints all use sites to `RIOMap::{from,to}`. This is a step towards interval API.

**Comment by MaskRay** [comment]
I think `map->itv.addr = foo` is verbose, too. I'm still thinking what is a more beautiful solution. `map->itv.addr` is much easier to find than `->to` `->from` (because other interval types have not been migrated)

**Comment by condret** [comment]
migrate them all, not for r2, but for compabillity to any other project out there. I think it should be (in concept)
4 functions: get_open_from, get_open_to, get_closed_from, get_closed_to.
For r_io_map_add the addr; size is better than from; to , but we should not name it addr. just make it a general interval, not just one for addresses

**Comment by MaskRay** [comment]
It is called `RAddrInterval` b/c it supports your favorite address space wraparound. If it didn't, I would not name it `Addr`. Because the wraparound is not a characteristic of normal intervals.

If all replacements are done in a consistent way: `r_itv_end (map->itv) - 1`, we can `sed` it if `get_closed_to` is really needed. That will be easy, but the initial finding is difficult. I hope we are one the same page, b/c I cannot afford my commit being reverted again.

**Comment by condret** [comment]
what wraparound do you mean, you allways write wrap arround, but it wraps around nothing, it just supports the complete range of 64 bit

**Comment by condret** [comment]
such as every reasonable implementation should do (yes, I complain about most operating systems here)

**Comment by XVilka** [comment]
So, what you have decided here?

**Comment by radare** [comment]
https://twitter.com/radareorg/status/1001783229362274305 <https://twitter.com/radareorg/status/1001783229362274305>

**Comment by ret2libc** [comment]
Apparently RAddrInterval got removed. Closing this.
