### ISSUE TITLE
Loading an r2 project clobbers non-default CPU

### ISSUE THREAD

**Issue by GeoSpark** [radareorg/radare2#8662]
radare2 1.7.0-git 16210 @ linux-x86-64 git.1.6.0-985-gb99733b
commit: b99733b6270b2f0860213d8eeeae6d00a6a13fe6 build: 2017-10-02__13:03:42

I have a project file for an m68k binary that is compiled for a 68040 CPU.
The project file contains:
```
"e anal.cpu = 68040"
...
"e asm.arch = m68k"
...
"e asm.cpu = 68040"
```

Loading the project sets the arch and CPU correctly for disassembly, but then sets the CPU back to the default 68000. I.e.:
```
[0x00000000]> e asm.cpu
68000
[0x00000000]> e anal.cpu
68000
```

This value then gets saved in the project file, which breaks the disassembly when the project is reloaded.

This also happens when setting ```asm.arch``` from within r2:
```
[0x00000000]> e asm.arch=m68k
[0x00000000]> e asm.cpu
68000
[0x00000000]> e asm.cpu=68040
[0x00000000]> e asm.cpu
68040
[0x00000000]> e asm.arch=m68k
[0x00000000]> e asm.cpu
68000
```

So setting the architecture should check to see if the CPU is already valid and leave it alone if so.

**Comment by Maijin** [comment]
here is the line responsible for the update of CPU after an arch change https://github.com/radare/radare2/blob/master/libr/core/cconfig.c#L336
