### ISSUE TITLE
Continuing radare2 hangs debuggee (and probably itself)

### ISSUE THREAD

**Issue by Hi-Angel** [radareorg/radare2#8749]
Steps to reproduce:

1. Run `kate` *(a graphical application, but it should work with anything — I initially found it with Skype)*.
2. Attach radare2 using `radare2 -d $(pgrep kate)`
3. Type `dc` to continue executing process.

What happens:
1. kate doesn't respond, it just stops updating its window as if I didn't type `dc`
2. Pressing <kbd>Ctrl</kbd>+<kbd>c</kbd> in radare2 doesn't interrupt it either, looks like it hanged too.

What should happen:
1. kate should continue working as usual
2. Pressing <kbd>Ctrl</kbd>+<kbd>c</kbd> in radare2 should interrupt execution.

Additional info:
radare version is 2.0.1
Pressing <kbd>Ctrl</kbd>+<kbd>c</kbd> in terminal with Kate results in radare2 interrupting execution with 

	child stopped with signal 2
	[+] SIGNAL 2 errno=0 addr=0x00000000 code=128 ret=0 got signal...

So it seems like radare2 somewhat continues working.

**Comment by josediazfer** [comment]
The problem is when radare attach a running process and not when it debug a new process because SIGINT signal is sent it to the process that you are debugging only in the first case.
I think that we could do the following:
Create a new process group for child process "setpgrp" (no attach case) in such a way that don't send  SIGINT signal to child process.
Catch SIGINT signal in radare and invoke r_debug_kill (dbg, dbg->pid, dbg->tid, SIGINT) for both cases.

**Comment by radare** [comment]
@josediazfer can you send a PR?

**Comment by Cloudef** [comment]
This is pretty annoying, and the only reason I have to use gdb separately, and calculate offsets manually from gdb to r2.

**Comment by radare** [comment]
Then fix it or provide a simple test case to reproduce without depending on graphical apps and such., its just a matter of handling thread events properly, i dont use debugger too much lately, and i have other priorities, shouldn’t be difficult to fix.

Why do you calculate offsets in gdb? Just load r2 with the right base address

**Comment by Cloudef** [comment]
>Why do you calculate offsets in gdb? Just load r2 with the right base address

For some reason I couldn't get that work, that particular program was a dll run through rundll32.

**Comment by ret2libc** [comment]
To me this does not reproduce. I see the graphical application continuing working after `dc`. The only thing that is missing is that when you press ^C it would be great to stop the application and get back into the debugger.

**Comment by Hi-Angel** [comment]
> To me this does not reproduce. I see the graphical application continuing working after `dc`. The only thing that is missing is that when you press ^C it would be great to stop the application and get back into the debugger.

Well, maybe some graphical apps continue working. FWIW, I don't think the fact an app has graphics is the root cause, it's just that back when I tried I only see that happening with graphical apps.

I just tried latest radare git as of bbbf6546e2 commit with `kate` app as per steps to reproduce, still reproducible for me.

By the way, I also noticed an interesting behavior worth mentioning. After both `radare2` and `kate` got hanged, if I kill `radare2`, then terminal in which kate is running reports the following:

```
[1]  + 656216 suspended (signal)  kate
```

So if I execute `fg`, kate continues running as usual. Note: this only happens if I kill `radare2`.

**Comment by Hi-Angel** [comment]
> I just tried latest radare git as of [bbbf654](https://github.com/radareorg/radare2/commit/bbbf6546e2a25a7b20e7fd1b55503bff4dc99a2e) commit with `kate` app as per steps to reproduce, still reproducible for me.

To have more testcases, I also just tried:

* `gedit`: it does not hang immediately, but does when you try typing the text
* `gvim` this also does not hang immediately, not even if you type the text. But if you typed something, and try closing the app, then a popup appears which ought to ask you to confirm quitting without saving, and on that moment `gvim` hangs.

**Comment by abcSup** [comment]
I assume this happens when attaching a multithreaded application and `dc` fails to continue all threads.

```
$ sudo r2 -d $(pgrep kate)
= attach 28535 28535
bin.baddr 0x55bd08a50000
Using 0x55bd08a50000
Dynamic tag 12 not handled
Dynamic tag 13 not handled
Dynamic tag 25 not handled
Dynamic tag 27 not handled
Dynamic tag 26 not handled
Dynamic tag 28 not handled
Dynamic tag 1879047925 not handled
Dynamic tag 21 not handled
asm.bits 64
 -- radare2 is power, France is pancake.
[0x7f602e041bf9]> dpt
 - 28535 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f602e041bf9)
 * 28536 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f602e041bf9)
 - 28537 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f602e041bf9)
 - 28538 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f602e041bf9)
 - 28539 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f602e041bf9)
[0x7f602e041bf9]> dc
```
```
$ ps -T aux | grep [k]ate
abcsup    28535  28535  0.0  2.4 1017784 97236 pts/6   Sl+  13:21   0:00 kate
abcsup    28535  28536  0.0  2.4 1017784 97236 pts/6   tl+  13:21   0:00 kate
abcsup    28535  28537  0.0  2.4 1017784 97236 pts/6   tl+  13:21   0:00 kate
abcsup    28535  28538  0.0  2.4 1017784 97236 pts/6   tl+  13:21   0:00 kate
abcsup    28535  28539  0.0  2.4 1017784 97236 pts/6   tl+  13:21   0:00 kate
```

**Comment by abcSup** [comment]
> To me this does not reproduce. I see the graphical application continuing working after dc. The only thing that is missing is that when you press ^C it would be great to stop the application and get back into the debugger.

@ret2libc I am working on a similar issue. I figured out that it might be caused by `r_sys_signal (SIGINT, SIG_IGN);` in `linux_dbg_wait` which prevents the interrupt from triggering `r_cons` because it ignores the signal completely.
https://github.com/radareorg/radare2/blob/bbbf6546e2a25a7b20e7fd1b55503bff4dc99a2e/libr/debug/p/native/linux/linux_debug.c#L386-L390
