### ISSUE TITLE
Reopening projects are not opening bininfo atm

### ISSUE THREAD

**Issue by rlaemmert** [radareorg/radare2#8763]
At the moment reopening projects are not loading any bin info (i , ii, ie, iE...)
reproduce:
r2 -p <projectname> <file>
quit
r2 -p <projectname>
i

**Comment by thestr4ng3r** [comment]
The problem are these two lines: https://github.com/radare/radare2/blob/9197da06d00de404fa71ed098f9108f609fe114e/libr/core/project.c#L645 from #8635 
I don't know if just setting `file.path` and `file.lastpath` to empty strings is the right way to indicate the new format.

**Comment by thestr4ng3r** [comment]
Ok, so I guess the actual problem is not these two values not being set in general, but that `r_core_bin_load` is not called anymore:
https://github.com/radare/radare2/blob/9197da06d00de404fa71ed098f9108f609fe114e/libr/core/project.c#L441-L444
So i assume that should be correctly implemented through the project script.

**Comment by rlaemmert** [comment]
Its a bit complicated. Currently we save all maps and sections and to prevent double loading that we skipped using r_core_bin_load. 
My current idea to fix this is to save sections and maps that have been added
by the user so that we can use o* and on* again in projects.

**Comment by radare** [comment]
What about having a flag in rbin to avoid loading sections when opening a project instead? And we keep the bin symbols, entrypoint... from rbin but hold the maps, sections, files separately?

**Comment by rlaemmert** [comment]
Yea thats also an option i think. Would you add some additional option to the printed commands of o* and on* or where would you save this information?

**Comment by condret** [comment]
@thestr4ng3r thats not the problem, those config vars need deprecation

**Comment by thestr4ng3r** [comment]
@condret Yeah makes sense, they are pretty useless for multifile anyway. `r_core_project_info` has to be changed then too.

**Comment by radare** [comment]
I think that we should set prj.simple=true enabled by default. what do you think? at least it's more reliable :P

**Comment by thestr4ng3r** [comment]
It is already default iirc
