### ISSUE TITLE
Mapping multiple files into the same address space

### ISSUE THREAD

**Issue by forma-formarum** [radareorg/radare2#8779]
When trying to map another file with `ofs`/`om` into the address space, the second file is not displayed when using `xc`. With `io.va` off, all files get mapped at address 0x0, and can be switched between with `op`. With `io.va` on, only the file mapped to 0x0 is visible. 

I've made a gist documenting the issue: https://gist.github.com/forma-formarum/ba3db320ebfad7e700261040e6f47970

**Comment by radare** [comment]
Cc @condret

**Comment by trufae** [comment]
This is done via op command
