### ISSUE TITLE
r2 coredump analysis issue

### ISSUE THREAD

**Issue by iddoeldor** [radareorg/radare2#8823]
[code attached to reproduce]

When I open the coredump with gdb I get the following output, which is great because it tells me the exact address I need which is 0x414b4141

```
$ gdb -q ./vuln core
Reading symbols from ./vuln...(no debugging symbols found)...done.
[New LWP 17197]
Core was generated by `EPAEQAE'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x414b4141 in ?? ()
```

When I open with radare2 (using latest)

```
$ r2 -v
radare2 2.1.0-git 16529 @ linux-x86-64 git.2.0.1-235-g9197da0
commit: 9197da06d00de404fa71ed098f9108f609fe114e build: 2017-11-13__06:20:17
$ r2 core
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
arw 00100000050000000010000001000000001003000090fdf70000000000100000002002000500000000100000010000000020030000b0fff70000000000100000001000000600000000100000010000000030030000c0fff70000000000100000001000000400000000100000010000000040030000d0fff70000000000100000001000000600000000100000010000000050030000c0fdff0000000000200200
[0x08048000]> arw 00100000050000000010000001000000001003000090fdf70000000000100000002002000500000000100000010000000020030000b0fff70000000000100000001000000600000000100000010000000030030000c0fff70000000000100000001000000400000000100000010000000040030000d0fff70000000000100000001000000600000000100000010000000050030000c0fdff0000000000200200
[0x08048000]> dr
oeax = 0x00000001
eax = 0x00000000
ebx = 0x00001000
ecx = 0x00000005
edx = 0x00001000
esi = 0x00000001
edi = 0x00031000
esp = 0x00001000
ebp = 0xf7fd9000
eip = 0x00032000
eflags = 0x00000000
```

vuln.c
```
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>

char * not_allowed = "/bin/sh";

void give_date() {
    system("/bin/date");
}

void vuln() {
    char password[16];
    puts("What is the password: ");
    scanf("%s", password);
    if (strcmp(password, "pa$$w0rd") == 0) {
        puts("good");
        give_date();
    }
    else {
        puts("bad");
    }
}

int main() {
    vuln();
}

```
compiled via gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
`gcc -m32 -o vuln vuln.c -fno-stack-protector
`

crashed it with
`ragg2 -P 1024 | rax2 -s - | ./vuln`

**Comment by radare** [comment]
Share the bins instead of the src.

**Comment by iddoeldor91** [comment]
[vuln.zip](https://github.com/radare/radare2/files/1468362/vuln.zip)

Done

Workaround  (attached screenshot, thanks to @ITAYC0HEN)

![image](https://user-images.githubusercontent.com/16100975/32747306-0a0a8aca-c8c1-11e7-80ac-3793f2c1c670.png)

**Comment by radare** [comment]
you are doing wrong. -d and -e dbg.profile  doesnt combine like this. first of all, args passed after -d are suposed to be the program name and arguments to the program. not r2.

the -e dbg.profile... its also wrong. you must use -r or -R. see man radare2..

can you show the register state that is gdb spitting out?

**Comment by Maijin** [comment]
ping 1

**Comment by radare** [comment]
this is the content of the register arena extracted with rabin2 from the core, i dont see any 0x41 in there, so im not sure where GDB is taking that addresss from :?

00100000050000000010000001000000001003000090fdf70000000000100000002002000500000000100000010000000020030000b0fff70000000000100000001000000600000000100000010000000030030000c0fff70000000000100000001000000400000000100000010000000040030000d0fff70000000000100000001000000600000000100000010000000050030000c0fdff0000000000200200

**Comment by radare** [comment]
cc @leberus

**Comment by radare** [comment]
if you do pxq@r:SP you'll see that 0x4141 thing you are looking for. what gdb shows is the backtrace. in r2 the dbt command doesnt show this 0x4141, i've tried this with all the bt algorithms. we have and nope. so im preparing a smartest backtracer to get this info from there.

I think this is the only issue that must be fixed in here. Right?

**Comment by ret2libc** [comment]
I think this works well now, please re-open if necessary.
This is the output, which seems to be what expected:
```
~/projects/radare2$ radare2 core 
Setting up coredump arch-bits to: x86-32
Setting up coredump: Registers have been set
Setting up coredump: 16 maps have been found and created
 -- *(ut64*)buffer ought to be illegal
[0x414b4141]> ar
oeax = 0xffffffff
eax = 0x00000004
ebx = 0x00000000
ecx = 0xffffffff
edx = 0xf7fab870
esi = 0xf7faa000
edi = 0xf7faa000
esp = 0xffffccb0
ebp = 0x4a414149
eip = 0x414b4141
eflags = 0x00010286
```

Thanks for opening this bug!
