### ISSUE TITLE
propeller, xtr_dyldcache, LM32 and Z80 pseudo plugins are not linked with the rest

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#8843]
```
   usr/lib64/radare2/2.1.0-git/asm_propeller.so
   usr/lib64/radare2/2.1.0-git/bin_xtr_dyldcache.so
   usr/lib64/radare2/2.1.0-git/asm_LM32.so
   usr/lib64/radare2/2.1.0-git/parse_z80_pseudo.so
```
those are not linked with the rest objects inside libr_asm, libr_bin and libr_parse.

**Comment by radare** [comment]
Why? Fix the mk if they are wrong

**Comment by XVilka** [comment]
Now only `usr/lib64/radare2/2.1.0-git/bin_xtr_dyldcache.so` is not Linkedin

**Comment by xarkes** [comment]
Keep in mind I removed propeller from the Windows meson build, you might want to add it again?

**Comment by radare** [comment]
Can you tell me what is linkedin in r2land exactly?

**Comment by XVilka** [comment]
not linked in libr_bin.so

**Comment by ret2libc** [comment]
@XVilka please check this again and close if not relevant anymore.

**Comment by ret2libc** [comment]
Ok, I think those are now linked because I see them in the sources used by meson.
