### ISSUE TITLE
Background commands listing issue

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#8902]
the &= command waits until all commands are finished, doing ^C finishes all the threads

**Comment by ret2libc** [comment]
it seems to me that the entire shell breaks until a task has finished :/ Either I'm not understanding how this works or this "tasks" are not doing what they are supposed to do. What's the point in running something in a task if you can't do anything until it finishes?

**Comment by thestr4ng3r** [comment]
It depends on what you are running in the task. What command did you try?

**Comment by ret2libc** [comment]
> It depends on what you are running in the task. What command did you try?

pd 1000

**Comment by thestr4ng3r** [comment]
pd probably never does an explicit yield or enter sleep mode, so it's expected to block. Try something like `& .:1337` (with libuv preferred)

**Comment by trufae** [comment]
Closing as its another task bug
