### ISSUE TITLE
Add a function that given a string and a position return x, y

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#8903]
This will be useful to implement in graph a / command to search for a substring and scroll directly to there. this can be even used like a graph-hud, scrolling while typing

**Comment by ret2libc** [comment]
I think this was kinda implemented, right @trufae ? We worked recently on a PR to add this kind of thing to graph and directly scroll to it. I'm closing this, but feel free to re-open it if you feel otherwise.

**Comment by trufae** [comment]
Yep its done
