### ISSUE TITLE
Do not set entry point when the information is invalid

### ISSUE THREAD

**Issue by ishitatsuyuki** [radareorg/radare2#8960]
For example, if the entrypoint is intentionally set to 0x0, r2 will fallback to the beginning of .text section.

We should print an error and do not set entrypoint in such cases.

Also, it doesn't seem to care about static/dynamic. Static binary entrypoints are absolute address, while dynamic linked executables has relative entrypoint.

**Comment by radare** [comment]
Any screenshot, binary, example to see the problem and reproduce it?

**Comment by ishitatsuyuki** [comment]
This is a CTF binary with the entrypoint zeroed out:
http://file.ctf2.cpaw.site/Exec_me_revenge/exec_me_revenge_4ba9b20108e56b8d77d8a2dd091c55c6

r2 determines the entrypoint as the beginning of executable code, but actually it directly segfaults at EIP 0x0.

**Comment by Maijin** [comment]
![image](https://user-images.githubusercontent.com/1408600/33655127-88bad22c-da72-11e7-9829-02b070cb2571.png)


Are you sure this is not part of the CTF (cf the str.XXX)

**Comment by ishitatsuyuki** [comment]
That's glibc, not entrypoint.

**Comment by Maijin** [comment]
Well that's what you provided

**Comment by Maijin** [comment]
Does it even executes properly when launched ?

**Comment by ishitatsuyuki** [comment]
* this is a static linked binary
* the entrypoint value is zeroed out and needs to be restored (this is what the question is asking for)
* the beginning of code section is not actually executed

**Comment by Maijin** [comment]
I think the current behavior is ok, but it should print a warning for this

**Comment by Maijin** [comment]
a bprintf

**Comment by karliss** [comment]
@ishitatsuyuki  Stale bot was supposed to set "stale" label instaed of "wontfix".
