### ISSUE TITLE
[gdb, mips]: issue in profile register mapping (again)

### ISSUE THREAD

**Issue by fid0did0** [radareorg/radare2#8992]
I see again a problem in the profile mapping when I run r2 with gdb (from openocd):
```
r2 -a mips -D gdb gdb://localhost:3333
```
This the info about the r2 release:
```
r2 -v
radare2 2.2.0-git 16732 @ linux-x86-32 git.2.1.0-93-g2f28eb4
commit: 2f28eb43c9eef2fc61174897489849b69a9616b5 build: 2017-12-09__14:03:01
r2 -V
2.1.0-93-g2f28eb4  r2
2.1.0-93-g2f28eb4  r_anal
2.1.0-93-g2f28eb4  r_lib
2.1.0-93-g2f28eb4  r_egg
2.1.0-93-g2f28eb4  r_asm
2.1.0-93-g2f28eb4  r_bin
2.1.0-93-g2f28eb4  r_cons
2.1.0-93-g2f28eb4  r_flag
2.1.0-93-g2f28eb4  r_core
2.1.0-93-g2f28eb4  r_crypto
2.1.0-93-g2f28eb4  r_bp
2.1.0-93-g2f28eb4  r_debug
2.1.0-93-g2f28eb4  r_hash
2.1.0-93-g2f28eb4  r_fs
2.1.0-93-g2f28eb4  r_io
2.1.0-93-g2f28eb4  r_magic
2.1.0-93-g2f28eb4  r_parse
2.1.0-93-g2f28eb4  r_reg
2.1.0-93-g2f28eb4  r_sign
2.1.0-93-g2f28eb4  r_search
2.1.0-93-g2f28eb4  r_syscall
2.1.0-93-g2f28eb4  r_util
```

This what I see in r2 (debugging panel)
```
[0x0000000d 285 gdb://localhost:3333]> ?0;f tmp;s.. @ pc
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x806a0308  c601 9843 0030 0000 0000 6180 7449 6080  ...C.0....a.tI`.
0x806a0318  f8fc 6080 f0fc 6080 ec79 6080 0000 0010  ..`...`..y`.....
0x806a0328  0000 6180 c0a8 7bfe 0c4a 6080 ffff ff00  ..a...{..J`.....
0x806a0338  e449 6080 4203 6a80 0000 6180 c0a8 7bfe  .I`.B.j...a...{.
  r0 0x00000000       r1 0x00008000       r2 0x00000060       r3 0x00000010
  r4 0x80612500       r5 0x00000000       r6 0x0000002c       r7 0x0000007e
  r8 0x80650000       r9 0x80650000      r10 0x00000064      r11 0x806a0008
 r12 0x00000000      r13 0x0000001c      r14 0xffffffff      r15 0x80610000
 r16 0x80610000      r17 0xfe7ba8c0      r18 0x840084ae      r19 0x10000000
 r20 0x439801c6      r21 0x00003000      r22 0xe1044ce4      r23 0xd1825282
 r24 0x00000000      r25 0x00000000      r26 0x80010482      r27 0x00000002
 r28 0x80613d20      r29 0x806a0308      r30 0xa0120600      r31 0x80605eb8
  lo 0x00000004       hi 0x00000000       pc 0x0000000d       f0 0x038ce811
  f1 0xd0008054       f2 0x80602ffc       f3 0x00000000       f4 0x00000000
  f5 0x00000000       f6 0x00000000       f7 0x00000000       f8 0x00000000
  f9 0x00000000      f10 0x00000000      f11 0x00000000      f12 0x00000000
 f13 0x00000000      f14 0x00000000      f15 0x00000000      f16 0x00000000
 f17 0x00000000      f18 0x00000000      f19 0x00000000      f20 0x00000000
 f21 0x00000000      f22 0x00000000      f23 0x00000000      f24 0x00000000
 f25 0x00000000      f26 0x00000000      f27 0x00000000      f28 0x00000000
 f29 0x00000000      f30 0x00000000      f31 0x00000000
```

This is what gdb (openocd) report:
```
===== mips32 registers
(0) r0 (/32): 0x00000000  (1) r1 (/32): 0x00008000
(2) r2 (/32): 0x00000060  (3) r3 (/32): 0x00000010
(4) r4 (/32): 0x80612500  (5) r5 (/32): 0x00000000
(6) r6 (/32): 0x0000002C  (7) r7 (/32): 0x0000007E
(8) r8 (/32): 0x80650000  (9) r9 (/32): 0x80650000
(10) r10 (/32): 0x00000064 (11) r11 (/32): 0x806A0008
(12) r12 (/32): 0x00000000 (13) r13 (/32): 0x0000001C
(14) r14 (/32): 0xFFFFFFFF   (15) r15 (/32): 0x80610000
(16) r16 (/32): 0x80610000 (17) r17 (/32): 0xFE7BA8C0
(18) r18 (/32): 0x840084AE (19) r19 (/32): 0x10000000
(20) r20 (/32): 0x439801C6 (21) r21 (/32): 0x00003000
(22) r22 (/32): 0xE1044CE4 (23) r23 (/32): 0xD1825282
(24) r24 (/32): 0x00000000 (25) r25 (/32): 0x00000000
(26) r26 (/32): 0x80010482 (27) r27 (/32): 0x00000002
(28) r28 (/32): 0x80613D20 (29) r29 (/32): 0x806A0308
(30) r30 (/32): 0xA0120600 (31) r31 (/32): 0x80605EB8
(32) status (/32): 0x00000004 (33) lo (/32): 0x00000000
(34) hi (/32): 0x0000000D (35) badvaddr (/32): 0x038CE811
(36) cause (/32): 0xD0008054 (37) pc (/32): 0x80602FFC
(38) f0 (/32): 0x00000000 (39) f1 (/32): 0x00000000
(40) f2 (/32): 0x00000000 (41) f3 (/32): 0x00000000
(42) f4 (/32): 0x00000000 (43) f5 (/32): 0x00000000
(44) f6 (/32): 0x00000000 (45) f7 (/32): 0x00000000
(46) f8 (/32): 0x00000000 (47) f9 (/32): 0x00000000
(48) f10 (/32): 0x00000000 (49) f11 (/32): 0x00000000
(50) f12 (/32): 0x00000000 (51) f13 (/32): 0x00000000
(52) f14 (/32): 0x00000000 (53) f15 (/32): 0x00000000
(54) f16 (/32): 0x00000000 (55) f17 (/32): 0x00000000
(56) f18 (/32): 0x00000000 (57) f19 (/32): 0x00000000
(58) f20 (/32): 0x00000000 (59) f21 (/32): 0x00000000
(60) f22 (/32): 0x00000000 (61) f23 (/32): 0x00000000
(62) f24 (/32): 0x00000000 (63) f25 (/32): 0x00000000
(64) f26 (/32): 0x00000000 (65) f27 (/32): 0x00000000
(66) f28 (/32): 0x00000000 (67) f29 (/32): 0x00000000
(68) f30 (/32): 0x00000000 (69) f31 (/32): 0x00000000
(70) fcsr (/32): 0x00000000 (71) fir (/32): 0x00000000
```

Clearly there are some error in the mapping:
```
r2                  gdb
r29 0x806a0308      (29) r29 (/32): 0x806A0308
r30 0xa0120600      (30) r30 (/32): 0xA0120600
r31 0x80605eb8      (31) r31 (/32): 0x80605EB8
                    (32) status (/32): 0x00000004
lo 0x00000004       (33) lo (/32): 0x00000000
hi 0x00000000       (34) hi (/32): 0x0000000D
                    (35) badvaddr (/32): 0x038CE811
                    (36) cause (/32): 0xD0008054
pc 0x0000000d       (37) pc (/32): 0x80602FFC
f0 0x038ce811       (38) f0 (/32): 0x00000000
f1 0xd0008054       (39) f1 (/32): 0x00000000
f2 0x80602ffc       (40) f2 (/32): 0x00000000
f3 0x00000000       (40) f3 (/32): 0x00000000
```
It seems like if the status, badvaddr, cause reg are removed from the mapping.

After the PR #8863 the register mapping was OK but the SP was not mapped.
Now (fixed after #8958) the SP is properly mapped: I can see the stack frame properly addressed in the debug panel.
But the mapping is not correct and the PC point to the wrong position.

**Comment by radare** [comment]
Stop doing -D gdb gdb://

Just do -d gdb://

Its the same and you save 8 chars

**Comment by fid0did0** [comment]
Bye the way using the -d switch:
```
r2 -a mips -d localhost:3333
Could not execvp: No such file or directory
[w] Cannot open 'dbg://localhost:3333' for writing.
```

```
r2 -v
radare2 2.2.0-git 16772 @ linux-x86-32 git.2.1.0-133-ge0deacc
commit: e0deacc91660e76df75fa116a9f09bf88b34842f build: 2017-12-16__12:54:24
```
```
r2 -V
2.1.0-133-ge0deacc  r2
2.1.0-133-ge0deacc  r_anal
2.1.0-133-ge0deacc  r_lib
2.1.0-133-ge0deacc  r_egg
2.1.0-133-ge0deacc  r_asm
2.1.0-133-ge0deacc  r_bin
2.1.0-133-ge0deacc  r_cons
2.1.0-133-ge0deacc  r_flag
2.1.0-133-ge0deacc  r_core
2.1.0-133-ge0deacc  r_crypto
2.1.0-133-ge0deacc  r_bp
2.1.0-133-ge0deacc  r_debug
2.1.0-133-ge0deacc  r_hash
2.1.0-133-ge0deacc  r_fs
2.1.0-133-ge0deacc  r_io
2.1.0-133-ge0deacc  r_magic
2.1.0-133-ge0deacc  r_parse
2.1.0-133-ge0deacc  r_reg
2.1.0-133-ge0deacc  r_sign
2.1.0-133-ge0deacc  r_search
2.1.0-133-ge0deacc  r_syscall
2.1.0-133-ge0deacc  r_util
```

**Comment by fid0did0** [comment]
using the cmd r2 -a mips -d gdb://localhost:3333, work properly. 
The profiler bug is always there.

```
r2 -a mips -d gdb://localhost:3333
= attach 0 0
 -- The unix-like reverse engineering framework.
[0x0000000d]> q
```

**Comment by XVilka** [comment]
@SrimantaBarua can you please check this issue if you have time?

**Comment by radare** [comment]
anyone still alive?

**Comment by radare** [comment]
tired of waiting for feedback

**Comment by vsbogd** [comment]
I see similar issue when attaching to `qemu` running i386 DOS image using `r2 -a x86 -b 16 -e asm.os=DOS  -d gdb://127.0.0.1:1234`. Tried latest version from master:
```
$ r2 -v
radare2 5.8.1 29677 @ linux-x86-64 git.5.8.0-74-g4841de240c
commit: 4841de240cbb64ce8279c4c10ad6fc6ffebf04df build: 2023-01-07__13:43:11
```

`=!monitor info registers` returns correct register values:
```
[fffff000:ffff]> =!monitor info registers
EAX=00000009 EBX=ee000038 ECX=03fd0000 EDX=000003da
ESI=000000be EDI=00004aaa EBP=0009ffc4 ESP=0000ffc4
EIP=0000908b EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =3245 00032450 0000ffff 00009300
CS =0b34 0000b340 0000ffff 00009b00
SS =3245 00032450 0000ffff 00009300
DS =3245 00032450 0000ffff 00009300
FS =0b24 0000b240 0000ffff 00009300
GS =04ba 00004ba0 0000ffff 00009300
LDT=0000 00000000 00000000 00008200
TR =0008 00000580 00067fff 00808900
GDT=     00002928 00000017
IDT=     00000000 0000ffff
CR0=00000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
EFER=0000000000000000
FCW=1332 FSW=0020 [ST=0] FTW=00 MXCSR=00001f80
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=0000000000000000 0000 FPR3=0000000000000000 0000
FPR4=0000000000000000 0000 FPR5=0000000000000000 0000
FPR6=edc39d6000000000 4008 FPR7=9700000000000000 4007
XMM00=0000000000000000 0000000000000000 XMM01=0000000000000000 0000000000000000
XMM02=0000000000000000 0000000000000000 XMM03=0000000000000000 0000000000000000
XMM04=0000000000000000 0000000000000000 XMM05=0000000000000000 0000000000000000
XMM06=0000000000000000 0000000000000000 XMM07=0000000000000000 0000000000000000
```
while `dr` returns something strange:
```
[fffff000:ffff]> dr
ip = 0x00003245
ax = 0x000000be
bx = 0x00000009
cx = 0x00000000
dx = 0x000003da
sp = 0x000004ba
bp = 0x0000ffc4
si = 0x00000038
di = 0x0000ffc4
flags = 0x00000b24
```

Looks like #19878 also caused by the same issue.

**Comment by vsbogd** [comment]
After debugging, found that GDB client calculates register offset in bits instead of bytes at https://github.com/radareorg/radare2/blob/53e908d8021aa4cd2d597d08a2298f4db562bd1c/shlr/gdb/src/gdbclient/xml.c#L255

May be quickfixed by replacing this line by:
```c
regoff += tmpreg->size / 8;
```
not sure if the quickfix is enough to fix MIPS architecture.

x86 still doesn't work after this fix because when profile is received from GDB server:
- xmm registers are not mapped into proper register types;
- A0 register is not mapped onto proper register.

Overall this issue is looks like a broken `gdbclient/xml.c`.

**Comment by trufae** [comment]
Yes that seems like a good fix to me. Can you send a pr? Will be good to have gdb tests in the ci but its really anoying to test it unless we consider adding extra logic to r2r to support external processes tied to a test so we can properly kill the qemu in case it fails, and also allocate random and unused tcp ports for each test etc..

**Comment by trufae** [comment]
Xmm registers are now named vec128

**Comment by trufae** [comment]
But maybe we should rename them to v128

**Comment by trufae** [comment]
Thanks for tracking down all those regressions!

**Comment by vsbogd** [comment]
> Can you send a pr?

I have removed part of my original comment (sorry if it is not visible from email thread) because I have found my original guess (the main issue is an incorrect register position) is wrong. I am not too familiar with radare2 codebase yet and from what I see the position works correctly for x86 case.

So in my case the root cause are three errors I described in https://github.com/radareorg/radare2/issues/8992#issuecomment-1374656888. I have some quickfix for them in my local branch and I will try to convert it into PR. I just need more time to figure out how to fix `xmm` and `r_anal_set_reg_profile` issues properly.

> Will be good to have gdb tests in the ci

Yes, I will think about it but at the moment it looks like more complex task to me, so may be I will look at it separately.

> Xmm registers are now named vec128

Thanks, yes, the proper fix will be setting correct type for xmm.

> But maybe we should rename them to v128

Yes I can add it as separate commit.

**Comment by trufae** [comment]
ping

**Comment by vsbogd** [comment]
I have raised PR #21258 with obvious fixes for x86 platform. Unfortunately it doesn't fix the whole situation with x86. Last issue is that after register profile is set by GDB client it is being overridden by the `r_anal_use` function.

For instance the patch below fixes this behaviour, but I believe it breaks something else:
```
diff --git a/libr/anal/anal.c b/libr/anal/anal.c
index 20b49140bf..d698402ef4 100644
--- a/libr/anal/anal.c
+++ b/libr/anal/anal.c
@@ -234,6 +234,9 @@ R_API bool r_anal_use(RAnal *anal, const char *name) {
        r_return_val_if_fail (anal, false);
        RListIter *it;
        RAnalPlugin *h;
+       if (anal->uses) {
+           return true;
+       }
        // r_anal plugins
        r_list_foreach (anal->plugins, it, h) {
                if (!h->name || strcmp (h->name, name)) {
```

**Comment by trufae** [comment]
I would like to finish moving all the anal plugins into arch asap so we can stop having those problems. Can you make a pr with that patch and we can see what it breaks and i can take a look at it too

**Comment by vsbogd** [comment]
Thanks @trufae, I just have raised PR #21260.

**Comment by vsbogd** [comment]
I have took a look at the MIPS issue using:
- `qemu-system-mips  -s -S` to run QEMU;
- `radare2 -a mips -b 32 -D gdb gdb://127.0.0.1:1234` to run radare2.

I see the following things:
1. GDB client sends `xmlRegisters=i386` even when MIPS is target architecture;
2. QEMU doesn't send registers profile for MIPS even after I manually removed `=i386` from `xmlRegisters` query;
3. `xml.c` and default MIPS registers profile has the same issue with `A0=` register absent.

After fixing (3) I can connect to remote QEMU without error message but in my case radare2 finally applies x86 profile, I am not sure why:
<details><summary>dr output:</summary><p><pre>
[0x00000000]> dr
eax = 0x00000000
ecx = 0x00000000
edx = 0x00000000
ebx = 0x00000000
esp = 0x00000000
ebp = 0x00000000
esi = 0x00000000
edi = 0x00000000
eip = 0x00000000
eflags = 0x00000000
fctrl = 0x08840040
fstat = 0x0070eabf
ftag = 0x00000000
fiseg = 0x00000000
fioff = 0x00000000
foseg = 0x00000000
fooff = 0x00000000
fop = 0x00000000
mxcsr = 0x00000000
</pre></p></details>
<details><summary>arp output:</summary><p><pre>
[0x00000000]> arp
=PC	eip
=SP	esp
=BP	ebp
=A0	eax
=A1	ebx
=A2	ecx
=A3	edx
=SN	oeax
gpr	eax	.32	0	0
gpr	ecx	.32	4	0
gpr	edx	.32	8	0
gpr	ebx	.32	12	0
gpr	esp	.32	16	0
gpr	ebp	.32	20	0
gpr	esi	.32	24	0
gpr	edi	.32	28	0
gpr	eip	.32	32	0
gpr	eflags	.32	36	0
seg	cs	.32	40	0
seg	ss	.32	44	0
seg	ds	.32	48	0
seg	es	.32	52	0
seg	fs	.32	56	0
seg	gs	.32	60	0
fpu	st0	.80	64	0
fpu	st1	.80	74	0
fpu	st2	.80	84	0
fpu	st3	.80	94	0
fpu	st4	.80	104	0
fpu	st5	.80	114	0
fpu	st6	.80	124	0
fpu	st7	.80	134	0
gpr	fctrl	.32	144	0
gpr	fstat	.32	148	0
gpr	ftag	.32	152	0
gpr	fiseg	.32	156	0
gpr	fioff	.32	160	0
gpr	foseg	.32	164	0
gpr	fooff	.32	168	0
gpr	fop	.32	172	0
fpu	xmm0	.128	176	0
fpu	xmm1	.128	192	0
fpu	xmm2	.128	208	0
fpu	xmm3	.128	224	0
fpu	xmm4	.128	240	0
fpu	xmm5	.128	256	0
fpu	xmm6	.128	272	0
fpu	xmm7	.128	288	0
gpr	mxcsr	.32	304	0
</pre></p></details>
<details><summary>=!monitor info registers output:</summary><p><pre>
[0x00000000]> =!monitor info registers
pc=0xbfea7000 HI=0x00000000 LO=0x00000000 ds 10000090 00000000 0
GPR00: r0 00000000 at 00000000 v0 00000000 v1 00000000
GPR04: a0 00000000 a1 00000000 a2 00000000 a3 00000000
GPR08: t0 00000000 t1 00000000 t2 00000000 t3 00000000
GPR12: t4 00000000 t5 00000000 t6 00000000 t7 00000000
GPR16: s0 00000000 s1 00000000 s2 00000000 s3 00000000
GPR20: s4 00000000 s5 00000000 s6 00000000 s7 00000000
GPR24: t8 00000000 t9 00000000 k0 00000000 k1 00000000
GPR28: gp 00000000 sp 00000000 s8 00000000 ra 00000000
CP0 Status  0x00400006 Cause   0x40008408 EPC    0xc0000000
    Config0 0x80008482 Config1 0x9e190c8f LLAddr 0x0000000000000000
    Config2 0x80000000 Config3 0x00000000
    Config4 0x00000000 Config5 0x00000000
</pre></p></details>

**Comment by vsbogd** [comment]
> QEMU doesn't send registers profile for MIPS even after I manually removed =i386 from xmlRegisters query;

I didn't check whether GDB client asks for the register profile in this case. So may be client doesn't ask about this profile or server doesn't support it.
