### ISSUE TITLE
Multiple inconsistencies with loadaddr and mapaddr

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#9068]
From @xarkes in Cutter repo:

> There are multiple inconsistencies with loadaddr and mapaddr right now in radare2. Just git grep r_core_file_open and you will undestand.

https://github.com/radareorg/cutter/issues/232#issuecomment-353854238

**Comment by xarkes** [comment]
Yes, also I don't know/understand the difference with r2 -m and r2 -B

**Comment by radare** [comment]
The address where the bin is loaded from. This is useful when the header is not in offset 0 like in fatmachos

**Comment by xarkes** [comment]
Then there are no inconsistencies and we can close this?

**Comment by radare** [comment]
the inconsistency is in the RBin API, i have several ideas to improve that and im trying to push small changes over time.

**Comment by radare** [comment]
imho we can close this issue, because its part of the plans for rbin already

**Comment by ret2libc** [comment]
This can be closed probably. Please re-open if you feel otherwise, but I don't see this providing any value apart from the usual never-ending refactoring of all the API.
