### ISSUE TITLE
Ps command does not save source file information, causing other commands to fail when project file is used

### ISSUE THREAD

**Issue by OhioDuckFarmer** [radareorg/radare2#9149]
`
### Work environment

Q: OS/arch/Bits
A: LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
   Distributor ID:	Ubuntu
   Description:	Ubuntu 16.04.3 LTS
   Release:	16.04
   Codename:	xenial

Q: File format of the file you reverse
A: RAW binary of a memory image

Q: File format of the file you reverse
A: MIPS  

Q: Architecture/bits of the file
A: 32

Q: r2 -v full output
A: radare2 2.2.0-git 16809 @ linux-x86-64 git.2.1.0-197-gd6e0b60
   commit: d6e0b606c79e777f7f28e015c4e85e68282df7f8 build: 2018-01-07__18:32:40 

Q: r2 -V full output in a pastebin document 
A: https://gist.github.com/OhioDuckFarmer/dc67e2da7c27936f19b9c5bcf26f5cd2

### Expected behavior

Source file information to be saved to the project file, such as:

    [0x00000000]> i

    blksz    0x0
    block    0x100
    fd       3
    file     test.img
    format   any
    iorw     false
    mode     -r-x
    size     0x17ffd8
    humansz  1.5M
    
    [0x00000000]> e~file
    
    asm.dwarf.file = true
    dbg.profile = 
    file.desc = 
    file.info = true
    file.lastpath = ~/test.img
    file.loadalign = 0x00000400
    file.location = 
    file.md5 = 164b0b1ebedd63761df31189088040a6
    file.nowarn = true
    file.offset = 
    file.openmany = 1
    file.path = ~/test.img
    file.sha1 = 33f0eeed0123ba8f4ee507ed80db737c9bae26dd
    file.type = 
    http.logfile = 
    prj.files = false
    scr.promptfile = false

### Actual behavior

Source file information is missing from the project file:

    $ r2 -p test
    
    [0x00000000]> i
    No file selected
    
    [0x00000000]> e~file
    
    asm.dwarf.file = true
    dbg.profile = 
    file.desc = 
    file.info = true
    file.lastpath = 
    file.loadalign = 0x00000400
    file.location = 
    file.md5 = 164b0b1ebedd63761df31189088040a6
    file.nowarn = true
    file.offset = 4194304
    file.openmany = 1
    file.path = 
    file.sha1 = 33f0eeed0123ba8f4ee507ed80db737c9bae26dd
    file.type = 
    http.logfile = 
    prj.files = false
    scr.promptfile = false

Lacking any information on the source file will cause commands such as izz to
fail:

    [0x00000000]> izz
    Core file not open

### Steps to reproduce the behavior 
01) Open any file inside of r2
02) Save project file with Ps commands
03) Close r2 (you can select save  project if you want)
04) Open r2 using the project file: r2 -p <prj_file>
    or try: r2 -p <prj_file> <image>

### Additional Logs, screenshots, compiled binaries, source-code,  configuration dump, ...

None
`

**Comment by Maijin** [comment]
Can you use Markdown code syntax when pasting output/code so it's readable ?

![image](https://user-images.githubusercontent.com/1408600/34665976-81390208-f462-11e7-8151-4cf226cdb2cb.png)

**Comment by OhioDuckFarmer** [comment]
Fixed. Sorry about that
