### ISSUE TITLE
Cannot find a main function for simple C++ win programm

### ISSUE THREAD

**Issue by dukebarman** [radareorg/radare2#9202]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0-git 17048 @ linux-x86-64 git.2.2.0-237-g876c60f
| r2 -V full output in a pastebin document (mandatory) | https://pastebin.com/Bw1wr69v

### Expected behavior

Find main function

### Actual behavior

Radare2 doesn't find a main function

### Steps to reproduce the behavior 
```
$ r2 example.exe 
[0x004110be]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[0x004110be]> afl~main
[0x004110be]> zfs ./vc32_14.sig 
Found flirt.__scrt_common_main__YAHXZ
Found flirt.__scrt_common_main_seh__YAHXZ
...
[0x004110be]> afl~main
0x00416790    1 15           flirt.__scrt_common_main__YAHXZ
0x004167b0   21 525  -> 421  flirt.__scrt_common_main_seh__YAHXZ
...
[0x004110be]>
```

### Additional Logs, screenshots, compiled binaries, source-code,  configuration dump, ...
I take `vc32_14.sig` from IDA 7 standard folder

**Comment by wargio** [comment]
the `example.exe` binary?

**Comment by dukebarman** [comment]
You can compile default console project in Visual Studio 2017 C++.

**Comment by sivaramaaa** [comment]
@dukebarman u can't expect everyone to have Visual Studio 2017 C++  installed  !!!
plss provide the binary if it's possible , or u could atleast  point out to some bins available in r2r repo !!

But i have tested with a few exe found /radare2-regressions/bins/pe , and it's working fine see below : 
```
$ r2 hellocxx-mingw32.exe
[0x004013ee]> afl~main
[0x004013ee]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x004013ee]> afl~main
0x004013ee    1 85           main
```
```
$ r2 crackme0x00.exe
[0x00401260]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x00401260]> afl~main
0x00401310    4 141          main
0x00401470    3 29   -> 27   sym.___main
0x00402d00    1 6            sym.___getmainargs
[0x00401260]>
```

**Comment by dukebarman** [comment]
Here two files:

- example_with_hello.exe (with print "Hello)
- example_empty_func.exe (with only `return 0`)

[example.zip](https://github.com/radare/radare2/files/1635151/example.zip)

I've found another bug. After this commands on empty function radare2 was closed:
```
$ r2 example_empty_func.exe
[0x004110be]> aaa
[0x004110be]> afl~main
[0x004110be]> zfs ./vc32_14.sig 
Found flirt.__scrt_common_main__YAHXZ
Found flirt.__scrt_common_main_seh__YAHXZ
...
[0x004110be]> afl~main
$
```

**Comment by radare** [comment]
Thats known issue. Those are binaries generated with msvc in debug mode, right?

The analysis required to find the main and other stuff is not worth the effort... the whole program is generated, and linked with jumps to make it easy to be modified in memory for the debugger to recompile parts of it on the fly.

**Comment by dukebarman** [comment]
Yep, this binaries were compiled in debug mode

**Comment by radare** [comment]
not even signatures can help on this, not sure how much useful is to add support for those messed up binaries

**Comment by riverar** [comment]
This isn't a r2 bug.

**Short version**: new behavior in Visual Studio 2017/C++ compiler. Ensure this is set:
![image](https://user-images.githubusercontent.com/475132/35855290-9abaf146-0ae7-11e8-9277-8c12b8e6ac1e.png)

**Longer version**:
What you're seeing is [new fastlink behavior in the linker](https://blogs.msdn.microsoft.com/vcblog/2016/10/05/faster-c-build-cycle-in-vs-15-with-debugfastlink/), switched on by default for new C++ projects in Visual Studio 2017. The resulting PDB isn't useful for loading into r2 or sharing with friends. You can temporarily build a complete PDB using `Build > Build full program database for solution` or reconfigure the project using the setting above.
