### ISSUE TITLE
Select fatmach0 sub-bin by index, and handle asm.cpu too

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#931]
Some fatmach0 bins are ARMv6 and ARMv7 (for example) and both are identified by `asm.arch=arm` and `asm.bits=16`, we must be able to handle `asm.cpu` too, and in addition have a way to select sub-bin by index.

Btw, the list of subbins should be stored in sdb too.

**Comment by alvarofe** [comment]
I would move this into future milestone, that would require rewriting how fat is handled and is not that easy, it could be workarounded though but is not the solution can live with r2 -a arm -b 32 fatfile . We have made bad decisions and it would require more time to fix it properly. I will create a meta/hackmd trying to explain my thought on this to discuss and create a plan of action even useful for GSOC if someone wants to chip in.

**Comment by radare** [comment]
define future milestone please

**Comment by alvarofe** [comment]
i mean not for 1.3 just postpone it

**Comment by radare** [comment]
ping
