### ISSUE TITLE
radare2: ARM BL/BLX target off by 4 when address is larger than 0x80000000

### ISSUE THREAD

**Issue by StefanBruens** [radareorg/radare2#9321]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | openSUSE-TW x86 64 
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | arm/32
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 0 @ linux-x86-64 git.2.3.0 commit: HEAD build: 2018-01-30__19:27:13

### Actual behavior

```
$> rasm2 -o 0x556 -a arm -b 16 -d 0xfff7aeed
blx 0xb4
$> rasm2 -o 0x0x40000556 -a arm -b 16 -d 0xfff7aeed
blx 0x400000b4
$> rasm2 -o 0x0x80000556 -a arm -b 16 -d 0xfff7aeed
blx 0x800000b8
$> rasm2 -o 0x0xf0000556 -a arm -b 16 -d 0xfff7aeed
blx 0xf00000b8
```
Same can be seen in radare2

### Expected behaviour

Address should be n000_00b4 in all cases.

**Comment by radare** [comment]
-d expects hexpairs not a number,

And this bug is in capstone, not in r2. Can you report this to the capstone project instead? In addition, can you confirm the behaviour is good with the gnu plugin?

**Comment by StefanBruens** [comment]
Some more datapoints:
```
$> rasm2 -o 0xf0000556 -a arm -b 16 -d fff7aeed
blx 0xf00000b8
$> rasm2 -o 0xf0000556 -a arm.gnu -b 16 -d fff7aeed
blx 0xf00000b4
rasm2 -o 0x80000456 -a arm -b 16 -d 0xfff7aeed
blx 0x7fffffb4
```
So, gnu plugin is working, and the bug depends on the branch target, not the PC.

**Comment by Maijin** [comment]
Greetings,

arm.as (*arm* handmade assembler) is one of the 2 arm assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix arm.as in https://github.com/radare/radare2-regressions/tree/master/new/db/asm** You can do so with github web editor without even cloning the repo.

You can contribute to arm.as by completing the following files: 
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass.c
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass64.c

You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a arm.ks…
or in radare2 session
	e asm.assembler = arm.ks
```

**Comment by radare** [comment]
u r doing it wrong. hexpairs dont start with 0x

**Comment by StefanBruens** [comment]
rasm2 does not care ... output is identical

**Comment by StefanBruens** [comment]
@Maijin - will create a test case.
can you also add https://github.com/radare/radare2-regressions/blob/master/new/README.md to your template - the test case syntax is not really self documenting

**Comment by ret2libc** [comment]
```
:~/projects/radare2$ rasm2 -o 0x556 -a arm -b 16 -d 0xfff7aeed
blx 0xb4
:~/projects/radare2$ rasm2 -o 0x0x40000556 -a arm -b 16 -d 0xfff7aeed
blx 0x400000b4
:~/projects/radare2$ rasm2 -o 0x0x80000556 -a arm -b 16 -d 0xfff7aeed
blx 0x800000b4
:~/projects/radare2$ rasm2 -o 0x0xf0000556 -a arm -b 16 -d 0xfff7aeed
blx 0xf00000b4
```
This seems to work as expected now, I'm closing this.
