### ISSUE TITLE
Parsing -d program arguments issues

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#9417]
Notice that it works fine with lldb

<img width="543" alt="screen shot 2018-02-18 at 02 43 01" src="https://user-images.githubusercontent.com/917142/36347355-b8c2b274-1455-11e8-9afd-17e154ba2df1.png">
<img width="625" alt="screen shot 2018-02-18 at 02 43 31" src="https://user-images.githubusercontent.com/917142/36347356-b8e158dc-1455-11e8-9361-a141add11a15.png">

**Comment by giuscri** [comment]
Future fixers: here
```
if (execvp (argv[0], argv) == -1) {
        eprintf ("Could not execvp: %s\n", strerror (errno));
        exit (MAGIC_EXIT);
}
```
argv[0] is whole `lldb-server g :9999 -- AAAAAAAAAAA`. Don't know if that's _the_ reason behind the bug but it may be a good start.

**Comment by giuscri** [comment]
@radare could you explain more this bug? what should happen?

**Comment by radare** [comment]
as you can see, r2 cant debug this `lldb-srver g... ` oneliner, take any other program as example and with "strange" arguments and see what happens

**Comment by giuscri** [comment]
is this the same bug?
```
$ r2 -d "python3 --version"
Could not execvp: No such file or directory
[w] Cannot open 'dbg://python3\ --version' for writing.
```

**Comment by radare** [comment]
Yep

**Comment by ret2libc** [comment]
I think there's a problem here though. It seems like lldb assumes that everything is part of the program to be debugged. So

` lldb "/tmp/program with space" --version` is interpreted as program="/tmp/program with space" and all the rest as arguments to the program.

In r2 case, instead, we still allow r2 arguments after the `-d` flag. So if you do
`r2 -d "/tmp/program with space" --version` this is interpreted as program="/tmp/program with space" and --version is interpreted as a flag for r2 (in this case radare will just print its version and it won't execute the "program with space" with --version as argument.

I believe it makes sense to consider everything after the `-d` flag as part of the debuggee arguments.

**Comment by radare** [comment]
this is the only issue pending to release. we can move it for 2.5 and have more time to discuss and find a better solution and have more time for the next release or just wait some hours and get this into 2.4. 

what do you think?

**Comment by ret2libc** [comment]
Yes I think it was ok to wait next release for this.
What do you think about what I said before? I'd say it makes sense that whatever is after the `-d` flag, should be considered as program name + its arguments.

**Comment by ret2libc** [comment]
@radare pong see https://github.com/radare/radare2/issues/9417#issuecomment-370863652 though.

**Comment by radare** [comment]
sgtm

**Comment by ret2libc** [comment]
@radare isn't this fixed?

I think in radare2 4.4.0 you can do `r2 -d python3 --version` and it will debug python3 with the argument `--version` (so when executed, the process will just print `Python 3.7.6`).

**Comment by radare** [comment]
imho yes
