### ISSUE TITLE
Remove FCN_OLD in analysis code

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#9421]
To speed up the analysis and remove legacy code

**Comment by 08A** [comment]
I am working on this where can i find documentation on sdb

**Comment by radare** [comment]
In the sdb repository

**Comment by radare** [comment]
But we will probably end up removing sdb now that we have more hands and better data structures

**Comment by 08A** [comment]
@XVilka @radare Should this issue be closed?
