### ISSUE TITLE
sandboxing using seccomp

### ISSUE THREAD

**Issue by bernhl** [radareorg/radare2#9422]
Hey, I'd like to enhance the sandboxing on linux by implementing a seccomp filter (allowing just the few system calls required by radare2). Would you be fine with adding libseccomp as dependency (as it really eases writing filters)? If so, whats the preferred way to include the lib into the build chain? If no, are you open to a (potentially verbose) handcrafted BPF?

**Comment by radare** [comment]
we are not a big fan of adding dependencise or optional libraries at compile time, cant this be done in a plugin? r2pm -i seccomp and link the plugin against this?

there’s some doc on how to sandbox r2 on different OSs see doc/sandbox
