### ISSUE TITLE
radare2 armv7 playstore bugs

### ISSUE THREAD

**Issue by radare2-bein** [radareorg/radare2#9520]
!shell escapes crashes
pd nr not working

is visual mode supported?

using archos neon 45b , android 5.1 2016-02-01 , kernel 3.10.65

**Comment by radare** [comment]
Can you use termux instead?

**Comment by radare2-bein** [comment]
same thing, I guess. currently sarching for logfile ...

**Comment by radare2-bein** [comment]
so, correctly r2pipe crashes on shellescape, logfile is lost

**Comment by radare2-bein** [comment]
I will look more closely..

**Comment by radare** [comment]
r2pipe? what are you trying to do and which version of r2, device, etc are you using?
