### ISSUE TITLE
Reloading of project causes source data to be blank

### ISSUE THREAD

**Issue by OhioDuckFarmer** [radareorg/radare2#9574]
### Work environment

Q: OS/arch/Bits
A: LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
   Distributor ID:	Ubuntu
   Description:	Ubuntu 16.04.3 LTS
   Release:	16.04
   Codename:	xenial

Q: File format of the file you reverse
A: IHEX

Q: Architecture/bits of the file
A: 8051

Q: r2 -v full output
A: radare2 2.4.0-git 17478 @ linux-x86-64 git.2.2.0-656-g00668df
commit: 00668df334800762038a77ca666ef46d378650f8 build: 2018-03-03__12:05:34

Q: r2 -V full output
A: https://gist.github.com/OhioDuckFarmer/d1b4e2f46d4bc9f81c502072a6814c8b

### Expected behavior

When reloading a project via the Po command the files contents should be properly restored.

### Actual behavior

When reloading a project via the Po command the files contents is blank

### Steps to reproduce the behavior 
	$ r2 -a 8051 ihex://Vend_Ax.hex
	Cannot set bits 64 to '8051'
	Cannot set bits 64 to '8051'
	 -- Hold on, this should never happen!
	[0x00000000]> px
	- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
	0x00000000  020e 51ff ffff ffff ffff ffff ffff ffff  ..Q.............
	0x00000010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000030  ffff ff02 0e7b ffff ffff ffff ffff ffff  .....{..........
	0x00000040  ffff ff02 0900 ffff ffff ff02 07ed ffff  ................
	0x00000050  ffff ff02 0900 ffff ffff ffff ffff ffff  ................
	0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000080  90e6 78e0 5410 ffc4 540f 4450 f51d 13e4  ..x.T...T.DP....
	0x00000090  33f5 1f90 e6b9 e024 5eb4 0a00 4003 0203  3......$^...@...
	0x000000a0  d890 00af 75f0 03a4 c583 25f0 c583 7302  ....u.....%...s.
	0x000000b0  024d 0202 4d02 03d8 0203 d802 00cd 0203  .M..M...........
	0x000000c0  d802 0113 0201 3902 00ed 0201 0090 e600  ......9.........
	0x000000d0  e0ff c454 0f90 e740 f0e4 90e6 8af0 90e6  ...T...@........
	0x000000e0  8b04 f090 e6a0 e044 80f0 0203 d890 e67a  .......D.......z
	0x000000f0  e054 fef0 e490 e68a f090 e68b f002 03d8  .T..............
	[0x00000000]> Ps vend_ax
	vend_ax
	[0x00000000]> Po vend_ax
	[0x00000000]> Pl
	vend_ax
	[0x00000000]> px
	- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
	0x00000000  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000010  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000020  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000030  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000040  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000050  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000060  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000070  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000080  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x00000090  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x000000a0  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x000000b0  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x000000c0  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x000000d0  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x000000e0  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x000000f0  0000 0000 0000 0000 0000 0000 0000 0000  ................
	[0x00000000]> 

### Additional Logs, screenshots, source-code,  configuration dump, ...

[exmple.zip](https://github.com/radare/radare2/files/1778093/exmple.zip)

**Comment by giuscri** [comment]
reproduced.

I've changed`rc` of the project and `rc` is actually re-executed when you `Po`.

**Comment by OhioDuckFarmer** [comment]
Some follow up information:  Setting prj.simple=True will resolve the issue of the data changes to 0x0 when  Po is issued; however, the next time the user tries to use the project the data is not what it should be as now it is all 0xff:

	r2 -a 8051 ihex://Vend_Ax.hex
	Cannot set bits 64 to '8051'
	Cannot set bits 64 to '8051'
	 -- 3nl4r9e y0\/r r4d4r3
	[0x00000000]> px
	- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
	0x00000000  020e 51ff ffff ffff ffff ffff ffff ffff  ..Q.............
	0x00000010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000030  ffff ff02 0e7b ffff ffff ffff ffff ffff  .....{..........
	0x00000040  ffff ff02 0900 ffff ffff ff02 07ed ffff  ................
	0x00000050  ffff ff02 0900 ffff ffff ffff ffff ffff  ................
	0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000080  90e6 78e0 5410 ffc4 540f 4450 f51d 13e4  ..x.T...T.DP....
	0x00000090  33f5 1f90 e6b9 e024 5eb4 0a00 4003 0203  3......$^...@...
	0x000000a0  d890 00af 75f0 03a4 c583 25f0 c583 7302  ....u.....%...s.
	0x000000b0  024d 0202 4d02 03d8 0203 d802 00cd 0203  .M..M...........
	0x000000c0  d802 0113 0201 3902 00ed 0201 0090 e600  ......9.........
	0x000000d0  e0ff c454 0f90 e740 f0e4 90e6 8af0 90e6  ...T...@........
	0x000000e0  8b04 f090 e6a0 e044 80f0 0203 d890 e67a  .......D.......z
	0x000000f0  e054 fef0 e490 e68a f090 e68b f002 03d8  .T..............
	[0x00000000]> e prj.simple
	false
	[0x00000000]> e prj.simple=true
	[0x00000000]> e prj.simple
	true
	[0x00000000]> Ps vend_ax
	vend_ax
	[0x00000000]> Po
	[0x00000000]> px
	- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
	0x00000000  020e 51ff ffff ffff ffff ffff ffff ffff  ..Q.............
	0x00000010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000030  ffff ff02 0e7b ffff ffff ffff ffff ffff  .....{..........
	0x00000040  ffff ff02 0900 ffff ffff ff02 07ed ffff  ................
	0x00000050  ffff ff02 0900 ffff ffff ffff ffff ffff  ................
	0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000080  90e6 78e0 5410 ffc4 540f 4450 f51d 13e4  ..x.T...T.DP....
	0x00000090  33f5 1f90 e6b9 e024 5eb4 0a00 4003 0203  3......$^...@...
	0x000000a0  d890 00af 75f0 03a4 c583 25f0 c583 7302  ....u.....%...s.
	0x000000b0  024d 0202 4d02 03d8 0203 d802 00cd 0203  .M..M...........
	0x000000c0  d802 0113 0201 3902 00ed 0201 0090 e600  ......9.........
	0x000000d0  e0ff c454 0f90 e740 f0e4 90e6 8af0 90e6  ...T...@........
	0x000000e0  8b04 f090 e6a0 e044 80f0 0203 d890 e67a  .......D.......z
	0x000000f0  e054 fef0 e490 e68a f090 e68b f002 03d8  .T..............
	[0x00000000]> q
	Do you want to save the 'vend_ax' project? (Y/n)

	$ r2 -p vend_ax
	 -- ESIL ruined my life
	[0x00000000]> px
	- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
	0x00000000  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000030  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000040  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000050  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000080  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000090  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000a0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000b0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000c0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000d0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000e0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000f0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	[0x00000000]> q

	$ r2 -
	 -- Good morning, pal *<:-)
	[0x00000000]> Pl
	vend_ax
	[0x00000000]> Po vend_ax
	Close current session? (Y/n)
	[0x00000000]> px
	- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
	0x00000000  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000030  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000040  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000050  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000080  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x00000090  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000a0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000b0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000c0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000d0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000e0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	0x000000f0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
	[0x00000000]>

**Comment by radare** [comment]
And if you type ‘o’ which file is opened?

**Comment by OhioDuckFarmer** [comment]
Based upon the results shown below, the original file is not being re-opened.

    Just after saving project and exiting:
    
    [0x00000000]> Ps vend_ax
    vend_ax
    [0x00000000]> Po
    [0x00000000]> o
    3 - -rw- 0x00000100 malloc://256
    4 - -rw- 0x00000080 malloc://128
    5 - -rw- 0x00010000 malloc://65536
    6 * -r-x 0x00000ead ihex://Vend_Ax.hex

    Staring r2 with project (r2 -p vend_ax)
     
    [0x00000000]> o
     3 - -rw- 0x00000100 malloc://256
     4 - -rw- 0x00000080 malloc://128
     5 * -rw- 0x00010000 malloc://65536

**Comment by astuder** [comment]
Does the missing data reappear if delete the maps that overlap the file using om-?
