### ISSUE TITLE
Debugger: push testsuite forward

### ISSUE THREAD

**Issue by leberus** [radareorg/radare2#9683]
I'd like to push our debugger's tesuite forward, so we are notified whenever anything breaks down.
I though about going through <b>./t.archos/Linux-x86_64/dbg_*</b> and check their output
I saw that few of them are broken, or at least not returning the expected output, which might be because: a) either we have to tweak the expected output or b) fix the debugger behavior, all depending on what we should get.

Any suggestions/ideas?

cc @radare

**Comment by XVilka** [comment]
Do it. Travis-CI cannot test debugger, but afaik AppVeyor can and our CI (Jenkins)

**Comment by radare** [comment]
Go for it

**Comment by ret2libc** [comment]
Closing this as debug tests are now working. Of course we can add tests there, but no need to track anything here. Thanks!
