### ISSUE TITLE
likely/unlikely should not emulate intermediate instructions only cjmps

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#9768]
<img width="679" alt="screen shot 2018-03-26 at 14 16 12" src="https://user-images.githubusercontent.com/917142/37905792-50af5af8-3100-11e8-8df2-6ef5da289d26.png">
<img width="703" alt="screen shot 2018-03-26 at 14 16 17" src="https://user-images.githubusercontent.com/917142/37905793-50d01b58-3100-11e8-969e-b141c9e00cb1.png">

**Comment by XVilka** [comment]
Not sure what you mean though.

**Comment by ret2libc** [comment]
I'm not sure either. Related to ESIL I think it's a must to change how it's evaluated. It doesn't have any sense that emulation changes based on where you start printing the disassembly.

**Comment by ret2libc** [comment]
@radare I'd move this to next release if you are ok with it.

**Comment by radare** [comment]
That one is important but probably makes sense to fix it with time
