### ISSUE TITLE
\xFFFF... when reading glibc version hash

### ISSUE THREAD

**Issue by mrpalacios** [radareorg/radare2#9770]
Hello,

I cannot get r2 to properly read libc debug file and problem seems to come from the read of libc.so version, as `r_io_read_at`, with correct _vaddr_ and _offset_, is always returning \xFFFFFFFF... .

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 4.14.17-1kali1
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.1.0-git 16437 @ linux-x86-64 git.0.10.1-5941-g44f6f1f6a commit: 44f6f1f6aef04f41f690570c23e34943df32209a build: 2018-03-26__17:24:53

### Expected behavior
Load debug symbols from glibc debug

### Actual behavior
Version read from libc.so is always FFFFFFFF... so load fails.

`$ uname -a`
`Linux localhost.localdomain 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux`

`$ r2 -version`
`radare2 2.1.0-git 16437 @ linux-x86-64 git.0.10.1-5941-g44f6f1f6a
commit: 44f6f1f6aef04f41f690570c23e34943df32209a build: 2018-03-26__17:24:53`

`$ r2 -d /bin/ls`
`$ aa`
`$ dcu entry0`

`[0x561d195116d0]> dm`
`0x0000561d1950c000 # 0x0000561d1952b000 * usr   124K s -r-x /bin/ls /bin/ls ; map._bin_ls._r_x`
`0x0000561d1972b000 # 0x0000561d1972c000 - usr     4K s -r-- /bin/ls /bin/ls ; map._bin_ls._rw_`
`0x0000561d1972c000 # 0x0000561d1972d000 - usr     4K s -rw- /bin/ls /bin/ls ; section_end.GNU_RELRO`
`0x0000561d1972d000 # 0x0000561d1972e000 - usr     4K s -rw- unk0 unk0`
`0x0000561d1ad07000 # 0x0000561d1ad28000 - usr   132K s -rw- [heap] [heap]`
`0x00007fb62afa8000 # 0x00007fb62afc1000 - usr   100K s -r-x /lib/x86_64-linux-gnu/libpthread-2.27.so /lib/x86_64-linux-gnu/libpthread-2.27.so`
`0x00007fb62afc1000 # 0x00007fb62b1c0000 - usr   2.0M s ---- /lib/x86_64-linux-gnu/libpthread-2.27.so /lib/x86_64-linux-gnu/libpthread-2.27.so`
`0x00007fb62b1c0000 # 0x00007fb62b1c1000 - usr     4K s -r-- /lib/x86_64-linux-gnu/libpthread-2.27.so /lib/x86_64-linux-gnu/libpthread-2.27.so`
`0x00007fb62b1c1000 # 0x00007fb62b1c2000 - usr     4K s -rw- /lib/x86_64-linux-gnu/libpthread-2.27.so /lib/x86_64-linux-gnu/libpthread-2.27.so`
`0x00007fb62b1c2000 # 0x00007fb62b1c6000 - usr    16K s -rw- unk1 unk1`
`0x00007fb62b1c6000 # 0x00007fb62b1c9000 - usr    12K s -r-x /lib/x86_64-linux-gnu/libdl-2.27.so /lib/x86_64-linux-gnu/libdl-2.27.so`
`0x00007fb62b1c9000 # 0x00007fb62b3c8000 - usr   2.0M s ---- /lib/x86_64-linux-gnu/libdl-2.27.so /lib/x86_64-linux-gnu/libdl-2.27.so`
`0x00007fb62b3c8000 # 0x00007fb62b3c9000 - usr     4K s -r-- /lib/x86_64-linux-gnu/libdl-2.27.so /lib/x86_64-linux-gnu/libdl-2.27.so`
`0x00007fb62b3c9000 # 0x00007fb62b3ca000 - usr     4K s -rw- /lib/x86_64-linux-gnu/libdl-2.27.so /lib/x86_64-linux-gnu/libdl-2.27.so`
`0x00007fb62b3ca000 # 0x00007fb62b43a000 - usr   448K s -r-x /lib/x86_64-linux-gnu/libpcre.so.3.13.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.3`
`0x00007fb62b43a000 # 0x00007fb62b63a000 - usr     2M s ---- /lib/x86_64-linux-gnu/libpcre.so.3.13.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.3`
`0x00007fb62b63a000 # 0x00007fb62b63b000 - usr     4K s -r-- /lib/x86_64-linux-gnu/libpcre.so.3.13.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.3`
`0x00007fb62b63b000 # 0x00007fb62b63c000 - usr     4K s -rw- /lib/x86_64-linux-gnu/libpcre.so.3.13.3 /lib/x86_64-linux-gnu/libpcre.so.3.13.3`
`0x00007fb62b63c000 # 0x00007fb62b7ed000 - usr   1.7M s -r-x /lib/x86_64-linux-gnu/libc-2.27.so /lib/x86_64-linux-gnu/libc-2.27.so`
`0x00007fb62b7ed000 # 0x00007fb62b9ec000 - usr   2.0M s ---- /lib/x86_64-linux-gnu/libc-2.27.so /lib/x86_64-linux-gnu/libc-2.27.so`
`0x00007fb62b9ec000 # 0x00007fb62b9f0000 - usr    16K s -r-- /lib/x86_64-linux-gnu/libc-2.27.so /lib/x86_64-linux-gnu/libc-2.27.so`
`0x00007fb62b9f0000 # 0x00007fb62b9f2000 - usr     8K s -rw- /lib/x86_64-linux-gnu/libc-2.27.so /lib/x86_64-linux-gnu/libc-2.27.so`
`0x00007fb62b9f2000 # 0x00007fb62b9f6000 - usr    16K s -rw- unk2 unk2`
`0x00007fb62b9f6000 # 0x00007fb62ba1b000 - usr   148K s -r-x /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libselinux.so.1`
`0x00007fb62ba1b000 # 0x00007fb62bc1a000 - usr   2.0M s ---- /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libselinux.so.1`
`0x00007fb62bc1a000 # 0x00007fb62bc1b000 - usr     4K s -r-- /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libselinux.so.1`
`0x00007fb62bc1b000 # 0x00007fb62bc1c000 - usr     4K s -rw- /lib/x86_64-linux-gnu/libselinux.so.1 /lib/x86_64-linux-gnu/libselinux.so.1`
`0x00007fb62bc1c000 # 0x00007fb62bc1e000 - usr     8K s -rw- unk3 unk3`
`0x00007fb62bc1e000 # 0x00007fb62bc43000 - usr   148K s -r-x /lib/x86_64-linux-gnu/ld-2.27.so /lib/x86_64-linux-gnu/ld-2.27.so ; map._lib_x86_64_linux_gnu_ld_2.27.so._r_x`
`0x00007fb62be00000 # 0x00007fb62be04000 - usr    16K s -rw- unk4 unk4`
`0x00007fb62be42000 # 0x00007fb62be43000 - usr     4K s -r-- /lib/x86_64-linux-gnu/ld-2.27.so /lib/x86_64-linux-gnu/ld-2.27.so ; map._lib_x86_64_linux_gnu_ld_2.27.so._rw`_
`0x00007fb62be43000 # 0x00007fb62be44000 - usr     4K s -rw- /lib/x86_64-linux-gnu/ld-2.27.so /lib/x86_64-linux-gnu/ld-2.27.so`
`0x00007fb62be44000 # 0x00007fb62be45000 - usr     4K s -rw- unk5 unk5 ; map.unk1._rw_`
`0x00007ffd92685000 # 0x00007ffd926a6000 - usr   132K s -rw- [stack] [stack] ; map._stack_._rw_`
`0x00007ffd9270c000 # 0x00007ffd9270f000 - usr    12K s -r-- [vvar] [vvar] ; map._vvar_._r__`
`0x00007ffd9270f000 # 0x00007ffd92711000 - usr     8K s -r-x [vdso] [vdso] ; map._vdso_._r_x`
`

I've added some debug messages on the attempt, and all looks good before r_io_read_at call:

`[0x5568e8ec16d0]> dmh`
`libc_ver_end: /lib/x86_64-linux-gnu/libc-2.27.so` 
`is_debug_file[0]: 0`
`is_debug_file[1]: 0`
`is_debug_file[2]: 0`
`is_debug_file[3]: 1`
`is_debug_file[4]: 0`
`is_debug_file[5]: 0`
`Option 2`
`Option 3`
`[r_io_read_at]`
`not in io->va`
`io->ret: 0 / len : 256`
`s->name: .note.gnu.build-id`
`s->vaddr: 624 (\x0270) ---> OK`
`in io->va`
`[r_io_vread_at] RIO* io: 0x55bb3c531710`
`[r_io_vread_at] io->ff: 1`
`[r_io_vread_at] all to FF`
`[onIterMap_wrap] return true`
`io->ret: 0 / len : 20`
`r_io_read_at exit code: 1`
`buf[ 20 ] = ffffffffffffffffffffffffffffffffffffffff`
`Path: /usr/lib/debug/.build-id/ff/ffffffffffffffffffffffffffffffffffffff.debug`
`Warning: glibc library with symbol main_arena could not be found. Is libc6-dbg installed?`

`$ objdump -h -j .note.gnu.build-id /lib/x86_64-linux-gnu/libc-2.27.so`

`/lib/x86_64-linux-gnu/libc-2.27.so:     file format elf64-x86-64`

`Sections:`
`Idx Name          Size      VMA               LMA               File off  Algn`
`  0 .note.gnu.build-id 00000024  0000000000000270  0000000000000270  00000270  2**2`
`                  CONTENTS, ALLOC, LOAD, READONLY, DATA`

`$ objdump -s -j .note.gnu.build-id /lib/x86_64-linux-gnu/libc-2.27.so`

`/lib/x86_64-linux-gnu/libc-2.27.so:     file format elf64-x86-64`

`Contents of section .note.gnu.build-id:`
` 0270 04000000 14000000 03000000 474e5500  ............GNU.`
` 0280 43535324 37255656 47dab729 45c7c581  CSS$7%VVG..)E...`
` 0290 42a4fae7                             B...            `
`

But `r_io_read_at` is always putting \xfffffff... in the buffer...

On the other hand `gdb` gets it right:
`Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/43/5353243725565647dab72945c7c58142a4fae7.debug...done.`
`done.`

`$ ll /usr/lib/debug/.build-id/43/5353243725565647dab72945c7c58142a4fae7.debug`
`-rw-r--r-- 1 root root 4756720 Mar  9 21:48 /usr/lib/debug/.build-id/43/5353243725565647dab72945c7c58142a4fae7.debug`

Any help?
Thanks in advance.

**Comment by ret2libc** [comment]
Could you try this again? I think it should be fixed. If it is not however, feel free to re-open the issue, but please do attach a binary to reproduce. Thanks again for your issue!
