### ISSUE TITLE
jump target shortcut not working for branch instructions other than beq/bne in MIPS

### ISSUE THREAD

**Issue by ambrosehua** [radareorg/radare2#9821]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux/x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | MIPS/MIPS64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0 
### Expected behavior
shortcut for branch/jump instruction should work as the immediate field in instruction suggested
### Actual behavior
Under Visual Mode, the shortcut(like [1]) for branch  instruction(jalr/jr, bltzal/bgez.etc) other than beq/bne/b is not as expected, but offset zero
### Steps to reproduce the behavior 
r2 -AA  <elf for mipsel/mips64el>

press V

press P

press shortcut for jalr or bltzal, jump to offset zero, not the offset that the instruction suggested
### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
Is this a bug in capstone? Can you provide a sample binary or a testcase with any of the bins of the suite? Also, you should be able get that information with the command ao~jump, which is the destination of the jump

**Comment by radare** [comment]
Also, jr, jalr... are jump to register, so that wouldnt work because the register value is not taken into account with the current shortcut code. This and jumo table handling would be good additions for this. Please confirm the ao output for those non reg branchs

**Comment by ambrosehua** [comment]
[ld-2.20.so.gz](https://github.com/radare/radare2/files/1886210/ld-2.20.so.gz)
check bltzal @ 0x00002e34

ao~jump is 0xa;

**Comment by ambrosehua** [comment]
check ld-2.20.so, “jalr/ t9”@ 0x00002e48 should be different than other case.

Since radare2 can tell that ld t9, -sym._dl_start(gp) @0x00002e40 is load t9 with target address _dl_start from GOT, it should give shortcut @ 0x00002e48 a valid target

**Comment by ambrosehua** [comment]
I think it is not a a bug of Capstone, since the radare2 can tell aav from bltzal@0x00002e34 


|              ; DATA XREF from 0x00019b7c (sym.dl_open_worker)                                                                                                                  
|           0x00002e30      288088df       ld t0, -aav.0x00002e3c(gp)    ; [0x37028:4]=0x2e3c aav.0x00002e3c                                                                     
|           0x00002e34      01001005       bltzal t0, aav.0x00002e3c   ;[2]                                                                                                      
|           0x00002e38      00000000       nop                                                                                                                                   
|           ;-- aav.0x00002e3c:                                                                                                                                                  
|              ; UNKNOWN XREF from 0x00037028 (section_end..data + 24)                                                                                                           
|           0x00002e3c      2f40e803       dsubu t0, ra, t0

**Comment by ambrosehua** [comment]
Oops，I think it is a bug of Capstone
the imm(0) returned from bltzal is wrong, while imm(0) returned from bal is (addr + (short)offset<<2)
