### ISSUE TITLE
introduce a mailing list for questions/help

### ISSUE THREAD

**Issue by ret2libc** [radareorg/radare2#9851]
# Existing communication channels<a id="sec-1"></a>

Right now we have mainly 2 communication channels, which are IRC/telegram and GitHub. The former is mainly used for real time communication, small chats and requiring help live. The latter is used for dealing with issues, bugs, Pull Requests, questions, ideas, etc.

# Problems<a id="sec-2"></a>

## IRC/Telegram<a id="sec-2-1"></a>

-   many questions are asked here, but people don't always have time to answer in real time. Messages get often lost between all the other messages and people either don't get answer or need to post again and again the same question to get somewhat of an answer.
-   it is used from time to time do discuss general improvements, discuss design choices and ideas, but it has the problems that people don't always stay connected all day, they have different time zones, can't reply right away, etc.

## GitHub<a id="sec-2-2"></a>

-   contains a lot of issues and PRs. Issues contain bugs, feature requests, questions and design discussions. Although GitHub is ideal to talk about bugs, precise feature requests and PRs, it is not that good (IMHO) for questions, discussions and design choices, because you cannot easily see which messages you already saw, you are not notified when interesting questions arise and when you want to discuss stuff, you often have to ping people multiple times on IRC/Telegram to request their contribution (otherwise they would probably miss the new issue)

# Proposed solution<a id="sec-3"></a>

Create a mailing list used mainly for asynchronous help, questions, design choices and feature requests discussions. In this way it would be much easier to reply to parts of a message, see which messages were already seen and which not, get notified when a new question comes (you would just receive a new email). Moreover, I think this is a much better workflow for long discussions where multiple people opinions are required. Nowadays these things happen usually on IRC and if one is not connected/available at that moment, he just misses the discussion and it doesn't have a chance to say his opinion. Those discussions that happen on GitHub don't have a lot of traction and have few answers.

Examples where a mailing list email would make sense:

1.  <https://github.com/radare/radare2/issues/9849>
2.  <https://github.com/radare/radare2/issues/9840>
3.  <https://github.com/radare/radare2/issues/9798>
4.  <https://github.com/radare/radare2/issues/9378>
5.  <https://github.com/radare/radare2/issues/9286>
6.  <https://github.com/radare/radare2/issues/9624>
7.  many others

I think we could use Google Groups to create the mailing list and it should be easy.

Comments? Thoughts?

**Comment by radare** [comment]
It’s 2018.

**Comment by Maijin** [comment]
Terrible idea sorry but no.
