### ISSUE TITLE
move aetr command to extras

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#9865]
REIL is very limited, buggy, and never used by anyone in r2land. We should support RREIL, OpenREIL, or anything else that supports at least a common subset of ESIL features, otherwise i dont see a reason for having this in core, except for the ability to get an SSA representation which may be probably better to represent inside the disasm or esil

**Comment by XVilka** [comment]
RREIL is very different from the REIL, just a similar name, totally another beast. Just cut and move to extras.

**Comment by radare** [comment]
Agree
